### ISSUE TITLE
[São Paulo] Desenvolvedor Android | Ginga.One

### ISSUE THREAD

**Issue by Vivianematos** [androiddevbr/vagas#10]
## Local
Berrini - Zona Sul.

## Benefícios
frigobar sempre cheio :P
sala de jogos
Para CLT: 
Assistência Médica
Odontológica
Vale Refeição
Vale Transporte

## Requisitos

Obrigatórios
Grande conhecimento do SDK do Android.
Grande conhecimento das principais libraries, v4 e v7.
Consumo de API rest .
Usar Android Studio.
Usar Git.
Trabalhar com metodologia Scrum.

Desejável
Conhecimento sobre os novos padrões do Material Design.

## Contratação

PJ e CLT

## Nossa empresa

Aqui na GingaOne somos um grupo de profissionais extremamente qualificados, dedicados e apaixonados pelo que fazem, que acreditam no poder transformador da tecnologia e que querem deixar sua marca neste admirável mundo novo. 

## Como se candidatar

Por favor envie um email para viviane.matos@gingaone.com com seu CV anexado com Pretensão PJ e CLT. - enviar no assunto: Vaga Android

**Comment by Vivianematos** [comment]
GingaOne.

**Comment by walmyrcarvalho** [comment]
@Vivianematos Você tem alguma descrição da vaga? Acho que ia deixar mais completo pra quem tá procurando. :)

**Comment by Vivianematos** [comment]
Olá,

Essa vaga já foi finalizada.

Obrigada.

*Viviane Matos Bonifacio*
Recursos Humanos

+ 55 11 5505 2923
+ 55 11 97653-6975

Skype: viviane.bonifacio2
www.gingaone.com


2016-04-12 23:33 GMT-03:00 Walmyr Carvalho <notifications@github.com>:

**Comment by walmyrcarvalho** [comment]
@Vivianematos Ok. Fechando então.
