### ISSUE TITLE
[Campinas, SP] Desenvolvedor Mobile / Android Pleno - CPS

### ISSUE THREAD

**Issue by andremilanez1986** [androiddevbr/vagas#100]
## Descrição da vaga

Algum DEV mobile Android afim de um novo desafio? vamos conversar?
Requisitos Obrigatórios: 5 anos ou mais de experiência com Android Websockets e APIs

## Local

Campinas - SP

Importante: faremos alguns testes para equiparar o conhecimento na entrevista. 

## Contratação

CLT + Benefícios

## Nossa empresa

Confidencial

## Como se candidatar

Enviar o CV para o email andrermilanez@gmail.com

**Comment by walmyrcarvalho** [comment]
@andremilanez1986 Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by andremilanez1986** [comment]
Pode fechar, obrigado. Não recebi nenhum CV deste canal.

Obg

*Andre Milanez+5519981936576*
