### ISSUE TITLE
[Rio de Janeiro | São Paulo] Desenvolvedor Android [SENIOR] | Telecine

### ISSUE THREAD

**Issue by EduardoViegas** [androiddevbr/vagas#1000]
## Descrição da vaga

  O Telecine está buscando Desenvolvedor(a) Android com ampla experiência e que seja capaz de criar excelentes experiências de uso.
  
  Estamos numa fase de transformação digital na empresa, para isso estamos buscando os melhores e mais engajados desenvolvedores para nos ajudar nessa missão.
  
  Aqui você participará da construção do nosso principal app, podendo impactar o dia a dia de centenas de milhares de usuários.

## Local

• Escritório Rio de Janeiro - Barra da Tijuca (preferencial) - Podendo haver ajuda com realocação.
• Escritório São Paulo - Jardins

## Oferecemos

Pacote atrativo de remuneração + benefícios

## Responsabilidades

• Construir o nosso produto core de streaming de vídeos
• Criar aplicações com experiências incríveis, escaláveis e performáticas
• Ajudar na melhoria contínua da nossa performance e método de trabalho
• Colaborar com outras áreas da empresa ajudando na definição de hipóteses data driven

## Requisitos

Obrigatórios

• Experiência trabalhando em times usando metodologias ágeis (Kanban, Scrum etc.)
• Experiência em diferentes arquiteturas (MVP / MVVM etc.)
• Experiência desenvolvendo testes automatizados
• Conhecimento avançado em Kotlin
• Estar familiarizado com as bibliotecas mais usadas no mercado
• Profundo conhecimento nas melhores práticas de UI e UX para aplicativos mobile
• Capacidade de escrever código com boa qualidade e legibilidade

Desejáveis

• Conhecimento em pipelines CI/CD de apps Android

Diferenciais

• Experiência desenvolvendo para Android TV
• Ter trabalhado com streaming de videos

## Contratação

CLT

## Nossa empresa

Telecine é um hub de cinema. Joint venture da Globo e dos maiores estúdios de Hollywood, reúne mais de 2000 filmes, dos mais variados gêneros, selecionados a partir de uma curadoria especializada e comprometida, que alia tecnologia e inovação para promover a melhor experiência.
 
Pela internet, a plataforma de streaming é a única dedicada exclusivamente ao cinema. Lançamentos e clássicos de grandes estúdios de Hollywood, nacionais e do mercado independente compõem o acervo mais completo de filmes. Líder de audiência na TV paga no Brasil, reúne em seis canais lineares segmentados por gêneros as produções que o público quer ver. Pela internet ou na TV, Telecine proporciona o seu momento cinema quando e onde você quiser.

## Como se candidatar

Envie um email com seu LinkedIn (atualizado) ou CV para emagalhaes@telecine.com.br com o assunto: Vaga Android - [Estado da sua escolha]
Ou me mande uma mensagem no LinkedIn: https://www.linkedin.com/in/eduardoviegas/

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
