### ISSUE TITLE
[Rio de Janeiro | São Paulo] Desenvolvedor(a) Mobile (Mobile Platform) | OLX Brasil

### ISSUE THREAD

**Issue by felipehjcosta** [androiddevbr/vagas#1001]
#Desapega do mesmo e venha fazer parte da empresa de tecnologia que empodera milhões de brasileiros para realizar sonhos e que está mudando a forma de consumo da sociedade sendo a maior representante de economia compartilhada do país. 

E para fazer acontecer, buscamos pessoas que acreditem no nosso propósito, que tenham paixão por desafios e estejam dispostas a fazer nossos usuários sorrir. Para assim somar à nossa equipe multidisciplinar de talentos incríveis que nos inspira todos os dias.

## Descrição da vaga

Nossa missão é melhorar a experiência de nossos usuários nas plataformas mobile Android e IOS através de ferramentas e frameworks que permitam os desenvolvedores da OLX criarem produtos em nossos apps com agilidade, qualidade e segurança.

### Quer saber sobre as atividades a serem desenvolvidas?

- Manter e evoluir nossa arquitetura mobile saudável, criando boas práticas e guidelines horizontais;
- Garantir que os times de produto contribuam de forma fluida nessa arquitetura, sendo guardião da separação das lógicas de negócio das demais;
- Evoluir os pipelines automatizados do Android e iOS;
- Evoluir ferramentas de build, teste, release e performance;
- Profunda curiosidade para aprender novas tecnologias, explorar novas idéias e paixão por implementá-las;

## Local

- Flamengo - Rio de Janeiro/RJ 
- Avenida Paulista - São Paulo/SP

## Benefícios

- Escritórios divertidos e sustentáveis que estimulam a criatividade e autonomia;
- Pacote salarial competitivo;
- PLR, conforme política da empresa;
- Vale Refeição e/ou Vale Alimentação para você se alimentar muito bem;
- Vale Transporte;
- Plano de saúde e odontológico para você, cônjuge e filhos;
- Auxílio Creche;
- Gympass para te ajudar nas metas de vida saudável;
- Previdência privada;
- Lanchinhos disponíveis ao longo do dia;
- Clube de descontos OLX, com parcerias em restaurantes, hotéis e demais serviços;
- Dresscode: seja você!

## Requisitos

Obrigatórios
- Experiência como engenheiro de software mobile, tendo aprendido e trabalhado com mais de uma stack de Objective-C e Swift no iOS, Java e Kotlin no Android ou plataformas híbridas como React Native e Flutter;
- Sólidos fundamentos em Ciência de Computação/Informática;
- Entendimento de processos/boas práticas de Engenharia de Software;
- Capacidade analítica/raciocínio lógico (problem solving/algoritmo);
- Conhecimento em metodologias ágeis e práticas ágeis (TDD, pair programming, CI, CD)
- Forte senso de ownership e iniciativa para corrigir problemas e otimizar sistemas dentro e fora da sua área de responsabilidade;
- Disposição e otimismo para tentar novas idéias; capacidade de se adaptar rapidamente e aprender com os erros e com outros membros da equipe;
- Conhecimentos de SOLID e arquitetura de software;
- Conhecimentos de testes (Testes unitários, teste de integração e testes de interface);
- Ciclo de vida de uma aplicação mobile e na loja em produção;

Diferenciais
- Projetos opensource

## Contratação

CLT Full

## Nossa empresa

Na OLX acreditamos que é a sua diferença que nos conecta com milhões de brasileiros todos os dias, e aqui você tem a liberdade de ser quem você é. Para nossas vagas não fazemos distinção de raça, nacionalidade, identidade de gênero, necessidades especiais e demais especificidades.
Achou que essa é essa a oportunidade que tem o match perfeito com você? Se candidate :) 

## Como se candidatar

https://www.linkedin.com/jobs/view/1621771035/

**Comment by tiagocasemiro** [comment]
Esse link nao funciona mais. Existe outra forma de se candidatar?

**Comment by felipehjcosta** [comment]
Olá @tiagocasemiro,

A gente conseguiu fechar o time e fechamos a vaga como consequência.

Em algum momento no futuro vamos reabrir a vaga novamente. Sugiro você enviar o seu linkedin para o meu e-mail felipe.costa@olxbr.com para entrar na fila quando a vaga for aberta novamente!

Obrigado
