### ISSUE TITLE
[São Paulo,SP] Desenvolvedor Android [SENIOR] | BIONEXO

### ISSUE THREAD

**Issue by jehroma** [androiddevbr/vagas#1002]
## Descrição da vaga

Estamos iniciando o projeto de desenvolvimento das nossas plataformas em versão mobile. As nossas plataformas funcionam como um Marketplace ajudando as instituições de saúde a serem mais eficientes e reduzirem custos, dessa forma impactamos + 83 milhões  de atendimento/ano. E, agora levaremos as nossas plataformas e todos os seus benefícios para as mãos dos nosso usuários, trazendo mais facilidade e modernidade para toda a cadeia de suprimentos.

## Local:
São Paulo - Vila Olímpia

## Benefícios:
VR e/ou VA, VT/Estacionamento/ Ônibus Fretado,Assistência Médica e Odontológica, Seguro de Vida;
Gympass,Clube de Desconto,Auxilio Creche,Licença Maternidade e Paternidade estendida.
Também oferecemos: Horário flexível e Bônus anual

## Requisitos:

Obrigatórios:
•	Sólidos conhecimentos e habilidades em algoritmos e estruturas de dados;
•	Experiência comprovada com Kotlin;
•	Experiência com  os principais frameworks do Android;
•	Ter domínio de engenharia de software, princípios, boas praticas e padrões de arquitetura;
•	Experiência com testes automatizados;
•	Gerenciamento de dependências;
•	Experiência com REST APIs;
•	Ferramenta de controle de versão (Git);
•	Mindset de agilidade;

Desejáveis
•	Conhecimentos de automação de publicação de aplicações (fastlane, etc);
•	Conhecimento do processo de publicação de um aplicativo;
•	Desenvolvimento de SDK;
•	Visão de UI/UX, seguindo Material Design.
## Contratação
CLT

## Nossa empresa
A Bionexo é uma empresa multinacional que se propõe a transformar a gestão de saúde por meio da tecnologia. Fazemos isso através de nossos produtos que entregam mais eficiência, transparência e inteligência para Hospitais, Clínicas, Fornecedores, Indústria e outros agentes do setor, sejam eles públicos ou privados. Transacionamos +10 Bilhões de reais através de nosso marketplace, ajudando as instituições de saúde a serem mais eficientes e reduzirem custos - por ano são +500 milhões de reais economizados para o setor no Brasil. Nossos clientes representam 38% dos leitos do País e, dessa forma, impactamos +83 milhões de atendimentos/ano!

## Como se candidatar
Por favor, faça a sua inscrição no seguinte link: https://jobs.kenoby.com/sejaumbiolover/job/desenvolvedor-a-android/5d1b76ecf9f83d48f9c68882

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
