### ISSUE TITLE
Android Developer

### ISSUE THREAD

**Issue by Julianapessoto88** [androiddevbr/vagas#1004]
## Descrição da vaga
Atuação com desenvolvimento de app utilizando Kotlin e/ou Java.

## Local
Campinas/SP - Atuação na Dextra

## Benefícios

Pacote de benefícios flexíveis, PLR, Auxílio Creche, horários flexíveis

## Requisitos
Você curte tecnologia e quer novos desafios? Queremos te conhecer!
O que você precisa saber para esta vaga?

Programar.. Mas com paixão!
Ser crític@ em relação à qualidade de código;
Ter experiência com Android (Java / Kotlin); 
Ser colaborativ@ e gostar de trabalhar em equipe! 

Seria legal se você:
Já tiver trabalhado com metodologias ágeis.

Aqui você pode ser você mesm@!  
Fazemos questão de ter diferentes perfis atuando com a gente. Nós enfatizamos a diversidade e tratamos com equidade e respeito todos os nossos colegas independentemente de gênero, orientação sexual, raça, idade, nível sócio econômico ou qualquer outra característica individual.

#VemPraDextra \o/

## Contratação

CLT

## Como se candidatar

Enviar CV ou link do linkedin para: recrutamento@dextra.com.br

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
