### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android JUNIOR/PLENO/SENIOR | FastShop

### ISSUE THREAD

**Issue by GibranLyra** [androiddevbr/vagas#1008]
## Descrição da vaga

Somos um time bem unido e queremos manter o máximo de qualidade no nosso desenvolvimento, somos abertos a novas tecnologias e estamos melhorando nosso code base cada dia.
Aqui você vai ter a responsabilidade de direcionar o produto para criar a melhor experiência possível para o consumidor final.

## Local

Escritório São Paulo - Santana

## Benefícios

• Horário flexível
• Área de descompressão (ping-pong, pebolin, puffs)
• Plano de Saúde
• Plano Odontológico
• Vale Refeição
• Vale Transporte
• No Dress Code

## Requisitos

Obrigatórios
- Confortável com padrão MVP, MVC, MVVM e derivados
- Retrofit
- Rxjava
- ConstraintLayout

Desejáveis
- Experiência com Espresso e Unit tests
- Experiência com DI
- Experiência com ecommerce

Diferenciais
- Projetos opensource

## Contratação

CLT/PJ

## Nossa empresa

Cuidar do cliente por toda a vida é a missão que norteia a Fast Shop desde 1986, quando a rede de eletrodomésticos e eletroeletrônicos iniciou suas atividades, ainda como concessionária e assistência técnica de motocicletas e equipamentos de transporte aquático.

Mais de 30 anos depois, a empresa expandiu essa essência e, apoiada em uma estratégia multicanal, se tornou referência no mercado premium de eletrodomésticos e eletroeletrônicos.

São mais de 100 lojas em todo o País - São Paulo, Rio de Janeiro, Bahia, Distrito Federal, Goiás, Minas Gerais, Paraná, Rio Grande do Sul, Pernambuco e Ceará; 11 centros de distribuição; Mais de 5 milhões de visitantes por mês em seu e-commerce, e mais de 5 mil funcionários.

Para garantir a satisfação, conveniência e a comodidade de seus clientes, a empresa tem como diferencial o atendimento ao consumidor, serviços personalizados e produtos exclusivos, além da integração entre varejo físico e on-line, com comunicação integrada em todos os canais de venda. E é fundamental citar o serviço Ultra Fast, estabelecido como um dos serviços de entrega mais rápidos do País. Focado em produtos de pequeno porte, o serviço da Fast Shop entrega os produtos em até duas horas.

## Como se candidatar

Por favor envie um email para hsuzuki@2bchosen.com com e tgibrangl@fastshop.com.br seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
