### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor Android | Fractal Engenharia e Sistemas

### ISSUE THREAD

**Issue by gustavo-gomes-ghg** [androiddevbr/vagas#1010]
## Descrição da vaga

Você irá trabalhar diretamente no desenvolvimento do DAMS App, que é um aplicativo que realiza campanhas de inspeção de segurança de Barragens. Nossos clientes esperam uma experiência suave, de fácil manuseio e livre de bugs. Estamos em uma batalha criativa para entregar uma qualidade incrível para nossos clientes.

## Local

Escritório Florianópolis - Trindades/UFSC

## Benefícios

- - VT, VA e Plano de Saúde

## Requisitos

- Ter proatividade e disciplina, além de ter comprometimento e dedicação com os ambientes de desenvolvimento, homologação e de produção
- 2+ anos de experiência com Android API level 16+
- Habilidade em Java, desenvolvimento em Android SDK e Android Studio
- Experiência com design de layouts em xml;
- Experiência com comunicação usando o padrão Restful;
- Entendimento do ecossistema Android e ciclo de vida das Activities;
- Experiência em configuração de arquivos gradle;
- Atletismo mental: Ser analítico e ter intelecto curioso
- Boa comunicação: Habilidade para articular problemas técnicos e projetos para todos da equipe
- Iniciativa e pensamento crítico. Nada é impossível, pois para tudo existe um jeito de fazer
- Experiência com lançamento de aplicativos em diferentes versões no Google Play Console;
- Experiência com SQL sintax e Sqlite;

## Tecnologias que usamos

- Java, SQLite, PostgreSQL
- PHP Symfony com Doctrine
- Python, Matlab, e Bash

## Nossa empresa

Somos uma empresa atuante em Engenharia de Segurança de Barragens, otimização de geração elétrica e previsão de inundação de rios. Desenvolvemos 3 produtos que fazem a integração entre estes serviços: DAMS App, SPEHC e SIGA. Em 2019 recebemos investimento da EDP Venture para impulsionar o desenvolvimento dos produtos e serviços da empresa e neste momento estamos contratando equipe para isso. Somos uma empresa pequena, de 15 a 20 funcionários e nos localizamos próximo à UFSC, na região central de Florianópolis. Nosso propósito é ter uma profunda inteligência sobre a dinâmica da água no mundo, transformando dados em melhoria operacional. 

## Contratação

- CLT

## Salário

R$ 5000,00

## Como se candidatar

Por favor envie um email para gustavo@fractaleng.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
