### ISSUE TITLE
Desenvolvedor (a) Android

### ISSUE THREAD

**Issue by Approvata** [androiddevbr/vagas#1013]
Empresa
Especializada em contratação de talentos de TI e Design Cultural para empresas que desejam aumentar os resultados de seus negócios, através de talentos, competências e habilidades conectamos o desempenho empresarial com as necessidades humanas.

Nosso Cliente - é um banco digital de investimentos.

Descrição da vaga

•Trabalhar com diferentes dimensões de dispositivos (Tablet, celular e afins);

•Trabalhar realizando testes, code-review, integração continua e afins;

-BDD e TDD. Trabalhar com pullrequest, promovendo um code-review constante;

•Trabalhar com times multidisciplinares (PO, UX, UI e Desenvolvedores);

•Desenvolvimento incremental “Comece pequeno e entregue de forma constante”.

•Acompanhar todas as entregas avaliando o impacto que as mudanças ocasionaram na relação com os nossos clientes.

Posição
Pleno/Sênior

Tipo de contratação
Presencial, Alocado, PJ

Requisitos
•Superior completo em Ciências da Computação, Engenharia, Sistemas da Informação ou áreas afins.

•Experiência com aplicativos em Android nativo, no mínimo 2 anos;

•Android SupportLibrary;

•Experiência em Material Design;

•Experiência com GIT;

•Experiência com Java;

•Conhecimento com Google Play Services;

•Ter trabalhado com API Level14

•Conhecimento de padrões de arquitetura: MVP, MVVM.

Como aplicar
Primeiro é realizado um call do candidato para validar os conhecimentos, pode ser por Skype ou telefone. Estando aderente (vide requisitos da vaga), encaminhamos ao Cliente que fará uma entrevista técnica e tirará todas as dúvidas referente a atuação.
Aceitamos candidatos de outros estados que estejam disponíveis para mudança.

Contato
Email: maria.carvalho@approvata.com.br

**Comment by davidtcdeveloper** [comment]
@Approvata as regras do nosso mural de vagas exigem a divulgação da empresa contratante. Vou encerrar a vaga, pedimos que editem a vaga com o nome e nos avisem para que ela seja reaberta.
