### ISSUE TITLE
[SP-São Pualo] Desenvolvedor(a) Android na Guiabolso

### ISSUE THREAD

**Issue by iagobyintera** [androiddevbr/vagas#1014]
**É tudo do início!** Estamos desenvolvendo novos produtos e para isso buscamos a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Por conta disso nós já **reduzimos mais de  R$500 milhões em gastos** dos brasileiros por ano. Apesar de estamos no início, começamos com tudo!

Atualmente nós trabalhamos principalmente com **Kotlin**, além disso estamos utilizando AWS, com **espaço para aprender muito** também. Essas tecnologias com **pessoas de propósito, dispostas e autonomia de ponta a ponta** é o que nos faz crescer exponencialmente!

A contratação será feita em regime CLT com trabalho de forma presencial, **ficamos na Pinheiros**, a **400 metros do metrô** da Faria Lima.

**Página da vaga para inscrição:** http://byintera.in/vemserguiabolso (preencher formulário na página)

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
