### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Android [PLENO] | Zero Um Digital

### ISSUE THREAD

**Issue by feliperezende** [androiddevbr/vagas#1015]
## Descrição da vaga
A 01 Digital é uma das maiores publishers e desenvolvedoras de aplicativos para iOS e Android do Brasil. Com mais de 50 milhões de downloads e presença constante entre os aplicativos mais populares.

Você será responsável por desenvolver, testar e aperfeiçoar aplicativos nas principais plataformas mobile. Atuará com um time de profissionais multi-disciplinares que estão sempre procurando as melhores soluções. 01 Digital se destaca no mercado de apps infantis e educativos como os da Galinha Pintadinha, Patati Patata, Palavra Cantada, Masha e o Urso, Os Pequerruchos, entre outros.

## Local

Pinheiros - São Paulo - SP - Próximo ao metrô Fradique Coutinho (Linha amarela)

### Responsabilidades

- Criação e manutenção de aplicativos e jogos mobile
- Prototipação e teste de novas funcionalidades
- Desenvolver código de qualidade

### Requisitos

- Conhecimentos de iOS (ObjC/Swift) ou Android (Java/Kotlin)
- Conhecimento em arquitetura de aplicativos mobile (MVC, MVP, MVVM) e testes unitários
- Conhecimento na utilização de Git
- Graduação em Ciência da Computação ou áreas relacionadas

### Diferencial

- Conhecimento em Unity 3D
- Aplicativos publicados
- Responsabilidade e senso de propriedade com os projetos

## Benefícios

- Vale Refeição
- Vale Transporte
- Assistência médica e odontológica

## Contratação
CLT

## Como se candidatar
Por favor envie um email para felipe@zeroum.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
