### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android [JUNIOR|PLENO] | Mobile2You

### ISSUE THREAD

**Issue by palomaveras** [androiddevbr/vagas#1016]
## Descrição da vaga

- Desenvolvimento de aplicativos Android utilizando Android Studio na linguagem Kotlin;
- Teste de funcionalidades desenvolvidas;
- Configuração de projeto no quesito versionamento, dependências e flavors/targets;
- Controle de versões utilizando BitBucket;
- Desenvolvimento paralelo e em equipe;
- Controle das tarefas a serem realizadas, assim como as em desenvolvimento, teste e concluídas, utilizando o software Jira;
- Fazer upload de aplicativos utilizando Fabric.

## Local

Escritório São Paulo - Oscar Freire

## Benefícios

- Remuneração compatível com o mercado;
- Plano de saúde;
- Vale refeição ou alimentação;
- Vale Transporte;
- Ambiente descontraído e informal;
- Academia Pinheiros 100% free;
- Frutas no escritório;
- Happy Hour;
- Diversas parcerias e descontos.

## Requisitos

Obrigatórios
- Experiência com linguagem Kotlin
- Experiência com Java

Diferenciais
- 1+ anos de experiência com Android
- Confortável com padrão MVP, MVVM e derivados

## Contratação

CLT ou PJ a combinar

## Nossa empresa

O foco da Mobile2you é o desenvolvimento de aplicativos para empresas e empreendedores, utilizando as plataformas iOS e Android.
Somos uma startup com pessoas apaixonadas pelo que fazemos e principalmente pela tecnologia, estimulamos o crescimento profissional contínuo e utilizamos a metodologia ágil scrum e XP.

## Como se candidatar

Por favor envie um email para paloma.veras@mobile2you.com.br com seu CV anexado e pretensão salarial ou chamar no slack @paloma oliveira veras - enviar no assunto: Vaga Android
Link para a vaga: https://www.linkedin.com/jobs/view/1643292125/

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
