### ISSUE TITLE
[Lisboa, Portugal] Mobile Developer

### ISSUE THREAD

**Issue by TheFakeMontyOnTheRun** [androiddevbr/vagas#1017]
Join us as a Mobile Developer (iOS or Android) and you'll be part of a dynamic team that makes sure our technology delivers the best experience for our customers.We’re always looking to improve by developing pioneering products and services which give every one of our customers’ experiences they’ll love.Your Key Responsibilities:- Develop excellent quality software using agile techniques
- Design clean and reliable code
- Deliver highly scalable an highly reliable products (yes, our customers expect 99.999% availability)
- Collaborate with other developers, sharing and receiving knowledge
- Promote best technology and software development practices into the team with passion and enthusiasm
- Contribute to the whole development cycle, analysis, implementation, testing and operation  
- Operation excellence and support are part of the development teams’ responsibilityPreferential skills:- Development in languages such as Objective-C, Swift, Java or Kotlin
- Solid iOS or Android development experience
- Understanding of Design Patterns and Object Oriented Design
- Knowledge of iOS or Android App Architecture
- Experience working with Restful APIs
- Practical knowledge of network protocols and challenges with latency and reliability
- Demonstrable knowledge of coding involving multithreading, request queueing and caching
- Continuous Integration/Deployment tools and processes
- Ability to work well in a team, self-driven and eager to learn
- Creative thinking, analytical skills, with attention to detail
- Strong spoken English skills
- Lisbon based

CVs to diego.valente@sky.uk

**Comment by jpventura** [comment]
This issue was closed due inactivity.

If the job position is still available, please reply **_Vaga ainda está aberta_**.
