### ISSUE TITLE
[Remoto] Desenvolvedor(a) Android [SENIOR] | Invillia

### ISSUE THREAD

**Issue by Massita** [androiddevbr/vagas#1018]
### Local
Remoto

### Posição
 Desenvolvedor(a) Android Sênior

### Tipo de contratação
Atuação 100% Remoto 
Contratação CLT + Benefícios 

### Requisitos
Sólida experiência em desenvolvimento Mobile utilizando a plataforma Android;
Amplos conhecimentos em Java e Kotlin;
Integração de sistemas via REST Api;
Testes de interface e testes unitários;
Experiência em desenvolvimento e integração com aplicações utilizadas em larga escala com foco em performance e utilização racional de recursos;
Conhecimento em arquiteturas móveis como MVP, MVVM.

### Benefícios
Plano de Saúde
Plano Odontológico
Vale alimentação e/ou Vale refeição
Auxílio creche
Entre outros...

## Nossa empresa

A Invillia é uma empresa global que vem revolucionando a maneira como game-changers expandem o poder de inovar, 
implementar tecnologias de ponta e desenvolver novas estratégias, produtos e serviços digitais. 
Nenhuma outra empresa no mundo atua como a Invillia.
E o que torna nosso Global Growth Framework tão único e poderoso?
Primeiro, dissolvemos os limites entre o físico e o virtual para ter em nosso time os melhores talentos do planeta.
Criamos infinitas práticas e metodologias para que que cada squad seja super customizado e engajado na cultura e desafios de cada cliente.
Adoramos usar ferramentas ágeis, métricas, inteligência de dados no dia-a-dia. Para que ideias e melhorias se multipliquem. 
Mas acreditamos que é na educação contínua, na abordagem mais humana e colaborativa que a mágica acontece. 
Novas oportunidades surgem. E a inovação nunca para. Infinite Digital Power.

We are a Global Growth Framework connected by
developers, engineers, makers, and dreamers. 

## Como se candidatar

Interessados/ indicações, por favor, direcionar currículo para: gabrielly.leonel@invillia.com

**Comment by davidmagalhaes** [comment]
Olá, essa vaga ainda está disponível?

**Comment by Massita** [comment]
Bom dia! Verifiquei com o RH aqui, a vaga já fechou :(
Mas em breve deve abrir novas oportunidades! Vou fechar a issue, mas qdo tiver algo, acho que eles postam aqui! Valeu!
