### ISSUE TITLE
[Recife, PE] Android Mobile Developer | Mesa Inc.

### ISSUE THREAD

**Issue by renanoaraujo** [androiddevbr/vagas#1019]
## Descrição da vaga

Nosso time de Desenvolvimento Mobile está com vagas abertas para Desenvolvedor Android, para todos os níveis. Organização é nosso principal asset: buscamos alguém organizado, que tenha um bom raciocínio lógico. Não buscamos peões: queremos alguém que goste de resolver problemas e que encare grandes desafios.

Para fazer parte do nosso time, é importante que você seja desenrolado. Queremos pessoas que busquem aprimorar suas habilidades constantemente, que gostem de fazer cursos e participar de eventos e palestras. Você precisará ser comprometido com seu projeto, acima de tudo. 

Você também vai trabalhar juntamente com outras equipes de desenvolvimento para pensar nas melhores soluções para clientes e usuários. Nosso trabalho é colaborativo, por isso sempre consideramos as outras equipes e como podemos facilitar seu trabalho.

## Local

Presencial, Recife - Paço Alfândega Shopping

## Benefícios

- Vale Refeição
- Vale Alimentação
- Plano de Saúde
- Estacionamento
- Vale Transporte
- PLR
- Auxilio de cursos, workshops e palestras

## Requisitos

Obrigatórios
- Kotlin
- Experiência com Controle de versão (GIT)
- Conhecimentos em arquiteturas modulares (MVVM, MVP)
- Conhecimento de conceitos de desenvolvimento ágil (scrum)
- Inglês técnico

Desejáveis
- Inglês avançado
- Clean Code
- Android Jetpack
- Testes

Diferenciais
- Programação reativa

## Nossa empresa

Além dos nossos benefícios, eventos internos, lanchinhos e happy hours, somos um time que investe em pessoas. Queremos desenvolver você e que você tenha abertura para testar coisas novas e que não tenha medo de errar. Fomentamos um espaço de troca de conhecimento, por isso estimulamos cursos e formação. 

Também, você terá a oportunidade de trabalhar com grandes projetos e grandes clientes com bastante autonomia.

## Como se candidatar

Por favor preencha o formulário de inscrição no site: https://mesainc.jobs.recrut.ai/A3U4FO

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
