### ISSUE TITLE
[São Paulo] Desenvolvedor Mobile (Android ou IOs) - Avenue Code

### ISSUE THREAD

**Issue by ricardofluiz** [androiddevbr/vagas#102]
A Avenue Code é uma empresa norte-americana de tecnologia, focada em metodologias ágeis, situada próximo a avenida paulista (Luis coelho / Bela Cintra).

Com mais de 250 funcionários distribuídos entre Brasil e EUA, estamos sempre em busca de profissionais qualificados e apaixonados pelo que fazem!

Quer motivos para ser um Avenue Coder?

- Fomos premiados como uma das melhores empresas para se trabalhar (prêmio GPTW – 2015) e eleita segunda melhor empresa de TI para se trabalhar em 2016 segundo[ Exame / Lovemondays](http://exame.abril.com.br/carreira/as-10-melhores-empresas-de-tecnologia-para-trabalhar-em-2016/).

- Oportunidade de experiência internacional (São Francisco, Flórida e Nova Iorque)

- Atuação com modernas tecnologias

- Flexibilidade de horário

- Desenvolvimento do inglês (língua oficial da empresa)

- Acompanhamento de mentores com avaliações trimestrais sobre sua performance que lhe dará apoio para evolução na carreira

Entre outras coisas, nesta posição você terá a oportunidade de:

- Analisar, projetar, programar, depurar e modificar software

- Escrever código de programação completa e realizar testes e depuração de aplicações

- Interagir com os usuários para definir os requisitos de sistema e / ou modificações necessárias, bem como interagir com os interessados ​​para entender os requisitos para o desenvolvimento de aplicações

- Conceber, construir e entregar soluções enxutas, escaláveis, seguras e de fácil manutenção

- Escrever e revisar documentação técnica, incluindo design/UX, desenvolvimento e código-fonte

- Analisar, revisar e modificar software para aumentar a eficiência operacional de nossos sistemas

Para isso, é necessário que você tenha (Ios):

- Experiência com desenvolvimento Móvel, tais como iOS SDK, Objective C, Cocoa, xcode IDE e REST/JSON

(Android):

- Domínio da plataforma Java e frameworks de desenvolvimento de sistemas Web (back end)

- Experiência no uso de tecnologias baseadas em Android, Android SDK e Android studio

- Conhecimento de estruturas com Apis Google

(Ambos):

- Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados

- Experiência de desenvolvimento de sistemas em ambientes distribuídos, escaláveis e de alta disponibilidade

- Sólidos conhecimentos em aplicações que atuam tanto como produtores quanto clientes de serviços RESTful

- Familiaridade com NodeJS será um diferencial

- Conhecimento de automação de testes: unitários, funcionais ou testes de integração

- Experiência em controle de versionamento com Git (desejável)

- Vivência com um ou mais métodos ágeis de desenvolvimento: XP (principalmente as práticas de pair programming e TDD), Scrum e Kanban

- Inglês avançado

Se identificou? Então, envie seu currículo agora para ricardofluiz.vagas@gmail.com

PS.: Serão aplicados testes técnicos e de inglês (remoto), então você deve dispor de tempo para participar dos testes se quiser concorrer as vagas :)

**Comment by walmyrcarvalho** [comment]
@ricardofluiz Ricardo, a vaga é pra São Paulo, capital?

Sobre a vaga, o ideal é focarmos em vagas somente pra Android, ok? Se possível, peço que ajuste a descrição para refletir isso. :)

**Comment by ricardofluiz** [comment]
Ola, eh a primeira vez que estou postando uma vaga, então fiquem a vontade para me corrigir se não segui algum padrão.

Sim, vagas são para SP próximo a avenida paulista (Luis coelho / Bela Cintra).
Como temos ambas as vagas posso colocar vaga IOs ou Android? na descrição esta detalhado o que e esperado de um dev android, de um dev Ios e de ambos...
Normalmente quem trabalha com Android tem algum amigo ou pessoa na mesma equipe que trabalha com Ios e pode se interessar pela vaga.
Mas se mesmo separando os temas na descrição vocês acharem que fica ruim eu apago a parte de Ios.

**Comment by walmyrcarvalho** [comment]
@ricardofluiz Esse repositório é específico pra vagas de Android, caso queira divulgar vagas de iOS recomendo você jogar aqui: https://github.com/cocoaheadsbrasil/vagas/issues

**Comment by walmyrcarvalho** [comment]
Ah, é possível você ajustar a descrição pro template sugerido? Lá tem informações relevantes (contratação, contato, etc) numa formatação mais padronizada. :)
