### ISSUE TITLE
[Curitiba, PR] Desenvolvedor(a) Android | Vega I.T.

### ISSUE THREAD

**Issue by heitorri** [androiddevbr/vagas#1020]
### Descrição da vaga
* Desenvolvimento de aplicações;
* Implementação de soluções inteligentes com código limpo;
* Executar a manutenção dos sistemas, fazendo eventuais correções necessárias e melhorias de performance, visando acompanhar as mudanças e atender as necessidades dos usuários;
* Atuar na implementação de novos recursos em aplicações já desenvolvidas.

### Local
Curitiba - PR

### Benefícios
* Horário flexível;
* Café fresquinho à vontade;
* Barbecue + Happy Hour mensal;
* Quick Massage;
* Gympass;
* Beauty Day com barbearia e manicure;
* Inglês In Company;
* Auxílio para cursos e palestras;
* Plano de Saúde;
* Plano Odontológico;
* Refeição no local;
* Vale-transporte.

### Requisitos
* Experiência de 1 ano em desenvolvimento utilizando Java ou Kotlin; 
* Experiência em consumo de WebServices REST; 
* Experiência em Git;
* Capacidade de aprender rapidamente tecnologias emergentes mediante ao consumo de documentação técnica; 
* Conhecimento sólido em programação orientada a objetos;
* Experiência em metodologias de desenvolvimento ágil.

### Contratação
CLT

### Como se candidatar
Enviar currículo para: rh@vegait.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
