### ISSUE TITLE
[São Paulo, SP] Pessoa Desenvolvedora Android | ThoughtWorks

### ISSUE THREAD

**Issue by RecrutamentoThoughtWorks** [androiddevbr/vagas#1021]
## Descrição da vaga
Estamos procurando uma Pessoa Desenvolvedora Mobile - Android para trabalhar em projetos desafiadores, entregando a melhor solução para os objetivos de clientes. Esta pessoa terá a oportunidade de trabalhar com práticas de desenvolvimento ágil, incluindo padrões de projeto, refatoração, integração contínua e TDD (Test Driven Development). 

## Local
São Paulo, SP;
Brasil

## Benefícios
- Convênio Médico;
- Convênio Odontológico;
- Vale Transporte;
- Vale Refeição;
- Gympass;
- Auxílio-creche.

## Requisitos
- Pessoas apaixonadas e que possuam experiência no desenvolvimento de aplicações para plataforma Android;
- Experiência com desenvolvimento móvel - Kotlin;
- Experiência e entendimento de várias plataformas e ferramentas para desenvolvimento móvel;
-Que tenha participado do ciclo completo de entrega (concepção, desenvolvimento e implantação) de aplicativos móveis;
- Forte em design OO, incluindo conhecimento de padrões de projeto;
- Com bom entendimento de testes unitários, de integração, funcionais e de regressão automatizados para Android;
- Que tenham interesse ou experiência com metodologias ágeis;
- Habilidade para julgar e fazer escolhas de plataforma dado o contexto sobre um aplicativo em particular;
- Habilidade de trabalhar em clientes diversos em um ambiente colaborativo e voltado ao trabalho em equipe;
- Forte habilidade de comunicação e de lidar com clientes trabalhando em um ambiente de consultoria;

## Contratação
CLT

## Nossa empresa
Somos uma consultoria global de software e uma comunidade de pessoas apaixonadas por propósitos.
Nós pensamos de forma disruptiva para para fornecer tecnologia capaz de enfrentar os desafios mais difíceis dos clientes, ao mesmo tempo em que buscamos revolucionar a indústria de TI e criarmos um impacto social positivo.

## Como se candidatar
Para se candidatar basta acessar o link https://www.thoughtworks.com/jobs/2015065?gh_jid=2015065 e criar seu cadastro!

Boa sorte!

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
