### ISSUE TITLE
[Barcelona, Spain] Lead Android Engineer | FREE NOW

### ISSUE THREAD

**Issue by Clara-Marie** [androiddevbr/vagas#1025]
## Descrição da vaga

Our Android Chapter is made up of +10 skilful, resourceful and experienced engineers. We are looking for someone that knows how to represent the interests of the Chapter, whilst also removing barriers and improving the work process.

You will be responsible for the development of a high-quality and impactful product, capable to withstand our fast growth and evolution in our way to become the leading mobility platform in Europe. You will also act as a coach for your team in order to help them with their weaknesses and build on their strengths.

In the Barcelona tech hub, we build the supply products. This means that you will build the Android drivers’ app. Ensuring that all of our passengers can get a driver when needed is a crucial aspect of our success and majorly contributes towards our goal of becoming the no.1 mobility app in Europe. We are constantly creating a reliable and convenient app that drivers love to use, so in your role, you’ll work in an agile, interdisciplinary team very close to our Product Team.

Just to give you some insights of the complexity of this project, we have more than 100.000 drivers, dispatching tours for more than 14 million passengers and we are present in more than 100 cities, each with their own unique requirements (i.e. fees, laws or promotions).

**What you’ll do:**

- Act as a representative for the Chapter's interests
- Be a facilitator and keep the conversations focused
- Embrace the team’s development: both tech and non-tech
- Improve the working processes
- Maintain a cohesive and safe working environment

## Local

Barcelona, Spain

## Benefícios

- Intensive Fridays 
- Gym membership
- Flexible working hours and home office
- Quarterly team-building activities (karting, bowling, laser tag, escape rooms, barbecues/calçotades…)
- Yearly off-site hacking weeks
- Hacking days and occasional trips to our HQ in Hamburg
- Weekly free buffet breakfasts in the office
- Health insurance with basic dental coverage
- 25 days annual leave plus your birthday off, and 24th & 31st December off
- A monthly mobility allowance for free taxi rides
- The opportunity to use the latest technologies and implement your own ideas
- Flexible learning and development opportunities through internal and external workshops, events and conferences
- Free language lessons
- ...and all the usual start-up goodies like free fruit, unlimited drinks, after-work beers and many more!

## Requisitos

You’ll be a match if you are:

- Passionate about Android
- Good listener
- Mediator
- Trustworthy 
- Able to make decisions in a complex and changing environment 
- Good communicator (up and down)
- Not afraid of making mistakes
- Experienced in Kotlin, RxJava, MVP, Dagger/Dagger2, Retrofit2, gradle, mqtt & microservices

## Contratação

CLT

## Nossa empresa

FREE NOW was founded as mytaxi in June 2009 and was the world’s first taxi app that established a direct connection between a passenger and a taxi driver. In July 2019, mytaxi rebranded to FREE NOW as part of a global mobility brand family and set itself up as a multiservice mobility provider. With 14 million passengers and more than 100,000 drivers, FREE NOW is one of the leading ride-hailing providers in Europe. Since February 2019, the service is part of the FREE NOW group, the ride-hailing joint venture of BMW and Daimler. FREE NOW today works with more than 700 employees in 26 offices and is available in over 100 European cities. Eckart Diepenhorst is leading the operational business as CEO Europe of FREE NOW. More information is available at: www.free-now.com

## Como se candidatar

You can apply here https://grnh.se/4b8d3f831 or send an email to clara.wehber@free-now.com

**Comment by jpventura** [comment]
@Clara-Marie do you also offer relocation allowance?

**Comment by Clara-Marie** [comment]
@jpventura Yes, we do offer relocation allowance which includes visa sponsorship, flight costs reimbursement and 4 weeks of accommodation (for our new hire + family)

**Comment by jpventura** [comment]
This issue was closed due inactivity.

If the job position is still available, please reply Vaga ainda está aberta.
