### ISSUE TITLE
[Porto Alegre, RS] Desenvolvedor(a) Android | SOUTH SYSTEM

### ISSUE THREAD

**Issue by cmazoni** [androiddevbr/vagas#1026]
## Descrição da vaga

A SOUTH SYSTEM está em busca de um(a) Desenvolvedor(a) Android que queira fazer parte do nosso propósito de impulsionar as pessoas para inovar o mundo. Para fazer parte do time, há algumas skills que valorizamos muito, e não estamos falando apenas de tecnologia, nós valorizamos profissionais que respeitem o próximo e suas diferenças, que sejam leais e responsáveis com as entregas e com as pessoas. A colaboração e engajamento devem fazer parte do dia a dia para que o resultado seja eficaz e que tenha sede de aprendizado para trabalhar com inovação contínua.

## Local

Bairro Rio Branco, Porto Alegre

## Benefícios

- Boa localização
- Ótimos equipamentos
- Salário acima da média do mercado
- Fliperama

## Requisitos

- Kotlin;
- Arquitetura MVVM + Databinding;
- Injeção de dependências com Dagger 2;
- Retrofit;
- Testes unitários com Mockito + Robolectric;
- Testes funcionais automatizados;
- Integração Contínua;
- Deploy Contínuo;
- Clean Code;
- Estrutura modularizada e independente.

Desejáveis
-  Experiência com setup de projetos com Bitrise;
- Experiência com setup de projetos com Fastlane;
- Experiência com criação de bibliotecas Android;
- Experiência com GitFlow;
- Experiência com Analytics (Google Analytics, Fabric e MixPanel);
- Experiência com Crashlytics (Fabric);
- Experiência com processo de publicação na Play Store.

## Contratação

PJ ou Cooperado

## Nossa empresa

A SOUTH SYSTEM atua hoje principalmente no setor financeiro, desenvolvendo as melhores soluções para atender às demandas de seus clientes. Focamos muito no desenvolvimento de nossos profissionais, oferecendo cursos e treinamentos para impulsionar seu desenvolvimento!

## Como se candidatar

Envie um e-mail para claudia.mazoni@southsystem.co.br com a vaga no assunto e vamos marcar um café!

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
