### ISSUE TITLE
[Berlin, DE] Android Software Developer | GetYourGuide

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [androiddevbr/vagas#1027]
## Nossa empresa

A GetYourGuide é o melhor lugar para marcar atividades em seus destinos através do globo. Desde de 2009, nós fizemos milhões de viajantes acharem únicas e inesquecíveis experiências para fazer onde quer que seja que suas viagens os levem. A GetYourGuide lá levantou mais de US$ 650 milhões em funding e já tem mais de 600 de empregados em escritórios ao redor do mundo, mas mantendo uma cultura de trabalhar de startup.  

## Seus desafios

Desenvolver o aplicativo nativo de android é nossa missão e esperamos que você se junte a nós para levar a empresa ao próximo nível. Procuramos uma pessoa que prese pela qualidade e que saiba trabalhar bem em grupo, sendo proativo e colaborando com outros engenheiros. 

## Local

Presencial. Berlim - Alemanha

## Cargo 

Desenvolvedor(a) Android Sênior.

## Benefícios

- 25 dias **úteis** de férias. (aumentando até 28 conforme tempo na empresa)
- Não é necessário esperar 1 ano para tirar férias =P.
- Horário flexível.
- Pacote de Realocação (funcionário e família)
- Acomodação por 1 mês.
- Salário competitivo.

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Experiência com Kotlin
- Boa comunicação em inglês (Fala, escreve e escuta)
- Não é necessário falar alemão.

## Contratação

Contrato indefinido de tempo (similar ao CLT). 

## Como se candidatar

Através do link: https://grnh.se/54662c911.
Se preferir, pode me contactar por @Leandro no androiddevbr. 
email: leandro.ferreira@getyourguide.com

**Comment by jpventura** [comment]
@leandroBorgesFerreira ficaram faltando:

  - Nome da empresa
  - Junior/Pleno/Senior
  - Cargo

**Comment by leandroBorgesFerreira** [comment]
Atualizado.

**Comment by leandroBorgesFerreira** [comment]
Pra facilitar as tags: Internacional, Presencial, Relocation Allowance, Sênior, Visa Sponsorship

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
