### ISSUE TITLE
[Campinas, SP] Android Developer | Mazzatech

### ISSUE THREAD

**Issue by taianeuchoac** [androiddevbr/vagas#1028]
## Descrição da vaga
Profissional atuará no desenvolvimento de aplicações mobile para instituições financeiras, bancos digitais e fintechs. Apoiar o time de suporte/produtos, sanar dúvidas técnicas e problemas de produção.

## Local
Bairro Vila Nova - Campinas
Atuação Presencial

## Benefícios
- Plano de Saúde
- Plano Odontológico
- Vale Refeição/Alimentação
- Vale Transporte
- Gympass
- Seguro de Vida
- PLR
- Plataforma de Cursos Alura

## Requisitos
Experiência em desenvolvimento Java/Android
Conhecimentos básico sobre Kotlin
Integração com APIs (webservices REST/SOAP);
Inglês/Espanhol Intermediário.

## Contratação
CLT

## Nossa empresa
Profissional atuará alocado em empresa que trabalha com soluções de segurança para instituições financeiras.

## Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado e pretensão salarial.
Inserir no assunto: Vaga Android Campinas.

**Comment by jpventura** [comment]
@taianeuchoac 

  - É desenolvimento nativo ou React Native?
  - Junior, pleno ou sênior?

**Comment by taianeuchoac** [comment]
Ola!
É desenvolvedor Nativo.
A oportunidade é preferencialmente Senior, mas o gestor avalia outros
perfis também.

Obrigada!
=)


Taiane Uchoa
ANALISTA DE RH

taiane@mazza.tech
011 2532.2992 <http://mazza.tech/assinatura/2019/11%2025322992> / 97569.0652
skype: taiane.uchoa
[image: Site]
[image: Localização]


Em sáb., 1 de fev. de 2020 às 03:30, JP Ventura <notifications@github.com>
escreveu:

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
