### ISSUE TITLE
[Metrô Portuguesa-Tietê, SP] Desenvolvedor(a) Android | Netshoes

### ISSUE THREAD

**Issue by Magalu01** [androiddevbr/vagas#1029]
# Sobre nós
Estamos a procura de um profissional que **#rompapadrões**, que tenha **#foco** no resultado e que tenha **#tesãoporfazer**  sempre o melhor! Tá afim? **:-)**

Então dê uma olhada no perfil abaixo e venha fazer parte de um dos maiores e-commerces da América Latina!  **\o/**

Todas as nossas vagas estão disponíveis também para pessoas com deficiência. 

Quais serão as suas atividades? 
Desenvolvimento de soluções para plataforma Android.

# O que buscamos para esta posição?

## Com certeza tem que ter
  - Conhecimento em consumo de APIs JSON/REST;
  - Conhecimento em Gradle(Build Variant, Tasks, etc);
  - Conhecimento sólido em Java/Kotlin;
  - Conhecimento do processo de distribuição da Play Store;
  - Conhecimento em alguma arquiteturas mobile (ex: MVP, MVVM, VIPER);
  - Conhecimento em armazenamento local (offline);
  - Conhecimento em Proguard;
  - Conhecimento em metodologia ágil;
  - Conhecimento em Git - Gitflow;
  - Testes unitários;
  - Inglês para leituras técnicas.

## Seria legal se você tivesse
  - Conhecimento em ferramentas de automação;
  - Conhecimento em Integração Contínua / Entrega Contínua;
  - Conhecimento de testes de interface – instrumentados;
  - Experiência em aplicativos Whitelabel;
  - Portfólio de aplicativos na Play Store;
  - Conhecimento em monitoração e métricas (crash report, analytics, performance);
  - Conhecimento em e-commerce;
  - Experiência em desenvolvimento Back-end;
  - Conhecimento em Otimização de performance e segurança.

# O que oferecemos?
  - Vale Refeição :-)
  - Vale Alimentação
  - Assistência Médica: Notredame Intermédica.
  - Assistência Odontológica: BBDental.
  - Vale Transporte
  - Day Off, descanso merecido no dia do seu aniversário \o/
  - Horário Flexível
  - Home Office 1 vez por semana
  - Participação nos Lucros e Resultados;
  - Desconto em Produtos;
  - Previdência Privada;
  - Parceria com Gympass, mexa-se!
  - Parceria  com o Cartão Funcional;
  - Parceria com Faculdades, você sendo protagonista do seu conhecimento!

## Nossa empresa:
E qual o nosso jeito de ser?

Fazemos o que amamos. **#TesãoPorFazer!**

Inovamos porque não sabemos olhar para trás. **#RomperPadrões!**

A liberdade de ser mais e fazer melhor está em nossas mãos. **#AquiEuPosso!**

Está na cara que conseguimos. **#FocoNoResultado!**

Somos parte do negócio. **#DonoDoNegócio!!**

Dominamos nossa rotina e agimos sem perder tempo. **#RápidoComoUmClick!**

Simples, diretos e precisos, como tem que ser. **#Descomplica!**

O resultado? Mera consequência da nossa equipe. Do nosso grupo. **#GenteValorizada!**

**#SomosGrupoNetshoes! =D**

E aí? Gostou?! Então que tal juntar-se ao nosso time?! **;-)**

## Como se candidatar
Por favor envie um e-mail para janaina.utempergher@magazineluiza.com.br com seu LinkedIn - enviar no assunto: Vaga Android Netshoes

## Contratações:
  - CLT
  - Escritório

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
