### ISSUE TITLE
[Curitiba, PR] Dev Android | AutomTech

### ISSUE THREAD

**Issue by AutomTech** [androiddevbr/vagas#1030]
## Descrição da vaga

Desenvolvimento em esteira ágil de aplicativos em Android.

## Local

Curitiba - PR.

## Benefícios

Seguro Saúde e odontológico com co-participação, extensível aos familiares
PLR do sindicato do Paraná
Seguro de vida
Vale alimentação ou refeição no valor de R$ 484,00
Auxilio creche
Conveio com o SESC

## Requisitos

Obrigatórios
Experiência em Desenvolvimento Android, Java.
Ensino Superior Completo.

Desejáveis
Kotlin, SQL, Git, UML.

Diferenciais
Conhecimento em Flex ActionScript, Flash Builder e Subversion.

## Contratação

CLT.

## Nossa empresa

Empresa do segmento bancário. 

## Como se candidatar

Enviar CV para trabalheconosco@automtech.com.br ou (41) 988142126.

![ANDROID](https://user-images.githubusercontent.com/57018306/73682258-cd380880-469e-11ea-8659-3c80a8d733e3.png)

**Comment by jpventura** [comment]
@AutomTech:

  - A vaga é para Android ou iOS? O assunto do email diz *DEV IOS*
  - É desenolvimento nativo ou React Native?
  - Junior, pleno ou sênior?
  - Presential ou remoto?

**Comment by AutomTech** [comment]
@jpventura, agradeço por ter avisado, já arrumei a imagem. 

- Conhecimentos:
Retrofit
Reactive - Diferencial
Kotlin - Diferencial

- As vagas são para Pleno e Sênior

- Presencial

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
