### ISSUE TITLE
[Curitiba, PR] Desenvolvedor Mobile | BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [androiddevbr/vagas#1031]
Descrição da vaga
Estamos em busca de profissionais com experiência em Android e IOS para atuar em projetos para grande cliente em Curitiba. Prazo indeterminado de contratação com muita chance de crescimento.

Local
Presencial no cliente em Curitiba- Bairro Rebouças.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico Bradesco
-previdência privada
-plano odontológico

Requisitos
- Experiência com desenvolvimento nativo Android e iOS
- Ferramentas de integração contínua como Jenkins, FastLane, BitRise, Bamboo
- Ferramentas de entrega contínua como JIRA, BitBucket, Confluence
- Development Security Operations (DevSecOps)
- Automação de processos com ShellScripting, Phyton ou Ansible
- Deploy em nuvem (Microsoft Azure, Azure DevOps)

Contratação
CLT full pela BRQ.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
