### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor(a) Android | ArcTouch

### ISSUE THREAD

**Issue by arctouch-douglasfornaro** [androiddevbr/vagas#1032]
## Descrição da vaga

Esta é uma oportunidade para os desenvolvedores do Android, com uma forte experiência de programação orientada a objetos e atenção aos detalhes e à qualidade, para contribuir com uma variedade de aplicativos desafiadores e de ponta.

Nossos projetos geralmente variam de três a seis meses. Em um ano, você poderia facilmente trabalhar em quatro projetos diferentes. Nós encorajamos colaboração e criatividade. Você irá interagir com a nossa equipe de gerentes de produto, designers e engenheiros, e poderá arquitetar soluções com nossos clientes e seus engenheiros também.

Em um dia com a gente você vai, por exemplo:

- Fazer nossos clientes parecerem heróis ajudando-os a criar e manter aplicativos incríveis;
- Desenvolver aplicativos para grandes audiências no mercado dos EUA;
- Pensar junto com o nosso cliente para construir produtos de sucesso e de impacto;
- Trabalhar ao lado de equipes de design e de produtos para ajudar a moldar e melhorar a maneira como desenvolvemos ótimos aplicativos para nossos clientes;
- Desenvolver aplicativos usando melhores práticas de engenharia de software e bibliotecas frameworks modernas;
- Escrever código que seja sustentável, com desempenho e projetado com amor;
- Fornecer e receber feedback em revisões de código;
- Fazer parte da comunidade, divulgar e compartilhar seu conhecimento com os outros;
- Ajudar nossa equipe a crescer fortemente e manter seus valores fundamentais;
- Participar de um hackathon anual, durante um período de dois dias, quando cada grupo deve desenvolver um aplicativo inteiro a partir do zero, que pode então ser escolhido como um novo projeto de negócios;
- Ser desafiado todos os dias e trabalhar ao lado de pessoas que amam o que fazem.

## Local

Remoto ou Escritório Florianópolis

## Benefícios

- Vale refeições/alimentação
- Convenio médico e odontológico
- Sala de videogame
- Geladeira totalmente equipada
- Treinamento em inglês pago
- Desenvolvimento profissional
- TechTalks e Meetups
- Suporte para eventos
- Gympass

## Requisitos

- Conhecimento em Java e Kotlin;
- Sólida compreensão do SDK do Android;
- Programação avançada em orientada a objetos e conhecimento de padrões de design;
- Experiência com desenvolvimento ágil;
- Habilidades para refatorar o código;
- Compreensão dos princípios do Material Design;
- Familiaridade integrando aplicativos a APIs RESTful;
- Inglês avançado.

## Contratação

CLT

## Nossa empresa

Você gosta de desenvolver e entregar produtos incríveis? Venha nos ajudar a liderar uma das indústrias mais dinâmicas do planeta!

A ArcTouch vem desenvolvendo aplicativos móveis premiados para smartphones e tablets desde que o iPhone foi lançado. Concluímos centenas de aplicativos personalizados feitos à mão para algumas das marcas mais importantes da atualidade, incluindo NBC, salesforce.com, Audi, CBS, Razorfish, Google e Yahoo!

Milhões de usuários se envolvem com nosso trabalho todos os dias.

Mas estamos apenas começando. O Gartner projeta que a “Internet das Coisas” adicionará mais de 26 bilhões de dispositivos conectados até 2020 - novos dispositivos além dos smartphones, tablets e PCs - que transformarão a maneira como vivemos, trabalhamos e jogamos. Todos esses dispositivos precisam de um ótimo software.

E nós precisamos da sua ajuda.

## Como se candidatar

Entre em https://grnh.se/aafb95af1 para realizar o cadastro

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
