### ISSUE TITLE
[Curitiba, PR] Desenvolvedor(a) Android (N341TS) | CINQ TECHNOLOGIES

### ISSUE THREAD

**Issue by cezarsg** [androiddevbr/vagas#1033]
## Descrição
Somos uma empresa paranaense, possuímos mais de 27 anos de histórias, dentre elas o CMMI nível 3 e somos GPTW pelo 8º ano seguido! Trabalhamos com soluções de Software, possuímos uma fábrica muito bem estruturada que atende clientes nacionais e internacionais. Outsourcing, profissionais CINQ que atuam em clientes de diversos segmentos e diferentes portes. Trabalhamos com o foco de construir carreiras e transformar vidas!

## Atividades:

Desenvolvimento, Manutenção e evolução de sistema Android embarcado em veiculos (caminhões e frotas leves).

## Local:

Curitiba, PR.

## Carga Horária:

40h semanais

## Perfil Técnico Necessário:

Ampla experiência com desenvolvimento Java e Mobile (Java)
Sólidos conhecimentos e experiência com boas práticas de Desenvolvimento e Arquitetura de Software com foco em manutenabilidade, escalabilidade, performance.

## Será considerado um diferencial conhecimento em:
Kotlin
C++
Inglês
Disponibilidade para eventuais viagens.

## Benefícios
Plano de Saúde
Plano Odontológico
Seguro de vida
Previdência Privada
Vale Refeição
Vale Alimentação
Auxílio Estudo

## Candidate-se
Favor enviar e-mail para c.gomes@cinq.com.br informando o título da vaga no assunto do e-mail.

**Comment by kaioshenrique** [comment]
Aceita trabalho remoto?

**Comment by cezarsg** [comment]
Infelizmente, não.

Em sex, 31 de jan de 2020 13:57, Kaio Henrique <notifications@github.com>
escreveu:

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
