### ISSUE TITLE
[Curitiba, PR] Android Developer (P302TC) | CINQ TECHNOLOGIES

### ISSUE THREAD

**Issue by cezarsg** [androiddevbr/vagas#1034]
## Descrição
Somos uma empresa paranaense, possuímos mais de 27 anos de histórias, dentre elas o CMMI nível 3 e somos GPTW pelo 8º ano seguido! Trabalhamos com soluções de Software, possuímos uma fábrica muito bem estruturada que atende clientes nacionais e internacionais. Outsourcing, profissionais CINQ que atuam em clientes de diversos segmentos e diferentes portes. Trabalhamos com o foco de construir carreiras e transformar vidas!

## Sobre o Projeto:

Projeto internacional para desenvolver a parte conectividade de eletrodomésticos usando Iot.

## Onde ficamos:

Curitiba, PR.

## Requisitos
O que estamos buscando:

Experiência com Java, GIT, Kotlin e Scrum.

## Consideramos como diferencial:

Inglês e conhecimento em IOT.

## Benefícios
Confira os nossos benefícios:
Plano de Saúde
Plano Odontológico
Seguro de vida
Previdência Privada
Vale Refeição
Vale Alimentação
Auxílio Estudo
GymPass
E não para por aqui! Temos diversos convênios e parcerias legais pela cidade. Dá uma olhada:

https://cinqconvenios.now.sh/#noAction

Benefícios que só a CINQ oferece:

Aqui, nosso foco é construir carreiras e transformar rotinas, por isso, não enfatizamos apenas a tecnologia - prezamos o cuidado com nossos colaboradores, com o ambiente e com os projetos. Para isso, temos o nosso programa de desenvolvimento, o CINQ TECH, que existe para que seja possível incentivar o Time CINQ a melhorar cada vez mais. Investimos em treinamentos técnicos que ajudam também com as capacidades pessoais, tornando tanto o profissional quanto o projeto mais qualificado.

Isso é ser CINQ: trabalhar em um ambiente moderno, tecnológico, inovador e flexível - It’s beyond technology.

## Candidatar-se
Favor enviar e-mail para c.gomes@cinq.com.br informando o título da vaga no assunto do e-mail.

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
