### ISSUE TITLE
[Belo Horizonte, MG] Desenvolvedor(a) Android | CI&T

### ISSUE THREAD

**Issue by anelisamelo** [androiddevbr/vagas#1035]
Procuramos por alguém que manja de android tenha muita experiência e inglês avançado. Você será responsável pelo desenvolvimento Android em um projeto internacional e terá contato com o cliente. Além disso, é necessário que essa pessoa seja comunicativa, pense rápido e estrategicamente em soluções para problemas e sempre busca inovação e melhorias.

**Procuramos pessoas que:** 

Gostam de novos desafios, estão dispostas a descobrir e aprender todos os dias;
Gostam de contribuir e jogam pelo time;
Atuam com autonomia, usando a liberdade para opinar em processos e questões relacionadas ao cliente quando for preciso; 

**Você será responsável por:**

Ajudar a codificar a aplicação Android de um produto digital inovador no qual o cliente está trabalhando;
Enfrentar desafios reais do negócio com o cliente e o time;
Atuar em um novo sistema de um cliente conhecido internacionalmente e com produtos de alcance mundial
Fazer testes nas aplicações Android;
Conhecer e aprender sobre concepção e design de produto.

**Trabalhar com tecnologias como:**
Language: Kotlin, Android: Constraint Layout, Lifecycle, Bluetooth, Screen sizes, RecyclewView, Notification
Architecture: MVVM, DDD, Clean Code, Multi-module architecture, Offline first development
Libraries: Android Architecture Components(Room, Lifecycle, Databinding, WorkManager), Koin
CI/Environment: Git, Jenkins, Sonarqube
Testing: Espresso, MockK, JUnit (edited) 

**Você precisa ter:**

Experiência com desenvolvimento Android / Kotlin;
Inglês Avançado.

**Você irá se destacar se tiver:**

Conhecimento prático em Android nativo.

Gostou? Tem mais! ;)

**A CI&T também oferece:**

Regime CLT, 40 horas semanais de segunda a sexta com horário flexível;
Remuneração a combinar;
Participação nos lucros e resultados;
Vale alimentação e refeição;
Assistência médica e odontológica (plano padrão custeado pela empresa);
Seguro de vida;
Licenças maternidade e paternidade estendidas;
Auxílio creche;
Ônibus fretado, estacionamento ou transporte intermunicipal de acordo com a base de atuação;
Descontos em estabelecimentos e parceria com o SESC;
Gympass.

**Além disso...**

Sem dress code: quem gosta de roupa social são nossos clientes. Aqui na base da CI&T você pode trabalhar do jeito que se sentir mais confortável!
Ambiente descontraído e acolhedor (adoramos cores, quadros e post-its);
Opções de lazer e relaxamento (videogame, sinuca, cadeira de massagem, etc);
Plano de carreira estruturado e acompanhamento individual;
CI&T University com cursos online disponíveis em diversos temas!
Prezamos pela diversidade, liberdade, flexibilidade e autonomia!

**Todas as nossas vagas se destinam também para pessoas com deficiência.**

**Interessados enviar currículo para Anelisa Melo: v.anelisam@ciandt.com**

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
