### ISSUE TITLE
 [São Paulo, SP] Senior Android Software Engineer

### ISSUE THREAD

**Issue by 5andar** [androiddevbr/vagas#104]
## Descrição da vaga

Technology and design at QuintoAndar
QuintoAndar is a technology company that enables a seamless rental experience from discovery to closing. Through the intensive use of technology and design, we are redesigning the entire rental process, from one end to the other, to allow the kind of customer experience that we wish for ourselves. As a result, we are creating a new business model that is unique in the whole world and that will revolutionize the real estate industry.
Technology and design are core components of our DNA. Our team works very very hard, with cutting edge technology and design practices, to invent web and mobile tools that are first of their kinds in the whole world.
At QuintoAndar you will:
Work with a top-notch team that uses the best practices and best tools.
Learn a lot. Really.
Be part of a high-impact project that will affect many people's lives.
Have autonomy to make decisions with no endless meetings or bikeshedding.
Work in an informal environment and horizontal hierarchy.

Mobile engineer responsibilities at QuintoAndar
Develop and maintain QuintoAndar end-user applications for Android.
Co-plan and develop new features in QuintoAndar's internal applications (mobile workforce).
Help expand and optimize our mobile API.
Manage app publication for GooglePlay.

Language and location
We are a Portuguese speaking company. This is written in English because 1) we value diversity and would welcome foreign candidates, and 2) if you are Brazilian you need to be fluent in English in order to learn the most from the whole world.
We have offices in São Paulo and Campinas. This position is for the Sao Paulo office, near Estação Paulista (metrô linha amarela).

## Local

Escritório São Paulo - Paulista.

## Benefícios

Competitive salary package
Opportunity to earn stock options
Health plan and life insurance
Meal allowance ("ticket refeição + ticket alimentação")
Parking, gas or public transportation allowance
Very fun, collaborative, and fast-paced work environment

## Requisitos

Please only apply if you:

have a Computer Science, Computer Engineering or equivalent degree.
have deep understanding of Android SDK
have already developed significant mobile apps.
are very strong in analytic skills.
are used to writing RESTful APIs that are accessed by mobile apps.
do ok using relational databases.
are fluent in English.

We'll like you better if:

you have experience with reactive programming (RxAndroid)
you have experience developing backend systems
you already developed an Android app
you are used to work side by side with UX and Product teams
Material design is the norm on your apps

## Contratação

CLT

## Como se candidatar

Por favor se cadastrar através do link: https://quintoandar.workable.com/jobs/48044

**Comment by walmyrcarvalho** [comment]
@5andar Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by 5andar** [comment]
Olá,

Está sim, nosso processo para vagas de engenharia e produto é contínuo :]

Abs



*Alex Felix *
Talent Acquisition Analyst
+55 (11) 3506-8216


2017-04-08 21:50 GMT-03:00 Walmyr Carvalho <notifications@github.com>:
