### ISSUE TITLE
[São Paulo, SP] Mobile Developer (iOS/Swift) | Agile Content

### ISSUE THREAD

**Issue by InteraTalentHacking** [androiddevbr/vagas#1041]
## Descrição da vaga

Criação de soluções de streaming.

## Local

Alexandre Dumas, São Paulo - SP

## Benefícios

Seguro de Saúde
Seguro de Vida
Seguro Odontológico
Aulas de inglês e espanhol no trabalho
Remuneração competitiva
Bilhetes de refeições
Plano de participação nos lucros pago duas vezes por ano

## Requisitos

Obrigatórios

- Bacharel em ciência da computação ou experiência profissional equivalente;
- Bons conhecimentos de iOS com pelo menos 2 anos de experiência no desenvolvimento, envio e manutenção de aplicativos móveis;
- Proficiente em Swift com fortes habilidades de design orientado a objetos;
- Bom entendimento das estruturas internas da estrutura do iOS;
- Conhecimento de padrões gerais de design de software, bem como padrões de design iOS;

 
Desejáveis

- Capacidade de trabalhar de forma independente e gerar resultados;

 
Diferenciais

- Você está atualizado(a) sobre as alterações mais recentes da estrutura, ferramentas de criação e bibliotecas;

## Contratação

A contratação será feita em regime CLT com benefícios.

## Nossa empresa

Em uma época em que a maneira como as pessoas consomem conteúdo muda em um ritmo vertiginoso, a Agile Content prevê a criação de soluções de streaming que possibilitam e aprimoram essas experiências.
Com tecnologia de ponta, desenvolvemos nossa experiência em streaming de vídeo e áudio, desde a ingestão de conteúdo, soluções de processamento e gerenciamento até a experiência do usuário final com aplicativos para celular, TV e Xbox, e aproveitamos essa experiência para ajudar algumas das maiores empresas de telecomunicações na Europa e na América Latina, incluindo Telefónica, NET / Claro e Globosat, para modernizar a maneira como eles fornecem mídia para seus clientes e permitir que eles alcancem novos públicos.​

## Como se candidatar

Faça a sua inscrição no [site](https://vagas.byintera.com/agile-content/mobile-developer-ios-swift/?utm_source=github&utm_medium=issue&utm_content=tipo1&utm_campaign=geral&cr=growth)

**Comment by davidtcdeveloper** [comment]
@InteraTalentHacking Esta é a terceira vez que a mesma vaga é criada em nosso mural, pela terceira vez violando as regras que restrigem as vagas apenas a oportunidades para desenvolvedores Android. A vaga será removida do mural, caso tenhamos novos problemas a equipe de moderação precisará tomar outras iniciativas.
