### ISSUE TITLE
[Maringá, PR] Desenvolvedor Android | Objective Solutions

### ISSUE THREAD

**Issue by isabeladn** [androiddevbr/vagas#1047]
# Descrição da vaga

Com unidades em São Paulo, Curitiba, Maringá e Chicago, estamos sempre em busca de profissionais que estejam alinhados a nossa cultura, que queiram trabalhar conosco em um ambiente descontraído e animado.

## Local

Maringá - PR.

## Benefícios

- Vale Refeição ou Vale Alimentação;
- Plano de Saúde;
- Plano Odontológico;
- Estacionamento para bikes e carros;
- Vale Transporte;
- Gympass;
- PLR;
- Seguro de vida;
- Frutas fresquinhas todos os dias;
- Café da manhã e Lanche da tarde à vontade;
- Massagem 1x por semana;
- Programa de indicação de funcionários;
- Convênios de descontos com universidades, escolas de idiomas e restaurantes.

## Requisitos

Obrigatórios
- Programação Android (Java e/ou Kotlin);
- Conhecimentos básicos Android Studio;
- Padrões de layout;
- Noções de utilização do gradle;
- Versionamento git.

Desejáveis
- Noções de padrões de arquitetura (MVP, MVVP ou Clean);
- Frameworks de injeção de dependência;
- Clean code;
- Testes unitários;
- Testes de UI (automatizados);
- Persistência de dados local.

Diferenciais
- Boas práticas de gerenciamento de memória;
- Gerenciamento de publicações e versões no Google Play;
- Fastlane.

## Contratação

Presencial - CLT

## Nossa empresa

A Objective é feita de pessoas. Somos um time comprometido e com foco no desenvolvimento de pessoas e lideranças. Somos apaixonados por tecnologia e criativos, gostamos de aprender e romper barreiras desenvolvendo soluções que resolvam os problemas e necessidades de nossos clientes com qualidade.

## Como se candidatar

Para se candidatar à essa vaga, [clique aqui](https://objective.gupy.io/jobs/161608?jobBoardSource=gupy_public_page).

Se ficar com alguma dúvida, pode também me procurar pelo [Linkedin](https://www.linkedin.com/in/isabela-dias-neves-a3a03970/)!

**Comment by jpventura** [comment]
@isabeladn junior, pleno ou sênior?
