### ISSUE TITLE
[Remoto] Desenvolvedor Android - Freelance

### ISSUE THREAD

**Issue by EduardoTT** [androiddevbr/vagas#105]
## Descrição

Olá, somos três empreendedores com o sonho de tornar nossa cidade mais divertida. Nada melhor que um app mobile para nos ajudar nesta tarefa. Por isso, precisamos de um desenvolvedor Android, apaixonado pelo o que faz, para trazer ao mundo este incrível app. Se você quer saber mais sobre o assunto e gosta de pegar projetos remotos como freelancer, não hesite em entrar em contato conosco. 

## Local

Remoto

## Como se candidatar

Por favor envie um email para dudutt@gmail.com.br. Enviar no assunto: Freela Android

**Comment by walmyrcarvalho** [comment]
@EduardoTT Boa noite Eduardo, tudo bem?

Você tem mais informações sobre a oportunidade, como modelo de pagamento ou nível de senioridade que vocês tão esperando?

Abraço!

**Comment by EduardoTT** [comment]
Bom dia @walmyrcarvalho,

sobre o pagamento:
Podemos avaliar o projeto com base na estimativa de horas, ou com base nas horas trabalhadas, de fato. Estamos abertos para conversar. De qualquer forma, faremos um contrato para formalizar a prestação de serviço.

sobre o nível de senioridade:
Não há um nível específico. O mais importante é que o profissional possa ter dedicação ao projeto nos próximos quatro meses (talvez três), com cerca de 20 horas semanais.

**Comment by felipeaugusto1** [comment]
@EduardoTT , os emails enviados para dudutt@gmail.com.br estão retornando. Abraço!

**Comment by andersonFaro9** [comment]
Opa, tudo bem Eduardo?
Mandei o email para o email que pede mas voltou.
Ainda há vaga?

**Comment by andersonFaro9** [comment]
Algum outro email?
