### ISSUE TITLE
[São Paulo/SP - Zona Sul] Arquiteto Android

### ISSUE THREAD

**Issue by gabimollo** [androiddevbr/vagas#106]
Meu cliente é uma startup (investidos pela Kaszek e Monashees+) ganhando bastante espaço no cenário nacional e em 2017 fará parte do programa de aceleração mundial do Google

**Responsibilities**
Develop and maintain our native mobile apps (Android)
Consume RESTful APIs to implement new functionalities that enhance the quality of our product
Bring pixel perfect UI/UX into life

**Requirements**
Senior experience coding in relevant startups and/or personal projects
Relevant Startup experience
Advanced knowledge of Android Java

**Local de trabalho:**
Vila Mariana

**Contratação:**
CLT Full

**Benefícios:**
Salário competitivo
Oportunidade de ganhar Stock Options
Assistência médica
Gym Pass
Bonus para upgrade deconfiguração de notebook
Cozinha com chefe de cozinha
Ambiente fun

Interessados enviar cv para `gaby_mollo@hotmail.com`

**Comment by walmyrcarvalho** [comment]
@gabimollo Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by walmyrcarvalho** [comment]
Fechada a pedido da dona da issue.
