### ISSUE TITLE
[Campinas - SP] Desenvolvedoras Júnior (de verdade, não precisa ter experiência)

### ISSUE THREAD

**Issue by ricardobrg** [androiddevbr/vagas#1061]
## Descrição da vaga

A AB-InBev está realizando um programa de capacitação remunerada com execução da ProWay. A contratação será com salário e benefícios desde o início do curso. Os candidatos selecionados serão contratado como CLT já no primeiro dia de curso que terá 3 meses de duração. A capacitação ocorrerá em Campinas e o local de trabalho após o curso será em Jaguariúna (região metropolitana de Campinas).

A primeira turma será de Android e iOS e tem início previsto para abril. As inscrições serão válidas também para as demais turmas que devem ser logo anunciadas.

## Local

Curso: Campinas
Local de trabalho após o curso: Jaguariúna (região metropolitana de Campinas)

## Benefícios
Salário R$ 2.458.62

VR, Gympass, Convênio médico e odontológico, fretado, 14º salário, auxílio material escolar para
dependentes, convênio farmácia

## Requisitos

Obrigatórios
- Trabalho em equipe 

Desejáveis
- Conhecimento básico em programação (qualquer linguagem)

Diferenciais
- Inglês

## Contratação

CLT

## Nossa empresa
A Anheuser-Busch InBev é uma empresa multinacional de bebidas e cervejas formada em 2004 pela fusão da belga Interbrew e da brasileira Ambev. Está sediada em Leuven, na Bélgica, e possui escritório global de gerência funcional em Nova York, e sedes regionais em Londres, Cidade do México, Joanesburgo, St.

A Anheuser-Busch InBev (ABInBev) tem uma galera apaixonada por cerveja que são especialistas nas tecnologias mais inovadoras utilizadas no mercado. São mais de 200 fanáticos que formam o Beertech, célula de tecnologia da companhia, localizada atualmente no Escritório Global de Jaguariúna/SP e em nosso headquarter em Nova York.

O intuito desta estrutura é oferecer serviços e soluções digitais para as empresas que pertencem ao Grupo Anheuser-Busch InBev, como por exemplo: Ambev, Labatt Brewing, Cervejaria Modelo, Cervejaria Hondurenha, South African Breweries (SAB) e muitas outras, que juntas formam o maior grupo cervejeiro do mundo.

A junção de profissionais técnicos, estratégicos e com senso de dono trabalhando lado a lado para a entrega de produtos globais auxilia fortemente no impulsionamento e crescimento de negócios locais que vendem um dos produtos mais consumidos e apreciados de todo o mundo, a cerveja.

## Como se candidatar
http://beertech.proway.com.br

**Comment by Daniray2008** [comment]
tem possibilidade de ser remoto?

**Comment by ricardobrg** [comment]
> tem possibilidade de ser remoto?

@Daniray2008 infelizmente não... o treinamento e a vaga são presenciais
