### ISSUE TITLE
[Dublin, IE] Lead Mobile Developer | Softest Consulting

### ISSUE THREAD

**Issue by SoftestLtd** [androiddevbr/vagas#1076]
_We are hiring a **Lead Mobile Developer** for one of our multinational clients in Dublin, Ireland., to be based at a leading bank in Ireland._

**Job Description**

•	More than 12 years of total experience with about 8 years in developing and architecting 
        mobile applications using Hybrid technologies such as, JavaScript, HTML, CSS.
•	Should have performed a lead role or have led a team in the past for at least 5 years.
•	Should have worked in an agile environment with good knowledge of JIRA.
•	Strong Object-Oriented design and development experience with JavaScript (ES5 and ES6).
•	Strong experience in building client-side applications using JS frameworks/technologies like 
        Handlebars, KnockoutJS, ReactJS, Zepto/jQuery. 
•	Strong experience of CSS pre-processors like SASS or LESS.
•	Familiarity with RESTful APIs to connect applications to back-end services. 
•	Strong experience of JavaScript task runners.
•	Good understanding of JavaScript design principles, patterns, and best practices. 
•	Proficient understanding of code versioning tools (such as GIT).
•	Experience with automating build processes (continuous integration), Unit testing, source 
        code analysis tools.
•	Basic understanding of Android and iOS development.  
•	Ability to understand business requirements and translate them into technical specifications.

Other Details:
Job Location: Dublin, Ireland 
Job Type: Permanent
Salary: Negotiable depending on experience
Industry: FinTech
*** Work eligibility: Irish, British and EU nationals only ***

Please share your CV at shivangi@softest.co
or reach us at admin@softest.co

Any queries, feel free to contact us at admin@softest.co

**Comment by vitorprado** [comment]
More than 12 years of mobile development? good luck.

**Comment by raphaelbgr** [comment]
😂😂😂

**Comment by SoftestLtd** [comment]
Hey guys, 
Actually the experience requirement is about 8 years in mobile applications using hybrid technologies. Total experience should be over 12 years with 5 years in a team lead role. Sorry for the typo. 
Cheers guys!

**Comment by davidtcdeveloper** [comment]
@SoftestLtd the person will be hired by Softest or another company? The rules of our opportunities board demand the information of the hiring company.

**Comment by SoftestLtd** [comment]
@davidtcdeveloper We are hiring on behalf of our multinational client in Dublin.

**Comment by jpventura** [comment]
@SoftestLtd according to the [community guidelines](https://github.com/androiddevbr/codigo-de-conduta/blob/master/README-en.md), it is required to reveal the name of the employer company. Otherwise we will have to remove your post.

Also, looking at the listed skills, it seems like you are looking for a  lead frontend developer with some Android skills (not a lead Android developer). If this is the case, I recommend you post this job at [Frontend BR](https://github.com/frontendbr/vagas)
