### ISSUE TITLE
Android Developer

### ISSUE THREAD

**Issue by SoftestLtd** [androiddevbr/vagas#1077]
_A fantastic opportunity is available for an **Android Developer** to be based in Dublin with one of the leading banks in Ireland. We are hiring on behalf of our multinational client._

If you satisfy the below requirements, this position is for you!

- More than 5 years of experience in developing Android applications 
- Strong knowledge of Android SDK with different versions of Androids.
- Strong knowledge of Android UI design principles, patterns, and best practices.
- Experience with offline storage, threading, and performance tuning. 
- Knowledge of the open-source Android ecosystem and exposure to a wide variety of Android and 3rd party libraries e.g. RxJava, Dagger 2, Retrofit, etc. 
- Experience of working in an agile environment.
- Familiarity with RESTful APIs to connect Android applications to back-end services. 
- Proficiency in Android Studio and code versioning tools (like GIT).
- Experience with automating build processes (continuous integration), Unit testing and source code analysis tools. 
- Ability to understand business requirements and translate them into technical specifications. 
- Good to have - basic understanding of HTML and JavaScript. 

Job Location: Dublin, Ireland
Position: Permanent
Salary: Negotiable (depending on experience)
Eligibility: Irish, British and EU nationals only.
Industry: FinTech

Please share your CV to shivangi@softest.co
or reach us at admin@softest.co

Any queries, feel free to contact us at admin@softest.co

**Comment by davidtcdeveloper** [comment]
@SoftestLtd the person will be hired by Softest or another company? The rules of our opportunities board demand the information of the hiring company.

**Comment by SoftestLtd** [comment]
@davidtcdeveloper we are hiring on behalf of our multinational client.

**Comment by davidtcdeveloper** [comment]
Just to be sure: the person will be hired by Softes but allocated inside a multinational client, is that right?

**Comment by SoftestLtd** [comment]
> Just to be sure: the person will be hired by Softes but allocated inside a multinational client, is that right?

Yes , David

**Comment by SoftestLtd** [comment]
Yes David. 

Thank you.

Best regards, 
Surya

**Comment by SoftestLtd** [comment]
This position is now closed. Thank you.
