### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor(a) Android | South System

### ISSUE THREAD

**Issue by AmandaElena** [androiddevbr/vagas#1087]
A SOUTH SYSTEM está em busca de um (a) Desenvolvedor (a) Android que deseja fazer parte do nosso propósito de impulsionar como pessoas para inovar no mundo. Para fazer parte do tempo, há algumas habilidades que valorizam muito, e não estamos falando apenas de tecnologia, que valorizamos profissionais que respeitem ou que sejam próximas e suas diferenças, que sejam leais e responsáveis ​​com entregas e com pessoas. A colaboração e o engajamento devem fazer parte do dia para que o resultado seja eficaz e ter a sede de aprendizado para trabalhar com inovação contínua.

Fazendo parte do tempo de implementação de projetos com as melhores práticas de desenvolvimento Android;
Solucionando desafios importantes junto à equipe, mantendo o foco e agilidade na condução das atividades, e priorizando uma melhor experiência.

Nessa oportunidade, o (a) profissional trabalhará:
- Android nativo
- Linguagem de programação Kotlin
- Arquitetura MVV
- Punhal para injeção de dependências  

**Será um diferencial para esta oportunidade:**
- Usar componentes do Android Jetpack
- Conhecimento em metodologia ágil.

** Local**
- Presencial em Florianópolis-SC

**Contratação**
- PJ ou Cooperado, a combinar

**Como se candidatar**
- Por favor envie um email para **amanda.almeida@southsystem.com.br** com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@AmandaElena sugiro postar a vaga no [Cocoa Heads Brasil](https://github.com/CocoaHeadsBrasil/vagas/issues).
