### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Android Pleno/Sênior | PertoDaqui

### ISSUE THREAD

**Issue by Moov8Systems** [androiddevbr/vagas#1089]
O PertoDaqui é um aplicativo de ofertas voltado para pequenos comerciantes e estamos em busca de um(a) Desenvolvedor(a) Android Pleno ou Sênior freelancer para corrigir um bug.

##Descrição
Problema:
Na programação do aplicativo está: - Pegar a última localização do dispositivo. Se por algum motivo não tem a localização, dá erro no app e nem abre. Se for acessar de novo e a localização estiver disponível, o erro não acontece.

O que fazer:
Configurar para que o app solicite a localização atualizada quando abrir ou quando requisitado em uma página. Quando não for possível ter a localização, deve surgir a mensagem de erro, mas ao clicar em ok irá retornar todas as ofertas publicadas no app independente da localização do usuário até que a localização atual seja obtida.

Considerações:
O código esta escrito em Java, mas nada impede de desenvolver alguma função em Kotlin caso seja necessário
Padrão: MVC
Versão android: 4.1
Apenas smartphone

##Local
Remoto

##Requisitos
Conhecimentos obrigatórios:
3+ anos de experiência com Android
Framework Android Nativo
Desenvolvimento Android (Java/Kotlin)
Gradle/Maven
Integração com serviços Restful
Saber utilizar GIT (Bitbucket/GitHub)

Conhecimentos desejáveis:
UX (noções)

##Contratação
Freelancer: PJ com nota fiscal

Remuneração:
Valor fechado a partir do valor/hora do desenvolvedor(a) x horas estimadas.

##Nossa empresa
A Moov Systems é uma startup com soluções para pequenos comerciantes, acelerada e residente no iDEXO da TOTVS. Para saber mais, acesse: https://pertodaqui.app ou http://www.minnis.com.br

##Como se candidatar
Envie seu GitHub para contato@pertodaqui.app - enviar no assunto: Vaga Android

#remoto #pleno #senior #pj #freelance

**Comment by DaniloFurtado** [comment]
Boa tarde, tenho interesse na oferta para free lancer.

Att,

Danilo Furtado.
