### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Pleno/Senior Android | 42 Consultoria Digital

### ISSUE THREAD

**Issue by fabriciovieira** [androiddevbr/vagas#109]
## Descrição da vaga
Estamos procurando um(a) Desenvolvedor Android para trabalhar na manutenção e criação de aplicativos Android para nossos clientes.

**Você será responsável por**:
- Desenvolver novos aplicativos 
- Otimizar o código e implementar novas funcionalidades em aplicativos existentes 
- Trabalhar junto com o time de design para ajudar construir protótipos e produtos funcionais 
- Contribuir com novas ideias e identificar melhorias proativamente

## Local
São Paulo - Pompeia

## Benefícios

- Salário compatível com o mercado
- Vale Transporte
- Vale Refeição

## Requisitos

**Obrigatórios**
- Ter conhecimento profundo do SDK Android
- Conhecimento sólido de algoritmos, estrutura de dados e orientação a objetos
- Conhecimento sólido de frameworks mvc para desenvolvimento móvel
- Raciocínio lógico
- Experiência desenvolvendo aplicativos móveis - enviar link de apps no google play
- Experiência no desenvolvimento de aplicativos que se comuniquem remotamente usando RESTful APIs
- Capacidade para resolver problemas
- Inglês avançado (oral, falado e escrito)

**Desejáveis**
- Experiência com UX/UI

**Diferenciais**
- Projetos opensource
- Perfil no github ou bitbucket

## Contratação

CLT

## Nossa empresa

A 42 é uma consultoria com foco em estratégias de marketing digital. Entregamos soluções digitais sob medida para cada um dos nossos clientes, de sites a aplicativos mobile, além de estratégias efetivas para o ambiente digital. Somos uma empresa jovem e estamos crescendo. Procuramos talentos que queiram apostar na empreitada e crescer junto conosco.

## Como se candidatar

Por favor envie um email para vagas@quarentaedois.net com seu CV anexado e link dos aplicativos na Google Play - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@fabriciovieira Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by fabriciovieira** [comment]
Opa!

Pode fechar, por favor.
