### ISSUE TITLE
Dev Android Senior [Remoto OU São Paulo/ZN]

### ISSUE THREAD

**Issue by renatoarg** [androiddevbr/vagas#1093]
**Estamos contratando um Dev Android Senior 100% remoto.**

Nosso App de e-commerce já está em produção e atualmente tem 900K downloads e 200K usuários ativos por mês. 

Precisamos de um dev que saiba criar um app do zero, com separação de camadas usando boas práticas em **_Kotlin_**. 

Requisitos técnicos:
- Kotlin, ViewModel, Coroutines, Extensions, Navigation, Retrofit, Koin, Dagger2, Fragments, Glide, Calendar, Animations, RecyclerViews, Adapters e ViewHolders.
- MVP e MVVM.
- GIT.

Contratação: Imediata, preferencia por PJ

Após analise de CV, enviaremos um teste para ser desenvolvido em 48h e postado no Github.

Interessados enviar CV para: renatoarg@gmail.com

Obrigado!

**Comment by davidtcdeveloper** [comment]
@renatoarg as regras do mural de vagas obrigam a divulgação do nome da empresa contratante. Estou encerrando a vaga até que o nome seja adicionado.
