### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Android | Qintess

### ISSUE THREAD

**Issue by RoseliReis15** [androiddevbr/vagas#1094]
A Qintess, empresa especializada em consultoria de TI e fábrica de software, esta com vaga em aberto para a posição abaixo:

Analista Desenvolvedor Android
Experiência com desenvolvimento de aplicações nativas Android
Sólidos conhecimentos em Java
Experiência na utilização de ferramentas de versionamento de código (GIT)
Integração de aplicativos com APIs e Web Services
Experiência com testes unitários
Experiência com as guidelines de design e desenvolvimento Google (Material Design, Components, ...)
Conhecimento de metodologias ágeis (SCRUM)
Local de atuação: Zona Sul e Centro /SP (Interlagos / Paulista)

Contratação CLT Full

Benefícios 
VT, VR, AM, AO , SV

Interessados encaminhar currículos atualizado com pretensão salarial e disponibilidade para recrutamentoeselecao@qintess.com / roseli.reis@qintess.com

**Comment by jpventura** [comment]
@RoseliReis15 quem é a empresa contratante? a própria Qintess?

**Comment by RoseliReis15** [comment]
Olá JP,


A empresa contratante é a Qintess / Resource IT

Porém o profissional ficará alocado em nosso cliente.


Obrigada!

________________________________
De: JP Ventura <notifications@github.com>
Enviado: quinta-feira, 9 de abril de 2020 15:26:55
Para: androiddevbr/vagas
Cc: Roseli Almeida Santos Reis; Mention
Assunto: Re: [androiddevbr/vagas] Analista Desenvolvedor Android (#1094)


@RoseliReis15<https://github.com/RoseliReis15> quem é a empresa contratante? a própria Qintess?
