### ISSUE TITLE
[Campinas, SP] Desenvolvedor Android [SENIOR] 

### ISSUE THREAD

**Issue by taisduarteleonel** [androiddevbr/vagas#1095]
## Descrição da vaga

O desenvolvedor participará de uma equipe multidisciplinar que criará sistemas web e aplicativos para diversos tipos de dispositivos mobile de diferentes marcas e modelos;
Estará inserido em uma grande multinacional da região com contato direto com cliente em nível global;
Participará do desenvolvimento de aplicativos desde a arquitetura até a versão final. 

## Local
Campinas, SP 

## Benefícios

- VR
- VA
- VT
- Assistência médica
- Assistência odontológica 
- Onibus fretado
- Seguro de vida
- Cooperativa de crédito
- Previdência privada
- Estacionamento gratuito
- Horário flexível
- Home office (1x na semana)

## Requisitos

Obrigatórios
- 5+ anos de experiência com Android
- Experiência com kotlin e java

## Contratação

CLT - a combinar 

## Nossa empresa

Hoje a Share RH, consultoria de recrutamento e seleção, está em parceria com o Venturus - instituto de tecnologia da cidade de Campinas. 

## Como se candidatar

Por favor envie um email para tl@sharerh.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@taisduarteleonel As regras do mural de vagas exigem a divulgação do nome da empresa contratante. Estou encerrando a vaga até que o nome da empresa seja adicionado.
