### ISSUE TITLE
[Barueri, São Paulo] Analista Desenvolvedor Android

### ISSUE THREAD

**Issue by rafaelbarrelo** [androiddevbr/vagas#11]
## Descrição da vaga

- Desenvolver plataforma de E-commerce;
- Relacionamento e atendimento as necessidades do cliente;

## Local

Barueri, próximo ao Rodoanel

## Benefícios

- Não informado

## Requisitos

-  Superior completo em áreas afins;
-  Experiência em desenvolvimento mobile;
-  Conhecimentos em JAVA/ Wbservices XML/JSON, PUSH notification; Geolocalização e automação de testes para múltiplos dispositivos;
-  Conhecimentos em UX;
-  Conhecimentos em SCRUM;
-  Leitura, interpretação e criação de especificações funcionais;
-  Definição de solução e arquitetura técnica.

## Contratação
- Não informado

## Remuneração
- Negociável

## Como se candidatar
Contato direto com Renata pelo email: renata@claudiacaparroz.com.br

**Comment by walmyrcarvalho** [comment]
@rafaelbarrelo Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by rafaelbarrelo** [comment]
@walmyrcarvalho Então, não sei se ainda tá aberta. Eu só repassei aqui um contato que fizeram comigo.

**Comment by walmyrcarvalho** [comment]
@rafaelbarrelo Beleza, sem problemas :)

**Comment by rafaelbarrelo** [comment]
@walmyrcarvalho acabei de mandar email pra saber se ainda está disponível. Qualquer novidade eu atualizo aqui.

**Comment by walmyrcarvalho** [comment]
Sem problemas, valeu Rafael!

**Comment by rafaelbarrelo** [comment]
A vaga foi encerrada.
