### ISSUE TITLE
[São Paulo - Faria Lima] Arquiteto Desenvolvedor Mobile Android

### ISSUE THREAD

**Issue by ezefranca** [androiddevbr/vagas#110]
## Descrição da vaga

Grande projeto (+1 ano no mínimo já em backlog). Maiores detalhes podem ser passados para os interessados

## Local

Escritório na Faria Lima (Mesmo prédio do Google)

## Benefícios

- Ambiente tranquilo
- Autonomia 
- Horário Flexível
- Outros benefícios negociáveis 

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados
- Perfil de arquiteto mobile porém que possa desenvolver, capaz de elaborar soluções de arquitetura MVC ou MVP para Android;
- Experiência em implementação de automação de testes unitários utilizando TDD ou BDD;
- Experiência com processo de publicação da aplicação para Google Play (Beta Test e Produção);

Desejáveis

- Experiência com Espresso e UI Automator
- Experiência com RxJava
- Desejável experiência com bibliotecas para interação com câmera, localização, gráficos e http client. 
- Desejável experiência Gradle ou Maven;
- Desejável conhecimento em automação de testes utilizando appium ou calabash;
- Desejável conhecimento em programação reativa;

Diferenciais
- Projetos opensource

## Contratação

A combinar (CLT)

## Nossa empresa

Mais detalhes podem ser enviados para os interessados. 

## Como se candidatar

Por favor envie um email para luizarantes@gmail.com com seu CV anexado - enviar no assunto: "Vaga Android"

**Comment by walmyrcarvalho** [comment]
@ezefranca Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by ezefranca** [comment]
@walmyrcarvalho close 👍
