### ISSUE TITLE
[PORTO ALEGRE, RS] Pessoa Desenvolvedora Android | Warren Brasil

### ISSUE THREAD

**Issue by fcjonas** [androiddevbr/vagas#1103]
### Warren: 1 Bilhão na Pandemia e 80 vagas abertas! 
A Warren é uma corretora digital de investimentos autorizada e regulada pela CVM, Anbima e Banco Central, que tem a missão de descomplicar as finanças e transformar o hábito de investir em algo fácil, transparente e eficiente.

Aliando tecnologia, usabilidade e experiências incríveis, a Warren vem conquistando espaço no mercado brasileiro. O novo é evolução, e a Warren surgiu exatamente para isso: ser a evolução.

Mas, para que tudo isso aconteça, precisamos dos melhores no time. Buscamos pessoas corajosas, otimistas e humildes que encarem de frente um mercado que por bastante tempo, foi controlado por empresas desalinhadas e pouco interessadas no que realmente interessa: O cliente no centro de tudo! Por isso queremos você aqui.

Nossa sede fica em Porto Alegre e já somos um time de mais de 221 pessoas incríveis. Todas dispostas a fazer o Warren acontecer e transformar a forma como o brasileiro investe.

Vamos juntos, construir o futuro da nova geração de bons investidores do país?

## Local

Nossa sede fica em Porto Alegre e já somos um time de mais de 221 pessoas incríveis. Todas dispostas a fazer o Warren acontecer e transformar a forma como o brasileiro investe.

## Sobre a oportunidade!

Você irá participar e atuar junto com o squad, na manutenção e criação de novas funcionalidades do aplicativo Android da Warren, analisando, compreendendo e discutindo os aspectos funcionais e técnicos. Temos várias equipes com projetos de diferentes atuações. Sendo responsável por:

Oferecer e fomentar uma experiência de uso fantástica já conhecida por nossos usuários;
 Implementar novas funcionalidades;
Propor melhorias;
Manter a qualidade do código buscando sempre melhoria contínua;
Versionamento;
Testes;
Deploy;
Participação na priorização de funcionalidades;
Acompanhar entregas.

## Benefícios

Benefício Flexível;
Vale Transporte;
Plano de Saúde Unifácil (100% pago pela Warren);
Aulas de Yoga semanais (40% pago pela Warren);
Parceria Oka Coliving;
Programa de Partnership;
Possibilidade de contratação PJ.

## Requisitos

Portfólio com algum projeto criado do zero ou GitHub com contribuições relevantes. Queremos ver o que você é capaz de fazer!
Bom conhecimento em Kotlin;
Conhecimento dos principais frameworks nativos para desenvolvimento Android;
Conhecimento em testes unitários e instrumentalizados.

## Contratação

CLT/PJ

## Como se candidatar

https://byintera.in/mk ou fale com nosso recrutador: https://www.linkedin.com/in/jfcornelio/

**Comment by iagotavaresst** [comment]
Onde fica a empresa em POA?
