### ISSUE TITLE
[Remoto] Desenvolvedor de Software [TODOS OS NÍVEIS] | BXBLUE

### ISSUE THREAD

**Issue by Rebeccapz** [androiddevbr/vagas#1107]
Essa vaga foi removida por não atender as [especificações do grupo de Android Dev BR](https://github.com/androiddevbr/vagas/blob/master/README.md).

Se ela for re-editada atendendo as regras descritas no [README](https://github.com/androiddevbr/vagas/blob/master/README.md), teremos prazer em aprová-la :smile:

**Comment by kammradt** [comment]
:coffee:
