### ISSUE TITLE
Android Developer (100%Remote)

### ISSUE THREAD

**Issue by ChySUbaidullah** [androiddevbr/vagas#1109]
We are looking for an Android developer who has experience in making the camera and/or OCR/scanning/receipt scanning apps.
https://join.skype.com/invite/gqlJBzyqHvdE

**Comment by davidtcdeveloper** [comment]
@ChySUbaidullah The rules of our job board state that the name of the hiring company must be listed. I will close this issue until the description is edited to adhere to the rules.
