### ISSUE TITLE
[Barueri, SP] Desenvolvedor Android Pleno

### ISSUE THREAD

**Issue by jenwendel** [androiddevbr/vagas#111]
## Descrição da vaga

Desenvolvedor Android Pleno

Responsabilidades:

- Desenvolvimento de apps em plataforma Android;

- Documentação e especificação de sistemas.

- Capacidade de estimativa de esforço para desenvolvimento.

## Local

Barueri, SP

## Benefícios
 Plano de Saúde, Plano Odontológico, Vale Transporte, Vale Alimentação, Seguro de Vida. 

## Requisitos

Obrigatórios

- Conhecimentos em noSQL, Java, xCode, Android SDK e Cordova;

- Bons conhecimentos em usabilidade;

- Capacidade de estimativa de esforço para desenvolvimento.

Desejáveis

- Prototipação de telas e fluxos

- Execução de QA

Diferenciais

- Habilidade Interpessoal

- Capacidade de negociação e argumentação

## Contratação

CLT

## Nossa empresa

A WorkIt Coaching & Hunting está auxiliando empresa na área de Análises Clínicas na contratação de um Desenvolvedor Android Pleno

## Como se candidatar

Por favor envie um email para jennifer@workitcoaching.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@jenwendel Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!
