### ISSUE TITLE
Desenvolvedor(a) Android Sênior

### ISSUE THREAD

**Issue by Anatalent** [androiddevbr/vagas#1112]
## Descrição da vaga

Projeto inovador, com grandes desafios técnicos envolvendo IoT e Big Data - Empresa multinacional de grande porte.

## Local

Campinas-sp

## Benefícios

- Férias remuneradas
- Participação nos lucros da empresa

## Requisitos

Obrigatórios
Desenvolvedor Android com mais de 3 anos de experiência em desenvolvimento Android nativo. Com experiência em Java/Kotlin. Conhecimento de padrões de arquitetura como MVP e MVVM. 
Conhecimento de Testes Unitários e Testes Instrumentados. 
Experiência com a API RESTful e sockets.
Boa experiência de trabalho em equipe.
Siga boas práticas de desenvolvimento Agile - Scrum
Bons conhecimentos de Git e butbucket.

Diferenciais
- Ter trabalhado com sistemas de coleta de dados em tempo real.

## Contratação

PJ 

## Nossa empresa

Empresa referencia em aplicativos móveis

## Como se candidatar

Por favor envie um email para recrutamento@talentreplacement.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@Anatalent Conforme as regras deste mural de vagas, é obrigatória a divulgação do nome da empresa contratante. Encerraremos esta issue até que a mesma seja editada com o nome da empresa.
