### ISSUE TITLE
Campinas, SP] Desenvolvedor Android [SENIOR] | Talent Replacement

### ISSUE THREAD

**Issue by Anatalent** [androiddevbr/vagas#1113]
## Descrição da vaga

Projeto inovador, com grandes desafios técnicos envolvendo IoT e Big Data - Empresa multinacional de grande porte.

## Local

Campinas -SP

## Benefícios

- Férias remuneradas
- Participação nos lucros

## Requisitos

Obrigatórios
Desenvolvedor Android com mais de 3 anos de experiência em desenvolvimento Android nativo. 
Com experiência em Java/Kotlin. Conhecimento de padrões de arquitetura como MVP e MVVM. 
Conhecimento de Testes Unitários e Testes Instrumentados. 
Experiência com a API RESTful e sockets.
Boa experiência de trabalho em equipe.
Siga boas práticas de desenvolvimento Agile - Scrum
Bons conhecimentos de Git e butbucket.

Diferenciais
Ter trabalhado com sistemas de coleta de dados em tempo real.

## Contratação

PJ a combinar

## Nossa empresa

Talent Replacement em parceria com uma empresa multinacional

## Como se candidatar

Por favor envie um email para recrutamento@talentreplacement.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@Anatalent Voltamos a informar que o nome da empresa é obrigatório de acordo com as regras do mural de vagas. Caso o problema continue ocorrendo, seremos obrigados a bloquear a criação de issues no mural.
