### ISSUE TITLE
OWL Developer - Meio de Pagamentos

### ISSUE THREAD

**Issue by owdeveloper** [androiddevbr/vagas#1117]
## Empresa
 OWL Developer
 Começamos como fábrica de software, mas hoje estamos focados no mercado financeiro.

## Descrição da vaga
 Desenvolvimento de app Android
 Meio de pagamento (Brasil/EUA)

## Posição
 Pleno e Senior

## Tipo de contratação
 Full time remoto PJ (Pretensão)

## Requisitos
 Vamos conversar

## Benefícios
 Férias remuneradas de 15 dias 

## Com quem você vai trabalhar
 Designer UI/UX
 Desenvolvedor Android SR
 Desenvolvedor iOS SR
 PO

## Contato
fernando@owldeveloper.com.br

**Comment by jpventura** [comment]
@owdeveloper é para atuar trabalhando diretamente com a OWL ou prestando serviço para algum cliente?

**Comment by owdeveloper** [comment]
> @owdeveloper é para atuar trabalhando diretamente com a OWL ou prestando serviço para algum cliente?

Seria direto com a gente.
