### ISSUE TITLE
[Remoto/Orlando, FL] Stormbreaker Studios - Junior Android Developer

### ISSUE THREAD

**Issue by mediumhotcoffee** [androiddevbr/vagas#1119]
## Empresa
Stormbreaker Studios is a fast-growing mobile application development agency based in Orlando, FL, with clients throughout the United States, Europe, and Asia. We specialize in native Android and iOS development for entrepreneurs and small businesses in a variety of industry sectors, including: Health & Wellness, Hospitality, Education, Utilities, and Entertainment. We take a consultative approach with our clients, helping them find ways to further their core business goals through mobile apps.

## Descrição da vaga
We are looking for a native Android developer with knowledge of Kotlin and Java. The candidate must be organized, detail-oriented and able to effectively communicate with their fellow developers, project managers, and leadership.

You may be a great fit if you:
- Have created an app (for yourself or for someone else) from scratch, that has been published on the Play Store
- Have demonstrated experience with and/or are committed to continuous learning about: Kotlin, Java, Android Studio, RESTful APIs, JSON, Firebase, Jetpack, Dagger, and RxJava
- Communicate regularly and write clean code
- Have at least 6 working hours that overlap the U.S. Eastern time zone
- Have experience working on a distributed team and/or telecommuting

## Posição
Junior Android engineer

## Tipo de contratação
- Freelancer

### Obrigatórios
- Java
- Kotlin
- Android Studio
- Git (at least working knowledge of basic operations and branching)
- Gradle

### Desejáveis
- Jira
- Hubstaff
- GitHub
- Slack
- Discord
- Firebase Auth, Realtime Database, and Firebase Storage
- Understanding of how to work with a XD and/or Sketch prototype
- Knowledge of common mobile development design patterns (e.g. MVC, MVVM, etc.)

### Diferenciais
- Knowledge of iOS development (Swift and/or Objective-C)

## Benefícios
- N/A (freelancer)

## Com quem você vai trabalhar
- [Gary Chisholm](https://www.linkedin.com/in/gary-chisholm-6348453/)
- [Charlyn Keating](https://www.linkedin.com/in/charlynkeating/)
- [Marcos Silva](https://www.linkedin.com/in/marcossilva7/)

## Como aplicar
1. Send a copy of your résumé and a link to your GitHub/Bitbucket repo (if you have one to share) to marcos@stormbreakerstudios.com, or send it on a DM to Marcos Silva on the Android Dev BR Slack — however you prefer
2. If selected, we'll contact you for a phone interview
3. After the phone interview, selected candidates have to pass an Android layout test

## Contato
If you have any questions, please reach out to us:
- Email: marcos@stormbreakerstudios.com (Marcos Silva, Project Manager)
- Slack: Marcos Silva (Android Dev BR)

**Comment by jpventura** [comment]
@mediumhotcoffee you also have a position available at the office in Orlando, or only remote?

**Comment by mediumhotcoffee** [comment]
@jpventura if you live in the US you're more than welcome to work at the Orlando office once we resume normal operations (currently we suspended the use of the office space due to the pandemic).

**Comment by mediumhotcoffee** [comment]
We were able to find a candidate for this position. Our thanks to everyone who took the time to apply and interview with us.
