### ISSUE TITLE
[São Paulo - Faria Lima] Desenvolvedor Android Nativo

### ISSUE THREAD

**Issue by helenmatos** [androiddevbr/vagas#112]
## Estamos com oportunidades para Desenvolvedor Android nível Pleno e Sênior. 
Atuar em projetos complexos e desafiadores

## Brigadeiro Faria Lima 

Escritório São Paulo - Brigadeiro Faria Lima

## Requisitos

Obrigatórios
-Experiência com android Nativo
Consumo de APIs RESTful; Conhecimentos em testes; Git

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para Helen.matos@5a.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@helenmatos Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!
