### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor(a) Android | GSURF

### ISSUE THREAD

**Issue by rafaelweis** [androiddevbr/vagas#1127]
## Descrição da vaga

Projeto de desenvolvimento de um app voltado para o meio de pagamentos.
O recurso será treinado até que seja capaz de tocar o projeto sozinho.

## Local

100% Remoto 

## Benefícios

- 1 hora de almoço
- Unimed Nacional Completa
- Vale Alimentação/Refeição
- Equipe Jovem

## Requisitos

Obrigatórios
- 2+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis
- Familiaridade com Kotlin e Java

Diferenciais
- Conhecimento em C

## Contratação

CLT a combinar

## Nossa empresa

Aqui na GSURF somos líderes no transporte de dados de maneira segura e eficiente, possuímos mais de 700k de produtos em produção transportando informação para o meio de pagamentos.

## Como se candidatar

Por favor envie um email para rafael@gsurfnet.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by lmaths** [comment]
Oi @rafaelweis , tudo joia? tenho interesse em participar do processo seletivo. Estarei enviando meu CV.
