### ISSUE TITLE
[Curitiba, PR] Desenvolvedor(a) Android | Pixelwolf

### ISSUE THREAD

**Issue by tiagotrcz** [androiddevbr/vagas#1128]
Nosso processo de seleção para Desenvolvedores Android está aberto. Buscamos profissionais com boa experiência em Kotlin.

A Pixelwolf é uma empresa sediada Curitiba que desenvolve soluções inovadoras de alta performance com foco na qualidade de código, experiência do usuário e envolvimento em grandes projetos que impactam o dia-a-dia das pessoas, principalmente nos segmentos de entretenimento (como o Jovem Nerd, Porta dos Fundos entre outros) e mercado financeiro.

• Os horários são 100% flexíveis, incluindo possibilidade de home-office (atualmente 100% home-office por conta do COVID-19);

• Buscamos profissionais que morem ou estejam dispostos a se mudar para Curitiba no futuro;

• Autonomia para tomada de decisões e uso de tecnologias;

• Remuneração entre R$ 34~68/hora de acordo com proficiência - PJ.

Para se aplicar à vaga, basta entrar em https://lnkd.in/d9JPiZs

• Após a aplicação, os desenvolvedores selecionados serão chamandos para uma rápida entrevista online individual;

• Os novos selecionados receberão um teste simples a ser concluído no período de 5 dias úteis;

• Os profissionais que tiverem o perfil mais próximo da cultura da Pixelwolf e obtiverem bons resultados no testes, serão chamados para uma nova reunião, e se tudo der certo, receber uma proposta de contratação :)

--

Job assignments:

• Develop and maintain Android apps using Kotlin/Java;

• Interact with other professionals, including designers, PMs and other developers;

• Participate in meetings with the client;

• Write clean and maintainable code;

• Review Pull Requests.

Knowledge required:

• Kotlin;

• Coroutines;

• Git;

• Android Architecture Components (ViewModel, Paging, Navigation, Room, etc);

• Firebase toolkit;

• Rest APIs;

• Dependency Injection (Koin, Dagger, Kodein or just the concept).

Desired:

• Software Architectures;

• Design Patterns;

• Unit Test;

• Basics of Continuous Integration and Continuous Delivery;

• Modularization;

• Custom Views;

•Basics of Reactive Programming (Coroutines Flow, Rx).

**Comment by jpventura** [comment]
@ttaraczuk dúvidas:

  - Localização da empresa
  - Quer realmente todos os níveis de senioridade?
  - CLT e/ou PJ?

**Comment by ttaraczuk** [comment]
> @ttaraczuk dúvidas:
> 
> * Localização da empresa
> * Quer realmente todos os níveis de senioridade?
> * CLT e/ou PJ?
 
São várias vagas, por isso não especifiquei o nível de senioridade.

Atualizado questão de localização e tipo de contratação.
