### ISSUE TITLE
(Campinas) Desenvolvedor Android Jr

### ISSUE THREAD

**Issue by dibpri** [androiddevbr/vagas#1129]
## (Campinas) Desenvolvedor Android Jr

Empresa de Tecnologia situada em Campinas/SP e Recife/CE - Porto Digital

## Campinas - in loco / Outras regiões - remoto

Remoto ou Escritório - Campinas

## Benefícios

•       Seguro Saúde Unimed (reembolso de consultas, seguro viagem) .
•       Uniodonto Campinas.
•       Seguro de vida.
•       Refeição ou Alimentação Flex - R$ 828,50
•       Estacionamento, Vale transporte e/ou Fretado.
•       Auxilio para curso de idiomas
•       Auxílio creche.
•       Gympass.
•       Educação continuada a partir de 2 anos como efetivo na empresa.
•       Parcerias e convênios diversos com alguns estabelecimentos que oferecem descontos especiais para os nossos funcionários (escolas de idiomas, restaurantes, academia, creches, etc).
•       Hora extra remunerada / Horário Flexível

## Requisitos

Obrigatórios
- 1+ anos de experiência com Android
• Experiência em desenvolvimento de software. 
•Experiência em desenvolvimento Android. 
• Linguagem Java. 
• Experiência com processos de desenvolvimento de software. 
• Experiência na elaboração de documentação (Java doc, UML, documentação de requisitos, escrita de caso de teste). 

Diferenciais
• Conhecimentos em C#, C/C++;  
• Conhecimento em desenvolvimento com Unity 3D;
• Conhecimento em Unit Test; 
• Experiência com processo Scrum/Agile; 

## Contratação

CLT

## Como se candidatar

Por favor envie um email para priscila.dib@hays.com.br com seu CV anexado - enviar no assunto: Vaga Android Jr

**Comment by davidtcdeveloper** [comment]
@dibpri Qual será a empresa contratante? As regras do nosso mural exigem a divulgação do nome da empresa contratante. Esta oportunidade será encerrada até que o nome da empresa contratante seja esclarecido.
