### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android Pleno/Sênior | Trade Force

### ISSUE THREAD

**Issue by ecarrara-araujo** [androiddevbr/vagas#113]
## Descrição da vaga

Desenvolvimento em app Android para pesquisas em pontos de venda, incluindo:
- novas funcionalidades;
- análise e correção de issues;
- evolução e refatoração.

## Local

Escritório São Paulo - Paraíso (próximo ao metrô)

## Benefícios
- Vale refeição
- Vale transporte\combustível
- Convênio médico
- Convênio odontológico
- Seguro de vida

## Requisitos

**Obrigatórios**

- Conhecimento em Java e programação OO;
- 3+ anos de experiência com desenvolvimento Android;
- Comunicação com serviços REST;
- Armazenamento de dados em storage local e sincronização de dados;
- Padrões de arquitetura e projeto como MVP, MVC, MVVM, GoF, Inversion of Control, Dependency Injection, EventBus e outros;
- Git e Github.

**Desejáveis**

- Automação de testes com JUnit, Mockito, Espresso, Robolectric etc;
- Conhecimentos em Programação Funcional e Reativa;
- Conhecimento em frameworks de banco de dados e ORM como ORMLite, Realm, DBFlow, StorIO, Requery etc;
- Libs, Frameworks e Ferramentas: Retrofit, MockWebServer, RxJava, RxAndroid, Dagger2, GCM, FCM, RetroLambda.

**Diferenciais**

- Projetos opensource;
- Artigos;
- Apresentações e Palestras.

## Contratação
CLT Full

## Nossa empresa

**História**

A Trade Force é uma empresa jovem, que identificou no mercado uma necessidade de transformar a gestão de equipes de Trade Marketing. Seu know-how de mercado, aliado ao conhecimento técnico de desenvolvimento de sistemas, e sua incansável sede por inovação possibilitou a criação de uma ferramenta extremamente aderente aos negócios dos seus clientes, agregando valor à operação e extraindo todo o potencial estratégico dos Pontos de Venda.

**O que fazemos**

Transformamos a maneira como as empresas fazem gestão de Trade Marketing, tornando os Pontos de Venda uma fonte estratégica de recursos para a tomada de decisão.

**No que acreditamos**

Somos movidos pela inovação constante, tanto no sentido tecnológico como na forma de fazer negócios. Criamos parcerias que estimulam o crescimento mútuo, através de resultados mensuráveis, soluções descomplicadas e agilidade no atendimento.

## Como se candidatar

Por favor envie um email para eduardo.carrara@tradeforce.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@ecarrara-araujo Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by ecarrara-araujo** [comment]
@walmyrcarvalho já estamos para fechar a vaga pode deixar que eu mesmo encerro aqui!
