### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor(a) Android Junior | GSURF

### ISSUE THREAD

**Issue by rafaelweis** [androiddevbr/vagas#1134]
## Descrição da vaga

Projeto de desenvolvimento de um app voltado para o meio de pagamentos.
O recurso será treinado até que seja capaz de tocar o projeto sozinho.

## Local

100% Remoto
Preferência por residentes em Florianópolis

## Benefícios

Unimed Nacional Completa
Vale Alimentação/Refeição
Equipe Jovem

## Requisitos

Obrigatórios
1+ anos de experiência com Android

Desejáveis
Familiaridade com Kotlin e Java

Diferenciais
Conhecimento em C++

## Contratação

CLT a combinar

## Nossa empresa

Aqui na GSURF somos líderes no transporte de dados de maneira segura e eficiente, possuímos mais de 700k de produtos em produção transportando informação para o meio de pagamentos.

## Como se candidatar

Por favor envie um email para rafael.frasson@gsurfnet.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by pedrofsn** [comment]
O @newtonjrfs passou neste processo seletivo e já iniciou as atividades na empresa, acredito que a vaga esteja fechada.
