### ISSUE TITLE
Desenvolvedor(a) Android

### ISSUE THREAD

**Issue by tawaneTavares** [androiddevbr/vagas#1137]
Requisitos:
• Superior completo em Ciências da Computação, Engenharia, Sistemas da Informação ou áreas afins.
• Experiência com aplicativos em Android nativo, no mínimo 2 anos;
• Android Support Library;
• Trabalhar com diferentes dimensões de dispositivos (Tablet, celular e afins);
• Trabalhar realizando testes, code review, integração continua e afins;
• Experiência com Java;
• Conhecimento com Google Play Services;
• Ter trabalhado com API Level 14
.
Desejáveis:
• Mockito/PowerMock/Similares
• Android NDK
• Boa bagagem de conhecimento com biblitotecas comuns ao desenvolvimento Android (Retrofit, Dagger, etc)
• Scrum / Kanban
• Contato com Kotlin
• Abordagem voltada a testes (TDD)
• Experiência em programação reativa
• Boas práticas de desenvolvimento (SOLID, KISS, DRY)

Por favor envie um email para rh@approvata.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@tawaneTavares As regras do nosso mural de vagas obrigam a especificação da empresa contratante. A vaga será encerrada até que seja editada com a especificação da empresa.
