### ISSUE TITLE
Android Dev - Meio de Pagamento - Brasil x EUA

### ISSUE THREAD

**Issue by owdeveloper** [androiddevbr/vagas#1141]
## Empresa
 OWL Developer
 Começamos como fábrica de software, mas hoje estamos focados no mercado financeiro.

## Descrição da vaga
 Desenvolvimento de app Android
 Meio de pagamento (Brasil/EUA)

## Posição
 Pleno e Senior

## Tipo de contratação
 Full time remoto PJ (Pretensão)

## Requisitos
 Vamos conversar

## Benefícios
 Férias remuneradas de 15 dias 

## Com quem você vai trabalhar
 Designer UI/UX
 Desenvolvedor Android SR
 Desenvolvedor iOS SR
 PO

## Contato
fernando@owldeveloper.com.br

**Comment by rsalomao2** [comment]
Contrato internacional ou nacional?

**Comment by owdeveloper** [comment]
Nacional
