### ISSUE TITLE
[São Paulo - Henri Dunant] Hitss - Desenvolvedor Android Sênior

### ISSUE THREAD

**Issue by Leonardolira01** [androiddevbr/vagas#1142]
## Hitss / K2 PARTNERING SOLUTIONS
Cliente final é do segmento de TELECOM

## Tipo de contratação
Presencial, PJ, tempo de contrato inicialmente 6 meses. 

## Como aplicar
Encaminhar CV atualizado para LEONARDO LIRA da Consultoria K2 PARTNERING SOLUTIONS com a pretensão da sua taxa hora para o seguinte e-mail: 
loliveira@k2partnering.com

## Contato
loliveira@k2partnering.com
Skype: leonardolirak2
11953923881

**Comment by davidtcdeveloper** [comment]
@Leonardolira01 Conforme regras deste mural de vagas, é obrigatória a divulgação da empresa contratante. Esta vaga será fechada até ser editada com o nome da empresa.
