### ISSUE TITLE
Desenvolvedor(a) Mobile - Startup de Segurança 

### ISSUE THREAD

**Issue by AmandaPrestes** [androiddevbr/vagas#1143]
## Descrição da vaga

Desenvolvedor(a) mobile com perfil hands on, atuando no desenvolvimento e apoio na solução técnica;
Experiência no desenvolvimento de aplicações mobile;
Desejável experiência ou interesse em atuar com a linguagem de programação flutter.

## Local

Leblon/RJ

## Benefícios

- Plano de saúde para colaborador e dependentes
- VR e VA
- Vale transporte sem desconto em folha
- Home Office 2 vezes por semana 
- Aluguel por 1 ano para pessoas que não moram no RJ.

## Requisitos

Obrigatórios
- Experiência com desenvolvimento Android 
- Kotlin / Xamarin
- Graduação completa

Desejáveis
- Conhecimento em Flutter 

## Contratação

CLT

## Nossa empresa

A Integrity Group é uma consultoria especializada em recrutamento e seleção e hoje temos uma posição para atuar na startup Gabriel. A Gabriel é uma startup de tecnologia criada em 2019, localizada no Rio de Janeiro e focada em resolver problemas de segurança. O objetivo é oferecer uma solução de tecnologia, baseada em inteligência artificial para a população. 

## Como se candidatar

Por favor envie um e-mail para amanda.prestes@integritygroup.com.br com seu CV anexado - enviar no assunto: Vaga Mobile

**Comment by davidtcdeveloper** [comment]
@AmandaPrestes Como as regras do mural de vagas exigem a divulgação do nome da empresa contratante, pedimos mais detalhes sobre a mesma para evitar problemas. Poderia nos passar o site da mesma, rede social e afins?

**Comment by AmandaPrestes** [comment]
Claro!!

A empresa é a Startup Gabriel

Site: https://gabriel.com.br/

A vaga também foi divulgada no nosso linkedin (
https://www.linkedin.com/company/beitrecruitment/)

Obrigada :)

*Amanda Prestes*

*Recruiter*

Tel.: +55 11 3042-5100 (Ramal 1058)
<http://www.integritygroup.com.br/>  <http://beit.work/>
Siga nossas redes sociais e acompanhe nossas vagas:
<https://www.facebook.com/integrityconsulting>
<https://www.linkedin.com/company/integrityrecruitmentgroup>
<https://www.instagram.com/integrityrecruitment/>

<https://www.youtube.com/channel/UCPs83C3FNMP3FH6NMqc7Qnw?view_as=subscriber>


Em seg., 29 de jun. de 2020 às 17:36, David Tiago Conceição <
notifications@github.com> escreveu:
