### ISSUE TITLE
[SP - Consolação] Desenvolvedor Android Sênior | QuintoAndar

### ISSUE THREAD

**Issue by rsacchi** [androiddevbr/vagas#115]
## Descrição da vaga

Trabalhar na versão Android dos produtos do QuintoAndar.

## Local

Presencial em São Paulo - Consolação

## Benefícios

- VA e VR
- VT
- Plano de saúde
- 40 dias de férias por ano
- Free beer às sextas-feiras
- Subsídio a academia de ginástica
- Ambiente típico de startup (informal, divertido, pode trabalhar de bermuda e chinelo, etc)

## Requisitos

Obrigatórios

- Ser graduado em Ciência da Computação, Engenharia da Computação ou equivalente
- Tem profundo conhecimento do SDK do Android
- Já desenvolveu aplicativos relevantes
- Inglês fluente
- Tem alta capacidade analítica

Desejáveis

- Experiência com RxAndroid
- Experiência com desenvolvimento backend
- Já trabalhou com times de produto e UX
- Conhece bem Material Design

Diferenciais

- Conhecimento de desenvolvimento iOS

## Contratação

CLT

## Nossa empresa

O QuintoAndar é uma empresa de tecnologia que facilita o processo de aluguel de imóveis do início ao fim. Usamos tecnologia e design para redesenhar o processo de locação e proporcionar o tipo de experiência que gostaríamos para nós mesmos. Estamos criando um novo modelo de negócios que é único no mundo inteiro e que vai revolucionar o setor imobiliário. Contamos com o suporte de alguns dos melhores investidores do mundo: Kaszek Ventures, Graph Ventures, e Kevin Efrusy from Accel Partners..

## Como se candidatar

Enviar um email para rafael.sacchi@quintoandar.com.br com o assunto "Vaga - Senior Android software engineer" com o CV anexo. Bônus se enviar os perfis de LinkedIn, GitHub e StackOverflow.

**Comment by walmyrcarvalho** [comment]
Ótima vaga! :)

**Comment by walmyrcarvalho** [comment]
@rsacchi Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by rsacchi** [comment]
@walmyrcarvalho preencheu semana passada, pode fechá-la.
