### ISSUE TITLE
[Fortaleza, CE] Desenvolvedor(a) Android Junior ou Pleno | Instituto Nordeste Cidadania (INEC)

### ISSUE THREAD

**Issue by jeancsanchez** [androiddevbr/vagas#1153]
## Descrição da vaga

Acreditamos que os nossos colaboradores constituem o mais importante elemento para a transformação da realidade de comunidades e entidades ainda carentes de políticas públicas e acesso à cidadania.
O INEC está em busca de pessoas talentosas, apaixonadas pelo que fazem e que querem ir cada vez mais longe.
O Analista atuará no time da Tecnologia da Informação realizando análises de requisitos dos sistemas de negócio para desenvolver customizações ou novos sistemas visando otimizar continuamente os processos da instituição.
Se você é um profissional organizado e que possui bom planejamento, o INEC é o seu lugar! 
Venha fazer parte dessa família essencialmente FEITA DE GENTE!

## Local

Fortaleza, CE - Itaperi

## Benefícios

- Treinamentos Internos e Externos;
- Plano de Saúde;
- Plano Odontológico;
- Plano de Previdência Privada;
- Auxílio Alimentação e Auxílio Cesta Básica;
- Auxílio Creche para filhos de até 06 anos; 
- Convênio com academias;
- Seguro de vida.

## Requisitos

Obrigatórios
- 2+ anos de experiência com Android;
- Linguagem Kotlin ou Java;
- Entendimento do ecossistema Android e ciclo de vida das Activities;
- Confortável com o padrão MVP, MVVM e derivados;
- Testes unitários com JUnit e Testes de UI em Android;
- Conhecimentos em padrões de projeto e boas práticas de POO.
- Experiência com comunicação usando o padrão Restful;

Diferenciais
- Experiência com JavaScript (Reactjs e/ou Nodejs);
- Experiência com o Framework Spring Boot;
- Linguagem SQL (SQL Server);
- Princípios SOLID, DDD e TDD;
- Ter algum projeto publicado na Google Play ou Open Source.

## Contratação

CLT (Salário Base: R$ 5.437,88)

## Nossa empresa

Fundado em 1993, o Instituto Nordeste Cidadania (Inec) é uma Organização da Sociedade Civil (OSC), qualificada como Organização da Sociedade Civil de Interesse Público (Oscip) desde 2003, que tem como foco principal o desenvolvimento sustentável de comunidades na região Nordeste do Brasil.

A qualificação como Oscip possibilitou a celebração de termo de parceria com o Banco do Nordeste para operacionalizar o Crediamigo, programa de microfinança urbana. E, em 2005, de forma inovadora, lançou, juntamente com o Banco do Nordeste, o primeiro programa de microfinança rural para agricultores familiares da América do Sul, o Agroamigo.

Com os dois programas, o Inec atende, anualmente, cerca de 3,5 milhões de microempreendedodes e agricultores familiares, com mais de 13 bilhões investidos em 2019.

![foto dos colaboradores](https://s3.amazonaws.com/gupy5/production/companies/600/career/714/images/institutionalImage1.jpg)

## Como se candidatar

Acesse o site **www.inec.org.br** e clique em “Trabalhe Conosco” para cadastrar seu currículo e candidatar-se a vaga no período até **19/07/2020**.

**Comment by JuarezLopesJr** [comment]
@jeancsanchez Bom dia, essa vaga ainda esta "open"  aqui, mas no site nao aparece opcao de cadastro, eu vi que era ate 19/07, por isso minha duvida, existe outra forma de aplicar para a vaga ? Grato

**Comment by jeancsanchez** [comment]
@JuarezLopesJr  Realmente já está fechada. A única forma de se candidatar era pelo site mesmo :/

**Comment by jeancsanchez** [comment]
@JuarezLopesJr Foi prorrogada até o dia 10/08/20. Corre!

**Comment by JuarezLopesJr** [comment]
@jeancsanchez Grato pelo aviso, ja apliquei la. Valeu!
