### ISSUE TITLE
[Porto Alegre, RS] Desenvolvedor Android | Pulsus.mobi

### ISSUE THREAD

**Issue by bzanchet** [androiddevbr/vagas#116]
## Descrição da vaga

Somos uma empresa inovadora e com crescimento muito rápido, atendendo clientes de abrangência nacional e internacional, e nosso time está precisando de reforços.

Procuramos um(a) profissional com experiência em desenvolvimento Android nativo, muito interesse em aprender e sangue frio para lidar com um software que afeta diretamente o trabalho de milhares de pessoas todos os dias! :-)

## Local

Escritório em Porto Alegre/RS.

## Benefícios

- oportunidade de trabalhar numa empresa em franco crescimento com amplas oportunidades de crescimento profissional;
- trabalhar diretamente com clientes de renome nacional e internacional, lidando com sistemas críticos para a operação do dia-a-dia (_with great power comes great responsibility..._);
- trabalhar com tecnologias bem recentes e as melhores práticas em desenvolvimento de software;
- em um time pequeno e experiente, num ambiente transparente, amigável e informal.

## Requisitos

Obrigatórios
- profissional com experiência em desenvolvimento de Apps nativas para Android - iOS é bônus;
- alguma experiência com sistemas web de grande escala;
- interesse em aprender, saber trabalhar em equipe e conversar, curiosidade intelectual para resolver problemas (necessariamente!).

Diferenciais
- Experiência com sistemas de MDM

## Contratação

A combinar

## Nossa empresa

Nossa empresa está se consolidando e montando seu primeiro escritório em Porto Alegre. Desenvolvemos um sistema completo de gerenciamento de dispositivos móveis e já temos milhares de celulares e tablets na rua que dependem disso para as mais variadas tarefas. Estamos começando a dar o próximo passo: organizar e aprender com essa quantidade enorme de dados para extrair informações relevantes.

## Como se candidatar

Favor enviar uma pequena descrição do seu perfil e o link pro seu Github ou LinkedIn; e o nome do último livro técnico que você leu para contato@pulsus.mobi

**Comment by walmyrcarvalho** [comment]
@bzanchet Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by plentz** [comment]
@walmyrcarvalho ta aberta ainda sim :)
