### ISSUE TITLE
[REMOTO] Invillia - Desenvolvedor(a) Android Sênior 

### ISSUE THREAD

**Issue by GabriellyLeonel** [androiddevbr/vagas#1169]
## Local

100% R E M O T O - vagas a nivel mundial!! :)

## Benefícios

- 2 horas de almoço
- va, vr, am, ao, seguro de vida.
- Ajuda de custo remoto. 

## Requisitos
Sólida experiência em desenvolvimento Mobile utilizando a plataforma Android;
Amplos conhecimentos em Java e Kotlin,
Integração de sistemas via REST Api;
Testes de interface e testes unitários.
Experiência em desenvolvimento e integração com aplicações utilizadas em larga escala com foco em performance e utilização racional de recursos.
Conhecimento em arquiteturas móveis como MVP, MVVM e Viper.

## Contratação

CLT - encaminhe sua pretensão salarial junto com o cv. 

## Nossa empresa

A experiência de trabalhar na Invillia é única. E global. Temos o nosso próprio jeito de conectar talentos e construir inovações.

Revolucionamos o ambiente de trabalho #Instation + somos experts em desenvolver soluções complexas para #GameChangers + temos uma metodologia única #EngagedbyDataPeopleAction + investimos em pessoas #InvilliaAcademy

Alguns diferenciais Invillia:
_inovamos lado-a-lado com #GameChangersGlobais
_cultura de trabalho distribuído #inStation
_metodologia exclusiva #GlobalGrowthFramework
_benefícios únicos entre as techs #InfinitePowers

Faça uma imersão aqui https://invillia.com/

## Como se candidatar
Se inscreva na vaga por este link: https://invillia.gupy.io/jobs/260649?jobBoardSource=gupy_public_page e não esqueça de preencher seus dados para contato. 

Suporte pelo e-mail: gabrielly.leonel@invillia.com

**Comment by davidtcdeveloper** [comment]
@GabriellyLeonel O link para inscrição direciona para uma página que pede login da empresa, não parece estar correto. Poderia conferir?

**Comment by GabriellyLeonel** [comment]
David, alterei para este: https://invillia.gupy.io/jobs/260649?jobBoardSource=gupy_public_page acho que agora vai. Muito obrigada!!
