### ISSUE TITLE
[SP - Metrô Santa Cruz] - Desenvolvedores Android - Pleno e Senior | Studo+

### ISSUE THREAD

**Issue by thiagonetorh** [androiddevbr/vagas#117]
## Descrição da vaga
Estamos procurando desenvolvedores Android que sejam apaixonado por desenvolver aplicações inovadoras que desafiam limites técnicos. O candidato irá trabalhar com nosso time de engenheiros, ajudando a desenhar e construir nossa próxima geração de apps e manter nossa primeira versão até a descontinuação.

Desenvolvimento e design de aplicações avançadas na plataforma Android;
Colaborar com times multi-funcionais para definir, desenhar e publicar novas features;
Trabalhar com APIs REST e outros datasources externos;
Escrita e manunteção de testes em busca de robustez, usabilidade e qualidade em geral;
Correção de bugs e improve de performance da aplicação;
Interessante em continuamente descobrir, avaliar e implementar novas tecnologias para maximizar nossa eficiência de desenvolvimento.

## Local
Escritório no Metrô Santa Cruz - São Paulo

## Benefícios

- Assistência médica Omint - sem desconto
- VR de R$ 25,00 / dia
- Máquinas de snacks grátis
- PLR
- Horário flexível

## Requisitos

Obrigatório
Experiência em desenvolvimento de software, focado em Android;
Experiência ou conhecimento teórico de metodologias ágeis (XP e Scrum);
Apps publicados são considerados diferenciais para o candidato;
Sólida experiência com SDK Android;
Experiência com consumo de dados via REST e padrão JSON;
Conhecimentos gerais do ambiente mobile, como arquiteturas, padrões, tendências e tecnologias emergentes.

## Contratação
CLT

## Studo+
Quem somos
Somos uma startup que busca a melhoria do aprendizado na educação básica. Nosso foco é entender a dinâmica do aprendizado dos alunos, dentro e fora da sala de aula, e propor ações que os levem a maximizar seu potencial.

O que fazemos
Desenvolvemos uma plataforma de gestão e interação educacional para compreender e apoiar o aprendizado, valorizando todos os atores envolvidos no processo.

## Como se candidatar

Por favor envie um email para thiagonetorh@gmail.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@thiagonetorh Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by walmyrcarvalho** [comment]
Fechando essa vaga, uma similar já está aberta: https://github.com/androiddevbr/vagas/issues/133
