### ISSUE TITLE
Campinas, São Paulo - Desenvolvedor(a) Android Pleno/Sr

### ISSUE THREAD

**Issue by Bridgeyou2** [androiddevbr/vagas#1171]
Buscamos um Desenvolvedor(a) Android para oportunidade para atuação em projeto junto à empresa multinacional da área de telefonia móvel, em contato frequente com times no exterior.

 **Responsabilidades / Desafios:**

Desenvolvimento de novas funcionalidades para um aplicativo Android relacionado à área de marketing/vendas;
Prototipação e validação de funcionalidades;
Design Patterns e proposição de soluções;
Revisão de código;
Correção de bugs e adaptação de funcionalidades as novas versões de Android.

**Conhecimentos / Experiências:**

Inglês Avançado;
Experiência em desenvolvimento Android;
Conhecimento em Kotlin.

**Contratação**

CLT a combinar

**A posição será home-office até o final do ano e depois negociado presencial ou semi presencial em Campinas/SP;**

## Como se candidatar

Pelo link:
https://www.linkedin.com/jobs/cap/view/1953139148/?pathWildcard=1953139148&trk=mcm

**Comment by davidtcdeveloper** [comment]
@Bridgeyou2 As regras do nosso mural exigem a divulgação do nome da empresa contratante. Estamos encerrando a issue até que o nome seja incluído.
