### ISSUE TITLE
[Campinas - SP]  Desenvolvedor Android Sênior - One Choice Recrutamento 

### ISSUE THREAD

**Issue by OneChoiceRH** [androiddevbr/vagas#1173]
## Nossa empresa
Olá, nós somos a One Choice, uma empresa que faz seleção e recrutamento de talentos de TI. 
Veja as vagas em aberto para Desenvolvedor Android Sênior https://www.onechoice.com.br/vagas/662

Temos diversas outras vagas abertas em nosso site

## Descrição da vaga
REQUISITOS
Proficiência em Java.
Bom conhecimento de Kotlin.
Boa experiência com o Git.
Conhecimento de bibliotecas do Android como Retrofit, RxJava, Dagger2.
Conhecimento de padrões de arquitetura como MVP e MVVM.
Conhecimento de Testes Unitários e Testes Instrumentados.
Experiência com a API RESTful.
Excelente comunicação interpessoal com fortes habilidades verbais / escritas em inglês (Nível B2 - Avançado).
DESEJÁVEL

Conhecimento do Android JetPack (Componentes de Arquitetura é importante).
Experiência com metodologias ágeis, como Kanban e Scrum.
Experiência com o sistema de gerenciamento de software, preferencialmente JIRA.
Interesse contínuo em aprender novas tecnologias.
Experiência de trabalho em equipe e entusiasmo pelo desenvolvimento e fornecimento de novos recursos para nossos produtos.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para talentos@onechoice.com.br com seu CV anexado, pretensão salarial e nome da vaga - enviar no assunto o nome da vaga

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by davidtcdeveloper** [comment]
@OneChoiceRH as regras do nosso mural obrigam a divulgação da empresa contratante. A vaga será fechada até que o nome seja incluído.
