### ISSUE TITLE
DESENVOLVEDOR MOBILE PL/SR - Somos Educação

### ISSUE THREAD

**Issue by rmello** [androiddevbr/vagas#1174]
## Descrição da vaga

- Desenvolver o aplicativo mobile da plataforma do Plurall;
- Discutir novas funcionalidades e a melhor forma de implementar com foco em usabilidade e reutilização;
- Planejar e arquitetar novas features bem como manter e refatorar features existentes;
- Trabalhar em um ambiente ágil dividido em Squads e Tribos;
- Ter foco na qualidade, garantindo seja de alta qualidade, uma boa cobertura de testes e, principalmente, que faça todo o sentido dentro das regras de negócio;
- Criar e ser responsável por novos produtos que impactam a educação de jovens por todo o Brasil!

## Local

Remoto ou Escritório em Bauru, São Paulo (capital), Rio de Janeiro (capital) 

## Benefícios

Nossas posições possuem um atraente pacote de remuneração e benefícios como dresscode be-yourself/havaianas friendly, bolsas de estudo em nossas marcas, Clube K-Vantagens, entre outros! 

Se você é uma pessoa com deficiência e está em dúvida se alguma das nossas vagas abertas é pra você, fique tranquilo, TODAS são para você também.

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis
- Experiência com Espresso e UI Automator
- Experiência com RxJava

Diferenciais
- Experiência com Swift/iOS

## Contratação

CLT a combinar

## Nossa empresa

A Somos Educação é um dos principais grupos de Educação Básica do Brasil e fazemos parte do Grupo Cogna que com mais de 50 anos de atuação, é uma das maiores empresas do setor de educação do mundo!

Oferecemos um amplo portifólio de soluções educacionais como sistemas de ensino, editoras, além de uma tecnológica plataforma de aprendizado digital e de e-commerce.

Há pouco tempo, fizemos nossa estreia na Nasdaq, Bolsa de Valores norte-americana.

Este passo nos orgulha muito pelo reconhecimento de sermos a terceira empresa brasileira de #educação listada na Bolsa de Valores Nasdaq; e, principalmente, por nos permitir ampliar nossos serviços de apoio à #escola!

## Como se candidatar

Por favor envie seu CV no link da vaga https://jobs.kenoby.com/somos/job/desenvolvedor-mobile-plsr/5f29f63b7bbb7d71aa2186ba

**Comment by pedrofsn** [comment]
Enviado :)
