### ISSUE TITLE
[Alphaville - SP] Desenvolvedor Android Pleno | Iteris 

### ISSUE THREAD

**Issue by faeldix** [androiddevbr/vagas#118]
## Descrição da vaga

A Iteris é uma empresa de serviços de TI focada no desenvolvimento de Aplicações Colaborativas, soluções de Automação de Processos (workflows), Portais de Intranet e Internet, Business Intelligence e Desenvolvimento de Sistemas Customizados. Conta com uma equipe de profissionais experientes e altamente especializados, buscando atender aos requisitos de negócio de empresas de grande porte nacionais e multinacionais, atuando como uma extensão de suas áreas de Tecnologia da Informação. 

## Local

Barueri - SP

## Benefícios

Oferecemos pacote atraente de remuneração, benefícios e plano de carreira focado em desenvolvimento profissional e pessoal.

## Requisitos

Obrigatórios:
* Experiência em projetos de desenvolvimento Mobile;
* Experiência no uso de tecnologias baseadas em Java, Spring, Android, Javascript, Angular.Js, Http, Rest, Soap e Git.
* Inglês Técnico.

Diferenciais
* Conhecimento em IOS, Objective C, Node, Express, C#, .Net, Wcf, SharePoint e Starteam.
* Nível superior

## Contratação

a combinar

## Nossa empresa

Diferenciando-se na gestão de pessoas e excelência de seu corpo consultivo, vem figurando desde 2011 na lista das melhores empresas para trabalhar em TI & Telecom no Brasil, em pesquisa conduzida pelo instituto "Great Place to Work".

Através de parcerias estratégicas com empresas como Microsoft, Qlik e Nintex, a Iteris oferece soluções altamente produtivas para seus clientes, com foco em custo-benefício diferenciado e entrega de valor em projetos de TI.

## Como se candidatar

https://www.linkedin.com/jobs/view/260153878

**Comment by walmyrcarvalho** [comment]
@faeldix Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!
