### ISSUE TITLE
Desenvolvedor (a) Android (Manaus) (Presencial) (CLT) (Instituto Eldorado Manaus)

### ISSUE THREAD

**Issue by joyce1214** [androiddevbr/vagas#1183]
# Informações importantes
Para que as vagas enviadas neste mural sejam categorizadas com as labels, as mesmas devem seguir as seguintes regras:
1. Todas as vagas enviadas neste mural devem estar de acordo com o Código De Conduta da nossa comunidade: https://github.com/androiddevbr/codigo-de-conduta. Vagas que violem este Código de Conduta serão automaticamente editadas e encerradas pela equipe de moderação.
2. Procure utilizar termos e descrições que façam o mínimo de distinção de gênero. Por exemplo, utilize "Desenvolvedor(a)", "Programador ou Programadora" ou "Pessoa".
3. Adicione links ou descreva as políticas de inclusão, não discriminação e afins adotadas pela empresa.
4. As vagas enviadas neste mural serão automaticamente divulgadas no canal #job-alerts do Slack da nossa comunidade.
5. Remova este bloco inicial antes de divulgar a vaga.

## Desenvolvedor(a) Android

Nesse projeto você irá trabalhar em um projeto em parceria com multinacional da área de telefonia móvel, interagindo com equipes de vários países.

## Benefícios

- Bolsa idiomas;
- Pós graduação ou concessão de horas para mestrado/doutorado;
- Plano saúde e odontológico;
- Vale refeição e alimentação;
- Bônus anual (conforme performance);
- Previdência privada;
- Seguro de vida;
- Estacionamento;
- Horário flexível;

## Requisitos

Obrigatórios
- Experiência com desenvolvimento de aplicações Android;
- Experiência em ferramentas de Controle de Versão;
- Conhecimento forte em arquitetura de sistema mobile;
- Experiência com Kotlin;
- Inglês Avançado.

## Contratação

CLT

## Nossa empresa

Way Consultoria busca profissionais da área de Tecnologia para trabalhar em um Instituto de Pesquisa e Desenvolvimento.

## Como se candidatar

Por favor envie um email para way@way-consultoria.com com seu CV anexado - enviar no assunto: Vaga Desenvolvedor(a) Android.

**Comment by davidtcdeveloper** [comment]
@joyce1214 Conforme regras do mural da comunidade, o nome da empresa contratante deve ser divulgado. Iremos encerrar a issue até que a mesma seja editada com o nome da empresa.

**Comment by joyce1214** [comment]
Já inclui o nome da empresa no título.

**Comment by joyce1214** [comment]
Olá Boa tarde!

Já fiz a inclusão do nome da empresa contratante. 

Já editei. Se puderem revisar, agradeço.

 

Att,

 

 



 

 

 

 

De: David Tiago Conceição <notifications@github.com> 
Enviada em: segunda-feira, 17 de agosto de 2020 12:40
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: joyce1214 <joyce@way-consultoria.com>; Mention <mention@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] Desenvolvedor (a) Android (Manaus) (Presencial) (CLT) (#1183)

 

@joyce1214 <https://github.com/joyce1214>  Conforme regras do mural da comunidade, o nome da empresa contratante deve ser divulgado. Iremos encerrar a issue até que a mesma seja editada com o nome da empresa.
