### ISSUE TITLE
[São Paulo / Rio de Janeiro] Desenvolvedor Android | Concrete Solutions

### ISSUE THREAD

**Issue by rafaeltoledo** [androiddevbr/vagas#12]
## Descrição da vaga

Participar de equipe mobile com desenvolvimento na plataforma Android.
Trabalho em horário integral, presencial.
## Local

Centro do Rio de Janeiro / Zona Sul de São Paulo
## Requisitos

É necessário apresentar os seguintes conhecimentos.
- Controle de versão distribuído (Git e/ou Mercurial)
- Ciclo de vida de activities e fragments
- Boas práticas de desenvolvimento mobile
- Conhecimento em Java, orientação a objeto e design patterns
- Integração com APIs RESTful e/ou Webservices
- Familiaridade com o Android Studio / Eclipse
- Familiaridade com componentes de User Interface do Android
- Adaptação de layouts para diferentes tamanhos de telas e dispositivos
- Conhecimento das guidelines de design do Google Play e de desenvolvimento
- Conhecimento de metodologias ágeis (Scrum e XP)
- Fluência em inglês (leitura técnica)

Pontos extras:
- Portfólio de aplicativos no Google Play
- Conhecimento sobre integração contínua (build, test, relatórios) e entrega contínua (deploy)
## Contratação

CLT
## Nossa empresa

[Concrete Solutions](http://www.concretesolutions.com.br) e [blog](http://blog.concretesolutions.com.br)
## Como se candidatar

[Android Pleno SP](https://www.bizut.me/vagas/perfil/692/13)
[Android Sênior SP](https://www.bizut.me/vagas/perfil/691/13)
[Android Pleno RJ](https://www.bizut.me/vagas/perfil/1154/13)
[Android Sênior RJ](https://www.bizut.me/vagas/perfil/1153/13)

**Comment by walmyrcarvalho** [comment]
@rafaeltoledo Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by rafaeltoledo** [comment]
@walmyrcarvalho essas vagas são sempre abertas. Sei que estão com urgência pra São Paulo.

**Comment by walmyrcarvalho** [comment]
@rafaeltoledo Beleza, just checking. :)
