### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor(a) Mobile Android Nativo [Pleno|Sênior]

### ISSUE THREAD

**Issue by JosiDeloeken** [androiddevbr/vagas#1200]
Desenvolvedor Mobile Nativo Android  - Remoto
Empresa de Florianópolis/SC

Requisitos:
· Pelo menos 3 anos de experiência em desenvolvimento mobile Android;
· Experiência em Java;
· Conhecimento JSON, REST, SOAP;
· Conhecimentos em Retrofit, Android Annotations, Material Designer, Push Notification e LiveData;
· Princípios de interface ao usuário;
· Conhecimento nos principais Design Patterns;
· Conceito de código limpo e melhores práticas;
· Conhecimento em Git;
· Conhecimentos em Métodos Ágeis (Agile/Scrum).

Tipo Contratação: CLT ou PJ

Candidatura: Enviar currículo com pretensão salarial para recrutamento@brtec.info

**Comment by davidtcdeveloper** [comment]
@JosiDeloeken as regras do nosso mural de vagas exigem a divulgação da empresa contratante. Esta issue será encerrada até que seja editada e tenha o nome da empresa.
