### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android - Youse

### ISSUE THREAD

**Issue by janainakovacs** [androiddevbr/vagas#121]
## Desenvolvedor Android

Precisamos de gente boa pra desenvolver programas, codificar e testar em plataformas Android, com foco no ambiente mobile. Que tal trabalhar com a gente? \o/

## Local

São Paulo - Vila Olímpia

## Contratação

CLT com excelente pacote de benefícios

#### Prezamos por qualidade de software

- Gostamos de arquiteturas testáveis. MVP e clean architecture fazem parte do nosso dia a dia;
- Temos um profissional de QA dedicado ao time mobile. Sem essa de testes manuais;
- Aqui é jUnit e Espresso na veia! :wink:
- Temos code review levado a sério!

#### Gostamos de tecnologias f0*@!

- Amamos RxJava2!
- Somos modernos! Retrô, só fit e lambda!
- Ainda não usamos Kotlin em produção, mas nesse quarter sai! :slightly_smiling_face:
- Utilizamos Dagger2!

#### Como trabalhamos?

Trabalhamos em squads, um modelo bastante inovador, que prioriza a autonomia. Quer saber mais? Clica aê: https://www.youtube.com/watch?v=Mpsn3WaI_4k #squad #Inovação #Autonomia;
- Atuamos de forma presencial, com horários flexíveis;
- A Youse tem inovação no DNA: dedicamos alguns dias do mês para tirar ideias do papel. :wink:

Ainda não trabalha como a gente? **Não tem problema!**
Adoramos ensinar e aprender coisas novas!
## Como se candidatar

Cadastre-se em vemprayouse.com
![desenvolvedor android 1](https://cloud.githubusercontent.com/assets/17124738/21828875/19be069c-d77a-11e6-9f15-6275ef588252.png)

**Comment by davidtcdeveloper** [comment]
Oi @janainakovacs, obrigado por cadastrar a vaga em nosso mural.
Recomendamos sempre cadastrar a vaga com o título no formato `[Cidade, Estado] Descrição da vaga (Ex.: Desenvolvedor Android Pleo | Nome da empresa`.
Desta forma fica bem mais fácil para os interessados pesquisarem por cidade, estado ou nível de conhecimento.

**Comment by walmyrcarvalho** [comment]
@janainakovacs Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by janainakovacs** [comment]
Olá Walmyr, esta sim e agora sao duas vagas! Abs,

Em sábado, 8 de abril de 2017, Walmyr Carvalho <notifications@github.com>
escreveu:
