### ISSUE TITLE
[SÃO PAULO] Quality Assurance na Cora

### ISSUE THREAD

**Issue by DebyTorres** [androiddevbr/vagas#1214]
**[OPORTUNIDADE] [SÃO PAULO] [QA]**

A **Cora** é uma empresa  **Start Up** que está apoiando e simplicando a gestão financeira do empreendedor, resolvendo as dificuldades de gerenciar as finanças das pequenas e médias empresas. Reconhecida como um dos melhores lugares para trabalhar no Brasil. A Cora recebeu um aporte de US$ 10 milhões, numa captação liderado pelos fundos de capital Kaszek e Ribbit. Assim, a Cora vem crescendo e buscando criar um produto de classe mundial, incrível né?!

Estamos com uma vaga aberta para **Quality Assurance (Q&A)** para atuar na Cora. Buscamos pessoas com um **perfil #sênior,** com experiência em **desenvolvimento e testes mobile/web**. Importante conhecer **ao menos uma #linguagem de programação orientada a objetos.**

Forma de Contratação: CLT

Você está aberto(a) a essa oportunidade e quer saber mais sobre esse desafio, ou conhece alguém que pode se interessar? 

Dá uma olhada nesse link que contém todas as informações da vaga: [https://byintera.in/13n](url)

**Comment by davidtcdeveloper** [comment]
@DebyTorres Este mural de vagas é focado em oportunidades para desenvolvimento Android. Como esta oportunidade não cita Android, a mesma será removida.
