### ISSUE TITLE
[Remto] Desenvolvedor Android JUNIOR|PLENO|

### ISSUE THREAD

**Issue by LuNogueira** [androiddevbr/vagas#1218]
## Descrição da vaga

Projeto de desenvolvimento de aplicativos internos de Industria.

## Local

Remoto 

## Requisitos

Obrigatórios
- 1+ ano de experiência com Android
JAVA 8
Spring Framework / SpringBoot
Gradle ou Maven
Hibernate
Banco SQL
Repositório Git

Desejáveis
- Experiência com Espresso e UI Automator
- Experiência com RxJava

## Contratação (Alocação)

PJ (valor/hora)

## Mazzatech

Transformamos oportunidades em sucesso, impulsionando o potencial de cada profissional através da nossa precisão em identificar talentos.

## Como se candidatar

Por favor envie um email para lucas@mazza.tech com seu CV anexado - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@LuNogueira A contratação será feita pela Mazzatech ou por outra empresa?

**Comment by LuNogueira** [comment]
será por nós @davidtcdeveloper
