### ISSUE TITLE
[Rio de Janeiro, RJ] Desenvolvedor Android - Stone

### ISSUE THREAD

**Issue by jcaiqueoliveira** [androiddevbr/vagas#122]
## Descrição da vaga

Se você é desenvolvedor mobile, manja dos paranauês das programações em java, kotlin, é loucamente apaixonado por tecnologia e adora desafios incríveis, é você que procuramos.

Abaixo listamos alguns dos conhecimentos que esperamos de você. Ah, esperamos que você também seja uma pessoa bem legal e descontraída. 😄

## Local

[Escritório, Centro - Rio de Janeiro](https://www.google.com.br/maps/place/MundiPagg/@-22.9072867,-43.1709332,17z/data=!4m12!1m6!3m5!1s0x9981e7223da871:0x4f382a5312ba5fe3!2sMundiPagg!8m2!3d-22.9072867!4d-43.1687445!3m4!1s0x9981e7223da871:0x4f382a5312ba5fe3!8m2!3d-22.9072867!4d-43.1687445)

## Benefícios

- Vale refeição/alimentação;
- Vale transporte;
- Plano de saúde;
- Horário flexível;
- Ambiente de trabalho descontraído;
- Snackbar dentro do escritório;
- Entretenimento: Vídeo games, sinuca, mesa de poker, etc;

## Requisitos
Obrigatórios
- Comunicação com APIs / RESTful;
- GIT;
- Scrum;
- MVP

Desejáveis
- Integration Test / Unit Test;
- RxJava
- Kotlin

Diferenciais
- Projetos opensource

## Nossa empresa

[Nosso Site](http://www.stone.com.br/)
[Blog: Ambiente de Trabalho](http://blog.mundipagg.com/um-ambiente-agradavel-de-trabalho-aumenta-a-produtividade/)

## Contratação 
CLT 
Presencial

## Como se candidatar

Envie um e-mail para jcosilva@stone.com.br e mmoreira@mundipagg.com com seu CV anexado - enviar no assunto: #MOBILE ${SEU_NOME}

**Comment by walmyrcarvalho** [comment]
@jcaiqueoliveira Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by jcaiqueoliveira** [comment]
@walmyrcarvalho Ta aberta =)
