### ISSUE TITLE
DESENVOLVEDOR(A) ANDROID - ZUP INNOVATION

### ISSUE THREAD

**Issue by denisvieira05** [androiddevbr/vagas#1225]
## Descrição da vaga

Sabe aquele app que você ama cada interação? Que tal participar da construção e melhorias das experiências para dispositivos Android - e contribuir para a transformação digital no país? Confere se você tem o que é preciso para fazer parte desse time de elite.
Sua Missão
Desenvolver, em conjunto com a equipe, os produtos mais inovadores do mercado - atuando tanto no desenvolvimento de novas features como em sua sustentação. 
Quais serão suas responsabilidades
Você vai trabalhar em equipe para criar soluções e melhorias no aplicativo/framework, aprendendo diariamente novas tecnologias que podem auxiliar na resolução dos problemas. Além disso, você vai participar e discutir sobre as soluções de arquitetura do sistema, melhores métodos para corrigir bugs, melhorar a UX e resolver problemas complexos. Com o tempo e sênioridade você passará a conduzir as discussões dentro da equipe e tomar as decisões referentes a arquitetura da aplicação.

## Local

Remoto ou Presencial (São Paulo, Uberlândia, Campinas, Belo Horizonte, Joinville, São José do Rio Preto)

## Benefícios

Plano de Saúde
Plano Odontológico
Seguro de Vida
Vale Refeição
Vale Alimentação
Home Office
Gympass
Auxílio creche
Eventos constantes de compartilhamento de experiências e conhecimentos
E muito mais ..
Para saber mais, fale com a gente!

## Requisitos
**O que você precisa ter para o Nível Júnior:**

Conhecimento básico em Java e/ou Kotlin;
Conhecimento básico de como estruturar uma tela usando XML;
Sabe usar o IntelliJ / Android Studio;

**O que seria um diferencial para o Nível Júnior?**

Manja muito de GIT;
Tem app na loja;
Trabalhou em algum projeto Open Source;
Familiaridade com alguma metodologia ágil;

**O que seria muito legal se você soubesse para se encaixar como Nível Pleno:**

Domínio em Java/Kotlin;
Sabe criar Views customizadas reaproveitáveis e escaláveis;
Sabe estruturar uma tela usando XML e Custom Views;
Domina o IntelliJ / Android Studio;
Conhecimento básico da arquitetura do Android, conhece Lifecycles, Threads, Services, Intents e sabe antes de acontecer que um código pode falhar e evita isso;
Conhece lógica de programação e POO;
Domina as principais Libs que a comunidade usa;
Sabe estruturar um app, começar um do zero. Sabe usar das boas práticas para criar uma arquitetura escalável e simples;

**O que seria um diferencial para o Nível Pleno?**

Sabe modelar banco de dados mobile;
Sabe trabalhar com requests criptografadas;
Sabe trabalhar com frameworks de segurança (KeyChainAccess);
Experiência com UnitTest;

**O que te tornaria um sênior/especialista para essa vaga:**

Domínio em Java e/ou Kotlin;
Sabe criar qualquer tipo de View Customizada escalável e em pouco tempo, domina Canvas, View Lifecycle, Styles e Animations;
Arquiteta um app do zero usando as boas práticas para o app funcionar em todas as plataformas existentes, versões do Android, tipos de tela, idioma e hardware;
Cria libs;
Ajuda no desenvolvimento profissional e técnico dos demais Devs;
Destrói o Android Studio;
Domina GIT;
Domina Gradle/Maven;
Domina as principais libs;
Domina Lifecycles;
Conhece Reactive Programming;
Diferenciais para Sênior/Especialista:

Conhece MVVM, MVP, MVC, Clean e sabe dialogar indicando vantagens e desvantagens de cada arquitetura;
Participa de algum projeto Open Source;
Tem app na loja;
Domina metodologia ágil;

## Contratação

CLT ou à combinar

## Nossa empresa

Desenvolvemos produtos digitais disruptivos que impactam a vida de milhares de usuários. Acreditamos em ambientes ágeis, autogerenciáveis e flexíveis. A prova disso é que crescemos mais de 30 vezes nos últimos 5 anos e já somos mais de mil zuppers em 6 cidades. 

Buscamos pessoas que gostam de ser desafiadas e querem fazer parte de projetos que estabelecem um novo curso para a história das maiores empresas do Brasil. 

Para saber mais sobre nossa cultura e oportunidades de carreira, acesse: zup.com.br/vagas

## Como se candidatar

LINK: https://boards.greenhouse.io/zup/jobs/4069877003

**Comment by luisangelorjr** [comment]
Opa! @denisvieira05, blza?
Não sei se aqui é o melhor lugar, mas é um lugar.

Curti o posicionamento da Zup com opensource
Teriam algum link pra enviar teste para a vaga?

**Comment by denisvieira05** [comment]
Opa @luisangelorjr , não entendi mt bem o "link para enviar o teste", mas para se candidatar só acessar esse link e preencher suas informações . Qualquer dúvida pode falar lá no slack do ADBR meu nick é denisvieira05

**Comment by luizcjr** [comment]
Passando aqui somente para parabenizar pela organização da descrição da vaga, de acordo com o nível. É muito bom para o candidato poder ter uma noção do que se espera em cada nível! Seria bom se todas as vagas tivessem esse padrão de descrição! Parabéns e continuem assim!
