### ISSUE TITLE
'Desenvolvedor FullStack para SP / RJ e PE

### ISSUE THREAD

**Issue by Daiane2020** [androiddevbr/vagas#1227]
#Desenvolvedor Android

Rio De Janeiro

Presencial

## Requisitos

Desejáveis
- Conhecimento Front End Development NodeJs ;
- Conhecimento no  desenvolvimento de aplicações;
- Capacidade de desafiar o status dos programas e modelos;
- Express.js;
- Git;

## Contratação

CLT a combinar

## Nossa empresa

Somos uma empresa de BPO e terceirização customizada de serviços e mão de obra. Estamos com oportunidades para atuar em nossos parceiros.

## Como se candidatar

Por favor envie um email para vagas@vikservices.combr.com.br com seu CV anexado - enviar no assunto: Vaga 'Desenvolvedor FullStack + cidade.

**Comment by davidtcdeveloper** [comment]
Este mural de vagas é dedicado a oportunidades para a plataforma Android. Como esta oportunidade não cita Android em momento algum, a mesma será removida.
