### ISSUE TITLE
[São Leopoldo, RS] Desenvolvedor Android | Conceptu

### ISSUE THREAD

**Issue by matheusjardimb** [androiddevbr/vagas#123]
## Descrição da vaga

Desenvolvedor com vasta experiência em desenvolvimento Android, com atenção especial à segurança.

## Local

Preferencialmente presencial (Porto Alegre ou escritório São Leopoldo - RS). Remoto a ser discutido. 

## Benefícios

Além de trabalhar em um ambiente descontraído em um time enxuto, você terá:
- Horário flexível
- Possibilidade de trabalho remoto (algumas reuniões são presenciais)
- Salário à combinar
- Café por nossa conta

## Requisitos

Você irá trabalhar com projetos inovadores e esperamos que você conheça:

- Gradle, Lint, Proguard
- JNI
- Integração com WebServices
- API's do Google
- As principais lib's open-source
- Git
- Inglês
- Segurança de apps

Procuramos alguém que possua atenção especial em proteção de apps.

Desejáveis
- Experiência com Espresso

Diferenciais
- Projetos opensource

## Contratação

CLT ou PJ

## Nossa empresa

Somos uma startup incubada no Parque Tecnológico da Unisinos e estamos procurando desenvolvedor para compor o nosso time. 
Possuímos projetos premiados em nosso portfólio e a equipe está crescendo rapidamente!

## Como se candidatar

Por favor envie um email para matheus.jardim@conceptu.ind.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@matheusjardimb Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!
