### ISSUE TITLE
[Manaus, AM] Desenvolvedor Android [SENIOR]

### ISSUE THREAD

**Issue by patriciaflorees** [androiddevbr/vagas#1231]
**Atividades:**
Desenvolvimento de novas funcionalidades para um aplicativo Android relacionado à área de experiência de uso do celular envolvendo utilização dos sensores do smartphone para aplicativo de notificações;
Prototipação e validação de funcionalidades;
Design patterns e proposição de soluções;
Revisão de código;
Correção de bugs e adaptação de funcionalidades as novas versões de Android.  

**Local: Manaus/AM**

Benefícios: pacote de benefícios compatível com o mercado.

**Requisitos:** 
Formação superior em Engenharia/Ciência da Computação, Sistemas de Informação, ou cursos similares;
Experiência com desenvolvimento de aplicações Android;
Experiência em ferramentas de controle de versão;
Kotlin.
Inglês avançado

**Contratação: CLT**

**Como se candidatar:** 
Envie um e-mail para way@way-consultoria.com com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Android

**Comment by davidtcdeveloper** [comment]
@patriciaflorees A contratação será feita pela Way consultoria ou por outra empresa? Se for por outra empresa, é obrigatório a informação do nome da mesma na descrição da issue.

**Comment by pedrofsn** [comment]
@patriciaflorees falta adicionar os labels com os detalhes da vaga.

**Comment by davidtcdeveloper** [comment]
A issue será fechada até que o nome da empresa contratante seja confirmado.
