### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) iOS Pleno/Sênior | PertoDaqui 

### ISSUE THREAD

**Issue by Moov8Systems** [androiddevbr/vagas#1232]
O PertoDaqui é um aplicativo de ofertas voltado para pequenos comerciantes e estamos em busca de um(a) Desenvolvedor(a) iOS Pleno ou Sênior freelancer para fazer a versão do app para iOS (nativo) ou híbrido.

##Descrição
Problema:
O app foi desenvolvido apenas nativo Android.

Considerações:
Há 2 anos, foi iniciado o projeto em linguagem nativa, mas não foi concluído. Portanto, talvez não seja possível usar o que temos.

##Local
Remoto

##Requisitos
Conhecimentos obrigatórios:
3+ anos de experiência com desenvolvimento iOS nativo (ou híbrido).
Integração com serviços Restful
Saber utilizar GIT (Bitbucket/GitHub)

Conhecimentos desejáveis:
UX (noções)

##Contratação
Freelancer: PJ com nota fiscal

Remuneração:
Valor fechado a partir do valor/hora do desenvolvedor(a) x horas estimadas.

##Nossa empresa
A Moov Systems é uma startup com soluções para pequenos comerciantes, acelerada e residente no iDEXO da TOTVS, que também já foi acelerada pela Edenred, Cielo e atualmente está no ciclo de aceleração do InovAtiva. Para saber mais, acesse: https://pertodaqui.app ou http://www.minnis.com.br

##Como se candidatar
Envie seu GitHub e CV para dev@pertodaqui.app - enviar no assunto: Vaga Dev iOS

#remoto #pleno #senior #pj #freelance

**Comment by davidtcdeveloper** [comment]
@Moov8Systems Este mural de vagas é direcionado para oportunidades para desenvolvimento de aplicativos Android, por isso, esta issue será removida.
