### ISSUE TITLE
Android Senior Especialista Remota 

### ISSUE THREAD

**Issue by natalia041287** [androiddevbr/vagas#1236]
Vaga de Android nativo SR regime CLT 9K a 12K com todos benefícios
para uma startup em plena expansão em Campinas e São Paulo (Moema).Conhecimento Andoid Nativo,Java,UI e UX,arq.MVVM, Clean, teste unitários, Retrofit, animações. Hibrido ou Remoto 100% . Interessados me chama no whatsapp 11-96052-5222 Natalia Head Hunter

**Comment by davidtcdeveloper** [comment]
@natalia041287 é obrigatória a divulgação do nome da empresa contratante. Esta issue será encerrada até que o nome da empresa contratante seja divulgado.
