### ISSUE TITLE
[Marialva - PR] Dev Android Trainee

### ISSUE THREAD

**Issue by JFSene** [androiddevbr/vagas#125]
Segue mais informações no flayer.

![vaga-android-v2](https://cloud.githubusercontent.com/assets/17616463/22026727/cb1164aa-dcb8-11e6-9c21-77cca93b9512.jpg)

**Comment by rsicarelli** [comment]
Olá @JFSene. Poderia informar qual o nível hierárquico para a vaga? Obrigado!

**Comment by Liellison** [comment]
É em qual cidade?

**Comment by walmyrcarvalho** [comment]
@JFSene Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by JFSene** [comment]
@walmyrcarvalho Fechou ontem!!
