### ISSUE TITLE
Teach Lead

### ISSUE THREAD

**Issue by GabrielNogueira85** [androiddevbr/vagas#1252]
Estamos com uma posição em aberto para ser o Teach lead em uma empresa especializada em consultoria de telecomunicações, reconhecida como a melhor do segmento em que atua por 7 anos consecutivos. 
Estamos desenvolvendo um projeto de desenvolvimento de uma plataforma de MDM, para a gestão do parque de aparelhos dos nossos clientes. 
Além de ser o responsável pelo projeto do MDM a pessoa será responsável por conduzir outras iniciativas de tecnologia dentro da empresa. 

O escritório da empresa fica localizado em São Paulo, no bairro Itaim Bibi, mas a pessoa poderá trabalhar remotamente alguns dias.

Obrigatórios

- C#
-  Microsoft .NetCore
- ApsNet Core, Angular 7, 
- Html
- CSS, SQL
- Java Script/Type Script, 
- Entity Framework
- Android com Java ou Kotlin

**Atividades**

•	Manutenção e desenvolvimento de sistemas WEB, utilizando C# e tecnologias Microsoft para backend e Angular para frontend;
•	Manutenção e desenvolvimento de aplicativo Android;
•	Desenvolver e consumir APIs;
•	Desenvolver consultar par banco de dados postgresql;
•	Manutenção e Desenvolvimento de teste automatizados; 
•	Colaborar com a evolução do processo de desenvolvimento de software.

Por favor envie um email para g.nogueiraa@gmail.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@GabrielNogueira85 as regras do nosso mural de vagas obrigam a divulgação do nome da empresa contratante. A oportunidade será fechada até que seja editada com o nome.
