### ISSUE TITLE
[Dublin - Ireland] Desenvolvedor Android | iCabbi

### ISSUE THREAD

**Issue by ppamorim** [androiddevbr/vagas#126]
> Pessoal, estou compartilhando essa vaga com vocês aqui da Irlanda. Um dos requisitos que não estão ali é: Precisa ter passaporte Europeu.

**Favor entrar em contato comigo em caso de interesse.**

iCabbi is the world leader in dispatch technology. We develop booking and dispatch management software predominantly for the Taxi and Private Hire industry. The company was founded in 2010 and is expanding rapidly. We currently have over 70 staff and our clients are based across Ireland, UK, US and Canada. Our focus on the customer’s needs and innovation has given us the opportunity to be the market-leader in many of our segments and is supporting our growth into new markets.

# **The Role**

We are looking for a talented Android developer to join the team. In this role you will work closely with our development and product team to develop, modify and support our Android native apps. This is a great opportunity to join a growing technology company and be on the right side of the change that is sweeping this industry. A real desire to work in a collaborative and fast-paced environment is essential.  

# **Responsibilities**

•	Design and build advanced applications for the Android platform
•	Developing high quality, testable and performant apps using Agile work practices
•	Driving best technology and software development practices into the team with passion and enthusiasm
•	Assisting product managers and business stakeholders in shaping, estimating and planning new requirements
•	Continuously discover, evaluate, and implement new technologies to maximize development efficiency

# **Requirements**

## Essential:
•	5+ years of professional Android development experience
•	Excellent communication skills, we are looking for a team player!
•	Familiarity with RESTful web services using XML/JSON data formats.
•	Commercial experience in some common third-party libraries (e.g. Retrofit, Volley, ButterKnife, Dagger, Picasso, GSON, Crashlytics, Google Analytics, JodaTime, Espresso, etc.)
•	A deep familiarity with Java and Android Framework
•	Experience of working within a continuous development environment and source code repositories
•	Solid understanding of the full mobile development life cycle
•	BS/MS degree in Computer Science, Engineering or a related subject
## Desirable:
•	Github and Jira
•	Experience of collaborating with a UI/UX team
•	Experience in integration with Bluetooth devices
•	Experience in Interaction with Google APIs (e.g. Location Services, Google Maps, GCM, Google Analytics, Firebase, etc.)
•	Have published one or more Android apps in google play

**Comment by walmyrcarvalho** [comment]
@ppamorim Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by paulo101977** [comment]
Esperando a definição aqui para "apply".
