### ISSUE TITLE
Desenvolvedor(a) Mobile - Android [Nelogica]

### ISSUE THREAD

**Issue by isadoravs** [androiddevbr/vagas#1260]
## Descrição da vaga

Aqui na Nelogica, desenvolvemos soluções de alta performance com o objetivo de construir o futuro do mercado financeiro! Buscamos por desenvolvedores com paixão em transformar inteligência em código e com foco na excelência técnica dos produtos para atuar no desenvolvimento da aplicação mobile do nosso principal produto, o Profit. 

Com a aplicação lançada em 2018, já temos mais de 160mil usuários/dia. A partir da excelência como bússola, atingiremos a liderança no mercado com nossa versão mobile, assim como já ocorre com a família Profit Desktop. Além disso, a Nelogica está com projetos de expansão para novos mercados, como o internacional e o de criptomoedas. 

Nossas vagas em aberto para desenvolvimento Android utilizam a linguagem Kotlin e somos movidos por encontrar o melhor desempenho possível para o funcionamento do sistema. Contamos contigo para transformar o mercado financeiro por meio da tecnologia! 

## Local

Porto Alegre, RS

## Requisitos

- Ensino Superior completo ou em andamento em Ciências da Computação, Engenharia da Computação, Análise e Desenvolvimento de Sistemas ou áreas afins de Tecnologia da Informação;
- Vivência em desenvolvimento mobile;

## Contratação

CLT

## Como se candidatar

Quer ser um nelogico e ter o desafio de desenvolver o melhor app de investimentos do Brasil? Confira nossa página de carreiras e te inscreve! 

https://jobs.kenoby.com/nelogica/job/desenvolvedora-mobile-android/5da9b8a5d8df8614b711460d

**Comment by MasterGoshi** [comment]
Por acaso não teria vaga para estágio?
