### ISSUE TITLE
[Dublin - Ireland] Desenvolvedor Android | Drop

### ISSUE THREAD

**Issue by ppamorim** [androiddevbr/vagas#127]
> Pessoal, estou compartilhando essa vaga com vocês aqui da Irlanda. Um dos requisitos que não estão ali é: Precisa ter passaporte Europeu.

**Favor entrar em contato comigo em caso de interesse.**

## About Drop:
Drop is a fast-growing startup with offices in Dublin, Zaragoza, and San Francisco.

Our vision is to provide an intuitive cookbook experience for the smart kitchen, empowering anyone to make delicious food they are proud to share. With a design-led ethos, we started by building an iOS app full of premium step-by-step recipes that work seamlessly with Drop Scale to create a bit of magic in the kitchen.

We are now sharing this magic by allowing remote-enabled appliances from major kitchen brands to integrate with our platform. To make the Drop Recipes app available to even more home cooks around the world, we need a talented Android Software Developer to join our productive and ambitious engineering team.

Our tight-knit, cross-functional team works hard to set our apps apart for usability, stability, performance and enjoyment. We want our Android app to offer the same delightful experience as our existing iOS platform. At Drop, you will play a key role in building and implementing beautiful interfaces that are revolutionizing the experience of making great food.

## Key  Responsibilities:
  •	Take end-to-end ownership — we are building an Android App from scratch, using our award-winning iOS design as a reference
  •	Contribute and implement new features from scratch
  •	Write clean, maintainable code while rapidly iterating and shipping
  •	Work with our creative team to craft and execute pixel-perfect designs
  •	Apply your knowledge of software engineering fundamentals to constantly evolving real-world challenges on a daily basis
  •	Fulfill several project requests simultaneously while meeting tight deadlines
  •	Identify and solve UX problems on emerging technology platforms and devices
  •	Drive feature development for our renowned apps for smartphones and tablets
  •	Own end-to-end product quality, from core app frameworks to jank-free, buttery UIs, ensuring our apps are reliable, performant and delightful
  •	Profile and analyze crash logs to improve the stability and performance of the Android app
  •	Use, create and help build the best tools around for analysis and troubleshooting, including real-time analytics, run-time configurations, and crash reporting

## Technical  Requirements:
  •	3+ years of experience working with Android
  •	Deep understanding of the Android SDK and Android devices landscape
  •	Demonstrated skills in developing, releasing, and maintaining high-quality Android

## Applications
  •	Experience shipping apps from start to finish
  •	Holistic knowledge and passion for the Android platform
  •	Adherence to current best practices and design patterns for mobile engineering
  •	Comfortable with collaborative git workflow
  •	High proficiency in consuming RESTful web services
  •	Strong sense of elegant and usable mobile UI, object-oriented programming, multi- threaded programming, unit tests, object relational mapping, object caching
  •	Ability to turn ideas into extremely fast and reliable code that other people – or you, six months into the future – will find easy to comprehend and modify

## Nice to have:
  •	Experience working with Kotlin
  •	Experience with Agile development methodologies
  •	Experience working with functional programming patterns and JavaRx
  •	Experience developing complex user interfaces
  •	Experience with Bluetooth, especially BLE
  •	Experience with IoT, Tizen

## Other  Requirements:
  •	You enjoy working in a close, highly energised, team-oriented environment.
  •	You’re self-confident, energetic, and enthusiastic.
  •	You present ideas, expectations and information in a concise, well-organized way.
  •	You practice good time management.

## What’s Next:
You should include these in your application:
  •	Links to apps you’ve released in the Play Store and description of the parts you’ve specifically built
  •	Links to online profiles you use (GitHub, StackOverflow, Twitter, etc) A description of your work history (resume, LinkedIn profile, prose, etc)

**Comment by walmyrcarvalho** [comment]
@ppamorim Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!
