### ISSUE TITLE
MOBILE IOS JR REACT NATIVE / SWIFT / ANDROID / SP

### ISSUE THREAD

**Issue by Glelcia** [androiddevbr/vagas#1274]
A Empresa: A Afya Educacional nasce em 2019 com o objetivo de ser a grande parceira dos profissionais médicos em toda a sua jornada de formação. Estamos em pleno crescimento e precisamos de você!!!!

## Local

Remoto - precisa residir em São Paulo

## Benefícios

Gympass; Plano Odontológico Bradesco; Plano de Saúde Notre Dame; Vale Alimentação; Vale Refeição; Seguro de Vida; Vale Transporte; Home Office e PLR (1 salário); Contratação - CLT.

## Requisitos

Obrigatórios
6 meses de experiência mínima: Conhecimentos em Swift, API Rest, Git, Code Review, Bash, Apple Design Guide Lines e Otimização de Desempenho

#mobile #junior # ios #android #edutech #bootcamp

Desejáveis:
- Graduação nas áreas de Engenharia de Software, Análise e Desenvolvimento de Sistemas, Sistemas de Informação, Ciências da computação ou áreas correlatas.

## Contratação

CLT

## Nossa empresa

A Afya Educacional nasce em 2019 com o objetivo de ser a grande parceira dos profissionais médicos em toda a sua jornada de formação. Mas a nossa história já tem mais de 20 anos, especialmente nos cursos de saúde e Medicina.
Por meio de nossas unidades de ensino, atuamos desde a graduação - são mais de 30 cursos diferentes, além da Medicina -, passando pelos cursos para provas de residência e outros títulos até a pós-graduação médica.
Possuimos mais de 2 mil professores e 35 mil alunos.
Na graduação estamos em cinco estados, com 13 Instituições de Ensino Superior, sendo três delas reconhecidas como Centros Universitários pelo Ministério da Educação (MEC).

## Como se candidatar

Por favor envie um e-mail para glelcia.alencar@harpio.com.br com seu CV anexado - enviar no assunto: Vaga Mobile iOS Jr, ou pelo link:
https://jobs.kenoby.com/harpiodigital/job/mobile-ios-junior/5f932960c586c87af69af239?x-token-internal=8f4ff2ae5d040aa7100df7b31e3ba09ab1b3a704b1b8f3bde64312eaa54d3aa310e3d58c6939ee9226979260758bea4a93af141cbc6b66a282c1113aacd55bc6&utm_source=internal

**Comment by davidtcdeveloper** [comment]
@Glelcia A vaga fala de iOS e tem requisitos de tecnologias iOS. Como este mural de vagas é dedicado a oportunidades para Android, iremos remover a issue.
Caso a oportunidade seja para Android, pedimos que a mesma seja recriada com os requisitos corretos.
