### ISSUE TITLE
[Rio de Janeiro, RJ] Desenvolvedor Android Jr/Pleno | Mobicare

### ISSUE THREAD

**Issue by burnermanx** [androiddevbr/vagas#128]
## Descrição da vaga
 
Participação de todo o ciclo de desenvolvimento de aplicativos, desde a fase de análise da solução até a entrega e manutenção do projeto.
 
Trabalhar com outros desenvolvedores de alto desempenho em um ambiente colaborativo.
 
 
## Local
 
Escritório Rio de Janeiro - Botafogo
 
## Benefícios
 
- Salário compatível com o mercado;
- Pacote de benefícios completo;
- Horário flexível de 40h semanais;
- Escritório com: Frutas, Sorvete, Pipoqueira, Frigobar, Vídeo – game e muito mais surpresas!
 
 
## Requisitos
 
- Forte conhecimento do Android SDK e das diferentes versões do Android
- Conhecimento dos padrões de UI do Android, princípios de design, padrões e melhores práticas
- Saber lidar com diferentes tamanhos de tela
- Familiaridade com RESTful webservices
- Experiência com armazenamento off-line, threading e melhora de performance
- Conhecimento das libs open-source mais utilizadas para Android
- Android Studio / Gradle
- Familiaridade com ferramentas de versionamento (Git/SVN)
- Inglês técnico
 
## Desejáveis
 
- Experiência com push notifications / FCM
- Testes automatizados
- Testes de UI
- Contribuição em projetos open source
- Ter ao menos um aplicativo desenvolvido (não necessariamente publicado no Google Play)
- API’s do Google Services (maps, analytics, GTM, GCM etc)
- Experiência com Material Design
- Conhecimento de metodologias ágeis
 
## Contratação
 
CLT
 
## Nossa empresa
 
Empresa do segmento de tecnologia especializada em solução de auto- atendimento móvel e wifi Carrier Grade.
 
## Como se candidatar
 
Por favor envie um e-mail para vagas@mobicare.com.br com seu CV anexado - enviar no assunto: #Desenvolvedor Android

**Comment by paulo101977** [comment]
Ainda tá valendo?

**Comment by walmyrcarvalho** [comment]
@burnermanx Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by burnermanx** [comment]
Está aberta sim
