### ISSUE TITLE
Senior Mobile  Kotlin Developer na HOLDEN [remoto]

### ISSUE THREAD

**Issue by jokapoa** [androiddevbr/vagas#1281]
**Vaga de Mobile Developer na HOLDEN para um dos maiores players de pagamentos do BR** 
(5 vagas) de pleno a especialista
Somos uma empresa especializada em recrutamento e estamos atendendo um dos maiores players do mercado de pagamentos

**Local**
Remoto ( qualquer lugar do Brasil)
Benefícios
• Vale transporte;
• Vale refeição e alimentação;
• Plano de saúde Bradesco Top Nacional Flex;
• Gympass;
• Participação nos Lucros ( 0 a 3 salários);

**Requisitos**
Obrigatórios
• Ensino superior completo em áreas da tecnologia;
• Experiência em projetos de aplicativos Mobile usando Kotlin;
• Capacidade de escrever códigos em Java/Kotlin limpos e bem documentados.
Rotina
• Atuar no desenvolvimento de aplicativos e componentes mobile voltados para o usuário;
• Trabalhar em conjunto com desenvolvedores mobile para a construção de soluções;
• Colaborar com o time de desenvolvimento utilizando métodos ágeis;
• Garantir a produção de códigos simples, eficientes e seguros;
• Contribuir em decisões de arquitetura do projeto;
• Acompanhar e colaborar com o produto para proporcionar a melhor experiência ao usuário;
• Realizar a revisão e validação do código para novas versões.
**Contratação**
CLT ( 5 a 12K)
Um dos mais avançados players do mundo de pagamentos 
**Para candidatar-se realize cadastro no link abaixo**
https://holden.compleo.com.br/Visualizar/66332

**Comment by davidtcdeveloper** [comment]
@jokapoa As regras deste mural de vagas exigem a divulgação do nome da empresa contratante. A issue será encerrada até ser editada com o nome da empresa contratante.

**Comment by davidtcdeveloper** [comment]
Caso a contratante seja a Holden, pedimos que especifique que o profissional atuará de maneira alocada.
