### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Android Pleno | Edumobi

### ISSUE THREAD

**Issue by thiagocortat** [androiddevbr/vagas#13]
## Descrição da vaga

Participação na equipe mobile com desenvolvimento na plataforma Android.
Trabalho em horário integral.
## Local

Ipanema - Rio de Janeiro
## Benefícios
- Plano de Saúde
- Plano odontológico 
- Previdência privada Abril (você decide o quanto quer investir por mês e esse valor é descontado do salário na fonte, reduzindo a porção do salário que conta para o imposto de renda) 
- Seguro de vida com valor de desconto também a seu critério. 
- VR e VT
- Horário Flexível
## Requisitos

Obrigatórios
- 2+ anos de experiência com Android
- Controle de versão distribuído (Git)
- Ciclo de vida de activities e fragments
- Boas práticas de desenvolvimento mobile
- Conhecimento em Java, orientação a objeto e design patterns
- Integração com APIs RESTful e/ou Webservices
- Familiaridade com o Android Studio
- Adaptação de layouts para diferentes tamanhos de telas e dispositivos
- Conhecimento das guidelines de design do Google Play e de desenvolvimento
- Conhecimento de metodologias ágeis (Scrum e Kanban)

Desejáveis
- Fluência em inglês
- Experiência com Espresso e UI Automator
- Experiência com RxJava
- Conhecimento sobre integração contínua (build, test, relatórios) e entrega contínua (deploy)

Diferenciais
- Projetos opensource
- Conhecimentos no desenvolvimento iOS
## Contratação

CLT
## Nossa empresa

Somos uma empresa do Grupo Abril, agora chamado de Somos Educação, com foco em desenvolver tecnologias para rede de ensino. 
Trata-se de uma empresa com ambiente descontraído e com muita oportunidade de crescimento dentro do mercado de edução no Brasil.  
## Como se candidatar

Por favor envie um email para thiago@edumobi.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@thiagocortat Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by walmyrcarvalho** [comment]
@thiagocortat Estou fechando essa vaga por falta de resposta, caso ainda esteja aberta me avise! :)
