### ISSUE TITLE
[Uberaba - MG] Dev Pleno/Sênio Android c/ interesse em web para projetos futuros

### ISSUE THREAD

**Issue by girolando** [androiddevbr/vagas#130]
## Descrição da vaga
Desenvolver Aplicativos Mobile na plataforma Android Nativo (nada de híbrido) com integração e comunicação através de protocolos padrão e sincronização de dados com servidor web.
Trabalhamos com aplicações online e off-line, sendo essencial a experiência com persistência de dados locais.
Pleno conhecimento de métodos de segurança para proteção de banco de dados, encriptação e arquivos.
Experiência em Build para publicar na Google Play e APK para distribuição direta.

## Local

Presencial em Associação Girolando - Uberaba, MG

## Benefícios

 - Refeição fornecida pela empresa
 - vale alimentação
 - vale transporte
 - convênio médico
 - Participação nos lucros e resultados no final do ano
 - Salário bastante competitivo

## Requisitos

Essenciais
 - Experiência avançada em desenvolvimento Android Orientado a Objeto (OOP).
 - Experiência avançada com a IDE Android Studio.
 - Sólida experiência em desenvolvimento de interface de Aplicativo de acordo com Layout.
 - Sólida experiência em consumo e integração com Webservices / API’s REST.
 - Sólida experiência em desenvolvimento e aplicação de testes em código para garantia de qualidade de entrega.
 - Experiência nos bancos de dados locais e métodos de persistência de dados off-line e sincronização de dados com servidor Web quando tiver acesso à internet.
 - Experiência com comunicação por TCP/IP e Bluetooth com outros dispositivos.
 - Conhecimento em desenvolvimento Android utilizando Frameworks ORM.

Desejáveis
 - Noções de UX
 - Ser preocupado com estética do Aplicativo, prezando por desenvolver a interface o mais próximo possível do Layout.
 - Ter conhecimento ou vontade de atuar no desenvolvimento de backend especificamente escrito em PHP utilizando Framework Laravel.

Diferenciais
- Projetos opensource
- Apps publicados na playstore (nativo)
- Experiência com TDD & Scrum

## Contratação

Regime CLT. Enviar pretensão salarial.

## Como se candidatar

Por favor envie um email para ansilva@girolando.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by andersonef** [comment]
Valeu @davidtcdeveloper  por add as labels. 
Conseguimos contratar aqui pelo grupo. Valeu, vocês são demais!

**Comment by davidtcdeveloper** [comment]
Maravilha @andersonef :D

Aproveitando pra fechar a issue então.
