### ISSUE TITLE
[remoto] [IOS DEVELOPER] [CLT]

### ISSUE THREAD

**Issue by suelenm** [androiddevbr/vagas#1307]
Projeto de desenvolvimento e melhorias de aplicações em aplicativos de mercado de pagamentos.

Remoto ou Escritório São Paulo - Faria Lima
Benefícios
Participação nos lucros
Assistência Medica
Odonto
Seguro de vida
Vale Refeição
Descontos em cursos
Cartão Farmácia

Requisitos

•	Nível superior completo.
•	Experiência com aplicativos em iOS nativo.
•	Ter experiência em Apple Design Guide Lines.
•	Trabalhar com Auto Layout e diferentes resoluções de tela (iPad, iPhone e afins).
•	Experiência com GIT.
•	Trabalhar realizando testes, code-review, integração contínua e afins.
•	Experiência com Swift e Objective C.
•	Abordagem voltada a testes (TDD).
•	Boas práticas de desenvolvimento (SOLID, KISS, DRY). 
•	Conhecimento com bibliotecas comuns ao desenvolvimento iOS (RXSwift, Alamo Fire etc.).
•	Ser proativo.

Contratação
CLT

Nossa empresa
Somos uma empresa líder no mercado de pagamentos, trabalhamos com as tecnologias mais atuais do mercado . Em times de alta performance, precisamos de profissionais que gostem de desafios e aprender cada dia mais.

Como se candidatar
Por favor envie um e-mail para suelen.matta@am53.com.br com seu CV anexado - enviar no assunto: Vaga IOS

**Comment by davidtcdeveloper** [comment]
@suelenm Este mural de vagas é focado em oportunidades para desenvolvimento de aplicativos Android. Como esta vaga não cita Android em nenhum momento, a mesma será removida. Caso a oportunidade seja realmente para Android, pedimos que a mesma seja reaberta com a descrição correta.
