### ISSUE TITLE
Desenvolver mobile app - SP - Capital

### ISSUE THREAD

**Issue by tripletech-it** [androiddevbr/vagas#131]
## Descrição da vaga

Analista programador mobile para apps híbridas e experiência de no mínimo 1 ano.
Desenvolvimento de apps usando Cordova e Ionic 2

## Local

Escritório São Paulo - Ipiranga, próximo metrô alto do ipiranga

## Benefícios

•Plano de Saúde Amil
•Vl Refeição - R$20,00
•Vl Transporte ou Vl Combustível - R$10,00 dia (não à desconto de benefício)
•Seguro de Vida Coletivo
•Plano de Carreira e PLR
• Ambiente descontraído
•Café da manhã
•Horário Flexível 
•Day off

## Requisitos

Requisitos Mandatórios:
- Cordova
- Javascript: Jquery e Angular
- HTML 5
- CSS 3

Desejáveis:
-link com portfólio de trabalhos
-Inglês Intermediário 

Diferenciais:
- Conhecimento em Ionic
- Noções de design
- Conhecimento básico em PHP ou Node

## Contratação

CLT ou PJ

## Nossa empresa

Empresa especialista em soluções de TI

## Como se candidatar

Por favor envie um email para rh@tripletech.com.br com seu CV anexado e informando preferencia de contratação CLT ou PJ - enviar no assunto: DevMobileApp

**Comment by walmyrcarvalho** [comment]
@tripletech-it Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by tripletech-it** [comment]
Olá,

Pode fecha-lá. Já realizados a contratação!
Att,

De: Walmyr Carvalho [mailto:notifications@github.com]
Enviada em: sábado, 8 de abril de 2017 21:57
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: RH <rh@tripletech.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] Desenvolver mobile app - SP - Capital (#131)


@tripletech-it<https://github.com/tripletech-it> Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!
