### ISSUE TITLE
[REMOTO] Pessoa Desenvolvedora Android [Pleno/Sênior] - ioasys

### ISSUE THREAD

**Issue by lribeiroms** [androiddevbr/vagas#1310]
## Descrição da vaga

Para a vaga de Pessoa desenvolvedora Android, buscamos um profissional que desenvolva aplicações em Java e/ou Kotlin, utilizando padrões de projeto modernos, como MVP e MVVM e esteja sempre antenado com tudo que há de novo no mercado. Este profissional irá desenvolver APPs Android para grandes empresas do mercado nacional e internacional.

**Atividades:**
• Manter e criar novas funcionalidades para clientes do mercado nacional e internacional em Java e Kotlin;
• Otimizar as interfaces para melhorar a performance e garantir a boa usabilidade dos APPs;
• Escrever códigos eficientes, reutilizáveis e de fácil manutenção;
• Discutir possíveis soluções entre os times de UX, Back-end e Front-end;
• Automatização de testes.

## Local

Remoto;
A empresa possui escritórios em Belo Horizonte, São Paulo e Lavras;

## Benefícios

• Day Off - Birthday;
• Jornada flexível;
• Acesso a plataforma de cursos online;
• Curso de Inglês (In Company).

## Requisitos

• Domínio de Java e/ou Kotlin;
• Experiência com integrações REST e SOAP;
• Conhecimento em base de dados SQL Lite e Realm;
• Conhecimento das Guidelines da Google para desenvolvimento Android;
• Experiência com Padrões de Material Design;
• Versionamento de código Git;

**Diferenciais:**
• Ter algum app já publicado na Google Play;
• Ter experiência em processos de code review;
• Ter conhecimento em testes unitários e de interface.

## Contratação

Modelo de contratação CLT ou PJ (a combinar);

## Nossa empresa

Somos especialistas em criar soluções únicas para empresas ousadas. Digitalmente, mas sempre com alma. Para nós, inovação, design e tecnologia são apenas meios que utilizamos para trazer o melhor do universo digital para nossos clientes e alcançar soluções que irão transformar a sociedade.

Somos formados por um time diverso e múltiplo que acredita na essência de que as nossas entregas são sempre feitas de pessoas e projetadas para pessoas. Queremos colaborar com a sociedade construindo um legado de um mundo acessível, conectado e intuitivo. Como deveria ser.

## Como se candidatar

Se inscrever através do site: https://ioasys.gupy.io/jobs/584475 ou enviar o CV para o e-mail [vagas@ioasys.com.br](url).

**Comment by davidtcdeveloper** [comment]
@lribeiroms Existe outra oportunidade aberta para a ioasys. Poderia verificar se trata-se da mesma oportunidade e fechar uma das issues?
https://github.com/androiddevbr/vagas/issues?q=is:issue+is:open+ioasys
