### ISSUE TITLE
[Remoto/São Paulo] Desenvolvedor (a) Android Pleno em BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [androiddevbr/vagas#1314]
Descrição da vaga
Estamos em busca de profissionais com experiência em Android /Kotlin para integrar um time de uma das maiores empresas do país. Prazo indeterminado de contratação com muita chance de crescimento.

Local
home office durante a pandemia; pós a definir, podendo ser necessário alguns dias presenciais na Zona Sul de SP- região do Jabaquara.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico Bradesco
-previdência privada
-plano odontológico
-Gympass;
-reembolso de certificações.

Requisitos necessários:
Tecnologias: Android, Kotlin, GIT, API Rest.

Contratação
CLT full pela BRQ.
Horário comercial, de segunda a sexta.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 2500 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Android.

**Comment by davidtcdeveloper** [comment]
@ReAnne123 Já temos estas outras duas issues cadastradas sobre oportunidades na BRQ:

https://github.com/androiddevbr/vagas/issues/1238
https://github.com/androiddevbr/vagas/issues/1090

Poderia confirmar se trata-se da mesma vaga? Se sim, sugerimos unificar em uma única issue. Se não, pedimos para fechar as issues  antigas.

**Comment by ReAnne123** [comment]
Olá boa tarde, as vagas citadas foram fechadas.
A #1314 é uma vaga nova.
Obrigada.
________________________________
De: David Tiago Conceição <notifications@github.com>
Enviado: terça-feira, 8 de dezembro de 2020 16:51
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: ReAnne123 <renata.tata123@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] [Remoto/São Paulo] Desenvolvedor (a) Android Pleno em BRQ Digital Solutions (#1314)


@ReAnne123<https://github.com/ReAnne123> Já temos estas outras duas issues cadastradas sobre oportunidades na BRQ:

#1238<https://github.com/androiddevbr/vagas/issues/1238>
#1090<https://github.com/androiddevbr/vagas/issues/1090>

Poderia confirmar se trata-se da mesma vaga? Se sim, sugerimos unificar em uma única issue. Se não, pedimos para fechar as issues antigas.
