### ISSUE TITLE
[100% REMOTO] Desenvolvedor Android Senior @ Instituição Financeira 

### ISSUE THREAD

**Issue by lucasherodoto** [androiddevbr/vagas#1325]
Vaga 100% Remota!

Conhecimentos:
• Práticas ágeis: Scrum, Kanban.
• Conhecimento em Firebase, ferramentas de Analytics; Kotlin
• Familiaridade com RestFul APIs
• Conhecimento dos conceitos SOLID e Clean;
• Conhecimento em arquiteturas MVP;
• Familiaridade com injeção de dependências
• Conhecimento em RxJava; Retrofit; Koin (Injeção de Dependência); Testes Unitários (JUnit);

Atividades:
• Utilização de metodologias ágeis e entregas contínuas.
• Automação da aplicação com testes unitários;
• Relacionamento próximo com as áreas de negócio e outras equipes de Tecnologia;
• Ferramentas e boas práticas de versionamento como git e gitflow;
• Diferentes versões de Android e como lidar com diferentes tamanhos de tela;
• Desenho, construção e manutenção de código eficiente e reutilizável;
• Identificação de gargalos e bugs e sugerir soluções para mitigar ou endereçar os problemas;
• Teste e gestão das versões alpha e beta de aplicativos;
• Manutenção nos aplicativos já existentes;
• Suporte técnico relativos aos sistemas.

Regime de Contratação: PJ

Envie um email para lucas.martins@cq1.com.br com seu CV anexado e pretensão salarial.
Enviar no Assunto: Desenvolvedor Android

**Comment by davidtcdeveloper** [comment]
@lucasherodoto As regras do nosso mural de vagas obrigam a divulgação do nome da empresa contratante. A issue será fechada até que esta informação seja incluída.
