### ISSUE TITLE
[São Paulo] Android Developer na [K2 Partnering]

### ISSUE THREAD

**Issue by nayaracozzolinorh** [androiddevbr/vagas#1328]
# Local

Inicio Remoto, mas profissional precisa ter disponibilidade para ir pontualmente ao cliente, apenas quando necessário.
Profissional pode ter base em São Paulo ou Florianópolis - onde o cliente tem escritório

# Tempo 

Tempo Indeterminado - contratação direta do cliente

## Requisitos

Obrigatórios:
Superior Completo
Java, Kotlin, Android SDK, Programação Orientada a Objetos
APIs REST, Padrões de programação funcional e RxJava
MVP Model View Presenter, Clean Architecture e MVVM
Conhecimentos em Testes Unitários e instrumentados
Injeção de dependências, Dagger, Material Design
Integração de APIs (Retrofit)

Desejáveis:

É desejável a experiência com: Ferramentas de DevOps (gitflow, Jenkins, Crashlytics, Firebase)
Conhecimento das melhores práticas
Conhecimentos em TDD
Experiência de trabalho em projetos com metodologia Ágil Scrum, JIRA

## Contratação

CLT a combinar

## Nossa empresa

Consultoria multinacional especializada em Tecnologia com sede em Londres. Estamos há mais de 20 anos no mercado sendo 10 anos no Brasil

## Como se candidatar

Por favor envie um e-mail para nandrade@k2partnering.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@nayaracozzolinorh Não ficou claro se a pessoal será contratada pela K2 ou por outra empresa. Caso seja outra empresa, é obrigatório divulgar o nome da mesma em nosso mural de vagas. Caso seja pela K2, pedimos que esta informação seja descrita de maneira mais clara.
A issue será encerrada até que seja editada com estas informações.
Pedimos que comentem na issue quando a edição for concluída para que a mesma seja reaberta.
