### ISSUE TITLE
[Remoto] [São Paulo/SP] PHP Developer Pleno/Senior Fullstack na MinniS

### ISSUE THREAD

**Issue by Moov8Systems** [androiddevbr/vagas#1331]
Estamos buscando desenvolvedor(a) PHP Pleno/Senior Fullstack freelancer para o MVP de uma nova feature que, depois de validada, poderá ser incluída no nosso app e/ou se tornar um produto independente.

## Descrição da vaga
Hoje, o MinniS é um comparador de preços de atacadistas para pequenos comércios de alimentação. Vamos testar uma nova feature que poderá ou não entrar no app, por isso, ela deverá ser desenvolvida como um produto independente, mas aproveitando a estrutura que já temos. 

Será preciso fazer integração com a Sefaz Nacional para captura de dados de notas fiscais (quem já tiver experiência nisso ganha pontos) e com um parceiro de negócios que tem toda a documentação detalhada. 

O frontend será html (site responsivo), deverão ser criadas tabelas independentes das que já temos no banco de dados e o código deverá ser todo comentado e documentado. Basicamente, utilizamos AWS, MySql (5.7), PHP/Láravel e Bitbucket. 

## Local
Remoto 

## Benefícios
- Pagamento por job
- Remoto 
- Horário de trabalho livre (freelancer)

## Requisitos

Obrigatórios:
- PHP/Láravel (5.6)
- Mysql (5.7)
- AWS (RDS, S3 e EC2)
- API padrão rest

Desejáveis:
- Git
- Linux, preferência distro Ubuntu
- Já ter feito integração com Sefaz Nacional (NFe)

Diferenciais:
- Ser ativo na comunidade de tecnologia
- Possuir Github ativo
- Domínio na AWS (RDS, S3 e EC2)
- Já ter feito integração com Sefaz Nacional (NFe)

## Contratação
- Projeto fechado
- Necessário nota fiscal (PJ)

## Nossa empresa
A MinniS é uma startup com uma solução para pequenos comerciantes residente do iDEXO/TOTVS e acelerada pelo iDEXO, Edenred e Cielo. 

O que usamos de tecnologia? tem no medium! :d
https://medium.com/idexo-developers/dev-demoday-idexo-minnis-70c595939681

Nossos apps:
Site 1: http://minnis.com.br
Site 2: https://pertodaqui.app

## Como se candidatar
Por favor envie um email para dev@minnis.com.br com seu CV anexado, tempo disponível para o projeto e no assunto: Vaga Freela MVP

#remoto #pleno #senior #pj #freelance

**Comment by davidtcdeveloper** [comment]
@Moov8Systems Este mural de vagas é focado em oportunidades para desenvolvimento de aplicativos para Android. Como a vaga não cita Android em nenhum momento, a mesma será removida.
