### ISSUE TITLE
Get handpicked freelance projects delivered to your inbox every week

### ISSUE THREAD

**Issue by byhub** [androiddevbr/vagas#134]
Hi there everyone
it is nice to be part of your group  :slightly_smiling_face:
Want to be close to where freelancers/nomads feel home since I am starting a new service for freelancers very soon.. I dont like making too much noise; but in case anyone interested , please contact me directly..

and here is my short pitch :slightly_smiling_face:

Get freelance projects delivered to your inbox every week - sign up at http://freelance.kobikit.com    #freelance #leads #meteorjs #angularjs #nodejs  #webdev #design #ux #ui

**Comment by walmyrcarvalho** [comment]
@byhub The idea of this board is to have positions for Android fixed and freelance projects, nothing related with web development. So I'm closing this issue, thanks!
