### ISSUE TITLE
[REMOTA ] Desenvolvedor Android [PLENO|SENIOR] | AM53

### ISSUE THREAD

**Issue by suelenm** [androiddevbr/vagas#1344]
Olá estamos com vagas para empresa Líder no mercado de pagamentos . Vagas remotas CLT.
Buscamos profissionais que gostem de aprendizado constante e desafios. 
Experiência com aplicativos em Android nativo, no mínimo 2 anos; • Android Support Library; • Experiência em Material Design; • Trabalhar com diferentes dimensões de dispositivos (Tablet, celular e afins); • Experiência com GIT; • Trabalhar realizando testes, code-review, integração continua e afins;BDD e TDD • Experiência com Java; • Conhecimento com Google Play Services; • Ter trabalhado com API Level 14 • Conhecimento de padrões de arquitetura: MVP, MVVM.

Vagas para perfis pleno e sênior. 
Interessados enviar currículo para suelen.matta@am53.com.br

**Comment by davidtcdeveloper** [comment]
@suelenm As regras deste mural de vagas exigem a informação da empresa contratante. Será a am53 ou outra empresa?
A issue será fechada até que esta informação seja detalhada no texto.
