### ISSUE TITLE
[SP - Alphaville ] Cielo - Desenvolvedor Android Sênior

### ISSUE THREAD

**Issue by mariliafranguelli** [androiddevbr/vagas#135]
**Descrição da vaga**
- Análise e desenvolvimento de soluções na plataforma Android;
- Proposição de melhorias tecnológicas e processuais;
- Realização de pesquisas, acompanhando as evoluções e tendências tecnológicas;
- Suportar fábrica externa no desenvolvimento de sistemas.

**Posição**
Pleno/ Sênior

**Tipo de contratação**
Presencial, CLT full.

**Requisitos**
- Ampla Experiência em diferentes frameworks de metodologias ágeis (Scrum, Kanban e Lean Thinking);
- Experiência em diferentes técnicas e ferramentas para acompanhamento dos projetos (JIRA);
- Experiência em desenvolvimento ágil, usando técnicas como Behaviour Driven Development (BDD) e Test Driven Development (TDD);
- Experiência, igual ou maior a 5 anos, no desenvolvimento, teste e debug de aplicativos nativos em Android;
- Experiência em integração de apps mobile com webservices e APIs (HTTP based, XML-RPC, JSON ou outros serviços);
- Experiência com Android Studio, Android SDK, gerenciamento de memória, background services, UI layouts e renderização.
- Experiência com o Android Development Guidelines e Android Style Guidelines;
- Experiência nos sistemas Android open-source e as bibliotecas disponíveis;
- Experiência nos protocolos de segurança referentes a mobile;
- Experiência em front-end (HTML5, JavaScript, CSS, entre outras tecnologias);
- Fundamentos sólidos no desenvolvimento de software (algoritmos, estruturas de dados, etc)
- Familiaridade com tendências de desenvolvimento de Android emergentes e Design Patterns;
- Familiaridade com Customer Centric Design;
- Desejável conhecimento em infraestrutura na nuvem;
- Desejável conhecimento em framework de teste automatizado (JUnit, Selenium, Jenkins, etc);
- Desejável conhecimento com ferramentas para distribuição Beta, crash reporting, User Metrics e App Analytics;

**Benefícios**
Assistência Médica, Assistência Odontológica, Plano de Previdência Privada, Seguro de Vida, Estacionamento/ Fretado, Auxílio Refeição (R$ 726,00 por mês), Auxílio Creche e PLR de até 3,3 salários por ano

**Como aplicar**
Interessados enviar currículo para Marília Franguelli (marilia.gabriela@2xs.com.br)

**Contato**
Para dúvidas ou maiores informações sobre a vaga, entrar em contato Marília Franguelli (marilia.gabriela@2xs.com.br)

**Comment by davidtcdeveloper** [comment]
Oi @mariliafranguelli A vaga cita "soluções na plataforma *iOS*;" ali no começo :smile:

**Comment by walmyrcarvalho** [comment]
@mariliafranguelli Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by mariliafranguelli** [comment]
Olá Walmir,

 

A vaga está aberta sim!

 

Abs,

 

Marília Franguelli
2XS Search and Success | São Paulo

Av. Nove de Julho, 3452 - 10° andar – Jardim Paulista
Tel: (+55 11) 2371-0000



 

De: Walmyr Carvalho [mailto:notifications@github.com] 
Enviada em: sábado, 8 de abril de 2017 21:56
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: mariliafranguelli <marilia.gabriela@2xs.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] [SP - Alphaville ] Cielo - Desenvolvedor Android Sênior (#135)

 

@mariliafranguelli <https://github.com/mariliafranguelli>  Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by mariliafranguelli** [comment]
Olá Walmir,

 

A vaga foi fechada! :)

 

Obrigada

 

Marília Franguelli 
2XS Search and Success | São Paulo

Av. Nove de Julho, 3452 - 10° andar – Jardim Paulista
Tel: (+55 11) 2371-0000 – (11) 98918-9277

 

De: Marília Franguelli - 2XS [mailto:marilia.gabriela@2xs.com.br] 
Enviada em: segunda-feira, 10 de abril de 2017 08:22
Para: 'androiddevbr/vagas' <reply@reply.github.com>; 'androiddevbr/vagas' <vagas@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Assunto: RES: [androiddevbr/vagas] [SP - Alphaville ] Cielo - Desenvolvedor Android Sênior (#135)

 

Olá Walmir,

 

A vaga está aberta sim!

 

Abs,

 

Marília Franguelli
2XS Search and Success | São Paulo

Av. Nove de Julho, 3452 - 10° andar – Jardim Paulista
Tel: (+55 11) 2371-0000



 

De: Walmyr Carvalho [mailto:notifications@github.com] 
Enviada em: sábado, 8 de abril de 2017 21:56
Para: androiddevbr/vagas <vagas@noreply.github.com <mailto:vagas@noreply.github.com> >
Cc: mariliafranguelli <marilia.gabriela@2xs.com.br <mailto:marilia.gabriela@2xs.com.br> >; Mention <mention@noreply.github.com <mailto:mention@noreply.github.com> >
Assunto: Re: [androiddevbr/vagas] [SP - Alphaville ] Cielo - Desenvolvedor Android Sênior (#135)

 

@mariliafranguelli <https://github.com/mariliafranguelli>  Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!
