### ISSUE TITLE
[Remoto/Santos-SP] Android Developer na [Zen Wellness]

### ISSUE THREAD

**Issue by diego-zen** [androiddevbr/vagas#1361]
Desenvolvedora de Software Android Pleno
Remoto ou no presencial no escritório em Santos/SP
Tempo Integral

// Sobre nós

Nossa missão é simples: melhorar a vida das pessoas todos os dias. 

Com um rico ecossistema de plataformas focadas em bem estar, ajudamos milhões de pessoas pelo mundo todo. 

Nossos aplicativos Zen e Sonno apoiam pessoas ao redor do mundo com conteúdos e ferramentas focados em promover o bem estar. Hoje, mais de 4 milhões de pessoas em 150 países utilizam os nossos aplicativos.

Zen é nosso app de meditação guiada, com conteúdo semanal em português, inglês e espanhol. Premiado entre os melhores apps da App Store e Google Play em 2016 e constantemente presente nos destaques das lojas, o Zen é um dos principais apps da categoria de bem estar mundialmente. 

Sonno foi criado para auxiliar aqueles que têm dificuldades para dormir. Oferecemos no Sonno uma experiência multissensorial inédita, combinando arte, sons 8D, ASMR e um ambiente convidativo.

Para apoiar ainda mais as pessoas, lançamos em 2020 o Zen Wellness, um estúdio online de yoga, pilates e meditação, oferecendo aulas ao vivo todos os dias. Todas as aulas são transmitidas diretamente do Zen Studios, nosso estúdio de produção audiovisual. Além de aulas ao vivo, os alunos podem acessar as práticas on demand e ainda participar de uma série de cursos e nossos masterclasses. O objetivo é uma experiencia de educação interativa com foco no desenvolvimento pessoal e autoconhecimento. Zen Wellness é a experiencia completa das nossas soluções, oferencendo também o Zen e Sonno aos assinantes da plataforma.

// Sobre a oportunidade

Como Pessoa Desenvolvedora de Software você será responsável por criar uma experiência incrível para as pessoas melhorarem de vida através de 2 apps principais: o Zen Wellness focado em praticas de Yoga ao vivo e On Demand, e o Zen App, focado em meditações guiadas.

// Se você tem esses habilidades, essa oportunidade é para você

* Se identificar 100% com a nossa missão
* Desenvolvimento de aplicativos nativos Android (Kotlin / Java)
* Familiaridade com GIT
* Experiência no consumo de APIs RESTful
* Ter boas práticas de programação
* Atenção a detalhes com design/layout na implementação de telas
* Dominio do idioma pt-br

// Será um diferencial se tiver atuado com

* Metodologia ágil
* Firebase
* Testes Unitários

Tipo de contratação: PJ

// Como se candidatar

Por favor se candidatar através do link: https://zenapp.bamboohr.com/jobs/view.php?id=12&source=devbr

**Comment by khalilayache** [comment]
@diego-zen pode por favor, colocar o nome da empresa no título da issue?

**Comment by diego-zen** [comment]
> @diego-zen pode por favor, colocar o nome da empresa no título da issue?
