### ISSUE TITLE
[Remoto] Android Developer na Dietbox.me

### ISSUE THREAD

**Issue by educosta** [androiddevbr/vagas#1369]
A pessoa desenvolvedora na Dietbox vai ter um papel chave na equipe, trabalhando diretamente em novas funcionalidades para os aplicativos mobile e dando manutenção aos mesmos.

O que você fará:

Trabalhar com aplicativos desenvolvidos pelo Dietbox, envolvendo-se na concepção de novas funcionalidades, testando provas de conceitos, desenvolvendo novas funcionalidades e acompanhando e atualizando as lojas de distribuição. Vontade de aprender e expandir seus conhecimentos. Em uma função de desenvolvedor mobile, você terá oportunidade de trabalhar em ambas plataformas nativas e também em Flutter.

**Esperamos que você:**

- Tenha sede por conhecimento;
- Tenha bons conhecimentos e habilidades em algoritmos e estruturas de dados;
- Tenha experiência em design pattern MVVM;
- Tenha domínio de engenharia de software, princípios, boas práticas e padrões de arquitetura;
- Experiência em desenvolvimento Android nativo
- Tenha experiência na consumo de APIs REST;
- Tenha conhecimento de ferramentas de versionamento como git;
- Conhecimentos em Java, Gradle, Material, Room, Lifecycle e Navigation;
- Conhecimento em Flutter e Dart é um diferencial;

**Benefícios:**

- Combinamos com você, tem plano de saúde, VT, VR etc. mas se quiser colocar tudo no salário também pode;
- Nosso salário também é competitivo, se você for a pessoa certa, você terá um bom salário.
- Empresa com gestão moderna, horizontal e enxuta, que promove a oportunidade de participação ativa em todos os níveis organizacionais.
- Cultura de tratar cada pessoa individualmente com foco em desenvolvimento profissional e pessoal.
- No dress code: o importante é se vestir como você se sentir melhor
- Cultura de home office
- Ambiente informal voltado ao bem estar das pessoas

**Aplicar para vaga em:** https://www.linkedin.com/jobs/view/2365540989

**Comment by EmilioLucena** [comment]
How to apply?

**Comment by educosta** [comment]
> How to apply?

Sorry! Updated
