### ISSUE TITLE
[Campinas, SP] Desenvolvedor mobile (iOS/Android) - Pleno/Sênior | Caiena

### ISSUE THREAD

**Issue by gdonscoi** [androiddevbr/vagas#137]
## Local

Campinas - SP - Presencial ou Home Office

## Benefícios

* Open Food: alimentação livre ao longo do dia
* Benefícios Flexíveis: tenha a liberdade de colocar seu crédito em Cultura, Refeição, Alimentação, Plano de Saúde, Transporte, Línguas, Bolsa Educação
* Plano de Carreira com visão dos valores e desafios
* Casual day todos os dias

## Requisitos

Obrigatórios
* Desenvolvimento ágil de aplicativos nativos
* Test-driven Development (TDD)
* Conhecimentos sólidos em Git
* Integração com APIs REST

Diferenciais
* Habilidade na criação de componentes de interface personalizados
* Experiência com APIs de redes sociais (Facebook, Instagram, Twitter e outros)
* Experiência com aplicações híbridas
* Programação Reativa

## Contratação

CLT

## Nossa empresa
**O que me fará trabalhar na Caiena?**
A Caiena é orientada pelos princípios ágeis:
* o talento importa mais que o processo
* o resultado importa mais do que a documentação burocrática
* a nossa cultura adaptável importa mais do que planos inflexíveis

## Como se candidatar
Acesse: [Inscrição Caiena](http://caiena.net/vagas/desenvolvedormobile/inscricao)

[Para mais informações acesse aqui =)](http://caiena.net/vagas/desenvolvedormobile)

**Comment by walmyrcarvalho** [comment]
@gdonscoi Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!
