### ISSUE TITLE
Desenvolvedor Android Jr/Pl/Sr - luizalabs (Mobile Team)

### ISSUE THREAD

**Issue by ubiratansoares** [androiddevbr/vagas#138]
## Descrição da vaga

Buscamos desenvolvedores Android que queiram fazer parte do nosso time no escritório de São Paulo e que sejam apaixonados por Mobile e aplicações de alta performance; que estejam dispostos a fazer experimentações em larga escala e utilizar a nossa grande base de clientes para testar e amplificar o impacto de nossas ações.

Temos grande autonomia e responsabilidade, somos multidisciplinares, autogerenciáveis e com pouca burocracia no nosso cotidiano, lutando para sempre romper barreiras que diminui nossa capacidade de agregar valor ao negócio. Fazemos entregas frequentes e agimos rapidamente ao encontrar problemas; nosso ritmo é acelerado mas temos tranquilidade para planejar e executar nossas tarefas com qualidade.

Estamos localizados na zona norte de São Paulo na Vila Guilherme e temos um time com grande engajamento, com muita vontade de melhorar a experiência de nossos consumidores e com muito bom humor para encarar as adversidades que existem no caminho.

Experiência com Desenvolvimento Android é o que buscamos mas para nós é igualmente (ou mais) importante que você seja apaixonado pelo que faz e gosta de compartilhar o que conhece; que tenha uma cabeça de aprendiz pois aqui sempre temos algo a aprender uns com os outros, não importa o nível de maturidade ou experiência.

Se você se identificou com esse perfil, inscreva-se e nós entraremos em contato! Seja bem vindo!

## Local

Presencial - Vila Guilherme/São Paulo (próximo à estação Tiête)

## Benefícios

 -Vale alimentação ou refeição;
- Plano de saúde (Unimed ou Allianz);
- Plano odontológico;
- Academia;
- Estacionamento;
- Bolsa de Estudos;
- Bônus Anual (PLR);
- Ambiente informal.

## Requisitos

Desejáveis
- Desenvolvimento Android
- Conhecimento em Integração com APIs Restful / JSON
- Controle de versão de software (GIT)
- UI e UX (Guidelines do Android)
- Metodologias Ágeis
- Automação de Testes (unitários e integrado)

Diferenciais
- Programação reativa (RxJava)
- Automação de CI/CD usando fastlane (Travis-CI, Circle-CI)
- Familiaridade com práticas de segurança voltadas a aplicativos Android (OWASP, noções de criptografia, protocolos de autenticação sobre REST APIs, uso de Proguard, uso de APIs de Fingerprint, etc)

## Contratação

CTL

## Nossa empresa

Somos um laboratório de Tecnologia e Inovação, iniciado no núcleo de Pesquisa e Desenvolvimento do Magazine Luiza, e temos como objetivo criar produtos e serviços com foco no varejo, oferecendo aos clientes uma melhor experiência de compra.

Buscamos quem é apaixonado por construir sistemas distribuídos e aplicações de alta performance, que estejam dispostos a fazer experimentações em larga escala e utilizar a nossa grande base de clientes para testar e amplificar o impacto de nossas ações.

Temos grande autonomia e responsabilidade, somos multidisciplinares, autogerenciáveis e com pouca burocracia no nosso cotidiano, lutando para sempre romper barreiras e aumentar nossa capacidade de agregar valor ao negócio. Fazemos entregas frequentes e agimos rapidamente ao encontrar problemas! Nosso ritmo é acelerado mas temos tranquilidade para planejar e executar nossas tarefas com qualidade.

## Como se candidatar

Aplique no nosso [Workable](https://luizalabs.workable.com/j/58859600A2) (atualizado)

**Comment by walmyrcarvalho** [comment]
@ubiratansoares Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by ubiratansoares** [comment]
Ainda está aberta!
