### ISSUE TITLE
Desenvolvedor Android Jr/Pl/Sr - luizalabs (Novos Negócios)

### ISSUE THREAD

**Issue by ubiratansoares** [androiddevbr/vagas#139]
## Descrição da vaga

Você gostaria de trabalhar em uma grande empresa que te proporcione um ambiente "startup" realmente informal, colaborativo, bem-humorado e inovador? A Luizalabs é assim!

Caso sinta que o perfil abaixo te descreve, o time de Novos Negócios do Luizalabs é o seu lugar!

- Procuro escolher empresas com ambiente de trabalho descontraído em que eu sinta prazer em trabalhar e me divertir;
- Sou comunicativo e curto trocar experiências com diversos perfis;
- Gosto de compartilhar e absorver conhecimento;
- Sou criativo e borbulho ideias;
- Técnicas e práticas Ágeis para os ciclos de desenvolvimento tornaram minhas entregas mais efetivas e fico motivado com o resultado agregado a cada sprint;
- MVP já faz parte do meu dia a dia para definir "o quê" e "como" desenvolver algo novo;
- Concordo que reuniões são necessárias e gosto de participar de forma clara e objetiva;
- Não perco tempo ou crio rugas com picuinha e mimimi;
- Sou questionador para executar aquilo que faça algum sentido;
- Me preocupo com o cliente que está utilizando aquilo que eu e meu time colocamos no ar;
- Mantenho-me atualizado e sempre estou por dentro de novas tecnologias;
- Sinto-me dono do produto que atuo;
- Procuro ser organizado e costumo traçar ou opinar em soluções assertivas

Fazendo parte do time de Novos Negócios do Magazine Luiza, você será responsável pela evolução de canais como Clube da Lu, Magazine Você e Quero de Casamento, e dos novos negócios digitais que o time e a empresa queiram experimentar.

Deu match? Então venha tomar um café para nos conhecer!

## Local

Presencial - Vila Guilherme/São Paulo (próximo à estação Tiête)

## Benefícios

 -Vale alimentação ou refeição;
- Plano de saúde (Unimed ou Allianz);
- Plano odontológico;
- Academia;
- Estacionamento;
- Bolsa de Estudos;
- Bônus Anual (PLR);
- Ambiente informal.

## Requisitos

Desejáveis
- Desenvolvimento Android
- Conhecimento em Integração com APIs Restful / JSON
- Controle de versão de software (GIT)
- UI e UX (Guidelines do Android)
- Metodologias Ágeis
- Automação de Testes (unitários e integrado)

Diferenciais
- Programação reativa (RxJava)
- Automação de CI/CD usando fastlane (Travis-CI, Circle-CI)
- Familiaridade com práticas de segurança voltadas a aplicativos Android (OWASP, noções de criptografia, protocolos de autenticação sobre REST APIs, uso de Proguard, uso de APIs de Fingerprint, etc)

## Contratação

CTL

## Nossa empresa

Somos um laboratório de Tecnologia e Inovação, iniciado no núcleo de Pesquisa e Desenvolvimento do Magazine Luiza, e temos como objetivo criar produtos e serviços com foco no varejo, oferecendo aos clientes uma melhor experiência de compra.

Buscamos quem é apaixonado por construir sistemas distribuídos e aplicações de alta performance, que estejam dispostos a fazer experimentações em larga escala e utilizar a nossa grande base de clientes para testar e amplificar o impacto de nossas ações.

Temos grande autonomia e responsabilidade, somos multidisciplinares, autogerenciáveis e com pouca burocracia no nosso cotidiano, lutando para sempre romper barreiras e aumentar nossa capacidade de agregar valor ao negócio. Fazemos entregas frequentes e agimos rapidamente ao encontrar problemas! Nosso ritmo é acelerado mas temos tranquilidade para planejar e executar nossas tarefas com qualidade.

## Como se candidatar

Aplique no nosso [Workable](https://luizalabs.workable.com/j/58859600A2) (atualizado)

**Comment by walmyrcarvalho** [comment]
@ubiratansoares Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by ubiratansoares** [comment]
Ainda está aberta, sim!

**Comment by mariofelesdossantosjunior** [comment]
Bira a página está fora do ar ..

**Comment by ubiratansoares** [comment]
O link para essa vaga está off, vou ver o que aconteceu e retorno aqui ...

**Comment by ubiratansoares** [comment]
@mariofelesdossantosjunior Atualizado

**Comment by guilhermeoa07** [comment]
O processo seletivo pode ser remoto?
