### ISSUE TITLE
[Joinville, Santa Catarina] Desenvolvedor Android - Camerite

### ISSUE THREAD

**Issue by ppamorim** [androiddevbr/vagas#14]
## Descrição da vaga

Precisamos de um desenvolvedor Android para tocar o aplicativo atual. Feito em Java, em MVP, Realm e Dagger 2.
## Local

Escritório Joinville - Santo Antônio
## Benefícios
- 1.5 horas de almoço;
- Horário flexível (de verdade);
- Vale alimentação;
- Vale transporte;
- Plano hospitalar;
- Estacionamento gratuito(a combinar);
- Maquina de café com 8 sabores;
- Sala de descanso grande;
- Ambiente com várias empresas, legal para networking;
- Restaurante/Padaria do lado da empresa.
## Requisitos

Obrigatórios
- Ter bastante conhecimento de Java. Ter pelo menos um projeto;
- Confortável com padrão MVP e derivados;
- Entender e construir a aplicação seguindo o padrão Material.

Desejáveis
- Experiência com jUnit e Expresso;
- Conhecimento do Dagger 2 (Google) e Realm.

Diferenciais
- Conhecimentos em Kotlin, Clojure ou Scala.
- Entender RxJava;
## Contratação

A combinar
## Nossa empresa

https://camerite.com/about
## Como se candidatar

Update: Por indicação de nosso supervisor, a vaga está disponível somente para profissionais de Joinville-SC ou regiões próximas.
Por favor envie um email para cristian@camerite.com e pedro@camerite.com com seu CV anexado - enviar no assunto: Vaga Android - Camerite.

**Comment by walmyrcarvalho** [comment]
@ppamorim Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by walmyrcarvalho** [comment]
@ppamorim Estou fechando essa vaga por falta de resposta, caso ainda esteja aberta me avise! :)
