### ISSUE TITLE
Desenvolvedor Mobile Android Sênior.

### ISSUE THREAD

**Issue by 2016-20162016** [androiddevbr/vagas#140]
Responsabilidades:

Manter e reestruturar aplicativo corporativo e liderar tecnicamente time de desenvolvedores mobile.

Requisitos obrigatórios:

Profundo conhecimento em Java;
Experiência com Android;
Testes unitários com JUnit, Mockito, etc;
Testes instrumentais Roboletric, Espresso, etc;
Git e Github;
Confortável com padrão MVP, MVC, MVVM e derivados;

Diferenciais:

DI/IoC (Dagger 2)
RxJava
Experiência com desenvolvimento de API REST

Local de trabalho: Vila Mariana

Caso seja interessante ou tenha indicações, favor encaminhar CV atualizado + pretensão salarial (PJ e CLT) para: talita.silva@randstad.com.br

**Comment by walmyrcarvalho** [comment]
@2016-20162016 Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!
