### ISSUE TITLE
Desenvolvedor Frontend Javascript

### ISSUE THREAD

**Issue by 2016-20162016** [androiddevbr/vagas#141]
Analista / Dev Javascript 

Desenvolvedor responsável por criar interfaces para o usuário final utilizando Javascript, Html5 e CSS3. Deve ter sólidos conhecimentos em Javascript, chamadas AJAX e renderização parcial da página, bem como conhecimento dos frameworks javascript modernos como Angular e React, e dos frameworks de front-end mais utilizados como Material e Bootstrap.

Um desenvolvedor Javascript, deve estar a par das tendências, componentes e estruturas utilizadas atualmente na produção de interfaces. Irá trabalhar em parceria com os desenvolvedores de back-end, consumindo e sugerindo alterações em serviços rest desenvolvidos por essa equipe. 

Responsabilidades

- Desenvolver interfaces para usuário final em javascript
- Construir código componentizável / reutilizável
- Garantir a viabilidade técnica das soluções implantadas
- Otimizar as aplicações considerando performance e escalabilidade
- Garantir que todos os dados sejam validados antes de serem enviados aos sistemas de back-end

Conhecimentos técnicos necessários

- Conhecimentos sólidos em javascript.
- Conhecimento de JQuery, AngularJS, ReactJS, VueJS e demais frameworks modernos
- Conhecimento de HTML5, CSS3, Bootstrap e Material Design
- Entendimento do mecanismo de renderização dos browsers, incluindo chamadas AJAX, partial rendering e questões de performance.
- Ferramentas de compilação, testes e distribuição Javascript (WebPack, Gulp, Grunt, Browserify, ...)
- Consumo de APIs REST via javascript
- Entendimento de mecanismo de autenticação OAuth2
- Proficiência em utilização do Git como versionador de código.

Local de trabalho: Av Faria Lima. Itaim Bibi.

Caso seja interessante ou tenha indicações, favor encaminhar CV atualizado + pretensão salarial (PJ e CLT) para: talita.silva@randstad.com.br

**Comment by davidtcdeveloper** [comment]
Este repositório tem a finalidade de concentrar vagas para desenvolvedores Android.
A issue será encerrada.
