### ISSUE TITLE
[Campinas, SP - Remoto] Desenvolvedor Android [JUNIOR] | TARVOS LTDA

### ISSUE THREAD

**Issue by rafacho** [androiddevbr/vagas#1412]
-Desenvolvimento, manutenção e constante aperfeiçoamento de nossa plataforma/software, atendendo às requisições dos usuários e área de suporte;

-Produção de código limpo, estruturado e documentado.

Requisitos:

Precisa ter:

    Formação superior na área;
    HTML/CSS;
    Angular;
    Node.js;
    Banco de dados não relacional;
    GIT.
    React/React Native
    Kotlin

Seria bom ter: 

    Firebase;
    Scrum;
    API REST.

CLT - Salário compatível com o mercado

Possibilidade de trabalho remoto

Contato: vagas@tarvos.ag

**Comment by davidtcdeveloper** [comment]
@rafacho A vaga cita Android no título porém os requisitos não falam de Android em momento algum. Pedimos que revisem a descrição da vaga para que ela fique aderente ao propósito deste mural que é divulgar vagas para desenvolvimento Android.
