### ISSUE TITLE
[Remoto] Mobile Developer @ Nuage IT

### ISSUE THREAD

**Issue by techrecruiterbsb** [androiddevbr/vagas#1427]
## Posição
Júnior e Sênior.

## Tipo de contratação
Remoto
CLT ou PJ

###### Obrigatórios
- Superior completo na área de TI;
- Experiência no desenvolvimento de aplicações híbridas para iOS e Android;
- Conhecimento em React Native;
- Docker;
- SQL;
- APIs Rest.

## Como aplicar
Se interessou pela vaga e preenche os requisitos? Envie o seu currículo para: techrecruiterbsb@gmail.com

**Comment by davidtcdeveloper** [comment]
@techrecruiterbsb Pode detalhar melhor o nome da empresa contratante? Se possível, um link para o site de vagas ou afins. As regras do mural exigem deixar claro o nome da empresa contratante.
