### ISSUE TITLE
[Remoto] Dev Android Nativo Pl/Sr @ Fusion S/A

### ISSUE THREAD

**Issue by valdir-silva** [androiddevbr/vagas#1434]
Descrição da vaga
Estamos à procura de desenvolvedores mobile experientes.

Local
Remoto ou Recife-PE

Benefícios
- TICKET: R$550
- PLANO DE SAÚDE E ODONTOLÓGICO
- AUXÍLIO CRECHE
- AUXÍLIO LENTE
- ALURA
- GYMPASS
- OUTROS...

Requisitos
• Dominio na linguagem Kotlin/Java;
• Confortável com padrão MVP, MVC, MVVM e derivados
• Experiência em desenvolvimento SOLID

Desejáveis
• Reactive Native
• MySQL

Contratação
• CLT 

Nossa empresa
Somos especialistas em logística para entregas fracionadas sendo nosso objetivo garantir o aumento da competitividade das empresas e, aos seus clientes, uma experiência fascinante com entregas eficientes e pontuais!

Como se candidatar
Enviar email para: 
valdir.silva@fusiondms.com.br

**Comment by davidtcdeveloper** [comment]
@valdir-silva Recomendamos complementar a vaga com os campos do template, assim poderemos adicionar labels e facilitar a pesquisa para as pessoas interessadas.

**Comment by valdir-silva** [comment]
> @valdir-silva Recomendamos complementar a vaga com os campos do template, assim poderemos adicionar labels e facilitar a pesquisa para as pessoas interessadas.

Fiz agora
