### ISSUE TITLE
[REMOTO] Desenvolvedor Android [ConquestOne]

### ISSUE THREAD

**Issue by Deyse85** [androiddevbr/vagas#1436]
Profissional que atue com Arquitetura, Desenvolvimento de Aplicativos, Automação de Testes, Continuous Delivery, Performance, Segurança.
Frontend Nativo Android;
Java (Android);
Kotlin (Android).

Contratação PJ
Home Office

Interessados encaminhar currículo atualizado para deyse.souza@cq1.com.br

**Comment by davidtcdeveloper** [comment]
@Deyse85 Recomendamos complementar a vaga com os campos do template, assim poderemos adicionar labels e facilitar a pesquisa para as pessoas interessadas.
