### ISSUE TITLE
[São Paulo] Desenvolvedor Android Jr/Pl - Accesstage Tecnologia 

### ISSUE THREAD

**Issue by mrebonato** [androiddevbr/vagas#144]
## Descrição da vaga

Desenvolvimento de aplicativos nativos Android, comunicação com webservices e integração com terceiros em soluções de conectividade financeira.
Programar, desenvolver, codificar e testar sistemas para Android nativo. Executar manutenção, melhorias e criações dos sistemas fazendo eventuais correções necessárias para otimização dos produtos, visando exceder às necessidades e expectativas dos stakeholders.

## Local

Matriz - Avenida Paulista - próximo a estação Consolação do metrô.

## Benefícios

- Vale Transporte, Vale Refeição, Vale Alimentação, Assist. Médica sem desconto, Assist. Odontológica sem desconto, Seguro de Vida, Auxílio Creche.
- Plataforma de parcerias - exemplo: Cursos: Alura, Graduação e Pós: Fiap, Restaurantes diversos, entre outros serviços de saúde, lazer, educação, cultura...
- Área de lazer com jogos, sofá, TV, biblioteca.
- Ambiente e formato de trabalho: Startup
- Será estimulado constantemente a aprender novas tecnologias, sair da zona de conforto, necessário gostar de concluir desafios. 

## Requisitos

Obrigatórios
- Superior completo em Tecnologia.
- Conhecimento em programação Java. 
- Experiência com Git ou outra ferramenta de controle de versão. 
- Currículo em Git, ter pelo menos um aplicativo publicado na loja. 
- Comunicação com webservices e integração com terceiros. 
- Conhecimento do SDK de Android e melhores práticas.
- Paixão por mobile. 

Desejáveis
- Experiência significatica com programação Java.

Diferenciais
- Habilidade com outras plataformas mobile (IOS).
- Pós-graduação cursando
- Certificação em programação

## Contratação

CLT - horário comercial

## Nossa empresa

“A Accesstage é seu parceiro tecnológico em conectividade financeira. Pela otimização da cadeia financeira de nossos clientes, garantimos a integridade, a acuracidade, a integração e a segurança nas vendas, pagamentos e recebimentos que ocorrem na cadeia financeira da sua empresa"
Celso Sato, presidente da Accesstage. http://site.accesstage.com.br/manifesto-accesstage

A contratação é para o nosso novo produto: Tiquei: O CONTROLE DAS VENDAS DO SEU ESTABELECIMENTO NA PALMA DA SUA MÃO
Suas vendas com cartões de crédito, débito e vouchers, e a previsão de seus recebimentos financeiros em um só aplicativo! http://www.tiquei.com.br/

## Como se candidatar

Por favor envie um email para selecao@accesstage.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Android/Tiquei

**Comment by walmyrcarvalho** [comment]
@mrebonato Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!
