### ISSUE TITLE
[Campinas, SP] Desenvolvedor Android [Junior/Pleno] Instituto Eldorado

### ISSUE THREAD

**Issue by IP-Eldorado** [androiddevbr/vagas#1440]
Se você ama um desafio, trabalhar em equipes multidisciplinares e tem experiência com desenvolvimento de aplicações Android, essa oportunidade é pra você!
Nesta oportunidade você contribuirá para  a construção de novos produtos de uma grande empresa multinacional de telefonia móvel, integrando-os com a plataforma atual, inicialmente com foco no desenvolvimento de aplicativos de câmera de smartphones.
O time atua com tecnologias do momento, focadas em Android e desenvolvendo códigos em JAVA, Kotlin e muito mais!

**Atividades**
Participação ativa no ciclo de desenvolvimento de aplicações Android, incluindo planejamento, estimativas, codificação, revisões, testes e implantação;
Desenvolvimento da interface de interação com o usuário;
Contato diário com times no exterior e contato com equipes multiculturais e multidisciplinares para apoio ao desenvolvimento de novas funcionalidades.

**Requisitos:**
Formação superior em Ciência ou Engenharia da Computação, Engenharia Elétrica ou cursos similares;
Conhecimento na linguagem Java e/ou Kotlin;
Desejável experiência em desenvolvimento de aplicativos Android;
Desejável conhecimento da arquitetura de aplicativos do Android;
Inglês avançado para contato diário com times no exterior.

[Inscreva-se, aqui](https://jobs.kenoby.com/eldorado/job/desenvolvedor-a-javaandroid/601b1199c13cf8406ba799ef?utm_source=website)

**Comment by davidtcdeveloper** [comment]
@IP-Eldorado Temos diversas vagas abertas para o Instituto Eldorado. Poderia conferir se alguma delas se trata desta mesma?
https://github.com/androiddevbr/vagas/issues?q=is:issue+is:open+eldorado
Também não está disponível a informação de como se aplicar.
