### ISSUE TITLE
[REMOTO] Android Developer na [Invillia]

### ISSUE THREAD

**Issue by GabriellyLeonel** [androiddevbr/vagas#1441]
## Descrição da vaga
Desenvolvimento e manutenção de aplicativos Mobile com foco em ferramentas de 2FA (Segundo Fator de Autenticação);
Desenvolvimento utilizando metodologias ágeis;
Desenvolver código através da documentação e histórias de usuário;
Corrigir defeitos;
Executar testes.   

## Local
100% REMOTO MESMO DEPOIS DA PANDEMIA.

## Benefícios

        Assistência médica sem coparticipação;
•	Vale refeição / alimentação
•	Bônus vale educação
•	Bônus saúde física
•	Auxílio teletrabalho
•	Bônus setup para teletrabalho
•	Bônus saúde emocional
•	Bônus seu aniversário

## Requisitos
Sólida experiência em desenvolvimento Mobile utilizando a plataforma Android;
Amplos conhecimentos em Java e Kotlin,
Integração de sistemas via REST Api;
Testes de interface e testes unitários.
Experiência em desenvolvimento e integração com aplicações utilizadas em larga escala com foco em performance e utilização racional de recursos.
Conhecimento em arquiteturas móveis como MVP, MVVM e Viper.

## Contratação

CLT

## Nossa empresa
A experiência de trabalhar na Invillia é única. E global. Temos o nosso próprio jeito de conectar talentos e construir inovações.
Revolucionamos o ambiente de trabalho #Instation + somos experts em desenvolver soluções complexas para #GameChangers + temos uma metodologia única #EngagedbyDataPeopleAction + investimos em pessoas #InvilliaAcademy

## Como se candidatar

Por favor envie um e-mail para gabrielly.leonel@invillia.com com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@GabriellyLeonel Acredito que a oportunidade já foi aberta anteriormente: https://github.com/androiddevbr/vagas/issues/1298
Poderia verificar se trata da mesma oportunidade e, caso seja, encerrar uma das duas issues?
