### ISSUE TITLE
[Remote] Sênior Android Developer na @XPInc

### ISSUE THREAD

**Issue by alexrodrigues** [androiddevbr/vagas#1442]
# Sobre nós

O nosso propósito é transformar o mercado financeiro para melhorar a vida das pessoas. Começamos em 2001, como um pequeno escritório de agentes autônomos de investimentos em Porto Alegre. Chegamos até aqui com a dedicação de pessoas talentosas que, por meio da nossa cultura de Sonho Grande, Mente Aberta e Espírito Empreendedor, tiveram a autonomia e liberdade que precisavam para transformar o mercado financeiro.

Porém, sabemos que o desafio é muito maior. Os grandes bancos ainda possuem 95% do mercado de investimentos no Brasil, mas estamos aqui para romper essa lógica e melhorar a vida de muito mais pessoas. Somos exatamente o que o sistema financeiro nunca foi.

Se você se identifica com esses conceitos e deseja construir algo especial, mergulhe de cabeça nesta oportunidade.

## Sobre a oportunidade

Como Pessoa Engenheira de Software em uma das Squads da Tribo Cartões, você será responsável pela evolução do cartão de crédito mais inovador do Brasil. Ainda é sua responsabilidade ajudar a manter o produto com um atendimento excepcional, com serviços inovadores que surpreendam a expectativa dos nossos clientes.

Somos uma empresa em construção, então aqui o aprendizado é constante e você terá pista livre para criar e muitos (muitos mesmo!) desafios. Além disso, você trabalhará ao lado de pessoas diversas e talentosas que irão te ajudar a usar todo o seu potencial e gerar o maior impacto possível. 

Alguns dos desafios que você vai encarar:   

Desenvolver sistemas com tecnologia de ponta, serviços escaláveis e de alta resiliência;
Aprender sobre os produtos de mercado financeiro;
Incentivar e melhorar as práticas ágeis.
Sobre o ambiente de trabalho, é importante você saber que:

Nossa cultura de mente aberta torna o ambiente horizontal para que as decisões sejam tomadas com base em fatos e dados, colocando os interesses dos clientes sempre em primeiro lugar.
Com espírito empreendedor, cada um de nós protagoniza a sua própria história, então não espere encontrar uma empresa que tome decisões por você.
Apesar de todos terem autonomia para assumir as rédeas da própria vida, a nossa rotina é intensa por sonharmos grande e amarmos o que fazemos.

## O que buscamos
Pré-requisitos para candidatura:

Ter a nossa cultura   
Kotlin
Injeção de dependência com Dagger ou similar
Conhecimento em Rx ou Coroutines
Conhecimento em Architecture Components
Consumo de API REST com Retrofit ou similar
Versionamento (GIT)
Desejável, mas não eliminatório:   

Inglês (reading and listening) 
Conhecimento prático de metodologias ágeis
Testes unitários
MVVM/Clean Architecture
Experiência com Custom Views

## Diferenciais:   
CI/CD
Testes instrumentados

## Local
Remoto

## Contratação

CLT Full

## Como se candidatar

Através da página: https://boards.greenhouse.io/xpinc/jobs/5125194002

**Comment by davidtcdeveloper** [comment]
@alexrodrigues temos outras vagas abertas para a XPInc: https://github.com/androiddevbr/vagas/issues?q=is:issue+is:open+XP+
Poderia verificar e encerrar as que estiverem repetidas ou já tiverem sido preenchidas?

**Comment by alexrodrigues** [comment]
@davidtcdeveloper  Todas essas vagas estão abertas e não estnao preenchidas 😄
