### ISSUE TITLE
[Cidade] Android Developer na Delivery Much (Senior)

### ISSUE THREAD

**Issue by dbonates** [androiddevbr/vagas#1443]
## Descrição da vaga

Dev Android na Delivery Much

Como Dev. Mobile Android você será responsável por desenvolvedor novas funcionalidades e evoluir nossa arquitetura utilizando as ferramentas e boas práticas das tecnologias disponíveis.

## Nossa empresa

A Delivery Much foi fundada em 2011, em Santa Maria - RS e hoje é o maior aplicativo de delivery de comida do interior do Brasil. Nascemos com o desejo de democratizar o Delivery e de lá para cá, não paramos de crescer! Hoje estamos presentes em mais de 300 cidades brasileiras, que atendem diariamente milhões de usuários com nosso app.

## Local

Remoto ou Escritório Florianópolis (não durante pandemia, claro)

## Benefícios

- VA/VR (cartão flexivel)
- Plano de saude UNIMED
- Plano Odontologico
- Seguro de Vida
- PADM (uma especie de PLR pago semestralmente)
- outros

### Como será o seu dia a dia:

- Desenvolvimento de novas features;
- Release e gerenciamento de versões na loja.
- Atuação com multidisciplinar;

## Esperamos que você conheça:
- Java/Kotlin;
- Arquitetura MVVM;
- Modularização dos apps;
- Conhecimento sobre redução de dependencias;

## Diferencial

- automação de releases;
- TDD;
- CI/CD;
- Testes unitários;
- APIs REST/RESTful;
- Programação reativa (RxJava e RxAndroid);
- Git (usamos Github)

## Contratação

CLT

## Como se candidatar

opção 1 - [link oficial da vaga aqui](https://boards.greenhouse.io/deliverymuch/jobs/4277967003)

opção 2 - envie um email para daniel.bonates@deliverymuch.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@dbonates Já temos outra vaga aberta para a Delivery Much: https://github.com/androiddevbr/vagas/issues/1443
Poderia verificar se trata da mesma oportunidade e fechar caso esteja repetida?
