### ISSUE TITLE
[Remote] Sênior Andoid Developer at DB1 Group

### ISSUE THREAD

**Issue by alissongusmao** [androiddevbr/vagas#1444]
### QUEM SOMOS

Somos um grupo de empresas de tecnologia nascido no interior do Paraná, com 20 anos de experiência em desenvolvimento de software voltado para soluções de grandes empresas. Atuamos em diversas frentes de mercado: com produtos (ANYMARKET, CONSIGNET, EIVE, TINBOT) e também com serviços e projetos personalizados através da nossa Fábrica de Software - DB1 Global Software . 

Somos mais de 500 colaboradores em todo o Brasil e até na Argentina, com escritório em Maringá/PR, Campo Grande/MS e Presidente Prudente/SP e atuação remota (home office) desde 2017. Há 11 anos consecutivos entre as Melhores Empresas Para Trabalhar, segundo o GPTW. 

Somos movido por desafios diários, sempre buscando uma forma de melhorar o que já existe e criar coisas novas com qualidade! Todos(as) aqui tem autonomia e voz para dar feedbacks, testar coisas novas e ser parte dessa mudança. Aqui aprendemos uns com os outros diariamente, com um forte senso de time. DB1 é pra quem não quer ser mais um!

### SOBRE A VAGA

Será preciso um bom embasamento em desenvolvimento Android para trabalhar em um projeto da área bancária em nossa Softwarehouse! Oportunidade de trabalhar com práticas de desenvolvimento ágil, pair programming, integração contínua, desenvolvimento orientado a testes (TDD) e boas práticas de Clean Code!

### **Fará parte do seu dia-a-dia trabalhar com:**

Tecnologia: Android;
Aplicação de conceitos de Clean Architecture;
Arquitetura Reativa e MVVM;
Ferramentas: Fastlane, Gitlab, Bitbucket e Bitrise;
Integrações com APIs RESTful.

### **Requisitos obrigatórios:**

Já ter atuado com linguagem Kotlin
Android Jetpack (Room, WorkManager, Navigation e ViewModels)
Conhecimento de arquitetura MVVM
Conhecer o conceito de Arquitetura limpa: se conhecer, já está ótimo!
Arquitetura baseada em divisão por feature;
Estruturação de projetos com múltiplos flavors;
CI/CD
Coroutines Kotlin
Injeção de dependência
Conhecer e saber aplicar os princípios SOLID e Clean Code
Ter experiência com modularização de aplicativos;
Conhecimento em testes Unitários
Ferramentas de análise de qualidade do código (Ex: SonarQube)
Grande capacidade de aprendizado para novas práticas, tecnologias, linguagens de programação e culturas de engenharia; 
Energia e desejo de fazer a diferença!
Abertura para compartilhar conhecimento :)

### **Não é necessário, mas um diferencial se:**

Já ter atuado com consumo de Api REST
Firebase (Push notification, eventos do analytics, crashlytics)
Publicação de apps na Play Store
Si hablas Español, será un diferenciador!
And if you speak English, it will be considered too! 

### **AQUI VOCÊ ENCONTRARÁ**

Vale alimentação e/ou vale refeição;
Plano de Saúde e plano odontológico;
Uma trilha de carreira com Plano de Desenvolvimento Individual (PDI) e feedbacks constantes para te ajudar na sua evolução profissional;
Horários flexíveis!;
Convênio com farmácia Droga Raia, com desconto para colaboradores;
Pra celebrar seu aniversário, é possível sair um pouco mais cedo no dia para comemorar com quem quiser e organizar o que for necessário :)
Aqui você terá a oportunidade de aprender coisas novas - seja no dia-a-dia, em um Programa de Mentoria ou em um desafio do Mestre dos Códigos.
Home office como modelo de contratação. Atuamos com essa possibilidade desde 2017. Além de viabilizar a nossos colaboradores trabalhar de casa em algum dia da semana quando necessário :)

### [**Sentiu que essa é sua oportunidade? Envie seu currículo!**](https://vagasdb1.recruiterbox.com/jobs/fk0ujrt?source=Github)

Contamos mais sobre como é trabalhar na DB1 em nosso LinkedIn, Instagram e Facebook. Se quiser ficar por dentro das novidades do mundo de tecnologia ou novas oportunidades, acompanha a gente lá! :)

**Comment by alissongusmao** [comment]
- [ ]

**Comment by davidtcdeveloper** [comment]
@alissongusmao Existe outra issue aberta sobre vaga na DB1, também para a área bancária. Poderia verificar se trata-se da mesma oportunidade e, se sim, encerrar uma das issues?
https://github.com/androiddevbr/vagas/issues/1470
