### ISSUE TITLE
[Home Office, Brasil] - Desenvolvimento Android Senior | AMBEV TECH

### ISSUE THREAD

**Issue by carololegario** [androiddevbr/vagas#1445]
Se você adora desafios, tem muita curiosidade e quer desenvolver soluções inovadoras, se liga nessa oportunidade: queremos deixar o time Ambev Tech ainda Melhor e, pra isso, precisamos das melhores pessoas com a gente!

Quer desenvolver soluções para a maior cervejaria do mundo? Vem pro nosso lado da força! 

- Sólidos conhecimentos em orientação a objetos
- Conhecimento do eco-sistema Android (ciclos de vida, diferença de versões, adaptação de tamanhos de tela, etc)
- Experiência com Kotlin e Java
- Experiência em consumo de APIs REST
- Experiência em arquitetura MVI ou MVVM e divisão de camadas
- Experiência em desenvolvimento com Android Architecture Components (Lifecycle, LiveData, ViewModel, Room, Navigation)
- Testes de unidade e de UI
- Experiência com banco de dados relacionais

**Desejável**
- Metodologias Ágeis
- Docker
- Azure DevOps

**Link pra inscrição** https://ambevtech.gupy.io/jobs/583076?jobBoardSource=gupy_public_page
**LinkedIn**: https://www.linkedin.com/in/carolina-olegario-ela-dela-76ab09172/

**LABELS**
CLT
Home office
Senior

**Comment by davidtcdeveloper** [comment]
@carololegario Recomendamos seguir o template de novas vagas para que seja possível adicionar as tags, facilitando a pesquisa.
