### ISSUE TITLE
[Remoto] Android Developer Pleno | Sênior [Inbev | Next]

### ISSUE THREAD

**Issue by CassianeIT** [androiddevbr/vagas#1453]
# Informações importantes

Olá, trabalho como tech recruiter freelancer para diversas empresas e no momento estou com demandas para Desenvolvedor Android Pleno, para o Banco Next (Contratação pela Foursys).
Obs:  Eu apenas faço a busca pelos perfis e  indicação,  trabalho para várias empresas, a contratação é diretamente com a empresa (Foursys) e todas as vagas são 100% remotas.

## Descrição da vaga

Atividades:
 * Analise da documentação do cliente com geração do detalhamento de requisitos.
 * Programação dos requisitos detalhados.
 * Reuniões com o cliente.
 * Testes do aplicativo desenvolvido

## Local
Remoto

## Benefícios
- Vai depender da forma de contratação, detalhe visto diretamente com a empresa.

## Requisitos

Obrigatórios
- 2+ anos de experiência com Java ou Kotlin.
- Experiência com MVP ou MVVM.
- Já ter trabalhado com o método ágil.
- Saber os comandos básicos do GIT.

## Contratação
PJ | CLT | Negociável

## Como se candidatar
Por favor envie um email para jobsrecruitment.it@outlook.com, com seu CV anexado ou link do perfil do Linkedin,  que passarei mais informações - enviar no assunto: Vaga Android

**Comment by khalilayache** [comment]
oi @CassianeIT tudo bem? Como está descrito no nosso código de conduta desse repositório de vagas, é obrigatório ter o nome da empresa. No seu caso como são várias, sugerimos que, ou enumere todas as empresas ou que abra uma issue para cada empresa. Por esse motivo, e enquanto esse problema não for solucionado, vamos manter essa issue fechada ok?

**Comment by CassianeIT** [comment]
Oi, tudo certo, alterei lá, se puder abrir novamente agradeço, eu não sei
como abrir de novo kkk

Em ter., 16 de mar. de 2021 às 09:34, Khalil Ayache <
***@***.***> escreveu:

**Comment by khalilayache** [comment]
@CassianeIT Obrigado, reabri a Issue  e vou apagar esses comentários em alguns minutos ok?
