### ISSUE TITLE
Lead Product Engineer / Potential CTO Co-Founder

### ISSUE THREAD

**Issue by leobrujah** [androiddevbr/vagas#146]
## Descrição da vaga

Position:Lead Product Engineer / Potential CTO Co-Founder
Salary:Negotiable incl. equity stake.

Description
We're looking for someone who can see the big picture of Promo Pads growth trajectory as a global company and is excited about the challenge and potential of building the first IoT advertising network in the world from the ground up. Self-motivated candidates who share our passion to do something on a global scale and change the world, with a keen product-focus, strong work ethic and attention to detail. This is an opportunity to become technical lead in a company that will create real change in a very significant global market, and you must be willing to embrace responsibility for the full technical development process. Initially you will work part-time, coding and managing outsourced developers off-shore to build-out the bespoke software for our system. Within 4-12 weeks we will discuss a transition into a full-time CTO role with an equity stake in the company, based on: Work Ethic. Cultural fit with the company. Passion for the product and vision. Proven technical ability.

## Local

Flexible (Dublin / Kildare)

## Requisitos

Obrigatórios
-Experience defining technical specifications for software development.
-Experience building for Android OS – Java, XML, MySQL.
-Experience working with AWS and/or MS Azure.
-Experience leading and managing a development team.
-Ambition and positive attitude to take the technical lead driving rapid development in a start-up -environment.
-Product-focused with an appreciation of commercial needs.
-Minimum undergraduate degree in computer science or similar.

Desejáveis
-Experience in development for IoT and hardware device networks.
-Experience in EPOS development and/or PCI-DSS technical compliance.
-Experience in development of programmatic advertising or exchanges.
-Postgraduate studies in an IT discipline.

## Nossa empresa
http://www.promo-pads.com/

## Como se candidatar

http://www.promo-pads.com/careers/

**Comment by walmyrcarvalho** [comment]
@leobrujah Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by leobrujah** [comment]
@walmyrcarvalho desculpa, só vi agora a mensagem! Vou fechar!
