### ISSUE TITLE
Desenvolvedores Mobile Android (6 Vagas) - Níveis Pleno e Sênior - São Paulo/SP

### ISSUE THREAD

**Issue by Gilzaobomzao** [androiddevbr/vagas#1464]
A HRSoul foi criada visando atender as necessidades do mercado de TI, Telecom e Engenharia, suprindo a carência de consultorias com expertise na área, assim como inovar os processos de Recursos Humanos para os demais segmentos. Oferecemos oportunidades para profissionais com o seguinte perfil:

Desenvolvedores Mobile Android (6 Vagas) – Níveis Pleno e Sênior - São Paulo/SP

 	Experiência em Desenvolvimento Kotlin e Android Studio;
 	Conhecimentos em Integrações API REST;
 	Distribuição na Apple Store;
 	Contratação CLT + Benefícios;
 	Atuação remota durante a pandemia (após este período, presencial em Interlagos, Zona Sul de São Paulo). 

Os interessados deverão enviar o currículo atualizado informando pretensão salarial e disponibilidade para início através do e-mail gazevedo@hrsoul.com.br e/ou https://oportunidades.hrsoul.com.br/

**Comment by davidtcdeveloper** [comment]
@Gilzaobomzao As vagas são para contratação pela HRSoul e alocação em outras empresas? 
Sugerimos seguir o template para criação de novas vagas para que seja possível incluir as labels e facilitar a pesquisa.

**Comment by khalilayache** [comment]
@Gilzaobomzao Como está descrito nas regras do repositório, é obrigatório conter o nome da empresa pra onde é a vaga, caso seja mais de uma mencione na descrição o nome de cada empresa, por favor
