### ISSUE TITLE
Desenvolvedor Mobile 

### ISSUE THREAD

**Issue by Luxfacta123** [androiddevbr/vagas#1471]
[Home Office] Mobile Developer [Luxfacta]

Estamos com vagas  para Desenvolvedor Pleno/Sênior #iOS e Desenvolvedor Pleno/Sênior #Android (Java) no formato Home Office para Luxfacta Soluções de TI de Rio Claro - SP.

A Luxfacta é uma fábrica de software que possui uma história de quase 2 décadas desenvolvendo produtos digitais. Trabalhamos com os mais complexos projetos nos mais diversos setores, de forma ágil e com alta qualidade. Atualmente, a empresa cria sistemas e aplicativos customizados, oferecendo atendimento exclusivo aos clientes. Não é o que fazemos, mas sim como fazemos!

Buscamos profissionais para atuar na área de desenvolvimento, com perfil analítico e responsável. E claro, que goste de atuar com projetos desafiadores!

Necessário conhecimento com: iOS; Objective - C; Swif; Android (Java); Kotlin; Integrações com APIs; GIT; SQlite; Jira; Jenkins; DevOps; React Native e Metodologias Ágeis.

Lembrando que não é necessário ter aderência de 100% ao perfil, você pode aprender com a gente! ;)
Nossas vagas são para todes profissionais, não fazemos distinção por sexo, gênero, orientação sexual, etnia, raça, religião etc. Todas as oportunidades se estendem para PCD's!

Venha fazer parte do nosso time!

Para se candidatar, envie seu currículo com a sua pretensão salarial para nlima@luxfacta.com com resumo dos conhecimentos.

**Comment by khalilayache** [comment]
Oi @Luxfacta123, poderia por favor atualizar o nome da Issue seguindo o template que temos nas nossas regras? facilita pra quem quiser buscar as vagas e as vagas serem encontradas também! Obrigado

**Comment by diegolimadeoliveira** [comment]
Colocar as tags fica bem mais fácil de analisar

**Comment by khalilayache** [comment]
@diegolimadeoliveira não costumamos colocar tags nas issues/vagas que estão pendentes de algum ajuste em relação as nossas regras/codigo de conduta. Tenha calma que a gente sempre coloca o mais rápido possível. Obrigado.

**Comment by diegolimadeoliveira** [comment]
@khalilayache, devo não ter me expressado bem, me refiro em relação ao print em anexo, creio que possa ter outro termo então, obrigado.
![Screenshot 2021-03-23 141817](https://user-images.githubusercontent.com/24457337/112189641-f9845080-8be2-11eb-99e1-6a913c78c6dc.jpg)

**Comment by khalilayache** [comment]
@diegolimadeoliveira desculpe, eu que usei a palavra errada... usei "tags" ao invés de "labels", o restante se aplica, como pode ver acima, eu solicitei uma alteração para a pessoa que abriu a issue, enquanto a issue estiver pendente, a gente não põe as labels

**Comment by diegolimadeoliveira** [comment]
@khalilayache ah sim, eu que não estava sabido do termo. Obrigado então.

**Comment by Luxfacta123** [comment]
> Oi @Luxfacta123, poderia por favor atualizar o nome da Issue seguindo o template que temos nas nossas regras? facilita pra quem quiser buscar as vagas e as vagas serem encontradas também! Obrigado



> Oi @Luxfacta123, poderia por favor atualizar o nome da Issue seguindo o template que temos nas nossas regras? facilita pra quem quiser buscar as vagas e as vagas serem encontradas também! Obrigado
