### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android [PLENO|SENIOR] Quicko

### ISSUE THREAD

**Issue by FernandoDiazGonzalez** [androiddevbr/vagas#1472]
**A Quicko é uma startup de Big Data e Inteligência em mobilidade que vai transformar a rotina daqueles que precisam se locomover. Chegaram para conectar você ao que você precisa.**

Estamos buscando um/a **Android Developer** que tenha atitude empreendedora, consiga equilibrar excelência e simplicidade, e adore trabalhar em equipe e procura apreender com os demais.

**Atividades:**
- Ser protagonista no desenvolvimento do nosso app;
- Participar em decisões de Produto junto ao time;
- Desafios e aprendizado acelerado;
- Cultura de feedback e desenvolvimento;
 
**Requisitos:**
- Experiência avançada com Kotlin e em todo ecossistema Android;
- Conhecimento em arquitetura MVVM e Architecture Components;
- Experiência com Custom Views, Componentização e Testes Unitários;
- Experiência com Remote Config e Testes A/B (Firebase);
- Experiência com Retrofit;
- Experiência com Push Notifications, Crashlytics e ferramentas de analytics;
- Imprescindível total fluencia com GitFlow;
 
**Desejável:**
- Experiência com desenvolvimento CrossPlatform (Flutter / ReactNative);
- Habilidade em benchmarking e otimização de apps;
- Experiência com Configurações de Build e CI/CD;
- Experiência com projetos modularizados;
- Experiência com bibliotecas de mapas.

**Oferecemos:**
- Contrato CLT e trabalho remoto;
- VR, plano de saúde e plano odontológico;

**Gostou?** Pode mandar o CV a **cv@ghidinirodil.com** com o assunto **"Android Quicko"**

**Comment by FernandoDiazGonzalez** [comment]
@davidtcdeveloper a vaga não é para ser alocado, é contratação direta pela Quicko. Tem como ajustar isso?

**Comment by davidtcdeveloper** [comment]
@FernandoDiazGonzalez Ajustei a label.

**Comment by FernandoDiazGonzalez** [comment]
> 
> 
> @FernandoDiazGonzalez Ajustei a label.

Obrigado!!!
