### ISSUE TITLE
[São Paulo/ Híbrido] Mobile Developer Pleno na [Grupo Globo]

### ISSUE THREAD

**Issue by mayksalles** [androiddevbr/vagas#1478]
## Descrição da vaga
Escrever código limpo, de fácil manutenção, utilizando as melhores práticas de
desenvolvimento de software;
Trabalhando de perto com os especialistas em UX;
Atuar como um team-player, comprometendo-se com os objetivos do time e
trabalhando em harmonia com todos;
Ajudar o crescimento do seu time, ensinando, capacitando e dando feedbacks;
Participar de times geograficamente distribuídos.

## Local

Inicialmente remoto, pós pandemia de forma híbrida - Jardim Paulista

## Benefícios

Plano de saúde Bradesco com coparticipação para os dependentes;
Plano odontológico;
Seguro de Vida;
Assistência funeral;
VR

## Requisitos

Obrigatórios

Experiência com JAVA; Experiência com Kotlin; 
Integração via APIs REST; GIT (Git-Flow); Conhecer S.O.L.I.D.;
Experiência com testes unitários; Experiência com ferramentas de métricas e de marketing aplicadas a Mobile (GA,Firebase, Crashlytics, etc); E
Experiência em desenvolvimento Nativo para iOS; 
Conhecimentos nas principais APIs do iOS, como: (UIKit, Foundation), Swift, Objective-C, Storyboard, XIB, Auto-layout, Generics, Protocols, Extension,

## Contratação

CLT - pelo Grupo Globo

## Nossa empresa

Trabalhamos com serviços de R&S (hunting) e alocação de profissionais de tecnologia.

## Como se candidatar

Por favor envie um e-mail para maycon.sales@projeto22.com.br com seu CV anexado - enviar no assunto: Vaga Mobile Pleno, ou pelo link - https://projeto22.selecty.com.br/vaga/455/

**Comment by davidtcdeveloper** [comment]
@mayksalles A contratação será feita pela Projeto22 ou a Projeto22 está fazendo hunting para outra empresa? As regras do mural de vagas exigem a divulgação da empresa contratante, por isso precisamos confirmar esta informação.

**Comment by mayksalles** [comment]
obrigado pelo alerta, fiz a alteração.

**Comment by davidtcdeveloper** [comment]
@mayksalles sugiro editar o título também para informar que a oportunidade é para o Grupo Globo, pode ajudar as pessoas a encontrarem a vaga.

**Comment by mayksalles** [comment]
Feito
