### ISSUE TITLE
[RECIFE – REMOTO]  Pessoa Eng. Software Android Embarcado no CESAR

### ISSUE THREAD

**Issue by CarolinaGChaves** [androiddevbr/vagas#1481]
#1481 [RECIFE – REMOTO] Pessoa Eng. Software Android Embarcado

## Descrição da vaga
Se você gosta de atuar em projetos desafiadores e inovadores onde tanto a sua capacidade técnica quanto a sua colaboração serão cruciais para o andamento do trabalho, gosta de trabalhar em equipes multidisciplinares, tem desenvoltura para interagir diretamente com clientes, gosta de atuar no desenvolvimento de soluções Android e atuar como protagonista em diversos projetos com clientes de escala mundial na área de mobilidade e telefonia móvel, a oportunidade de Eng. Software Android Embarcado faz match contigo!

O que a pessoa atuando no cargo de Eng. Software Android Embarcado faz?
Assume todas as responsabilidades associadas a execução de um projeto. Ela tem como função criar, manter e auditar metodologias de desenvolvimento de sistemas, além de desenvolvê-lo, atuando com um perfil mais voltado para tecnologias Mobile Android embarcado na qual é esperado a interação com os demais membros da equipe de projeto e com clientes do CESAR para discussão sobre requisitos / arquitetura / configuração assim como revisão de código.

## Local
Atuação remota de qualquer estado da região Nordeste.

## Benefícios
  - Plano de Saúde
  - Plano Odontológico
  - Vale Refeição/ Alimentação
  - Seguro de Vida
  - Auxílio Creche
  - Auxílio Lentes
  - Auxílio Idiomas
  - Auxílio Funeral
  - Descontos em cursos da CESAR School
  - DayOff (no Aniversário)
  - Modalidades esportivas in company (Pilates, Top Dance e Yoga)
  - Ginástica Laboral
  - Cultural e clima colaborativo e flexível

## Requisitos
  - Superior completo em Ciências da Computação, Engenharia da computação, Sistemas de Informação e áreas afins;
  - Experiência com desenvolvimento de aplicações Android;
  - Conhecimento e experiência na construção de apps com múltiplos propósitos integrado à serviços externos bem como reagindo à múltiplos tipos de inputs (usuário, eventos do sistema e requisições externas);
  - Conhecimento da arquitetura Android e os diversos componentes que compõem às aplicações e a plataforma (ex: `ContentProvider`, `BroadcastReceiver`, `Service`, `SystemService`);
  - Experiência na área de testes de software e no desenvolvimento de testes automáticos;
  - Inglês de avançado à fluente.

**Contratação** 
CLT

**Nossa empresa**
Olá, nós somos o CESAR, um centro privado sem fins lucrativos, às vezes descentralizado, que acredita na inovação para transformar as vidas de pessoas e organizações. Enxergamos software em tudo e, através dele, a solução de problemas complexos nas mais diversas áreas de atuação. Em resumo: a gente é massa!

**Como se candidatar:** 
Gostou? 
Então envia e-mail com seu currículo para cgc@cesar.org.br, com o título **[RECIFE – REMOTO] Pessoa Eng. Software Android Embarcado**, ou pelo link: https://vagas.cesar.org.br/p/5f11189e892b-eng-de-software-android

**Comment by khalilayache** [comment]
@CarolinaGChaves pode colocar o nome da empresa no nome da Issue também por favor?
