### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android Júnior | KickSIM

### ISSUE THREAD

**Issue by jaqueventurim** [androiddevbr/vagas#149]
## Descrição da vaga

Estamos buscando uma(um) desenvolvedora(desenvolvedor) para trabalhar em um ambiente informal desenvolvendo aplicações nativas Android, participando desde a concepção da ideia até a entrega final e manutenção da versão.

## Local

Oxigênio Aceleradora | Remoto

## Benefícios

- Trabalhar remoto
- R$ 2.500 após o período de experiência. Durante a experiência (90 dias) ajuda de custo de R$ 1.200,00.
- Aprendizado rápido
- Ótimo ambiente de trabalho
- Contato direto com o CEO da empresa
- Ambiente e formato de trabalho: Startup
- Será estimulado constantemente a aprender novas tecnologias, sair da zona de conforto, necessário gostar de concluir desafios.

## Requisitos

Obrigatórios
- Conhecimento em programação Java.
- Experiência com Git ou outra ferramenta de controle de versão.
- Comunicação com webservices.
- Conhecimento do SDK de Android e melhores práticas.

Diferenciais
- Conhecimento sobre empreendedorismo e startups
- Lean Startup

## Contratação

A combinar

## Nossa empresa

KickSIM - startup de roaming celular grátis. Nós encaminhamos as suas ligações para o número internacional sem o custo de roaming.
Nossa sede é no Vale do Silício e a equipe do Brasil trabalha remotamente.

## Como se candidatar

Entre nesse link (http://www.kicksim.com.br/jobs/) e faça o cadastro :)

**Comment by PedrinhoDS** [comment]
é 100% remoto, ou precisa estar em São Paulo para a vaga?

**Comment by jaqueventurim** [comment]
Apesar de ser remoto (SP), você precisa atender às reuniões de retrospectivas com o time. Para pessoas que sejam auto-gerenciáveis, 1x por semana e com o bom uso do Skype com o time você apareceria apenas para os happy hours, se os trabalhos forem entregues nos prazos (meritocracia).

**Comment by PedrinhoDS** [comment]
Entendi, perguntei mais por que tô na Paraíba, de toda forma vou ver se envio meu currículo, obrigado!
