### ISSUE TITLE
[São Paulo ] Android Developer na [AgileThought]

### ISSUE THREAD

**Issue by vagastech** [androiddevbr/vagas#1491]
## Descrição da vaga

Projeto de desenvolvimento mobile para as plataformas Android e IOS.

## Local

Escritório São Paulo - Interlagos 

## Benefícios

- Vale Alimentação
- Vale Refeição
- Vale Combustível
- Assistência Médica
- Assistência Odontológica
- Seguro de Vida
- Gympass

## Requisitos

Obrigatórios
 
-Android: Proficiência em desenvolvimento para plataformas móveis. 
Experiência em desenvolvimento Kotlin e Android Studio
Integracoes API REST
Distribuição na Play Store

Desejáveis

-IOS: conhecimentos em SWIFT, design patterns e integrações REST MVVM e MVVM-C
Distribuição na Apple Store

Diferenciais

## Contratação

CLT

## Nossa empresa

Empresa de tecnologia do mercado financeiro.

## Como se candidatar

Por favor envie um email, com pretensão salarial para belen.ramirez.tech@gmail.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@RecrutamentoDocketBrasil As regras do mural de vagas exigem a divulgação do nome da empresa contratante. A contratação será feita pela AgileThought?

**Comment by RecrutamentoDocketBrasil** [comment]
> @RecrutamentoDocketBrasil As regras do mural de vagas exigem a divulgação do nome da empresa contratante. A contratação será feita pela AgileThought?

Olá,
Sim, será feita pela Agile Thought, para trabalhar alocado no Santander tecnologia.
