### ISSUE TITLE
[Remoto] Mobile Android/IOS Developer na [Pasquali Solution]

### ISSUE THREAD

**Issue by Recrutas** [androiddevbr/vagas#1498]
**Descrição da vaga**
Estamos procurando pessoas que tenha uma vasta experiência em desenvolvimento Mobile com conceitos de IOS e Android.

**Local**
Remoto

**Requisitos obrigatórios:**
•	Android
•	Mobile
•	IOS
•	AWS
•	MySQL
•	Node
•	Python para análise, consultoria de produto

**Requisitos desejáveis:**
•	Firebase
•	Google Analystics
•	Mídia ou indústria de música

**Labels**
•	Alocado
•	PJ
•	Sênior

** Como se candidatar**
Envie seu currículo https://cutt.ly/HjdWRLs
Envie seu currículo: denise.assis@pasqualisolution.com.br

**Nossa empresa**
A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Comment by davidtcdeveloper** [comment]
@Recrutas Existem diversas oportunidades abertas para a Pasquali Solution. Poderia verificar se há alguma repetida ou se realmente todas permanecem abertas?
https://github.com/androiddevbr/vagas/issues?q=is:issue+is:open+pasquali
