### ISSUE TITLE
[Remoto] Desenvolvedor Android | Freelancer

### ISSUE THREAD

**Issue by marceloreis13** [androiddevbr/vagas#15]
## Descrição da vaga

Estou montando uma agencia que será especializada em mobiles, onde meus parceiros serao 100% especializados em suas areas, por isso vou trabalhar com fornecedores remotos.
Sempre que houver projetos em mesa, irei passar o escopo para os parceiros/fornecedores, entao vou fazer uma analise de custo/prazo/qualidade para escollher qual parceiro irei repassar o projeto.
## Local

Remotamente
## Requisitos

Obrigatorio
- Email 
- Telefone

Desejaveis
- Perfil Github
- Portifolio
## Contratação

PJ a combinar
## Nossa empresa

http://migre.mobi
## Como se candidatar

Por favor envie um email para contato@migre.mobi com o titulo: Dev Android e com os dados solicitados em ##Requisitos

**Comment by walmyrcarvalho** [comment]
Editei o título da vaga pra padronizar com o resto das vagas do repositório. :)

**Comment by marcelloreis** [comment]
Show! Obrigado.

Em ter, 19 de abr de 2016 às 18:08, Walmyr Carvalho <
notifications@github.com> escreveu:

**Comment by halysongoncalves** [comment]
@marceloreis13 tudo bem? Já arrumar algum desenvolvedor?

**Comment by walmyrcarvalho** [comment]
@marceloreis13 Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by otaviommendes** [comment]
O endereço de email não funciona.

**Comment by walmyrcarvalho** [comment]
@marceloreis13 Estou fechando essa vaga por falta de resposta, caso ainda esteja aberta me avise! :)
