### ISSUE TITLE
[Manaus] Machine Learning Developer na Way Consultoria e Psicologia

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [androiddevbr/vagas#1503]
## Descrição da vaga 
**Atividades:**

*   Criar e desenvolver soluções para soluções de problemas em larga escala, utilizando abordagem com algoritmos de Machine Learning.
*   Combinar dados de experiência do usuário de várias fontes para reconhecimento de situações contextuais
*   Aplicação de algoritmos de visão computacional em artefatos capturados pela câmera de telefones celulares.
*   Definir e implementar arquiteturas IA e algoritmos Machine Learning.
*   Desenvolvimento de ferramentas e algoritmos de aprendizagem para criação uma base de conhecimento dos contextos do usuário e dos dispositivos móveis.

  

**Requisitos:**

*   Formação concluída em Ciência da Computação/Engenharia da Computação/Sistemas de Informação ou cursos afins
*   Experiência com técnicas de Aprendizado de Máquina 
*   Conhecimento em Estatística
*   Domínio em alguma linguagem de programação como: Java, Python, C ou C++
*   Inglês intermediário

  

**Diferenciais:**

*   Conhecimento em Metodologia de Desenvolvimento Ágil (Scrum);
*   Analytics / Big Data, Data Quality;
*   Experiência com conceitos, técnicas e abordagens de análise de dados, como inferência estatística ou modelos de regressão.
*   Conhecimento do Android SDK e diferentes versões do Android.
*   Familiaridade com APIs RESTful para conectar aplicativos Android a serviços de back-end.

  

Candidatos que não residem em Manaus também podem participar.
## Local 
Manaus/Amazonas 
## Como se candidatar 
Accesse a [Vaga de Machine Learning Developer](https://nerdprogramador.com.br/way-consultoria-e-psicologia-machine-learning-developer/74ee6c11-4d8a-47bb-ac62-f718c2d41fe1?utm_source=github) para mais informações. 
## Labels 
* Alocado

**Comment by davidtcdeveloper** [comment]
@NerdProgramador-com-br Este mural de vagas é focado em oportunidades para desenvolvimento Android. Como a oportunidade cita Android somente nos diferenciais, não ficou claro se é uma oportunidade para Android ou não. Pedimos que melhore a descrição esclarecendo o link com Android para que a vaga seja reaberta.
