### ISSUE TITLE
[Remoto] Mobile Engineer - Android na AgileProcess

### ISSUE THREAD

**Issue by anafelauto** [androiddevbr/vagas#1508]
## Descrição da vaga

Buscamos um(a) Mobile Engineer que será responsável por prover a melhor experiência para nossos clientes através de nossas soluções mobile.

## Local

100% remoto

## Benefícios

  - Onboarding de boas-vindas!
  - “All Hands”: nosso encontro semanal com o CEO;  
  - Dress Code: seja você mesmo(a);
  - Flexibilidade de horário;
  - VR/VA Flex: R$ 550,00 (mês); 
  - Plano de saúde (para você e quem você ama);
  - Plano odontológico; 
  - TotalPass;
  - PLR;
  - Clube de Descontos;
  - Seguro de Vida;
  - Parceria com ZenKlub.

### Obrigatórios

  - Ensino superior completo ou cursando em Ciências da Computação, Sistemas de Informação ou áreas correlatas;
  - Conhecimentos e experiência em Android Nativo;
  - Conhecimentos e experiência em Kotlin;
  - Conhecimentos e experiência em metodologia ágil;
  - Boas práticas de Clean Code;
  - Conhecimento de TDD - Test Driven Development;
  - Conhecimentos e experiência em Java.
  - Inglês intermediário.

### Desejáveis

  - Conhecimentos de DevOps mobile.

## Contratação

  - CLT
  - R$ 5K a .5K

### QUEM É A AGILEPROCESS?

A [AgileProcess](https://agileprocess.com.br/) é uma startup criada para simplificar o processo logístico, tornando-o muito mais eficiente do início ao fim. Junto com pessoas que buscam tornar a logística cada vez mais digital e otimizada, a empresa utiliza as melhores tecnologias do mercado em busca de entregar sempre mais e melhor.

Fundada em 2014 e com sede em Florianópolis, a AgileProcess está em constante crescimento e busca por criatividade, conhecimento, pessoas apaixonadas por inovação e tecnologia e o desejo de tornar a logística 100% digital em uma realidade.

### O QUE FAZEMOS?

Utilizando as melhores tecnologias do mercado, o sistema AgileProcess otimiza o uso da frota, propõe as melhores rotas e sequenciamento de entregas e coletas, auxilia cada motorista, mostrando o percurso com apoio de GPS e faz a comprovação de entregas no exato momento em que forem realizadas.

Hoje, mais de 9 milhões de entregas e coletas passam no software da AgileProcess por mês, presente em mais de 4.600 cidades pelo Brasil.

## Como se candidatar

  - Envie seu currículo para [meu email](mailto:ana.felauto@agileprocess.com.br) OU;
  - Candidate-se através da nossa [página de carreiras]( https://agileprocess.gupy.io/jobs/780913?jobBoardSource=gupy_public_page) OU;
  - Contactarme via [LinkedIn](https://www.linkedin.com/in/ana-gabriella-felauto-5386b3b5/)

**Comment by jpventura** [comment]
Possíveis duplicatas:

  - #1508
  - #1512
