### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Mobile (iOS/Android) | Nuance

### ISSUE THREAD

**Issue by yzraeu** [androiddevbr/vagas#151]
## Descrição da vaga

Desenvolvimento de aplicativos multi-idiomas e multi-plataforma. O candidato irá participar de todas as fases de desenvolvimento e também será procurado para ajudar em questões técnicas e da arquitetura da plataforma. 

## Local

Presencial - Escritório São Paulo - ao lado da Estação Paraíso do metrô (Linha Verde/Azul)

## Benefícios

- CLT
- PLR
- Café, frutas e snacks
- Horário 10:00 - 19:00

## Requisitos

Obrigatórios
- 5+ anos de experiência com desenvolvimento Mobile (iOS/Android)
- Experiência com desenvolvimento e suporte de aplicações iOS e Android
- Conhecimento em C# conforme utilizado no Xamarin
- Capaz de trabalhar independente e com um time extremamente motivado e ágil
- Inglês fluente - entrevista será em inglês

Desejáveis
- Experiência com Xamarin / Xamarin Test Cloud
- Conhecimentos com ferramenta Atlassian Jira
- Conhecimentos com ferramenta Jenkins
- Experiência de trabalho com time remoto - parte da equipe fica no exterior
- Experiência com metodologia Ágil
- Experiência com publicação de aplicativos na App Store e Google Play Store
- Conhecimentos com idiomas adicionais: Francês, Espanhol

Diferenciais
- Já ter desenvolvido algum aplicativo que possa ser demonstrado (Bonus se estiver publicado na App Store ou Google Play)

## Educação

Formação em Engenharia de Software, Ciências da Computação ou equivalente

## Contratação

CLT

## Nossa empresa

http://www.nuance.com/company/index.htm

## Como se candidatar

Por favor envie um email para silmara.silva@nuance.com com seu CV anexado - enviar no assunto: Vaga Mobile (iOS/Android)

**Comment by walmyrcarvalho** [comment]
@yzraeu Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by yzraeu** [comment]
@walmyrcarvalho ainda está em aberto sim.
