### ISSUE TITLE
[Berlin / Germany] Android Engineer (Scala proficient)

### ISSUE THREAD

**Issue by ubiratansoares** [androiddevbr/vagas#152]
## Descrição da vaga

We have a position for an exciting mature start-up in Berlin who are looking to bring on multiple Software Developers within Android and Java/Scala. This company are heavily focused within communication, application and design & technology, and have created a very unique product based on this, so are looking to expand their development team.

This a great time to get on board with this company where you can really make an impact! They provide relocation (ideally EU based), an office with over 20x different nationalities, German classes given to self and partner, free breakfasts and lunches, plus exciting travel incentives!

## Local

Berlin / Germany

## Requisitos

The talented individuals will ideally have:-
- 2-3 years in JVM software development
- Android development experience
- Scala experience ideally (commercial OR personal)
- Have a solid founding/understanding in computer science fundamentals
- English fluency and a great team player

## Como se candidatar

[https://jobs.functionalworks.com/job-board/1542](https://jobs.functionalworks.com/job-board/1542
)

**Comment by walmyrcarvalho** [comment]
@ubiratansoares Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!
