### ISSUE TITLE
[São Paulo] Android Developer na [Pasquali Solution]

### ISSUE THREAD

**Issue by Recrutas** [androiddevbr/vagas#1524]
**Descrição da vaga**
Estamos procurando pessoas que tenha uma vasta experiência em desenvolvimento Android com conceitos de Java

**Local**
Alameda Campinas - SP

**Requisitos obrigatórios:**
•	Java
•	Kotlin 
•	Android 
•	MVVM/MVP
•	Git
•	Git Flow 
•	API Rest 

**Requisitos desejáveis:**
•	Scrum 
•	Kanban 
•	Testes unitários 
•	Inglês Avançado/Fluente 
•	APIs Google (Google Maps SDK, Firebase) 
•	Jetpack

**Labels**
•	Alocado
•	PJ
•	Sênior

**Como se candidatar**
Envie seu currículo https://cutt.ly/vfiG9RX
Envie seu currículo: camila.brito@pasqualisolution.com.br

**Nossa empresa**
A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Comment by davidtcdeveloper** [comment]
@Recrutas Existem diversas vagas abertas para a Pasquali Solution em noso board. Poderia revisar quais continuam abertas ou podem estar duplicadas?

https://github.com/androiddevbr/vagas/issues?q=is%3Aissue+Pasquali+is%3Aopen
