### ISSUE TITLE
Vaga para desenvolvedor Android Sr. 

### ISSUE THREAD

**Issue by andreshige** [androiddevbr/vagas#1528]
Olá, meu nome é André e eu represento a Hexacta Brasil, empresa de constultoria de tecnologia. 

Venho aqui apresentar uma das nossas inumeras vagas, sendo ela para desenvolvedor Android Sr., na ABInbev.
A descrição solicita:

- Linguagens Java e Kotlin,

- Android Studio

- Arquitetura MVP, MVVM

- Conhecimento de GIT e Jira

- Trabalho seguindo método ágil Scrum

Para entrar em contato,
andre.shigemori@hexacta.com.br

**Comment by davidtcdeveloper** [comment]
@andreshige Recomendamos preencher a issue com o template padrão para que seja possível incluir as labels e facilitar a pesquisa.
