### ISSUE TITLE
Desenvolvedor Android

### ISSUE THREAD

**Issue by VRCCASTRO** [androiddevbr/vagas#1529]
**Estamos com algumas posições para pessoas com conhecimento em desenvolvimento em Android.**
•	Conhecimento entre versões Android a partir Api level 15,envolvendo System Services,Apis de Animações,Serv. em background,widgets de layouts;
•	Kotlin; 
•	Material Design; 
•	total domínio ciclo de vida, desde o de responsabilidade/do desenvolvedor ao package lifecycle do Android;Conhec Object Animation,View Animation/Physics Animations;animações de transições de Activity/Fragments, cenas c/widgets;
•	JetPack,Android Architecture Components,Room, LiveData,ViewModel,App Bundle,programação reativa Rx e/ou LiveData;
•	Android 8: Conhecer novas formas implementações Serv. em background p/versões a partir Android 8: Notifications groups,Foreground services c/barra de notificações, JobSchdule, Firebase JobDispatcher;
•	conhecer MVVM/MVP. 

Interessados encaminhar o currículo para: vitoria.cardoso.castro@everis.nttdata.com

**Comment by davidtcdeveloper** [comment]
@VRCCASTRO Recomendamos seguir o template de criação de novas vagas, sem ele fica  bem difícil adicionar labels para facilitar  a pesquisa.
