### ISSUE TITLE
São Paulo-SP [remoto] - Desenvolvedor Android Pleno ou Senior - K2 Solutions

### ISSUE THREAD

**Issue by fbis42** [androiddevbr/vagas#1534]
Requisitos:
Experiência com Java e Kotlin
Experiência/preocupação com UX
Experiência com Arquitetura MVP ou MVVM (preferencialmente MVVM)
Domínio total com GIT e Gitflow
Inglês intermediário
Experiência com Coroutines
Dominar conceito de Injeção de Dependência
Experiência com as ferramentas de Injeção de Dependências (Insert-Koin)

Desejável: Conhecimento de Testes Unitários e de Interface

Contratação: CLT ou PJ
Trabalho – home-office

Skills principais: Java, kotlin, UX

Interessados, enviar currículo atualizado para o e-mail:  **rh@k2solutions.com.br**

Obs: Informar pretensão salarial e disponibilidade.

**Comment by davidtcdeveloper** [comment]
@fbis42 a  contratação será feita pela K2? 
Recomenamos seguir o template de criação de novas issues para que seja possível incluir as labels.

**Comment by fbis42** [comment]
@davidtcdeveloper sim...todo o processo de contratação é feito pela K2. Estou verificando como incluir as labels.

**Comment by davidtcdeveloper** [comment]
@fbis42 
Obrigado pela confirmação.
As labels são adicionadas pela nossa equipe de moderação para as vagas que seguem o template de nova issue.
