### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android Sr | zFlow

### ISSUE THREAD

**Issue by philipefechio** [androiddevbr/vagas#154]
## Descrição da vaga

Desenvolvedor senior em Android.
O app zFlow atua em todas as etapas de e-commerce de veículos.

## Local

Novo Escritório São Paulo - Itaim Bibi

## Benefícios

- Vale-alimentação
- Vale-refeição
- Plano de Saúde
- Bônus atrativo, além do fixo.
- Ambiente de trabalho colaborativo, descontraído, decisões ágeis, autonomia, possibilidades de crescimento. 

## Requisitos

Obrigatórios
- Experiência sênior em Android
- Design Patterns, Scrum e XP, GIT, API Restful ou Webservices, Java.

## Contratação

CLT Full a combinar

## Nossa empresa

A zFlow atua em todas as etapas do processo de compra de um veículo e tem como missão viabilizar o e-commerce automotivo, maximizando a eficiência de revendas e garantindo jornadas de compra memoráveis para consumidores.

## Como se candidatar

Por favor envie um email para philipe.fechio@randstad.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by philipefechio** [comment]
Olá, Walmyr
Sim! Eu tentei, mas não consegui encerrar o tópico, por favor, poderia
fechar?
Obrigado!

**Comment by walmyrcarvalho** [comment]
@philipefechio Opa, desculpa, vou fechar!
