### ISSUE TITLE
[REMOTO OU SALVADOR] [ANDROID] [PLENO] [CLT OU PJ] – Pessoa Desenvolvedora Android na CUBOS

### ISSUE THREAD

**Issue by Franciely12** [androiddevbr/vagas#1547]
Você acredita no poder de transformar a realidade ao seu redor através da tecnologia?! A Cubos também! Nós temos um desejo pujante de criar, impactar, aprender e causar uma diferença significativa na vida das pessoas através da tecnologia. Criamos tecnologia com significado!

Buscamos pessoas desenvolvedoras Android para se unir ao nosso time, alinhadas ao propósito de transformar continuamente a realidade. Oferecemos um ambiente colaborativo com bastante café, flexibilidade, pessoas incríveis dispostas a aprender e ensinar.

Requisitos:

- **Kotlin;**
- **Ao menos um Rest Client;**
- **Versionamento com Git;**
- **Persistência em banco de dados;**
- **Entre outros.**

Contratação: CLT ou PJ

Para saber mais, dá uma olhada no link a seguir:

https://byintera.in/1ch

Um sorriso de orelha a orelha =D

**Comment by davidtcdeveloper** [comment]
@Franciely12 Recomenamos seguir o template da vaga para que seja possível adicionar as labels permitindo que as pessoas encontrem a vaga com mais facilidade.
