### ISSUE TITLE
[SP - Metrô Santa Cruz] - Tech Lead Mobile Android | Studo+

### ISSUE THREAD

**Issue by thiagonetorh** [androiddevbr/vagas#155]
Descrição da vaga

Estamos procurando
por um Tech Lead mobile para nos ajudar na construção de apps desafiadores, focando
na melhoria da educação pública. A equipe de mobile é responsável pela arquitetura,
desenvolvimento e inovação de novas funcionalidades. O candidato ideal deve ter
experiência em desenvolvimento e design de apps Android, com um ou mais apps
publicados no Google Play ou referência similar.

Experiência na área pedagógica é considerada um diferencial!
O perfil de Tech Lead que procuramos é de um engenheiro que esteja confortável em
codificar em 50% do seu tempo, enquanto também acompanha e orienta o
desenvolvimento do time de mobile, sendo o ponto focal de decisões técnicas para a
equipe. É importante que o Tech Lead esteja sempre ciente dos próximos passos do
desenvolvimento, orientando a equipe tecnicamente a alcançar as entregas acordadas
com a equipe de produto. Facilidade com trabalho em equipe e cooperação são pontos
fundamentais, pois a equipe de mobile se integra a outras equipes. Deve se reportar
diretamente para o diretor de tecnologia e interagir com Tech Leads de outras equipes.

Requisitos:
- Experiência como líder técnico
- Experiência em desenvolvimento de apps mobile nativos Android.
- Conhecimento prático sobre design patterns, refactoring e TDD.
- Experiência pratica em consumo de APIS restfull.
- Experiência prática com metodologias ágeis de desenvolvimento.
- Expeirência com desenvolvimento iOS é um diferencial

Local

Escritório no Metrô Santa Cruz - São Paulo

Benefícios

Assistência médica Omint - sem desconto
VR de R$ 25,00 / dia
Máquinas de snacks grátis
PLR
Horário flexível
Requisitos

Obrigatório
Experiência em desenvolvimento de software, focado em Android;
Experiência ou conhecimento teórico de metodologias ágeis (XP e Scrum);
Apps publicados são considerados diferenciais para o candidato;
Sólida experiência com SDK Android;
Experiência com consumo de dados via REST e padrão JSON;
Conhecimentos gerais do ambiente mobile, como arquiteturas, padrões, tendências e tecnologias emergentes.

Contratação

CLT

Studo+

Quem somos
Somos uma startup que busca a melhoria do aprendizado na educação básica. Nosso foco é entender a dinâmica do aprendizado dos alunos, dentro e fora da sala de aula, e propor ações que os levem a maximizar seu potencial.

O que fazemos
Desenvolvemos uma plataforma de gestão e interação educacional para compreender e apoiar o aprendizado, valorizando todos os atores envolvidos no processo.

Como se candidatar

Por favor envie um email para thiagonetorh@gmail.com com seu CV anexado - enviar no assunto: Vaga Tech Lead Android

**Comment by walmyrcarvalho** [comment]
@thiagonetorh Essa vaga ainda está aberta? Senão, irei fechá-la, para fins de organização!

**Comment by walmyrcarvalho** [comment]
Fechando essa vaga, uma similar já foi aberta: https://github.com/androiddevbr/vagas/issues/165

@thiagonetorh Por favor, peço que feche vagas antigas antes de abrir novas.
