### ISSUE TITLE
[REMOTO] Android Engineer na AgileProcess

### ISSUE THREAD

**Issue by anafelauto** [androiddevbr/vagas#1555]
## Descrição da vaga

Buscamos um(a) **Mobile Engineer** que será responsável por prover a melhor experiência para nossos clientes através de nossas soluções mobile.

Como **Mobile Engineer** seus desafios serão:

- Projetar o crescimento do aplicativo utilizando melhores práticas e padrões;
- Disseminar o uso destas práticas e padrões para as demais squads;
- Trabalhar em conjunto com os times de desenvolvimento pensando na evolução de nossa solução;
- Analisar e otimizar os dados sobre o uso de nossa solução;
- Liberdade e pensamento crítico para propor e questionar soluções relacionadas a engenharia.
- Executar a manutenção das soluções mobile, realizando eventuais correções necessárias.

## Local

100% remoto. Estamos localizados em Florianópolis - Santa Catarina.

## Benefícios

- Onboarding de boas-vindas!
- “All Hands”: nosso encontro semanal com o CEO;
- Dress Code: seja você mesmo(a);
- Flexibilidade de horário;
- VR/VA Flex: R$ 550,00 (mês);
- Plano de saúde (para você e quem você ama);
- Plano odontológico;
- TotalPass;
- Clube de Descontos - NewValue;
- PLR;
- Parceria com ZenKlub;
e muito mais!

## Requisitos

- Conhecimentos e experiência em Android Nativo;
- Conhecimentos e experiência em Kotlin;
- Conhecimentos e experiência em metodologia ágil;
- Boas práticas de Clean Code;
- Conhecimento de TDD - Test Driven Development;
- Conhecimentos e experiência em Java.
- Inglês intermediário.

Torcemos para que você tenha:

- Conhecimentos de devops mobile.

## Contratação

CLT.
Salário: R$ 5.000,00 - R$ 10.000,00
Nível: Júnior/Pleno

## Nossa empresa

A AgileProcess é uma startup criada para simplificar o processo logístico, tornando-o muito mais eficiente do início ao fim. Junto com pessoas que buscam tornar a logística cada vez mais digital e otimizada, a empresa utiliza as melhores tecnologias do mercado em busca de entregar sempre mais e melhor.

Fundada em 2014 e com sede em Florianópolis, a AgileProcess está em constante crescimento e busca por criatividade, conhecimento, pessoas apaixonadas por inovação e tecnologia e o desejo de tornar a logística 100% digital em uma realidade.

O QUE FAZEMOS?

Utilizando as melhores tecnologias do mercado, o sistema AgileProcess otimiza o uso da frota, propõe as melhores rotas e sequenciamento de entregas e coletas, auxilia cada motorista, mostrando o percurso com apoio de GPS e faz a comprovação de entregas no exato momento em que forem realizadas.

Hoje, mais de 9 milhões de entregas e coletas passam no software da AgileProcess por mês, presente em mais de 4.600 cidades pelo Brasil.

## Como se candidatar

Você pode se candidatar via:

  - [Email](mailto:ana.felauto@agileprocess.com.br)
  - Nossa [página de carreiras](https://agileprocess.gupy.io/jobs/780956?jobBoardSource=gupy_public_page)
  - [WhatsApp](https://api.whatsapp.com/send?phone=5548988435995)

**Comment by davidtcdeveloper** [comment]
@anafelauto Há diversas issues abertas para a AgileProcess, poderia verificar se as oportunidades ainda estão em aberto ou se podem ser encerradas?
https://github.com/androiddevbr/vagas/issues?q=is%3Aissue+is%3Aopen+agileprocess

**Comment by gusoliveira21** [comment]
[Email](mailto:ana.felauto@agileprocess.com.br) -> Qual o título do e-mail?
Nossa [página de carreiras](https://agileprocess.gupy.io/jobs/780956?jobBoardSource=gupy_public_page) -> Página não encontrada.

**Comment by giovanninibarbosa** [comment]
vaga finalizada

**Comment by gusoliveira21** [comment]
Atualização.
Email continua a não existir e página de carreira ainda não encontrada
