### ISSUE TITLE
[Remoto] Android Mobile Engineer na AgileProcess < by Coodesh />

### ISSUE THREAD

**Issue by gabrielhws** [androiddevbr/vagas#1556]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url https://coodesh.com com o pop-up personalizado de candidatura. :wave:
<p>Buscamos um(a) <strong>Mobile Engineer</strong> que será responsável por prover a melhor experiência para nossos clientes através de nossas soluções mobile.</p>
<p></p>
<p><strong>RESPONSABILIDADES E ATRIBUIÇÕES</strong></p>
<p>Como Mobile Engineer seus desafios serão:</p>
<ul>
<li>Projetar o crescimento do aplicativo utilizando melhores práticas e padrões;</li>
<li>Disseminar o uso destas práticas e padrões para as demais squads;</li>
<li>Trabalhar em conjunto com os times de desenvolvimento pensando na evolução de nossa solução;</li>
<li>Analisar e otimizar os dados sobre o uso de nossa solução;</li>
<li>Liberdade e pensamento crítico para propor e questionar soluções relacionadas a engenharia.</li>
<li>Executar a manutenção das soluções mobile, realizando eventuais correções necessárias.</li>
</ul>
<p></p>
<p><strong>INFORMAÇÕES ADICIONAIS</strong></p>
<p>DNA Agile &lt;3&nbsp;</p>
<p></p>
<p>Faz parte do DNA de todo AGILE ser ambicioso e buscar entregar sempre mais e melhor. O respeito e a tolerância são indispensáveis para nós, e somos apaixonados pela nossa diversidade. Crescemos como time e celebrando juntos todos os resultados atingidos. Somos Customer Centric e buscamos criar conexão com nossos clientes, com simplicidade e empatia. Compartilhamos de forma direta e honesta todas as informações e opiniões possíveis. Reconhecemos nossas fraquezas e assumimos nossos erros. Somos apaixonados por inovação e usamos da nossa criatividade, autonomia e voz para propor novas formas de fazer as coisas.&nbsp;</p>
<p></p>
<p>Somos representados por cada um e nadamos todos na mesma direção.​</p>
<p></p>
<p><em>*Todas as vagas da AgileProcess são abertas para pessoas com deficiência (PcD). </em></p>
<p><em>*Nos processos seletivos da AgileProcess, não há qualquer tipo de distinção em virtude de gênero, orientação sexual, religião, crença, condição social ou raça.</em></p>

## AgileProcess: 
 <p>A AgileProcess é uma startup criada para simplificar o processo logístico, tornando-o muito mais eficiente do início ao fim. Junto com pessoas que buscam tornar a logística cada vez mais digital e otimizada, a empresa utiliza as melhores tecnologias do mercado em busca de entregar sempre mais e melhor.</p>
<p>Fundada em 2014 e com sede em Florianópolis, a AgileProcess está em constante crescimento e busca por criatividade, conhecimento, pessoas apaixonadas por inovação e tecnologia e o desejo de tornar a logística 100% digital em uma realidade.</p><a href='https://coodesh.com/empresas/agileprocess'>Veja mais no site</a>

 ## Habilidades: 
 - Java 
- Kotlin 
- DevOps 
- TDD
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimentos e experiência em Android Nativo; 
- Conhecimentos e experiência em Kotlin; 
- Conhecimentos e experiência em metodologia ágil; 
- Boas práticas de Clean Code; 
- Conhecimento de TDD - Test Driven Development; 
- Conhecimentos e experiência em Java.

## Benefícios: 
 - 100% remota 
- Onboarding de boas-vindas! 
- “All Hands”: nosso encontro semanal com o CEO;   
- Dress Code: seja você mesmo(a); 
- Flexibilidade de horário; 
- VR/VA Flex: R$ 550,00 (mês);  
- Plano de saúde (para você e quem você ama); 
- Plano odontológico;  
- TotalPass; 
- Clube de Descontos - NewValue 
- PLR; 
- Parceria com ZenKlub;
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Android Mobile Engineer na AgileProcess](https://coodesh.com/vagas/android-mobile-engineer-134757?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Mobile

**Comment by anafelauto** [comment]
@gabrielhws @davidtcdeveloper, estamos com todas oportunidades abertas :)
