### ISSUE TITLE
Remoto - Android Developer na Iventis 

### ISSUE THREAD

**Issue by cimerio** [androiddevbr/vagas#1557]
Vagas PJ- 100% Remoto
CV para recrutamento@iventis.com.br

Vaga 1 - Desenvolvedor(a) Android ( com experiência em react native ou interesse em atuar)
Vaga 2 - Desenvolvedor(a) React Native
Vaga 3 -Desenvolvedor(a) Mobile- Web - React Native + Angular/Node

**Comment by davidtcdeveloper** [comment]
@cimerio Recomendamos fortemente seguir o template de publicação da vagas para que possamos adicionar as labels e facilitar a pesquisa de pessoas interessadas.
