### ISSUE TITLE
Desenvolvedor Android (Pontual 2 meses) (In loco)

### ISSUE THREAD

**Issue by catalinacp** [androiddevbr/vagas#156]
Desenvolvedor Android

Alocação pontual pelo período de 2 meses, com possibilidade de prorrogar. Desenvolvimento de soluções que possibilitem acessar as informação através de dispositivos móveis (Tablets e Celulares).              
- Desejável que conheça interface SMP SAP e SAP Gateway e Fiori
Presencial no cliente.

 
Por favor envie um email para contato@dualis.com.br com seu CV anexado e valor taxa hora- enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@catalinacp Essa vaga ainda está aberta? Senão, irei fechá-la pra fins de organização!

**Comment by pedrofsn** [comment]
@catalinacp esta vaga ainda está aberta?
