### ISSUE TITLE
Desenvolvedor(a) Mobile - Remoto - São Paulo

### ISSUE THREAD

**Issue by Bruna-03** [androiddevbr/vagas#1580]
Empresa: Beyond
Atuação: Remoto

Já pensou em fazer parte de uma empresa que vai ALÉM de uma consultoria tradicional de outsourcing?
Nós da BEYOND estamos presentes nas principais organizações do mercado de investimentos e fintechs.

**E-mail: bruna.wehrmann@imaginebeyond.com.br

Oportunidade para Dev's Mobile
Pleno/Sênior**

**Oportunidade Mobile nas linguagens: Swift, Java Nativo, Kotlin, Flutter e React Native.**

**O que esperamos de você:**

🎯 Superior Completo
🎯 Vivência mínima de 2 anos em desenvolvimento de Aplicativos;
🎯 Conhecimento nos Frameworks;
🎯 Conhecimento de versionamento 
🎯 Conhecimento de componentização
🎯 Conhecimento de testes unitários e instrumentados
🎯 Padrões de Projeto, Orientação a Objetos, Gerenciamento de Estado e Arquitetura;

Ainda na dúvida em ser um [ Beyonder ]??
Espia nosso Glassdoor 👇🏻

https://www.glassdoor.com.br/Avalia%C3%A7%C3%B5es/Beyond-Solutions-Avalia%C3%A7%C3%B5es-E2149256.htm

**Comment by khalilayache** [comment]
@Bruna-03 olá Bruna, por favor, conforme as nossas regras solicitam, poderia colocar o local de trabalho e o nome da empresa no título da issue?  assim facilita pras pessoas verem pra onde é a vaga e qual é a empresa contratante! 

Obrigado

**Comment by khalilayache** [comment]
@Bruna-03 faltou o nome da empresa no título! vou manter a issue fechada enquanto você executa esse ajuste, por favor!
