### ISSUE TITLE
[Remoto] Android Developer na MovilePay (Pleno/ Sênior)

### ISSUE THREAD

**Issue by 1jGabriel** [androiddevbr/vagas#1581]
## Descrição da vaga
Estamos em busca de uma pessoa Desenvolvedora Android, que será responsável por desenvolver e atualizar a nossa Conta Digital, colaborando com os demais times no entendimento dos requisitos de negócio e técnico. Criando código limpo, modular, organizado e bem testado.
Utilizamos Coroutines, Navigation, Módulos por features, Moshi, Retrofit, Koin

## Local

Remoto

## Benefícios

Assistência Médica e Odontológica
Vale Refeição ou alimentação de R$ 660/mês
PLR
Auxílio home office
Horário flexível
Mentoria
Incentivo Terapia
Idiomas - A MovilePay reembolsa 50% do curso de inglês ou espanhol que você optar por fazer. 
GymPass
iFood Refeição
Auxílio Creche
Auxílio Material Escolar
Seguro de Vida
Day off no aniversário

## Requisitos

Obrigatórios

- Kotlin
- Git

Desejáveis (não eliminatórios)

- Testes unitários
- Coroutines
- Jetpack Navigation
- Confortável com padrão MVVM/MVI

Diferenciais

- Modularização por feature
- Testes com espresso

## Contratação

CLT

## Nossa empresa

Quem Somos Nós? 

Somos uma fintech do Grupo Movile – empresa líder em marketplaces móveis – nosso propósito é revolucionar o mercado de pagamentos com soluções descomplicadas, inovadoras, democráticas e surpreendentes. 

Nosso sonho grande é ser a maior wallet do Brasil.

## Como se candidatar
Se inscrever pelo link: https://grnh.se/705c80f72us

**Comment by 1jGabriel** [comment]
@davidtcdeveloper atualizei a vaga para nível Senior também

**Comment by gusoliveira21** [comment]
O link não funciona mais.
A vaga foi encerrada.

**Comment by giovanninibarbosa** [comment]
vaga finalizada
