### ISSUE TITLE
[REMOTO] Desenvolvedora(o) Pleno Mobile Kotlin

### ISSUE THREAD

**Issue by taxconhr** [androiddevbr/vagas#1583]
Descrição da vaga
Estamos buscando desenvolvedor Android para o nosso time em Curitiba PR, para atuar com Kotlin.

Local
Curitiba - Centro

Contrato CLT
Remuneração a combinar
Benefícios
-Plano de saúde
-Plano odontológico
-Seguro de vida
-VR
-VT

Contratação PJ
Remuneração a combinar

Requisitos
-Conhecimento em Kotlin / Java
-Conhecimento em programação orientada a objetos
-Experiência com Android SDK / Android Studio
-Git

Como se candidatar
Por favor envie um email para contato@milkup.com.br com seu CV anexado - enviar no assunto: Vaga Android - PR

**Comment by taxconc** [comment]
> Descrição da vaga
> Estamos buscando desenvolvedor Android para o nosso time em Curitiba PR, para atuar com Kotlin.
> 
> Local
> Curitiba - Centro
> 
> Benefícios
> -Plano de saúde
> -Plano odontológico
> -Seguro de vida
> -VR
> -VT
> 
> Requisitos
> -Conhecimento em Kotlin / Java
> -Conhecimento em programação orientada a objetos
> -Experiência com Android SDK / Android Studio
> -Git
> 
> Contratação
> CLT
> Remuneração a combinar
> 
> Como se candidatar
> Por favor envie um email para [contato@milkup.com.br](mailto:contato@milkup.com.br) com seu CV anexado - enviar no assunto: Vaga Android - PR
