### ISSUE TITLE
[São Paulo, SP] Desenvolvedor (a) Android  [SENIOR] Moochies Technologies

### ISSUE THREAD

**Issue by marinanova** [androiddevbr/vagas#1584]
A **Moochies** é uma empresa de tecnologia e telecomunicações para crianças. Nós fazemos relógios / smartphones, conectado com o aplicativo Moochies no telefone dos pais, que permite que os pais controlem as configurações do relógio.

Buscamos profissionais apaixonados por tecnologia e inovação para atuar com Desenvolvimento Mobile - Android.

- Graduação na área de TI (completa ou cursando);

- Experiência profissional Java e Kotlin, Android Studio, Design Patterns ( MVVM, MVP ),Versionamento de código (git), Git Flow e Consumo de API Rest;

- Conhecimento desejável em APIs Google (Google Maps SDK, Firebase), Jetpack

Contrato PJ com VR + curso de inglês na empresa + Bônus

***Disponibilidade para atuar 3 dias da semana no escritório - região da Avenida Paulista***

**Comment by davidtcdeveloper** [comment]
@marinanova Há outra issue aberta em nosso mural para oportunidade da Moochies, poderia verificar se trata da mesma vaga?
https://github.com/androiddevbr/vagas/issues/1526
Também recomendamos seguir o template de nova vaga para permitir a classificação com labels.

**Comment by marinanova** [comment]
Olá boa tarde,

sim, se trata da mesma vaga (mesma atividade) porém são duas oportunidades
em abertas. Mas desta forma, então acredito que podemos permanecer com a
divulgação da primeira posição.

Att

Em sex, 21 de mai de 2021 15:41, David Tiago Conceição <
***@***.***> escreveu:
