### ISSUE TITLE
Android Developer na WillFly - Home office.

### ISSUE THREAD

**Issue by Robrtha** [androiddevbr/vagas#1590]
[B] Android Developer na [WillFly - Home office ]

## Descrição da vaga
Trabalhar com equipes de desenvolvimento e gerentes de produto para idealizar soluções de software;
Desenvolver e sustentar integrações;
Escrever testes e corrigir erros ou outros problemas de codificação;
Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
Atuar como uma das referências em projetos de desenvolvimento mobile para voos de drone;
Publicação nas app stores.
Analisar métricas e monitoramento/troubleshooting de crashs.

## Local

Remoto 

## Benefícios

Flexibilidade de horário;
Home office;
Salário compatível com a vaga;
Oportunidade de crescimento na startup;
Ambiente de aprendizado.

## Requisitos
👉Para voar com a gente, você precisa de:

Kotlin;
Java;
Métodos ágeis;
Rest API;
Escrita de testes automatizados;
Conhecimento do processo de publicação app store;
Conhecimento em monitoramento e métricas (performance, crash report, analytics etc.);
Entender processos e boas práticas de Engenharia de Software.
Diferencial 

Flutter;( Básico)
Dart;( Básico)

Obrigatórios

- 2+ anos de experiência com Android

Desejáveis

- Experiência com Java e Kotrin

Diferenciais

- Dart e Flutter

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para Roberta.felix@talentbrand.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by khalilayache** [comment]
@Robrtha conforme as nossas regras de divulgação das vagas, é necessário ter o nome da empresa no título e o local. Sem isso a vaga poderá ser fechada!

**Comment by Robrtha** [comment]
> @Robrtha conforme as nossas regras de divulgação das vagas, é necessário ter o nome da empresa no título e o local. Sem isso a vaga poderá ser fechada! Poderia alterar por favor?

Atualizado, obrigada ;) @khalilayache

**Comment by khalilayache** [comment]
@Robrtha  Oi, desculpe, mas não foi não, o título atual  ainda é "[B] Android Developer na [Nome da Empresa]". é  o campo que contém esse texto que precisa ser alterado. 
Vi que você colocou na primeira linha  da descrição da vaga "Desenvolvedor(a) Mobile Android Pleno/Sênior | WillFly (Home office)." sendo que o lugar a ser alterado era o título.

Pode por favor alterar? Obrigado

**Comment by Robrtha** [comment]
@khalilayache verifica se agora está correto por favor?

**Comment by khalilayache** [comment]
@Robrtha ainda não! Como eu mencionei no comentário acima...

O título é o que tá escrito como "[B] Android Developer na [Nome da Empresa]"... é esse campo que precisa ser alterado, não o que está escrito na descrição.

**Comment by khalilayache** [comment]
@Robrtha Agooora sim! Vou dar um tempinho e apagar os comentários aqui para não ficar poluído o post da vaga! Obrigado você

**Comment by Robrtha** [comment]
@khalilayache, perfeito muitíssimo obrigada.
