### ISSUE TITLE
[REMOTO] Desenvolvedor Android Nativo (Kotlin) - Lead Up Digital

### ISSUE THREAD

**Issue by emanuelagape** [androiddevbr/vagas#1594]
Requisitos:

Saber desenvolver pontes nativas para o RN(React Native) e implementar bibliotecas específicas para o ecossistema. Executar documentação das interfaces de ponte criadas para o time de implementação de app (RN)

• Experiência com apps publicados na Play Store Google
• Conhecimentos sólidos em Kotlin e/ou Java
• Android Studio e Android SDK
• Experiência com ferramentas de versionamento (GitHub)

Desejável:

• Conhecimento em Firebase
• Conhecimento em Postgres
• Conhecimento em Node JS

Contratação:

• PJ a combinar;
• Full-time;
• Remoto.

Como se candidatar:

• Basta preencha o formulário de candidatura através deste link 

https://app.pipefy.com/public/form/cP6bDODX

**Comment by khalilayache** [comment]
@emanuelagape Segundo as regras para divulgar vaga por aqui é que no título contenha o local de trabalho e a empresa contratante. Pode alterar por favor?

**Comment by emanuelagape** [comment]
Certamente!! Vou corrigir agora
