### ISSUE TITLE
Sysmap Solutions: Oportunidade Dev SR Android (100% Remoto - Brasil)

### ISSUE THREAD

**Issue by Vanmob123** [androiddevbr/vagas#1596]
A Sysmap está com super oportunidades para Desenvolvedor Android - Sênior, atuação 100% remoto, para atuar em empresa do segmento de cosméticos:

Requisitos:
Experiências em desenvolvimento em Kotlin;
Experiência em gerenciamento de threads e programação assíncrona;
Experiências com Arquitetura MVVM (JETPACK) e Databinding;
Experiências com Injeção de dependências com Dagger 2 / Koin;
Experiências com Retrofit;
Testes unitários com Mockito e Robolectric;
Testes funcionais E2E com AndroidX UI Automator;
Integração Contínua;
Deploy Contínuo;
Clean Code;
Estrutura modularizada e independente;
Conhecimento e experiências com Github e Gitflow;
Preocupação com qualidade do código e funcionalidades;
Scrum/XP/Metodologias Ágeis;
Desejável experiência com React Native.

Encaminhar CV para vanessa.cruz@sysmap.com.br

**Comment by khalilayache** [comment]
@Vanmob123 conforme as regras na página inicial desse repositório: é obrigatório que o título da issue contenha o local da oportunidade e a empresa contratante. Poderia por favor arrumar? 

Aproveitando, aconselhamos seguir o padrão de detalhamento da vaga para que seja possível colocarmos labels e que o candidato tenha mais informações sobre a mesma

**Comment by Vanmob123** [comment]
> @Vanmob123 conforme as regras na página inicial desse repositório: é obrigatório que o título da issue contenha o local da oportunidade e a empresa contratante. Poderia por favor arrumar?
> 
> Aproveitando, aconselhamos seguir o padrão de detalhamento da vaga para que seja possível colocarmos labels e que o candidato tenha mais informações sobre a mesma

**Comment by Vanmob123** [comment]
Olá ! Obrigada pelo retorno ! é a minha primeira divulgação e não consegui editar a descrição da vaga.

**Comment by khalilayache** [comment]
@Vanmob123 tudo bem, não tem problema nenhum.. estamos aqui para ajudar na organização das informações que beneficiem todo mundo

Sobre a edição da descrição você pode apertar nos 3 pontinhos no canto direito em cima da descrição e tem a opção Editar

**Comment by Vanmob123** [comment]
> @Vanmob123 tudo bem, não tem problema nenhum.. estamos aqui para ajudar na organização das informações que beneficiem todo mundo
> 
> Sobre a edição da descrição você pode apertar nos 3 pontinhos no canto direito em cima da descrição e tem a opção Editar

**Comment by Vanmob123** [comment]
muito obrigada ! Agora, acho que está ok !

**Comment by khalilayache** [comment]
@Vanmob123  Agora está ok! Você tinha fechado a issue, mas reabri novamente! Vou apagar os comentários em alguns minutos para a vaga não ficar poluída
