### ISSUE TITLE
Analista de Desenvolvimento - Adroid Nativo 

### ISSUE THREAD

**Issue by klassetech** [androiddevbr/vagas#1597]
A Positivo Tecnologia, empresa nacional com presença global e certificada pelo Great Place to Work (GPTW) como uma das melhores para se trabalhar. Que desenvolve produtos e soluções tecnológicas como notebooks, desktops, celulares, tablets, dispositivos para casas e escritórios inteligentes (IoT), tecnologias educacionais, servidores para data centers e muito mais. 

Que tal fazer parte desta equipe?

**ANALISTA DE DESENVOLVIMENTO** (Remoto)

Conhecimento Android nativo (Java/Kotlin)
Conhecimento de orientação a objetos
Conhecimento em Git e testes unitários (TDD)

Se interessou? envie um currículo para janaina@klassetech.com.br

**Comment by khalilayache** [comment]
@klassetech conforme as nossas regras de submissão de vaga, que estão nesse repositório, é obrigatório colocar o nome da empresa e o local/cidade de trabalho no título da vaga. Pode corrigir por favor? Sem isso a issue será fechada nos próximos dias

Uma segunda coisa: sugerimos seguir o template de descrição de vaga que colocamos, assim fica mais fácil saber quais labels colocamos e permite que o candidato tenha mais informações sobre a vaga e a empresa.
