### ISSUE TITLE
[Florianópolis, Santa Catarina] Desenvolvedor Android Senior | Bravi Software

### ISSUE THREAD

**Issue by pucamafra** [androiddevbr/vagas#16]
## Descrição da vaga

Desenvolvimento e manutenção de aplicativos para o sistema Android

## Local

Florianópolis - Santa Catarina

## Benefícios

- Benefícios (UNIMED Nacional, Uniodonto, VISA Vale, Auxílio Combustível)
- 1 dia de folga no seu aniversário
- Oportunidade de eventualmente trabalhar remoto
- Ambiente dinâmico onde pessoas vem primeiro
- E um excelente ambiente de trabalho
- Dois monitores por colaborador

## Requisitos

Obrigatórios
- 3 anos ou mais de experiência com Android
- Experiência com consumo de Webservices e API’s REST
- Conhecimentos avançados do Android SDK, das diferenças entre versões e plataformas
- Controle de versão distribuído (Git)
- Ciclo de vida de activities e fragments
- Boas práticas de desenvolvimento mobile
- Conhecimento em Java, orientação a objeto e design patterns
- Adaptação de layouts para diferentes tamanhos de telas e dispositivos
- Conhecimento em Java, orientação a objeto e design patterns
- Conhecimento das guidelines de design do Google Play e de desenvolvimento
- Inglês intermediário ou avançado

Desejáveis
- Experiência com RxJava
- Experiência com RxAndroid

Diferenciais
- Contribuição em algum projeto opensource
- Ter algum aplicativo publicado na Google Play

## Contratação

CLT

## Nossa empresa

A Bravi é uma empresa especializada no desenvolvimento de soluções e tecnologia. Nós acreditamos que a tecnologia e a educação tem o poder de transformar empresas comuns em inovadoras. Por isso, desenvolvemos softwares que promovem a cultura da mobilidade digital para o engajamento dos colaboradores. E para completar o ciclo de aprendizado, geramos reflexões e insights por meio da análise de dados em larga escala.

## Como se candidatar

Por favor envie um email para recrutamento@bravi.com.br com seu CV anexado - enviar no assunto: Vaga Android

Mais informações em [http://www.bravi.com.br](url)

**Comment by walmyrcarvalho** [comment]
@pucamafra Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by pucamafra** [comment]
@walmyrcarvalho Opa, desculpa, foi preenchida semana passada. To fechando, valeu.

**Comment by walmyrcarvalho** [comment]
@pucamafra Sem problemas, valeu! 👍
