### ISSUE TITLE
[SP - Vila Leopoldina] - Desenvolvedor Android - Nativo | Iterative

### ISSUE THREAD

**Issue by rafaelnicolett** [androiddevbr/vagas#160]
## Empresa

A ITERATIVE é uma empresa de TI, inovadora, dinâmica e moderna, em plena ascensão e expansão, com seus serviços e produtos. 

Nosso time é composto por profissionais que gostam de tecnologia, comprometidos com prazos, responsáveis, engajados, criativos, dinâmicos e com bom senso de humor, criando um ambiente descontraído e uma equipe altamente eficaz e responsável. 

## Descrição da vaga

Imprescindível

•	Sólida experiência em Java/Android
•	Design patterns
•	Padrão de Arquitetura/Organizacao de Codigo (MVP, Clean Architecture, ...)
•	Conhecimento em Testes unitários e de Aceitação
•	Experiência com as últimas tecnologias da plataforma 
•	Android (RxJava, Dagger2, Realm, JUnit4, Espresso, Retrofit)
Desejável:
•	Formação em engenharia da computação ou Ciência da Computação ou correlatas
•	Experiência em metodologia apoiado em Testes (TDD / diferencial BDD)
•	Padrões de Segurança da Informação (OWASP)
•	Ter Conhecimento em Xamarin
Observações:
•	Código de projetos no Github será de grande valor agregado para seleção técnica;
•	Portfolio de APPS será um diferencial para seleção.

## Local

Nosso escritório fica na Vila Leopoldina, temos algumas Vans que circulam de 15 em 15 minutos nas estações: Imperatriz Leopoldina e Ceasa. 
Horário de trabalho flexível e não batemos ponto.

## Benefícios

Forma de Contratação PJ (aceitamos empresas simples) 
Descanso Remunerado após 12 meses de contrato
Participação de Lucros Trimestral 

## Como se candidatar

Enviar currículos atualizados para: camila.wolf@iterative.com.br com assunto Desenvolvedor Android Pleno

**Comment by walmyrcarvalho** [comment]
@rafaelnicolett Essa vaga ainda está aberta? Senão, irei fechá-la pra fins de organização!

**Comment by rafaelnicolett** [comment]
@walmyrcarvalho ainda está aberta.
