### ISSUE TITLE
[Remoto] Desenvolvedor Android | Domvs

### ISSUE THREAD

**Issue by thaisvilladal** [androiddevbr/vagas#1603]
## Descrição da vaga

Buscamos uma Pessoa Desenvolvedora Mobile Android capaz de arquitetar e construir interfaces que proporcionem a melhor experiência em aplicativos de música da plataforma Android, que seja apaixonado(a) por aprender e codificar (em Java e Kotlin) e que goste de pensar no produto além das linhas de código.

Será responsável por pensar, contribuir no planejamento e desenvolver novas funcionalidades dos produtos para Android.

Irá trabalhar junto com nosso time de engenheiros na arquitetura e definição de soluções de alta escala e alta disponibilidade e utilizar as melhores práticas e tecnologias para escrever código que se orgulhará de ler amanhã.

Esse profissional será responsável em participar do início ao fim do projeto de desenvolvimento de um app de histórias infantis onde terá um áudio contendo todas essas histórias.

## Local

Remoto - Aceitamos candidatos de todo o Brasil

## Requisitos

Obrigatórios

✔Paixão em escrever código e pela plataforma Android (Kotlin).
✔Vivência com desenvolvimento de aplicativos para plataforma Android.
✔Domínio de conceitos de OOP e conhecimento em conceitos de Functional Programming.
✔Conhecimento sobre os guidelines de desenvolvimento e usabilidade da plataforma Android.
✔Habilidade de desenvolver aplicativos do seu início ao fim.
✔Conhecimento em desenvolvimento de interface dentro do Android.
✔Se sentir confortável com arquiteturas de desenvolvimento

## Contratação

PJ a combinar - remuneração em aberto

## Nossa empresa

Somos uma consultoria de TI focada em oferecer excelência aos nossos Clientes e desenvolvimento aos nossos Colaboradores, através de soluções, pessoas e processos pensados para cada necessidade de negócio. 

Buscamos profissionais com sede de tecnologia, que curta muuuito novos desafios e que seja apaixonado pelo que faz! 

Valorizamos o espírito de equipe, por isso é importante que você também valorize. 

## Como se candidatar

Por favor envie um email para thais.villadal@domvs.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by khalilayache** [comment]
@thaisvilladal  essa vaga aqui é a mesma que essa https://github.com/androiddevbr/vagas/issues/1602?  Se for, só é permitido manter uma vaga aberta por vez, por isso por favor feche uma das duas!
