### ISSUE TITLE
[Porto Alegre - RS / Sydney - AUS] Mobile Tech Lead

### ISSUE THREAD

**Issue by patrickds** [androiddevbr/vagas#162]
## Empresa
Fundada há 24 anos, empregando as mais avançadas tecnologias de informação e o controle efetivo e ágil de projetos. Atualmente com mais de 400 colaboradores, atuando em Porto Alegre/RS, Caxias do Sul/RS, Curitiba/PR, São Paulo/SP, Rio de Janeiro/RJ e Sidney/AUS.

Nosso foco são as pessoas e a cultura da empresa. Bons resultados são gerados a partir da combinação de um bom clima organizacional, com colaboradores satisfeitos e uso de práticas e ferramentas adequados. 
- Indivíduos e interação entre eles – mais que processos e ferramentas
- Software em funcionamento – mais que documentação abrangente
- Colaboração com o cliente – mais que negociação de contratos
- Responder a mudanças – mais que seguir um plano

#### Serviços
Teste Center, Projetos de Software, Fábrica de Software, Outsourcing e Consultoria de Software e Métodos Ágeis.

## Descrição da vaga
Como Líder Técnico de Mobile no nosso time, você será responsável por definir e promover o uso das melhores práticas no desenvolvimento de aplicações para smartphones, além de liderar e ser o mentor de outros desenvolvedores no time. Estamos construindo uma experiência de apostas online de primeira classe usando tecnologias de ponta para suportar enormes quantidades de transações em uma plataforma personalizada que precisa ser robusta, segura e altamente escalável. Você vai trabalhar com um time altamente colaborativo onde sua opinião e ideias serão extremamente valorizadas, em um ambiente em constante evolução que combina o interessante domínio dos esportes com as complexidades do mercado financeiro, utilizando as mais recentes tecnologias digitais.

### Mais informações

- Onboarding do projeto com todo o time em Sydney, Australia.
- Membros do time de Porto Alegre revezando em Sydney a cada 3 meses.
- Time Ágil extremamente colaborativo em Porto Alegre e Sydney.
- Ambiente de trabalho que promove aprendizado contínuo e experimentos com novas tecnologias.
- Você irá liderar um time de alto calibre técnico distribuído e em fusos diferentes.

## Posição
Mobile Tech Lead

## Tipo de contratação
 CLT

## Requisitos

Dar direção ao time em relação à uma ou mais áreas de desenvolvimento. Assumir uma posição pró-ativa de líder técnico em discussões de design de software e tomar a responsabilidade por implementações de sucesso.
Dar o exemplo e liderar/ser mentor do time em todos os aspectos relacionados a desenvolvimento de software e melhores práticas e princípios.

###### Obrigatórios

 - Desenvolver, testar e manter aplicativos nativos para Android.
 - Utilizar e promover as práticas e valores Ágeis.
 - Garantir que as soluções são testáveis escrevendo testes unitários e funcionais.
 - Inglês falado e escrito de nível avançado.
 - Extenso conhecimento em software design patterns para desenvolvimento para smartphones.
 - Experiência com desenvolvimento de aplicações multi-threaded para Android consumindo APIs RESTful.

###### Desejáveis

- Experiência com TDD.
- Experiência com Appium.
- Prática de Continuous Delivery como CI e automação de testes.
- Experiência com ferramentas de automação de testes com Android Studio ou Xcode.
- Experiência com BuildKite.
- Muito bom conhecimento de arquiteturas comuns de aplicativos e aplicaçõesweb e metodologias de desenvolvimento, incluindo as ágeis.
- Conhecimento de ferramentas e processos de DevOps.
- Disposto a aprender e trabalhar através de ambas plataformas (iOS e Android) quando necessário (mesmo que especializado em alguma delas). 

###### Diferenciais

- Experiências profissionais no exterior.
- Contribuições ativas para a comunidade open source ou Ágil.

## Remuneração

Salário a combinar + benefícios

## Como aplicar e Contato

Email: [vagas_australia@dbserver.com.br](vagas_australia@dbserver.com.br)

**Comment by walmyrcarvalho** [comment]
@patrickds Essa vaga ainda está aberta? Senão, irei fechá-la pra fins de organização!
