### ISSUE TITLE
[REMOTO] Desenvolvedor(a) Android na SOUTH SYSTEM

### ISSUE THREAD

**Issue by ghost** [androiddevbr/vagas#1620]
## Descrição da vaga

A SOUTH SYSTEM está em busca de um(a) Desenvolvedor (a) Android Júnior, Pleno ou Sênior que queira fazer parte do nosso propósito de impulsionar as pessoas para inovar o mundo. Para fazer parte do time, há algumas skills que valorizamos muito, e não estamos falando apenas de tecnologia, nós valorizamos profissionais que respeitem o próximo e suas diferenças, que sejam leais e responsáveis com as entregas e com as pessoas. A colaboração e engajamento devem fazer parte do dia a dia para que o resultado seja eficaz e que tenha sede de aprendizado para trabalhar com inovação contínua.

## Local

Remota

## Benefícios

- Parceria com a Udemy (+ de 4 mil cursos gratuitos)
- Parceria com a Vitalk (plataforma de saúde mental e acompanhamento psicológico, gratuito)
- Parceria com a Money Mind (Consultoria financeira gratuita)
- Acompanhamento constante (avaliação de performance e Plano de Desenvolvimento Individual)
- Ajuda de custo para montar seu Home Office

## Requisitos

**Nessa oportunidade, o(a) profissional trabalhará com:**

- Desenvolvimento nativo em Kotlin;
- Arquitetura MVVM + Databinding;
- Injeção de dependências com Dagger 2;
- Retrofit;
- Testes unitários com Mockito + Robolectric;
- Testes funcionais automatizados;
- Integração Contínua;
- Deploy Contínuo;
- Clean Code;
- Estrutura modularizada e independente.

**Para isso, é importante ter:**

- Experiência com desenvolvimento Android e Kotlin;
- Experiência com setup de projetos com Bitrise e Fastlane;
- Conhecimento com GitFlow;
- Conhecimentos em processo de publicação na Play Store.

## Contratação

CLT

## Nossa empresa

https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-SOUTHSYSTEM-EI_IE2433278.13,24.htm

## Como se candidatar

Se interessou pela oportunidade e curte ambientes que invistam no teu desenvolvimento? Então não perde tempo e envia o teu currículo para atracaodetalentos@southsystem.com.br

## Labels

- Android
- Júnior
- Pleno
- Sênior
- CLT

**Comment by davidtcdeveloper** [comment]
@kaueny Existem outras issues abertas com vagas para a South System:
https://github.com/androiddevbr/vagas/issues?q=is%3Aissue+is%3Aopen+SOUTH+SYSTEM
Poderia verificar se as issues tratam da mesma vaga?

**Comment by kaueny** [comment]
> @kaueny Existem outras issues abertas com vagas para a South System:
> https://github.com/androiddevbr/vagas/issues?q=is%3Aissue+is%3Aopen+SOUTH+SYSTEM
> Poderia verificar se as issues tratam da mesma vaga?

oie! como faço para excluir a outra?

**Comment by kaueny** [comment]
> @kaueny Existem outras issues abertas com vagas para a South System:
> https://github.com/androiddevbr/vagas/issues?q=is%3Aissue+is%3Aopen+SOUTH+SYSTEM
> Poderia verificar se as issues tratam da mesma vaga?

Olá! São vagas diferentes :)
