### ISSUE TITLE
Vaga Desenvolvedor Android Nativo [100% remoto]

### ISSUE THREAD

**Issue by AliceBonez** [androiddevbr/vagas#1623]
Se você é Desenvolvedor Android Nativo e tem experiência de pelo menos 2 anos em Kotlin, essa vaga é para você!
No link abaixo tem mais informações e você pode se candidatar!
https://bemfacilcontrate.com.br/oportunidades-detalhes.php?titulo=desenvolvedor-android-nativo&id=517
Ou, me chama no linkedin: https://www.linkedin.com/in/alicebonez/

**Comment by davidtcdeveloper** [comment]
@AliceBonez As regras do nosso mural de vagas exigem a divulgação do nome da empresa contratante. A issue será encerrada até que o nome seja adicionado.
