### ISSUE TITLE
[Rio de Janeiro, RJ] Desenvolvedor Android | Winnin

### ISSUE THREAD

**Issue by ericholiveira** [androiddevbr/vagas#163]
## Descrição da vaga

Estamos buscando candidatos que  querem trabalhar com as tecnologias mais avançadas do mercado: testes automatizados, integração contínua e interfaces com unicórnios que vomitam arco-íris.

## Local

Escritório em Ipanema

## Requisitos

Obrigatórios
- Java e orientação a objetos
- Criação de interface de usuário para os diferentes devices e tamanhos de tela
- Integrações com serviços web
- Sabe usar bem o git
- Nos diga qual site de Android que você costuma acessar

Desejáveis
- Conhecimento de TDD
- Uso de teste automatizados
- Conhecimento do metodologias ágeis (Kanban, Scrum);
- Conhecimento profundo dos guidelines de desenvolvimento e interface do Android

## Contratação

PJ  com 13 salários e férias

## Nossa empresa

Somos uma startup financiada pela Coca-Cola chamada winnin (winnin.com) e nosso negócio é criar conteúdos divertidos e engajadores baseados no conhecimento que obtemos através da nossa plataforma voltada para jovens.
A nossa empresa tem dois anos e estamos fechando uma nova rodada de investimento no momento.
Somos uma startup nacional, porém pretendemos expandir para outros países (EUA e México) ainda esse ano.

## Como se candidatar

Por favor envie um email para erich.oliveira@winnin.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by halysongoncalves** [comment]
Pode ser remoto ou Freelancer?

**Comment by ericholiveira** [comment]
Damos preferência a contratação local. Casos de remoto ou freelancer só serão analisados caso a vaga não possa ser preenchida de outra forma
