### ISSUE TITLE
Remoto - Desenvolvedor Android Nativo Sênior - PJ

### ISSUE THREAD

**Issue by Recrutador-De-TI** [androiddevbr/vagas#1636]
Vaga de TI Home Office!
Desenvolvedor (a) Android Nativo Sênior (PJ)

Selecionamos para agência de Tecnologia de São Paulo!

Local: Remoto.

Requisitos:
Kotlin;
Injeção de dependência com Dagger ou similar;
Conhecimento em Rx ou Coroutines;
Consumo de API REST com Retrofit ou similar;
Versionamento (GIT).

Carga horária semanal: 40 horas.

Regime de contratação: PJ.

Contatos: 51996925571, arthur.tischler@grupodreamwork.com.br ou https://www.linkedin.com/in/contratarthur/

**Comment by davidtcdeveloper** [comment]
@Recrutador-De-TI 
Conforme as regras do nosso mural de vagas, é obrigatória a divulgação do nome da empresa contratante.
A issue será encerrada até que seja editada com o nome da empresa.
