### ISSUE TITLE
[GO - Rio Verde] ON GO - Desenvolvedor Android Nativo

### ISSUE THREAD

**Issue by fykos** [androiddevbr/vagas#164]
## Empresa
 O ON GO é um aplicativo de mobilidade urbana, com táxi, mototáxi e motofrete.

## Descrição da vaga
 Auxiliar no desenvolvimento do aplicativo já existente em Android Nativo.
 Efetuar testes e corrigir bugs e desenvolver novas implementações
 Caso conheça alguém, também precisamos de programador iOS e Analista/Desenvolvedor WEB PHP/MySQL.

## Posição
 Pleno

## Tipo de contratação
 Presencial, CLT, PJ. 

## Requisitos
 Desenvolvedor de aplicativo nativo em Java utilizando Android Studio última versão.

###### Obrigatórios
 Já possuir um aplicativo em nativo Android já publicado na PlayStore ou em fase de testes em Android.

## Com quem você vai trabalhar
| ![](https://github.com/waister.png?size=117) | ![](https://github.com/fykos.png?size=117) |
| --- | --- |
|[Waister](https://github.com/waister)|[Elis](https://github.com/fykos)|
|Desenvolvedor Android|Desenvolvedor iOS|

## Como aplicar
 Envie um e-mail para ongo-github@elisnunes.com.br

## Contato
 WhatsApp: (64) 99299-4416
 E-mail: ongo-github@elisnunes.com.br

**Comment by walmyrcarvalho** [comment]
@fykos Essa vaga ainda está aberta? Senão, irei fechá-la pra fins de organização!
