### ISSUE TITLE
[Remoto] Android Developer - Kotlin / Java (JR/PL/SR) na Qintess

### ISSUE THREAD

**Issue by rtakara** [androiddevbr/vagas#1640]
EMPRESA
Com 30 anos no mercado, somos uma multinacional brasileira entre as maiores integradoras de TI do Brasil.
Valorização dos talentos, seriedade, compromisso no atendimento aos clientes, agilidade e qualidade nos projetos são algumas das premissas que nos diferenciam.
São mais de 2000 clientes – grandes empresas nacionais e globais – que nos reconhecem pela excelência e inovação, o que só é possível pelo trabalho de uma equipe altamente qualificada e engajada. Reunimos diferentes programas de qualidade de vida e oportunidades de carreira, além de ações para proporcionar um ambiente de trabalho motivador e colaborativo, com incentivo à diversidade e à inovação. Tudo isso, baseado nos princípios ESG – Environmental, Social and Governance (em português: Ambiental, Social e de Governança), uma prática global que tem ganhado força no mundo dos negócios e que é composta por três fatores centrais que atuam na medição da sustentabilidade e do impacto social de uma empresa.
Mais de 3.500 profissionais altamente capacitados compõem a nossa equipe em mais de 151 cidades no Brasil e na América Latina. Estamos na era da mudança permanente e, nesse cenário, trabalhamos para suportar as empresas à alcançarem um novo patamar de desempenho e alavancarem à transformação digital.
Somos uma fonte de geração de ideias, que trabalha de forma colaborativa, que transforma pessoas e estas transformam o jeito de fazer negócios.

Para mais informações, acesse: www.qintess.com

DESCRIÇÃO DA VAGA
Android Developer - Kotlin e Java

LOCAL
Home Office

BENEFÍCIOS
• Plano de saúde AMIL Apto
• Convênio Odontológico - AMIL DENTAL
• Seguro de vida
• Vale refeição
• Auxílio creche
• Convenio Farmácia

REQUISITOS
Obrigatórios

• Conhecimentos em padrões arquiteturais MVVM etc…;
• Atuação com kotlin / Java, Engenharia de Software, Design Patterns etc…
• Saber estruturar tela usando XML e Custom Views;
• Conhecimento básico da arquitetura Android
• Conhecimento em Lifecycles, Threads, Services, Intents
• Experiência com padrão modularização
• Versionamento de código utilizando Git.

Nível Sênior: profundos conhecimentos em padrões arquiteturais VIPER, MVVM etc… e perfil de líder, engajando e ajudando outros dev’s

Diferencial:

• Experiência com CI/CD
• Construção / manutenção de pipelines em AzureDevops

Como se candidatar
Por favor envie um email para roger.takara@qintess.com com seu CV anexado - enviar no assunto: [Remoto] Android Developer [Seu nome completo]

Contratação:
CLT

Nível:
Júnior
Pleno
Sênior

**Comment by danilodox** [comment]
A vaga é para Android Developer - Kotlin / Java. 
Mas para enviar o e-mail com o currículo eu coloco como assunto "Front-End Developer (ReactJS)". É isso mesmo ?
