### ISSUE TITLE
[SP - Metrô Santa Cruz] - Tech Lead Android - Pleno e Senior | Studo+

### ISSUE THREAD

**Issue by thiagonetorh** [androiddevbr/vagas#165]
O perfil de Tech Lead que buscamos é de um engenheiro que esteja confortável em codificar em 50% do seu tempo, enquanto também acompanha e orienta o desenvolvimento do time de mobile, sendo o ponto focal de decisões técnicas para a equipe.

Requisitos:
Experiência como líder técnico
Experiência em desenvolvimento de apps mobile nativos Android.
Conhecimento prático sobre design patterns, refactoring e TDD.
Experiência pratica em consumo de APIS restfull.
Experiência prática com metodologias ágeis de desenvolvimento.

Local

Escritório no Metrô Santa Cruz - São Paulo

Benefícios

Assistência médica Omint - sem desconto
VR de R$ 25,00 / dia
Máquinas de snacks grátis
PLR
Horário flexível
Requisitos

Obrigatório
Experiência em desenvolvimento de software, focado em Android;
Experiência ou conhecimento teórico de metodologias ágeis (XP e Scrum);
Apps publicados são considerados diferenciais para o candidato;
Sólida experiência com SDK Android;
Experiência com consumo de dados via REST e padrão JSON;
Conhecimentos gerais do ambiente mobile, como arquiteturas, padrões, tendências e tecnologias emergentes.

Contratação

CLT

Studo+

Quem somos
Somos uma startup que busca a melhoria do aprendizado na educação básica. Nosso foco é entender a dinâmica do aprendizado dos alunos, dentro e fora da sala de aula, e propor ações que os levem a maximizar seu potencial.

O que fazemos
Desenvolvemos uma plataforma de gestão e interação educacional para compreender e apoiar o aprendizado, valorizando todos os atores envolvidos no processo.

Como se candidatar

Por favor envie um email para thiagonetorh@gmail.com com seu CV anexado - enviar no assunto: "Tech Lead Android"

**Comment by walmyrcarvalho** [comment]
@thiagonetorh Essa vaga é igual essa? https://github.com/androiddevbr/vagas/issues/133

Se sim, peço que evite abrir vagas antes de fechar antigas.
