### ISSUE TITLE
[Remoto] Desenvolvedor IOS Sênior na Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [androiddevbr/vagas#1661]
**Descrição da vaga**
Estamos procurando pessoas que tenha uma vasta experiência em desenvolvimento.

**Local**
Remoto

**Requisitos obrigatórios:**
•	Desenvolvimento IOS com Objective-C e Swift
•	Consumo de serviços no padrão RESTful
•	Recursos nativos de arquitetura do sistema operacional como: fila, sincronização, etc
•	Publicação de apps para na Apple Store
•	SQLite / MongoDB

**Conhecimento intermediários:** 
•	Implementação de código utilizando SDKs
•	Computação em Nuvem (AWS/Azure/Google)
•	Experiência em desenvolvimento Java ou .NET
•	Desenvolvimento WEB com HTML, CSS e JavaScript

**Conhecimentos Básicos:** 
•	CX, UX, UI

**Labels**
•	Alocado
•	PJ
•	Sênior

**Como se candidatar**
Envie seu currículo https://bit.ly/2Wu2JH0
Envie seu currículo: simone.santos@pasqualisolution.com.br

**Nossa empresa**
A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Comment by khalilayache** [comment]
@Recrutas Esse repositório só aceita vagas relacionadas a Android. Por esse motivo a issue será fechada.
