### ISSUE TITLE
[Remoto] Senior Android Developer na SevenApps

### ISSUE THREAD

**Issue by raquelsevenapps** [androiddevbr/vagas#1662]
## Descrição da vaga

Está em busca de novos desafios?! E se você pudesse atuar em um projeto internacional incrível, e ainda receber todo o suporte de colegas brasileiros de alta performance? 

Na Seven, você vai estar próximo das melhores tecnologias do mercado, trabalhar em projetos desafiadores e em um ambiente rico em aprendizado. Estamos procurando devs proativos, experientes e que estejam em busca de vivenciar essa imersão na cultura do mercado norte-americano. 

Nessa posição, você atuará alocado em uma empresa da Flórida de grande porte, e terá autonomia e liberdade para trabalhar 100% remoto, com flexibilidade de horário.  Os seus desafios irão envolver o desenvolvimento e evolução dos sistemas Mobile da empresa; Você terá um time altamente capacitado para implementar essas soluções com você. 

Nós acreditamos que a Tecnologia tem o poder de transformar o mundo e melhorar a maneira como vivemos e enfrentamos os desafios. Se você também acredita nisso, vem fazer parte do nosso time!

## Local

100% Remoto 

## Benefícios

- **Revisão salarial:** revisão a cada 6 meses;
- **15 Dias Livre:** férias remuneradas por 15 dias ao ano;
- **Horário Flexível:** trabalhe no horário que se sentir mais produtivo 
- **Workshop quinzenal:** aprendizados e trocas expositivas com outros Seven Coders
- **Acompanhamento semanal:** reuniões semanais com todo o time gerando um ecossistema de conhecimento e troca mútua entre os profissionais;
- **Imersão Internacional:** cultura internacional com projetos fora do Brasil;
- **Bônus por indicação:** nos ajude a trazer os melhores devs para nosso time 

## Requisitos

- 4+ anos de experiência com Android;
- Experiência com desenvolvimento Kotlin;
- Forte conhecimento do Android SDK, diferentes versões do Android e como lidar com diferentes tamanhos de tela;
- Familiaridade com APIs RESTful para conectar aplicativos Android a serviços de back-end;
- Forte conhecimento dos princípios, padrões e práticas recomendadas de design de IU do Android;
- Experiência com armazenamento offline, threading e ajuste de desempenho;
- Capacidade de projetar aplicativos em torno de interfaces de usuário naturais, como “touch”;
- Familiaridade com o uso de sensores adicionais, como giroscópios e acelerômetros;
- Familiaridade com APIs de mensagens em nuvem e notificações push;
- Compreensão dos princípios de design do Android do Google e diretrizes de interface;
- Compreensão proficiente de ferramentas de controle de versão de código, como Git;
- Experiência com programação reativa, seus padrões e melhores práticas.
- Um talento especial para benchmarking e otimização;
- Familiaridade com integração contínua;
- Inglês avançado

## Contratação

PJ a combinar

## Nossa empresa

Somos mais que uma empresa, somos um estilo de vida baseado na paixão em solucionar problemas usando design, usabilidade e tecnologia. Nosso propósito é unir os melhores profissionais do mercado em projetos nacionais e internacionais com um crescimento de carreira e troca interna de alta velocidade. Nosso time aprende, evolui e compartilha. 

Com um escritório administrativo em Belo Horizonte e uma sede em Miami, já crescemos mais de 300% no último ano e ajudamos nossos clientes a crescerem mais de 120% com alocação dos nossos profissionais sênior e/ou desenvolvimento de aplicativos e softwares de alta performance.

## Como se candidatar

Por favor envie um email para sabrina.fantoni@sevenapps.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by raquelsevenapps** [comment]
Prezados, gostaria de saber como adcionar Labels no link da vaga?

**Comment by davidtcdeveloper** [comment]
@raquelsevenapps As labels são adicionadas pela nossa equipe de moderação. Acabei de adicionar conforme a descrição, se houver outras labels para adicionar por favor avise.

**Comment by raquelsevenapps** [comment]
Ah sim, muito obrigada pelo retorno David. Se puder adicionar então as labels Internacional e Alocação, por favor.

**Comment by raquelsevenapps** [comment]
@davidtcdeveloper Gostaria de encerrar essa vaga aqui, pois ela já foi preenchida. Como funciona?

**Comment by davidtcdeveloper** [comment]
@raquelsevenapps Obrigado pelo feedback. Ao comentar na issue você pode usar a opção de fechar. Farei o fechamento por aqui, novas issues você mesmo pode fechar.
