### ISSUE TITLE
Desenvolvedor Android Remoto

### ISSUE THREAD

**Issue by FerCaponi** [androiddevbr/vagas#1667]
Ola,
Espero que esteja bem.
Estamos com uma oportunidade para trabalhar como Desenvolvedor Android em uma empresa de grande porte (Remoto) 
Contratação: PJ ou CLT

Você tem interesse? 
Encaminhe CV atualizado para fernanda.caponi@am53rh.com.br

Necessário Experiência com:
Experiência com aplicativos em Android nativo.
• Experiência em Android Support Library e Material Design.
• Experiência com diferentes dimensões de dispositivos (tablet, celular e correlatos).
• Experiência com GIT.
• Experiência com a realização de testes, code review, integração contínua, entre outros.
• Experiência com a linguagem Java.
• Conhecimento em Google Play Services.
• Experiência com API level 14.
• Conhecimento de padrões de arquitetura MVP e MVVM.

**Comment by davidtcdeveloper** [comment]
@FerCaponi Conforme as regras do nosso mural de vagas, é obrigatória a divulgação da empresa contratante. A issue será encerrada até que seja editada com o nome da empresa.
