### ISSUE TITLE
[Remoto] Desenvolvedor (a) Mobile Flutter

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [androiddevbr/vagas#1673]
## Descrição da vaga 
**Aceitamos candidatos de todo o Brasil.**
------------------------------------------

  

**Conhecimentos Técnicos - Desejáveis:**

*   Git Flow;
*   Flutter;
*   Microservices;
*   Design de soluções;
*   Segurança de APIs.

  

**Atribuições:**

*   Participação em projetos de desenvolvimento de aplicações para mercado financeiro;
*   Design das soluções;
*   Publicações nas lojas.

**Requisitos:**

*   Experiência de no mínimo 2 anos nas atribuições;
*   Comprometimento com os prazos acordados;
*   Comprometimento com a qualidade do produto final;
*   Pró-atividade.
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor (a) Mobile Flutter](https://vaga.contratar.dev/apply/full/fb8d58fb-4e11-473d-a9a9-cc6d3b3e77fd) para se candidatar. 
## Labels 
* Remoto 
* Flutter 
* Git 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by davidtcdeveloper** [comment]
@NerdProgramador-com-br Conforme regras do nosso mural de vagas, é obrigatório a divulgação da empresa contratante. Esta issue será encerrada até que o nome da empresa seja informado.
Este é o terceiro aviso sobre issues abertas incorretas, em caso de nova incidência o acesso ao mural será bloqueado.

**Comment by jpventura** [comment]
@NerdProgramador-com-br Samuel, este foi o *último* aviso. Já é quinta vez que viola os termos da comunidade:
  
  1. Issue #1673
  2. Issue #1552
  3. Issue #1551
  4. Issue #1543
  5. Issue #1503
