### ISSUE TITLE
[Uberlândia] Android Developer no Social Bank

### ISSUE THREAD

**Issue by ericferreira1992** [androiddevbr/vagas#1674]
### O que é o Social Bank? 🤔
**O[ Social Bank](https://socialbank.com.br) é um banco digital cujo propósito é ressignificar os valores da sociedade.**
Buscamos tornar o mundo mais justo, ético, transparente e com oportunidades para todos. Nossos produtos são importantes agentes de inclusão financeira, social e digital, ajudando as pessoas a terem uma melhor relação com o dinheiro, transformando suas formas de pensar, de consumir e, consequentemente, gerando relações mais saudáveis e humanas.

### A vaga é para aonde? 📱
Full Remoto **ou** Presencial em Uberlândia (CLT)

### Pra qual nível ténico? 😬
Estamos sempre em busca dos melhores, mas sabemos existem talentos que ainda precisam ser lapidados, então estamos em busca desde os *juniors* até os *sêniors*.

### Quanto o **Social Bank** paga? 💸
Vai depender do seu nível técnico, mas também de como você é. Se você mandar bem no Android mas também for uma pessoa que seja aderente aos propósitos do Social Bank, o céu é o limite para gente!

### Como me candidato? 🤓
Temos um portal na Gupy para se candidatar pra vaga: https://socialbank.gupy.io/jobs/904209.
Qualquer coisa pode nos chamar no Whatsapp
 📞   [(37) 9 8813-4410](https://web.whatsapp.com/send?1=pt_br&phone=5537988134410)

**Comment by gusoliveira21** [comment]
vaga finalizada
