### ISSUE TITLE
[Remoto]Desenvolvedor Android na Iventis 

### ISSUE THREAD

**Issue by cimerio** [androiddevbr/vagas#1682]
Desenvolvedor Android - Vaga 100% Remoto- PJ
CV para recrutamento@iventis.com.br
Sólidos conhecimentos na plataforma Android e Kotlin.
Boa compreensão de MVVM, padrões de projeto e Clean code.
Experiência em desenvolver, testar, lançar e manter aplicações Android nativas.
Experiência com bibliotecas do Android Jetpack

**Comment by davidtcdeveloper** [comment]
@cimerio Recomendamos seguir o template de criação de novas vagas para que seja possível adicionar labes.
