### ISSUE TITLE
[Remoto] - Android Developer na [PicPay]

### ISSUE THREAD

**Issue by LudmilaBergamini** [androiddevbr/vagas#1688]
O PicPay é uma plataforma de pagamento criada para quebrar barreiras e eliminar burocracias. Nós existimos para melhorar a vida das pessoas e só conseguimos fazer isso porque temos pessoas fantásticas aqui dentro. O que você vai fazer por aqui? Buscamos pessoas que sejam apaixonadas por construir aplicações distribuídas e de alta performance, escaláveis para milhões de novos usuários em todo o mundo e que suportem a melhor experiência de pagamentos.

_Obs: Temos vaga de nível júnior, pleno e sênior._

Manda bem nos requisitos abaixo? Então essa vaga é pra você! :)

**RESPONSABILIDADES E ATRIBUIÇÕES**

- Desenvolver soluções escaláveis e que irão ser utilizadas por milhões de usuários;
- Apresentar melhorias nos sistemas existentes e garantir a qualidade nas entregas;
- Ter autonomia no desenvolvimento e manutenção dos sistemas.

**REQUISITOS E QUALIFICAÇÕES**

Precisamos que você tenha experiência com:

- Desenvolvimento de aplicativos nativos Android (Kotlin/Java);
- Android SDK (Lifecycle, Service, ContentProvider, Broadcast etc);
- Arquitetura de software, princípios SOLID e padrões de projeto;
- Ferramentas de versionamento de código e desenvolvimento colaborativo;
- Consumo de APIs RESTful;
- Testes unitários e instrumentados;
- CI e CD;
- Android Jetpack Components (ViewModel, Room, LiveData, Databinding, Navigation);
- Conhecimento em UI customizada;
- Metodologias ágeis.

Será um diferencial se você tiver atuado com:

Gerenciamento de memória e ajustes de desempenho do App;
Modularização de aplicações;
Ferramentas de minificação e ofuscação de código;
Processo de build (gradle, tasks).
VAMOS ALÉM E VOCÊ PODE FAZER PARTE DISSO! 🚀
Fazer todos os seus pagamentos de forma simples e rápida. Na nossa plataforma PicPay dá para enviar e receber dinheiro, fazer um Pix, pagar boletos, estabelecimentos, comprar crédito para o celular, para games online e muito mais. Tudo isso direto do celular.

Nos últimos anos, o PicPay conquistou milhões de usuários e busca diariamente tornar a vida das pessoas mais fácil.

Contamos com um time de pessoas fantásticas e que amam o que fazem, somos #PicPayLovers.

O que você acha de:

Participar de projetos com times multidisciplinares e inovadores;
Aprender e se reinventar a todo instante para atender a necessidade do mundo atual;
Ter uma liderança inspiradora e que trabalha junto;
Liberdade para criar e fazer acontecer.

AQUI NO PICPAY VOCÊ PODE VIVER ESSES DESAFIOS!

Nosso pacote de benefícios possui:

- Assistências médica (você e +1 dependente ficam por nossa conta!);
- Assistência odontológica;
- Seguro de vida;
- Vale Transporte e/ou Auxílio combustível;
- Vale Refeição e/ou Vale Alimentação;
- Gympass;
- PicPay Acolhe - Programa que cuida da gente e dos nossos familiares, oferecendo apoio jurídico, social, psicológico e financeiro;
- PPR - Participação nos Resultados do PicPay;
- Horário flexível e possibilidade de home office.

Curtiu? Basta se inscrever em uma das vagas correspondentes nos links abaixo:

https://picpay.gupy.io/jobs/867353
https://picpay.gupy.io/jobs/1006758
https://picpay.gupy.io/jobs/1006767
https://picpay.gupy.io/jobs/983857
https://picpay.gupy.io/jobs/931078
https://picpay.gupy.io/jobs/1013029

QUER CONHECER QUEM SÃO E O DIA A DIA DOS NOSSOS PP LOVERS?

Acesse picpaylovers.gupy.io/ 💚

**Comment by gusoliveira21** [comment]
Nenhum dos links encontra-se em funcionamento!

**Comment by giovanninibarbosa** [comment]
@davidtcdeveloper creio que esta vaga foi finalizada
