### ISSUE TITLE
[São Paulo/SP] Desenvolvedor Android | Qiwi Brasil

### ISSUE THREAD

**Issue by AndreRicarti** [androiddevbr/vagas#169]
## Descrição da vaga

Procuramos um desenvolvedor Android para o desenvolvimento de um novo aplicativo junto com nossa equipe.

## Posição
Pleno/Sênior

## Local

Escritório no Metrô Consolação - São Paulo

## Benefícios

* Vale Refeição
* Vale Transporte
* Convênio Odontológico
* Convênio Medico

## Requisitos

* Android Studio 
* TDD
* Material Design
* Banco de Dados Relacional/Não Relacional
* Ferramenta De Versionamento 
* Fortes Conceitos de Orientação Objeto
* Aplicativo Publicado Na Loja
* Experiência com consumo de dados via REST e padrão JSON
* Experiência com gerenciador de dependência/Gradle

## Contratação

Presencial, CLT, PJ.

## Nossa empresa

A QIWI é uma rede de serviços inovadora com o objetivo de ajudar consumidores e empresas a se conectarem com praticidade através de terminais de autoatendimento. Aqui você encontra: recarga de bilhetes de transporte, recarga de jogos e de telefonia, consulta de situação fiscal e consulta de crédito, doações, compra de ingressos, pagamento de contas e outras facilidades em mais de 170 mil pontos no mundo todo.

## Como se candidatar

Por favor envie um email para raquel@qiwi.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by Son182** [comment]
Pode fechar essa vaga. Obrigado!
