### ISSUE TITLE
[Remota] IOS Software Developer [Compasso UOL]

### ISSUE THREAD

**Issue by Jacke17** [androiddevbr/vagas#1690]
Se candidate aqui --> https://compasso.gupy.io/jobs/865289

Somos a Compasso UOL. Ajudamos nossos clientes a elevarem seu potencial com soluções de tecnologia pensadas sob medida. 

Contamos com mais de 2.000 profissionais de diferentes vivências que compartilham suas paixões e habilidades para alcançar os melhores resultados ao lado dos nossos clientes. Juntos, construímos histórias incríveis.

**Requisitos e qualificações:** 

- Swift 4.0+;
- Habilidades na construção de aplicações escaláveis, de alto desempenho e tolerantes a falhas;
- Interfaces utilizando autolayout e storyboards, xib e viewcode;
- Boas práticas de programação como S.O.L.I.D, KISS, DRY ;
- Rest API utilizando protocolo codable;
- Gerenciador de dependência como: Cocoapods, Carthage ou SPM;
- Git usando desenvolvimento: trunk based ou gitflow;
- Fluxo de PR/CodeReview;
- MVC, MVP, MVVM, VIPER, Clean Swift;
- Testes automatizados: XCTest, Quick/Nimble, KIF;
- UX para apps móveis.

**Diferenciais:**

- Programação Reativa com RxSwift;
- Interesse pelo segmento mobile (trends, growth hacking...);
- Conhecimento de ferramentas para monitoramento de apps como Firebase, Analytics, Sentry;
- Experiência no processo de publicação de AppStore;
- Ferramentas de Continuous Integration como: Fastlane, Bitrise, CircleCI, etc...;
- Modularização.

Não possui todos os requisitos para a vaga?

Não tem problema! Aqui na Compasso UOL estimulamos continuamente o desenvolvimento do nosso time!

Informações adicionais: 

Aqui na Compasso UOL acreditamos nas pessoas e no seu potencial de transformação. Acreditamos que as pessoas são a chave, e por isso, prezamos pelo respeito e valorizamos a diversidade em nossos times.

**O que você vai encontrar por aqui:**

• Cultura colaborativa, com forte senso de cooperação e união entre todos; 

• Respeito à singularidade de cada indivíduo;

• Compartilhamento de experiências e conhecimentos entre as áreas;

• Incentivo à inovação;

• Horizontalidade e dinamismo;

• Trilhas de capacitação para aprendizado de novas tecnologias e métodos;

• Convênio para pós graduação com instituição parceira;

• Delivery Centers espalhados por diversas cidades do país, que operam como uma referência da nossa cultura e como ponto de apoio para todos os nossos profissionais;

• Politica de Home Office;

• No dress-code;

• Outros benefícios contratuais.

**Responsabilidades e atribuições:** 

- Compreender problemas técnicos e desenvolver soluções Mobile Nativa focado em aplicações IOS;
- Concepção, desenvolvimento, implantação e manutenção de aplicações IOS;
- Realizar integrações com serviços de terceiros;
- Habilidade de aplicar os padrões de desenvolvimento IOS nativo;
- Colaborar com os testes e feedbacks dos usuários do aplicativo.

**Comment by davidtcdeveloper** [comment]
@Jacke17 Este mural de vagas é focado em oportunidades para Android, por isso a issue será removida.
