### ISSUE TITLE
Desenvolvedor Android Pl e Sr com possibilidade de 100%remoto.

### ISSUE THREAD

**Issue by 0073010** [androiddevbr/vagas#1692]
**Empresa:** Confidencial.
**Salário:** Varia de acordo com a experiência e pretensão.
**Tipo de contratação:** PJ
**Cargo:** Desenvolvedor Android Pl e Sr.
**Local:** São Paulo - SP 
**Horário:** 3 dias de Home Office pós
pandemia ou 100% remoto se o profissional não for de São Paulo.
 

Requisitos:
Pré-requisitos: Superior completo ou em andamento em Ciência da Computação, Engenharia, Sistemas da Informação ou áreas correlatas;
Experiência profissional no desenvolvimento e publicação de aplicativos em Android nativo;
Trabalhar com diferentes dimensões de dispositivos (tablet, celular e afins);
Experiência em controle de versionamento de códigos (Git);
Conhecimentos de testes unitários e funcionais usando Junit;
Android Support Library;
Inglês técnico avançado para leitura.
Desejáveis: Experiência profissional com metodologias ágeis (Scrum e/ou Kanban); Jenkins;
Conhecimento em Kotlin; Material design; Conhecimento de ferramentas de medição de crash,
audiência e uso de recursos de servidores.

Enviar currículo atualizado + pretensão salaria para camila.cristina@projeto22.com.br com o título: Engenheiro Android + a sua senioridade. 

At.te,

Camila Santos

**Comment by jpventura** [comment]
@0073010 é obrigatório informar o nome da empresa, do contrário infelizmente removeremos a vaga.
