### ISSUE TITLE
[Remoto] Android Developer Sênior na [R4S]

### ISSUE THREAD

**Issue by GiovanniCustodio10** [androiddevbr/vagas#1697]
A R4S é uma empresa de recrutamento especializado focado em posições sêniores de TI. Estamos recrutando para uma empresa (confidencial) em ampla expansão e líder no segmento em que atua. 

## Descrição da vaga

Principais atividades:
- Implementar técnicas de desenvolvimento visando a evolução constante das nossas aplicações;
- Contribuir com a melhoria contínua da experiência entregue no aplicativo Android para os nossos clientes;
- Trabalhar em um time multidisciplinar se integrando e participando das discussões técnicas para resolução de problemas.

Requisitos:
- Tenha conhecimentos sólidos em Java e Kotlin;
- Já tenha atuado em times multidisciplinares;
- Conhecimentos sólidos em UI/UX;

## Local

100% remoto ou presencial em São Paulo (como o colaborador preferir)

## Benefícios

- VT ou estacionamento - para quem estiver presencial
- Se for 100% home office - ajuda de custo mensal 100,00
- VR e/ou VA - 32,20 por dia
- plano de saúde - amil one (100% custeado pela empresa para colaborador - se quiser incluir dependente é pago à parte)
- plano odonto metlife
- convênio farmácia - Drogaria São Paulo
- Day Off de aniversário
- Cupom de desconto para compras dos produtos internos
- Seguro de vida

## Contratação

CLT

## Nossa empresa

Se você é uma pessoa inquieta e curiosa, apaixonada por inovação e tecnologia; se você sempre busca soluções criativas e novas perspectivas e acredita que trabalhar em equipe, com transparência é a chave para o sucesso, vem escrever essa história com a gente e fazer parte do nosso time de talentos.

## Como se candidatar

Por favor envie um email para giovanni.custodio@r4s.com.br com seu CV anexado - enviar no assunto: Vaga Android ou me contate pelo Linkedin: https://www.linkedin.com/in/giovanni-custodio/

**Comment by davidtcdeveloper** [comment]
@GiovanniCustodio10 As regras do nosso mural de vagas exigem a divulgação do nome da empresa contratante. Estamos encerrando a issue até que o nome seja divulgado.
