### ISSUE TITLE
[REMOTO] Desenvolvedor Android na Capgemini

### ISSUE THREAD

**Issue by rsafira** [androiddevbr/vagas#1699]
Que tal trabalhar com em uma empresa que está transformando todos os modelos de prestação de serviço?

Somos guiados por sete valores principais: honestidade, audácia, confiança, liberdade, espírito de equipe, modéstia e fun. Se você compartilha dos mesmos valores, aqui é o seu lugar. 

**O que esperamos de você:** 

- Ser capaz de criar soluções de software, onde os recursos são rapidamente entregues sem sacrificar a qualidade do código;
- Concepção, desenvolvimento, implantação e manutenção de aplicações Android;
- Domínio e experiência em desenvolvimento mobile Android
- Desenvolver criativas soluções de frontend para atender as necessidades e experiência de usuário;
- Necessário conhecimentos em Clean Architecture e MVVM LiveData RxJava e Coroutines;
- Necessário sólida experiência com Jetpack Gradle e Kotlin;
- Noções de Clean Code e SOLID;
- Desejável experiência com CI CD de preferência Githu Actions.

**O que podemos te oferecer:** 

Contratação: CLT  

_Benefícios: Assistência Médica, Assistência Odontológica, Vale Refeição, Seguro de Vida, Previdência Privada, Plataforma de curso de Inglês, Gympass_, Parceria com Pluralsight e Coursera, 2 anos de gratuidade Veloe, Clube de benefícios e _Universidade Corporativa._ 

A Capgemini se orgulha da sua diversidade e está empenhada em promover um ambiente inclusivo e com igualdade de oportunidades. Todas as nossas vagas abertas também são para profissionais com deficiência. 

**Candidate-se através do link:** https://www.linkedin.com/jobs/view/2645776904

**Comment by gusoliveira21** [comment]
O link não aceita mais candidaturas
