### ISSUE TITLE
[São Paulo] Desenvolvedor Android Pleno | Evino

### ISSUE THREAD

**Issue by mauriciojt** [androiddevbr/vagas#17]
## Descrição da vaga

O que a vaga é
- Para famintos por aprender novas ferramentas, tendências e tecnologias. Por exemplo, nosso dev de iOS está quebrando a cabeça para aprender como se usa o novo Universal Links do adjust!
- Engajante para quem quer resolver problemas e trabalhar em melhoria contínua. Você não irá entregar um projeto e partir para outro completamente novo. Para sermos a melhor experiência de venda de vinho pelo mobile, o app exigirá melhorias, iterações e correções constantes
- Para pessoas resilientes e adaptáveis. Mudança de foco, de estratégia e repriorizações fazem parte do nosso dia-a-dia
- Oportunidade para trabalhar em um ambiente de start-up, onde você terá contato com os CEOs e liberdade para opinar e influenciar com design, features e usabilidade. Quer oportunidade melhor para treinar seus skills de negócios?  

O que a vaga NÃO é
- Um projeto de escopo fechado, desses que faz com que o desenvolvedor se tranque num quarto, fique sem ver o sol por 4 meses e viva a base de refrigerante e salgadinho
- Para desenvolvedor full-stack que "quebra o galho" com Android. Pelo contrário, precisamos de alguém especializado em Android e mobile.

Key Responsibilities
- Ser o responsável pelo aspecto técnico do app
- Entender as necessidades do app e trabalhar junto com o product manager para criar e priorizar as tarefas
- Estimar complexidade, esforço e tempo para desenvolvimento de forma precisa, sendo peça chave para um bom planejamento
- Pesquisar novas tecnologias e soluções que sejam relevantes para o app
- Orientar de forma clara e precisa o time de desenvolvimento de back-end a respeito das necessidades e forma de trabalhar do app
## Local

Escritório São Paulo - Vila Mariana
## Benefícios
- Estacionamento
- O de sempre (VR, VT, convênios médico / odonto)
- Vinhos com descontos sensacionais
- Oportunidade para aprender mais sobre o mundo dos vinhos (afinal, dev tambem é chique se quiser ser)
- Excelente localização do escritório (Sério! Entre 7-10 minutos do metrô Paraíso)
## Requisitos

Obrigatórios
- Android SDK é seu melhor amigo
- Experiência com framework de testes
- Boas práticas de desenvolvimento são imprescindíveis para vaga
- Conhecer Design Patterns também é importante
- Ter criado apps consumindo APIs RESTFul é essencial

Desejáveis
- Experiência com metodologias ágeis (trabalhamos com Scrum na Evino)
- Se programou Java antes de partir para a SDK do Android você já tem um diferencial
- NoSQL é um plus
## Contratação

CLT
## Nossa empresa

Estamos em busca de um desenvolvedor Android que seja apaixonado pela idéia de democratizar o vinho no Brasil. Com o objetivo de tornar os vinhos mais acessíveis aos brasileiros, a Evino já oferece aos clientes a possibilidade de comprar pelo site e pelo aplicativo iOS. Agora é o momento de oferecer esta oportunidade aos clientes usuários de Android!  
## Como se candidatar

Por favor envie um email para mauricio@evino.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@mauriciojt Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by mauriciojt** [comment]
Ainda está aberta sim. Obrigado!

**Comment by walmyrcarvalho** [comment]
@mauriciojt Beleza! 👍

**Comment by walmyrcarvalho** [comment]
@mauriciojt Estou fechando essa vaga por falta de resposta, caso ainda esteja aberta me avise! :)
