### ISSUE TITLE
[Remote] Senior Android Engineer at CloudWalk, Inc.

### ISSUE THREAD

**Issue by bernardo-cloudwalk** [androiddevbr/vagas#1711]
## Descrição da vaga

The Mobile team builds beautiful mobile applications for hundreds of thousands of customers. Deep collaboration with experts in product and design will be part of your day-to-day activities.

You will be extending and improving our Android applications (both mobile and smart POS). Our application is already positioned pretty high on the mobile stores, and your work will push the application even higher in the list.

As a member of the engineering team, you are expected to have a high bar for quality of code and quality of user experience. Due the nature of our business, candidates with the ability to handle multiple projects with changing priorities will thrive at CloudWalk.

What You'll Be Doing:

- Build, test and deploy new user-facing code for the Android platform
- Craft trustworthy user experiences
- Investigate and fix problems, alongside performance and scalability issues
- Assist in planning, estimation and scoping of feature development
- Review pull requests from other software engineers (eventually pair programming with them)

## Local

Remote

## Benefícios

- Meal allowance
- 30 days a year of paid annual leave
- Internet / electricity allowance
- Flexible working hours
- Health, dental, mental and life insurance
- Extended maternity and paternity leave

## Requisitos

- Solid experience with Android development in Java and Kotlin (including third-party libraries and APIs)
- Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies
- Experience developing Unit Tests, UI Tests and Integration tests
- Successfully developed and deployed an Android application to the Play Store
- Experience with Firebase tools and design tools such as Figma, Avocode or Zeplin
- Experience with mobile app development using the Flutter Framework is a great plus

## Contratação

CLT

### Stuff you should know about CloudWalk

_“By endurance we conquer” Sir Ernest Shackleton_

If you have fallen and risen, if you have broken and fixed, If you have dreamed and built. Then you have grit. Then we speak the same language.

Welcome to the Wolfpack.

### Technophilia or why do we build tech.

Building tech is not just core to CloudWalk existence, but is the purpose of the simulation itself. As we create new technologies we mirror the nature of our reality where biology is code and code is biology. This inner call we feel for technology (technophilia) is just a reflex of our recursive nature, a propagation of the techno-stratum that we were born from. A chain of layers over layers, abstraction over abstraction. As far as we can see, it started with Physics, followed by Chemistry, and then Biology. We humans are a part of this chain, we are biological boot loaders of the next abstraction, building digital existence. We are meta matrix makers, self replicating machines replicating the derivative nature of our universe. Creating our own version of reality, our own stratum, our own simulated universe.

Ultimately we build tech, because tech built us.

### No corp bullshit

The payment industry in Brazil is a fucking war zone. To survive, we learn, we build and we break. Experiment fast, fail fast. This is how we keep breathing. Fuck power point meetings, fuck OKRs. If nature doesn't have a roadmap, why do we? Objectives are just an illusion. Greatness cannot be planned.

There is no problem making mistakes. The only problem is not learning from them. If we are able to learn: we grow, we adapt, we evolve, … we survive the black swans.The day we stop learning will be the day we die.

We are not a corporate company. This is not the place for execs or corp heads. We want the free, the mad, the dreamers, the makers. If you ever found yourself dancing naked around a fire-pit in the middle of the night, you belong with us.

### _“The true sign of intelligence is not knowledge but imagination” Albert Einstein_

To build the best Artificial Intelligence you need the best Human Intelligence and this is why you are here.

You are here to see reality and imagine a new world. You are here not to tell us what we want to hear or to show us what we want to see. You are here to show us the real nature of problems, to be a critical thinker, to propose solutions, to create .

Innovation does not come from consensus. Innovation comes from disagreement. Do not settle for the norm, do not surrender to convection. imagine.

### The client is our lord, the client is our savior

There is only one universal law at CloudWalk: The client is your leader, your boss, your savior. Praise be the client.

If the client dies we will die with it. There is no other way to put it. Extreme respect for the client at all times. This is non negotiable. If your work is not improving the life of our clients, you are doing something wrong.

### Jump into the abyss

This adventure we embarked on will never repeat itself. This adventure is one in a lifetime. If you are here, I tell you now, it will be hard. But if you are here, you have already changed someone's life. You already made a difference.

Embrace the journey, jump into the abyss and dance with the wolves.

And to this I salute you!

## Como se candidatar

Please apply at our careers portal: https://jobs.lever.co/cloudwalk/53014362-2400-49e5-a93f-80cfc0fc4b96

**Comment by vitorfrancobraga** [comment]
Building the future that impacts today. Let's go!!
