### ISSUE TITLE
[Remoto] Android Developer na [Popcode]

### ISSUE THREAD

**Issue by giovanninibarbosa** [androiddevbr/vagas#1717]
# Informações importantes

A Popcode é uma startup brasileira criada para explorar um novo e eficaz canal de comunicação e espaço de mídia, através da criação de aplicativos personalizados para dispositivos iOS (iPhone, iPad e iPod Touch) e Android (smartphones e tablets).

Criamos aplicativos sob medida, moldando-o de acordo com suas necessidades e usando todos os recursos necessários do aparelho. Focados no desenvolvimento de aplicativos, com mais de 1 milhão de usuários ativos e com clientes do ramo financeiro. Fornecemos aplicativos para bancos, fintechs e empresas de cartão de crédito. Em 2019 crescemos cerca de 40% e em 2020 dobramos de tamanho.

## Descrição da vaga

Na posição de desenvolvedor(a) Mobile na Popcode você irá trabalhar em conjunto com o gerente de produto e com os profissionais de UI/UX com o objetivo de reproduzir experiências visuais encantadoras para nossos projetos.

O candidato que buscamos precisa entregar um trabalho com qualidade acima do padrão de mercado e estar sempre estudando e se atualizando em relação ao que há de mais novo em termos de ferramentas e processos.

Nessa posição você será responsável por toda a arquitetura, desenvolvimento, manutenção e planejamento da vida útil dos projetos Android. Poderá definir metodologias e tecnologias que desejar, entretanto deve garantir a operação e evolução constante dos projetos desenvolvidos.

## Posição

Desenvolvedores Android (Pleno e Sênior)

## Local

Remoto 

## Benefícios

- Vale alimentação/Refeição;
- Plano de Saúde e odontológico;
- Treinamento e desenvolvimento;
- Day Off – Birthday;
- Curso de Inglês (In Company);

## Requisitos

Obrigatórios
- Experiência em Desenvolvimento de Apps Nativos com Java e Kotlin
- Experiência com integração com APIs REST
- Controle de Versão com Git
- Boas práticas de UI/UX
- Ter trabalhado em algum aplicativo publicado em alguma loja.
- Noções básicas de testes automatizados;

Diferencias (não obrigatórios)
- Conhecimento com CI/CD;
- Ter participado de projetos com metodologia Ágil.

## Contratação

CLT OU PJ

## Como se candidatar

Você pode se candidatar através do e-mail: queroser@popcode.com.br, basta colocar no assunto do e-mail Dev Android, fechado?

**Comment by AnthoniIP** [comment]
Aqui tá dizendo que o email queroserpop@popcode.com.br não existe, poderiam verificar qual o email correto?

**Comment by giovanninibarbosa** [comment]
@AnthoniIP O email correto é queroser@popcode.com.br , acabei de corrigir! 🙂
