### ISSUE TITLE
wBrain - Vaga Dev Android - Remoto

### ISSUE THREAD

**Issue by monicamenezes** [androiddevbr/vagas#1718]
Requisitos
• Superior em Ciências da Computação, Engenharia, Sistemas da Informação ou áreas correlatas.
• Experiência com aplicativos em Android nativo.
• Experiência em Android Support Library e Material Design.
• Experiência com diferentes dimensões de dispositivos (tablet, celular e correlatos).
• Experiência com GIT.
• Experiência com a realização de testes, code review, integração contínua, entre outros.
• Experiência com a linguagem Java.
• Conhecimento em Google Play Services.
• Experiência com API level 14.
• Conhecimento de padrões de arquitetura MVP e MVVM.

Desejável
• Conhecimento em Jenkins, Bluetooth API, MVP, Mockito, powerMock, Android NDK, SonarQube, Cucumber, automação com Espresso, Kotlin e TDD.
• Experiência em desenvolvimento SOLID, KISS e DRY.
• Conhecimento com bibliotecas comuns ao desenvolvimento Android (Retrofit, Dagger etc.).
• Conhecimentos sobre o processo de distribuição do Google Play, Scrum e Kanban.

Principais atividades
• Trabalhar com BDD, TDD e pull request, promovendo um code review constante.
• Atuar em um time multidisciplinar.
• Trabalhar com o método de desenvolvimento incremental.
• Acompanhar as entregas avaliando o impacto que as mudanças ocasionam na relação com os clientes.

Ficou interessado ou tem indicações? 
Entre em contato no e-mail
📧 monica.menezes@workerbrain.com
CLT OU PJ

**Comment by davidtcdeveloper** [comment]
@monicamenezes As regras do nosso mural de vagas exigem a divulgação da empresa contratante. A issue será encerrada até que o nome da empresa seja divulgado.

**Comment by monicamenezes** [comment]
Feito
