### ISSUE TITLE
[São Paulo/SP] Desenvolvedor Android | KiiK

### ISSUE THREAD

**Issue by esdrasedu** [androiddevbr/vagas#172]
## Descrição da vaga

Vaga para desenvolvedor fullstack, com focu em android, Pleno

## Local

Rua Maranhão 600, Higienópolis, São Paulo - SP

## Benefícios

- CLT
- VR + VT
- plano de saúde
- plano odontológico
- ambiente descontraido (incubadora com outras startups)

## Requisitos

Obrigatórios
- 2+ anos de experiência com Android
- Fullstrack

Desejáveis
- Retrofit
- Elixir
- Ruby
- Ansible

Diferenciais
- Ter experiência em fintech 

## Contratação

CLT 4k - 5K

## Nossa empresa

O KiiK é uma Startup plaforma de pagamento, buscando sempre inovação e qualidade.

## Como se candidatar

Entro no nosso repo e faça nosso teste https://github.com/kiik-payments/jobs

**Comment by paulovitorns** [comment]
Olá, boa tarde.
Fiz o fork do teste da kiik para android, e verifiquei que o link da api não esta disponível.
A vaga ainda esta em aberto?

**Comment by esdrasedu** [comment]
Olá @paulovitorns , está sim!

Que a empresa mudou de marca, agora somos Paggi, e também lançamos uma nova versão da api (v4), no link docs.paggi.com

Mas se vc fez tudo no versão v3, tudo bem, pode fazer o PR q iremos analisar!

Abs

**Comment by rafaelcrz** [comment]
Olá @esdrasedu 
Como essa "issue" está em aberta, eu comecei a fazer o teste disponivel no Github. Porem a api(v4) não está respondendo alguns endpoints.

Obrigado,
Abs.

**Comment by rafaelcrz** [comment]
Olá @esdrasedu .
Eu gostaria de saber se a vaga ainda está aberta. Eu comecei a fazer o teste, se quando terminar posso te enviar.
Obrigado,
Abs

**Comment by esdrasedu** [comment]
Está sim @rafaelcrz, abs

**Comment by rafaelcrz** [comment]
Enviei um PR o/
Obrigado @esdrasedu
Abs
