### ISSUE TITLE
[REMOTO] Desenvolvedor Mobile na 5A Attiva

### ISSUE THREAD

**Issue by CarolinaRCerqueira** [androiddevbr/vagas#1730]
## Local

Vaga hibrida em SP pós pandemia, e se for de fora de São Paulo (outro estado) será 100% home office

## Requisitos

Experiência com aplicativos em Android nativo, Android Support Library; Trabalhar com diferentes dimensões de dispositivos (Tablet, celular e afins); Experiência com GIT; Trabalhar realizando testes, code review, integração continua e afins; BDD e TDD; Experiência com Java; Conhecimento com Google Play Services; API Level 14; Conhecimento de padrões de arquitetura: MVP, MVVM.

## Contratação

PJ 

## Nossa empresa

5A Attiva

## Como se candidatar

Por favor envie um email para carolina.cerqueira@5aattiva.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@CarolinaRCerqueira existem diversas issues abertas para vagas na 5A Attiva. Poderia confirmar se todas estão abertas e se tratam-se da mesma vaga?
https://github.com/androiddevbr/vagas/issues?q=is%3Aissue+is%3Aopen+5A+Attiva
