### ISSUE TITLE
[Porto Alegre/RS] Desenvolvedor Android Pleno ou Sênior

### ISSUE THREAD

**Issue by AndreCGusmao** [androiddevbr/vagas#174]
## Descrição da vaga

Auxiliar no desenvolvimento de um app para investimentos no mercado financeiro.
Alocação pontual pelo período de um mês, com possibilidade de prorrogar.

## Local

Presencial - Porto Alegre - RS

## Nossa empresa
Somos uma plataforma online de investimentos na qual os usuários investem com eficiência, simplicidade, custos baixos e com a ajuda de um mentor virtual.

## Como se candidatar

Por favor envie um email para andre.gusmao@gmail.com com seu CV anexado - enviar no assunto: Freela Android

**Comment by pedrofsn** [comment]
A vaga ainda está aberta @AndreCGusmao  ?
