### ISSUE TITLE
Dev Mobile Android

### ISSUE THREAD

**Issue by Daniellelinoo** [androiddevbr/vagas#1753]
⚠️ Vaga remota 
📍 São Paulo/SP  
Horário: 08 as 17hrs

🎯 Principais Atividades:
Implementar features nativas para o ramo financeiro de pagamentos;
Criar protótipos;
Testes de Unidade e Integração.

🎯 Requisitos:
Experiência em ANDROID
Conhecimentos em banco de dados nativos para cada tecnologia e Firebase;
API Rest e Restful 
Noções de UI/UX;
Noções de Cloud;

🖤 Gostou da vaga?  
🌐 Se aplique em: caroline.pistore@edesoft.com.br ou danielle.lino@edesoft.com.br

**Comment by davidtcdeveloper** [comment]
@Daniellelinoo As regras do nosso mural de vagas exigem a divulgação do nome da empresa contratante. A issue será encerrada até que seja editada com o nome da empresa.
