### ISSUE TITLE
[REMOTO] Desenvolvedor Android [PLENO] OXEANBITS

### ISSUE THREAD

**Issue by IngridCRodrigues** [androiddevbr/vagas#1755]
## Objetivo:

Como Dev Android você trabalhará desenvolvendo soluções tecnológicas que geram impacto e que trazem significado para a vida das pessoas. 

Trabalhará com projetos 100% internacionais

## Tecnologias:

- Kotlin;
- Flutter;
- Redux;
- Experiência em escrever testes TDD, JUnit, Roboeletric e Espresso;
- Padrão de projeto Scrum;
- Design Patterns;
- Experiência com GIT;
- Graphql;
- Experiência em bancos de dados SQL/ NoSQL;

## Requisitos:

- Formação em Computação ou Sistemas de Informação;
- Ter boa desenvoltura em Estruturas de Dados e Análise de Algoritmos;
- +1 de experiência na área mobile;
- Ter experiência com Java/Kotlin;
- Ter experiência com Android Studio;
- Experiência em escrever testes;
- Conhecimento em inglês;
- Organização e proatividade são fundamentais;

## Cargo:

Desenvolvedor Mobile Android Pleno

## Benefícios:

- Salário à combinar;
- Plano de Saúde;
- Horário flexível;
- Vale alimentação
- 100% Home Office
- Muito aprendizado e crescimento profissional;
- Participar da construção de novos produtos digitais;

**Comment by gusoliveira21** [comment]
Link para aplicar para a vaga?
