### ISSUE TITLE
Desenvolvedor Android

### ISSUE THREAD

**Issue by Sempreit1** [androiddevbr/vagas#1769]
Função e responsabilidades: Atuar no desenvolvimento de novas funcionalidades em um aplicativo Android, enfrentando desafios reais do negócio com o cliente e com o time. Codificar testes automatizados para garantia de qualidade dos entregáveis. Compartilhar conhecimento com as demais pessoas desenvolvedoras de forma a colaborar com a melhoria das habilidades de todos.

﻿Habilidades: Android nativo em Kotlin - Experiência com Testes Unitários - Experiência com MVP ou MVVM - Diferencial: conhecimentos sobre Clean Architecture - Injeção de dependências (preferencialmente com Koin) - Versionamento de projetos com GIT (GIT Flow é um Diferencial) - Familiaridade com métodos ágeis e trabalho com equipes multidisciplinares

Requisitos: desejável ensino superior cursando/completo em Análise de Sistemas/Ciências da Computação ou áreas correlatas.

http://www.sempreit.com.br/carreiras

**Comment by davidtcdeveloper** [comment]
@Sempreit1 As regras do nosso mural de vagas exigem a divulgação do nome da empresa contratante. Esta issue será encerrada até que seja editada com o nome da empresa.
