### ISSUE TITLE
[Portugal] IOS Developer na Multivision- Consulting 

### ISSUE THREAD

**Issue by msls19** [androiddevbr/vagas#1789]
We are a multidisciplinary team, specialized in providing consultancy services - Outsourcing, Time and Materials, Turnkey Projects - in the areas of Telecommunications and Information Technology, with more than 100 projects in the most diverse domains.

RESPONSIBILITIES:

- Developing and maintaining iOS applications from the requirements to the App Store.
- Producing clean and organized code, taking advantage of software design patterns, architectural patterns and data structures.
- Creating fluid visual interactions, creating and implementing mobile user experience patterns

COUNTRY:

Porto- Portugal

BENEFITS:

-Multicultural team
- International projects
- Health insurance and many other good things 🙂💪

REQUIREMENTS:

Mandatory-

- Fluency or good level of English (written and oral)
- Swift, Cocoa Touch and other Apple frameworks (Objective-C is fine too!)
- Being self-driven and working with little supervision towards a common team or company purpose
- Having a sense of craftsmanship in what you produce, seeking the best solutions and being proud of the final outcome
- Being a team player, sharing knowledge and leading by example
- Agile mindset and methodologies such as Scrum and Kanban.

Nice to have:

- Experience with FRP framework (ReactiveCocoa, RxSwift, etc)
- Experience with MVVM(-C) architecture
- Experience with Functional programming/concepts
- Experience with CI/CD development methodologies and tools (fastlane, Jenkins, Travis, GoCD, etc)
- Ability/experience testing code and/or writing testable code
- Open Source contributions and/or willingness to contribute

HIRING:

-Similar to CLT

OUR VALUES:

-Pro-activity
-Renewal
-Learning
-Responsability

APPLY:

Apply now by sending your CV to mariana.santos@multivision.pt - send in the subject: IOS opportunity

**Comment by khalilayache** [comment]
Segundo o nosso Código de Conduta, apenas são permitidas divulgação de vagas de Android. Por esse motivo a Vaga será fechada
