### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Android | SmartBeach

### ISSUE THREAD

**Issue by rodrigovsilva** [androiddevbr/vagas#18]
## Descrição da vaga

Estamos desenvolvendo um aplicativo que vai inovar o lifestyle do frequentador da praia....
## Local

Remoto ou Escritório Rio de Janeiro - Santa Teresa
## Benefícios

A combinar
## Requisitos

Obrigatórios
- Grande experiência com Android
- Confortável com utilização de API de Mapa do Google e de pagamentos Payleven, Parse, Firebase, etc 

Desejáveis
- Resida no Rio de Janeiro
- Amante da Praia
- Altamente motivado
## Contratação

A combinar
## Nossa empresa

Nossa empresa está desenvolvendo um projeto altamente inovador... E podemos dizer uma coisa.... A praia não será mais a mesma depois dele.... É um nicho de mercado em crescimento com bastante oportunidade. 
## Como se candidatar

Por favor envie um email para info@smartbeach.com.br com seu CV anexado - enviar no assunto: Oportunidade Android

**Comment by walmyrcarvalho** [comment]
Título atualizado para se adequar ao padrão descrito no README. :)

**Comment by walmyrcarvalho** [comment]
@rodrigovsilva Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by rodrigovsilva** [comment]
Opa Walmir, pode fechar a vaga.... Estamos passando por uma reestruturação.

Obrigado pela atenção.

-------------------------------------------------------
Rodrigo Vinicius Ferreira da Silva
E-mail: rodrigovfsilva@gmail.com
Celular: (21) 99868-5066
Skype: rodrigovfsilva
Linkedin: http://www.linkedin.com/in/rodrigovfsilva
-------------------------------------------------------

2016-07-28 11:53 GMT-03:00 Walmyr Carvalho <notifications@github.com>:

**Comment by walmyrcarvalho** [comment]
Fechada a pedido do owner da issue.
