### ISSUE TITLE
Nearsure - Desenvolvedor Mobile Senior

### ISSUE THREAD

**Issue by deboracdc** [androiddevbr/vagas#1813]
### **Quem somos nós?**

**Uma empresa em rápido crescimento com oportunidades incríveis!**
A Nearsure foi criada para ajudar empresas americanas a aumentar suas equipes de desenvolvimento de software de maneira eficiente. Devido ao nosso _mindset remote first_ nos conectamos com desenvolvedores de toda a América Latina, e assim temos a oportunidade de trabalhar com os melhores talentos em tecnologia, mantendo uma estrutura organizacional _lean_.

Nosso alcance abrange milhares de profissionais de TI, com habilidades em vários setores e tecnologias. Temos uma equipe totalmente distribuída trabalhando remotamente da Argentina, Bolívia, Colômbia, Equador, Honduras, Peru e Uruguai e queremos continuar expandindo por toda a América Latina!

**Descrição da Função**
Procuramos um Desenvolvedor Mobile com experiência em Objective-C baseado na América Latina com objetivo de resolver problemas complexos em um ambiente dinâmico. Você será referência de qualidade e eficiência, utilizando suas habilidades técnicas para inventar e simplificar como as coisas funcionam com diferentes tecnologias e garantindo que seu software atenda aos mais altos padrões. Trabalhando em estreita colaboração com os membros da equipe em um ambiente _Agile_, você será o responsável pela criação e migração do código __SaaS_._

**Responsabilidades**

- Compreensão de Design orientado a objetos, incluindo padrões de design
- Desenvolvimento e teste de aplicativos móveis usando o Xamarin Forms e o desenvolvimento nativo Xamarin como um grande plus
- Desejável conhecimento de framework C# e .NET
- Proficiente no desenvolvimento e consumo de APIs RESTful
- Experiência trabalhando em plataformas baseadas em nuvem, preferencialmente Microsoft Azure
- Forte experiência com Objective-C
- Experiência com tecnologias de banco de dados móvel como SQLite, Firebase, Realm, etc.
- Capacidade de teste de caixa branca básica (cobertura de múltiplas condições, caminho de base, loop)
- Proficiente na criação, teste e implantação de microsserviços
- Conhecimento prático de metodologia de ciclo de vida de desenvolvimento ágil de software, de preferência Kanban
- Experiência no uso de práticas de desenvolvimento ágil como TDD, BDD, programação em pares e compilações automatizadas

**O que nós oferecemos**

- _Remote work_, trabalhe de onde quiser.
- Horários de trabalho flexíveis.
- Participe de projetos desafiadores para empresas distribuídas nos Estados Unidos.
- Trabalhe em um ambiente amigável e multicultural.
- Faça parte de uma equipe em desenvolvimento com grandes oportunidades de crescimento profissional.
- Salário competitivo em dólares americanos.
- Um pacote de benefícios sob medida com foco em saúde, bem-estar, entretenimento, treinamento e finanças pessoais, disponível para você escolher o que realmente importa.

Somos uma start-up multicultural totalmente distribuída em busca dos melhores talentos da América Latina. Não hesite em se inscrever se achar que se encaixa bem nesta posição!

* Observação: esta oportunidade é para todos aqueles que tenham um nível avanzado de inglês *
*** Este é um cargo remoto de tempo integral com uma carga de trabalho de 40 horas por semana apenas para a América Latina.**
**Esta oportunidade é para trabalhar 100% remoto de qualquer parte da América Latina**

**Comment by khalilayache** [comment]
@deboracdc Olá Débora! Conforme nosso código de conduta do repositório é obrigatório conter no título da issue e nome da empresa que a pessoa vai ser contratada/trabalhar e a localidade. Pode, por favor, arrumar o mais rápido possível? Vamos deixar por dois dias e ai se não tiver sido alterado, fecharemos a issue.
