### ISSUE TITLE
[REMOTO] Desenvolvedor Android Sênior na @Zup Innovation

### ISSUE THREAD

**Issue by vgsants** [androiddevbr/vagas#1814]
## Descrição da vaga

Na missão de construir os produtos mais inovadores do mercado, você irá atuar desenvolvendo novas features e na sustentabilidade das aplicações.

## Local

Remoto 

## Benefícios

💰 - PLR (1,35 salário)
💊 - Plano de Saúde SulAmérica
🦷 - Plano Odontológico SulAmérica
🍝 - Flash VR / VA R $ 1.045,00
📚 - Capacitação anual (Ajuda de custo)
📱 - Plano de celular
🏡 - Auxílio Home Office
👶 - Creche Auxílio
⭐ - seguro de vida
💪 - Gympass
🖥️ Monte seu escritório (R $ 1.000 para você montar seu escritório do seu jeitinho)
💵 - Bônus por indicação
🏖️ - Liberdade para trabalhar de onde quiser
🍻 - Happy Hours e Confraternizações
🔀 - Trilha de Carreira em W
👨‍🦽 - Diversidade e Inclusão
✅ - Telavita (psicólogo online)

## Requisitos
Experiência com agilidade
Sólida experiência com a plataforma Android
Domínio de Design Patterns
Testes Unitários (JUnit, Mockito, Mockk, Robolectric)
Testes Instrumentados (UI Tests com Espresso)
Qualidade de Código com SonarQube / Fortify

Obrigatórios

- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis
Testes End-2-End (BDD)
Domínio de Kotlin / Swift
Experiência com Ofuscação de código em Android (Proguard, Dexguard)
Mirrors Maven (Artifactory, Nexus)

## Contratação

CLT

## Nossa empresa

Desenvolvemos uma stack de tecnologia para melhorar a experiência do desenvolvedor, facilitando e diminuindo o tempo entre a concepção de uma ideia e o código em produção. Trazendo ainda mais eficiência para profissionais de desenvolvimento e tempos de tecnologia.

## Como se candidatar

Se a posição fizer sentido pra ti, você pode me chamar no LinkedIn ( https://www.linkedin.com/in/vit%C3%B3ria-gomes-santos/ ) e vamos bater um papo! Ou você pode enviar seu CV para vitoria.santos@zup.com.br

![Apresentação sem título](https://user-images.githubusercontent.com/70250442/135137176-9113c41e-e2ec-428c-b82c-2b445ac15829.jpg)

**Comment by khalilayache** [comment]
Oi @vgsants segundo o nosso código de conduta é permitido a divulgação apenas uma única vez por vaga, por isso, pode checar essa lista (https://github.com/androiddevbr/vagas/issues?q=is%3Aissue+is%3Aopen+zup) e verificar a existencia de repetição, fechar e apenas deixar a última aberta, por favor? 

Caso nenhuma issue seja fechada até sexta, nós mesmos fecharemos todas e apenas deixaremos essa aberta ok?

**Comment by khalilayache** [comment]
Devido a falta de resposta do comentário acima as issues https://github.com/androiddevbr/vagas/issues/1785, https://github.com/androiddevbr/vagas/issues/1761 e https://github.com/androiddevbr/vagas/issues/1734 foram fechadas por duplicidade.
