### ISSUE TITLE
[Home Office] Desenvolvedor Mobile I no Inatel

### ISSUE THREAD

**Issue by lpliao** [androiddevbr/vagas#1829]
**Descrição da vaga**

O Inatel está recrutando Desenvolvedor para atuar no ICC Software Aplicativo.

**Responsabilidades:**

- Projetar e desenvolver aplicativos mobile (desenvolvimento focado, mas não limitado a plataforma Android), voltados a solução para IoT e para o mercado de distribuição de energia elétrica;
- Construir, treinar,  manter e evoluir aplicativos mobile, através das tecnologias utilizadas pelas equipes;
- Contribuir com a evolução tecnológica e de metodologias das equipes e do Inatel;
- Participar ativamente na concepção de novos produtos e soluções.

**Local**

Remoto

**Requisitos**

Obrigatórios:

- Ensino Superior Completo, preferencialmente em cursos de Computação, Sistemas de Informação ou Ciência da Computação;
- Conhecimentos em: Lógica de Programação, Linguagens de Programação Orientada a Objetos, Padrões de Projetos, HTML, Javascript, CSS, Java, Android, Kotlin.

Desejáveis:

- Conhecimento em Flutter.

**Contratação**
CLT

**Como se candidatar** 
Através do link https://jobs.kenoby.com/inatel/job/desenvolvedor-mobile-i-home-office/6132356116e8a53e882ea00f?utm_source=website

# Labels
🏢 Remoto
👶🏽 Junior
⚖️ CLT

**Comment by gusoliveira21** [comment]
vaga encerrada
