### ISSUE TITLE
[Remoto] Android Developer Júnior na Innvo

### ISSUE THREAD

**Issue by andersonsv-zz** [androiddevbr/vagas#1835]
## Descrição da vaga

Projeto de desenvolvimento de um App de um banco digital (foco Pessoa Jurídica).

## Local

100% Remoto 

## Benefícios

- Ótima remuneração (até R$ 5.000,00 CLT - R$7.000,00 - PJ) 
- Convênio médico (CLT)
- GymPass (CLT)
- Vale alimentação (CLT)
- Programa de distribuição de ações (Stock Options)
- Férias remuneradas (PJ)

## Requisitos

Obrigatórios

- Júnior - 2+ anos de experiência com Android
- Kotlin
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis

- Experiência com Testes Unitários

## Contratação

CLT/PJ a combinar

## Nossa empresa

www.innvo.com.br

## Como se candidatar

Por favor envie um email para vagas@innvo.com.br com seu CV anexado - enviar no assunto: Android Júnior

**Comment by gusoliveira21** [comment]
Acredito que a vaga foi finalizada
[vagas@innvo.com.br (vagas@innvo.com.br)](mailto:vagas@innvo.com.br)
O endereço ao qual você enviou a mensagem não foi encontrado no domínio de destino.
