### ISSUE TITLE
[Remoto] Android Developer Jr na [Iventis]

### ISSUE THREAD

**Issue by cimerio** [androiddevbr/vagas#1852]
## Descrição da vaga

Desenvolvedor Android JR - PJ - Remoto- 2 Vagas
CV para recrutamento@iventis.com.br
Requisitos e qualificações: 
Vontade de aprender ,Facilidade com comunicação ,Habilidades com trabalho em grupo ,Pro atividade e Interesse genuíno em aprender

Aqui você irá aprender e desenvolver:
Linguagem Kotlin;Jetpack (Compose, ViewModel, Navigation, Room);
SOLID; Testes unitários e de integração Arquitetura modularizada
Padrão MVVM e MVI ,Notificações push com FCM; Consumo de APIs Rest utilizando Retrofit; Injeção de dependências utilizando Koin

## Local

Remoto

## Contratação

PJ a combinar

## Nossa empresa

Iventis .

## Como se candidatar

Por favor envie um email para recrutamento@iventis.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jcarrio** [comment]
Essa vaga não está mais aberta.
