### ISSUE TITLE
[Remoto] Desenvolvedor Android Senior | Freelance

### ISSUE THREAD

**Issue by albtsantos** [androiddevbr/vagas#186]
## Descrição da vaga

Procuro desenvolvedor Android freelance (de preferência senior) para dois projetos com duração de aproximadamente 20 dias cada. Passarei mais informações aos interessados que se encaixarem no perfil.

## Local

Remoto.

## Benefícios

- 💰

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Projeto(s) publicado(s) na Play Store
- Disponibilidade para ligações periódicas

## Contratação

PF

## Como se candidatar

Por favor envie um email para albertoleite.s@gmail.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by halysongoncalves** [comment]
Enviado o email :)

**Comment by halysongoncalves** [comment]
@albtsantos a vaga fechou?
