### ISSUE TITLE
[Remoto] Desenvolvedor Android [Junior | Pleno | Sênior] OmniChat

### ISSUE THREAD

**Issue by Rebaduy** [androiddevbr/vagas#1861]
**OMNICHAT | LÍDER EM CHAT-COMMERCE NO BRASIL**
Por meio do chat-commerce, já ajudamos mais de 300 marcas do varejo a revolucionar o relacionamento com seus clientes.
Isso porque as vendas por chat unem o melhor de dois mundos: a humanização das lojas físicas com a praticidade e agilidade das vendas online. 
Com mais de 10 mil vendedores na plataforma, ajudamos empresas a construírem marcas verdadeiramente omnichannel.
E queremos cada vez mais transformar compras online em experiências reais.

**RESPONSABILIDADES E ATRIBUIÇÕES**
Desenvolver novas funcionalidades na aplicação Android.
Realizar correções de bugs.
Propor melhorias performáticas para a aplicação e processo.
Sugerir soluções e arquiteturas junto a equipe.
Fazer Code Reviews.
Ensinar e aprender junto a equipe!

**REQUISITOS E QUALIFICAÇÕES**
Experiência com desenvolvimento Android em diferentes aplicações.
Ter trabalhado em equipe de desenvolvedores Android.
Experiência com Kotlin.
Conhecimento sobre estruturas e arquiteturas.
Conhecer testes unitarios

**Será um diferencial:**
Já tiver trabalhado com arquiteturas de mensageria.
Conhecer conceitos de arquitetura, design pattern e clean code.
Ter estudado Jetpack Architecture Components
Conhecimento em Flutter.
Trabalhar com TDD

INFORMAÇÕES ADICIONAIS
Trabalho 100% remoto;
Contratação CLT;
Vagas também para PCD.
Benefícios: VR/VA R$ 30,00 ao dia, Plano de Saúde sem mensalidade, com 30% de coparticipação, Plano Odontológico, Seguro de Vida e Patrocínio aos estudos.

**Interessados, podem entrar em contato no renata.baduy@omni.chat ou se cadastrar em nosso link: https://omnichat.gupy.io/jobs/1205053**

**Comment by gusoliveira21** [comment]
Não encontrado
