### ISSUE TITLE
Android Development

### ISSUE THREAD

**Issue by djaircosta** [androiddevbr/vagas#1874]
Me chamo **Djair Costa**,  tenho 15 de experiencias em TI, mais precisamente em suporte helpdesk, rede infraestrutura logica e cloud, desenvolvimento web, sou iniciante como desenvolvedor android. estou aqui procura de oportunidades para trabalhar e encarar os desafios, aprendizados no mundo de desenvolvimento mobile. contato email: riajd10@gmail.com, telefone: (61) 982703601.

**Comment by khalilayache** [comment]
@djaircosta infelizmente esse repositório é para vagas, por isso precisamos remover a sua postagem de "procurando uma vaga", de uma olhada no repositório, tem algumas vagas para JR, aplique para elas. Se tiver alguma dúvida mande mensagem no #ajuda lá no slack, a chance de alguém te ajudar é alta! 

Qualquer coisa estamos pelo slack ok?! Abraço
