### ISSUE TITLE
Dev Front - React Native Android (especialista)

### ISSUE THREAD

**Issue by Jessysa1** [androiddevbr/vagas#1883]
VAGA
Dev Front - React Native Android (especialista)
CLT- REMOTO, HIBRIDO, PRESENCIAL( Escolha do candidato)

Quais serão seus desafios?
Analisar e desenvolver especificações para testes dos sistemas de média e eventual alta complexidade, objetivando que o aplicativo/software seja liberado dentro do prazo e com qualidade, visando garantir seu perfeito funcionamento.
Planejar e executar o processo de qualidade do aplicativo/software sob sua responsabilidade, bem como evoluir os sistemas e correção de falhas e bugs, buscando garantir reduzir riscos e atrasos nas entregas.
Realizar testes, analisar os resultados e emitir parecer, conforme especificado nos cenários de testes, visando entregas para o cliente com mais qualidade e controle.
Promover a automação dos testes, visando a assertividade e otimização dos trabalhos, bem como preparar o ambiente de testes através de padrões estabelecidos.

O que você precisa ter?
Superior completo em Ciências de Computação, Sistemas de Informação ou áreas afins.
Experiência no desenvolvimento de testes de aplicativos e soluções mobile
Experiência com:
Testes Back-End: Ruby
Principais gems: HTTParty, Sinatra, Cucumber, Selinium Webdriver e Savon
Teste de Performance (diferencial): Jmeter
Teste Front-End: Cypress (JavaScript)
Conhecimento protocolo Http utilizando serviços REST
JIRA

CV:jaraujo@octarh.com.br

**Comment by davidtcdeveloper** [comment]
@Jessysa1 As regras do nosso mural de vagas exigem a divulgação do nome da empresa contratante. Esta vaga será encerrada até ser editada com o nome da empresa contratante.
