### ISSUE TITLE
[Lisboa/Remote] Java Developer at Genesis.studio 

### ISSUE THREAD

**Issue by MargaridaAlmeida10** [androiddevbr/vagas#1884]
![image](https://user-images.githubusercontent.com/63243312/143076942-1b15e00f-9f5b-4d3f-a7d9-b920c1a37aae.png)

**Comment by khalilayache** [comment]
@MargaridaAlmeida10 está issue será fechada pois, segundo as nossas regras só são aceitas vagas relacionadas a Android
