### ISSUE TITLE
[Lisbon/Remote] Tech Lead Java at Genesis.studio

### ISSUE THREAD

**Issue by MargaridaAlmeida10** [androiddevbr/vagas#1885]
![image](https://user-images.githubusercontent.com/63243312/143077889-489edd75-a81e-4be7-924d-772045c6b781.png)

**Comment by khalilayache** [comment]
@MargaridaAlmeida10 está issue será fechada pois, segundo as nossas regras só são aceitas vagas relacionadas a Android
