### ISSUE TITLE
[Brasil, Remoto] Desenvolvedor Fullstack [PLENO] | Incognia 

### ISSUE THREAD

**Issue by EduardaFischer** [androiddevbr/vagas#1887]
**Candidate-se aqui** - [https://www.incognia.com/pt/candidatura-incognia-fullstack-pleno-015](url)
**Sobre a empresa**

Incognia é uma solução de identidade digital para aplicativos mobile, que permite o reconhecimento em tempo real de usuários confiáveis no onboarding, login e pagamentos. Incognia utiliza a biometria comportamental por localização e fingerprint de dispositivos para aumentar as conversões, reduzir os falsos positivos e impedir fraudes. A tecnologia de localização da Incognia usa sinais de rede e sensores no dispositivo para fornecer informações de localização altamente precisas sem capturar dados que identifiquem diretamente o usuário.

As empresas com apps mobile e dispositivos conectados utilizam Incognia para, sem fricção, verificar a identidade do usuário autenticar seu login, detectar e avaliar riscos de fraude, e ao mesmo tempo proteger sua privacidade.

Incognia tem equipes em Nova York, Palo Alto, São Paulo e Recife, com mais de 100M de dispositivos na base, utilizando nossa tecnologia de localização.

**Nossos valores:**

Nós não queremos saber a identidade dos nossos usuários;
Nossa prioridade é servir aos nossos clientes;
Somos rápidos solucionadores de problemas;
Nós nos respeitamos e estamos livres para sermos nós mesmos;
Trabalhamos em equipe para vencer juntos;
Buscamos o que é melhor para nosso futuro;

**Sobre o time:**

Na nossa equipe você irá trabalhar diretamente com o produto que é acessado pelos nossos clientes, seja uma pessoa com perfil de desenvolvedor para realizar as integrações de SDK e API, como o setor de fraude para visualizar as avaliações da Incognia em relação aos dispositivos que estão acessando seus aplicativos. Para isto, você colaborará com a equipe de produto e design para entender as necessidades dos clientes, bem como propor e conceber soluções. Temos bastante autonomia na escolha das nossas ferramentas e decisões de arquitetura, somos uma equipe extremamente colaborativa (Slack e Meet que nos aguentem!) e temos um fluxo de release pouco burocrático.

Nossos serviços são majoritariamente em Ruby on Rails e servem um API GraphQL, os quais consomem várias outras APIs gRPC feitas com Java e Micronaut; também temos alguns consumidores do Kafka para entregar algumas métricas e validações de integração (aquela de SDK que falei lá em cima!). Nosso front-end é feito com React, temos uma biblioteca de componentes (você pode conhecê-la aqui), usamos Typescript, ApolloGraphQL e outras coisinhas mais. 

Você não precisa ter experiência nestas tecnologias, basta conhecimento e experiência em tecnologias similares! E claro: vontade de resolver o problema do cliente!

**O que você irá fazer:**

Desenvolver e manter aplicações web, o que envolve a arquitetura das soluções de front e back-end (Ruby on Rails, GraphQL, React, Python, Java, HTML, CSS etc).
Colaborar e se comunicar efetivamente com desenvolvedores, designers, PMs e outros stakeholders.
Auxílio na construção de novas funcionalidades para produtos web de acordo com as necessidades do negócio.
Integrar sistemas que já estão em uso, seja através da criação de APIs ou de scripts.
Trabalhar junto com a equipe de produto na concepção e desenvolvimento do dashboard utilizado pelos clientes.

**Quais são os requisitos e diferenciais?**

Formação em Ciência da Computação, Sistemas da Informação, Engenharia da Computação ou afins.
Inglês intermediário.
Experiência com Produto e contato com o cliente.
Conhecimento em desenvolvimento de sistemas Web (Por exemplo, Rails).
Conhecimento de Frameworks JS (Por exemplo, React).
Uso de ferramentas de controle de versão (Por exemplo, Git).
Saber utilizar containers (Docker).
Boas noções de Algoritmos e Estruturas de dados.
Saber utilizar banco de dados relacionais (PostgreSQL).

**Comment by davidtcdeveloper** [comment]
@EduardaFischer este mural é voltado a oportunidades para atuar com Android. Como a oportunidade não cita Android, a mesma será removida.
