### ISSUE TITLE
[Remoto] Desenvolvedor Android | Contractor

### ISSUE THREAD

**Issue by arthurpalves** [androiddevbr/vagas#19]
## Descrição da vaga

Procuramos desenvolvedor para trabalhar num curto projeto, de apenas 2 semanas, disponível até 8 horas / dia (caso necessário). Basicamente na criação de um protótipo.

## Local

Remoto

## Benefícios

- Horário flexível
- Pagamento semanal

## Requisitos

Obrigatórios
- 1+ anos de experiência com Android
- Controle de versão distribuído (Git)
- Confortável com padrão MVP, MVC, MVVM e derivados
- Boas práticas de desenvolvimento mobile
- Conhecimento em Java, orientação a objeto e design patterns
- Integração com APIs RESTful e/ou Web Services

Desejáveis
- Experiência em TDD
- Experiência com RxJava
- Projetos Open Source

Diferenciais
- Inglês fluente

## Contratação

Freelance/Informal

## Nossa empresa

www.dapptive.com

## Como se candidatar

Por favor envie um email para arthur@dapptive.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@arthurpalves Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by arthurpalves** [comment]
Não está mais aberta @walmyrcarvalho, esqueci de fechar. ;)

**Comment by walmyrcarvalho** [comment]
@arthurpalves sem problemas! :)
