### ISSUE TITLE
[Barueri – Alphaville] - Desenvolvedor Android Pleno ou Sênior - Foursys

### ISSUE THREAD

**Issue by williamvasconcelos** [androiddevbr/vagas#190]
## Descrição da vaga

Oportunidade para desenvolver aplicativos bancários.

## Local

Barueri – Alphaville

## Requisitos

Obrigatórios
- 2+ anos de experiência com Android
- Confortável com padrão MVP, MVVM

Desejáveis
- Experiência com RxJava, EventBus, Retrofit

## Contratação

CLT

## Nossa empresa

Somos uma empresa de serviços de TI com 15 anos de atuação no mercado, focada no desenvolvimento de soluções customizadas, consultoria de TI, Outsourcing, Body Shop e treinamento, para atender as demandas de seus clientes.

Provedora de soluções, consolida sua marca entregando projetos com qualidade e respeitando os prazos acordados com seus clientes.

Utilizamos as melhores práticas de mercado para desenvolvimento de software, atuando em todo ciclo de vida do projeto com profissionais capacitados, que utilizam seus processos baseados na metodologiaRUP (Rational Unified Process) e a gestão dos projetos baseados no PMI (Project Management Institute), o que garante alto grau de satisfação de seus clientes.

## Como se candidatar

Por favor envie um email para caio.ribeiro@foursys.com.br com seu CV anexado - enviar no assunto: Vaga AndroidDevBR

**Comment by renanrider** [comment]
Do lado de casa, pena que só tenho 7 meses de estudo de Android.

**Comment by walmyrcarvalho** [comment]
Fechado a pedido do owner da issue.
