### ISSUE TITLE
[João Pessoa, PB] - Desenvolvedor Android Pleno ou Sênior - Fractal Tecnologia

### ISSUE THREAD

**Issue by felipefpx** [androiddevbr/vagas#191]
<p align="center"><img src="http://fractaltecnologia.com.br/fractal-tecnologia.png" height="250px"/></p>

## Descrição da vaga

Procuramos um desenvolvedor Android Pleno ou Sênior, organizado, antenado em novas tecnologias, disposto a aprender e compartilhar conhecimentos. Se você manja das paradas do sucesso, têm interesse em trabalhar em sistemas a serem utilizados em diversas escolas espalhadas por todo o Brasil e busca uma empresa que seja aberta a novas tecnologias e sugestões: Seu lugar é aqui!

## Local

Remoto ou Escritório em João Pessoa - PB

## Benefícios

- Horário flexível;
- Equipe bastante receptiva;
- Ambiente de trabalho descontraído;
- Comida! :O

## Requisitos

Obrigatórios
- 2+ anos de experiência com Android
- Inglês intermediário ou avançado
- Material Design Guidelines
- Android Studio e Gradle
- Java 7 ou superior
- Consumo de RESTful APIs com Retrofit 2
- Testes unitários com JUnit 4
- Git
- SCRUM
- Confortável com os padrões MVP, MVC, MVVM e derivados
- Advanced Layouts com Custom UI e Animations
- Experiência com Uncle Bob's Clean Architecture 🥇 

Conhecimentos desejados
- Java 8
- Dagger 2
- ButterKnife
- Realm DB
- ConstraintLayout
- Espresso

Diferenciais
- RxJava / RxAndroid
- JUnit 5
- Robotium
- Mockito

## Contratação

Pessoa Jurídica ou Autônomo com salário a combinar

## Nossa empresa

A Fractal Tecnologia é uma empresa que visa contribuir com a melhoria na educação do mundo através do desenvolvimento de ferramentas que facilitam a vida de estudantes e educadores. Nossa filosofia é que através do aprendizado conseguimos nos tornar pessoas melhores e assim contribuir para um mundo melhor, por isso damos incentivo ao auto-desenvolvimento investindo na sua carreira e lhe proporcionando horários flexíveis.
Temos um ambiente de trabalho flexível, moderno, descontraído e colaborativo onde sua opinião é importante para crescermos juntos.
Gosta de trabalhar de bermuda? Vem pra cá! O que importa pra gente é o que você traz de conhecimento para compartilhar e a vontade de aprender.

## Como se candidatar

Por favor envie um email para recrutamento@fractaltecnologia.com.br com seu CV anexado e com o assunto: **[AndroidDevBr] Vaga Android**

**Comment by walmyrcarvalho** [comment]
Fechada a pedido do dono da issue.
