### ISSUE TITLE
[REMOTO] Pessoa Desenvolvedora Android Kotlin - Construção de Currículo [Trybe] [jr, pleno, senior]

### ISSUE THREAD

**Issue by gfpoliva** [androiddevbr/vagas#1912]
### Como pessoa desenvolvedora Android, sua missão inclui:

- Produzir e melhorar conteúdos (em formato de texto, vídeo), exercícios (teóricos e práticos) e projetos (individuais e em grupo, com avaliação automatizada através de testes unitários) que serão utilizados na formação em desenvolvimento mobile com o objetivo de maximizar a proficiência e empregabilidade das pessoas estudantes;
- Desenvolver instrumentos e processos confiáveis e consistentes de avaliação de proficiência nos conteúdos do currículo da formação em desenvolvimento mobile;
- Participar ativamente da formação de nossas pessoas estudantes, por meio da produção, curadoria e revisão dos  conteúdos lecionados, sejam eles vídeos, textos, exercícios ou projetos;
- Contribuir com o time que executa os conteúdos e o time de Currículo nas tomadas de decisão sobre o desenvolvimento das atividades síncronas e assíncronas da nossa formação;
- Coletar insumos que alimentem o backlog de produto e conteúdo para a evolução constante da experiência das pessoas estudantes.
- Ser referência técnica para as equipes que estão executando o currículo nas turmas, e também para as pessoas que fazem Summer Job na produção de conteúdo da Trybe, tanto do ponto de vista de conhecimento em tecnologia, como de experiência de mercado, compartilhando vivências e aprendizados.

## Local

Remoto

## Benefícios

- Trabalho 100% remoto, não importa onde você está
- Salário competitivo com o mercado
- Plano de Saúde e Odontológico para você e sua família
- Vale Refeição e Alimentação da Caju
- Seguro de vida
- Auxílio de Desenvolvimento Pessoal
- Licença Maternidade e Paternidade estendidas - Empresa Cidadã

## Requisitos

Buscamos alguém que:
- Conheça Kotlin e não tenha medo de botar a mão em Java;
- Saiba utilizar o AndroidX, Architecture Components e outros frameworks do Jetpack. E que também tenha conhecimento das principais third party libraries do mercado;
- Trabalhe com diferentes arquiteturas, sabendo diferenciar suas vantagens e desvantagens;
- Saiba implementar e integrar camadas de networking utilizando APIs RESTful;
- Tenha experiência com testes unitários e/ou testes automatizados;
- Seja proficiente em ferramentas de versionamento de código, como o git.
- Seja referência em feedbacks nos code reviews, sempre buscando formas de ajudar outras pessoas a melhorar a qualidade do código;
- Capacidade de autogestão e planejamento;
- Orientação a dados e fatos, buscando benchmarks e boas práticas no desenvolvimento de conteúdo, exercícios e métodos de avaliação sobre tecnologia;
- É desejável que você tenha alguma experiência com produção e/ou curadoria de conteúdo sobre as tecnologias acima, seja em texto ou em vídeo (blog posts, canais, podcasts, artigos, etc).

## Contratação

CLT

## Nossa empresa

A Trybe é a uma escola de desenvolvimento que se compromete integralmente com o sucesso das pessoas. Afinal, elas só começam a nos pagar quando tiverem uma remuneração mensal mínima. 

Trabalhamos com muito propósito e estamos procurando pessoas que, assim como nós, sonham em transformar o mundo por meio da educação. 

Nosso negócio é GENTE. Trabalhamos exclusivamente com gente talentosa, comprometida, curiosa, motivada e obcecada por qualidade e entrega. Para nós, cultura e valores são inegociáveis. Reconhecemos que todas as pessoas que estão conosco o fazem por escolha própria, pois teriam oportunidades em qualquer outro lugar. 

Fazemos o (im)possível para que cada Tryber tenha oportunidades, desafios, recompensas, se divirta e seja muito feliz. Sabemos que o caminho de construção é longo, que precisamos ter abertura e flexibilidade e que vamos aprender em conjunto todos os dias. Nada nunca está pronto!

### Nossos Valores

**Estudantes em primeiro lugar:** somos obcecados com o sucesso e a conquista dos objetivos profissionais das pessoas estudantes da Trybe e não medimos esforços para tal.
**Confiança genuína:** acreditamos que boas relações são baseadas em confiança, autonomia e liberdade. 
**Transparência:** um ambiente transparente permite melhoria contínua e constrói relações fortes e duradouras. 
**Comprometimento:** missão acordada é missão cumprida. 
**Colaboração:** o nosso sempre vem antes do meu.
**Nosso negócio é gente:** Tudo na Trybe é construído por pessoas para pessoas. É uma obsessão nossa atrair, desenvolver e gerar oportunidades para quem trabalha e estuda conosco e estamos em uma busca constante para ter um coletivo de pessoas cada vez mais diverso.

### Diversidade e Inclusão

Nosso objetivo é criar produtos e experiências de aprendizado para todas as pessoas que desejam ingressar em uma carreira de tecnologia. 

Nos empenhamos em construir uma equipe diversa e forte e contratamos dando oportunidades iguais, independente de identidade de gênero, orientação sexual, raça, religião, formação. 

Acreditamos que ter experiências, perspectivas e trajetórias de vida diferentes enriquecem nosso ambiente, contribuem para evoluir nossa visão de mundo e nos ajuda a construir produtos e experiências que entreguem real valor para a sociedade.
Nos empenhamos para criar um espaço justo, seguro e agradável para todo o time e incentivamos um ambiente aberto, questionador e respeitoso, onde todas as pessoas têm a oportunidade de se manifestar e participar, crescer e compartilhar idéias.

Para conhecer mais sobre nossa cultura: http://bit.ly/2XfOvIR

## Como se candidatar

[Link da vaga](https://jobs.lever.co/trybe/f9dc0f5d-b604-4d39-a509-86ab5aeff249)

**Comment by gusoliveira21** [comment]
Vaga encerrada

**Comment by gusoliveira21** [comment]
(update) Vaga continua encerrada, "Sorry, we couldn't find anything here"
update² 31/01/2023 -> continua dando a mesma resposta.

**Comment by EduardoGhost** [comment]
Vaga encerrada?
