### ISSUE TITLE
Oportunidade desenvolvedor Android SR

### ISSUE THREAD

**Issue by AndriwsPrando** [androiddevbr/vagas#1929]
### **`Desenvolvedor Android SR`**

Estou contratando Desenvolvedores Android SR para atuar em projetos a longo prazo 100% remoto 
Modelo de contratação PJ ou Cooperativa
100% remoto mesmo pós pandemia
Remuneração acima de 15k
Requisitos:
conhecimentos de Kotlin, desejável conhecimentos em Flutter.  
Interessados enviar cv para hunting@descompliti.com.br ou para 11 9-4122-4209 aos cuidados de Andriws

**Comment by davidtcdeveloper** [comment]
@AndriwsPrando As regras do nosso mural exigem a divulgação do nome da empresa contratante. A issue será encerrada até que o nome da empresa seja adicionado.
