### ISSUE TITLE
Desenvolvedor Android SR+

### ISSUE THREAD

**Issue by AndriwsPrando** [androiddevbr/vagas#1930]
### **`Desenvolvedor Android SR+**

Estou contratando Desenvolvedores Android SR para atuar em projeto nos EUA para Ambev Tech. 100% remoto 
Empresa contratante: http://ergondata.com.br/

Modelo de contratação PJ ou Cooperativa
100% remoto mesmo pós pandemia
Projeto de longa duração com possibilidade do profissional se mudar para os EUA 
Remuneração acima de 17k
Beneficios: 
Plano de saúde + seguro devida + descanso remunerado de 30 dias + Gympass + descontos na plataforma Alura
Requisitos:
conhecimentos de Kotlin e Java
Inglês avançado com conversação é obrigatório.
Interessados enviar cv para hunting@descompliti.com.br ou para 11 9-4122-4209 aos cuidados de Andriws

**Comment by davidtcdeveloper** [comment]
@AndriwsPrando As regras do nosso mural exigem a divulgação do nome da empresa contratante. A issue será encerrada até que o nome da empresa seja adicionado.

**Comment by AndriwsPrando** [comment]
> @AndriwsPrando As regras do nosso mural exigem a divulgação do nome da empresa contratante. A issue será encerrada até que o nome da empresa seja adicionado.

Editei o anuncio colocando o site da empresa, muito obrigado pela colaboração
