### ISSUE TITLE
[Brasil] Desenvolvedor Android Sr. / Especialista Inglês Fluente 

### ISSUE THREAD

**Issue by bananajobs** [androiddevbr/vagas#1934]
# Estamos em busca de um perfil sênior/especialista em Android com inglês fluente para uma multinacional :)

Requisitos e qualificações: 
4 anos de experiência em desenvolvimento para Android

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- Aux. HO
- PLR 
- Caju
- e mais :)

## Contratação

CLT

## Como se candidatar

Por favor envie um email para marina@bananajobs.com.br com seu CV anexado - enviar no assunto: Vaga Android Inglês

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by davidtcdeveloper** [comment]
@bananajobs De acordo com as regras do nosso mural de vagas, o nome da empresa contratante é obrigatório. A issue será encerrada até que o nome seja adicionado.

**Comment by bananajobs** [comment]
David, hoje temos vários projetos então gostaríamos de fazer uma abordagem
diferente para as pessoas que têm interesse em se movimentar.

**Comment by davidtcdeveloper** [comment]
@bananajobs Neste caso, para que a issue possa ser ativada novamente, precisamos da lista das empresas e das diversas oportunidades, caso contrário, a issue continuará ferindo as regras e não poderá ser reaberta.
Esta regra foi discutida com a comunidade em nosso Slack e não podemos abrir exceções.

**Comment by bananajobs** [comment]
David, tivemos a autorização das respectivas empresas e já ajustamos o
anúncio das vagas!
Aguardo a ativação :)
Obrigada!

**Comment by davidtcdeveloper** [comment]
@bananajobs Não encontrei o nome da empresa na issue. Poderia cria novas issues para as empresas, cada uma com seus detalhes?

**Comment by bananajobs** [comment]
Isso já foi feito. 

Marina Almeida
