### ISSUE TITLE
(Remote) Searching for Senior Developers

### ISSUE THREAD

**Issue by luzsemoIT** [androiddevbr/vagas#1935]
Hi GitHub community! 
At [Jobsity](jobsity.com) we´re looking for Senior developers (+3 years of experience) with a good English level. We currently have many frontend, backend and full-stack positions, so any techs and languages are welcome!
We offer 100% remote positions, very good salaries in USD and some more benefits: 
-15 working days of paid vacations
-3 extra off days per year
-Paid local holidays
-Paid time off
-Budget for e-learning courses
-Financing program for equipment
-Bonuses for referrals

If you´re interested, don´t hesitate to contact me via email at luz.semo@jobsity.com or [LinkedIn](https://www.linkedin.com/in/luz-semo/) :)

**Comment by khalilayache** [comment]
@luzsemoIT  this issue will be close because as you can check on repository rules, is not allowed position to create or fill a pool.

**Comment by jpventura** [comment]
@luzsemoIT prospecting resumés for non-existent positions is explicitly forbidden by [community code of conduct](https://github.com/androiddevbr/vagas).
