### ISSUE TITLE
Líder de Squad - Fullstack

### ISSUE THREAD

**Issue by SamiBrazil** [androiddevbr/vagas#1936]
### **Pré-requisito**

- Experiência profissional sólida em React e/ou React-Native para Android e/ou IOS em equipe
- Experiência profissional sólida em Node.js em equipe
- Experiência com plataformas de infraestrutura da nuvem (GCP, AWS ou Azure)
- Experiência com versionamento de código em GIT
- Experiência na implementação de testes automatizados

Nossa oferta é de atuação Full time, 100% remoto e CLT, oferecemos asst médica, asst odontológica, VR R$ 500,00 e curso de inglês gratuito, in company. A faixa salarial para essa função, está entre R$ 7k - 11k bruto (temos um projeto para alinharmos faixa x entrega do projeto).

Junte-se ao time: https://liventech.notion.site/Vaga-L-der-de-Squad-Fullstack-8383d24b66684abb8a3937bfc06eae83

**Comment by khalilayache** [comment]
@SamiBrazil  está issue será fechada pois, segundo as nossas regras só são aceitas vagas relacionadas a Android
