### ISSUE TITLE
Desenvolvedor Android Mobile PL/SR

### ISSUE THREAD

**Issue by apaulucci** [androiddevbr/vagas#1938]
**Atividades:**
Desenvolvimento de aplicações para Android;
Desenvolvimento e release, junto com a squad;
Fazer uso de boas práticas e garantir que os projetos estejam em conformidade com convenções internas;
Ser conhecedor do produto promovendo melhorias contínuas o dia-a-dia;
Ser parte colaborativa na evolução da plataforma, trazendo novas ideias, novos pontos de vista e questionando;
Desenvolvimento de funcionalidades que encantem os usuários;
Escrita de código de alta qualidade, com testes e performáticos
Escrever testes unitários e integrados;

**Requisitos:**
Java
Arquitetura Mvp Clean;
Clear Architecture;
Gitflow;
Testes Unitários com Junit/mokito;

**Home Office
PJ**
**Salário: 90h**
Contato: 11 93048-3890

**Comment by davidtcdeveloper** [comment]
@apaulucci De acordo com as regras do nosso mural de vagas, o nome da empresa contratante é obrigatório. A issue será encerrada até que o nome seja adicionado.
