### ISSUE TITLE
Engenheiro(a) Móvel - IOS

### ISSUE THREAD

**Issue by apaulucci** [androiddevbr/vagas#1939]
Atividades:

●        Faça parte de uma equipe multifuncional, contribuindo diretamente para o desenvolvimento e manutenção de um produto global;

●        Faça parceria com colegas para construir e manter ferramentas para desenvolvimento de testes, automação e melhoria de processos de liberação;

●        Defender a experiência do usuário ao se comunicar com produtos, design e tecnologia;

●        Seguir as melhores práticas de desenvolvimento para alcançar a melhoria contínua;

●        Proporcionar à equipe uma estratégia de qualidade que apoie as metas de entrega da equipe;

●        Ser constantemente desafiado a criar soluções de classe mundial.

 

Requisitos:

●        Experiência com Micro frontends e Web Apps;

●        Experiência com Swift;

●        Experiência com React Native e Flutter (é uma vantagem);

●        Experiência com Estruturas Ágeis (Scrum ou similar);

●        Experiência com protocolos de segurança (JWT, OAUTH, etc.);

●        Experiência com ferramentas e plataformas DevOps (Azure, Docker, Kubernetes, etc.);

●        Experiência com ferramentas de desenvolvimento e processo (GIT, NPM, etc.).

 

Home Office

Vaga: PJ (indeterminado)

Salário:  a combinar

Contato: 11 93048-3890

**Comment by davidtcdeveloper** [comment]
@apaulucci Este mural de vagas é focado em oportunidades para desenvolvimento de aplicativos Android. Por este motivo, a issue será encerrada.
