### ISSUE TITLE
[Campinas - SP] - 2 Vagas Desenvolvedor .NET Pleno 

### ISSUE THREAD

**Issue by andremilanez1986** [androiddevbr/vagas#194]
Venha para o lado bom da força. Vem pra cá!
Nós, da HBSIS, estamos reforçando nosso time em Campinas.

Temos mais de 25 anos de experiência no mercado e somos especializados em soluções nas áreas de logística e vendas.

Em nosso dia a dia, adotamos uma cultura ágil para desenvolvimento de produtos que atendam o mercado.  Aqui você vai ver em prática uma gestão que prioriza a entrega de valor, eficiência e segurança reduzindo desperdícios e otimizando processos continuamente.

Como Full Stack Developer você vai atuar como Programador para integrar o nosso time de desenvolvimento de produtos da empresa.

Clique aqui e envie o seu CV
http://www.hbsis.com.br/trabalhe-conosco/#op-156129-full-stack-developer

**Comment by davidtcdeveloper** [comment]
Oi @andremilanez1986 
Este mural de vagas é para oportunidades para Android, ok?
Estou encerrando a issue, já que se trata de oportunidade para .NET.
