### ISSUE TITLE
Remoto - Engenheiro Móvel - Android  [Taking]

### ISSUE THREAD

**Issue by apaulucci** [androiddevbr/vagas#1942]
Atividades:

●        Faça parte de uma equipe multifuncional, contribuindo diretamente para o desenvolvimento e manutenção de um produto global;

●        Faça parceria com colegas para construir e manter ferramentas para desenvolvimento de testes, automação e melhoria de processos de liberação;

●        Defender a experiência do usuário ao se comunicar com produtos, design e tecnologia;

●        Seguir as melhores práticas de desenvolvimento para alcançar a melhoria contínua;

●        Proporcionar à equipe uma estratégia de qualidade que apoie as metas de entrega da equipe;

●        Ser constantemente desafiado a criar soluções de classe mundial.

 

Requisitos:

●        Experiência com Micro frontends e Web Apps;

●        Experiência com Kotlin;

●        Experiência com React Native e Flutter (é uma vantagem);

●        Experiência com Estruturas Ágeis (Scrum ou similar);

●        Experiência com protocolos de segurança (JWT, OAUTH, etc.);

●   Experiência com ferramentas e plataformas DevOps (Azure, Docker, Kubernetes, etc.);

●       Experiência com ferramentas de desenvolvimento e processo (GIT, NPM, etc.).

Home Office

Vaga: PJ

Salário: a combinar

Contato: 11 93048-3890
cvs: analuisa.paulucci@taking.com.br

**Comment by davidtcdeveloper** [comment]
@apaulucci Recomendamos adicionar mais informações da empresa, se possível website e informação para contato. A oportunidade também não cita como a pessoa deve aplicar.

**Comment by apaulucci** [comment]
Feito! Obrigada
