### ISSUE TITLE
Desenvolvedor Android Mobile Sr

### ISSUE THREAD

**Issue by ArianySoares** [androiddevbr/vagas#1949]
Senioridade: Sênior
Atividades:
Atuar na manutenção de aplicativos existentes;
Atuar na criação de novas funcionalidades, conforme a demanda;
Buscar novas tecnologias e aplicá-las aos produtos visando inovação;
Atuar com Sprints semanais de forma motivada e comprometida;
Comprometer-se a aplicar o layout conforme descrito, sugerindo mudanças quando necessário.
Requisitos:
Experiência no mínimo de 4 anos em Android na Linguagem Kotlin e/ou AndroidX;
Já ter realizado um fluxo completo de publicação na Play Store;
Experiência em aplicação de layout (Constraint, Linear, Layout e outros);
Orientação a Objetos e padrões de projeto (MVC, MVVM e outros);
Integração/acompanhamento com ferramentas de análise de dados e social (Play
Store, Google analytics, Firebase, Fabric e outras);
Manipulação de serviços utilizando Rest APIs e SQL (Retrofit, Gson);
Inserção/gerenciamento de bibliotecas (Gradle).
Contratação: CLT
Atuação: Home Office.
Benefícios: Plano de saúde, plano odontológico, vale alimentação, vale refeição, vale mobilidade, vale cultura, vale saúde, vale educação, seguro de vida, auxílio creche e descontos em parceiros

Interesses enviar cv com pretensão salarial para ariany.soares@mtp.com.br

**Comment by davidtcdeveloper** [comment]
@ArianySoares As regras do nosso mural de vagas exigem a divulgação do nome da empresa contratante. A issue será encerrada até que mais informações sobre a empresa sejam adicionadas.
