### ISSUE TITLE
Dev Android

### ISSUE THREAD

**Issue by KstackRe** [androiddevbr/vagas#1976]
Estamos com uma posição em aberto para Dev Android!! 

Contratação PJ + benefícios: 
Atuação: full home office. 

Conhecimentos obrigatórios:
- Experiência com Kotlin;
- Experiência com endpoints padrão REST;
- Rigor na organização em repositório GIT;
- Rigor na produção de código: usar comentários, seguir a arquitetura do projeto, usar nomes de variáveis e métodos que fazem sentido, etc..

O que buscamos em você:
- Mínimo de 3 anos de experiência com Android trabalhando em projetos reais.
- Mínimo de 1 ano de experiência com Kotlin.
- Experiência com versionamento de código utilizando GIT. Nós usamos GitHub.
- Conhecimentos de arquitetura MVVM.
- Ter conhecimento e programação reativa e injeção de dependências.
- Conhecimentos em desenvolvimento utilizando o Android Jetpack.

**Comment by davidtcdeveloper** [comment]
@KstackRe Conforme as regras do nosso mural, é obrigatória a divulgação do nome da empresa contratante. Esta issue será encerrada até que o nome seja adicionado.
