### ISSUE TITLE
[Home Office] Desenvolvedor Android Sênior  

### ISSUE THREAD

**Issue by RecruiterLucas** [androiddevbr/vagas#1997]
*Desenvolvedor Android Sênior*
Alocação: Banco Digio
Tempo de projeto: Indeterminado
R$17.000,00
Contrato: PJ
Modelo trabalho: 100% Home Office 

*Benefícios*
Férias;
Descanso remunerado;
Máquina.

*Atribuições*
Acompanhar todo o ciclo de vida do aplicativo (conceito, projeto, testes, lançamento e suporte);
Assegurar que aplicativos novos e antigos satisfaçam aos padrões de qualidade;
Colaborar com equipes multidisciplinares para definir, projetar e entregar novos recursos;
Descobrir, avaliar e implementar continuamente novas tecnologias para maximizar a eficiência de desenvolvimento.
Projetar e construir aplicativos avançados para a plataforma Android;
Realizar testes unitários de código quanto à robustez, incluindo casos extremos, usabilidade, acessibilidade e confiabilidade geral;
Trabalhar com fontes de dados externas e APIs.

*Requisitos*
Activity;
Broadcast Receiver;
CI/CD;
Clean Code;
Coroutuines;
Firebase;
Fragments;
Kotlin;
Princípios de Design OOP;
Princípios de Programação Funcional;
Protocolo HTTP;
Providers;
Qualifiers;
Room;
Service;
SOLID;
SQLite;
ViewModel;
WorkManager.

E-mail para envio de currículo/ Linkedln: lucas.oliveira@plus-it.com.br

**Comment by davidtcdeveloper** [comment]
@RecruiterLucas As regras do nosso mural de vagas exigem a divulgação do nome da empresa contratante. A issue será encerrada até que o nome seja adicionado.
