### ISSUE TITLE
[Remote] Android Developer @ International opportunity

### ISSUE THREAD

**Issue by TacianySouza** [androiddevbr/vagas#1999]
Mandatory technical requirements:
● Fluent English.
● 4 years of development experience with Python, Java/Kotlin or Golang.
● 3 years of CI/CD experience
● 3 years of Postgres, Redis, MySql experience
● API development - 4 years
● kafka, rabbitmq or redis streams
● API Services Integration

Company Details:
Company focused on the development of Artificial Intelligence, founded in 2019 in Los Angeles, California.

Responsibilities:
Create and maintain APIs for research and other ongoing projects
Create pixel perfect web pages from wireframes
Integrate API Services
Build highly scalable APIs that are deployed via CI/CD pipelines
Participate in the development lifecycle to develop new features and functionality for the Backend.

Application: https://forms.gle/rak7saN2ByLS1hts8

**Comment by davidtcdeveloper** [comment]
@TacianySouza The rules of our board demand the name of the hiring company. This issue is going to be closed until it gets edited with the company name.
