### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Android | Stone Pagamentos

### ISSUE THREAD

**Issue by jgabrielfreitas** [androiddevbr/vagas#2]
## Descrição da vaga

Energia, Inteligência, Tecnologia e MOBILE. Se você é um desenvolvedor mobile apaixonado e procura crescer sem limites em uma empresa com desafios gigantes, venha pra Stone!

## Local

Centro do Rio de Janeiro, perto do aeroporto Santos Dumont

## Benefícios

- Ambiente descontraído
- Video Game (Xbox One)
- Vale transporte
- Vale refeição/alimentação
- Plano de saúde
- Venha trabalhar de bermuda e chinelo

## Requisitos

Obrigatórios
- Experiência com Android
- Boas noções de orientação a objetos
- Design patterns
- Experiências com aplicações RESTful (JSON e XML)
- Persistência de dados (SQLite, ActiveAndroid, Realm....)

Desejáveis
- Experiência com Espresso e UI Automator
- Integração contínua  
- Deploy contínuo 

Diferenciais
- Projetos opensource

## Contratação

Estágio ou CLT

## Nossa empresa

A Stone é uma adquirente de cartão de crédito 100% brasileira, com uma abordagem de mercado disruptiva e com produtos inovadores em um segmento normalmente dominado por grandes bancos.

Oferecemos um pacote completo de serviços de pagamento para lojistas processarem transações e aumentarem suas taxas de conversão. Tudo isso com um atendimento inteligente, pessoal e especializado.

## Como se candidatar

Se interessou pela empresa? Quer ver o nosso escritório? Acha que está de acordo com o que buscamos? Mande um email com o assunto "#DEVANDROID ${SEU_NOME}" para o email jferretti@stone.com.br e jfreitas@stone.com.br 

Quer saber mais da empresa? Acesse o nosso [site](http://www.stone.com.br/)

**Comment by walmyrcarvalho** [comment]
@jgabrielfreitas Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by jgabrielfreitas** [comment]
Infelizmente ainda está aberta 😔

**Comment by walmyrcarvalho** [comment]
@jgabrielfreitas Não chora, já já aparece! hahah 👍
