### ISSUE TITLE
[Remoto]  Desenvolvedor Digital Twin [Alliança Consultoria Recursos Humanos]

### ISSUE THREAD

**Issue by Taisa09** [androiddevbr/vagas#2022]
Buscamos por Desenvolvedor Digital Twin para Multinacional Alemã do segmento de Soluções e Engenharia.

Requisitos:

- Experiência em desenvolvimento de jogos, processamento de imagens e realidade virtual;
- Vivência nas ferramentas Unreal Engine, Unity, 3ds Max, Maya, Houdini, Cinema 4D e Blender;
- Conhecimento em C++ e Python;
- Inglês avançado.

Contrato CLT + Benefícios

Para mais informações envie um e-mail para taisa@alliancarh.com.br 💻

**Comment by davidtcdeveloper** [comment]
@Taisa09 As regras do nosso mural de vagas exigem a divulgação do nome da empresa contratante. A issue será encerrada até ser editada com o nome.
