### ISSUE TITLE
Android Native Sr

### ISSUE THREAD

**Issue by AnaCarolinaBuschinelli** [androiddevbr/vagas#2027]
Multinacional Portuguesa  com mais de 17 anos de fundação que atua também no segmento de consultoria de tecnologia está buscando um Android Sênior para um cliente internacional. 

Oportunidade remota ou possibilidade de migrar para Lisboa ou Porto. Empresa fornece o visto de trabalho.

Inglês: Avançado

Remuneração: 175 euros/dia se for PJ ou 2.000 euros (Líquido) CTI + benefícios

The context is:

- Design, build and test native Android versions of popular e-mobility applications.

- Work as part of a stable, cross-functional team to ship regular updates.

- Collaborate with product and business colleagues to plan upcoming features and manage technical debt.

- Take ownership of your personal development and developer experience.

-  Minimum of 5 years experience only with Android native. 

- Have very good knowledge of the Kotlin programming language and Android Studio.

- Experienced in common mobile app design patterns and architectures.

- Familiar with Material design, HTTP request methods and RESTful API design.

- Knowledge of Jetpack Compose, Kotlin Flow and LiveData would be beneficial, but is not required.

- Feel at home in a diverse, inclusive team that has high quality standards and passionately develops software.

Interessados podem me enviar mensagem no whatsapp
Ana Carolina - 11 9 8446 2020

**Comment by davidtcdeveloper** [comment]
@AnaCarolinaBuschinelli As regras do nosso mural de vagas exigem a divulgação do nome da empresa contratante. A issue será encerrada até que seja editada com o nome.
