### ISSUE TITLE
[Remoto] Kotlin Multiplatform Mobile Developer na [Touchlab]

### ISSUE THREAD

**Issue by chislett** [androiddevbr/vagas#2042]
### Job Description
[Touchlab](https://touchlab.co) is looking for Mobile Developers! We are the global experts in Kotlin Multiplatform Mobile (KMM) tech. As KMM adoption continues to grow, we want to work with engineers who want to become experts in the tech and help shape the future of the platform. We’re looking for someone who has Android/Kotlin experience and is eager to dive into KMM development. The ideal candidate has some iOS experience, but we know most Android devs need to learn these skills, and we’re the best place to learn! 
 
In your role, you will be working with clients to implement mobile projects, using a blend of Kotlin Multiplatform Mobile and platform-native technologies. You will have opportunities to contribute to both our open source and internal products, as well as speaking and publishing opportunities. We have been involved in the Android and native mobile communities for years and will be increasing that involvement going forward.
 
> [@faogustavo](https://androiddevbr.slack.com/team/U261VHWA0) works with us and has offered to answer any general questions about Touchlab in the AndroidDevBr Slack Group.

**[APPLY HERE](https://touchlab.co/kotlin-multiplatform-mobile-developer/)**
 
### What you will be doing
- Build quality applications based on product requirements
- Experiment, learn, and coach others in Multiplatform strategies
- Bring design mock-ups to life and create attractive UI’s
- Perform peer code reviews and help us all get better
- Improve our process in weekly retrospectives
 
### Must-Have
- 2+ years of professional Android development experience or demonstrable equivalent skills. Open source contributions and individual projects will be considered as well (not school projects)
- Strong familiarity with Kotlin on the JVM
- Understanding of various Android libraries and recent best-practice technologies and libraries
- Familiarity with Git, GitHub, and good version control practices
- Strong interest in Kotlin Multiplatform Mobile development
 
### Nice-to-Have
- iOS and XCode familiarity
- Experience with Kotlin Multiplatform
- Experience working in an Agile team
- Open source contributions
 
### What We Offer
In addition to competitive fair salaries, Touchlab provides a comprehensive benefits package. We have a generous vacation policy, plus company holidays and a floating holiday (so you choose what’s important to you). We also offer the team budget for learning and development, as well as a Classpass membership and remote support for monthly coworking and internet.
 
Prior to the pandemic, we had remote and flexible work-from-home policies. We’re all dIstributed now and will continue to be fully distributed. Monday- Friday 8-hour workweek. Everyone receives a remote work gear kit, including a company-supplied Apple machine. We get together for team events, sponsored lunches, and team socializing. It’s a big plus if your dog can make an appearance on Zoom (we don’t discriminate against cats, either).
 
### Hiring Practices
- PJ or CLT ([Deel](https://www.deel.com/))
- As in all our work, we believe hiring is a collaborative process. Hiring doesn’t come down to the decision of just one person, multiple members of our team will evaluate each candidate.
- Your time is as valuable as ours. We’ll keep the interview process as streamlined as possible and make sure you speak with multiple members of the team in a timely fashion; it helps you get to know us quicker, and vice versa.
- We focus on practical topics during the interview process. We want to hear how you’ve worked on a software team and your knowledge to solve common mobile problems.
- Our typical interview stages: A technical screening where we ask you to complete an exercise. Next is the introductory phone interview, followed by long-form interviews with rotating members of our team. Finally, we collect feedback internally and notify applicants whether or not an offer will be made. Of course, this can vary based on the position and level and we’ll communicate that at the start of the process.
 
### Who We Are
We are a growing team of people with a breadth of backgrounds in different industries. Our team is great at what they do. We work collaboratively and believe we can help shape the future of mobile through Kotlin Multiplatform.
 
For the last decade, Touchlab has been at the forefront of mobile product development. We train and advise on mobile best practices, develop apps for all platforms, and as the recognized global experts in Kotlin Multiplatform Mobile, we have been both a JetBrains and Google-certified agency.
 
Because both startups and the largest public companies seek us out to help them build their mobile products, our team members get the opportunity to work on a variety of interesting projects as well as contribute to our open-source endeavors.
 
We’ve contributed code to Kotlin/Native itself, built the most successful open-source starter kit for KMM, and released multiple KMM libraries that are being used by developers around the world. Through our [partnership](https://blog.jetbrains.com/kotlin/2020/02/accelerate-your-kotlin-multiplatform-evaluation-with-kamp-kit/) with JetBrains and our community [efforts](https://touchlab.co/category/touchlab-share/), we are directly influencing the growth and adoption of KMM. Check out our [blog](https://touchlab.co/blog/) and JetBrains’ KMM [portal](https://kotlinlang.org/lp/mobile/) to learn more.
 
We believe that embracing our unique diversity leads to success, and we’re working hard to build a diverse, equitable, and inclusive team. Touchlab is proud to be an equal opportunity workplace for people of every gender identity and expression, race, ethnicity, religion, sexual orientation, national origin, disability, age, veteran status, parental status, and any other identities. We strive for all to feel welcome and comfortable here.

**[APPLY HERE](https://touchlab.co/kotlin-multiplatform-mobile-developer/)**

#### Category
- Kotlin

#### Allocation
- Remote

#### Regime
- PJ
- CLT

#### Level
- Mid

**Comment by jeancsanchez** [comment]
@chislett Is this position still open?
