### ISSUE TITLE
Vaga para desenvolvedor em São Paulo

### ISSUE THREAD

**Issue by andrelramos** [androiddevbr/vagas#205]
![desenvolvedor3-02](https://cloud.githubusercontent.com/assets/10236206/26423303/8832ddae-40a3-11e7-89f1-8948d14cb34d.png)

Se você não está tão familiarizado com o stack proposto na vaga mas se sente capaz de aceitar o desafio, não hesite em mandar o seu cv para nós!

**Comment by davidtcdeveloper** [comment]
Este mural tem como objetivo divulgar vagas para desenvolvedores Android.
Como não encontrei nada sobre Android na vaga, estou encerrando a issue.
