### ISSUE TITLE
Excluir

### ISSUE THREAD

**Issue by nathanameta** [androiddevbr/vagas#2055]
## Descrição da vaga

Projeto de desenvolvimento de um app  de vendas para um dos maiores varejistas do brasil. 

## Local

100% Remoto 

## Benefícios

- PPR
- Alimentação/Refeição
- Ajuda de custo extra
- Ajuda custo alimentação
- Plano de saúde Bradesco
- Plano Odontológico
- Plano de Saúde e Odontológico Nacional
- Seguro de Vida

## Requisitos

Obrigatórios

- 2  anos de experiência com Android Kotlin
- 2 anos de vivência de   MVVM.
- Conhecimento POO (Programa orientada a objetos).
- Conhecimento em testes unitários e de interface.
- Clean Architecture
- Clean Code.

## Contratação

CLT + Ajuda custo + Benefícios. 

## Nossa empresa

Há mais de 30 anos no mercado, preparamos empresas para os desafios do presente e do futuro, direcionando-as à Transformação Digital, eficiência, redução de custos, agilidade e humanização dos processos, pensando sempre na melhor experiência do cliente.

## Como se candidatar

Por favor envie um e-mail para nathana.silva@meta.com.br com seu CV anexado - enviar no assunto: Vaga Android ou entre em contato no whats 51 2101-1331.

## Labels

- CLT
- Remoto
- Pleno

**Comment by MessiasLima** [comment]
@nathanameta não dá para fechar a issue?
