### ISSUE TITLE
[100%remote] Android Developer na [ConveyorNow]

### ISSUE THREAD

**Issue by paulartt** [androiddevbr/vagas#2056]
We are looking for an international software company based in US who partner with the world’s leading brands such as Dow Jones, FOX, Warner Bros., Facebook, Google, BMW, BlackBerry, Discovery. 

You are a good match if you have:

> BS or advanced degree in software engineering or equivalent professional experience.

> Mínimum 4 years of experience in Software Development in Android, especially with Kotlin.

> Experience working with distributed teams and clients.

> Knowledge of Agile and SDLC concepts, practices, and techniques.

> Strong written and verbal communication skills in English

please send  your resume to paula@conveyornow.com

**Comment by khalilayache** [comment]
This issue was closed because following the rules it is not allowed to create a post with a propose to create a bank of resumes
