### ISSUE TITLE
[remoto] android developer júnior na aiqfome

### ISSUE THREAD

**Issue by monicapio** [androiddevbr/vagas#2057]
## Nossa empresa ##

aiqfome
Somos a primeira e a maior plataforma de delivery online para restaurantes 100% brasileira, levando tecnologia e a melhor experiência em entrega pra todo o interior do Brasil!

Somos parte do Grupo Magazine Luiza, compartilhando o sonho de digitalizar todo o Brasil e trazer tecnologia pra todo mundo!

A gente se reinventa a todo momento e estamos revolucionando o mercado local de delivery, sem abrir mão de um valor inegociável: tratamos os outros como gostaríamos de ser tratados, criando soluções únicas e proporcionando a melhor experiência possível sempre, pra todo mundo envolvido!

Ah, e o mais importante: nos divertimos MUITO enquanto fazemos tudo isso!

Por isso, atenção: só contratamos pessoas legais 😉💜

## Descrição da vaga ##

Principal missão: Ser responsável pela construção e inovação do universo fominha que cabe até dentro de um display de 7" polegadas! E atuar como um novo cientista em nosso LaB, unindo neurônios e memes diariamente para entregar um app capaz de atingir todos os fominhas de nosso multiverso.

**Coisas que você precisa fazer pra mandar muito bem aqui:**
- Participar de análises junto ao time, quanto as sugestões de melhorias dadas por fominhas, restaurantes, fomers e hunters;
- Programar novas funcionalidades e ajustes solicitados pensando em desempenho e escalabilidade das aplicações já existentes;
- Entregar software de qualidade, buscando boas práticas de desenvolvimento;
- Proatividade para encontrar soluções alternativas/eficazes - e não só as saídas mais fáceis!
- Estar sempre disposto a pesquisar e se atualizar sempre sobre novidades da área.

**Requisitos**
**Antes de qualquer coisa, você precisa ser MUITO gente boa e teamplayer!**
**Mas também é importante que tenha:**
- Conhecimento no desenvolvimento de aplicativos nativos Android (Kotlin/Java);
- Conhecimento no Android SDK (Android Components como: Lifecycle, Service, ContentProvider, Broadcast, etc);
- Consumo de APIs REST;
- Ferramentas de versionamento de código e desenvolvimento colaborativo;
- Android Jetpack Components (ViewModel, Room, LiveData, Databinding, Navigation).

**Será um diferencial:**
- Conhecer e ter aplicado alguma arquitetura de software (MVVM, MVP, MVI, etc);
- Conhecer Clean Architecture, princípios SOLID e padrões de projeto;
- Conhecer UI customizada;
- Conhecer testes unitários, de integração e instrumentados.

**Contratação**

- CLT

**Benefícios**

- Opção de trampo full remoto
- Bônus por metas atingidas
- Cupons mensais pra pedir no aiq
- Descontos em cursos
- App de saúde mental (terapia online)
- Plano odontológico
- Plano de saúde
- Vale alimentação
- Vale transporte
- Seguro de vida
- Dois monitores pra trabalho
- Cafézin expresso e moído na hora
- Uma cultura de autonomia e diversidade
- Não temos nenhum dress code
- E a chance de você crescer aqui dentro é imensa!

**Nível**

- Júnior

**Como se candidatar**
Se inscreva na vaga [aqui](https://aiqfome.gupy.io/jobs/2000829)

**Comment by gusoliveira21** [comment]
vaga encerrada

**Comment by gusoliveira21** [comment]
continua encerrada

**Comment by gusoliveira21** [comment]
update -> continua encerrada
![Caspturar](https://user-images.githubusercontent.com/42920754/215842061-043854f0-54e0-4d42-817c-6ea6dc8f91ed.PNG)

**Comment by biduzilla** [comment]
Vaga encerrada
