### ISSUE TITLE
Android Developer Sênior

### ISSUE THREAD

**Issue by brugalerani** [androiddevbr/vagas#2061]
Android Developer | Bees Force
at BEES Brasil [(View all jobs)](https://boards.greenhouse.io/beesbrasil)
Campinas - SP
About us
We are part of ABInBev’s ecosystem, the biggest brewer in the world, and we work to help our costumer’s life using a range of BEES Applications.
As a tech cell of our organization, we have a simple goal: to grow. Grow as people, as professionals, as a company.
To achieve it, we use the technology creating digital solutions that make our costumers lives simpler, their decisions smarter and their business more profitable. 
What you'll do:
•	Be part of a cross-functional team, directly contributing for software development and maintenance
•	Collaborate in the definition of concepts such as project-wide coding style guides
•	Enforce quality during code development and review
•	Promote and defend the best practices and quality within the team and across the business
•	Constantly be part of code tuning and, refactoring and debugging
•	Identify problems, risks, and dependencies, escalating and managing when necessary 
What you'll need:
•	Development for Android (native) using Kotlin and Java
•	Code versioning with Git
•	MVVM architecture
•	Mechanism for dependency injection
•	APIs consuming by Retrofit
•	Coroutines
•	Firebase
•	Unit Test
•	Creation of pipelines using Azure Devops
•	Apps modulation
•	Code Review
•	Design Architecture solutions
 
More about you:
•	You´re passionate about software development and knows how to ensure its quality;
•	You´re motivated by building up world class solutions that impacts millions of users all over the world;
•	Experienced working in an environment which uses and stimulates DevOps culture;
•	You´re creative when solving problems and is continuously seeking improvements for processes and solutions;
•	You can communicate clearly with your team and the company to identify issues and demands;
•	You have the autonomy to recognize the current and new priorities, evaluating the impact of their outcomes in the final result.
 
What We Offer:
•	Performance based bonus*
•	Fourteen annual salaries* 
•	Private pension plan
•	Meal Allowance
•	Casual office and dress code
•	Days off*
•	Health, dental, and life insurance
•	Medicines discounts
•	Gympass partnership
•	Zenklub partnership
•	Childcare subsidies
•	Discounts on Ambev products*
•	Newvalue partnership
•	Scholarship*
•	School materials assurance
•	Language and training platforms
•	Transport allowance
*Rules applied
 
Equal Opportunity & Affirmative Action:
•	Bees is proud to be an Equal Opportunity and Affirmative Action employer. We do not discriminate based upon of race, color, national origin, gender, gender identity, sexual orientation, protected veteran status, disability, age, or other applicable legally protected characteristics.

Send me a Resume: bruna.galerani@sharepeoplehub.com.br

**Comment by khalilayache** [comment]
@brugalerani Following the rules of this repository it is mandotory to put at the name of the issue, the company which will be hire the candidate and local that candidate will be work. So please change the name of the issue. Until the name be fixed this issue will be closed
