### ISSUE TITLE
Vaga para Desenvolvedor (a) Mobile Android - CLT - 100%Home Office para a Solutis Consultoria 

### ISSUE THREAD

**Issue by RosangelaSeekerh** [androiddevbr/vagas#2063]
A Seekerh, esta em busca de um Desenvolvedor(a) Mobile Android Pleno.
Contato: linkedin.com/in/rosangelaheidorn](https://www.linkedin.com/in/rosangelaheidorn

Segue descrição da vaga:
RESPONSABILIDADES E ATRIBUIÇÕES

Como será seu dia a dia: (Atividades que vai realizar)
Desenvolver aplicações para dispositivos Android, Java 7, Kotlin, Android Studio, REST, Retrofit, Android ViewModel.

REQUISITOS E QUALIFICAÇÕES
Pra mandar bem nessa oportunidade você precisa manjar das tecnologias: (Conhecimentos técnicos obrigatórios)
Sólidos conhecimentos do SDK Android;
Java/Kotlin;
Android JetPack(ViewModel/LiveData/Room/Navigation)
Familiaridade com ferramentas de injeção de dependência (Koin || Dagger)
Experiência com gerenciamento de threads (RxJava || Coroutines)
Consumo de APIs com Retrofit
Testes usando JUnit, Mockito e Espresso;
Familiaridade com padrões arquiteturais como MVVM, CLEAN;
Git, Docker, GitLab CI.

**Comment by khalilayache** [comment]
@RosangelaSeekerh conforme as regras do repositório, é obrigatório colocar no título da issue, o nome da empresa a qual se destina a vaga! Por favor, peço que altere.

**Comment by RosangelaSeekerh** [comment]
> @RosangelaSeekerhconforme as regras do direito empresa, é obrigatório colocado no título da empresa, o nome da qual se destina a vaga! Por favor, peço que altere.

**Comment by RosangelaSeekerh** [comment]
Onde coloco essa i formacao

**Comment by khalilayache** [comment]
@RosangelaSeekerh você coloca no título da issue. Atualmente está "Vaga para Desenvolvedor (a) Mobile Android - CLT - 100%Home Office" no topo dessa página e há um botão "Editar" ao lado
