### ISSUE TITLE
MVHunter são jose dos campos Android Developer 

### ISSUE THREAD

**Issue by jcveri** [androiddevbr/vagas#2067]
Vaga: Desenvolvedor Android Sr./PL
Desenvolvimento Android, Flutter,  Android Annotations, Material Designer, Push Notification, LiveData.
Conceito de código limpo e melhores práticas. Utilização arquitetura VIPER, MVP, MVC, MVVM. JSON, REST, SOAP.
Desenvolvimento Seguro. Análise de Requisitos. Agile/Scrum. Jira / Git /Gitflow/AZURE DEVOPS, CI/CD, Publicação na Loja
Com o que irá trabalhar:
Desenvolvimento de novos projetos e manutenção e melhorias em aplicativos mobile voltados para soluções de gestão financeira que atende o cidadão brasileiro.
SoftSkills
Proativo para identificação e resolução de problemas; atitude positiva em situações adversas; autoconfiança; trabalho em equipe;
boa comunicação verbal e escrita; flexibilidade e adaptabilidade a projetos, processos e pessoas; boa gestão do próprio tempo e empatia.
MODALIDADE DE CONTRATAÇÃO: PJ OU COOPERADO
 
cv para contato@mvhunter.com.br com pretensão salarial

**Comment by khalilayache** [comment]
@jcveri conforme as regras do repositório, é obrigatório colocar no título da issue, o nome da empresa a qual se destina a vaga! Por favor, peço que altere.
