### ISSUE TITLE
[Remoto] Desenvolvedor Android | Freelance - AquiCabe app de storage

### ISSUE THREAD

**Issue by simonfan** [androiddevbr/vagas#207]
### Sobre o projeto:
Estamos desenvolvendo um app que permite aos nossos clientes gerenciarem seus bens em um serviço de storage remoto diretamente do mobile. Nossa empresa oferece o serviço de coleta (pegar o objeto da casa do cliente e levá-lo ao storage) e também de devolução (do storage de volta para a casa do cliente).

O App já está em processo de desenvolvimento e a primeira parte, relacionada à contratação de planos de storage já está pronta. Agora faltam as partes de gerenciamento dos objetos armazenados.

O App Android deverá permitir aos usuários:
- [x] Selecionar múltiplos planos de storage para contratar e pagar por assinatura
- [ ] Agendar coletas de objetos (de casa para o storage)
- [ ] Agendar devoluções de objetos (do storage para casa)
- [ ] Visualizar e gerenciar os objetos guardados direto do app

### Sobre o trabalho:

Estamos procurando um Desenvolvedor Android Pleno para um projeto de 2 - 3 meses para concluir o desenvolvimento do app. Você trabalhará em um app Android que publica e consome dados para uma API REST, com autenticação de usuário e gerenciamento de dados. Todos os layouts já estão prontos e bem organizados em um protótipo no InVision e as especificações do layout estão no Zeplin.

A API REST já está funcionando, portanto o trabalho de desenvolvimento será de implementar a interface e integrá-la à API e, nos casos necessários, especificar novas demandas de endpoints da API.

Nós trabalhamos com Scrum como metodologia. Requeremos que todos os membros da equipe participem de uma *daily de 10min via Google Hangouts / Skype* para sincronizar o trabalho e pedir ajuda - trabalhar remoto é algo que adoramos, mas que sabemos ser difícil, um contato pessoal diário é algo que acreditamos ser importante para o bom fluir do trabalho :)

## Local

Remoto.

## Benefícios

- Workflow bem organizado, com todo o layout muito bem planejado e organizado
- Tempo flexível, podemos nos reorganizar
- Volume de trabalho deverá ser de aprox. 10-12 horas semanais

## Requisitos

Obrigatórios
- 2+ anos de experiência com Android
- Confortável com trabalho REST
- Trazer boa energia :)

## Contratação

PJ a combinar

## Nossa empresa

Somos uma Startup Brasileira testando um produto. O time é pequeno, mas extremamente motivado.

## Como se candidatar

Por favor envie um email para simonxd@gmail.com com seu CV anexado - enviar no assunto: Vaga Android AquiCabe

**Comment by felipepalma14** [comment]
Ainda em aberto?

**Comment by simonfan** [comment]
Acabamos de fechar com um desenvolvedor @felipepalma14, obrigado pelo interesse!
