### ISSUE TITLE
Desenvolvedor Android | ICON IT | REMOTO

### ISSUE THREAD

**Issue by FlavinhaRH** [androiddevbr/vagas#2070]
Olá! A ICON IT está com oportunidade de Desenvolvedor Android para atuar em um cliente internacional!

**Projeto 100% remoto
Regime PJ (Taxa hora negociável)**

Skill Técnico: 
- Android (Java)
- Basic SQL
- DevOps (CI/CD)
- Inglês avançado (necessário para conversação)

Ficou interessado(a)? Envie seu currículo para flavia.marques@iconit.com.br ou me chama no linkedin para eu te passar mais detalhes da posição! https://www.linkedin.com/in/fl%C3%A1viamarques/

**Comment by khalilayache** [comment]
@FlavinhaRH conforme as regras do repositório, é obrigatório colocar no título da issue, o nome da empresa a qual se destina a vaga e o local de atuação! Por favor, peço que altere
