### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Android [PLENO] | DELIVERY MUCH BRASIL

### ISSUE THREAD

**Issue by manoellapreuss** [androiddevbr/vagas#2075]
## Oi Dev Android! 

Prazer, sou a Manoella, recruiter da Delivery Much Brasil. Estou encarregada de encontrar um talento Dev Android Pleno. Quero te contar um pouco sobre a nossa empresa e sobre a vaga: 

**A Delivery Much:**

A DM, como carinhosamente chamam os muchers, é a maior plataforma de delivery de comida do interior do Brasil. Acreditamos que podemos democratizar a tecnologia levando-a para todos os cantos e, assim, facilitando a vida das pessoas. Afinal, todos precisam comer, não é mesmo? No momento, estamos com mais de 3 milhões de usuários cadastrados, dos quais a grande maioria acessa o app através do seu Android, ou seja, sua habilidade é indispensável para nós! 

**Sobre a vaga:** 

O time de engenharia da DM é o nosso maior time, visto que o aplicativo depende dele para funcionar. O desenvolvedor Android que trabalhar conosco deve ser alguém com espírito de batalha, porque vai ser o grande responsável pelo app. É uma vaga para quem gosta de autonomia, tem experiência e muita vontade de crescer. 

**Requisitos:**

Experiência em Kotlin e Android Studio
Experiência em arquitetura (MVVM, MVP, Clean etc)
Usa ou já usou Git
Conhece Retrofit, Livedata e RxJava, Koin/Dagger
2+ anos de experiência com desenvolvimento Android

**Benefícios:**

-Plano de saúde, Plano odontológico e Seguro de Vida;
-PLR semestral;
-VA/VR Flexível;
-Gympass e Gogood;
-Dayoff no aniversário;
-Investimento em capacitação;
-Parceria com SESC, ACATE e desconto em diversos estabelecimentos; 
-Flexibilidade de horários;
-Licença paternidade e maternidade estendida.

**Salário a combinar**

Podem entrar em contato comigo por aqui ou se inscreverem pelo link:
https://boards.greenhouse.io/deliverymuch/jobs/5185037003

#vemsermucher #tamojunto

![capas-linkedin-GPTW](https://user-images.githubusercontent.com/107579926/175121825-57722244-6888-4221-a35c-c504350f8b27.png)

**Comment by Brunostd** [comment]
[BRUNO_BRITO_UPDATE.pdf](https://github.com/androiddevbr/vagas/files/9114183/BRUNO_BRITO_UPDATE.pdf)
