### ISSUE TITLE
[Remoto] Android Developer Sênior [K2 Partnering Solutions]

### ISSUE THREAD

**Issue by GBarbosa30** [androiddevbr/vagas#2076]
## Importante

Por questões contratuais nosso cliente pediu que o seu nome fosse mantido em sigilo.

# Sobre a empresa

Nosso cliente é um app que possibilita, por meio da tecnologia, serviços de entrega em domicílio e tempo livre, pois seus pedidos de supermercados e lojas especializadas são entregues na sua casa ou onde você preferir. É uma empresa de rápido crescimento que opera no Chile, Brasil, Peru, Colômbia, México, Costa Rica, EUA e Canadá. 

Então, se você quer trabalhar em um ambiente inovador, com cultura de startup, pessoas que amam piadas de tios e são “good vibes”, seu lugar é conosco!

## Descrição da vaga

Estamos procurando um Desenvolvedor Android para se juntar à equipe que desenvolve os aplicativos usados por centenas de milhares de compradores e clientes todos os dias!

**O que você irá fazer?**

- Desenvolver o app utilizado por nossos compradores e clientes.

- Projetar e melhorar as interfaces de usuário.

- Diagnosticar e corrigir bugs críticos que podem impactar negativamente a vida de centenas de usuários.

- Redesenhar e refatorar o código existente.

## Requisitos

**O que você precisa para ter sucesso?**

- Entender o SDK do Android e suas APIs.

- Conhecimento dos princípios de design da interface Android.

- Experiência em trabalhar com a fragmentação do ecossistema Android.

- Familiaridade com as APIs de interação.

- Conhecimento em _Profiling_ e _Debugging_.

- Conhecimento com _Content Providers_ e ORMs.

- Inglês Avançado.

- Experiência mínima de 5 anos.

## Local

Remoto.

## Benefícios

- Salário competitivo;

- Assinatura do app com promoções e descontos exclusivos;
- Planos de seguro odontológico e de saúde;
- Vale-transporte;
- Seguro de vida;
- Creche/Assistência de babá e Assistência para Crianças Excepcionais;
- Programa de Melhoramento do Inglês.
- Vale-refeição no cartão de crédito (flexível) - Você pode comprar suéteres se quiser, nós não nos importamos =)
- Valorizamos a saúde mental de nossos funcionários e, por isso, todo funcionário tem direito a 2 sessões mensais no Zenklub;
- Fazemos parte do "Programa Empresa Cidadã", e oferecemos licença-maternidade de 180 dias e licença-paternidade de 21 dias. (Este benefício é válido também para mães e pais que adotam ou obtêm a custódia judicial da criança, e para casais homossexuais); Amamentação - 1 hora a menos por dia em seu horário de trabalho durante o primeiro ano de vida da criança;
- Também oferecemos licença para:  Mudança de casa - até 2 dias úteis e Casamento / Sindicato - até 7 dias corridos;
- E muitas outras vantagens adicionais!

## Contratação

100% CLT.

## Nossa empresa

K2 Partnering Solutions é uma empresa líder global em recursos humanos de tecnologia consultiva. A K2 Partnering Solutions é uma empresa especializada nos mercados de Enterprise Cloud Corporation e On Premise, Análise Preditiva e Big Data, Mobilidade Social e Corporativa, Cibersecurity, Inteligência Artificial e Robótica.

## Como se candidatar

Por favor envie um email para gbarbosa@k2partnering.com com seu **CV em inglês** anexado - enviar no assunto: Vaga Android Developer

**Obs.: Qualquer dúvida ou mais detalhes sobre a vaga poderá ser consultada por meio do e-mail acima.**

**Comment by davidtcdeveloper** [comment]
@GBarbosa30 As regras do nosso mural de vagas exigem o nome da empresa contratante. A K2 é a empresa contratante ou será a empresa que não teve o nome divulgado?

**Comment by GBarbosa30** [comment]
Olá, boa noite @davidtcdeveloper .

A K2 seria a contratante para um cliente final.
