### ISSUE TITLE
Vaga Android Pleno - Devskin Consultoria de Software 

### ISSUE THREAD

**Issue by juliavtechrecruiter** [androiddevbr/vagas#2082]
Vaga Full Time e Home Office (100% remota) - Pleno/Sênior.

O que esperamos de você:
- Experiência em Android.
- Experiência em Kotlin.
- Conhecimento em Java é um diferencial.

Horas flexíveis de acordo com o contexto do cliente e cerimônias do projeto. Queremos que você se sinta bem trabalhando com a gente!

Acreditamos que a troca de experiência é sempre algo positivo. Comunicação e feedback fazem parte da nossa cultura.

VEM FAZER PARTE DA NOSSA TRIPULAÇÃO!
Voe Alto, Sonhe Alto e seja um Devskin com a gente 👨‍🚀🚀

Link: https://www.linkedin.com/jobs/view/3148544741/?capColoOverride=true

**Comment by davidtcdeveloper** [comment]
@juliavtechrecruiter Recomendamos seguir o template de novas issues para que seja possível classificar a vaga com labels.
