### ISSUE TITLE
Dev Java (ERP)

### ISSUE THREAD

**Issue by gleyceaalves** [androiddevbr/vagas#2083]
**Sobre a oportunidade**

Você será responsável por desenvolver novas funcionalidades para o produto, demandas de legislação, melhorias e manutenção de incidentes. 

O que buscamos para o time Dev Varejo?

Buscamos um profissional comprometido e com muita vontade de aprender. Precisa gostar de ter autonomia, pois no nosso dia a dia precisamos tomar decisões rápidas. 
Você trabalhará no time do Varejo e somos um time responsável por criar e manter as soluções para este segmento.

**O que precisamos?**

- Superior completo ou cursando em Ciências da Computação, Sistemas de Informação ou áreas afins;
- Conhecimento em Java7, Git, Postgres/Linguagens SQL.

**O que pode diferenciar você?**

- Conhecimento em Java8+, Java.Swing, JUnit/Noções de testes automatizados;
- Conhecimento Integração WS;
- Gradle;
- Conhecimento/Vivência em Metodologias Ágeis;
- Conhecimento em Varejo (Retaguarda, PDV);
- Legais (PAF, BlocoX, NFc-e, Nfe).

**Nossos benefícios:**

Você pode conferir os nossos benefícios na página de carreiras, em [www.senior.com.br/carreiras](https://www.senior.com.br/carreiras) 

Link para candidatura: https://s.seniorlabs.io/5vf8PX

Além dos benefícios, contamos com:

- Certificado de “Melhores Empresas para Trabalhar” segundo o ranking do Glassdoor; 
- Profissionais que são referência no mercado de tecnologia; 
- Cursos de aperfeiçoamento e vários conteúdos para potencializar carreiras, por meio da Universidade Corporativa Senior. Conheça mais, [aqui](http://ucsonline.senior.com.br/lms/#/home). 
- Presente em diferentes regiões do Brasil, como São Paulo, Rio de Janeiro, Paraná, Brasília e com matriz localizada no município de Blumenau, considerado como um dos polos de tecnologia com maior desenvolvimento do país. Está na lista de melhores cidades com mais de 100 mil habitantes, segundo o IGM. É, também, a capital nacional da cerveja e a terra da Oktoberfest Blumenau: a maior festa de origem alemã do Brasil.

**Comment by khalilayache** [comment]
@gleyceaalves  Conforme as regras do repositório só é aceito divulgação de vagas relacionadas ao desenvolvimento Android/Mobile. Por isso essa vaga será fechada
