### ISSUE TITLE
UX/UI Designer para Produtos SaaS / Cyber Security

### ISSUE THREAD

**Issue by RADARProfissional** [androiddevbr/vagas#2087]
Buscamos um Designer de UI/UX com foco em produtos SaaS e sites de segurança cibernética. Histórico comprovado de projetar soluções inteligentes e limpas para produtos desafiadores. Que tenha uma visão e requisitos técnicos em arquitetura de informação, wireframes detalhados e protótipos. Experiência de usuário fluente (wireframes) e uma interface de usuário (UI) inovadora. Que realiza pesquisas, através de entrevistas com usuários e testes de usabilidade. Amplo conhecimento de trabalho em grupos multifuncionais, apoiando o processo de desenvolvimento. Experiência prática em tecnologias web e sólida compreensão do ambiente de trabalho ágil.

•	Experiência como UI/UX e em programas de criação (por exemplo: Adobe Photoshop, Sketch, Adobe XD, Adobe Illustrator);
•	Experiência com produtos da plataforma SaaS e sites de segurança cibernética;
•	Conhecimento em CSS/HTML/JS;
•	Conhecimento na ferramenta como Figma, Miro, Invision;
•	Conhecimento de ferramentas de pesquisas e testes de usabilidade, prototipagem de interfaces de usuário, pesquisa de experiência do usuário, discovery, entrevistas com usuários, validação de produtos;
•	Conhecimento de metodologias ágeis, Scrum ou Kanban;
•	Portfólio que comprove boas soluções e qualidades de entrega;
•	Inglês avançado para conversação, leitura e escrita.

Contratação: PJ 
Local: 100% Home Office 
Interessados: Enviar CV para [vagas@radarprofissional.com.br](mailto:vagas@radarprofissional.com.br)

**Comment by khalilayache** [comment]
@RADARProfissional  Conforme as regras do repositório só é aceito divulgação de vagas relacionadas ao desenvolvimento Android/Mobile. Por isso essa vaga será fechada
