### ISSUE TITLE
React Frontend Developer

### ISSUE THREAD

**Issue by RADARProfissional** [androiddevbr/vagas#2088]
Buscamos profissionais com experiência no desenvolvimento e manutenção de aplicações web, que realize a manutenção e criação de novas funcionalidades. Que realize o desenvolvimento de funcionalidades no Front-end e aplique as melhores práticas de documentação de código desenvolvido. Que tenha experiência em desenvolver e sustentar integrações e que busque novas ferramentas e técnicas para a melhoria contínua dos sistemas.
•	Vivência em desenvolver novas funcionalidades nas plataformas web (SaaS) utilizando React JS com Javascript;
•	Experiência em desenvolver e testar aplicativos da Web totalmente responsivos;
•	Experiência em definir, esboçar, projetar e desenvolver, com a equipe, soluções técnicas para sistemas;
•	Experiência com Git, ReactJS, JavaScript, TypeScript, Styled Components, Material UI, CSS e Adobe XD
•	Experiência com metodologias ágeis de desenvolvimento (Agile), testes unitários e boas práticas na criação e consumo de API Restful.
Contratação: PJ 
Local: 100% Home Office 
Interessados: Enviar CV para [vagas@radarprofissional.com.br](mailto:vagas@radarprofissional.com.br)

**Comment by khalilayache** [comment]
@RADARProfissional  Conforme as regras do repositório só é aceito divulgação de vagas relacionadas ao desenvolvimento Android/Mobile. Por isso essa vaga será fechada
