### ISSUE TITLE
[São Paulo] Desenvolvedor Android Sênior

### ISSUE THREAD

**Issue by restevam** [androiddevbr/vagas#21]
## Descrição da vaga

Vaga para atuar em um grande banco brasileiro e ajuda-los na área de pesquisa, desenvolvimento e manutenção dos aplicativos na plataforma Android.

## Local

Matriz da empresa - Zona Oeste da grande São Paulo

## Requisitos
o	Arquitetura Android
o	Desenvolvimento orientado à componentes
o	Android Studio
o	Android Wear
o	Criação de Layouts
o	Git
o	Gradle
o	Support Libraries
o	Google Play Libraries
o	Automação de builds
o	Ferramentas de crashlogs

Diferenciais
- Portfólio de aplicativos publicados (favor fornecer links) e experiencia na publicação e monitoração da loja

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para rafael@solucoes.wf com seu CV anexado ou perfil do LinkedIn - enviar no assunto: Desenvolvedor Android

**Comment by walmyrcarvalho** [comment]
Ajustei o título só pra ficar no padrão descrito no README. :)

**Comment by walmyrcarvalho** [comment]
@restevam Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by restevam** [comment]
Já foi preenchida @walmyrcarvalho . Obrigado pela ajuda ;-)

**Comment by walmyrcarvalho** [comment]
@restevam Eu que agradeço! :)
