### ISSUE TITLE
#Job 100% Remoto para empresa nos Estados Unidos

### ISSUE THREAD

**Issue by sarahaluc** [androiddevbr/vagas#2113]
Interessados escrever para sarah@freethefreela.com

Oi! Somos a [FREE THE FREELA](https://www.freethefreela.com/), uma plataforma que ajuda você a encontrar a oportunidade perfeita nos Estados Unidos ou na Europa, trabalhando de forma 100% remota e com remuneração em dólares 🤓

Estamos buscando desenvolvedores Full Stack, Front-End e/ou Back-End para um projeto super interessante, em empresa dos Estados Unidos, respaldada pela Harvard e MIT. 

Tecnologias buscadas: React js. & Java para front-end; Phyton para Back-end. 
Fundamental ter conhecimentos em AWS Cognito, Amazon Cloudformation, and Amazon S3.

É NECESSÁRIO FALAR INGLÊS

É um diferencial se souber programar no Apache Spark. 

O pagamento é em dólares e o trabalho é full-time, 100% remoto. 

Interessados escrever para sarah@freethefreela.com e se registrar na www.freethefreela.com

Obrigada =D

**Comment by davidtcdeveloper** [comment]
@sarahaluc Este mural de vagas é focado em oportunidades que envolvam desenvolvimento para Android. Como não encontramos nenhuma menção a Android na issue, a mesma será encerrada.
