### ISSUE TITLE
[São Paulo ou interior] [Desenvolvedor Android Pleno (2 anos de experiência no mínimo)] Remoto

### ISSUE THREAD

**Issue by ErickaMB** [androiddevbr/vagas#2116]
[Desenvolvedor Android Pleno (2 anos de experiência no mínimo) e Desenvolvedor iOS Pleno (2 anos de experiência no mínimo)] - Remoto. CLT Pleno: R$ 8 mil a R$ 10 mil / Senior: R$ 11 mil a R$ 13 mil.  Eventualmente haverá reuniões de alinhamento na sede em São Paulo Interlagos. Precisa residir em São Paulo ou interior.

O que precisa?

Os requisitos que essas vagas pedem essencialmente.

Empresa
Atuar num grande banco por uma consultoria internacional.

Benefícios:
R$ 1.5000,00 cartão Flex mensal.
Assistência Médica;
Seguro de vida;
Assistência Odontológica;
Academia
Seguro de vida.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by davidtcdeveloper** [comment]
@ErickaMB As regras do nosso mural de vagas exigem a divulgação do nome da empresa contratante. Esta issue será encerrada até ser editada com o nome.
