### ISSUE TITLE
[Closed][Porto, Portugal] Android Developer at Infraspeak

### ISSUE THREAD

**Issue by Pedrobertucci** [androiddevbr/vagas#2118]
Hi Folks, we’re offering talented #AndroidDevelopers the chance to join our growing, world-class team.

What do we need:

👉 An experienced, curious and enthusiastic developer
👉 Someone who knows the ins and outs of the #Android framework
👉 A person who sleeptalks in #Kotlin
👉 Diamond personality traits, fluent English
👉 Senior Developer
💫The natural ability to crack an awful joke and ride the awkwardness (non-negotiable!)

Project Stack
#Kotlin
#Kmm
#Sqdelight
#JetpackCompose
#CleanArchitecture
#Firebase
#infiniteCoffeeAndBeer

If you don't live in Portugal and want to relocate, we also help you with:

🇵🇹 Visa Sponsor
🏠 First month for relocation to Portugal
💰Competitive salary package

Sounds good?! 😉

Apply here 👇
https://careers.infraspeak.com/jobs/1914867-android-developer

**Comment by Bruno-Casado** [comment]
@davidtcdeveloper essa vaga está fechada atualmente no site deles
