### ISSUE TITLE
[Stockholm, Sweden] Agile Lead - Android Developer Senior na [Be iT Overseas]

### ISSUE THREAD

**Issue by Camismor** [androiddevbr/vagas#2124]
## Descrição da vaga

As a technical and thought leader with a strong agile mindset, you will be joining a team of talented developers and testers from diverse backgrounds who are passionate about Android Application development. 

You'll be responsible for driving the team's deliveries as well as improving the team's agile processes, collaborating with the Product Owners, stakeholders and other teams. 

You should have prior hands-on technical experience in delivering Android applications. 

You love the idea of working with a mission-critical product with millions of end-users and zero downtime. 

Being experienced in Agile and Lean development, you enjoy responsibility and care as much about developing teams agile process as developing Android App. 

In your role communication, coordination and team spirit are key components in getting things done. 

We promote an open and proactive culture where our developers and testers are encouraged to learn and contribute in ways outside the usual development work. This can include areas such as participating in different development academies, conferences, public speaking, and leadership among others. 

## Local

Stockholm, Sweden (relocated position)

## Requisitos

- Kotlin
- Android Jetpack components
- MVVM design pattern
- Retrofit to connect to Rest services
- Hilt for dependency injection
- Git
- Continuous delivery
- Best development practices
- Agile and lean values

Diferenciais

- International job opportunity

## Contratação

PJ a combinar

## Nossa empresa

Our client is a Leader of online betting site

## Como se candidatar

email: camilla.moriya@beitoverseas.com
https://forms.clickup.com/31110733/f/xndjd-5763/GNLQ7TZIX2MEDOVBLM 
https://beitoverseastech.gupy.io/jobs/3165743

**Comment by davidtcdeveloper** [comment]
@Camismor The rules of this job board require the name of the hiring company. This issue will be closed until it gets edited with the name of the company.

**Comment by Camismor** [comment]
@davidtcdeveloper This is a confidential position, because my client is replacing the professional who is there. So, is there any chance to evaluate in that case?

**Comment by davidtcdeveloper** [comment]
@Camismor The community defined the rules for this mural so I cannot open an exception to this rule.

**Comment by Camismor** [comment]
@davidtcdeveloper Thanks
