### ISSUE TITLE
[Amsterdam][Semi-presencial] Senior Android Developer @ Polaroid 📸

### ISSUE THREAD

**Issue by rsicarelli** [androiddevbr/vagas#2130]
### About us: Iconic brand, tiny company.
Polaroid was founded in 1937 by one of the most seminal innovators of the 20th century, Edwin Land. His motto was, “don't undertake a project unless it is manifestly important and nearly impossible.” In 2008, Polaroid shuttered its last factory, but a group of diehard fans came together as The Impossible Project to save the instant film. Over 10 years later that start-up acquired what was left of Polaroid and today we’re again a small group of people passionate about empowering creators to change the world in the name of Polaroid.

### What we are building: Tools for creators.
Throughout its 80-year history, Polaroid was at its best when we made tools for people to express themselves, push boundaries and move the culture forward. In the next decade, we are getting back to this purpose. We're not solving small problems, and we're not addressing a small market; our goal is to make products that will make the world more meaningful and human.

### Job description:
As Senior Android Developer you are responsible for developing our Polaroid apps for mobile devices powered by the Android operating system. Your primary focus developing Android applications. As a Senior Android Engineer, you will be responsible for developing and maintaining our Polaroid apps for Android within a multidisciplinary team composed of iOS, QA, PO, and of course, your Android colleagues.

### Responsibilities:
Accountable for designing, building, and maintaining our Android apps
 
### Basic Qualifications and Mindset:
- 5+ years of experience in Software Development with at least 3 years of experience in Android Development
- 2+ years experience with the Kotlin language
- Familiar with the Agile methodology
- Teamwork and passion for exchanging knowledge
- Fluent or advanced in English

### Nice to have:
- Enthusiastic about art and creativity 
- Open-minded and not afraid to come up with new ideas to make things better
- Effective communication skills
- Willing to exchange  constant constructive feedback

### Some technologies and practices that we follow:
- Multi-project applications (single codebase with multiple modules)
- Jetpack Compose is fully adopted 🥳 in our [new app](https://play.google.com/store/apps/details?id=com.polaroid.music) and adopting into our [photo app](https://play.google.com/store/apps/details?id=com.polaroidoriginals.po1)
- Trunk-based development
- Scrumban as our development framework
- MVVM / MVI Architecture

### What to expect:
- This is a full-time role based in our Amsterdam office in a hybrid mode - once or twice per week in the office
- Work with a distributed team in the same timezone (Spain, Germany, Poland)
- Visa sponsorship
- Fixed relocation package
- Free Polaroid Films every month 📷 

## Como se candidatar
Essa vaga é pra ser meu par! Se tiver qualquer dúvida, só me pingar no Slack ou no rodrigo.sicarelli@polaroid.com

Para se aplicar:
1. [Nossa carreers page](https://www.polaroid.com/careers-senior-android-developer-amsterdam-20220303) or
2. [Linkedin](https://www.linkedin.com/jobs/view/3448777618)

**Comment by Bruno-Casado** [comment]
@davidtcdeveloper essa vaga também está fechada

**Comment by rsicarelli** [comment]
> @davidtcdeveloper essa vaga também está fechada

opa, essa vaga continua aberta!

**Comment by Bruno-Casado** [comment]
> > @davidtcdeveloper essa vaga também está fechada
> 
> opa, essa vaga continua aberta!

E como aplica? Os dois links parece fechada =/

**Comment by rsicarelli** [comment]
> > > @davidtcdeveloper essa vaga também está fechada
> > 
> > 
> > opa, essa vaga continua aberta!
> 
> E como aplica? Os dois links parece fechada =/

obrigado por reportar, atualizei o link da vaga!
