### ISSUE TITLE
(Rio de Janeiro , RJ)DESENVOLVEDOR ANDROID PLENO -BillingPay

### ISSUE THREAD

**Issue by CristinaAlliage** [androiddevbr/vagas#2131]
Estamos selecionando Desenvolvedor Android Pleno, para atuar com desenvolvimento e/ou aperfeiçoamento de softwares voltados para gestão e monitoramento de transporte de passageiros; desenvolvimento de novas funcionalidades para aplicação mobile utilizando Android Java; definição e criação de novos componentes.

Experiência comprovada em desenvolvimento Android.  
Conhecimento com Software embarcado, será um diferencial;

LOCAL DE TRABALHO: CENTRO/RIO DE JANEIRO

VAGA: PRESENCIAL

Enviar Currículo para : rh@alliage.com.br

**Comment by davidtcdeveloper** [comment]
@CristinaAlliage A empresa contratante é a BillingPay? As regras do nosso mural de vagas exigem a divulgação do nome da empresa contratante, por isso precisamos dessa confirmação.

**Comment by CristinaAlliage** [comment]
Olá,

Mas eu coloquei no título.


Cristina Pires​

Consultor de RH


T: +55 (21) 2212.9800
T: +55 (11) 3192.3898

RJ – Av. Rio Branco, 181 – 18º andar (parte)

SP - Av. B. Faria Lima, 1461 - 4º andar
www.alliage.com.br<http://www.alliage.com.br/>



Alliage é uma empresa diferenciallgroup.com.br


________________________________
De: David Tiago Conceição ***@***.***>
Enviado: segunda-feira, 7 de novembro de 2022 16:15
Para: androiddevbr/vagas ***@***.***>
Cc: RH Alliage ***@***.***>; Mention ***@***.***>
Assunto: Re: [androiddevbr/vagas] (Rio de Janeiro , RJ)DESENVOLVEDOR ANDROID PLENO -BillingPay (Issue #2131)


@CristinaAlliage<https://github.com/CristinaAlliage> A empresa contratante é a BillingPay? As regras do nosso mural de vagas exigem a divulgação do nome da empresa contratante, por isso precisamos dessa confirmação.

**Comment by davidtcdeveloper** [comment]
Certo, queria apenas confirmar esta informação.
Ainda sobre a issue, recomendamos que ela siga o template para novas issues para que seja possível classificar com labels e facilitar a pesquisa.

**Comment by CristinaAlliage** [comment]
Desculpe vou tentar ser mais assertiva.  É a primeira vez que uso GitHub.

**Comment by davidtcdeveloper** [comment]
Sem problemas. Se quiser usar o template, fique a vontade pra encerrar esta issue e criar uma nova seguindo o template.

**Comment by CaNSantos** [comment]
Oi Davi, estou publicando a primeira vez aqui também no github. Onde encontro o novo template? Por que ponde publiquei não encontrei a opção de acrescentar as labels. Pode me ajudar?

**Comment by davidtcdeveloper** [comment]
@CaNSantos Ao criar uma nova vaga, ela virá com um modelo pré-preenchido, basta completar. Este é o template que eu comentei. Sobre as labels, elas são adicionadas pela equipe de moderação nas vagas que seguem o template e tem as informações necessárias.
