### ISSUE TITLE
[Remoto] Desenvolvedor Android [SENIOR] | WESPER/TECLA

### ISSUE THREAD

**Issue by BeatrizRecruiterTecla** [androiddevbr/vagas#2133]
Ready for this challenge? Sr Android Opportunity (UP to USD 9k/month)

Wesper is a NY-based company with the mission to provide clinical-grade insights that allows its users to improve their sleep health from start to finish. In order to help more people every day, they are looking for a Sr Android Developer to join their team, check it out:

This role is **100% remote and full-time.** Salary is up to **USD 9K** monthly (based on experience) + great perks like Flexible PTO, Holidays Off, and more!

What do you think? Check out the full Job Description here:

https://app.tecla.io/job?id=2053&r=1XQM

If you are interested, please apply to the link above and i will work to schedule a chat with you and Wesper.

Please feel free to reach out if you have any questions! beatriz.oliveira@tecla.io

Best,

Beatriz Oliveira
Sourcing Specialist at TECLA

**Comment by davidtcdeveloper** [comment]
@BeatrizRecruiterTecla We highly recommend using the issue template to fill new issues. That would allow us adding labels making search easier.
