### ISSUE TITLE
[REMOTO] desenvolvedor pleno firmware ANDROID para notebook ALLWINNER A133

### ISSUE THREAD

**Issue by fitandre** [androiddevbr/vagas#2137]
[REMOTO] desenvolvedor pleno firmware ANDROID para notebook ALLWINNER A133. Contato andre@meyerpflug.com.br

**Comment by davidtcdeveloper** [comment]
@fitandre As regras do nosso mural de vagas exigem a divulgação do nome da empresa contratante. Esta issue será encerrada até que o nome seja divulgado.
