### ISSUE TITLE
[Brasil] Pessoa Desenvolvedora Android [Pleno | Senior] Global Hitss

### ISSUE THREAD

**Issue by CapassoLevinia** [androiddevbr/vagas#2138]
Requisitos necessários:

Ensino superior completo;
Inglês e/ou Espanhol (para leitura e escrita);
Forte conhecimento do Android SDK, diferentes versões do Android e como lidar com diferentes tamanhos de tela;
Familiaridade com APIs RESTful para conectar aplicativos Android a serviços de back-end;
Conhecimentos sólidos dos princípios, padrões e práticas recomendadas do design da IU do Android;
Experiência com armazenamento offline, segmentação e ajuste de desempenho;
Familiaridade com APIs de mensagem na nuvem e notificações push (google firebase);
Entendimento dos princípios de design e diretrizes de interface do Google para Android;
Compreensão proficiente de ferramentas de controle de versão de código, como o Git;
Familiaridade com integração contínua;
Comprometimento com prazos e níveis de qualidade;
Flutter;
Desenvolvimento para plataforma iOS – Nativo;
Experiência em desenvolvimento de software usando metodologias ágeis;
Principais atribuições:

Foco principal será no desenvolvimento e manutenção de aplicativos voltados para um grande número de dispositivos;
Planejar e desenvolver aplicações móveis, nativas e híbridas;
Confecção de aplicativos que suportem a lógica de apresentação e negócio.

CLT | Modelo Hibrido 2x por semana |
Contato:
Le Capasso🚀
Tech Recruiter RPO - Global Hitss
(11) 96959-1775
[levinia.capasso.3@globalhitss.com.br](mailto:levinia.capasso.3@globalhitss.com.br)

**Comment by davidtcdeveloper** [comment]
@CapassoLevinia Recomendamos fortemente seguir o template de criação de novas issues para permitir a classificação com labels.
