### ISSUE TITLE
[Belo Horizonte - MG] Android Developer na [JP&F CONSULTORIA]

### ISSUE THREAD

**Issue by 123kjp** [androiddevbr/vagas#2155]
## Descrição da vaga

Estamos buscando um talento para um cliente do segmento de meios de pagamentos.

## Local

Híbrido - Belo Horizonte MG - Centro 

## Benefícios

- CONVÊNIO ODO.
- CONVÊNIO MÉDICO 
- VT
- VR
- PLR
- AUXILIO CRECHE
- SEGURO DE VIDA
- AUXÍLIO ESTUDO

## Requisitos

Obrigatórios

- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados
Opportunity - Software Engineer.

Experience in RTOS and Linux / Android operating systems, Experience in embedded projects with Cortex ARM M and A processors, Experience with communication interfaces, with knowledge of EMV, MIFARE and ISO14443 Kernels. Advanced English.

Salário: A combinar.

## Contratação
CLT efetivo 

## Nossa empresa

A JP&F Consultoria é especializada em recrutamento, seleção e gestão estratégica em Recursos Humanos.

## Como se candidatar

Por favor envie um email para rh@jpefconsultoria.com.br com seu CV anexado - enviar no assunto o título da vaga.

**Comment by davidtcdeveloper** [comment]
@123kjp As regras do nosso mural de vagas exigem a divulgação da empresa contratante. A contratante é a JP&F CONSULTORIA?

**Comment by davidtcdeveloper** [comment]
Issue será fechada até que a dúvida sobre a contratante seja resolvida.
