### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Android Sênior na Cora (Vaga Afirmativa Para Pessoas LGBTQIAPN+)

### ISSUE THREAD

**Issue by 1jGabriel** [androiddevbr/vagas#2175]
## Descrição da vaga

Estamos em busca de uma pessoa desenvolvedora Android talentosa e comprometida para fazer parte da nossa equipe de tecnologia na Cora, uma fintech que oferece serviços de conta digital PJ para pequenas e médias empresas.

Como pessoa desenvolvedora Android na Cora, você será responsável por desenvolver e aprimorar nosso aplicativo, garantindo uma experiência excelente aos nossos clientes. Trabalhará em conjunto com uma equipe multidisciplinar, que valoriza a colaboração e está sempre disposta a compartilhar conhecimentos.

## Local

Remoto 

## Benefícios

- Benefícios flexíveis no cartão [Flash](https://flashapp.com.br/colaboradores/);
- Trabalho 100% Remoto
- Plano de Saúde 100% custeado pela Cora (com inclusão de dependentes)
- Plano Odontológico (Desconto de pequeno valor em folha)
- Auxílio Aprendizagem de R$ 3.000 por ano para cursos, livros, pós graduação, etc (para profissionais em início de carreira, o benefício é de R$ 4.000)
- Licença maternidade e paternidade estendidas
- Parceria com Gympass e Zenklub
- Day Off de aniversário
- Estrutura para home office: fornecimento de equipamento completo (notebook com suporte, monitor extra, teclado e mouse), possibilidade de compra de cadeira, escrivaninha e apoio para pé;
- Auxílio home office mensal;
- Convênio com a plataforma Woba para você poder trabalhar em vários Coworkings em todo o Brasil

## Requisitos

Obrigatórios

- Domínio de Kotlin e de boas práticas de desenvolvimento (Solid);
- Domínio de padrões de arquitetura e Design Patterns (MVVM, Clean, etc);
- Experiência com corrotinas ou similares (Flow, RxJava, etc)
- Conhecimento de ferramentas de injeção de dependência (por aqui usamos Koin, mas não precisa ser essa);
- Integração de APIs e com o back-end;

Desejáveis
- Experiência trabalhando com Design System, Custom View;

Diferenciais

- Contribuição opensource
- Experiência com Compose UI

## Contratação

CLT

## Nossa empresa

Somos uma fintech. A Cora é uma conta digital PJ que busca apoiar e simplificar a rotina de pequenas e médias empresas, libertando pessoas empreendedoras das papeladas e taxas abusivas dos bancos tradicionais. 

Em 4 anos, já somamos cerca de 400 Corajosers trabalhando de forma 100% remota para simplificar a rotina de mais de 750 mil clientes em todo o país.

Temos muito orgulho da nossa cultura e do nosso jeito de trabalhar. Trabalhamos para criar um ambiente com segurança psicológica, flexibilidade, inclusão e desenvolvimento de pessoas. 

Buscamos por pessoas colaborativas e humanas, que pensem nas outras pessoas de verdade. Pessoas dinâmicas e flexíveis, pois nossos problemas são complexos e muitas vezes não temos todas as respostas. Pessoas dispostas a se desenvolverem todos os dias para nos ajudar a construir a Cora que queremos.

 Vem ser Corajoser?

## Como se candidatar

https://boards.greenhouse.io/cora/jobs/6813940002

**Comment by alcinolago** [comment]
O site que consta no link mostra que a vaga não esta mais disponivel.

**Comment by 1jGabriel** [comment]
@alcinolago no momento estamos com uma fila e por enquanto a vaga ta fechada
