### ISSUE TITLE
Software engineer 

### ISSUE THREAD

**Issue by 123kjp** [androiddevbr/vagas#2187]
Conhecimento de modelos de terminais POS, MPOS, SmartPOS e TEF. Conhecimento da mensageria ISO8583, regras EMV e ABECS. Elaboração de especificações com funcionalidades e requisitos técnicos. Validação de versões de aplicações disponibilizadas pelo fornecedor. Análise de logs, problemas e incidentes. Suporte as áreas de Produtos e Operações e clientes. Acompanhamento de piloto em produção com monitoramento de dados estatísticos. Análise e controle de atividades. Vivência em instituições financeiras ou tecnologia em pagamentos (TEFhouses, facilitadores, subadquirências ou adquirências).

BENEFÍCIOS: Assistência Médica / Medicina em grupo, Tíquete Alimentação, Vale Transporte, Participação nos lucros SALÁRIO: A Definir. REGIME DE CONTRATAÇÃO: CLT / Efetivo. LOCAL DE TRABALHO: Uberlândia – Minas Gerais. MODALIDADE DE TRABALHO: Remoto (Duas vezes na semana na empresa).

Interessados enviar o CV para vagas@jpefconsultoria.com.br

**Comment by davidtcdeveloper** [comment]
@123kjp Este mural de vagas é focado em oportunidades para desenvolvimento Android. É obrigatório também a divulgação do nome da empresa contratante.
Por estes motivos, a issue será encerrada.
