### ISSUE TITLE
[Remoto] Android Developer na Torc

### ISSUE THREAD

**Issue by Lucca-C** [androiddevbr/vagas#2188]
## Panorama do mercado

Aumente suas chances de contratação conhecendo mais do panorama do mercado Android: http://panorama.androiddevbr.org

Remova o bloco acima antes de divulgar a vaga.

## Descrição da vaga

Esta posição é para uma empresa dos EUA que está contratando desenvolvedores(a) do brasil.

Nesta função, você vai desenvolver código Android, focando em casos de uso complexos. Além disso, vai colaborar com as equipes de Produto, UX e Engenharia para aprimorar nossas funcionalidades. Você também vai orientar membros da equipe regularmente. O escopo do desenvolvimento vai além de simples funcionalidades, incluindo melhorias na arquitetura básica.

## Local

Remoto

## Requisitos

Obrigatórios

Inglês fluente 
6+ anos de experiência em desenvolvimento de software, com pelo menos 6+ anos em design/desenvolvimento de aplicações móveis Android
5+ anos de experiência com frameworks modernos de desenvolvimento Android, como o Jetpack
5+ anos de experiência trabalhando com equipes multifuncionais, como design, produto e equipes de dados, para entregar ótimas experiências ao usuário
2+ anos de experiência influenciando grandes organizações sobre melhores práticas em desenvolvimento móvel Android
2+ anos de experiência em acessibilidade. Experiência em telemetria e observabilidade além do Firebase
2+ anos demonstrando um desejo de construir testes desde o início com experiência em desenvolvimento TDD. Entrega contínua em mobile, revisão de código, análise estática, integração contínua, automação e testes funcionais (usando XCUI)

Desejáveis

- Experiência em gerir múltiplas prioridades em ambiente acelerado. Conhecimento em BFF, GraphQL, e programação reativa Android. 
- Integração com frameworks e SDKs terceiros. Experiência em OAuth e tokens. 
- Análise estática e dinâmica. Contribuições significativas em apps na Play Store.

## Como se candidatar

https://lp.torc.dev/jobs/android-developer-2

**Comment by coderReview** [comment]
Bom dia. Se tiverem alguma dúvida ou preocupação com relação a vaga, podem me perguntar aqui. Att.

**Comment by coderReview** [comment]
Caso queriam, podem usar o link abaixo para registrar diretamente e poder ganhar USD250. Att.

Link para registro: https://platform.torc.dev/#/r/xhblcov/cp

Link para a notícia da vaga: https://www.linkedin.com/posts/nikitajaintc_latamjobs-braziljobs-gigeconomy-activity-7121194731153350656-7-i5?utm_source=share&utm_medium=member_desktop

**Comment by brunomilhan** [comment]
> Bom dia. Se tiverem alguma dúvida ou preocupação com relação a vaga, podem me procurar. Att.

Qual o seu email para contato?

**Comment by coderReview** [comment]
Pode usar o link https://platform.torc.dev/#/r/xhblcov/cp para se registrar e se candidatar a vaga. A dona da vaga Nikita Jain - https://www.linkedin.com/posts/nikitajaintc_latamjobs-braziljobs-gigeconomy-activity-7121194731153350656-7-i5?utm_source=share&utm_medium=member_desktop - pode ser alcançada no linked in
