### ISSUE TITLE
[São Paulo] Android Developer na Nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [androiddevbr/vagas#2193]
## Descrição da vaga

Projeto de desenvolvimento de novos app e melhorias em App já existentes 

## Local

Hibrido, podendo ser 1 vez por semana ( Não será todas as semanas)   São Paulo - Berrini

## Requisitos

Obrigatórios

Android: Kotlin, Java, Android Studio, Jetpack Compose, Room, ViewModel, LiveData, Retrofit, Gson, Mockito, Espresso

Desejáveis
Desenvolvimento ágil
Testes automatizados

Diferenciais

Desenvolvimento Web
React
Node
Next.js
Typescript
Javascript
HMTL E CSS

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para helen.matos@nexmuv.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by MessiasLima** [comment]
> Hibrido, podendo ser 1 vez por semana

1 vez por semana em casa, ou 1 vez por semana no escritório?
