### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Android Pleno na Cora

### ISSUE THREAD

**Issue by 1jGabriel** [androiddevbr/vagas#2195]
## Descrição da vaga

Estamos buscando uma pessoa desenvolvedora Android nível pleno, para compor uma das nossas squads aqui na Cora

## Local

Remoto

## Benefícios

- Benefícios flexíveis no cartão [Flash](https://flashapp.com.br/colaboradores/);
- Trabalho 100% Remoto
- Plano de Saúde 100% custeado pela Cora (com inclusão de dependentes)
- Plano Odontológico (Desconto de pequeno valor em folha)
- Auxílio Aprendizagem de R$ 3.000 por ano para cursos, livros, pós graduação, etc (para profissionais em 
início de carreira, o benefício é de R$ 4.000)
- Licença parental estendida para gestantes e não gestantes
- Parceria com Gympass e Zenklub
- Day Off de aniversário
- Estrutura para home office: fornecimento de equipamento completo (notebook com suporte, monitor extra, teclado e mouse), possibilidade de compra de cadeira, escrivaninha e apoio para pé;
- Auxílio home office mensal;
- Convênio com a plataforma Woba para você poder trabalhar em vários Coworkings em todo o Brasil

## Requisitos

- Conhecimento de Kotlin e de boas práticas de desenvolvimento (Solid);
- Experiência com integração de APIs e com o back-end (utilizamos retrofit);
- Conhecimento de padrões de arquitetura e Design Patterns (MVVM, Clean, etc);
- Conhecimento em corrotinas (State Flow, etc)
- Conhecimento em Compose UI
- Conhecimento em Jetpack navigation
- Conhecimento de ferramentas de injeção de dependência (por aqui usamos Koin, mas não precisa ser essa);
- Experiência trabalhando com Design System, Custom View;
- Desejável pelo menos 3 anos de experiência trabalhando com Android

## Contratação

CLT

## Nossa empresa

Somos uma fintech. A Cora é uma conta digital PJ que busca apoiar e simplificar a rotina de pequenas e médias empresas, libertando pessoas empreendedoras das papeladas e taxas abusivas dos bancos tradicionais. 

Em 4 anos, já somamos cerca de 400 Corajosers trabalhando de forma 100% remota para simplificar a rotina de mais de 1 milhão clientes em todo o país.

Buscamos por pessoas colaborativas e humanas, que pensem nas outras pessoas de verdade. Pessoas dinâmicas e flexíveis, pois nossos problemas são complexos e muitas vezes não temos todas as respostas. Pessoas dispostas a se desenvolverem todos os dias para nos ajudar a construir a Cora que queremos.

 Vem ser Corajoser?

## Como se candidatar

Por favor se inscrever aqui no [link](https://grnh.se/c65fe3362us)

**Comment by joaoeudes7** [comment]
Enviado! :)
