### ISSUE TITLE
[São Paulo] Desenvolvedor Android Pleno/Sênior | GingaOne

### ISSUE THREAD

**Issue by Vivianematos** [androiddevbr/vagas#22]
## Local
Berrini - Zona Sul.
Alphaville

## Benefícios
frigobar sempre cheio :P
sala de jogos
Para CLT: 
Assistência Médica
Odontológica
Vale Refeição
Vale Transporte

## Requisitos

Obrigatórios
Grande conhecimento do SDK do Android.
Grande conhecimento das principais libraries, v4 e v7.
Consumo de API rest .
Usar Android Studio.
Usar Git.
Trabalhar com metodologia Scrum.
Experiência em Integração Contínua.

Desejável
Conhecimento sobre os novos padrões do Material Design.

## Contratação

PJ 

## Nossa empresa

Aqui na GingaOne somos um grupo de profissionais extremamente qualificados, dedicados e apaixonados pelo que fazem, que acreditam no poder transformador da tecnologia e que querem deixar sua marca neste admirável mundo novo. 

## Como se candidatar

Por favor envie um email para viviane.matos@gingaone.com com seu CV anexado com Pretensão PJ.
 - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
Ajustei o título só pra ficar no padrão descrito no README. :)

**Comment by Vivianematos** [comment]
Ok, obrigada :)

*Viviane Matos Bonifacio*
Recursos Humanos

+ 55 11 5505 2923
+ 55 11 97653-6975

Skype: viviane.bonifacio2
www.gingaone.com


2016-05-12 15:34 GMT-03:00 Walmyr Carvalho <notifications@github.com>:

**Comment by walmyrcarvalho** [comment]
@Vivianematos Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by Vivianematos** [comment]
Oi Desculpe,

Já foi finalizada.

*Viviane Matos Bonifacio*
Recursos Humanos

+ 55 11 5505 2923
+ 55 11 97653-6975

Skype: viviane.bonifacio2
www.gingaone.com


2016-07-28 11:51 GMT-03:00 Walmyr Carvalho <notifications@github.com>:

**Comment by walmyrcarvalho** [comment]
@Vivianematos Beleza, fechando!
