### ISSUE TITLE
VAGA APAGADA

### ISSUE THREAD

**Issue by scenelyn23** [androiddevbr/vagas#2202]
VAGA APAGADA

**Comment by khalildevbr** [comment]
Hey @scenelyn23!
Agradecemos o post da vaga no nosso repositório, porém, ela vai precisar ser apagada! Aqui nesse repositório, bem como no canal de vagas do slack da comunidade só são aceitas divulgação de vagas relacionadas com Android e/ou Mobile. Ou seja, apenas vagas de Android Nativo e Mobile Hibrido (Flutter, React Native, etc).

Os posts no canal de vagas do slack já foram apagados! 
Pedimos desculpas e te orientamos a procurar, talvez, a comunidade mais propícia para vagas de DevOps, ok?
