### ISSUE TITLE
[Remoto] Desenvolvedor Mobile Sr no Grupo Otimiza

### ISSUE THREAD

**Issue by grupootimiza** [androiddevbr/vagas#2220]
Desenvolvedor Mobile Sr no Grupo Otimiza

Somos especialistas em sistemas para o segmento de inspeção e vistoria veicular, e nossas soluções são as mais completas e modernas

Atividades:
Realizar a migração de um aplicativo em Xamarin Android para Android Nativo (Java). Após migração realizar melhorias, e manutenção da aplicação, fazendo eventuais alterações necessárias, visando atender às necessidades dos usuários.
Analisar, desenvolver e implementar melhorias nos sistemas e aplicações, estabelecendo o fluxo e os procedimentos necessários para a transformação dos dados de entrada no processo requerido pelo usuário / demandante, de maneira eficiente, segura e de acordo com os objetivos estabelecidos.

REQUISITOS 
Ensino Superior Completo em Ciência da Computação, Sistemas de Informação, ou áreas afins.
Pós Graduação relacionada a área de desenvolvimento.
4 a 6 anos de experiência 
Experiência com Android e IOS
Experiência com a linguagem Java para desenvolvimento Android.
Conhecimento API-REST e protocolos de comunicação.
Experiência, C# e Xamarin.
Capacidade de pesquisa de novas tecnologias e rápido aprendizado

Modelo Híbrido para Belo Horizonte e Região -Remoto para outras localidades

Benefícios:
Plano de Saúde SulAmérica para colaborador e dependentes (cônjuge e filhos) cobertura nacional.
Assistência Odontológica
Swile Food no valor de R$ 42/dia (com bandeira Mastercard, é aceito em restaurantes, cafés, apps de delivery, supermercados, açougues, padarias etc.)
Day off + presente personalizado de aniversário
Participação nos Lucros e Resultados (equivalente a um salário do colaborador)
Presente especial de casamento
Auxílio-fralda para os bebês recém-nascidos da Otimiza
Licença-maternidade e paternidade
Vale-transporte ou vale-mobilidade
Lanches na empresa com café, chocolate quente, chá e snacks 
Vale-transporte ou vale-mobilidade
Convênio farmácia
Horário: De segunda a sexta de 08:00 as 17:00 ou 09:00 as 18:00 (40 horas semanais)
Regime de contratação: CLT (Efetivo)
Salário: Á combinar

**Comment by AleksGustavo** [comment]
[Aleksander - Curriculo.pdf](https://github.com/user-attachments/files/16593929/Aleksander.-.Curriculo.pdf)
