### ISSUE TITLE
Desenvolvedor Android Pleno - Banco Neon

### ISSUE THREAD

**Issue by RBJUR** [androiddevbr/vagas#224]
## Desenvolvedor Android - Pleno

Banco Neon

Quer fazer  parte do time que está desenvolvendo um app incrível para facilitar a vida financeira das pessoas?
Buscamos um profissional seja capaz de entregar um produto com requintes avançados de UX utilizando animações e navegação fluída.

## Localização: Pinheiros – São Paulo/SP

Remoto ou Escritório São Paulo - Vila Olímpia

## Requisitos

Obrigatórios
- 2+ anos em desenvolvimento de aplicativos nativos Android.
- Conhecimentos em Java;
 - Boas noções em animações;
- Experiência no uso de Web Services (REST, JSON/XML);
- Ter preocupação com a parte visual dos aplicativos;
- Adaptação de layouts para diferentes tamanhos de telas;
- Design Patterns.

Diferenciais
- MVP
- Links com código no github e ou apps publicadas;
- Ter trabalhado com jogos;
- Kotlin.

## Contratação

CLT a combinar

## Como se candidatar

Mande seu CV para seja@timeneon.com.br com o assunto “Dev Android”

**Comment by rbispo21** [comment]
eu vi essa vaga no linkedin, mandei mensagem e informaram que a vaga não pode ser remota, apenas presencial

**Comment by pedrofsn** [comment]
@RBJUR a vaga ainda está aberta? É somente presencial como o @rbispo21 fcomentou ou também aceitam remoto?
