### ISSUE TITLE
[Campinas e São Paulo] Programa Jovens Profissionais de TI da Indra 2017

### ISSUE THREAD

**Issue by CesarNog** [androiddevbr/vagas#232]
A Indra Company é uma companhia global de tecnologia com mais de 20 anos de atuação no Brasil, focada em inovação e talento e líder em soluções e serviços de alto valor agregado para os setores de Transporte e Tráfego, Energia e Indústria, Administração Pública e Saúde, Serviços Financeiros, Segurança e Defesa e Telecomunicações e Mídia, entre outros.

Operamos em 148 países e contamos com mais de 37.000 profissionais no mundo, focados em desenvolver soluções inovadoras aos nossos clientes.

Jovens Profissionais de TI - 2017

Se você está na faculdade, busca desafios, conhecimentos e quer construir uma carreira de sucesso com o que há de mais inovador no mercado de Tecnologia, faça parte do Programa de Jovens Profissionais da Indra Company.

Pré-Requisitos:
Recém formados e estudantes dos cursos de Graduação e Tecnólogos: Engenharia da Computação, Ciência da Computação, Análise de Sistemas, Tecnologia da Informação e correlatos.

Idiomas:
Será considerado diferencial o conhecimento em Inglês e Espanhol.

Remuneração inicial: 
R$1.880,00 (Mensal - CLT)

Durante o programa os Jovens Profissionais passarão por 4 avaliações com possibilidade de aumento de até 60% na remuneração conforme desempenho individual no programa.

Carga Horária: 
Período Integral de Segunda a Sexta-feira.

Etapas do Processo:
• Inscrições e Testes On line (Raciocínio Lógico, Inglês e Espanhol*)
• Dinâmica de Grupo
• Entrevista Individual 

*Após realizar os testes não esqueça de "Confirmar a sua Candidatura" no site.

Vagas Disponíveis: 
•São Paulo – SP (Região de Santo Amaro)
•Campinas – SP

Início Previsto:
•São Paulo – SP Julho/17
•Campinas – SP Agosto/17

Benefícios:
• Assistência Médica; 
• Assistência Odontológica; 
• Vale-refeição; 
• Vale-transporte;
• Seguro de Vida; 

Todas as etapas serão eliminatórias, portanto dê o melhor de si em cada atividade. 
Para acompanhar as etapas do processo de seleção fique atento aos seus e-mails, pois nossa comunicação será online.

Boa sorte!

**Comment by davidtcdeveloper** [comment]
Oi @CesarNog 
Este mural de vagas é voltado para vagas para desenvolvedores Android.
Como o texto não faz nenhuma referência para Android, irei encerrar a issue.
Fique à vontade para postar outras oportunidades para Android.

**Comment by orafaaraujo** [comment]
Esta oportunidade contempla tecnologia Android?

Att,
Rafael de Araújo

Em 6 de julho de 2017 15:47, Cesar Augusto Nogueira <
notifications@github.com> escreveu:

**Comment by CesarNog** [comment]
Olá pessoal, boa tarde.

Esta vaga também contempla tecnologia Android e Android Wear!

**Comment by CesarNog** [comment]
Por favor peço que reabram a ISSUE, e se possível me permitam adicionar labels nela também de CLT

**Comment by davidtcdeveloper** [comment]
Encerrei a issue porque não há informações sobre Android ou sequer Mobile.
Vou reabrir a issue, só peço que adicione essas informações sobre Android para que a vaga faça sentido no nosso mural.

**Comment by CesarNog** [comment]
Obrigado!

**Comment by davidtcdeveloper** [comment]
Como a issue não foi editada e ainda não faz referência alguma a tecnologia Android, estou encerrando a mesma.
À disposição para mais informações.

**Comment by CesarNog** [comment]
Opa, bom dia.

Issue editada! =)
