### ISSUE TITLE
VAGAS URGENTE: DESENVOLVEDOR JAVA SÊNIOR 

### ISSUE THREAD

**Issue by RADARProfissional** [androiddevbr/vagas#233]
A Radar Profissional, Consultoria de Recrutamento & Seleção e Terceirização de mão de obra, busca profissionais para atuar em um dos nossos clientes. 

Requisitos:  
•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Experiências com: Java, JavaScript, CSS3, Web Services, APIs RESTful e SOAP, Application Servers (tomcat, Jboss e/ou Websphere), Frameworks MVC (Struts, VRaptor ou Spring), SQL,Banco de Dados (SQL, Oracle e/ou My-SQL), Controle de versões no GIT (TFS, Jira e/ou GitHub), Análise de Requisitos, Metodologia Ágile Scrum, Testes unitários e automatizados (TDD);
•	Desejáveis: HTML5, PL/SQL e Certificação Java. 

Contratação: PJ
Local: Alphaville  

Interessados: Enviar currículo para analista@radarprofissional.com.br    
Visite nosso site: www.radarprofissional.com.br

**Comment by davidtcdeveloper** [comment]
@RADARProfissional Algumas informações ainda estão com o padrão do template, pedimos que ajuste a issue para que completar as informaçõs.

**Comment by davidtcdeveloper** [comment]
Este mural de vagas é destinado a vagas para Android.
Como a vaga não cita Android, estou encerrando a issue.
