### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android | iFood

### ISSUE THREAD

**Issue by lochetti** [androiddevbr/vagas#235]
### O que você irá entregar:
- Criar código de boa qualidade a partir de designs e wireframes
- Desenvolver, implementar e manter código bem estruturado, reutilizável e de ótima performance
- Identificar e corrigir bugs e gargalos de performance
- Criar e manter a arquitetura, qualidade de código, e testes automatizados
- Participar de definições estratégicas da evolução do produto

## Local

Escritório São Paulo - ao lado do parque Vila Lobos (3 minutos a pé da estação Vila Lobos - Jaguaré)

## Benefícios

- Contratação CLT com benefícios;
- Bônus anual;
- Autonomia para definir processos e seu próprio ritmo;
- Ambiente altamente desafiador e colaborativo;
- Possibilidade de aprendizado e crescimento acelerado, numa empresa que cresce em ritmo alucinante, - com oportunidade de implementar projetos que serão cases de sucesso no mundo digital

## Requisitos

Obrigatórios
- Excelente conhecimento do SDK Android. Como lidar com diferentes versões do sistema e diferentes dimensões de tela
- Bom conhecimento com Java e Kotlin
- Conhecimento de push notifications
- Experiência com testes unitários e de UI 
- Experiência com arquitetura MVP 
- Conhecimento da arquitetura MVVM recomendada pelo Google (Architecture Components)
- Capacidade de construir código testável

Desejáveis
- Desejável conhecimento em views e animações customizadas
- Desejável experiência com aplicativos geolocalizados e geofence

## Contratação

CLT

## Nossa empresa

Saibam mais sobre o iFood em https://ifood.delivery/br/sobre

## Como se candidatar

Por favor envie um email para renato.lochetti@ifood.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by lucastimotio** [comment]
A vaga ainda está aberta?
