### ISSUE TITLE
[São Paulo/SP] Lead Android Engineer | The Climate Corporation

### ISSUE THREAD

**Issue by joseandro** [androiddevbr/vagas#236]
## Descrição
A Climate Corporation, empresa do Vale do Silício, procura um engenheiro sênior para liderança técnica de Android de nosso laboratório no Brasil, trabalhando com apps que vão operar sob extremas condições climáticas. Você terá a oportunidade de criar um produto de impacto mundial, trabalhar com enormes conjuntos de "big data", tais como: dados científicos, IoT e dados geospaciais gerados por maquinários de várias fazendas ao redor do globo!
Nós estamos revolucionando a indústria e ajudando os agricultores do mundo todo a aumentar a produtividade de suas fazendas de modo sustentável com ferramentas digitais. 

Se você é apaixonado por inovação e deseja se tornar um contribuidor chave para criação de um negócio sustentável, a Climate Corporation gostaria de falar contigo!

## O que você fará
- Desenvolver apps Android responsivos e robustos para ingerir dados agronômicos, geospaciais, e climatológicos diretamente do campo.
- Colaborar com produto, design, e a liderança de engenharia para criar conceitos inovadores com ótimas experiências para o usuário de fone e tablet da indústria agrícola.
- Contribuir para bibliotecas comuns compartilhadas entre vários de nossos apps Android.
- Resolver grandes problemas de engenharia, como a sincronização de serviços offline e feeds de atividade em tempo real.
- Ser parte de um time ágil, que abraça as melhores e mais modernas práticas e ferramentas de desenvolvimento de software.
- Continuamente desenvolver e fazer releases, cumprindo as deadlines com total cobertura de testes unitários e de aplicação.
- Oportunidade para resolver um dos maiores desafios da indústria agrícola (i.e. acesso limitado a conexão confiável de dados) e aprender outras linguagens de programação, como: REST com Java / Clojure, iOS e JS.

## O que você oferece
- Profundo conhecimento de conceitos avançados de Android, incluindo: redes, segurança, gerenciamento de memória, multi-threading, e gerenciamento do ciclo de vida da aplicação;
- Total domínio da API e SDK do Android ;
- Conhecimento das bibliotecas: RXJava, Retrofit, EventBus, Dagger 2, etc;
- Habilidade com testes unitários e TDD;
- 3+ anos de experiência com Android;
- Exemplos de apps publicados na Google Play são altamente desejáveis;
- Fortes conhecimentos de programação orientada a objetos, design patterns, estruturas de dados, e algoritmos;
- Diploma em Ciência da Computação ou equivalente experiência;
- Habilidade em apresentar informações técnicas de uma maneira clara e concisa;
- Inglês fluente, você vai se comunicar (de maneira escrita e falada) com times americanos diariamente;

## Localização
CENU, São Paulo - Brooklin

## O que oferecemos
Nosso time é composto por profissionais de ponta de diferentes áreas, como: produto, ciência, engenharia, e outras. O ambiente é extremamente engajador, com diversos PhDs em agronomia, estatística e engenharia trabalhando juntos para oferecer a melhor experiência e produtos para nossos clientes.
Oferecemos salários competitivos e alguns dos melhores benefícios da indústria, incluindo:
- Convênio médico executivo;
- Convênio dental e seguro de vida;
- Ticket refeição de R$ 28;
- Frutas e snacks no laboratório;
- Encorajamento para sair do escritório para o campo para uma experiência real de como nossos produtos ajudam os agricultores;
- Oportunidade única de um impacto real no mundo - estamos resolvendo problemas que impactam massivamente a vida de agricultores e a área de segurança alimentar;
- Nós buscamos a mais alta qualidade em tudo o que criamos. Desde a precisão de nossos modelos agronômicos e a performance de nossas base de dados, as snacks que temos no escritório: nós estamos sempre refinando e melhorando;
- Oportunidade de explorar tópicos pessoais que são relevantes ao negócio;
- Regularmente hospedamos meet-ups e tech-talks e encorajamos a participação em workshops e conferências fora da empresa;
- Ótimo plano de previdência privada;
- Descontos em academias;
- Quadra de tênis grátis para uso;
- Consultas grátis ao nutricionista;
- Massagem disponível durante o dia de trabalho;
- Flex Fridays: O expediente se encerra as 15:00hr nas sextas-feiras;

## Contratação
CLT

## Como se candidatar
https://jobs.monsanto.com/

**Comment by jpventura** [comment]
@douglasdrumond, @joseandro Is this issue still opened?
