### ISSUE TITLE
[SP] 99 | Junior/Pleno/Senior

### ISSUE THREAD

**Issue by rsicarelli** [androiddevbr/vagas#238]
## About position

At 99 we are constantly evolving our software development culture. Mobile development is core to our business and therefore we constantly strive for precision and rigor in our development cycles, working closely with tests, tools and data to ensure top notch quality for our users. For this position we are looking for a detail-oriented, high-performing, mobile engineer (Android).

Since our strongest value-proposition is user experience, you must have a keen eye for UX in all aspects of the development cycle. You will be part of a 5+ multi-disciplinary team that takes care our passenger/driver apps, iterating on existing features and developing new ones to help achieve our strategic and business goals.

If you love participating and pitching in, this is also the place for you. As a team-member, you will be vital in influencing the approaches to solving core business problems and achieving desired results. We have a super friendly and supportive community where we strongly value creative ideas and dedication.

All in, if you are crazy about making a mark in the way people get from A to B, love being part of a fast-paced & quick moving company and want to help take our Android app experience to the next level, this is the place for you.

## Local

[Campus 99](https://goo.gl/maps/jmxRoj7sQCU2)

## Some of your responsibilities 

- Ensure high quality software releases, using continuous integration, automated tests and with careful code-reviews;
- Build sustainable and stable platforms for new product ideas;
- Work together with a multidisciplinary team;
- Deliver simple and elegant solutions for complex problems;
- Guidance of enterprise architecture, solutions architecture;

## Squads

You will work on Driver or Passenger squads. 

## What we​'re looking for

- 2+ years of Android development experience;
- Good experience working with Kotlin;
- Strong knowledge of Android SDK, different versions of Android, and how to deal with different screen sizes;
- Good experience on Android UI design principles, patterns, and best practices;
- Git experience;
- Efficient Task prioritization capacity;
- Hands on experience with software engineer best practices  (tests, code-review, continuous integration …);
- RESTful knowledge and background practice;
- Knowledge and practical experience with Play Store distribution process;
- MVVM/MVP experience.

# Additional Eligibility Qualifications

- Bachelor's Degree in Information Systems (IS), Information Technology (IT), Computer Science or Engineering from an accredited college or university;
- English - professional working proficiency.

## Our stack

- Languages: Scala, Java (legacy), Javascript, Kotlin (Android), Objective-­C and Swift (iOS);
Frameworks: Play, Akka, Slick;
- Databases: MySQL, Postgres, Redis, ElasticSearch, DynamoDB;
- Cloud: AWS, Docker, Elastic Beanstalk, S3, SQS, SNS, Lambda;
- Tools: Splunk, NewRelic, Crashlytics, Tableau.
- CI/CD: BuddyBuild

## What you will find on our code

- Kotlin
- Reactive approach (RxJava);
- MVP;
- Dagger2;
- Optimized layouts (custom views);
- Unit tests (a lot)
- Git (you will get used to small commits, squash, rebasing, merging, git flow etc.);
- Github (good pull requests, code reviews and other tricks)
- Open source projects

## Benefits and Perks:

- Competitive compensation
- The best ride-hailing team in Brazil: sharp, motivated co-workers in a results-driven culture;
- Fun, casual environment;
- Awesome office with a great location - we're accessible by bus and train, situated in Brooklin/Vila Olímpia;
- Health, dental and life insurance;
- Meal allowance / vale refeição;
- GymPass.

## We have a nice environment

- Different fruits everyday;
- Break fast on every mondays and fridays (with vegetarian options)
- Every ending friday we have beer (heineken) and cake's
- Barbecues and crafted beers on the rooftop

## About 99

99's mission is to make transportation cheaper, faster and more efficient using technology. We're one of the top startups in Latin America, backed by top investors monashees+, Tiger Global, and Qualcomm. We're leading the urban mobility revolution in Brazil.
Check out this video to see what we care about.

At 99 you'll be working on a problem that really matters: improving transportation - something that 200 million Brazilians do at least twice a day, every single day. We just launched 99POP, our private car service, and our big next steps will include new vehicles like vans, motorcycles, boats, rocket ships and whatever else we can dream up. We believe we have the best team in Brazil, and what we've built so far is on over 10 million devices and has completed tens of millions of rides.

## How to apply

https://jobs.lever.co/99taxis/e2045b61-28e1-42a0-8377-81c1be019584
https://jobs.lever.co/99taxis/38b575b4-7e45-435b-a64a-c8472cb78dee
https://jobs.lever.co/99taxis/fa48e2c9-f59a-406b-98f4-1846bb0fe9a5
https://jobs.lever.co/99taxis/38f1c919-6234-4a64-a028-884a3ca8a05a
https://jobs.lever.co/99taxis/561bb51f-7592-4987-804c-e31e7a03d106
https://jobs.lever.co/99taxis/5bd2aa0b-4bee-4124-834e-609cc76623ee

Didn't found your role? Ping me on slack (`@rsicarelli`) and let's talk :)

**Comment by lucaspiresdba** [comment]
Vaga(junior) ainda aberta?
