### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Android Pleno | Concrete Solutions

### ISSUE THREAD

**Issue by ghost** [androiddevbr/vagas#24]
## Descrição da vaga

Profissional deverá ter conhecimento de: Controle de versão distribuído (Git e/ou Mercurial) - Ciclo de vida de activities e fragments - Boas práticas de desenvolvimento mobile (conhecer arquiteturas) - Conhecimento em Java, orientação a objeto e design patterns - Integração com APIs RESTful e/ou Webservices - Familiaridade com o Android Studio - Familiaridade com componentes de User Interface do Android (widgets, animações, etc).
## Local

Rio de Janeiro - Barra da Tijuca
## Benefícios

Assistência Médica e Odontológica, Ticket Restaurante e Vale Transporte.
## Requisitos

Obrigatórios
- 3+ anos de experiência com Android

Desejável
- Conhecimento de metodologias ágeis (Scrum e XP)
## Contratação

CLT
## Nossa empresa

A Concrete Solutions ajuda empresas a desenvolver produtos digitais de sucesso. Foi fundada em 2001, no Rio de Janeiro, e em 2009 abriu um escritório em São Paulo. Nesses 15 anos, já desenvolvemos software para mais de 25 países e já criamos mais de 250 aplicativos mobile, para iOS e Android em smartphones e tablets. Somos o primeiro parceiro e o único com certificação Mobile da Amazon Web Services (AWS).
## Como se candidatar

Por favor envie um email para amanda.diaz@concretesolutions.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@cshalysongoncalves Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by cs-victor-nascimento** [comment]
Está aberta sim @walmyrcarvalho! Vou editar a descrição para melhorar a renderização.

**Comment by walmyrcarvalho** [comment]
@cs-victor-nascimento Tranquilo, perguntei na época só porque de tempo em tempo a gente checa se as vagas ainda tão abertas pois as vezes preencheu e a gente não sabe. :)
