### ISSUE TITLE
DESENVOLVEDOR FRONT-END SÊNIOR 

### ISSUE THREAD

**Issue by RADARProfissional** [androiddevbr/vagas#240]
A Radar Profissional, Consultoria de Recrutamento & Seleção e Terceirização de mão de obra, busca profissionais para atuar em um dos nossos clientes. 

Requisitos:
•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Domínio de HTML, CSS, JS;
•	Conhecimentos de SASS, LESS ou outro Pré-Processador de CSS;
•	Integrações com APIs REST e Webservices;
•	Style guides;
•	Padrões de Projeto;
•	Conhecimento de sistema de GRIDs;
•	Experiência com versionamento GIT/SVN, preferencialmente GIT;
•	Conhecimento em algum framework, Angular I/II, React, VueJS, Elm, ...;
•	Conhecimento em alguma framework de CSS (Boostrap, Foundation, Skeleton, Pure, Material Design ou outro);

Contratação: CLT
Local:  Zona sul -São Paulo - SP
Benefícios: AM, AO, VA, VR, entre outros. 
Interessados: Enviar CV para analista@radarprofissional.com.br com sua pretensão Salarial.
Visite nosso site: www.radarprofissional.com.br 
Data da divulgação: 14.07.2017

**Comment by davidtcdeveloper** [comment]
Oi @RADARProfissional 
Novamente uma vaga que não cita Android em momento algum.
Caso uma nova vaga neste formato seja criada, iremos reportar como spam para o GitHub.
Pedimos que prestem mais atenção ao propósito deste mural de vagas.

**Comment by RADARProfissional** [comment]
Boa tarde!

 

Me desculpe! Já orientei nossas Analistas de RH. 

 

Obrigada!

 

Att, 

 

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: David Tiago Conceição [mailto:notifications@github.com] 
Enviada em: quinta-feira, 20 de julho de 2017 10:16
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] DESENVOLVEDOR FRONT-END SÊNIOR (#240)

 

Oi @RADARProfissional <https://github.com/radarprofissional> 
Novamente uma vaga que não cita Android em momento algum.
Caso uma nova vaga neste formato seja criada, iremos reportar como spam para o GitHub.
Pedimos que prestem mais atenção ao propósito deste mural de vagas.
