### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android Pleno/Senior | Netshoes

### ISSUE THREAD

**Issue by gcoutinho** [androiddevbr/vagas#25]
## Descrição da vaga

Buscamos desenvolvedores com experiência de no mínimo 2 anos com desenvolvimento de Apps Android (nativo), trabalho presencial em horário comercial.
## Local

Escritório em São Paulo - próximo ao metrô Vergueiro
## Benefícios
- Use Mac + Monitor
- Equipe dinâmica e motivada
- Voz ativa e participação nas decisões de negócio
- VR, VA, VT, Assistência Médica + Assistência Odontológica, Benefício Farmácia, Seguro de Vida, Plano de Previdência de Privada, Bolsa de estudos, PLR
## Requisitos

Obrigatórios
- Testes unitários
- Conhecimento em consumo de APIs JSON/REST (Retrofit, Volley...)
- Conhecimento em Gradle - Flavors
- Conhecimento do processo de publicação de apps
- Conhecimento em Arquiteturas Mobile (MVP, MVVM, Clean...)
- Conhecimento em metodologia Agile
- Conhecimento em CI / CD
- Conhecimento em Git - GitFlow
- Conhecimento em Event Bus
- Fluência em inglês (leitura técnica)

Desejáveis
- Testes de interface - instrumentados
- Portfólio de aplicativos na Play Store
- Acompanhamento de relatórios - analytics

Diferenciais
- Conhecimento em e-commerce
- Conhecimento em Otimização de Performance e Segurança
## Contratação

CLT Full - 44h Semanais
## Nossa empresa

Somos nós que construímos cada história de sucesso, cada inovação que leva à melhor experiência de compra para nossos clientes.
Estamos constantemente quebrando recordes e ampliando a nossa atuação. Não somos mais apenas esporte. Somos moda. Somos estilo de vida. E seremos muito mais.
E é dessa incansável vontade de fazer mais e melhor que pautamos nossos novos valores, missão e visão para continuarmos sempre à frente.
Somos Netshoes. Somos Zattini. Somos o Grupo Netshoes!
## Como se candidatar

Por favor envie um email para tamirys.rabelo@netshoes.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@gcoutinho Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by walmyrcarvalho** [comment]
@gcoutinho Estou fechando essa vaga por falta de resposta, caso ainda esteja aberta me avise! :)
