### ISSUE TITLE
[Barueri, SP] Android Developer

### ISSUE THREAD

**Issue by otaviommendes** [androiddevbr/vagas#271]
## Descrição da vaga

Temos duas vagas para desenvolvedores Android para trabalhar em uma Fintech, spin off digital de um dos maiores bancos do Brasil.

## Local

Barueri, SP

## Posição
Pleno ou senior.

## Contratação

CLT ou PJ.

## Como se candidatar

Por favor envie um email para otavio.mendes@gingaone.com com seu CV anexado - enviar no assunto: Vaga Android Banco

**Comment by vinyguitar** [comment]
Pode ser remoto?

**Comment by otaviommendes** [comment]
@vinyguitar apenas presencial

**Comment by davidtcdeveloper** [comment]
@otaviommendes Para aumentar a chance de interesse na vaga, sugiro preencher com os outros campos do template da issue.

**Comment by otaviommendes** [comment]
@davidtcdeveloper infelizmente não posso
