### ISSUE TITLE
[São Paulo, SP] Estagiário(a) Android | Vee Digital

### ISSUE THREAD

**Issue by sergiobr** [androiddevbr/vagas#275]
## Descrição da vaga

Estagiário(a) da área de TI para trabalhar com desenvolvimento e teste de aplicações Android.
CARGA SEMANAL: 30h

## Local

Vaga presencial para Vila Olímpia, São Paulo - SP

## Benefícios

VR

## Requisitos

- Estar cursando Ensino Superior em Sistema de Informação, Informática, Análise de Sistemas, Ciência da Computação ou afins a partir do 2º ano; 
- Inglês intermediário PARA LEITURA;
- Ótimo raciocínio lógico

DESEJÁVEL:
Conhecimentos da linguagem Java, estruturas de dados, algoritmos, orientação a objetos

DIFERENCIAIS:
- Conhecer Android SDK / API Android;
- Ter um aplicativo publicado na Play Store

## Contratação

Estágio.

## Como se candidatar

Enviar e-mail com o assunto: "ESTÁGIO TI" para contato@vee.digital 
- Currículo ou Linkedin completo;
- Usuário do Github ou outro repositório de código, se possuir;
- Link para algum aplicativo publicado, se houver.

**Comment by cafecanudo** [comment]
Possivel locação remota?
