### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android

### ISSUE THREAD

**Issue by Fgochomoto** [androiddevbr/vagas#28]
## Descrição da vaga
- Buscamos profissional independente que irá estruturar a área de desenvolvimento
- O profissional terá grande interface com as equipes internas e terá participação no planejamento das novas features do portal.
## Local

Brooklin - São Paulo - SP (Zona Sul)
## Requisitos Obrigatórios
- Sólidos conhecimentos em linguagens de desenvolvimento Android (Ferramentas Google - Android Studio; Android Query, Java), para assumir posição como desenvolvedor único, trabalhando na estruturação da área
- Vivência em todo ciclo do projetos mobile, desde o levantamento de requisitos até entrega.
## Contratação

PJ à combinar
## Nossa empresa

A Be IT ([beit.work](http://beit.work/)) é a consultoria de Recrutamento e Seleção especializada no mercado de TI que compõe o grupo Integrity.

O cliente requisitante da posição, nesse primeiro momento se mantém confidencial
## Como se candidatar:

Por favor envie um email para ph@integrityconsulting.com.br com seu CV anexo - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@Fgochomoto Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by walmyrcarvalho** [comment]
@Fgochomoto Estou fechando essa vaga por falta de resposta, caso ainda esteja aberta me avise! :)
