### ISSUE TITLE
[London, UK] Android Developer | OWLR Technologies

### ISSUE THREAD

**Issue by FBisca** [androiddevbr/vagas#281]
## Role Description
OWLR are looking for an Android developer with a solid software engineering background. You will be an integral part as we develop our product which aims to make home IP cameras smarter, simpler and more Secure.

You will be working together with a multicultural engineering team and developing at a fast-pace, ensuring that the apps we deliver fulfill the promise of delivering video at the right time and the right moment.

## Local
Office located in London - England but the position is to work remotely from anywhere.

### Needed
- In-depth experience with Kotlin and Android Framework
- Consumer product experience (examples in Play Store)
- Clean coder
- Experience with consuming API’s (Rest / JSON / Parsing / etc)
- Proficient with GIT
- Experience on RxJava based architectures
- English communication needed

### Plus Points
- Experience with audio/video
- IP camera experience
- In-App Purchase subscriptions
- Firebase
- Amplitude

## Salary/Compensation
- Salary: dependant on experience 
- Short-term possibility to travel abroad

## The Company
We are a London start-up aiming to delivery the best home IP camera application in the market, with fun and responsibility.

We believe in the potential of our team, here you will find freedom of speech and quality of life, being able to work at your own pace, delivering with quality and responsibility. Our only ceremony is a video meeting scheduled at 11:00 Brazilian time every weekday.

Our multicultural team is composed by people living in 
- Cape Town, South Africa
- London, England
- Paris, France
- São Paulo, Brazil

## To apply
Submit LinkedIn, GitHub, portfolio or anything related to [jobs@owlr.com](mailto:jobs@owlr.com).

**Comment by douglasdrumond** [comment]
@FBisca 
“OWLR are looking for an Android developer with a solid software engineering background”
+
“Salary: dependant on experience”

Com esse "solid background” + “dependant on experience” faz sentido considerar Pleno + Sênior? Mantenho esses rótulos?

**Comment by FBisca** [comment]
Faz sentido manter os dois sim!
Obrigado @douglasdrumond

**Comment by pucamafra** [comment]
Hi @FBisca 
Does this role still available?
