### ISSUE TITLE
[Hummingbird] Vaga para designer!

### ISSUE THREAD

**Issue by vnavarro** [androiddevbr/vagas#284]
## Descrição da vaga

Precisamos de alguém para iniciar e liderar o time de design, essa vaga é para uma pessoa que vai auxiliar a modelar visualmente os projetos da Hummingbird, além de participar da coordenação de toda a parte de design.

## Local

Depende:

Remoto com escritório disponível. São Paulo - Paulista altura do Metro Trianon Masp

## Requisitos

Obrigatórios

* Experiência com interfaces mobile e web, incluindo wireframe, prototipação e layout
* Experiência com Sketch ou ferramentas similares

Desejáveis

* Experiência em quantificar tarefas de design
* Desejável experiência em gerenciamento de times de design
* Trabalhar com desenvolvedores para garantir que a linguagem visual será consistente e bem aplicada
* Senso de propriedade dos projetos e ter proatividade
* Desejável experiência em gerenciamento de times de design

Diferenciais

* Conhecimentos em trabalhar com Scrum
* Experiência em UX

## Contratação

PJ a combinar

## Nossa empresa

A Hummingbird é um studio de produtos digitais que cria incríveis apps e websites. A empresa é composta por pessoas extraordinárias que gostam de código de alta qualidade, aprender coisas novas, descobrir novas tecnologias, criar designs charmosos. Tudo isso com horários flexíveis, possibilidade de trabalhar parcialmente remoto e ganhar acima da média do mercado em São Paulo. Se identificou? Entra pro time.

## Como se candidatar

Mande um email com o seu currículo e portfólio e iremos entrar em contato com você
talents@hummingbird.com.br

**Comment by davidtcdeveloper** [comment]
Oi @vnavarro 
Agradecemos pelo interesse em divulgar as vagas no nosso mural. O propósito deste mural, porém, é divulgar vagas para desenvolvedores Android. Para evitar que o propósito se perca, estou encerrando esta issue.
Em caso de dúvidas por favor nos avise.
