### ISSUE TITLE
[SP - Alphaville] BRQ Digital - Desenvolvedor Android

### ISSUE THREAD

**Issue by cpoletti-brq** [androiddevbr/vagas#288]
## Descrição da vaga

O time da BRQ  especializado na criação de produtos digitais está com oportunidades para desenvolvedores mobile Android Pleno e Sênior que gostem de programar, boas práticas e código limpo para atuarem em um ambiente de transformação e ágil ajudando um grande cliente na sua jornada de criação de novo produto digital.

## Local

Presencial em Alphaville

## Benefícios

Contratação CLT e ótima cesta de benefícios.

## Requisitos

Obrigatórios
- Java
- Git
- Swagger

Desejáveis
- Bitbucket

## Contratação

CLT a combinar

## Nossa empresa

Paixão por transformar negócios com tecnologia, esse é o propósito que move a BRQ há 24 anos.
Com soluções digitais próprias e customizadas, a BRQ acelera a transformação digital das maiores empresas que operam no Brasil. 
Com mais de 3000 profissionais distribuídos em oito unidades no país e uma nos EUA, a BRQ é reconhecida pelo IDC como a maior empresa de serviços no gerenciamento e desenvolvimento de aplicações para o setor financeiro, atuando também em empresas líderes em seus setores.  

www.brq.com

## Como se candidatar

Por favor envie um email para Charlie - cpoletti@brq.com

**Comment by cafecanudo** [comment]
possível alocação remota?
