### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor Android Sênior | Involves

### ISSUE THREAD

**Issue by nadocoelho** [androiddevbr/vagas#29]
## Descrição da vaga

Na Involves, a área de desenvolvimento mobile está focada na manutenção e desenvolvimento do app Agile Promoter. Esse app está presente em mais de 15 mil dispositivos Android espalhados por vários países. Possuímos um roadmap extenso de novas funcionalidades, então temos bastante trabalho pela frente!
## Local

Florianópolis - Santa Catarina
## Benefícios
- Excelente ambiente de trabalho
- Dois monitores
- Folga no dia do seu aniversário
- Café, café e mais café
- Frutas durante a tarde
- Vale Refeição e Vale Transporte
- PLR (distribuição dos lucros da empresa)
- Um valor fixo de R$222,22 para distribuir em benefícios (Plano de Saúde, Odontologia...)
- Involvimento: são atividades pagas pela empresa para aumentar a interação entre os colaboradores. Dentro das atividades nós temos: Academia, Massagem, Yoga, Kart, Paintball, Futebol, Rafting...
## Requisitos

Obrigatórios
- 5 anos ou mais de experiência com Android
- Websockets e APIs Rest
- Conhecimento avançado no Android SDK
- Utilização do GIT como controle de versão

Desejáveis
- Inglês intermediário ou avançado
- Experiência com frameworks, libs e APIs Android
## Contratação

CLT
## Nossa empresa

Duas bandas de rock em Floripa, formadas por então estudantes das universidades Federal e Estadual em SC, deram origem à Involves. O ano era 2008. Os primeiros 9 meses (a gestação) dentro de um quarto cedido, dedicados ao primeiro plano de negócios. Nos primeiros 2 anos foram desenvolvidos mais de 10 produtos em versões alfa. Um deles, o Agile Promoter, avançou.

O time cresceu e especializou-se em trade marketing e merchandising no PDV, e estudou a fundo o seu mercado. E assim, com o software Agile Promoter, o modelo de negócios SaaS consolidou-se dentro da Involves. A partir de 2010 o faturamento duplicou a cada ano. Em 2015 aumentamos 2,5 vezes. Em 2016 queremos triplicar.

Mas os números não são tão importantes. O que nos move são sonhos. O que move a Involves são os sonhos de cada um dos Involvidos - os habitantes da Involves. Aprendemos nos momentos de dificuldade e conhecemos nossos mais profundos valores. A cultura da empresa e a gestão profissional e transparente são nossas marcas. A energia positiva do time é inacreditável.

Nos últimos anos conquistamos grandes clientes, nossos parceiros, e nos dedicamos diariamente ao seu sucesso. Conquistamos o Brasil e queremos conquistar o mundo. Não temos nenhum segredo, senão a paixão pelo trabalho: Coração.
## Como se candidatar

Entre no site http://www.involves.com.br/pt/faca-parte-da-equipe - selecione o "CARGO" "DESENVOLVEDOR ANDROID". A vaga de "DESENVOLVEDOR ANDROID SÊNIOR" será preenchida automaticamente. Basta inserir seus dados + o seu currículo e enviar.

**Comment by walmyrcarvalho** [comment]
@nadocoelho Essa vaga ainda está aberta? Se não, irei fechar essa issue!

**Comment by nadocoelho** [comment]
Bom dia @walmyrcarvalho, fechamos a vaga no final de março, esqueci de fechar a issue.
Muito obrigado.
