### ISSUE TITLE
[Alphaville - SP] Android Developer Pleno e Sênior na [RADAR Profissional]

### ISSUE THREAD

**Issue by RADARProfissional** [androiddevbr/vagas#290]
## Descrição da vaga

Vaga - Android Developer - Pleno e Sênior.

-Para atuação em cliente do segmento de tecnologia, especializado em desenvolvimento web e mobile! Vaga fixa (não é projeto de tempo determinado).

## Local

Alphaville - SP

## Beneficio

15 dias de férias remuneradas ao ano.

## Requisitos

**Obrigatórios:**

- Necessários: iOS; Objective C; Swift; Json/XML; SQL; MVC; MVP; APIs RESTful e SOAP; GIT (TFS, Jira, GitHub e/ou outros); Adaptação de layouts de smartphones e tablets; Arquitetura de Software; Testes unitários e automatizados (TDD); Provisionamento de aplicações; Push notification e Geração de certificados iOS;

**Diferenciais:**

- VIPER; Xamarin e Programação Reativa.

## Contratação

PJ salário a combinar

## Consultoria de Recrutamento e Seleção de Profissionais.
- Atuar em cliente de segmento de tecnologia, especializado em desenvolvimento de plataformas web e mobile.

## Como se candidatar

Por favor envie um email para recrutadora@radarprofissional.com.br com CV anexo e pretensão salarial PJ.

**Comment by vinyguitar** [comment]
Os requisitos sao de iOS

**Comment by davidtcdeveloper** [comment]
Bem observado @vinyguitar 
@RADARProfissional a issue está inconsistente. Peço que crie uma issue nova com os requisitos corretos.
Obrigado.
