### ISSUE TITLE
[Remoto] Dev Android Júnior/Pleno

### ISSUE THREAD

**Issue by ivanrosolen** [androiddevbr/vagas#291]
## Descrição da vaga

Desenvolvimento do app android do Billion Run

## Local

Remoto

## Requisitos

Obrigatórios
- Conhecimento em Android, codificação, versionamento GIT e publicação dos Apps;

Diferenciais
- Experiência em colaborar equipe remota, incluindo interações com design e backend
- Conhecimento em Dev iOS
- Vontade de aprender e crescer

## Contratação

- CLT

## Oferecemos

Um ambiente de startup com pessoas comprometidas, horário flexível, ambiente dev local e staging na nuvem rodando com práticas ágeis. 
Você irá trabalhar com uma equipe multidisciplinar (designers, desenvolvedores, marketing, etc)  consumindo API para desenvolver o aplicativo recém lançado.

## Nossa empresa

Billion Run

## Como se candidatar

Por favor envie um email para ivanrosolen@gmail.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Android

**Comment by ThallisonRhanniel** [comment]
@ivanrosolen. Aceita Xamarin?

**Comment by filipiandrader** [comment]
Ao enviar o currículo deu esse erro:
![6336a490-650c-4450-a862-cb65b34e20b0](https://user-images.githubusercontent.com/5423699/30773482-c0fcfefe-a047-11e7-8af2-00422e6f895d.png)

**Comment by ivanrosolen** [comment]
@ThallisonRhanniel atualmente é nativo :(
