### ISSUE TITLE
[Remoto] Desenvolvedor Android | Soul Technologies

### ISSUE THREAD

**Issue by dougritter** [androiddevbr/vagas#298]
## Descrição da vaga

Estamos à procura de um(a) desenvolvedor(a) Android com no mínimo dois anos de experiência para trabalhar remoto full time em um app de dating.
É possível também a contratação de algumas horas semanais, caso o dev não tenha 8h diárias disponíveis.

## Local

Remoto (a empresa tem escritório em Lisboa, Portugal)

## Requisitos

Obrigatórios
- 2+ anos de experiência com Android
- Entendimento de comunicação client/server para implementar uma camada de rede completa apenas com Okhttp como dependência (temos um SDK próprio)
- Experiência com versionamento, git-flow etc.
- Inglês intermediário/avançado (não precisa ser fluente, mas precisa conseguir expressar uma solução para outra pessoa)

Desejáveis
- Experiência com RxJava 
- Experiência com ferramentas de analytics e bug trackers

Diferenciais
- Projetos opensource

## Contratação

A combinar. Pagamento por hora ou mensal via PayPal ou semelhante (é possível fechar um pacote de horas semanais menor do que 40h)

## Como se candidatar

Por favor envie um email para douglas@soulplatform.com com seu CV anexado e uma breve cover letter - enviar no assunto: Android Dev

**Comment by halysongoncalves** [comment]
@dougritter Enviei pra o email!
