### ISSUE TITLE
[Remoto] Dev Android Pleno | Abacomm

### ISSUE THREAD

**Issue by DougFischer** [androiddevbr/vagas#3]
## Descrição da vaga

**Atenção:** Essa vaga foi preenchida, mas dentro dos próximos meses teremos outra contratação com o mesmo perfil. Estou mantendo a vaga por aqui para quem tiver interesse em agendar algumas conversas sem compromisso. 

Vaga para compor a equipe de Mobile da Abacomm, em projetos de diversas naturezas, porém normalmente mais voltado ao mercado Corporativo (em especial empresas de Telecom e Saúde). 

Não existe um nível técnico totalmente definido para essa vaga, porém procuramos pessoas interessadas em crescer, que sejam capazes de tocar ao menos projetos simples por conta própria.
## Local

Na Abacomm incentivamos o trabalho remoto. Você pode atuar de qualquer lugar do planeta. Se você realmente prefere trabalhar no escritório, nossa sede é no Rio de Janeiro, na Barra. 
## Benefícios
- Vale refeição/alimentação.
- Plano de saúde.
- Horário flexível.
## Requisitos

Obrigatórios
- Ao menos 1 ano de experiência com Android.
- Confortável com os principais padrões de desenvolvimento de software.
- Android Studio.
- GIT.

Desejáveis
- Experiência anterior com trabalho remoto.
- Testes unitários.
- Testes de interface, automatizados.
- Experiência em outra plataforma Mobile.
- Integração Contínua. 
## Contratação

Muito preferencialmente CLT. Outros modelos a negociar.
## Nossa empresa

A Abacomm é uma empresa focada em desenvolvimento mobile para o mercado corporativo, em especial Telecom e Saúde, com mais de 12 anos de atuação. Nossa equipe de desenvolvimento é 100% remota e por aqui você vai poder trabalhar em apps usados por algumas das principais empresas do Brasil. Não deixe de conhecer nosso site: www.abacomm.com.br
## Como se candidatar

Email para contato@abacomm.com.br com CV, github, portfólio e pretensão salarial. Colocar no assunto: Vaga Android Github.

**Comment by walmyrcarvalho** [comment]
@DougFischer Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by mariofelesdossantosjunior** [comment]
Está vaga esta aberta?

**Comment by mariofelesdossantosjunior** [comment]
Está vaga esta aberta?

**Comment by mariofelesdossantosjunior** [comment]
Está vaga esta aberta?

**Comment by mariofelesdossantosjunior** [comment]
Está vaga esta aberta?

**Comment by mariofelesdossantosjunior** [comment]
Está vaga esta aberta?

**Comment by mariofelesdossantosjunior** [comment]
Está vaga esta aberta?

**Comment by mariofelesdossantosjunior** [comment]
Está vaga esta aberta?

**Comment by mariofelesdossantosjunior** [comment]
Está vaga esta aberta?
