### ISSUE TITLE
[Rio de Janeiro, RJ] Desenvolvedor Android

### ISSUE THREAD

**Issue by helenamcfreire** [androiddevbr/vagas#30]
## Descrição da vaga

Projeto de desenvolvimento de um app para e-commerces
## Local

Escritório (com 1 dia remoto) Rio de Janeiro - Barra da Tijuca
## Benefícios
- horário flexível (desde que entregue)
- monte a sua máquina como desejar (temos monitor 24')
- frigobar sempre cheio, além de chocolate e nespresso <3
- plano de saúde
- ticket refeição de R$ 800,00
- 1 dia por semana de home office (exceto às segundas-feiras)
## Requisitos

Obrigatórios
- 1+ anos de experiência com Android
- Sangue nos olhos
## Contratação

CLT ou PJ a combinar
## Nossa empresa

Aqui na Fulllab fazemos diversos produtos focados em e-commerce. Um deles se chama Mobfiq (http://mobfiq.com.br/) que é responsável por criar o app nativo (tanto android quanto iOS) para grandes e-commerces brasileiros. Se quiser saber um pouco mais da empresa, segue a gente lá no instagram @fulllab.
## Como se candidatar

Por favor envie um email para helenamcfreire@gmail.com ou helena@fulllab.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@helenamcfreire Essa vaga ainda está aberta? Senão irei fechar essa issue!
