### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android | Youse Seguradora

### ISSUE THREAD

**Issue by janainakovacs** [androiddevbr/vagas#31]
## Descrição da vaga

Você acredita que o potencial do smartphone é pouco explorado pelas aplicações atuais?
Você tem aplicativos próprios?
Gosta de testar apps e estar sempre antenado com as novidades?
Tá afim de trabalhar em uma startup?
Se você respondeu “SIM” para quase todas as perguntas, pode ser a pessoa ideal que estamos procurando!
Agora é só se candidatar ;)
## Local

São Paulo - Vila Olímpia
## Benefícios
- Atuação em uma startup com espírito empreendedor, ágil e moderno;
- Assistência médica e odontológica;
- Assistência farmácia;
- Vale-refeição e vale-alimentação;
- Seguro de vida;
- Incentivo a academia para que vc possa praticar seu esporte
  favorito ;)
- Previdência privada (spoiler: o melhor plano do mercado).
## Requisitos Obrigatórios

Experiência com as seguintes atividades:
- Desenvolvimento e suporte de arquitetura de desenvolvimento do Android;
- Implantação e manutenção de integração contínua;
- Preparação e revisão do estilo do código;
- Customização e implementação de aplicações mobile.

Desejáveis
- Experiência em startups.

Diferenciais
- Projetos publicados.
## Contratação

CLT
## Nossa empresa

Somos uma empresa de tecnologia, com foco em desenvolver soluções inovadoras, feitas para quebrar a lógica de um mercado tradicional: o segurador.

Valorizamos a realização de cada um de nossos colaboradores, em um ambiente divertido (mesmo), de muito aprendizado, onde cada um é dono de suas tarefas e projeto.
## Como se candidatar

Vem pra Youse! Por favor envie um email para selecao@youse.com.br com seus contatos (telefone e e-mail) e seu perfil do Linkedin e/ou Currículo. - enviar no assunto: Vaga Android.

**Comment by walmyrcarvalho** [comment]
@janainakovacs Essa vaga ainda está aberta? Senão irei fechar essa issue!

**Comment by walmyrcarvalho** [comment]
Fechando essa vaga, já existe uma mais recente: https://github.com/androiddevbr/vagas/issues/121
