### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android Pl/Sr - Love Mondays

### ISSUE THREAD

**Issue by ubiratansoares** [androiddevbr/vagas#32]
## Descrição da vaga

Estamos recrutando um Desenvolvedor de Android para fazer parte da equipe do Love Mondays. Somos uma das startups de tecnologia mais inovadoras do Brasil e nosso sonho é ajudar profissionais a fazerem boas escolhas de carreira. Para chegar lá, construímos a maior comunidade de carreiras onde os funcionários avaliam as empresas onde trabalham. Estamos crescendo muito rápido e já ajudamos mais de 1 M profissionais todos os meses. Somos apaixonados pelo que fazemos, trabalhamos duro e sempre com integridade.
Temos um dos melhores aplicativos de carreiras no Mercado (https://goo.gl/ofl0ji) e precisamos de um excelente desenvolvedor Android para nos ajudar a continuar construindo uma experiência ótima para os nossos usuários.
## Local

São Paulo, SP (Presencial, acredito)
## Benefícios
- Trabalhar ao lado de alguns dos melhores desenvolvedores do Mercado.
- Ambiente de desenvolvimento emocionante – nós conceituamos, codificamos e implantamos para a produção várias vezes na semana.
- Um ambiente super amigável e informal – vista o que você quiser.
- Horário Flexível.
- Salários e benefícios competitivos.
- Incentivos para participar de Conferências de desenvolvedores.
## Requisitos
- Demostrar experiência arquitetando e criando um ou mais aplicativos Android com qualidade de produção: Mande para nós seus links do Google Play 
- Fluência na linguagem Java, Android SDK ( 2.3 – 4.x ), Dalvik VM, Render Script, gerenciamento de memória, vasto conhecimento de princípios de orientação a objetos, estrutura de otimização de dados, segurança, ipc, a interação de serviços de terceiros (Google Play Services) e o ambiente de desenvolvimento Android.
- Profundo conhecimento em REST-ful API design: Você pode projetar e documentar um protocolo servidor-cliente, e você pode implementar o lado do cliente em um protocolo documentado.
- Experiência como membro de um time de desenvolvedores trabalhando com Scrum, Kanban ou técnicas similares de desenvolvimento.
- Fortes habilidades de comunicação escrita e verbal: Você irá se comunicar com frequência com outros membros do time.
- Nível Intermediário de Inglês – nós temos Gringos então vai ajudar se você conseguir falar com eles! 
## Contratação

A combinar
## Nossa empresa

Conheça [aqui](https://www.lovemondays.com.br/)
## Como se candidatar

Se interessado, mandar um email para dave@lovemondays.com.br com o link para o seu perfil no LinkedIn ou clique em candidatar.

**Comment by walmyrcarvalho** [comment]
@ubiratansoares Essa vaga ainda está aberta? Senão irei fechar essa issue!

**Comment by ubiratansoares** [comment]
Acho que pode fechar já, só repassei aqui ...

**Comment by walmyrcarvalho** [comment]
@ubiratansoares Beleza, fechando!
