### ISSUE TITLE
[Belo Horizonte, BH] Desenvolvedor Android Pl/Sr - Avenue Code

### ISSUE THREAD

**Issue by clertonleal** [androiddevbr/vagas#33]
## Descrição da vaga

Avenue Code está contratando um desenvolvedor Android.
Entre outras coisas, nesta posição você terá a oportunidade de:
- Analisar, projetar, programar, depurar e modificar software
- Escrever códigos, realizar testes e depurar aplicações
- Interagir com os usuários para definir os requisitos de sistema e/ou modificações necessárias, bem como interagir com os interessados ​​para entender os requisitos para o desenvolvimento de aplicações
## Local

Presencial. Escritório de Belo Horizonte.
## Benefícios
- trabalhe no dia a dia com grandes clientes internacionais
- vista-se como quiser
- copa sempre com frutas, sucos e refrigerante liberado
- sala de jogos
- ambiente sempre descontraído
## Requisitos

Obrigatórios
- Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados
- Experiência em desenvolvimento Java
- Experiência com Android SDK
- Experiência com metodologias Ágeis
- Excelentes habilidades em análise e modelagem de sistemas
- Ter experiência com desenvolvimento móvel, tais como 9Patch, Android SDK, AsyncTask, Fragments, Java, Layouts, Multi-Threading, Screen Resolutions e SQLite
- Inglês avançado

Diferenciais
- Projetos opensource
## Contratação

CLT a combinar
## Nossa empresa

A Avenue Code é uma empresa norte-americana de tecnologia, focada em metodologias ágeis.
Com mais de 250 funcionários distribuídos entre Brasil e EUA, estamos sempre em busca de profissionais qualificados e apaixonados pelo que fazem!

Quer motivos para ser um Avenue Coder?
- Fomos premiados como uma das melhores empresas para se trabalhar (prêmio GPTW – 2015)
- Oportunidade de experiência internacional (São Francisco, Flórida e Nova Iorque)
- Atuação com modernas tecnologias
- Flexibilidade de horário
- Desenvolvimento do inglês (língua oficial da empresa)
## Como se candidatar

Por favor envie seu curriculum para nós pelo greenhouse: http://grnh.se/cgx5q2

**Comment by walmyrcarvalho** [comment]
@clertonleal Essa vaga ainda está aberta? Senão irei fechar essa issue!
