### ISSUE TITLE
Desenvolvedor Mobile Android - Grande Florianópolis/SC

### ISSUE THREAD

**Issue by diogodesouzajunior** [androiddevbr/vagas#335]
## Descrição da vaga

Atuar com análise e desenvolvimento de soluções personalizadas utilizando a plataforma Android.

## Local

Disponibilidade para atuação em Palhoça/SC

## Benefícios

- Clima descontraído, minuto da fruta e muito café :D

- Ginástica laboral

- Horários flexíveis

- Incentivo educação

- Convênio com restaurantes

## Requisitos

Obrigatórios
- Experiência em Android, Git. Compreensão de APIs REST e como consumi-las, conhecimento em micro serviços, conhecimento em desenvolvimento front-end: HTML5 e CSS, Javascript 
- Necessário conhecimento em Java.

Desejáveis
- Conhecimento em AngularJS, React, Umber, Vue, Micro-serviços, DEVOPS e Spring Boot.

## Nossa empresa

A SUPERO TI é uma empresa especialista nas vertentes de Fábrica de Software e Outsourcing de profissionais, além de atuar em projetos com soluções Oracle Cloud. Desde 2003 no mercado, com escritórios estratégicos em Joinville, Blumenau e Florianópolis, o time Supero TI opera sistemas em diversas tecnologias como: Java, dotNet, PHP, Android, iOS, Python, AngularJS, Oracle, SAP, e etc.

## Como se candidatar

Interessados na vaga, devem se cadastrar no site https://goo.gl/iLnJV2

**Comment by davidtcdeveloper** [comment]
No título fala de Florianópolis, mas no texto fala Palhoça. Poderia conferir qual a cidade correta?
