### ISSUE TITLE
[Remoto] Android Developer | adopets

### ISSUE THREAD

**Issue by lucasacw05** [androiddevbr/vagas#337]
## Descrição da vaga
Como Lead Android Developer na adopets, você será responsável pelo desenvolvimento do melhor sistema de adoção de animais no mundo, atualmente presente em todo o território dos Estados Unidos pelas plataformas iOS e Web. Você trabalhará ao lado de um time multicultural e também remoto, com o objetivo de salvar os mais de 7.6 milhões de pets sendo eutanasiados todos os anos nos EUA pela ineficiência dos abrigos e sistemas de adoção. Para isso, você vai precisar ter muita paixão e dedicação, sem medo de errar, aprender e fazer cada vez melhor.

## Local
Remoto 

## Requisitos

Obrigatórios
- Ser apaixonado pelo que faz e querer melhorar o mundo através disso.
- Desejar criar disrupção no mercado através de propostas inovadoras. 

- 2+ anos de experiência com Android
- Nível de Inglês intermediário-avançado

- Experiência em API RESTfull, Github
- Experiência em Testing (Unit, Beta, etc.)

- Experiência em Android API 16+, Gradle
- Boa lógica de programação

## Nossa empresa

A adopets é uma startup Estadunidense, de Boston, MA, que tem o objetivo de transformar/salvar a vida de milhões de animais e pessoas através da adoção eficiente e consciente. Somos ambiciosos e determinados a resolver um problema global através de uma tecnologia simples de usar e acessível, tanto para abrigos de animais quanto para adotantes. Atualmente estamos presentes apenas nos Estados Unidos, mas já planejamos estar no Brasil até o segundo semestre de 2018.

Somos atualmente um time multicultural de 6 pessoas, entre brasileiros, estadunidenses e indianos, portanto, um domínio intermediário-avançado de leitura/escrita do inglês é fundamental. Todos no time sempre temos características a melhorar, caso a sua seja o inglês, também sinta-se bem-vindo e com nosso total apoio.

## Como se candidatar

Por favor envie um email para lucas@adopets.org com seu CV anexado - enviar no assunto: Vaga Android

![screenshot1](https://user-images.githubusercontent.com/12879601/33960381-58e493c8-e029-11e7-8716-ca15dc58d197.png)
![screenshot2](https://user-images.githubusercontent.com/12879601/33960393-60eae982-e029-11e7-87ca-833edb2926a7.png)
![screenshot3](https://user-images.githubusercontent.com/12879601/33960394-610f3364-e029-11e7-9b93-df648c70b905.png)
![screenshot4](https://user-images.githubusercontent.com/12879601/33960397-61313cfc-e029-11e7-9b27-22c9a0277408.png)
![screenshot5](https://user-images.githubusercontent.com/12879601/33960398-6154d702-e029-11e7-90d4-c723ba55bb1d.png)

**Comment by mion23** [comment]
Bom dia, esta vaga ainda está aberta?
