### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android Pl/Sr - Avenue Code

### ISSUE THREAD

**Issue by clertonleal** [androiddevbr/vagas#34]
## Descrição da vaga

Avenue Code está contratando um desenvolvedor Android com conhecimentos de Backend.
Entre outras coisas, nesta posição você terá a oportunidade de:
- Criar protótipos, executar testes, debugging, manutenção e updates nos sistemas da plataforma
- Conceber, construir e entregar soluções enxutas, escaláveis, seguras e de fácil manutenção
- Escrever e revisar documentação técnica, incluindo design/UX, desenvolvimento e código-fonte
- Analisar, revisar e modificar software para aumentar a eficiência operacional de nossos sistemas
## Local

Presencial. Escritório de São Paulo
## Benefícios
- Trabalhe no dia a dia com grandes clientes internacionais
- Horário flexível
- Copa sempre com frutas, sucos e refrigerante liberado
- Sala de jogos
- Ambiente sempre descontraído
## Requisitos

Para isso, é necessário que você tenha:
- Ter cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados
- Domínio da plataforma Java e frameworks de desenvolvimento de sistemas Web (back end)
- Experiência no uso de tecnologias baseadas em Android, Android SDK e Android studio
- Conhecimento de estruturas com Apis Google
- Experiência de desenvolvimento de sistemas em ambientes distribuídos, escaláveis e de alta disponibilidade
- Sólidos conhecimentos em aplicações que atuam tanto como produtores quanto clientes de serviços RESTful
- Familiaridade com NodeJS será um diferencial
- Conhecimento de automação de testes: unitários, funcionais ou testes de integração
- Experiência em controle de versionamento com Git (desejável)
- Vivência com um ou mais métodos ágeis de desenvolvimento: XP (principalmente as práticas de pair programming e TDD), Scrum e Kanban
- Inglês intermediário

Diferenciais
- Projetos opensource
## Contratação

CLT a combinar
## Nossa empresa

A Avenue Code é uma empresa norte-americana de tecnologia, focada em metodologias ágeis.
Com mais de 250 funcionários distribuídos entre Brasil e EUA, estamos sempre em busca de profissionais qualificados e apaixonados pelo que fazem!

Quer motivos para ser um Avenue Coder?
- Fomos premiados como uma das melhores empresas para se trabalhar (prêmio GPTW – 2015)
- Oportunidade de experiência internacional (São Francisco, Flórida e Nova Iorque)
- Atuação com modernas tecnologias
- Flexibilidade de horário
- Desenvolvimento do inglês (língua oficial da empresa)
## Como se candidatar

Por favor envie seu curriculum para nós pelo greenhouse: http://grnh.se/yu60nk

**Comment by walmyrcarvalho** [comment]
@clertonleal Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!
