### ISSUE TITLE
Vaga Android

### ISSUE THREAD

**Issue by kamiarc** [androiddevbr/vagas#342]
## Descrição da vaga

Desenvolvimento de um app para uma rede social de pets

## Local

Remoto ou Escritório São Paulo - Jardins (Brigadeiro Luís Antonio)

## Benefícios
- VR
- Horário flexível
- Turno de 6h

## Requisitos

Obrigatórios
- 2+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis
- Experiência com Realm

Diferenciais
- Apps públicados na Playstore

## Contratação

A combinar

## Nossa empresa

Na Onesight somos totalmente focados em inovação, sempre buscando as mais novas tecnologias para criar o que há de melhor!

## Como se candidatar

Por favor envie um email para trampos@onesight.com.br com seu CV anexado - enviar no assunto: Vaga Android MG

**Comment by cshalysongoncalves** [comment]
Enviado!

**Comment by DaniellSousa** [comment]
Vaga preenchida?
