### ISSUE TITLE
[Sao Paulo, SP]  Lead Mobile Developer (Android & IOS) | BovControl

### ISSUE THREAD

**Issue by BovControlRH** [androiddevbr/vagas#344]
O time de desenvolvimento da BovControl está procurando desenvolvedores apaixonados por desafios exponenciais.  Somos uma startup global que vem conectando todas as vacas e fazendas do planeta numa 'nuvem diferente' (antes do modismo do blockchain) - com o objetivo de erradicar a fome no mundo, empoderando produtores rurais com tecnologia para serem mais eficientes e sustentáveis. 
Nossas soluções combinam coleta e a análise de dados, para toda a cadeia produtiva. 

Os dados são coletados no campo por aplicativos móveis e podem ser analisados por vários meios, por diferentes elos da cadeia (varejo, bancos, processadores de leite, etc).

Alimentar 1 bilhão de pessoas por dia, em 10 anos de existência da empresa, é a nossa meta.

## Requisitos:

- Sólidos conhecimentos em programação orientada a objetos, padrões de projeto e engenharia de software;
- Ter trabalhado com ferramentas de build e automação, como o gradle, Jenkins;
- Experiência com device tracking, geofencing, GCM, Firebase, Kotlin,Okhttp, Retrofit, Butterknife, Dagger e RxJava;
- Ter feito alguma feature offline
- Conhecimento em algum banco de dados com sqlite, Realm ou outros
- Excelente conhecimento nas linguagens Swift,Kotlin e Java.
- Conhecimento com tecnologias como fastlane, cocoapods, push notifications, core data, etc
- Experiência com o processo de distribuição da App Store e Google Play.
- Estar confortável com a aplicação dos guidelines da Apple e Google.
- Experiência com AutoLayout.
- Experiência com testes automatizados.
- Experiência em algum dos cloud provider como Azure, aws ou google cloud.
- Conseguir aprender novas ferramentas de trabalho de forma rápida e por conta própria;
- Pro atividade
- Seguir boas práticas de segurança durante no desenvolvimento
- Experiência com Testes Funcionais
- Opinar em decisões de arquitetura (sistemas) dos produtos;
- Gostar de desenvolver pessoas tecnicamente;
- Experiência com gestão de equipes; 

## Responsabilidades:

- Participar de todas as etapas do aplicativo, com foco no desenvolvimento e solução de problemas;
- Escrever códigos limpos e funcionais para aplicações;
- Solução de problemas de aplicações;
- Realizar testes unitários para aumentar a performance;
- Utilizar novas tecnologias para melhorar as aplicações antigas;
- Definir e atender os requerimentos técnicos e de design das aplicações;
- Construir código que seja reutilizável e bibliotecas para uso futuro;
- Acompanhar novas tecnologias;
- Experiência em algum dos cloud providers Azure, AWS ou Google Cloud;
- Conseguir aprender novas ferramentas de trabalho de forma rápida e por conta própria;
- Opinar em decisões de arquitetura (sistemas) dos produtos;
- Utilizar boas práticas de segurança durante no desenvolvimento;
- Administrar a própria energia e encorajar, servir de exemplo e recompensar boas energias dos colegas.

## Como BovER você desfrutará de:

- Ambiente descontraído e global;
- Contato com escritórios da empresa no Vale do Silício, Boston e São Paulo;
- Tecnologia de ponta e disruptiva;
- Ambiente de startup;
- Code Review;
- Meetups internos e externos sobre tecnologias usadas na empresa.

Venha ajudar a alimentar 1 bilhão de pessoas por dia! 

Let's rock! Let's #mooo!

## Como se candidatar:

Por favor acesso ao link: [https://bovcontrolcareers.squarespace.com/lead-mobile](https://bovcontrolcareers.squarespace.com/lead-mobile)

**Comment by jpventura** [comment]
@BovControlRH `AutoLayout` é de iOS, não? Creio que quis dizer `ConstraintLayout` 😄
