### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Android | Editora GOL

### ISSUE THREAD

**Issue by LucianoPQD** [androiddevbr/vagas#345]
## Descrição da vaga

Freela de correções e implementações em Android .

## Local

Barra da Tijuca - Orla da praia altura do posto 6.

## Requisitos

Obrigatórios
- 2+ anos de experiência com Android
- Confortável com Android Studio
- Residente no Rio de Janeiro

## Contratação

A princípio é uma Freela, podendo ser contratado, daremos almoço e transporte.

## Como se candidatar

Por favor envie um email para luciano@golmobile.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by LucianoPQD** [comment]
Obs. A idéia da empresa é pagar pela hora trabalhado, mas temos intenção de contratar se houver interesse, inicio pra ontem.

**Comment by halysongoncalves** [comment]
Mandei o email.!

**Comment by LucianoPQD** [comment]
Programador selecionado, grato a todos que enviaram email.

**Comment by mariofelesdossantosjunior** [comment]
Essa vaga ja foi fechada?
