### ISSUE TITLE
[São Paulo/SP] Desenvolvedor Android Sênior - Ginga.One

### ISSUE THREAD

**Issue by otaviommendes** [androiddevbr/vagas#349]
## Descrição da vaga

Oportunidade para desenvolvedor Android Sênior.

## Local

Inicialmente presencial em São Paulo - Bela Cintra, podendo virar remoto posteriormente.

## Requisitos

Obrigatórios
Atuar com Programação Mobile Android. Programar, codificar e testar sistemas em Android.
- Experiência com aplicativos em Android nativo;
- Integração com SDK de terceiros;
- Android Support Library e material Design;
- Trabalhar com diferentes dimensões de dispositivos (Tablet, celular e afins), experiência com GIT;
- Conhecimento com Google Play Services.

Desejáveis
- Bluetooth API, MVP, Android NDK, Sonarqube, Cucumber;
- Familiaridade com o processo de distribuição do Google Play, Scrum / Kanban.

## Contratação

CLT ou PJ a combinar.

## Como se candidatar

Interessados, por favor, encaminhar CV com pretensão salarial para vagas@gingaone.com.

**Comment by cshalysongoncalves** [comment]
Remoto?

**Comment by otaviommendes** [comment]
Inicialmente não. Depois de um tempo há a possibilidade de virar remoto.
