### ISSUE TITLE
[Curitiba, PR] Desenvolvedor Android - Fleety

### ISSUE THREAD

**Issue by clarasantana** [androiddevbr/vagas#35]
## Descrição da vaga

O Fleety é a única plataforma de car sharing P2P que está disponível em aplicativos pra celular. Entender a importância e contexto do mobile no mercado é crucial pra essa vaga.

Nosso time de desenvolvimento utiliza metodologias ágeis e dá liberdade e autonomia pra que todos participem do processo criativo. Mais do que sair largando código pelos dedos, uma participação ativa nos processos de concepção é fundamental.

## Local

Curitiba - PR

## Benefícios

- Horários flexíveis.
- Plano de carreira.
- Estoque infinito de balas de iogurte.
- Home-office uma vez por semana.
- Salários compatíveis com a função.
- Regime CLT com benefícios.
- Campeonatos diários de ping-pong.
- Conquistar o continente e mais um terceiro país a sua escolha.

## Requisitos

Desejáveis

- Experiência prévia em desenvolvimento mobile.
- Android lover.
- Já ter trabalhado com RESTful APIs e versionamento de código.
- Fascinação por código limpo e minimalista.
- Inglês técnico.

Diferenciais
- Inglês fluente.
- Possuir aplicativos publicados na Google Play.
- Interesse por mobilidade urbana.
- Usuário de serviços da economia compartilhada.
- Usuário ativo no Fleety. (:

## Contratação

CLT

## Como se candidatar

Por favor envie um email para jobs@fleety.com.br com seu CV anexado - enviar no assunto: ADEV8190

**Comment by walmyrcarvalho** [comment]
@clarasantana Bom dia Maria Clara, tudo bem? :) 

Duas perguntas:
- Essa vaga tem alguma especificação de senioridade? 
- Ela é presencial ou remoto?

É só pra gente adicionar umas tags pra ajudar quem tá procurando. :)

**Comment by clarasantana** [comment]
@walmyrcarvalho Bom dia :)

Nivel pleno ou senior e a vaga é presencial.

Obrigada!

**Comment by walmyrcarvalho** [comment]
@clarasantana Ótimo, atualizei as tags da issue. :)

**Comment by clarasantana** [comment]
Conseguimos contratar! Fechando a issue. Thanks!

**Comment by walmyrcarvalho** [comment]
Aeee que bom! o/
