### ISSUE TITLE
[Salvador, BA] Desenvolvedor Android Estágio | Cubos

### ISSUE THREAD

**Issue by lbguilherme** [androiddevbr/vagas#356]
## Descrição da vaga

Vaga de estágio aberta para desenvolvimento Android - [jobs.cubos.io](https://jobs.cubos.io)

## Local

Alameda Salvador, n. 1057, Torre América, sala 1008
Salvador, BA

## Benefícios

* horário flexível
* ambiente legal
* empresa em crescimento
* aprendizado constante
* utilização de tecnologias novas

## Requisitos

Obrigatório

* Vontade de aprender
* Motivação
* Conhecimento em Java

Desejáveis

* Experiência mínima com Android.

Diferenciais

* Conhecimento em Kotlin

## Contratação

_Estágio_
Valor: a conversar na entrevista + auxílio transporte (aumento progressivo com o passar do tempo)
Carga horária: 6 horas

## Nossa empresa

Somos um empresa de desenvolvimento de software que surgiu em 2013 em Salvador, a partir da vontade de 3 jovens de trabalhar tecnologia de uma forma mais criativa. Hoje, são 30 cúbicos, buscando sempre mostrar às pessoas o poder da tecnologia, com entregas rápidas e de qualidade. Pra conhecer mais sobre o que fazemos visite o nosso site [cubos.io](https://cubos.io)

## Como se candidatar

Preencha o formulário [jobs.cubos.io](https://jobs.cubos.io) que nós entraremos em contato para uma entrevista.

**Comment by andersonFaro9** [comment]
Somente estágio? 
Tenho dois aplicativos publicados com 02 anos de experiência e formado.

**Comment by andersonFaro9** [comment]
Estou formado e se desejar podemos negociar

**Comment by lbguilherme** [comment]
Temos a vaga para CLT também (https://github.com/androiddevbr/vagas/issues/355). Temos interesse

**Comment by andersonFaro9** [comment]
Formulário enviado, por favor verifica lá.
