### ISSUE TITLE
[São Paulo] [Pleno/Sênior] Android Developer na EvolutionIT

### ISSUE THREAD

**Issue by igor9silva** [androiddevbr/vagas#358]
## Descrição da vaga

Desenvolvimento de aplicação de força de vendas mobile. Projeto com time grande, envolvendo várias plataformas e clientes.

## Local

Escritório em São Paulo - Barra Funda

#### Diferenciais

- horários flexíveis
- use a IDE/Editor e OS de sua preferência
- clientes globais
- muito café :P

## Requisitos

**Obrigatórios:**
- inglês intermediário ou melhor
- boas práticas e padrões de projeto
- conhecimento sólido em Java, Orientação a Objetos e APIs Android
- estar confortável com MVC, MVVM e derivados

**Desejáveis:**
- GIT
- desenvolvimento de GUIs (telas)
- comunicação (client-side) com serviços REST (OData, JSON, XML, etc)

**Diferenciais:**
- conhecimento de tecnologias SAP

## Contratação

PJ a combinar

## Nossa empresa

Aqui na EvolutionIT temos a missão de simplificar processos complexos através da tecnologia. Ao lado de clientes dos mais diversos ramos, como: agronegócio, produtos farmacêuticos e cervejarias, estamos caminhando em ritmo acelerado!

Se você busca desafios novos, que exigem soluções criativas, aqui é o seu lugar :)

## Como se candidatar

Por favor envie um email para marina.duarte@evolutionit.com.br com seu CV anexado.

**Comment by igor9silva** [comment]
Tags: PJ, Pleno, Sênior

**Comment by igor9silva** [comment]
@jpventura a vaga ainda está aberta

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
