### ISSUE TITLE
[São Paulo, SP] Senior Android Developer - Quinto Andar

### ISSUE THREAD

**Issue by digoreis** [androiddevbr/vagas#36]
## Descrição da vaga

Technology and design at QuintoAndar

QuintoAndar is a technology company that enables a seamless rental experience from discovery to closing. Through the intensive use of technology and design, we are redesigning the entire rental process, from one end to the other, to allow the kind of customer experience that we wish for ourselves. As a result, we are creating a new business model that is unique in the whole world and that will revolutionize the real estate industry.

Technology and design are core components of our DNA. Our team works very very hard, with cutting edge technology and design practices, to invent web and mobile tools that are first of their kinds in the whole world.

At QuintoAndar you will:

Work with a top-notch team that uses the best practices and best tools.
Learn a lot. Really.
Be part of a high-impact project that will affect many people's lives.
Have autonomy to make decisions with no endless meetings or bikeshedding.
Work in an informal environment and horizontal hierarchy.
## Local

We have offices in São Paulo. This position is for the Sao Paulo office, near Estação Paulista (metrô linha amarela).
## Benefícios
- Competitive salary package
- Opportunity to earn stock options
- Health plan and life insurance
- Meal allowance ("ticket refeição + ticket alimentação")
- Parking, gas or public transportation allowance
- Very fun, collaborative, and fast-paced work environment
## Requisitos

Obrigatórios
- have a Computer Science or Computer Engineering degree.
- are very strong in analytic skills.
- are fluent in Android programming environments.
- have already developed significant mobile apps.
- are used to writing RESTful APIs that are accessed by mobile apps.
- do ok using relational databases.
- are fluent in English.

Desejáveis
- you have experience with reactive programming (RxAndroid)
- you are used to functional programming
- you do well good using noSQL databases (couchbase, redis etc)
- distributed systems are your friend; you understand their main challenges and know how to overcome them.
- you rock in Computer Theory and Discrete Mathematics.
## Contratação
- CLT
## Nossa empresa

Technology and design at QuintoAndar

QuintoAndar is a technology company that enables a seamless rental experience from discovery to closing. Through the intensive use of technology and design, we are redesigning the entire rental process, from one end to the other, to allow the kind of customer experience that we wish for ourselves. As a result, we are creating a new business model that is unique in the whole world and that will revolutionize the real estate industry.

Technology and design are core components of our DNA. Our team works very very hard, with cutting edge technology and design practices, to invent web and mobile tools that are first of their kinds in the whole world.

At QuintoAndar you will:

Work with a top-notch team that uses the best practices and best tools.
Learn a lot. Really.
Be part of a high-impact project that will affect many people's lives.
Have autonomy to make decisions with no endless meetings or bikeshedding.
Work in an informal environment and horizontal hierarchy.
## Como se candidatar

https://quintoandar.workable.com/jobs/48044

**Comment by walmyrcarvalho** [comment]
@digoreis Essa vaga ainda está aberta? Senão irei fechar essa issue!

**Comment by digoreis** [comment]
@walmyrcarvalho Não estou mais lá porém acredito que pode fechar.  Vou dar um toque na galera de lá, caso queiram eles abrem uma nova issue.
