### ISSUE TITLE
Desenvolvedor (a) Android - Sênior

### ISSUE THREAD

**Issue by NEON-GabiMollo** [androiddevbr/vagas#367]
## Descrição da vaga

O profissional será responsável pelo desenvolvimento e manutenção do app Android, a expectativa é que o profissional seja capaz de entregar um produto com qualidade e requintes avançados de UX.

## Local

Escritório São Paulo - Pinheiros

## Benefícios

O funcionário que entra na empresa recebe uma pontuação. Com essa pontuação, ele pode compor sua cesta de benefícios podendo pegar cerca de 7 benefícios de um total de 13 opções.

## Requisitos Obrigatórios

* Experiência mínima como pleno em desenvolvimento de aplicativos nativos Android.

* Experiência no uso de Web Services.

* Conhecimentos de UX.

* Design Patterns.

* Testes unitários.

* Conhecimentos de arquitetura como MVP e MVVM.

Desejáveis

* Experiência com desenvolvimento para smartwatch e extensões.

* Links com código no github e ou apps publicadas.

* Conhecimento em Integração Contínua. 

Diferenciais

* Conhecimentos em Kotlin (Altamente desejável).

## Contratação

CLT 

## Nossa empresa

O banco Neon é tipo um banco, só que totalmente diferente. Queremos provar que você não precisa odiar seu banco. 

## Como se candidatar

Por favor se cadastrar em https://jobs.kenoby.com/neon/job/desenvolvedor-android-senior/5a7b3b519028da144ecf062c

**Comment by jpventura** [comment]
Olá, @NEON-GabiMollo! Essa vaga ainda está aberta?

**Comment by NEON-GabiMollo** [comment]
Ta sim, JP.

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by jpventura** [comment]
Essa vaga ainda está aberta @NEON-GabiMollo?
