### ISSUE TITLE
[São Paulo, SP, Região da Paulista - Metrô da Brigadeiro] Desenvolvedor(a) Android (PL/SR) | Keycar

### ISSUE THREAD

**Issue by malkes** [androiddevbr/vagas#368]
## Descrição da vaga

Desenvolvimento de apps customizados

## Local

Presencial - Região da Paulista perto do Metrô da Brigadeiro

## Benefícios
Ambiente descontraido de Startup
dress code casual
vale-refeição
vale-transporte

## Requisitos

Obrigatórios
- 2+ anos de experiência com Android
- Confortável com padrão MVP
- Retrofit
- Git

Desejáveis
- Experiência com RxJava

## Contratação
PJ a combinar

## Nossa empresa
Startup do segmento automotivo.

## Como se candidatar
Por favor envie um email para leonardo.malkes@keycar.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by malkes** [comment]
Local da vaga atualizado. Agora com possibilidade de trabalhar em São Paulo, Paulista, Metrô Brigadeiro

**Comment by jpventura** [comment]
Olá, @malkes! Essa vaga ainda está aberta?

**Comment by malkes** [comment]
Não. Irei fechar a issue.
Obrigado

Em sex, 22 de jun de 2018 18:19, JP Ventura <notifications@github.com>
escreveu:
