### ISSUE TITLE
[São Paulo , SP] Desenvolvedor Android Pleno e Senior PJ 

### ISSUE THREAD

**Issue by Deborag12** [androiddevbr/vagas#369]
Superior completo ou em andamento em Ciência da Computação, Engenharia, Sistemas da Informação ou áreas correlatas;
• Experiência profissional no desenvolvimento e publicação de aplicativos em Android nativo;
• Trabalhar com diferentes dimensões de dispositivos (tablet, celular e afins);
• Experiência em controle de versionamento de códigos (Git);
• Conhecimentos de testes unitários e funcionais usando Junit;
• Android Support Library;
• MVC;
• Restful;
• Inglês técnico avançado para leitura.
 
Desejáveis:
• Experiência profissional com metodologias ágeis (Scrum e/ou Kanban);
• Jenkins;
• Conhecimento em Kotlin;
• Material design;
Local: 
Zona Sul e Zona Oeste de SP 

## Benefícios
não possui

Por favor envie um e-mail para debora.lima@verx.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@Deborag12 para classificar a issue com labels e fazer com que nossos membros encontrem a vaga com facilidade, peço que complemente ela com as informações do template.

```
# Informações importantes
Para que as vagas enviadas neste mural sejam categorizadas com as labels, as mesmas devem seguir as seguintes regras:
1. Todas as vagas enviadas neste mural devem estar de acordo com o Código De Conduta da nossa comunidade: https://github.com/androiddevbr/codigo-de-conduta. Vagas que violem este Código de Conduta serão automaticamente editadas e encerradas pela equipe de moderação.
2. Procure utilizar termos e descrições que façam o mínimo de distinção de gênero. Por exemplo, utilize "Desenvolvedor(a)", "Programador ou Programadora" ou "Pessoa".
3. Adicione links ou descreva as políticas de inclusão, não discriminação e afins adotadas pela empresa.
4. As vagas enviadas neste mural serão automaticamente divulgadas no canal #job-alerts do Slack da nossa comunidade.
5. Remova este bloco inicial antes de divulgar a vaga.

## Descrição da vaga

Projeto de desenvolvimento de um app de corrida, etc.

## Local

Remoto ou Escritório São Paulo - Vila Olímpia

## Benefícios

- 2 horas de almoço
- monte a sua máquina como desejar
- frigobar sempre cheio :P
- sala de jogos
- ...

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis
- Experiência com Espresso e UI Automator
- Experiência com RxJava

Diferenciais
- Projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Corporação ACME somos líderes em...

## Como se candidatar

Por favor envie um email para email@email.com.br com seu CV anexado - enviar no assunto: Vaga Android
```

**Comment by jpventura** [comment]
Olá, @Deborag12! Essa vaga ainda está aberta?

**Comment by Deborag12** [comment]
Olá,
Sim...

Débora Lima

Em Sex, 22 de jun de 2018 18:24, JP Ventura <notifications@github.com>
escreveu:

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by jpventura** [comment]
@Deborag12 de acordo com as [regras da comunidade](https://github.com/androiddevbr/vagas/blob/master/README.md), o nome da empresa precisa estar na descrição da vaga.

**Comment by jpventura** [comment]
@Deborag12 de acordo com as [regras da comunidade](https://github.com/androiddevbr/vagas/blob/master/README.md), o nome da empresa precisa estar na descrição da vaga.
