### ISSUE TITLE
[PR - Curitiba] Boleto Bancário - Desenvolvedor Android Sênior

### ISSUE THREAD

**Issue by thamiramachado** [androiddevbr/vagas#370]
## Desenvolvedor Android Sênior

As responsabilidades desse job são:
• Desenvolver do zero um app com as mesmas, ou boa parte, das funcionalidades da versão web;
• Desenvolvimento de telas de fácil entendimento e usabilidade do cliente;
• Otimizar fluxos, processos e rotinas;
• Raciocínio lógico e rapidez no teclado;
• Atenção a detalhes.

## Local
Curitiba/PR Centro - R. Marechal Deodoro, 630 (Shopping Itália)

## Benefícios

- Horário flexível
- Clube Gazeta do Povo

## Requisitos

Se você é do tipo que:
• Sonha Grande!
• É proativo e coopera de forma genuína;
• Acredita que só é possível alcançar o sucesso trabalhando duro;
• Tem ensino superior completo em áreas relacionadas a TI;
• Já teve experiência em desenvolvimento mobile;
• Conhece linguagem Kotlin, domínio será um diferencial;
• Conhece Java e meios de pagamento;
• Possui capacidade de planejamento, desenvolvimento, testes e em aprimorar grandes projetos;
• Sabe gerenciar seu tempo e prazos de entregas;
• Buscar sempre aprender coisas novas;
• Sabe se comunicar de forma assertiva.

Obrigatórios
• 3+ anos de experiência com Android

Diferenciais
• Conhecer meios de pagamento;
• Conhecer Kotlin;

## Contratação

PJ a combinar
Faixa salarial: $6.000,00 a R$8.000,00/mês

## Nossa empresa

O BoletoBancário.com cria e desenvolve soluções inovadoras para o mercado de pagamento. Começamos nosso sonho com facilidades para emissão de boletos bancários por múltiplos bancos de forma automática. Hoje focamos nossos esforços em desenvolver uma plataforma completa para geração de cobranças.

Somos jovens e queremos construir algo grande! Crescemos dia após dia, cooperamos uns com os outros e buscamos um ambiente onde trabalho, amizade e resultados possam caminhar de mãos dadas. Pró-atividade e vontade de aprender fazem parte de nosso DNA.

## Como se candidatar
[Clique Aqui](boletofacil.typeform.com/to/NSa5Z1)

**Comment by davidtcdeveloper** [comment]
@thamiramachado Para que a vaga seja cadastrada com nossas labels e seja facilmente encontrada pelos membros da comunidade, peço que verifique os ítems da seção de informações do template:

```
2. Procure utilizar termos e descrições que façam o mínimo de distinção de gênero. Por exemplo, utilize "Desenvolvedor(a)", "Programador ou Programadora" ou "Pessoa".
3. Adicione links ou descreva as políticas de inclusão, não discriminação e afins adotadas pela empresa.
```

**Comment by jpventura** [comment]
Olá, @thamiramachado! Essa vaga ainda está aberta?

**Comment by thamiramachado** [comment]
Olá,

não, a vaga de Dev Android foi preenchida no final de maio.

Como faço para desativa-la?

Obrigada! :)



2018-06-22 18:23 GMT-03:00 JP Ventura <notifications@github.com>:
