### ISSUE TITLE
[Florianópolis - SC] Engenheiro de Software Android

### ISSUE THREAD

**Issue by dnassuncao** [androiddevbr/vagas#372]
## Descrição da vaga

Engenheiro de Software Android

## Local

Escritório Florianópolis  - João Paulo

## Benefícios

- Vale Refeição/alimentação;
- Vale Transporte;
- Assistência Médica e odontológica;
- PLR – Atrelado a metas;
- Convênio com academias;
- Ambiente divertido e casual;
- Dress code Informal;
- Bem-estar e diversão: Happy Hour, Snacks à vontade, sala de descanso, vídeo game e ginástica laboral.

## Requisitos

O que esperamos de você:

- Graduação completa em Ciência da computação, Engenharia da computação, Análise e -
- Desenvolvimento de Sistemas ou áreas correlatas;
- Experiência comprovada em desenvolvimento de software, focado em Android;
- Experiência em desenvolvimento Android (Kotlin ou Java);
- Sólida experiência com SDK Android;
- Experiência com consumo de dados via REST e padrão JSON;
- Conhecimentos gerais do ambiente mobile, como arquiteturas, padrões, tendências e tecnologias emergentes;
- Conceitos sólidos em orientação a objetos;
- Experiência e cultura de testes (unitários e instrumentais);
- Preocupação em detalhes de tela: olhos clínicos para as definições de design.
 
Diferenciais:

- Experiência com Firebase;
- Experiência com desenvolvimento em Kotlin;
- Conhecimento em Clean Architecture;
- Experiência ou conhecimento teórico de metodologias ágeis (Scrum e Kanban).

## Contratação

PJ

## Nossa empresa

O Peixe Urbano é a maior plataforma de ofertas locais do Brasil. Com mais de 30 milhões de usuários cadastrados e milhares de ofertas de gastronomia, entretenimento, estética, turismo e produtos, sua missão é conectar pessoas a serviços com o melhor custo-benefício. Fundado no Brasil no início de 2010, o Peixe Urbano foi a primeira empresa latino-americana a ser eleita a “Melhor Startup Internacional do Ano” pelo Crunchies Awards, principal premiação dos Estados Unidos para startups da área de Internet e tecnologia.Em novembro de 2017, o fundo de investimento latino-americano Mountain Nazca, responsável pela operação do Groupon América Latina, adquiriu as operações do Peixe Urbano e realizou a fusão entre a empresa e o Groupon Brasil.

## Como se candidatar

Por favor envie um email para rh@peixeurbano.com com seu CV anexado - enviar no assunto: Engenheiro de Software Android

**Comment by jpventura** [comment]
Olá, @dnassuncao! Essa vaga ainda está aberta?

**Comment by diegonassuncao** [comment]
Fechamos na semana passada @jpventura .
