### ISSUE TITLE
[São Paulo - SP] Desenvolvedor(a) Android | MB

### ISSUE THREAD

**Issue by kaiokot** [androiddevbr/vagas#373]
## Descrição da vaga

Projeto de desenvolvimento de um app (para tablet) de cardápio virtual, com integração com meios de pagamentos e comunicação bluetooth
Manutenção e melhorias continuas em nosso app de mobilidade urbana. (motorista e cliente)

## Local

Presencial - São Paulo - Vila Congonhas (ao lado do aeroporto)

## Benefícios

- horário flexível
- sem dress code

## Requisitos

Obrigatórios
- 4+ anos de experiência com Android.
- Confortável com padrão  MVC e MVVM.
- Reactive programming - RxAndroid, RxJava
- Retrofit, Volley
- Implementação de layouts avançados.

Desejáveis
- Kotlin
- Dagger, Room
- Testes (espresso, jUnit, UIAutomator)
- Controle de versão Git

Diferenciais
- Home office alguns dias a combinar
- Auto gerenciamento

## Contratação
PJ 

## Nossa empresa

A MB nasceu para atender o mercado B2B, para isso oferecemos mais controle e facilidade na hora de adequar o sistema de mobilidade das empresas.

Nosso objetivo é gerar economia e conveniência para os nossos clientes. 

Vamos muito além de simples serviços de logística, mergulhando em mobilidade e soluções personalizadas. 

Contamos com uma equipe de desenvolvimento para novos produtos, bigdata e machine learning.

## Como se candidatar

Enviar e-mail com curriculo(em anexo) ou perfil Linkedin  para:

kaio.turubia@meiabandeirada.com.br
andre.insardi@meiabandeirada.com.br
natanael.silva@meiabandeirada.com.br

Com o assunto [Vaga Dev Android]

**Comment by cshalysongoncalves** [comment]
Remoto?

**Comment by kaiokot** [comment]
Boa tarde @cshalysongoncalves foi mal,  editei a descrição, aqui nós trabalhamos homeoffice somente alguns dias da semana, quando combinado.
Valeu

**Comment by davidtcdeveloper** [comment]
@kaiokot Para que a issue seja categorizada com nossas labels e seja facilmente encontrada pelos membros da nossa comunidade, peço que verifique as informações do template, especialmente os pontos abaixo:
```
2. Procure utilizar termos e descrições que façam o mínimo de distinção de gênero. Por exemplo, utilize "Desenvolvedor(a)", "Programador ou Programadora" ou "Pessoa".
3. Adicione links ou descreva as políticas de inclusão, não discriminação e afins adotadas pela empresa.
```
