### ISSUE TITLE
[Florianópolis - SC] Engenheiro(a) de Software Android

### ISSUE THREAD

**Issue by lkraider** [androiddevbr/vagas#376]
## Descrição da vaga

Desenvolvimento de sistemas para produto aplicado na área de Companhias Elétricas nacionais e internacionais. Buscamos alguém para integrar o core team, o que inclui participar na arquitetura e inovação do produto e liderança de equipe.

## Local

Escritório Florianópolis - Itacorubi

## Benefícios

- Vale Refeição/alimentação
- Assistência Médica e odontológica
- Dress code Informal
- Snacks, frigobar, ambiente tranquilo e descontraído
- Trabalho com equipe multidisciplinar

## Requisitos

Obrigatórios
- Graduação completa em alguma das áreas de Computação, Sistemas ou correlatas
- 2+ anos de experiência com Android
- Sólido conhecimento de arquitetura de sistemas mobile
- Sólido conhecimento da plataforma Android como Services, Deep Linking, Intents, lifecycle de Activities e Fragments, entre outros
- Confortável com conceitos de máquinas de estado, código paralelo/concorrente, geração procedural de interfaces, performance e otimização de algoritmo e de dados (online/offline)
- Experiência com consumo de dados via REST e padrão JSON
- Preocupação com usabilidade e qualidade de interface (UI/UX)
- Boa proficiência em Inglês (escrito e falado)

Desejáveis
- Experiência com criptografia e segurança de dados
- Experiência com testes automatizados
- Experiência com metodologias ágeis (Scrum e Kanban)

Diferenciais
- Experiência com desenvolvimento em Kotlin
- Experiência com JNI e integração de hardwares
- Experiência com validação formal de algoritmos
- Experiência com algoritmos de blockchain

## Contratação

CLT ou PJ a combinar

## Nossa empresa

A Huru Systems está criando uma plataforma de controle de supply chain de materiais de segurança utilizados por Companhias Elétricas e outras empresas de âmbito mundial. Estamos ampliando o core team para desenvolver e liderar o produto além de inovar e abarcar novas tecnologias como blockchain e big data.

## Como se candidatar

Por favor envie um email para info@hurusystems.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by graffiti75** [comment]
Meu nome é Rodrigo Cericatto e sou um Desenvolvedor Android, e também Instrutor.

Eu tenho Certificação Android da Google pelo programa Android Developer Nanodegree.

Eu tenho 6 anos de experiência em Desenvolvimento Android e dou aulas de Android a 4 anos.

Meu LinkedIn, Github e site da WeMobile:
https://br.linkedin.com/in/rodrigocericatto
https://github.com/graffiti75
http://wemobilegroup.com/

Aplicativos publicados no Google Play ao qual participei:
http://goo.gl/m5ceR
http://goo.gl/rvrRk
http://goo.gl/Zz7ON
http://goo.gl/4jDzo9
http://goo.gl/cT8VH1
https://goo.gl/GKlt8j
https://goo.gl/zjL41K

Meu CV (em Inglês e Português):
https://goo.gl/qepE36
https://goo.gl/HwM6za

**Comment by jpventura** [comment]
Olá, @lkraider! Essa vaga ainda está aberta?
