### ISSUE TITLE
DESENVOLVEDOR ANDROID

### ISSUE THREAD

**Issue by EddyJob** [androiddevbr/vagas#377]
![fb](https://user-images.githubusercontent.com/36642646/36393713-74c27330-158f-11e8-9a54-d10ad910046f.png)

# **Descrição da vaga**

Desenvolvimento de sistemas para produto aplicado na área de Companhias Elétricas nacionais e internacionais. Buscamos alguém para integrar o core team, o que inclui participar na arquitetura e inovação do produto e liderança de equipe.
Desenvolver código através da documentação e histórias de usuário; 
Corrigir defeitos;  Executar testes;  Estar em sintonia aos interesses dos projetos e empresa;
Seguir e respeitar as políticas e processos da empresa;

# **Local**
Escritório São Paulo- Araraquara

Benefícios
Vale Refeição/alimentação
Assistência Médica e odontológica
Dress code Informal
Snacks, frigobar, ambiente tranquilo e descontraído
Trabalho com equipe multidisciplinar
Requisitos
Obrigatórios

# **Formação:**
Superior cursando na área de Tecnologia da Informação ou áreas afins.

Experiência com Android

Contratação CLT 

#  **Sobre nós**
Somos uma empresa formada por mais de duzentas pessoas inquietas e comprometidas, incessantes na busca pela inovação e tecnologia.
Aqui o "nós"​ sempre prevalece sobre o "eu"​, pois somos apaixonados por pessoas, movidos pela tecnologia e inspirados pela inovação.
# 
# **Como se candidatar**
Envie seu currículo para vagas@s2it.com.br ou acesse https://lnkd.in/d3Uqqkr, confira todas as nossas oportunidades e cadastre seus dados no formulário. #VemPraS2IT #SomosMuitosQueremosMais #GerandoOportunidades

**Comment by jpventura** [comment]
Olá, @EddyJob! Essa vaga ainda está aberta?
