### ISSUE TITLE
Android Developer na Movile, iFood, Sympla, PlayKids e outras empresas do Grupo

### ISSUE THREAD

**Issue by MovileGente** [androiddevbr/vagas#378]
## Descrição da vaga
Vagas para Android Developers que queiram nos ajudar a construir produtos globais, que impactam a vida das pessoas e estão presentes no dia a dia delas. Mas dessa vez queremos propor uma abordagem diferente. Após a inscrição, você passará por uma qualificação inicial e, sendo aprovado, você ficará em **destaque frente aos recrutadores de mais de 8 empresas do Grupo Movile, dentre elas iFood, Sympla, Rapiddo, PlayKids, MapLink e Wavy.**

**RESPONSABILIDADES E ATRIBUIÇÕES**

- Criação de códigos de boa qualidade a partir de designs de wireframes;
- Criação e manutenção da arquitetura, identificação e manutenção de bugs e gargalos de performance em alguns dos aplicativos do grupo.
- Desenvolver novos aplicativos Android do zero;
- Desenvolver produtos em parceria com nossos clientes;
- Estabelecer uma relação forte com a nossa área de produtos;

[[Vídeo] Entrevista do nosso CTO](https://youtu.be/DNfLpKNoN7c)
[[Vídeo] Tech Case sobre como aplicamos Room para criar uma arquitetura modular e escalável](https://www.youtube.com/watch?v=nu5d4Y2zpTM&t=6s)
[[Vídeo] Webinar sobre o uso de Kotlin na Movile](https://www.youtube.com/watch?v=LL2iUZ1oiKE)

## Local

Presencial. Local do escritório dependerá da empresa, mas estamos presentes em São Paulo, Campinas e Belo Horizonte.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR compatível com o local do escritório
- VT
- Férias
- Possibilidade de home office
- Investimento em capacitação
- E outros diversos que são específicos de algumas empresa do Grupo (ex: GymPass, Plano odontológico, vale cultura)

#### Diferenciais

- Horário flexível
- Ambiente amigável e descontraído
- Times talentosos
- Produtos e tecnologia de ponta
- Espaço para inovação e tentativas
- Oportunidade para desenvolvimento e crescimento profissional
- Snacks liberados no escritório
- Cerveja sempre à disposição
- Muito café (máquina e coador)

## Requisitos

**Obrigatórios**
- No mínimo 4 anos de experiência profissional;
- Sólida experiência com Android SDK;
- Experiência prática com desenvolvimento Java;
- Conhecimento de Programação Orientada a Objetos;
- Bom conhecimento de APIs REST;
- Padrões de programação funcional e RxJava;
- MVP (Model View Presenter) e Clean Architecture;
- Experiência na condução de Testes Unitários;

**Desejáveis**
- Experiência prática no desenvolvimento de aplicativos utilizando Kotlin;
- Modelos de programação reativa;
- Construção de componentes de UI;

**Diferenciais**
- Implementação constante de novas linguagens e tecnologia
- Produtos novos surgem sempre
- Desafios presentes no dia a dia da empresa
- Tecnologia está presente em nossos objetivos
- Trabalhar com referências do desenvolvimento Android

## Contratação

CLT

## Nossa empresa

A Movile é líder em marketplaces móveis, e tem como grande sonho tornar a vida de 1 bilhão de pessoas melhor através de seus aplicativos. Atualmente trabalhamos com negócios e empresas em 4 pilares, que são: Food (iFood), Tickets (Sympla), Education & Care (PlayKids, SuperPlayer e Wavy) e Rapiddo (Marketplace, Payments e Entregas). Já estamos presentes no Brasil, Estados Unidos, França, México, Colômbia, Peru e Argentina, e somamos mais de 100 milhões de usuários ativos mensalmente. Com 1600 funcionários apaixonados pelo mesmo sonho, empoderados a construir novos negócios com potencial global e motivados a tomarem riscos.

A tecnologia é o nosso core, estamos formando times que criem e desenvolvam produtos incríveis para impactar e melhorar diretamente a vida das pessoas. Nossa stack é totalmente diversificada, contamos com tecnologias e linguagens diversas para termos a liberdade de sempre aplicar o que fizer mais sentido para determinado projetos. Gostamos de inovar, de aplicar ideias diferenciadas, de mudar produtos e de criar coisas realmente grandes e escaláveis.

## Como se candidatar

Basta [clicar aqui](https://jobs.kenoby.com/movile/job/android-developer-movile-group/5af2184c01c84e65c978765a?utm_source=Github) e preencher a inscrição.

## Labels
- Alocado
- CLT
- Pleno
- Sênior
- Presencial

**Comment by MovileGente** [comment]
As vagas continuam abertas :)

**Comment by jpventura** [comment]
Olá, @MovileGente! Essa vaga ainda está aberta?
