### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android na Squad

### ISSUE THREAD

**Issue by danielangelo98** [androiddevbr/vagas#381]
# Informações importantes
Para que as vagas enviadas neste mural sejam categorizadas com as labels, as mesmas devem seguir as seguintes regras:
1. Todas as vagas enviadas neste mural devem estar de acordo com o Código De Conduta da nossa comunidade: https://github.com/androiddevbr/codigo-de-conduta. Vagas que violem este Código de Conduta serão automaticamente editadas e encerradas pela equipe de moderação.
2. Procure utilizar termos e descrições que façam o mínimo de distinção de gênero. Por exemplo, utilize "Desenvolvedor(a)", "Programador ou Programadora" ou "Pessoa".
3. Adicione links ou descreva as políticas de inclusão, não discriminação e afins adotadas pela empresa.
4. As vagas enviadas neste mural serão automaticamente divulgadas no canal #job-alerts do Slack da nossa comunidade.
5. Remova este bloco inicial antes de divulgar a vaga.

## Descrição da vaga

We are building tools to help large companies extract more value from their collaborators in the areas of knowledge, influence, sales and benefits.

We are looking for talented and creative engineers excited about scale, quality, craftsmanship, looking to push the boundaries of what is possible in this fast-paced industry that is evolving daily. We are seeking a full-time Senior Android Engineer to join our Mobile team. 

As a Senior Android Engineer at Squad, you will be building technology to help groups around the world to extract more value from their connections. 

## Local

São Paulo

## Requisitos

Obrigatórios

- Re-imagine features and build new and innovative ideas

- Customize the Squad experience for the Android platform

- Go from idea to implementation

- Collaborate with designers and engineers

- Maintain high-level performance quality

- Eager to learn new languages, methodologies and technologies

- Passion for working in a dynamic and high-performance environment; able to deliver fast and with quality;
- B.S. or M.S. Computer Science or 3+ years in software development experience

- 3+ years building Android applications in Java using Android SDK

- Experience in understanding code bases, including API design techniques

- Experience in reactive programming

- Experience in the following technologies:

     * Java language and related frameworks

     * Multi-Threading and memory management specific to mobile devices

     * Caching mechanisms

     * Architecture and Design Patterns

     * Quality, distribution and monitoring tools

Desejáveis
- Knowledge of agile methodologies and techniques: Scrum, XP, Kanban, pair-programming, etc.

## Contratação

CLT to combine

## Nossa empresa

Tudo que você precisa para acelerar seu crescimento
 e extrair mais valor da sua rede reunido em um só lugar

## Como se candidatar

https://app.vulpi.com.br/squad-brazil/584?invited_by=9433

**Comment by jpventura** [comment]
Olá, @danielangelo98! Essa vaga ainda está aberta?
