### ISSUE TITLE
[São Paulo, SP] Engenheiro de Software Android Pleno

### ISSUE THREAD

**Issue by SuelenGC** [androiddevbr/vagas#382]
## Descrição da vaga

Estamos crescendo rápido e agora buscamos por mais devs para fazer parte do nosso time de Engenharia de Software! Buscamos pessoas que queiram colaborar na construção do zero de algo inovador e que realmente tem um grande impacto positivo no Brasil. 

## Local

Escritório São Paulo - Vila Olímpia 

## Benefícios

- Horário flexível
- Sem dress code
- Possibilidade de crescimento profissional
- Autonomia com alinhamento 

## Requisitos

Obrigatórios
- 2+ anos de experiência com desenvolvimento **Android nativo (Java)**
- Experiência com MongoDB e/ou MySQL, principalmente através da biblioteca ORM **[PaperDB](https://github.com/pilgr/Paper)**
- Experiência com consumo de serviços REST no Android, principalmente através das bibliotecas **[Retrofit](http://square.github.io/retrofit/)** e/ou **[OkHttp](http://square.github.io/okhttp/)**
- Experiência com programação **Orientada a Objetos**
- Experiência com **[RxJava](https://github.com/ReactiveX/RxJava)** e/ou **[RxAndroid](https://github.com/ReactiveX/RxAndroid)**
- Familiaridade com **testes de unidade** e **testes automatizados**
- Familiaridade com **métodos ágeis** (Kanban, Lean, Scrum, TDD, XP, etc)
- Familiaridade com **Git**
- Familiaridade com boas práticas de desenvolvimento de software (Design Patterns, KISS, DRY, SOLID, Code Smells mais populares, etc)

Diferenciais
- Conhecimento em Kotlin
- Familiaridade com HockeyApp ou Google Play Console (Release Management menu)
- Familiaridade com as bibliotecas Picasso, **[Butterknife](http://jakewharton.github.io/butterknife/)**, Calligraphy, Circle Image View, Easy Content Providers, JUnit e Zxing
- Familiaridade com o mercado financeiro, mais especificamente crédito e/ou microcrédito
- Já ter lido um ou mais desses livros: Clean Code ou Refatoração: Aperfeiçoando o Projeto de Software Existente

## Contratação

CLT

## Nossa empresa

O acesso ao pequeno crédito de curto prazo é extremamente limitado no Brasil para a população de baixa renda. 

O [Jeitto](http://jeitto.com.br) tem o propósito de promover a inclusão financeira das classes CDE com uma solução de crédito de pequenos valores, baixo custo e acesso simples e fácil através de aplicativos em celular. 

Fazendo uso extensivo de tecnologia o Jeitto coleta informações sobre o usuário e faz a avaliação de crédito na hora, permitindo ao cliente o uso do Jeitto para pagamento de pequenas despesas recorrentes com conveniência e rapidez.

## Como se candidatar

Se você gostou do que leu, se identificou, e está buscando um desafio bacana! Envie seu **currículo** e link do **Linkedin**, **Github** e **outros links** que acredite ser relevante para [suelen.carvalho@jeitto.com.br](suelen.carvalho@jeitto.com.br) com o assunto **Engenheiro de Software Android Pleno**

**Comment by jpventura** [comment]
Olá, @SuelenGC! Essa vaga ainda está aberta?
