### ISSUE TITLE
[BH, MG] Programador(a) mobile - Júnior ou Estágio (presencial)

### ISSUE THREAD

**Issue by alessandro-oliveira** [androiddevbr/vagas#383]
## Descrição da vaga

Vaga para programação de apps no maior site e aplicativo de música do Brasil!

## Local

Ed. Renaissance, Rua Paraíba 550, 22º andar, próximo à praça da Liberdade.
Santa Efigênia, BH / MG

## Mais informações

Saiba mais sobre os benefícios, requisitos, como se cadastrar e até assista um videozinho da empresa nesse link aqui:
https://www.studiosol.com.br/programador-mobile/

**Comment by filipiandrader** [comment]
Aceita apenas pessoas de MG?

**Comment by alessandro-oliveira** [comment]
@filipiandrader  o processo seletivo pode ser realizado remotamente, mas uma vez contratado, seria apenas presencial mesmo.

**Comment by filipiandrader** [comment]
@alessandro-oliveira entendi, é que sou de outro estado e quando vou preencher o formulário e boto meu numero, ele dá erro

**Comment by alessandro-oliveira** [comment]
Que estranho @filipiandrader , acabei de testar com DDD de São Paulo aqui e funcionou. Você tentou sem espaços / parênteses? Se ainda assim não funcionar, entra em contato no e-mail selecao.mobile@studiosol.com.br que a gente vai descobrir o que rolou =)

**Comment by filipiandrader** [comment]
Botei espaço! Irei tentar novamente! 😆

**Comment by guilhermeoa07** [comment]
Inscrições encerradas?

**Comment by alessandro-oliveira** [comment]
Sim, @guilhermeoa07 ! Eu havia esquecido de fechar a issue, obrigado pelo lembrete.
De qualquer forma, você pode se cadastrar no nosso site que assim que houver alguma vaga, a gente te avisa.
https://www.studiosol.com.br/trabalhe-conosco

Abraço!
