### ISSUE TITLE
[Florianópolis,SC] Desenvolvedor(a) Android/iOS

### ISSUE THREAD

**Issue by ygorgasparin** [androiddevbr/vagas#384]
## Descrição da vaga

![img-20180221-wa0037](https://user-images.githubusercontent.com/16228629/36558714-a7696840-17ea-11e8-9b0a-a9f4df0186e5.jpg)

Desenvolvimento de um aplicativo focado para portaria remota. O integrante irá participar desde o inicio do desenvolvimento do projeto, podendo sugerir tecnologias, arquiteturas e framework que o mesmo deverá utilizar.

## Local

Florianópolis - Santa Mônica

## Benefícios

- Vale almoço/refeição
- Cafézão da tarde top
- Sala de jogos
- Churrasqueira e chopp liberado

## Requisitos

Obrigatórios
- 2+ anos de experiência com desenvolvimento de aplicativo
- Boa organização e documentação de código-fonte (Clean code)
- Metodologia Ágil
- GIT

Desejáveis
- Testes unitários
- React Native

Diferenciais
- Integração Continua
- AWS
- C#
- NoSQL
- Experiência em cloud computing

## Contratação

CLT

## Nossa empresa

A Kiper é uma solução eficiente envolvendo hardware e software, com know-how para o controle e gerenciamento do acesso de condomínios à distância, trazendo mais segurança para seus clientes.

## Como se candidatar

Por favor envie um email para ygor.gasparin@kiper.com.br com seu CV anexado - enviar no assunto: Vaga Aplicativo

**Comment by jpventura** [comment]
Olá, @ygorgasparin! Essa vaga ainda está aberta?
