### ISSUE TITLE
[São Paulo, SP] Dev Android | Screencorp #CLT #Presencial

### ISSUE THREAD

**Issue by ab8877** [androiddevbr/vagas#385]
## Descrição da vaga
Buscamos Desenvolvedor(a) Android para ser **o(a) responsável** por projetos mobile em Android. Temos grandes clientes dos segmentos bancário, cartão de crédito, farmacêutico, hospitalar, contact center, etc. Veja mais em https://screencorp.com.br/ e https://phonecorp.com.br/

## Local e horário
- Presencial em São Paulo - Vila Madalena, perto do metrô
- Horário comercial

## Benefícios
- Benefícios pagos em dinheiro (VR, VT, etc)
- Plano de saúde Amil
- Ambiente informal e super descontraído
- Flexibilidade de horário
- 1 dia de home-office por semana
- Café expresso infinito
- Muito teamwork
- Acesso direto aos founders (CEO, COO, CTO). Sua opinião é relevante

## Requisitos
**Obrigatórios**
- Criação de apps Android: do começo ao fim (inclusive publicação na Play Store)
- Experiência em economia dos recursos de hardware (processamento e memória)
- Experiência em gestão (download, cache e reprodução) de mídias (vídeos e imagens)
- Experiência com push notifications
- Experiência com versionamento utilizando Git
- Experiência com controle de bugs e crashes (Crashlytics)

**Desejáveis**
- Conhecimentos de UX
- Experiência com Android TV
- Experiência com Firebase Cloud Messaging (FCM)
- Conhecimentos em C++ e Qt Framework

## Contratação
- CLT
- Salário compatível com o perfil. Envie sua pretensão e vamos analisar com atenção

## Nossa empresa
Somos uma startup B2B com produto validado, time world class e crescendo rápido com recursos próprios. Você responderá direto para o CTO, podendo propor ideias e melhorias para o produto.

## Como se candidatar
Por favor envie um email para rh@screencorp.com.br com seu CV anexado, mencionando apps publicados desenvolvidos por você. Enviar no assunto: Vaga Dev Android

**Comment by jpventura** [comment]
Olá, @ab8877! Essa vaga ainda está aberta?

**Comment by ab8877** [comment]
Olá..

Não, já foi preenchida.


Obrigado,


-- André Barbosa שׂלומּ | Shalom | Peace | Paz (11) 9-8030-9300 On Fri, Jun 22, 2018 at 6:21pm, JP Ventura < notifications@github.com [notifications@github.com] > wrote:
Olá, @ab8877 [https://github.com/ab8877] ! Essa vaga ainda está aberta?
