### ISSUE TITLE
[São Paulo, SP] Dev Android Pleno na Evino 

### ISSUE THREAD

**Issue by evinorecruiter** [androiddevbr/vagas#386]
## Descrição da vaga

Como Dev Android na Evino você irá:

- Compartilhar paixão por tecnologia e desenvolvimento de software, com um olho na limpeza, concisão e saúde do código;
- Resolver problemas combinada com uma boa estrutura pensada em processos; 
- Desenvolver aplicações de mobile nativo;
- Valorizar a experiência do usuário.

## Local

Alocado em nosso escritório na Bela Cintra, próximo ao metrô Consolação.

## Benefícios

- VT (com desconto de 6%) ou estacionamento no prédio (com desconto de R$43,00/mês)
- VR ou VA (R$28,00/dia) 
- Vale Alimand – para consumo interno (R$65,00/mês) 
- AM (One Health)
- AO (MetLife) 
- Seguro de Vida
-  Gympass 
- Desconto em vinhos
- Parceria com instituições de ensino e idiomas
- Horário flexível 
- HH de vinho toda sexta 

## Requisitos

É essencial que você:

- Abrace a mudança e inovação;
- Tenha experiência em publicação de apps na Play Store;
- Tenha conhecimento em programação Java e Kotlin;
- Injeção de dependência com Dagger 2;
- Reconheça especificações de UI/UX nativo;
- Tenha experiência no uso de Web Services;
- Entenda estrutura de dados e quando aplicá-las;
- Conheça desenvolvimento moderno e melhores práticas bem como padrão de design;
- Seja familiar com no mínimo uma estrutura ágil (Scrum, Kanban, XP);
- Use e bata ferramentas de integrações analíticas;
- Resolva problemas e tenha a mentalidade voltada para a qualidade;

São requisitos desejáveis

- Experiência com Espresso e UI Automator
- Experiência com RxJava

## Contratação

CLT a combinar

## Nossa empresa

Somos apaixonados por vinho e acreditamos que o melhor vinho do mundo é aquele que harmoniza com você. Por isso fazemos de tudo para descomplicar e proporcionar a melhor experiência, sempre.

Fazemos uma cuidadosa curadoria para levar o melhor rótulo para a sua mesa, onde quer que você esteja. Temos vinhos para todos, dos iniciantes aos experts. O objetivo aqui é levar a garrafa certa, no preço certo, para agradar seu paladar sem desagradar seu bolso, é claro.

Adoramos pesquisar e compartilhar. A gente acredita que novas descobertas sobre o universo do vinho podem deixar tudo melhor. Se você conhece vinho, nossa função é contar algo diferente, que poucos sabem. Se desconhece, somos a porta de acesso a um mundo cheio de novidades e prazer.

Lembre-se: quando se trata de vinho, tudo pode. Vinho pode com futebol, pode com churrasco no verão. Pode com rock e - por que não? - com samba. Só não pode complicar. Então levante sua taça (ou seu copo) e brinde a um mundo novo, cheio de descobertas.

## Como se candidatar

Por favor envie seu cv/linkedin para valeria.souza@evino.com.br com assunto: Android Pleno

**Comment by jpventura** [comment]
Olá, @evinorecruiter! Essa vaga ainda está aberta?
