### ISSUE TITLE
[São Paulo SP] Android Developer - SumUp 

### ISSUE THREAD

**Issue by Pedrogrecco** [androiddevbr/vagas#387]
# About SumUp
SumUpers are inspired by a dream: payments must be so easy, intuitive and cheap that transaction happens and people don’t even realize it. Our intuitive, inclusive and innovative payment solutions are the first step towards this world. We are proud of our amazing and challenging working environment.

Excited about building striking payments to empower the world? Join the team!

The SumUp office in São Paulo is now hiring for the position of Android Developer!

You’ll shape the core experience of merchants who are using the Android App on a daily basis.

## You will fit in perfectly to our team if

- You speak Portuguese and English - you'll be working in a global environment!

- You're comfortable with Java and the Android framework. You also know how to get things done on the command line

- You love coding and take the time to reflect on all aspects of your implementation, be it the frameworks, languages or processes

- You strive for clean code, but also know how to make your "shortcuts" easy to delete in a crunch

- Your precise communication skills make working in a distributed, global team effective and efficient

- Technology excites you, and you strive to learn something new on a daily basis!

## It will be a plus if

- You are familiar with Kotlin

- You have Bluetooth Low Energy knowledge

- You are familiar with Financial Services companies

- You have a bachelor's degree in tech related courses

## Benefits 

- Healthcare (no discounts for the employee)
- Transportation voucher or parking space
- Meal voucher
- Gympass
- Childcare assistance for moms
- Optional dental assistance.

## Location

- Pinheiros/SP

## How to apply

https://sumup.com/careers/positions/3DD1710A9C/

## How to apply

![cdt-1151-sharing-image-flying-nfc-blue](https://user-images.githubusercontent.com/36959818/36852031-88c288e0-1d49-11e8-9b9d-aa38208f32cf.png)

**Comment by douglasdrumond** [comment]
@Pedrogrecco CLT, PJ? Presencial ou remoto? Jr, Pl, Sr?

**Comment by Pedrogrecco** [comment]
@douglasdrumond Oi Douglas! CLT, Presencial de Pleno/ Senior. 

Abs!

**Comment by Pedrogrecco** [comment]
@douglasdrumond Fechamos essa vaga! 

Abs
