### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android Pleno | Editora FTD

### ISSUE THREAD

**Issue by okraciunas** [androiddevbr/vagas#388]
## Descrição da vaga

A Editora FTD está com vaga para Desenvolvedor Android Pleno, que será responsável por desenvolver novos projetos e refazer projeto antigos, que foram desenvolvidos em PhoneGap/Cordova/Ionic.

## Local

O prédio da Editora FTD está localizado na Bela Vista, São Paulo (capital).

## Benefícios

- Home-office
- Horário flexível
- Cursos online pagos pela empresa

## Requisitos

Obrigatórios
- Java
- MVC
- Experiência com Android Support Library e Material Design
- Integração com webservices utilizando API REST/JSON
- GIT
- Experiência com publicação de aplicativos

Desejáveis
- Scrum
- GitFlow

Diferenciais
- Kotlin
- Retrofit
- Dagger
- Conhecimentos com PhoneGap/Cordova/Ionic
- Experiência com Chromebook

## Contratação

PJ a combinar.

## Nossa empresa

A FTD nasceu no Brasil, em 1902, ampliando a atuação dos Irmãos Maristas que estavam no país desde 1897 na direção de vários colégios.

Os mais de 100 anos pensando muito além de livros e da sala da aula inspiraram na FTD um movimento de abraçar um compromisso ainda maior: o de transformar a sociedade por meio da Educação, com a vontade de pensar além e enxergar a Educação como um momento que inspira descoberta, escolha, liberdade e cidadania.

## Como se candidatar

Para se candidatar a vaga e ter mais detalhes, favor enviar CV/Linkedin/Portfólio para leonardo.kraciunas@ftd.com.br com o assunto **Vaga Android**.

**Comment by CaiqueJhones** [comment]
O home office pode ser em outro estado?

**Comment by okraciunas** [comment]
Olá @CaiqueJhones, tudo bem? Temos dias presenciais, por isso gostaríamos de alguém que tenha disponibilidade de ir para empresa quando necessário.

**Comment by danaric** [comment]
Oi, @okraciunas. Eu sei que a vaga é pra Android Developer, mas vocês cogitariam aceitar para o processo seletivo alguém com experiência bem sólida em NativeScript?
Eu sou do Rio de Janeiro, mas teria disponibilidade para ir à SP quando precisasse.

**Comment by okraciunas** [comment]
Olá @danaric, tudo bem? Infelizmente não, estamos em busca de um Desenvolvedor Android.

**Comment by okraciunas** [comment]
Tranquilo @danaric! Abraços!

**Comment by CarlosMion** [comment]
Bom dia @okraciunas ,

Tendo disponibilidade para ir para SP quando necessário, o HomeOffice pode ser feito de MG?

**Comment by okraciunas** [comment]
Olá @CarlosMion, tudo bem? Acabamos de fechar a vaga. Obrigado.
