### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Pleno/Sênior Android | Kanamobi

### ISSUE THREAD

**Issue by taynanb** [androiddevbr/vagas#389]
## Descrição da vaga

Vagas para perfil Pleno e Sênior, presencial. Local com ambiente de trabalho descontraído e agradável. Vai trabalhar em um ambiente informal, desenvolvendo aplicações Android, participando desde a concepção da ideia até a entrega final, publicação e manutenção dos apps.

## Local

São Paulo / SP
Próximo ao Metrô Barra Funda (Linha Vermelha do Metrô)

## Benefícios

- Trabalhar com pessoas extraordinárias;
- Oportunidades de participar de decisões estratégicas da empresa;
- Horário Flexível;
- 30 dias de férias remuneradas
- 50% do convênio médico/odontológico Bradesco
- Ambiente de muito aprendizado.

## Requisitos

**Obrigatórios**
- Mais de 2 anos de experiência com desenvolvimento Android (Nativo);
- Experiência com Android Studio e Gradle;
- Boa experiência com desenvolvimento em Java;
- Experiência com Kotlin;
- Experiência com Dependency Injection e RxJava;
- Experiência com ofuscação de código usando Proguard;
- Experiência com arquitetura de desenvolvimento (MVP/MVVM)
- Conhecimento nas Guidelines do Google;
- Conhecimento de UI/UX;
- Conhecimento e vivência com RESTFul;
- Experiência com Git, Git Flow, e Metodologia Ágil;
- Proficiência em Inglês;
- Familiaridade com o processo de distribuição do Google Play.;
- Ser apaixonado por desenvolvimento Mobile;
- Gostar de trabalhar em equipe;
- Gostar de desafios.

**Diferenciais**
- Experiência com CI;
- Experiência com desenvolvimento para outras plataformas/linguagens;
- Contribuições em projetos Open Source;
- Graduação em Ciências da Computação, Engenharia da Computação, Análise e Desenvolvimento de - Software ou cursos afins.

## Contratação

- PJ a combinar

## Nossa empresa

Empresa estabelecida no mercado há 8 anos, especializada no desenvolvimento de aplicativos mobile sob demanda e consultoria. 

## Como se candidatar

Tem interesse?
Por favor, envie um email com sua **pretensão salarial, currículo e portfolio de aplicativos** para taynan.bonaldo@kanamobi.com.br **&&** fernanda.oliveira@kanamobi.com.br

**Comment by jpventura** [comment]
Olá, @taynanb! Essa vaga ainda está aberta?
