### ISSUE TITLE
[São Paulo] Android Developer Nativo | espressoLabs

### ISSUE THREAD

**Issue by espressolabsbr** [androiddevbr/vagas#390]
## Descrição da vaga

Desenvolvimento de aplicativos Android de grande porte a partir do zero. Complexidade técnica semelhante ao Uber, Tinder e Instagram. 

## Local

Escritório em São Paulo - Perdizes, 5 min a pé do metrô Sumaré

## Benefícios

- Café e comida à vontade
- Varanda com rede e puff
- Flexibilidade de horário
- Clima descontraído
- Time jovem e talentoso
- Espaço para inovação

## Requisitos

Obrigatórios
- 1+ ano de experiência com Android
- Boa organização de código
- Bom conhecimento de APIs REST
- Git

Desejáveis
- Experiência com lançamentos na PlayStore

Diferenciais
- Flutter
- Swift

## Contratação

Estágio ou PJ a combinar

## Nossa empresa

A espressoLabs tem a missão de resolver qualquer necessidade de pequenos negócios que nos consultam. Seja um problema de business e marketing ou um desenvolvimento de aplicativo ou ecommerce, temos o objetivo de garantir a solução mais adequada ao cliente.  

A startup foi fundada por três universitários da USP (dois engenheiros e um administrador) e estamos em busca de talentos que queiram crescer junto conosco.

## Como se candidatar

Por favor envie um email para development@espressolabs.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Olá, @espressolabsbr! Essa vaga ainda está aberta?
