### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor(a) Android (Kotlin) | Biologia Total

### ISSUE THREAD

**Issue by daniel-leandro** [androiddevbr/vagas#391]
## Descrição da vaga

Responsável em desenvolver aplicativos mobile, colaborando com os demais membros do time no entendimento dos requisitos de negócio e técnico, juntamente com os respectivos critérios de aceitação para a elaboração e codificação dos aplicativos.Esta pessoa deve ser apaixonada pelo desenvolvimento de software e pelo trabalho colaborativo em equipes multidisciplinares de desenvolvimento, sendo evangelista na melhoria contínua da qualidade dos aplicativos mobile.

## Local

Presencial - Escritório no Bairro Trindade, Florianópolis - SC

## Responsabilidades:
Desenvolvimento do aplicativo Biologia Total para dispositivos Android (smartphones e tablets)

## Pré-requisitos:
Experiência com desenvolvimento nativo para Android (Kotlin de preferência)

## Diferenciais:
Experiência com publicação e gestão nas lojas de aplicativos (Google Play)
Experiência com desenvolvimento nativo para iOS
Entender sobre a composição de aplicativos Android em estrutura, APIs e performance;
Fundamental entender o ciclo de vida de aplicações e componentes do Android (Application, Activity, Service, ContentProvider, etc);
Experiência em projetos com metodologia Scrum
Conhecimentos em APIs REST e/ou RESTful
Conhecimentos em ensino online
Experiência com controle de tarefas no Jira
Ensino superior cursando ou completo em Ciência da Computação ou áreas relacionadas.

## Contratação

CLT a combinar (Envie sua pretensão salarial)

## Nossa empresa

Conheça um pouco mais sobre nossa empresa:

- http://g1.globo.com/economia/pme/pequenas-empresas-grandes-negocios/noticia/2018/02/professor-de-biologia-de-florianopolis-faz-sucesso-na-internet-dando-aula.html
- https://www.youtube.com/watch?v=ZKWIvNGHbZA
- https://www.biologiatotal.com.br/

## Como se candidatar

Aceita o desafio? Envie-nos seu currículo e pretensão salarial para daniel@biologiatotal.com.br com assunto “Desenvolvedor(a) Android”.

**Comment by jpventura** [comment]
Olá, @daniel-leandro! Essa vaga ainda está aberta?
