### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Android Sênior | Gigigo Brasil

### ISSUE THREAD

**Issue by luizzabuscka** [androiddevbr/vagas#392]
## Descrição da vaga

Estamos em busca de um Desenvolvedor Sênior para formar parte de nossa equipe de Android no escritório do Brasil, baseado em São Paulo. Trabalhará no desenvolvimento de aplicações nativas, principalmente em Java. Deve ser capaz de liderar os projetos trabalhando de forma autônoma quanto integrado em uma equipe com várias pessoas. 
Reportará diretamente ao Gerente de Operações do Brasil. Queremos profissionais que demonstrem paixão pelo seu trabalho, e para isso, promovemos o crescimento dos membros da equipe através de palestras e workshops internos onde se espera contribuição ativa. 
Também é uma grande preocupação a qualidade de nossos produtos e entregas, por isso se exigirá que o profissional seja detalhista – não somente a nível estético – mas também que ao programar um código saiba que deverá seguir os princípios básicos de Clean Architecture e Clean Code. É apreciado que saiba desenvolver bem com testes unitários.

## Local

Escritório São Paulo - Vila Olímpia.

## Benefícios

● Incorporar em uma empresa jovem e dinâmica que aposta nas últimas tendências tecnológicas, com um excelente ambiente de trabalho e desafios muito interessantes.
● Interação entre os profissionais da Espanha, México e Brasil.
● Contrato por período indeterminado

## Requisitos

● Ao menos 2 anos de experiência desenvolvendo aplicações nativas para Android
● Alto conhecimento de Java e do framework do Android
● Conhecer bem os princípios de SOLID e saber aplicá-los
● Conhecimentos em Clean Architecture
● Experiência desenvolvendo testes unitários
● Utilizar bem Git e Git-Flow
● Atitude autodidata, operativo, vontade de querer continuar aprendendo e melhorando, predisposição a sempre fazer bem e com qualidade, saber trabalhar em equipe e em projetos diversos.
● Idiomas: espanhol (preferencial) e/ou inglês, ambos em nível de conversação. Este profissional terá contato com equipes de desenvolvimento alocadas nos escritórios da Espanha e do México.

Diferenciais
● Clean Code
● Scrum
● Jira
● Integração contínua

## Contratação

PJ a combinar

## Nossa empresa

Gigigo foi fundada em 2004 com a gestão e distribuição de conteúdos para dispositivos móveis como principal linha de negócio. Atualmente contamos com clientes globais e projetos em mais de dez países da Europa e América Latina, com escritórios no México, Brasil e Espanha. Nossa estratégia de crescimento se apoia no investimento em Pesquisa e Desenvolvimento e na experiência adquirida sobre conectividade de equipamentos, big data, desenvolvimento multiplataforma, entre outros.

## Como se candidatar

Inscreva-se pela vaga no LinkedIn: https://www.linkedin.com/jobs/view/551895675/

**Comment by jpventura** [comment]
Olá, @luizzabuscka! Essa vaga ainda está aberta?

**Comment by luizzabuscka** [comment]
@jpventura Não conseguimos ninguém ainda, mas como alguns planos aqui da empresa mudaram, pode fechar. Valeu!
