### ISSUE TITLE
[Salvador, BA] Desenvolvedor(a) Android Estágio | Cubos

### ISSUE THREAD

**Issue by lbguilherme** [androiddevbr/vagas#394]
## Descrição da vaga

Vaga de estágio aberta para desenvolvimento Android - [jobs.cubos.io](https://jobs.cubos.io)

## Local

Alameda Salvador, n. 1057, Torre América, sala 1008
Salvador, BA
Estaremos mudando de escritório no próximo mês. Localização ainda não definida. 

## Benefícios

* horário flexível
* ambiente legal
* empresa em crescimento
* aprendizado constante
* utilização de tecnologias novas

## Requisitos

Obrigatório

* Vontade de aprender
* Motivação
* Conhecimento em Java

Desejáveis

* Experiência mínima com Android.

Diferenciais

* Conhecimento em Kotlin

## Contratação

_Estágio_
Valor: a conversar na entrevista + auxílio transporte (aumento progressivo com o passar do tempo)
Carga horária: 6 horas

## Nossa empresa

Somos um empresa de desenvolvimento de software que surgiu em 2013 em Salvador, a partir da vontade de 3 jovens de trabalhar tecnologia de uma forma mais criativa. Hoje, são 30 cúbicos, buscando sempre mostrar às pessoas o poder da tecnologia, com entregas rápidas e de qualidade. Pra conhecer mais sobre o que fazemos visite o nosso site [cubos.io](https://cubos.io)

## Como se candidatar

Preencha o formulário [jobs.cubos.io](https://jobs.cubos.io) que nós entraremos em contato para uma entrevista.

**Comment by davidtcdeveloper** [comment]
@lbguilherme Obrigado por compartilhar esta oportunidade em nosso mural. Peço apenas que dê atenção para as instruções que tempos para o envio de vagas, especialmente ao ítem 2:
```
2. Procure utilizar termos e descrições que façam o mínimo de distinção de gênero. Por exemplo, utilize "Desenvolvedor(a)", "Programador ou Programadora" ou "Pessoa".
```

**Comment by lbguilherme** [comment]
Resolvido @davidtcdeveloper. Obrigado.

**Comment by davidtcdeveloper** [comment]
Obrigado pela agilidade :)

**Comment by jpventura** [comment]
Olá, @lbguilherme! Essa vaga ainda está aberta?

**Comment by lbguilherme** [comment]
Sim!

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
