### ISSUE TITLE
[Belo Horizonte - MG] - Analista de Sistemas Android e IOS

### ISSUE THREAD

**Issue by feraguiar** [androiddevbr/vagas#397]
Descrição da vaga

Desenvolvimento de melhorias nos aplicativos da empresa.

 Local

Belo Horizonte - MG

Benefícios

Vale transporte, Vale refeição, plano saúde Bradesco

Requisitos

Obrigatórios
- 1 ano de experiência com Android

Desejáveis
- Experiência com IOS

Contratação

CLT

Nossa empresa

Criativa RH

Como se candidatar

Por favor envie um email para fernanda@criativarh.com.br com seu CV anexado - enviar no assunto: Vaga Android e IOS

**Comment by jpventura** [comment]
Olá, @feraguiar! Essa vaga ainda está aberta?

**Comment by feraguiar** [comment]
Envia seu currículo.



*Att. *
*Fernanda Aguiar*
*Recursos Humanos *

*Tel: 31 2526-7820*
*Cel: 31 99281-7820*



*E-mail: fernanda@criativarh.com.br <fernanda@criativarh.com.br>Visite o
nosso site: www.criativarh.com.br <http://www.criativarh.com.br/>*

2018-06-22 18:17 GMT-03:00 JP Ventura <notifications@github.com>:

**Comment by jpventura** [comment]
@feraguiar Não, eu quero saber porque sou um dos moderadores e estou fechando as vagas inativas :smile:

**Comment by feraguiar** [comment]
A vaga ainda está aberta.



*Att. *
*Fernanda Aguiar*
*Recursos Humanos *

*Tel: 31 2526-7820*
*Cel: 31 99281-7820*



*E-mail: fernanda@criativarh.com.br <fernanda@criativarh.com.br>Visite o
nosso site: www.criativarh.com.br <http://www.criativarh.com.br/>*

2018-07-03 12:21 GMT-03:00 JP Ventura <notifications@github.com>:

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
