### ISSUE TITLE
BRQ São Paulo- Sr Android Developer

### ISSUE THREAD

**Issue by ReAnne123** [androiddevbr/vagas#398]
Descrição da vaga
Projeto de desenvolvimento para um grande banco de investimentos.

Local
Presencial na unidade de São Paulo- Itaim Bibi.

Benefícios
- Vale refeição
-Assistência médica Amil com co-participação
-Seguro de Vida
-Vale alimentação
-Previdência privada
-Assistência odontológica

Obrigatórios
Experiência com Android,  
Experiência em implementação de automação de testes unitários utilizando TDD ou BDD;
Experiência com processo de publicação da aplicação para Google Play e Apple (Beta Test e Produção);
Excelente conhecimento de Orientação a Objetos
Conhecimentos de Programação Orientação a Protocolos

Desejáveis
-Desejável experiência com bibliotecas para interação com câmera, localização, gráficos e http client.
-Desejável experiência Gradle para Android;
-Desejável conhecimento em automação de testes utilizando appium ou calabash para Android;
-IOS Swift.

Contratação
CLT pela BRQ, salário a combinar, vamos considerar a expectativa salarial do candidato.

Nossa empresa
Fundada em 1993, a BRQ é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife, Salvador, Brasília, Natal e Nova Iorque. 

Como se candidatar
Por favor envie um email para ryokota@brq.com (Renata) com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Olá, @ReAnne123! Essa vaga ainda está aberta?

**Comment by ReAnne123** [comment]
@jpventura essa foi concluída, mas tenho outra que pede Java também. 
Obrigada.

**Comment by jpventura** [comment]
@ReAnne123 só postar então 😄
