### ISSUE TITLE
[São Paulo/Remoto] Dev. Android Sr. | Empresa Sigilosa 

### ISSUE THREAD

**Issue by rsicarelli** [androiddevbr/vagas#4]
**REPASSANDO**: Consultoria **Kelly Services** procura desenvolvedor com as seguintes características:

## Descrição da vaga

Empresa do segmento logístico

## Local

Zona Sul - Bairro Pinheiros

## Requisitos
- Experiência com geolocalização;

## Contratação

CLT ou PJ

## Como se candidatar

Por favor envie um email para Marília Filippetti _marilia.filippetti@kellyservices.com_

**Comment by walmyrcarvalho** [comment]
Vaga preenchida.
