### ISSUE TITLE
[Porto Alegre, RS] Desenvolvedor(a) Android |DeepX

### ISSUE THREAD

**Issue by kuquert** [androiddevbr/vagas#401]
## Descrição da vaga

DeepX is looking for Android developers. We search for enthusiastic developers that would love to work with new technologies.

## Local

Escritório Porto Alegre - Moinhos de Vento

## Benefícios

- Vale viagem
- Academia
- Farmácia
- Cabify
- VT
- VR
- Plano de saúde
- Plano odontológico 
- Seguro de vida

## Requisitos

Obrigatórios
 - English

Desejáveis
- Functional languages knowledge
- Experience with iOS development

Diferenciais
- Experience with kotlin

## Contratação

CLT

## Nossa empresa

DeepX is a fast-growing company dedicated to the research and development (R&D) of new products that leverage advanced, cutting-edge technologies. Originally founded in the United States in Austin, Texas and headquartered in Porto Alegre, Brazil, DeepX is on a mission to build world changing products of the future.

## Como se candidatar

Enviar e-mail para careers@deepx.it

**Comment by jpventura** [comment]
Olá, @kuquert! Essa vaga inda está aberta?

**Comment by kuquert** [comment]
SIm, ainda está aberta!!

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
