### ISSUE TITLE
[ São Paulo, SP ] Desenvolvedor(a) Android Pleno & Senior | Dailyltd.com

### ISSUE THREAD

**Issue by alanlammiman** [androiddevbr/vagas#402]
## Descrição da vaga

- Cia de apps até agora focada só em iOS busca Devs Android plenos e seniores
- Responsabilidade por toda a atuação da empresa em Android
- Trabalho inicial: implementação dos principais apps da cia em Android, incluindo integração com backend e ferramentas Firebase, in-app-purchases, SDKs, etc.
- O time de Android poderá inclusive vir a assumir a liderança em criação de novos produtos (vs. o time iOS) dada a maior velocidade de aprovação / iteração do desenvolvimento em Android.
- Mais infos sobre a cia: dailyltd.com

## Local

- Presencial no Brooklin
- Atualmente na Av. Morumbi na altura do 8400
- Mudança em breve para Torre Norte (Av. Nações Unidas)

## Benefícios

- PJ
- Bônus por desempenho
- Oportunidade de crescimento acelerado: para liderança técnica/CTO 
- Oportunidade de tornar-se sócio(a)

## Requisitos

Obrigatórios
- Competência comprovada em desenvolvimento para Android, com boas práticas de git, tdd, etc.
- Maturidade, comprometimento e profissionalismo (parece clichê mas é sério)

Desejáveis
- Graduação em ciência da computação ou engenharia
- Familiaridade com Firebase/Firestore/Google Cloud Platform, e in-app-purchases

Diferenciais
- Visão técnica mais ampla do que só o desenvolvimento Android (pensando num potencial eventual avanço a CTO)
- Competência adicional em qualquer outra linguagem ou framework esp. Node, Swift, React, Flutter, Rails.
- Experiência empreendedora, ou mesmo só projetos interessantes (por exemplo no github)

## Contratação

- PJ
- R$3 a 10k conforme senioridade

## Nossa empresa

- Somos uma startup fundada em 2017, focada em desenvolvimento de apps mobile de entretenimento por assinatura. Temos assinantes em mais de 130 países, não dependemos de investimento externo e temos crescimento acelerado.
- Mais info: dailyltd.com

## Como se candidatar

Envie email com CV para talent@dailyltd.com

**Comment by jpventura** [comment]
Olá, @alanlammiman! Essa vaga inda está aberta?
