### ISSUE TITLE
Desenvolvedor- Android e IOS- projeto específico!

### ISSUE THREAD

**Issue by FabioBenites** [androiddevbr/vagas#406]
**Descrição da vaga**
Estamos a procura de um(a) desenvolvedor(a) Android e IOS para atuar em projeto específico.
Local:
Porto Alegre, RS
Remuneração:
A combinar.
Requisitos
Obrigatórios:
Experiência com definição de arquitetura para aplicativos (MVP, MVVM etc);
Conhecimento de Android Nativo e/ou  IOS ;
Conhecimento em testes automatizados;
Experiência com Firebase, Google Cloud Platform, Amazon AWS;
Publicações de versões na Play Store;
Conhecimento de metologia ágil e
Boas práticas de programação
Diferenciais:

Conhecimento outra linguagem de desenvolvimento Mobile (Swift, Kotlin ou Ionic);
Familiaridade com programação reativa e
Familiaridade com ferramenta de controle de versão distribuída (preferência Git)

Formação:

Sistemas de Informação, Análise e Desenvolvimento de Sistemas, Engenharias ou similares.

Contratação:

A combinar!

Nossa empresa
A Shine Service é uma empresa que atua na área de conservação e asseio condominial, localizada em Porto Alegre-RS. Já recebeu vários prêmios de destaque em seu seguimento, como o clave de sol.

Como se candidatar
Entrar em contato com:
http://www.shineservice.com.br/
rodrigo@shineservice.com.br
Telefone- whats- 51 98133730

fbenites@gmail.com
Telefone: 51 981240551

**Comment by jpventura** [comment]
Olá, @FabioBenites! Essa vaga inda está aberta?
