### ISSUE TITLE
[Rio de Janeiro, RJ] Desenvolvedor Android / Mobicare

### ISSUE THREAD

**Issue by MobiSelecao** [androiddevbr/vagas#408]
## Descrição da vaga

Participar de todo o ciclo de desenvolvimento de aplicativos, desde a fase de análise da solução até a entrega e manutenção do projeto.
Trabalhar com outros desenvolvedores de alto desempenho em um ambiente colaborativo.

## Local

Botafogo - Rio de Janeiro

## Benefícios

Horário de trabalho com flexibilidade de acordo com os projetos, entregas e necessidades; 
Plano de saúde 
Plano Odontológico
Vale-Transporte; 
Vale-Refeição e / ou Alimentação (mantido inclusive nas férias); 
Curso de inglês e /ou espanhol (Dentro do nosso programa de curso de idiomas ministrado internamente); 
Bônus anual. 

## Requisitos

Forte conhecimento do Android SDK e das diferentes versões do Android;
Conhecimento dos padrões de UI do Android, princípios de design, padrões e melhores práticas;
Saber lidar com diferentes tamanhos de tela;
Familiaridade com RESTful webservices;
Experiência com armazenamento off-line, threading e melhora de performance;
Conhecimento das libs open-source mais utilizadas para Android;
Android Studio / Gradle;
Familiaridade com ferramentas de versionamento (Git/SVN);
Inglês técnico;
Experiência com push notifications / FCM;
Testes automatizados;
Testes de UI;
Contribuição em projetos open source;
Ter ao menos um aplicativo desenvolvido (não necessariamente publicado no Google Play);
API’s do Google Services (maps, analytics, GTM, GCM etc);
Experiência com Material Design;
Conhecimento de metodologias ágeis;

## Contratação

CLT

## Nossa empresa

Somos especializados em soluções de autoatendimento móvel e WiFi Carrier Grade.

## Como se candidatar

Por favor envie um email para vagas@mobicare.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Olá, @MobiSelecao! Essa vaga inda está aberta?

**Comment by MobiSelecao** [comment]
@jpventura a vaga finalizou.
