### ISSUE TITLE
[SP - Barra Funda] Desenvolvedor(a) Android 

### ISSUE THREAD

**Issue by VivianeCrisogano** [androiddevbr/vagas#409]
## ##**Oportunidade Desenvolvedor(a) Android - São Paulo**

**Sobre a shopper.com.br:**
Somos o supermercado 100% online que mais cresceu em 2017. 
Recebemos um prêmio de R$ 1 milhão para desenvolver tecnologias que revolucionem a forma como as pessoas fazem compras.
Acreditamos que com trabalho duro, usando tecnologias e modelos de negócio inovadores, podemos transformar a sociedade e entregar mais tempo, energia e dinheiro às pessoas. 
Levantamos da cama todos os dias com esse propósito em mente: criar soluções para que os brasileiros vivam vidas mais inteligentes. Nossa cafeína diária é a vontade de servir, e servir bem (muito bem!)
Estamos em uma fase de expansão e crescimento, e, para que isso aconteça, queremos gente do nosso lado que acredite na nossa missão e que tenha muuuita vontade de crescer e fazer um trabalho incrível!

**Descrição da vaga:**
Responsabilidades:
- Desenvolver alterações/melhorias no app da Shopper para Android.

**Local**
Escritório - Avenida Marquês de São Vicente, 1619 - Barra Funda.

**Benefícios**
- Ambiente de startup, informal, de muito aprendizado e de possibilidade de crescimento muito rápido, nosso trabalho é focado em meritocracia, então, só depende de você!

**Requisitos:**
Conhecimentos em: Java, GIT, Android Studio e Fire Base
Será considerado um diferencial conhecimentos em Kotlim 

**Contratação:**
PJ a combinar

**Como se candidatar:**
Por favor envie um email para vagas@shopper.com.br com seu CV em anexo - enviar no assunto: Desenvolvedor Android

**Comment by jpventura** [comment]
Olá, @VivianeCrisogano! A vaga continua aberta ou podemos encerrá-la?

**Comment by jpventura** [comment]
Olá, @VivianeCrisogano! Essa vaga inda está aberta?

**Comment by VivianeCrisogano** [comment]
Olá!

Pode encerrar.

Obrigada!



Em Dom, 24 de jun de 2018 07:11, JP Ventura <notifications@github.com>
escreveu:
