### ISSUE TITLE
[Rio de Janeiro, RJ] Desenvolvedor Android - Freelance

### ISSUE THREAD

**Issue by wiltonneto** [androiddevbr/vagas#41]
App Android para tablet a ser posicionado em gôndolas de supermercado para clientes consultarem receitas.
- 3 telas: menu principal, entrada de dados, conteúdo da receita.
- a instalação do app será controlada e feita manualmente.
- o app deverá ficar em kioskmode (desabilitar botões que dariam ao usuário controle ao device).
- o app não pode contar com internet para funcionar.

Esse projeto é simples e bem definido. Tem um designer, uma produtora de conteúdo e um gerente. O início é a partir do dia 18 de Julho.

Pode ser remoto. O projeto será no Rio de Janeiro.

**Comment by walmyrcarvalho** [comment]
@wiltonneto Wilton, tudo bem? A vaga tem um template descritivo, peço que atualize para o formato correto, similar a esse link: https://github.com/androiddevbr/vagas/issues/new

**Comment by walmyrcarvalho** [comment]
Título editado para se adequar ao formato dos outros anúncios do repositório.

**Comment by otaviommendes** [comment]
Gostaria de me candidatar a esse freela. Como faço? Meu perfil do LinkedIn, inclusive com alguns projetos nos quais trabalhei mais recentemente. Obrigado.

**Comment by walmyrcarvalho** [comment]
@wiltonneto Por favor, você pode ajustar a descrição da vaga ao formato do template, incluindo o contato? O @otaviommendes está interessado na vaga.

**Comment by mariofelesdossantosjunior** [comment]
Tenho interesse em se candidatar ... http://mariofelesdossantosjunior.890m.com/
Obrigada

**Comment by halysongoncalves** [comment]
Já preencheu?

**Comment by mariofelesdossantosjunior** [comment]
Já contrataram?

**Comment by walmyrcarvalho** [comment]
@wiltonneto Caso a vaga já tenha sido fechada, peço que nos avise pra que a gente dê um close na issue, senão as pessoas vão achar que a oportunidade ainda está aberta. OK? :)

**Comment by RichardSilveira** [comment]
A oportunidade ainda está aberta?

**Comment by walmyrcarvalho** [comment]
Fechada por falta de contato do dono da issue!
