### ISSUE TITLE
[Remoto] Desenvolvedor(a) Android Pleno/Sênior | Tabmedia

### ISSUE THREAD

**Issue by vncmaciel** [androiddevbr/vagas#412]
**Sobre a empresa:**

A Tabmedia é uma plataforma de gestão de conteúdos de Marketing e Treinamento capaz de gerenciar, segmentar, distribuir e mensurar conteúdos estáticos e interativos em tempo real. 
Atualmente, a solução é utilizada por 50 empresas,  em 7 países somando mais de 15.000 usuários ativos.

**Requisitos:**

3+ anos de experiência com Android
Conhecimento avançado em Java
Clean Code
Arquitetura MVP, MVVM e afins
Reactive programming - RxAndroid, RxJava
Custom Views
Testes automatizados com jUnit
Testes automatizados com Espresso
Git
Inglês técnico (leitura)

**Diferenciais:**

Scrum
Kotlin
Dagger
CircleCI ou afins
React Native
Swift

Enviar cv para: vagas@tabmedia.com.br

**Comment by leonardoaramaki** [comment]
How to apply?

**Comment by vncmaciel** [comment]
Sorry, @leonardoaramaki. Send your Résumé to vagas@tabmedia.com.br. Tks.

**Comment by jpventura** [comment]
Olá, @vncmaciel! Essa vaga inda está aberta?

**Comment by vncmaciel** [comment]
Opa, @jpventura. Já fechou.

**Comment by vncmaciel** [comment]
Opa, @jpventura. Já fechou.
