### ISSUE TITLE
[São Paulo, SP] Estágio Android Developer | EspressoLabs

### ISSUE THREAD

**Issue by espressolabsbr** [androiddevbr/vagas#413]
## Descrição da vaga

Buscamos um desenvolvedor que deseja viver a flexibilidade e aventura de uma startup, sem correr os riscos atrelados.  Somos uma empresa pequena em rápido crescimento e queremos encontrar uma pessoa para crescer rapidamente junto conosco.  Gostamos apenas de profissionais que gostem de autonomia e que prezem pela excelência.

## Local

Escritório em São Paulo - Perdizes, 5 min a pé do metrô Sumaré

## Benefícios

- Café e comida à vontade
- Clima muito descontraído
- Time jovem e talentoso
- Espaço para inovação
- Liberdade técnica (e responsabilidade)
- Projetos de grande porte e impacto

## Requisitos

Obrigatórios
- 1+ ano de experiência com Android Nativo
- Boa organização de código
- Bom conhecimento de APIs REST
- Git

## Contratação

Estágio remunerado

## Nossa empresa

A Espresso Labs surgiu da ideia de aliar uma casa de código à uma consultoria estratégica. Acreditamos que códigos, plataformas e aplicativos devem fazer sentido a vida e no contexto do cliente. Nosso processo de desenvolvimento não começa no computador. Buscamos entender primeiro quais são as necessidades específicas e que tipo de tecnologias podem atingir melhor o público alvo. Apresentamos uma série de soluções possíveis e escolhemos junto do cliente aquela que faz mais sentido. Na parte de desenvolvimento nossa equipe conta com desenvolvedores das melhores universidades de São Paulo. Soluçōes digitais, resultados concretos.

## Como se candidatar

Por favor envie um email para development@espressolabs.com.br com seu CV anexado - enviar no assunto: Vaga Android Nativo

**Comment by jpventura** [comment]
Olá, @espressolabsbr! Essa vaga inda está aberta?
