### ISSUE TITLE
[SP - Vila Olímpia] ZxVentures/Ambev/Zé Delivery - Desenvolvedor Android Sênior

### ISSUE THREAD

**Issue by sergiohenriquefp** [androiddevbr/vagas#415]
## DESCRIPTIONS
We are a global disruptive growth group, incubator, and venture capital team backed by one of the largest multinational companies in the world, Ambev. Our trade is dreaming up what the future looks like, today. We are a small army of futurists, dreamers, doers, designers, engineers, scientists, marketers, brewers, builders, and data geeks. For us, the future is now.

We are developing a global platform where customers from many countries will be waiting for their cold beers! You will work with people with multidisciplinary skills (PO, UX / UI, Developers and QAs) in order to deliver the best experience for our user. If you are passionate about a good interface using the latest in mobile technology, this opportunity is for you!

## POSITION

- Sênior
- Presential and CLT

###### Must have experience

- Developing and designing advanced applications on the Android platform;
- Agile methodologies.
- Experience with REST APIs and other external data sources.
- Have more than 3 years in proven mobile development.
- Work with different device dimensions (tablet, cell phone, etc...).
- General knowledge of the mobile environment, such as architectures, standards, trends and emerging technologies.
- Familiar with the process of submitting apps to the Play Store.

###### Nice if you have experience

- iOS 
- React Native
- Continuous Integration/Continuous Deploy (Travis)
- Experience with unit tests / automated ui tests.
- Fetch GraphQL APIs

## BENEFITS

- Attractive compensation package
- Health, dental and life insurance
- GymPass
- Meal allowance

## HOW TO APPLY
Here: https://zx-ventures.workable.com/jobs/550981

**Comment by jpventura** [comment]
Olá, @sergiohenriquefp! Essa vaga inda está aberta?
