### ISSUE TITLE
[São Paulo - SP] Desenvolvedor Android  Sênior | Concrete 

### ISSUE THREAD

**Issue by alinerachel** [androiddevbr/vagas#416]
## Descrição da vaga

Procuramos desenvolvedores Android Seniores para fazerem parte de um time que orquestra os robozinhos verdes para ser um dos canais de maior impacto para nosso clientes. O desenvolvimento Android (que pode ser apps, Android Things, Auto, TV, Chrome OS, etc) é crucial para dar cara a um produto digital. Nosso time vive de discussões sobre essa plataforma desde o design (Material?) até a arquitetura (MVP, MVC, MVVM, MVI, Clean, Architeture Components, etc), testes (locais e instrumentados) e instrumentação (hit analytics, performance, conversão e etc.)

Aqui, você fará parte de um time com mais de 50 devs Android, que possuem sua própria comunidade. Temos vários colegas que são referência, somos o time com maior participação em eventos do Brasil, temos reuniões bi-semanais para discussão e troca de ideias e promovemos treinamentos dos mais diversos temas. Ainda criamos e mantemos projetos Open Source na plataforma e fazemos parte do programa do Google de Agências (GDA, Google Developers Agency).

Venha mover o mundo com o capítulo de Android!

#SomosConcrete #TrabalheComOsMelhores 

## Local

- Escritório em São Paulo - Berrine

## Benefícios

- Vale Refeição
- Assistência Médica
- Assistência Odontológica
- Gympass
- Aulas de Inglês
- Auxílio na realização de Cursos e Certificações
- App Colaboradores
- Acesso a constante tecnologias de ponta
- Plano de Carreira e Desenvolvimento

## Requisitos

Para ser um dev Android Sênior aqui, buscamos pessoas que:

- Entendam sobre a composição de aplicativos Android em estrutura, APIs e performance;

- Entendam o ciclo de vida de aplicações e componentes do Android (Application, Activity, Service, ContentProvider, etc);

- Saibam quais os desafios de desenvolvimento a plataforma nos propõe (manter estado, concorrência, guia de estilos e etc);

- Tenham bom entendimento sobre arquitetura de sistemas (seja GUIs reativas, SOLID, KISS, etc);

- Conheçam formas de instrumentação de aplicativos (Hit Analytics, performance, conversão de uso);

- Entendam formas de ciclo de vida de um aplicativo: como o código evolui da máquina do desenvolvedor até produção;

- Sigam boas práticas de desenvolvimento das linguagens em uso (Java e Kotlin);

- Conheçam sistemas de versionamento de código, preferencialmente GIT;

- Conheçam o build system padrão da plataforma (atualmente o Gradle);

- Entendam sobre práticas de teste: importância, propósito e prática;

- Saibam trabalhar em time;

- Tenham vontade de se envolver com o que faz (tornar-se parte do problema e da solução).

## Contratação

CLT Full + Benefícios

## Nossa empresa

Somos a Concrete, uma empresa da Accenture especializada em produtos digitais, e estamos em constante movimento. Trabalhamos junto às maiores companhias do Brasil para garantir a transformação digital. Para isso, usamos design, desenvolvimento ágil e nossa cultura de inovação. Trabalhamos com tendências, mas não seguimos passos: criamos os nossos caminhos, que viram referência. 

Procuramos desenvolvedores Android para fazerem parte de um time que orquestra os robozinhos verdes para ser um dos canais de maior impacto para nosso clientes. O desenvolvimento Android (que pode ser apps, Android Things, Auto, TV, Chrome OS, etc) é crucial para dar cara a um produto digital. Nosso time vive de discussões sobre essa plataforma desde o design (Material?) até a arquitetura (MVP, MVC, MVVM, MVI, Clean, Architeture Components, etc), testes (locais e instrumentados) e instrumentação (hit analytics, performance, conversão e etc.)

Aqui, você fará parte de um time com mais de 50 devs Android, que possuem sua própria comunidade. Temos vários colegas que são referência, somos o time com maior participação em eventos do Brasil, temos reuniões bi-semanais para discussão e troca de ideias e promovemos treinamentos dos mais diversos temas. Ainda criamos e mantemos projetos Open Source na plataforma e fazemos parte do programa do Google de Agências (GDA, Google Developers Agency).

Vem mover o mundo com a gente!

#SomosConcrete #TrabalheComOsMelhores 

## Como se candidatar

Por favor envie um email para trabalheconosco@concrete.com.br com seu CV anexado - enviar no assunto: Vaga Android Sênior

**Comment by jpventura** [comment]
Olá, @alinerachel! Essa vaga inda está aberta?
