### ISSUE TITLE
[São Paulo, SP] - Android Developer - Easy Carros

### ISSUE THREAD

**Issue by rsicarelli** [androiddevbr/vagas#42]
## Descrição da vaga

Buscamos pessoas ambiciosas para integrar a nossa equipe de desenvolvimento e surpreender os nossos clientes e profissionais com produtos incríveis!

Embora busquemos pessoas excepcionais, não diferenciamos profissionais jovens daqueles experientes, pois acreditamos que valor é criado através de inteligência, espírito empreendedor, capacidade de execução e meritocracia. O perfil importa mais que o nível de escolaridade - quanto mais hungry, melhor. Por trás da empresa, está um time incrível de pessoas e investidores com vasta experiência em algumas das empresas mais conhecidas do mercado: Ambev, Easy Taxi, Helpling, Zocprint, Airu, etc. Trabalhamos duro para transformar a maneira com que as pessoas se relacionam com seus carros e se você não está alinhado com essa cultura, por favor, não se inscreva.

Integrando a equipe, sua primeira tarefa será acompanhar e colaborar com o desenvolvimento dos nossos aplicativos nativos em Android, trabalhando lado a lado com Marcio William, Founder & CIO da Easy Taxi! ;)
## Responsabilidades
- Criar e manter aplicativos em Android
- Pesquisar novas tecnologias e soluções relevantes
## Local

Somente presencial, em São Paulo, Capital. O escritório fica em Cerqueira César, ao lado de Pinheiros, a 900m do metrô Sumaré.
## Benefícios
- Espaço, estímulo e suporte para se desenvolver e crescer de forma meteórica
- Aprendizado constante
- Oportunidade de Equity
- Meritocracia
- Oportunidade de colocar a teoria em prática
- Interação com outras startups (Bee Cambio, Singu, F(x), Choppup) da venture builder eGenius (grupo do qual fazemos parte)
- Contato direto com grandes empreendedores
- Oportunidade de contribuir efetivamente para a evolução de uma startup em crescimento acelerado (aqui, suas ações e opiniões podem causar grandes impactos)
- Ambiente descontraído e dinâmico
## Requisitos

Obrigatórios
-3+ anos de experiência comprovada na criação de aplicativos Android nativos
- Conhecimentos sólidos em Java/Android SDK
- Conhecimentos sólidos em POO e Design Patterns
- Consumo de APIs RESTful
- Conhecimentos em Git
- Residir na cidade de São Paulo ou região
- Interesse em aprender constantemente
- Seja atento aos detalhes
- Inglês técnico

Diferenciais
- Possuir conhecimentos em GraphQL
- Possuir conhecimentos em MEAN Stack
- Possuir conhecimentos em AWS
- Possuir conhecimentos em iOS
- Possuir apps publicados
- Possuir conhecimentos em testes unitários
- For formado em Ciência da Computação ou cursos relacionados
- For fluente em inglês
## Contratação

PJ a combinar
## Como se candidatar

[Preencher o formulário](easycarros.typeform.com/to/oZBc1O) ou mandar e-mail para marcio@egenius.com.br

**Comment by heitornascimento** [comment]
O link do formulário está quebrado.

**Comment by walmyrcarvalho** [comment]
@rsicarelli Essa vaga ainda está aberta? Senão irei fechar essa issue!
