### ISSUE TITLE
[SP - Faria Lima] Desenvolvedor Android Pleno/Senior

### ISSUE THREAD

**Issue by JessicaTurra** [androiddevbr/vagas#423]
## Altran
A Altran é uma empresa multinacional Francesa que atua em consultoria de inovação tecnológica e está presente em mais de vinte países. Atua no segmento financeiro, Telecom, Automotivo, Aeroespacial, energia e TI. Na Europa a Altran é Líder em inovação tecnológica. No Brasil, estamos em um crescimento exponencial e com diversos projetos em todo território nacional.

## Posição
Pleno/Sênior

## Tipo de contratação
CLT, tempo indeterminado. 

###### Obrigatórios
- Java

###### Desejáveis
- Kotlin
- Metodologias ágeis (Scrum)
- Arquitetura Viper

## Como aplicar
Enviar currículo com pretensão salarial para:
jessica.turra@altran.com.br

## Contato
Linkedin: Jessica Turra
Cel/Whats: (41) 98838-5918

**Comment by jpventura** [comment]
Olá, @JessicaTurra! Essa vaga inda está aberta?
