### ISSUE TITLE
[Alphaville - Barueri, SP] Desenvolvedor(a) Android Sênior | VC+

### ISSUE THREAD

**Issue by caiopg** [androiddevbr/vagas#424]
## Sobre a VC+

A VC+ é uma Fintech, spin-off da Brasil/CT, que nasce com o desafio de facilitar o dia-a-dia das pessoas ao reunir diversos meios de pagamento em uma mesma plataforma, permitindo que o usuário realize seus pagamentos como quiser de um modo simples e fácil, no varejo físico e online.
## Descrição da vaga

O profissional ficará responsável por entregar e manter projetos focado em uma plataforma de serviços para atender aplicações mobile, e trabalhará com Continuous Delivery entregando não só produtos, mas valor ao usuário final. Utilizamos frameworks/práticas ágeis, dentre elas Scrum, Kanban e Management 3.0. Buscamos pessoas que agreguem conhecimento e novas idéias, para usar sua criatividade e gerar novos aprendizados e descobertas. Aliamos liberdade de criação e implementação de novas tecnologias com qualidade de entrega, e fazemos disso nosso diferencial.

## Local

Alphaville - Barueri, SP

## Benefícios

- Flexibilidade de horário
- Plano de saúde
- Plano Odontológico
- Férias remuneradas
- VA/VR
- Auxilio Transporte
- Oportunidade de trabalhar em um time empoderado para dar idéias e aplicar mudanças
- Local de descompressão
- Serviços in-company (3,2,1 Beauty)

## Requisitos

Obrigatórios
- 5 ou mais anos de experiência em projeto / implementação / aplicações distribuídas de alta disponibilidade e escalabilidade.
- Conhecimento prático de ferramentas e metodologias de desenvolvimento de software
- Experiência em desenvolvimento de aplicativos para dispositivos móveis
- Familiaridade com APIs RESTful para conectar aplicações Android para serviços back-end
- Forte conhecimento de princípios de design, patterns e melhores práticas de Android UI
- Experiência com armazenamento offline, threading e tuning de performance
- Conhecimento do ecossistema Android open-source e as bibliotecas disponíveis para tarefas comuns
- Habilidade de entender requisitos de negócio e traduzi-los em requisitos técnicos
- Familiaridade com APIs de mensagens em nuvem e notificações push
- Entendimento dos princípios de design e guias de interface do Google
- Entendimento proficiente de ferramentas de versionamento de código, como Git
- Familiaridade com integração contínua
- Forte conhecimento com arquitetura de componentes Google com MVP, MVVM
- Forte conhecimento com padrões de projeto (Design Pattern)

Desejáveis
- Forte conhecimento com injeção de dependência utilizando Dagger 2
- Experiência em desenvolvimento de aplicativos financeiras (fintech)
- Benchmarking e otimização
- Conhecimento de segurança em aplicações mobile

Diferenciais
- Conhecimento de Infraestrutura como serviço, em especial Amazon Web Services.
- Ter contribuído com algum projeto open source
- Conhecimento em nodejs, Angular, React

## Contratação

PJ ou CLT a combinar (possuem os mesmos benefícios)

## Como se candidatar

Mandar e-mail com CV e Linkedin para marcio.rosa@vcmais.com

**Comment by jpventura** [comment]
Olá, @caiopg! Essa vaga inda está aberta?

**Comment by caiopg** [comment]
Está sim @jpventura

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
