### ISSUE TITLE
[São Paulo - Brooklin, SP] Desenvolvedor(a) Android Sênior | FolhaCerta

### ISSUE THREAD

**Issue by johndrinane** [androiddevbr/vagas#425]
## Local

São Paulo SP - Brooklin

## Nossa empresa

O FolhaCerta é uma startup que está revolucionando a maneira como o RH das empresas cuidam das suas rotinas. Tem apenas um ano e meio de vida, mas já deu passos importantes, está no programa inovaBra Startups do Bradesco, recebeu investimento, estando na fase de entrada no mercado e formação do time de vendas e de onboarding.

## Requisitos

•	Experiência de, no mínimo, 4 anos em desenvolvimento de aplicativos nativos Android.
•	Conhecimentos avançados em Java.
•	Conhecimentos avançados em Lean Programming e Clean Architecture.
•	Experiência no uso de Web Services (REST, JSON/XML). 
•	Ter preocupação com a parte visual dos aplicativos.
•	Adaptação de layouts para diferentes tamanhos de telas.
•	Experiência com Testes integrados.
•	Saber elaborar modelagem de dados.
•	Conhecer Design Patterns.
•	Habilidade de autogerenciamento e ser um Team Player.

## Diferenciais
•	Experiência com desenvolvimento de funcionalidades com câmera e reconhecimento facial.
•	Links com código no github e ou apps publicados.
•	Ter trabalhado com views customizadas.
•	Adaptar biblioteca de terceiro.
•	Experiência com Dagger, RxJava, Retrofit e EventBus.
•	Advanced or Intermediate English.

## Benefícios

•	Horário Flexível
•	No dress code
•	Estacionamento ou Vale Transporte (sem desconto no salário)
•	Vale Refeição

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Por favor envie um email para vagas@folhacerta.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Olá, @johndrinane! Essa vaga inda está aberta?
