### ISSUE TITLE
[SP - Faria Lima] Desenvolvedor Android Senior

### ISSUE THREAD

**Issue by marcelsanches2** [androiddevbr/vagas#426]
## Descrição da vaga
Estamos buscando desenvolvedores ou desenvolvedoras para construir aplicativos que irão reinventar a forma com que as pessoas lidam com os serviços financeiros.
Faça parte de um time ágil e colaborativo formado por pessoas fora da curva. Você poderá desenvolver aplicativos escaláveis e seguros, utilizando Clean Architecture, Reactive Programming e o que há de mais moderno no desenvolvimento de aplicativos Android. #TheNextBigFin

## Local
Presencial - Faria Lima 

## Benefícios
- Vale Refeição - valor acima da média;
- Vale Alimentação - para compras em mercado;
- Convênio médico para todos os dependentes;
- Plano de bonificação diferenciado.

## Requisitos
Desenvolver nas linguagens Java e Kotlin;
Desenvolver testes unitários e instrumentados;
Conhecer os frameworks mais utilizados do mercado.

## Desejáveis
Conhecimentos em Clean Architecture e Reactive Programming;

## Contratação
CLT Full

## Como se candidatar
Para se candidatar a vaga acesse o link https://thenextbigfin.gupy.io/jobs/7316 e faça nosso desafio em https://bitbucket.org/TheNextBigFin/androidchallenge

**Comment by jpventura** [comment]
Olá, @marcelsanches2! Essa vaga inda está aberta?
