### ISSUE TITLE
[São Paulo - SP] Pessoa Desenvolvedora Mobile 

### ISSUE THREAD

**Issue by stephanioliveira** [androiddevbr/vagas#427]
## Nossa empresa

O Pagar.me é uma empresa brasileira de tecnologia de pagamentos online, que trabalha para descomplicar o recebimento de todo tipo de pagamento pela internet.

## Descrição da vaga

Aqui no Pagar.me unimos profundidade técnica com sede de desenvolver produtos. Por isso buscamos pessoas que se identifiquem:

- Gostar e querer aprender
- Conhecer alguma linguagem orientado a objetos (Usamos Kotlin)
- Não fugir de problemas difíceis 
- Trabalho em equipe (pair programming)
- Cultura Open Source ,  gostar de compartilhar conhecimento
- Preocupação com qualidade de software (testes automatizados, code review)
- Conhecimento e interesse em interface 

Com o que você vai trabalhar no dia a dia:

- Desenvolvimento de aplicativo mobile e interação com time de backend e UI
- Comunicação com APIs
- Participar de decisões de negócios e tecnologia

O que temos por aqui:

- Acompanhamento de desenvolvimento pessoal e de carreira
- Horário flexível 
- Diversidade de pessoas e diversidade de ideias 
- Aqui todo mundo tem voz e as decisões são tomadas em conjunto, sempre que possível. 
- O feedback aqui rola de verdade
- Ambiente cheio de mudanças
- Participar na contratação de pessoas incríveis pro nosso time

## Local

Escritório São Paulo - Vila Olímpia

## Contratação
CLT

## Como se candidatar
Se você se identifica com a nossa missão de descomplicar o mercado de pagamentos no Brasil e quer fazer parte desse time, veja as nossas vagas e mande o seu CV pra gente! https://jobs.kenoby.com/pagarme

**Comment by jpventura** [comment]
Olá, @stephanioliveira! Essa vaga inda está aberta?
