### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android PLENO | 4MOVE

### ISSUE THREAD

**Issue by MarcusMoraes4MOVE** [androiddevbr/vagas#428]
## Descrição da vaga
Desenvolvedor Android Pleno

- Experiência em desenvolvimento de sistemas mobile. 
- Experiência com desenvolvimento ágil / SCRUM
Conhecimento em: 
- Java e bibliotecas para desenvolvimento de front end mobile Android
- Integração de aplicativos com API´s REST
- Repositório de código git 
-  Domain Driven Design (DDD)
-  Linguagem Java
-  Framework Spring
-  Java Script e frameworks específicos para front-end web (como Angular, React)

Responsabilidades
Atuar com as atividades de desenvolvimento interno dos sistemas da empresa. 
Apoiar na sustentação dos sistemas atuais, tratamento de incidentes e evolução dos produtos desenvolvidos nessa plataforma.

## Local
São Paulo - Alto Pinheiros - 4MOVE
Trabalho no Local - PRESENCIAL

## Benefícios

- Flexibilidade de horário
- Plano de saúde
- Férias remuneradas
- VR
- Auxilio Transporte
- Local de descompressão
- Oportunidade de trabalhar em um time empoderado para dar idéias e aplicar mudanças
- Aula de Inglês in Company

## Requisitos
Obrigatórios
- 2+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis
- Experiência com Espresso e UI Automator
- Experiência com RxJava

## Contratação
CLT / PJ a combinar

## Nossa empresa
4MOVE

MISSÃO
Reduzir o transito no mundo, tornando a mobilidade urbana eficiente e mais ecológica.

Visão
Trabalhar com excelência transmitindo conforto e confiança ao cliente, ser inovadora com presença global, excelência no desenvolvimento de serviços e no atendimento dos nossos colaboradores, parceiros, e clientes finais.

Valores e Crenças
Ética profissional, Credibilidade e Responsabilidade social.

## Como se candidatar

Por favor envie um email para george@4move.me e marcus.moraes@4move.me com seu CV anexado - enviar no assunto: Vaga Android PLENO

#

**Comment by jpventura** [comment]
Olá, @MarcusMoraes4MOVE! Essa vaga inda está aberta?
