### ISSUE TITLE
[São Paulo, SP] - Software Engineer, Mobile Applications (Android) - GetNinjas

### ISSUE THREAD

**Issue by rsicarelli** [androiddevbr/vagas#43]
## Descrição da vaga

You will work with our small and strong development team to create innovative and high scale solutions to change the way people hire services providers. You will be responsible for contributing to all aspects of defining, building and maintaining our mobile applications, mainly the Android app.
## Local

Sao Paulo - Pinheiros
## Benefícios
- Competitive compensation
- Benefits and Perks
- Health insurance
  Transit and meal vouchers
- Free snacks and beverages at the office
- Strong network with like-mind high-impact entrepreneurs and early stage investors.
- Possibility to have a huge positive impact and change the way people use the internet.
- An exciting and fun-to-work environment
## Requisitos

You’re self-motivated, idealistic and want to be part of something huge, from the very start. Of course, you’re smart, creative, accomplished, energetic and communicative. You are a strong team player that's comfortable working in an awesome start-up environment. You also love challenges and have passion employing technology for solving difficult problems. Simply put, a fun-to-work-with A-player.
- 3+ years designing and implementing mobile Android applications
- 5+ years experience with Java language
- Solid working knowledge of the Android framework: theming, custom views, resources, etc
- Solid working knowledge of Android development tools: gradle, adb, Android Studio, 1st and 3rd party libraries and tools, etc
- Experience working JSON via RESTful interfaces
- Good understanding of software development best practices
- Excellent communication skills
- Git (we love it!)
- Agile, Iterative Development
- TDD and/or BDD experience

**What would be nice**
- Knowledge of other mobile platforms like iOS, Windows Phone, etc.
- Experience developing RESTfull APIs
- Great portfolio of published apps
## Contratação

CLT
## Como se candidatar

https://getninjas.workable.com/jobs/36699/candidates/new

**Comment by walmyrcarvalho** [comment]
@rsicarelli Essa vaga ainda está aberta? Senão irei fechar essa issue!
