### ISSUE TITLE
São Paulo - Metrô Saúde - Desenvolvedor(a) Android Pleno.

### ISSUE THREAD

**Issue by wagner-pansani** [androiddevbr/vagas#432]
## Descrição da vaga

Temos um projeto em andamento para realizar pesquisas de mercado (pesquisas de satisfação e recomendação de produtos, por exempko) e estamos precisando de um(a) desenvolvedor(a) em Android Studio com java para participar da conclusão do projeto.

A contratação é como PJ com prazo definido até 12/2018.

## Local

Presencial - Metrô Saúde - Presencial.

## Benefícios

- 1 hora de almoço

## Requisitos

Obrigatórios
- 2+ anos de experiência com Android nativo
- Linguagem Java
- Controle de versão usando TFS
- Padrão MVVM

## Contratação

PJ a combinar

## Nossa empresa

A HSR Tech é uma empresa da holding HSR e somos responsáveis por toda a parte tecnológica do grupo, o sistema que estamos desenvolvendo é mais uma das soluções que será integrada ao nosso portfólio.

## Como se candidatar

Por favor envie um email para wagner.pansani@hsrtech.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Tudo bem @wagner-pansani? Essa vaga ainda está aberta?

**Comment by wagner-pansani** [comment]
Olá, a vaga já foi preenchida.

Um abraço,

WAGNER PANSANI

[cid:image004.png@01D23689.1C6842A0]<http://hsrtech.com.br/>


+55 11 3089-7122 | +55 11 98272-3983

hsrtech.com.br<http://www.hsrtech.com.br/>




De: JP Ventura <notifications@github.com>
Enviada em: segunda-feira, 25 de junho de 2018 08:55
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: Wagner Pansani <wagner.pansani@hsrtech.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] São Paulo - Metrô Saúde - Desenvolvedor(a) Android Pleno. (#432)


Tudo bem @wagner-pansani<https://github.com/wagner-pansani>? Essa vaga ainda está aberta?
