### ISSUE TITLE
[Campinas] Desenvolvedor(a) Android JR/PL/SR | Venturus

### ISSUE THREAD

**Issue by alex-tavella** [androiddevbr/vagas#433]
## Descrição da vaga

​Esta oportunidade é para você que tem domínio em estrutura de dados e algoritmos, possui conhecimento em Java e/ou C/C++ e também tem interesse em aprender e trabalhar com novas tecnologias.

Suas responsabilidades serão voltadas para desenvolvimento de melhoriasnas aplicações ou no framework (middleware) Android, integrar correções de pacotes provenientes de terceiros, investigar e corrigir problemas nos respectivos aplicativos, frameworks, criação e prototipação de novas funcionalidades. Além disso, estará em contato com o cliente, que é multinacional da área de manufatura de eletrônicos.

Gostou? Então inscreva-se e participe de nosso processo seletivo!

Vagas também para pessoas com deficiência.​

## Local

Campinas

## Benefícios

- 1 hora de almoço
- Plano de Saúde
- Plano Odontológico
- Vale Refeição
- Vale Alimentação
- Liberação de horas para mestrado/doutorado

## Requisitos

Obrigatórios
​- Ensino superior completo em Ciências da Computação, Engenharia da Computação e áreas afins;

Desejáveis
- Excelentes conhecimentos em programação e depuração de código (domínio de orientação a objetos);
- Experiência com desenvolvimento para aplicações móveis;
- Conhecimento em Java;
- Inglês intermediário para leitura, escrita e conversação.

Diferenciais
- Experiência com Git;
- Conhecimento de aplicações Android de Contatos, Telefone, Messaging, Dual SIM;
- Conhecimento de Android framework (middleware) ou framework (middleware) de outras plataformas móveis: Connectivity,Telephony, Messaging, UI Framework, OpenGL.​

## Contratação

CLT

## Nossa empresa

http://www.venturus.org.br/

## Como se candidatar

http://vagas.venturus.org.br/Candidatese.aspx?IDVaga=116

**Comment by guilhermeoa07** [comment]
Processo seletivo pode ser remoto?

**Comment by jpventura** [comment]
Tudo @alex-tavella? Essa vaga ainda está aberta?

**Comment by alex-tavella** [comment]
@jpventura está sim

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
