### ISSUE TITLE
[SP | Vila Olímpia | Cubo] Desenvolvedor(a) Android - Carreira Beauty

### ISSUE THREAD

**Issue by vixandrade** [androiddevbr/vagas#434]
## Nossa Empresa

Somos uma startup focada no setor de beleza profissional, "empoderamos" e turbinamos as redes sociais de negócios e profissionais da beleza no Brasil através de conteúdo, marketing digital e tecnologia. Somos uma das startups residentes do Cubo na Vila Olímpia em São Paulo.

## Descrição da Vaga

Procuramos um programador ou programadora com experiência em desenvolvimento de aplicativos nativos em Android para atuar no desenvolvimento de novas features, manutenção e refatoração do aplicativo Ahazou ([Veja na Play Store](https://play.google.com/store/apps/details?id=ahzproapp.carreirabeauty.com.ahz_pro)).

## Local
Cubo
Rua Casa do Ator, 919.
Vila Olímpia - São Paulo

(Mudaremos nos próximos meses para o novo prédio gigante do Cubo, ainda na Vila Olímpia)

### Básicos
- 3+ anos de experiência com desenvolvimento Android nativo e com apps publicados
- Integração e uso de APIs REST
- Conhecimento de Design Patterns (MVP, MVVM, Clean) e visão de como aplicá-los no desenvolvimento
- Versionamento com Git
- Uso de ferramentas de tracking, analytics e crash reports (Fabric, MixPanel, etc)
- Experiência com ferramentas como Firebase e SQLite

### Desejáveis
- Experiência com metodologias ágeis
- Ter trabalhado em Startup
- Experiência com testes em mobile

## Contratação e Salário
PJ - A combinar (dependendo da senioridade)

## Como se Candidatar
Enviar um email com CV e link do GitHub para victor@carreirabeauty.com e assunto "Desenvolvedor(a) Android"

## Labels
- PJ
- Senior
- Pleno

**Comment by jpventura** [comment]
Tudo bem @vixandrade? Essa vaga ainda está aberta?

**Comment by vixandrade** [comment]
@jpventura está sim, mas não vieram candidatos. Pode fechar se quiser.

**Comment by jpventura** [comment]
@vixandrade normalmente temos uma boa responsividade com as vagas aqui. O que pode ter acontecido é ela ter ficado no nas últimas páginas dos issues e ter passado despercebido.

Se quiser, pode postar novamente ou reabrir o issue. Eu recomendaria criar um novo para aparecer no topo :smile:
