### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor(a) Android | Involves

### ISSUE THREAD

**Issue by nadocoelho** [androiddevbr/vagas#435]
## Descrição da vaga

Ter capacidade de avaliar e criticar ferramentas e metodologias de desenvolvimento, apontando para uma escolha ideal de acordo com a necessidade do projeto. Apresenta argumentos concretos que confirmem sua opinião e é referência para os demais desenvolvedores. Possui aptidão para repasse de conhecimentos ou treinamentos. Domina técnicas de refactoring e tira proveito de padrões de projeto. É alinhado ao conceito de artesão de software.

## Local

Apenas presencial
Florianópolis - SC

## Benefícios

- Horário semi-flexível
- Vale Refeição
- Vale Transporte
- PLR (distribuição dos lucros da empresa)
- Programas de Involvimento: são atividades pagas pela empresa para aumentar a interação entre os colaboradores. Dentro dos planos nós temos: Academia, Massagem, Yoga, Kart, Paintball, Futebol, Rafting...

## Requisitos

Obrigatórios
- Entendimento de Android SDK e API's.
- Conhecimento da linguagem Java.
- Conhecimento do paradigma de Orientação a Objetos.
- Base sólida de algoritmos e estrutura de dados.
- Escrever código limpo e de fácil manutenção.
- Experiência com versionamento Git.
- Experiência com o padrões arquiteturais da plataforma Android.
- Conhecimentos em SQLite.
- Confortável em trabalhar com ferramentas e metodologias ágeis.
- Habilidade para resolver problemas rapidamente.
- Mindset criativo e analitico.

Desejáveis
- Experiência com testes, incluindo TDD, BDD e Android Test Library.
- Experiência com o padrão arquitetural MVVM na Plataforma Android.
- Kotlin, Data Binding e RxJava
- Alinhamento com o mindset UX.

Diferenciais
- Experiência com aplicações multi-thread
- Experiência com aplicações realtime
- Experiência com ferramentas de CI/CD

## Contratação

CLT
Nível: Pleno ou Sênior

## Nossa empresa

A Involves foi a vencedora do prêmio Melhores Empresas para Trabalhar 2016 e 2017 da GPTW
- Melhor empresa de T.I do Brasil (até 99 colaboradores)
- Melhor empresa de SC de todos os ramos de atuação (até 99 colaboradores)

No final de 2016 nos mudamos para uma nova sede e nossa estrutura está incrível!

![2](https://cloud.githubusercontent.com/assets/17482386/21590112/ef759a44-d0df-11e6-84b0-314ae3cca807.jpg)
![4](https://cloud.githubusercontent.com/assets/17482386/21590109/ef7504d0-d0df-11e6-81d7-3f76754c48a0.jpg)
![5](https://cloud.githubusercontent.com/assets/17482386/21590110/ef757aaa-d0df-11e6-820c-0862e378223d.jpg)
![6](https://cloud.githubusercontent.com/assets/17482386/21590111/ef759918-d0df-11e6-8488-e4cfe5f7099f.jpg)
![7](https://cloud.githubusercontent.com/assets/17482386/21590114/ef9164a4-d0df-11e6-9753-1e65d5af4465.jpg)
![9](https://cloud.githubusercontent.com/assets/17482386/21590117/ef929c48-d0df-11e6-938d-2c9c6e142c44.jpg)
![10](https://cloud.githubusercontent.com/assets/17482386/21590119/ef934c88-d0df-11e6-8ca2-5b86a075eff1.jpg)
![11](https://cloud.githubusercontent.com/assets/17482386/21590118/ef92d3b6-d0df-11e6-93c7-75623fcc1de1.jpg)
![12](https://cloud.githubusercontent.com/assets/17482386/21590116/ef91df42-d0df-11e6-8e23-6d554e168116.jpg)
![15](https://cloud.githubusercontent.com/assets/17482386/21590122/efaef0fa-d0df-11e6-8324-ceb413f239fe.jpg)
![16](https://cloud.githubusercontent.com/assets/17482386/21590123/efaf68c8-d0df-11e6-8194-ba30bc13cfee.jpg)
![17](https://cloud.githubusercontent.com/assets/17482386/21590124/efb4f8b0-d0df-11e6-82da-93f01e15a8be.jpg)

## Como se candidatar

Interessados devem entrar no link: [https://jobs.kenoby.com/involves/job/desenvolvedor-android/5ad88fc84d9afb6e2bbbe14e](https://jobs.kenoby.com/involves/job/desenvolvedor-android/5ad88fc84d9afb6e2bbbe14e) e preencher os dados.

**Comment by jpventura** [comment]
Tudo bem @nadocoelho? Essa vaga ainda está aberta?

**Comment by nadocoelho** [comment]
Bom dia @jpventura essa vaga aqui ainda está em aberto.

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
