### ISSUE TITLE
[Ribeirão Preto - SP] Android Developer | Crave Food Systems

### ISSUE THREAD

**Issue by shrpereira** [androiddevbr/vagas#437]
Link: https://crave.workable.com/jobs/608551

Description

Crave Food Systems is an innovation & technology company specialized in generating efficiency in the food service industry. Our product WhatsGood is an online marketplace that connects chefs and local food purveyors.

Purveyors find at WhatsGood a place to showcase and offer their products to purchasers, while efficiently managing their ordering process.

Purchasers find at WhatsGood a place to connect with purveyors and organize their local purchasing.
We currently have an office in Providence (RI – USA) and we are just opening a new office in Ribeirão Preto (SP – Brazil). **This position is a local position for the Ribeirão Preto office only.**

Are you able to understand backend developers and UX designers? Can you put their work together to make beautiful and useful mobile apps?

Independently of the position we expect that everyone get involved in the development process and be interested in the whole stack and product – there is no part of the system that is somebody's else problem.

Requirements

Some skills we would like to see in our candidates:

    Experience in Java and Kotlin languages (for Android position)
    Knowledge in modern mobile architectures like MVP, MVVM, Clean
    User Interface design and development following Material Design Guidelines
    Experience working with remote data via REST and JSON
    Experience with third-party libraries and APIs
    Solid understanding of the entire mobile development life cycle
    Comfortable working on Android Studio

Also, we would like you to have:

    Good understanding of git
    Ability to multi-task and work under pressure
    Passion for mobile technology and high quality engineering
    Strong skills on Unix/Linux environment
    Familiar with agile principles
    Know about automated building, deployment (CD/CI) and testing
    Know about Gradle customizations with Groovy, Flavors, Dimensions, etc
    Memory management and performance tuning

Benefits

Compensation:

    Junior: R$ 2000,00 to R$ 4000,00 (PJ)
    Pleno: R$ 5000 to R$ 7000,00 (PJ)
    Senior: R$8000 to R$10000,00 (PJ)

Other:

    Relocation package
    40h / week
    Quarterly bonus (up to 30% of salary each quarter)
    20 days off / year

**Comment by jpventura** [comment]
Tudo bem @shrpereira? Essa vaga ainda está aberta?
