### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Android Nativo |  NAVILLE BRASIL

### ISSUE THREAD

**Issue by danilo-righetto** [androiddevbr/vagas#438]
## Descrição da vaga

Desenvolvedor(a) Android Nativo - NAVILLE BRASIL

## Local

Escritório Guarulhos - São Paulo - Centro

## Benefícios

- 1 hora de almoço
- VT e VR
- Instale programas/so na sua maquina como quiser (respeitando o discernimento e o bom senso)

## Requisitos

Obrigatórios
- 6 meses de experiência com Android
- Bom conhecimento com Java
- Confortável com o software Android Studio
- Confortável com o versionamento usando o BitBucket

Diferenciais
- Projetos opensource
- Conhecimento do Kotlin

## Contratação

PJ a combinar

## Nossa empresa

A Naville Brasil é uma fabrica de software atendendo clientes de diversos segmentos. Conheça um pouco mais da nossa companhia pelo site http://navillebrasil.com

## Como se candidatar

Por favor envie um email para deboradressano.naville@gmail.com com seu CV anexado - enviar no assunto: Programador(a) Android - Naville

**Comment by jpventura** [comment]
Tudo bem @danilo-righetto? Essa vaga ainda está aberta?
