### ISSUE TITLE
Desenvolvedor Android Sênior - Líder Técnico ( 2 vagas)

### ISSUE THREAD

**Issue by jokapoa** [androiddevbr/vagas#439]
## Descrição da vaga

Atuação em projetos de grande porte, com time  altamente qualificado de profissionais  engajados com mobile e  a comunidade.
Aqui o desenvolvedor  precisa ser movido a desafios, gostar de inovação e buscar sempre fazer um código limpo, seguindo padrões

**## Local**
São Paulo

**## Benefícios**
Todos os benefícios de uma empresa de ponta e mais alguns...

## Requisitos
Sólida experiência com  projetos inovadores em android nativo.
Experiência com  Kotlin,  Rx Java e Retrofit  é fundamental.
Vivência com liderança técnica em projetos  de grande importância é desejável.
Gostamos de pessoas engajadas na comunidade, ligados em eventos na área de desenvolvimento.

## Contratação

CLT + beneficios

Envie seu curriculo para jonask@Holdenrh.com.br com informações de projetos de relevância ou apps publicados  e aguarde meu contato ou de minha equipe.
Se tiver fit com o que buscamos voltaremos a falar em breve para passar mais detalhes.

Att 
Jonas Kaffka
IT Headhunter

**Comment by jpventura** [comment]
Tudo bem @jokapoa? Essa vaga ainda está aberta?
