### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android | GetNinjas

### ISSUE THREAD

**Issue by ricardoalmeida** [androiddevbr/vagas#44]
## Descrição da vaga

Desenvolvimento de novas features no app do GetNinjas e novos projetos em Android.

## Local

Escritório São Paulo - Pinheiros

## Benefícios

- Vale refeição
- Desconto na compra de um notebook.
- Geladeira sempre cheia :P

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis
- Experiência com Espresso e UI Automator
- Experiência com RxJava

Diferenciais
- Projetos opensource

## Contratação

CLT

## Nossa empresa

Fundada em outubro de 2011, a GetNinjas é uma plataforma que conecta clientes a prestadores de serviços. Com mais de 200 mil profissionais cadastrados em todo o Brasil, divididos em mais de 100 subcategorias, e uma média de 130 mil cotações por mês no site, a empresa já captou mais de R$ 47 milhões de investimento da Monashees Capital, Kaszek Ventures e Tiger Global.

## Como se candidatar

Por favor dê um apply na vaga:
https://getninjas.workable.com/jobs/36699

**Comment by walmyrcarvalho** [comment]
@ricardoalmeida Ricardo, essa vaga é diferente da #43 ou representam a mesma posição?

**Comment by ricardoalmeida** [comment]
É a mesma. Vou fechar essa duplicada. Valeu!
