### ISSUE TITLE
[São Paulo, SP] Senior SW Android Engineer  | LexisNexis Risk Solution

### ISSUE THREAD

**Issue by febaisi** [androiddevbr/vagas#440]
## Descrição da vaga
Developement and maintance of a Telematics app. 

Key Responsibilities

- Participate in full lifecycle agile software development from Product Backlog all the way to Deployment
- Work with Business Analysts in translating business requirements into high level and /or Object Oriented design specification
- Define workload for Sprints and Monthly Releases

- Make the best design and implementation decisions to ensure, reusability, quality, efficiency, and scalability
- Elaborate, Design and Manage architecture and design documents

- Develop Mobile, APIs, SDKs applications and features through hands-on coding through a Continuous Delivery cycle
- Mentor software engineers and developers towards best practices and technologies around QA, Automation and Design Patterns
- Conduct project design reviews and code reviews
-Provide support for Product, QA, Infrastructure and other internal teams
- Mentor a small team of developers about methodology, DevOps practices and agile delivery models

- Work collaboratively with teams in Brazil and Internationally on leveraging solutions and promoting contributions to other international teams.

- Manage incidents, issues, bugs and defects

- Excellent communication skills - both written and verbal

Education and Experience
 

Education: B.S. in Computer Science or related or equivalent work experience
Fluent English and Portuguese Skills

Additional useful Qualifications
- Comfortable and passionate about using the latest technologies, tools, and techniques
- Experience with consuming REST services
- Self-motivated, detail oriented, and highly responsible
- Must be a fast learner and multi-tasker
- Sensor data experience (GPS, accelerometer) is a plus

- Location tracking app experience

- Experience with developing on SDKs for consumption by other Apps

- Experience of working with the Google Play Services SDKs

- Experience with Bluetooth or other peripheral device communications

## Local
Escritório - R. Bela Cintra 

## Benefícios

- Custom Machine
- Health and Dental Insurance
- Refeição & Alimentação
- Montly celebrations (Snacks, games and beers) 😄 

## Requisitos

The role requires a strong experience as a Full-stack Mobile Developer
Development experience in full life-cycle development and agile methodologies

Experience as Software Engineer on developing Mobile Applications
Solid Experience in Android and React Native technologies
Solid understanding of modern Android and React architectures, build tools, including Gradle and Android Studio, NPM, Node.js, Appium.

Experience in production environments: release management, testing and support running on Docker, Shell/Unix and AWS.

Experience with Git and Continuous Integration

Experience with backend communication and integrations (e.g. RESTful services)

Have one or two apps on Google Play or App Store, which you either developed yourself or can clearly demonstrate and describe your role in its construction. Or contributions to OSS and related public repositories, i.e. Github.

- Nice to have experience with iOS, Object-C and SWIFT.

## Contratação
CLT

## Nossa empresa

Big Data company technology, proprietary linking, and targeted solutions provide actionable insights that help make your organization more secure and efficient.
Find more in https://risk.lexisnexis.com . 

## Como se candidatar

Send an e-mail to felipe.baisi@lexisnexisrisk.com with your CV. 
You can also apply to our position on LinkedIn: https://www.linkedin.com/jobs/view/672785310

**Comment by jpventura** [comment]
Tudo bem @febaisi? Essa vaga ainda está aberta?
