### ISSUE TITLE
[São Paulo - Pinheiros, SP] Desenvolvedor Android | Worldpackers

### ISSUE THREAD

**Issue by diegoy** [androiddevbr/vagas#441]
## Descrição da vaga

Estamos buscando por alguém para trabalhar presencialmente em Pinheiros, São Paulo e que goste da responsabilidade de ser o principal dev do nosso aplicativo Android nativo.

## Local

Presencial no Escritório em São Paulo - Pinheiros

## Benefícios

- Vale alimentação
- Plano de saúde

## Requisitos

- Não para de aprender
- Ama Kotlin e Android
- Tem uma ideia de como funciona RxJava e Databinding
- Pira quando vê uma série de testes automatizados verdes
- Respira código limpo e clean architecture/MVP
- Já trabalhou com desenvolvimento Android Nativo
- Já teve experiência ou brincou com banco de dados Realm

**Diferenciais**

- É apaixonadx pela ideia de usar tecnologia para impactar a vida de milhões de pessoas ao redor do mundo
- Trabalha com autonomia & responsabilidade, participando ativamente das decisões do produto
- Se sente motivadx em um ambiente de startup global em constante mudança, testes e novas oportunidades
- Toma decisões baseadas em dados e feedback de usuários
- Tem um mindset de melhoria contínua, sempre desenvolvendo seus skills e entendimento do mercado & negócio
- Quer trabalhar com propósito com gente realmente boa!

## Contratação

CLT ou PJ a combinar

## Nossa empresa

A Worldpackers torna possível experiências incríveis de viagem que cabem no bolso. Somos uma comunidade de mais de 1.000.000 de viajantes e anfitriões trocando habilidades por acomodação ao redor do mundo. Imagine mochilar pela América do Sul ajudando hostels com recepção ou social media, voluntariar pelo Sudeste Asiático em ONGs & projetos sociais ou aprender sobre sustentabilidade em ecovilas & projetos ecológicos.

Temos um time de tecnologia enxuto e bem experiente para tornar a parte técnica na “parte fácil” e nos focar em melhorar, testar & crescer nosso produto & negócio.

## Como se candidatar

[Candidate-se aqui!](https://docs.google.com/forms/d/e/1FAIpQLSc7DK6K0dwmmmdBG9AHEiU2PVlFipB2317aiH7_wFSkYxszuw/viewform)

**Comment by jpventura** [comment]
Olá, @diegoy! Essa vaga ainda está aberta?

**Comment by diegoy** [comment]
Oi @jpventura já conseguimos preencher esta vaga, vou fecha-la
