### ISSUE TITLE
[São Paulo] Mobile (Ionic) - Sênior

### ISSUE THREAD

**Issue by AluanaDias** [androiddevbr/vagas#442]
## Descrição da vaga
**Startup** bem inovadora no ramo de logística que atua com tecnologias de ponta, tem um ambiente bem descontraído e uma equipe bem flexível, dispostos a aprender e absorver conhecimento.
O profissional irá planejar a arquitetura dos aplicativos mobile desenvolvidos pela empresa.
Atuar juntamente com a equipe de frontend na adoção de novos padrões e tecnologias javascript para equipe. Definir e estruturar o desenvolvimento dos novos aplicativos mobile que a empresa oferece ao mercado e mapear melhorias junto ao time nos aplicativos existentes.
Criar e codificar testes automatizados. Análise de possíveis fontes de erros e sempre corrigir os bugs de forma eficientes.

## Local
Presencial na - Vila Mariana, próximo ao metrô.

## Benefícios

- 1 horas de almoço
- Férias depois de um ano (Não remuneradas)
- Flexibilidade nos horários
- Ambiente descontraído

## Requisitos

Obrigatórios
- 3+ anos de experiência com Mobile Nativo
- Experiência ou contato com Node.JS, HTML5, CSS3, Ionic 3, Angular 1 e 4
- Antenado e ligado em outros frameworks como React, Vue, Ember, Mithril, etc.
- Conhecer o processo de publicação de aplicativos nas lojas Play Store (Android) e App Store (iOS).
- Trabalhar com gerenciadores de tasks como Gulp, Grunt
- Conhecer e estar disposto a aplicar novos conceitos como PWA, AMP, SWs e etc.
- Experiência significativa com aplicações modernas e APIs REST (json), ferramentas de testes como Jasmine, JS Mock e outras
- Experiência significativa com GIT

Desejáveis
- Métodos ágeis como Kanban ou Scrum.
- Aplicações responsivas, mobile first e pixel perfect concepts.

Diferenciais
- Querer atuar em Startup: Tecnologia e Soluções em Logística

## Contratação

PJ a combinar

## Nossa empresa

A 5A Attiva é uma consultoria especialista em identificar profissionais de alta performance em Tecnologia da Informação, especialmente na área de  desenvolvimento de software. 
Estamos buscando profissionais para trabalhar na área de  MOBILE para um dos nossos clientes. 

## Como se candidatar

Por favor envie um email para aluana.dias@5Aattiva.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Mobile (Ionic) ou se cadastre na vaga https://5a.selecty.com.br/vaga/1562/vaga-para-desenvolvedor-mobile-ionic-em-sao-paulo-sao-paulo

**Comment by jpventura** [comment]
Olá, @AluanaDias! Essa vaga ainda está aberta?
