### ISSUE TITLE
[Campinas] Android Developer SR [Petra Group]

### ISSUE THREAD

**Issue by prisciladiasromeu** [androiddevbr/vagas#443]
## Local
Campinas, São Paulo.

## Benefícios
Todos os benefícios de mercado.

Quem estamos buscando?

Profissional que goste de desenvolver aplicativos Android e que conheça Java ou Kotlin.

Como será o seu dia?

Suas responsabilidades serão voltadas para o desenvolvimento de Aplicativos.

​Competências e Experiência necessárias:

- Superior completo em Ciências da Computação, Engenharia da Computação e áreas afins
- Experiência em desenvolvimento de aplicativos principalmente que tenham gráficos
- Excelentes conhecimentos em Android
- Experiência com GitLab, Jira, Bitbucket
- Inglês avançado

Diferenciais:

​- Experiência com bibliotecas gráficas 
- Experiência em IOS
​- Conhecimento em Firebase (Analytics, SMS)

CLT + benefícios

Envie seu currículo para priscila.dias@petraexec.com.br com informações de projetos de relevância ou apps publicados e aguarde meu contato ou de minha equipe.

**Comment by jpventura** [comment]
Olá, @prisciladiasromeu! Essa vaga ainda está aberta?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
