### ISSUE TITLE
[Brasília] Android | Comvex

### ISSUE THREAD

**Issue by gbrvalerio** [androiddevbr/vagas#444]
O profissional atuará no auxílio ao desenvolvimento de API's, codificação e teste de sistemas em Android, para aplicativos nativos. Integrará uma equipe responsável pela manutenção dos aplicativos, tanto corretivas, quanto evolutivas e toda a sustentação que a empresa julgar necessária, visando atender às necessidades dos usuários.

Conhecimentos exigidos

- Experiência em desenvolvimento Java/Android/Kotlin;
- Padrões de projeto e arquitetura;
- Organização de código;
- MVP;
- Clean Architecture;
- Estar atualizado com a melhores práticas para desenvolvimento Android e Padrões de Segurança da Informação e versionamento de código usando Git.

Benefícios

- CLT
- Vale transporte
- Ticket refeição
- Plano de saúde

Horário:

Segunda a sexta, 8:30 as 18:00 com horário de almoço.

Interessados enviar email para raquel@prevservice.com.br

**Comment by pedrofsn** [comment]
Alguma chance de ser parcialmente presencial e parcialmente home office? Pergunto porque sou de Goiânia e me deslocaria pra BSB algumas vezes por semana, mas não todos os dias.

**Comment by gbrvalerio** [comment]
Só full presencial, amigo.

**Comment by jpventura** [comment]
Olá, @gbrvalerio! Essa vaga ainda está aberta?

**Comment by gbrvalerio** [comment]
Opa! Me desculpa, já foi fechada
