### ISSUE TITLE
[São Paulo - Ibirapuera] - Android Developer - Webforce

### ISSUE THREAD

**Issue by godois** [androiddevbr/vagas#445]
## Descrição da vaga

Procuramos um integrante para ser o ponto focal de desenvolvimento Android para os projetos que a WebForce está desenvolvendo. Inicialmente são dois business suportados por dois aplicativos em produção, os quais precisamos sustentar e evoluir.

## Local

Av. República do Líbano, ao lado do parque do Ibirapuera em São Paulo. http://www.casawebforce.com.br/

## Benefícios

- Flexibilidade de horários
- Possibilidades de homeoffice 1x por semana
- Possibilidade para almoçar no próprio local de trabalho

## Requisitos

Obrigatórios
- Experiência 2+ anos em desenvolvimento de aplicativos utilizando Android SDK, sobre diferentes versões e diferentes dispositivos (tamanhos e fabricantes);
- Conhecimentos em padrões MVP, MVC, MVVM e derivados

Desejáveis
- Experiência em princípios de UI utilizando Android, padrões e melhores práticas;
- Experiência em troubleshooting de bugs utilizando Crashlytics;
- Conhecimentos em consumos de API´s REST;
- Conhecimento em versionamento de código GIT;
- Conhecimento em build e deploy de aplicativos na PlayStore;

Diferenciais
- Ter trabalhado com linguagens NodeJs ou Golang

## Contratação

PJ a combinar

## Nossa empresa

Webforce é um grupo de investimentos que investe e desenvolve startups para o seguimento de tecnologia. 

Fundada por empreendedores seriais, nenhum outro grupo de empreendedores brasileiros de Internet tem tantos sucessos consecutivos. Em apenas 10 anos foram realizadas 3 saídas estratégicas de primeira linha. Atualmente, toda a energia da empresa está voltada para segmentos onde a expertise da nossa equipe é clara: Internet services, e-commerce, life style e games. Já faz alguns anos que promovemos também o empreendedorismo social através de nosso apoio a diversas iniciativas.

## Como se candidatar

Por favor envie um email para mgodoi@newcore.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Olá, @godois! Essa vaga ainda está aberta?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
