### ISSUE TITLE
Instrutor para treinamento de Kotlin para Android (Básico e Avançado), in Company

### ISSUE THREAD

**Issue by viniciusalvesmello** [androiddevbr/vagas#446]
## Descrição da vaga

   Instrutor com experiência em Kotlin para Android, para ministrar um curso in company. Este curso deve abordar tópicos básicos e avançados. A ideia seria desenvolver durante o curso um aplicativo que utilize estas funcionalidades. Não e necessário material didático para o curso, sendo o código fonte comentado o material que deve ser disponibilizado. Abaixo segue alguns tópicos que precisam ser abordados no curso:
		- Kotlin
		- Dagger
		- Room
		- Retrofit 2
		- Picasso
		- Material Design
		- Lifecycle
		- LiveData
		- Clean Architectyre
		- Recyclerview
		- etc.

## Local

Catalão, Goiás

## Benefícios

- Hospedagem e Transporte

## Requisitos

Obrigatórios
- Ter plenos conhecimentos dos tópicos abordados no curso.

## Contratação

PJ

## Nossa empresa

HPE Automotores do Brasil LTDA, responsável pela fabricação e distribuição dos veículos das marcas Mitsubishi e Suzuki.

## Como se candidatar

Por favor envie um email para viniciusmello@hpeautos.com.br com seu CV anexado - enviar no assunto: Curso Kotlin

**Comment by jpventura** [comment]
Olá, @viniciusalvesmello! Essa vaga ainda está aberta?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
