### ISSUE TITLE
Desenvolvedor(a) Mobile Android (Reestruturar a área de Apps)

### ISSUE THREAD

**Issue by tocalivros** [androiddevbr/vagas#447]
## Descrição da vaga
*Desenvolvedor(a) Mobile Android e iOS*
Desenvolvimento Android que ira reestruturará a área de aplicativos. Estamos migrando para aplicativo nativo.

## Local

A Tocalivros se localiza na av. Ordem e Progresso 115, na Barra Funda São Paulo
www.tocalivros.com

## Benefícios

- Horário flexível
- Almoço bom na empresa
- Estacionamento incluso e pago

## Requisitos

Buscamos uma pessoa pró-atividade, hands-on, com alta capacidade de trabalho em equipe, engajamento e focado em metas, para trabalhar full-time na equipe.

Obrigatórios
- 3+ anos de experiência com Android
- Java / kotlin seria um diferencial
- Clean archtecture
- Mvp
- Rxjava
- Ioc (injeção de dependencia)
- Materal design
- Retro compatibilidade
- Push notification
- Retrofit
- Publicação na playstore
- Bindservices
- Notification manager
- Sqlite
- Mysql-light

## Contratação

PJ a combinar

## Nossa empresa

A Tocalivros trabalha com audiolivros, um formato que tem crescido muito no mundo todo.
www.tocalivros.cm

## Como se candidatar

Entrar em contato com Marcelo Camps marcelo@tocalivros.com com seu CV anexado
Abraços 
Marcelo Camps

**Comment by jpventura** [comment]
Olá, @tocalivros! Essa vaga ainda está aberta?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
