### ISSUE TITLE
[Campinas] Android Developer and Embedded Apps [Pertra Group]

### ISSUE THREAD

**Issue by prisciladiasromeu** [androiddevbr/vagas#448]
Desenvolvedor Android Framework e apps embarcadas Jr / Pl / Sr

Quem estamos buscando?

Por profissionais talentosos em desenvolvimento de software que tenham interesse em conhecer a fundo diferentes camadas de software por trás das milhões de linhas de código que estão dentro do seu smartphone.

Como será seu dia a dia?

Trabalhará em um grande projeto com um dos líderes mundiais em eletrônicos de consumo e convergência digital.

Experienciará satisfação de ver seu trabalho ser usado por milhões de usuários no mundo todo.

Estará em contato com profissionais de outros sites no exterior e ajudará a avançar a tecnologia e experiência dos smartphones, desenvolvendo novas aplicações e funcionalidades em código Android nativo tendo como principais objetivos:

Adicionar funcionalidades às aplicações de nossos smartphones de modo a suportarem as mais novas tecnologias de rede;
Conquistar novos mercados ao atender às demandas de operadoras, especialmente dos Estados Unidos;
Manter o software legado estabilizando-o e atualizando-o a cada nova plataforma Android;
Vencer o desafio de agilizar a disponibilização aos usuários finais atualizações de software para as versões mais recentes da plataforma Android;
O profissional terá a oportunidade de:

Acessar o código de aplicações e framework do Android AOSP (SDK) tendo não somente a oportunidade de conhecer e evoluir código produzido pela Google mas também a possibilidade de interagir com a Google em discussões de problemas ou de design que demandarem solução conjunta e de contribuir com seu código diretamente para a Google.
Conhecer o estado da arte do Android em primeira mão ao ter acesso antecipado ao código das novas versões da plataforma Android.
Participar de uma equipe global e de alto desempenho, distribuída em vários países e disposta a trocar ideias sobre os desafios encontrados no dia a dia, em uma experiência cultural enriquecedora;
Receber feedbacks de seu código de profissionais altamente experientes.
Trabalhar em ferramentas e scripts que aumentem a produtividade da equipe de desenvolvimento;
Vivenciar e trabalhar num ambiente de desenvolvimento e integração de software global, de alta maturidade e complexidade com integração contínua e uso de métodos ágeis de desenvolvimento; 
 

Competência e experiências necessárias:

Ensino superior completo em Ciências da Computação, Engenharia da Computação/ Elétrica e áreas afins;
Experiência em programação orientado a objetos (Java e/ou C++);
Conhecimento com estrutura de dados e algoritmos;
Inglês intermediário para leitura, escrita e conversação.
 

Diferenciais

Experiência em desenvolvimento de aplicações Android e seus blocos principais;
Conhecimento em atividades de integração de software e atualização de sistema operacional para smartphones;
Experiência com plataformas móveis (apps, framework, configuration management, makefiles, etc);
Experiência com Git.

## Contratação

CLT

## Como se candidatar?

Por favor envie um e-mail para priscila.dias@petraexec.com.br com seu CV anexado - enviar no assunto: Vaga Android Framework e o nível (JR, PL ou SR)

**Comment by jpventura** [comment]
Olá, @prisciladiasromeu! Essa vaga ainda está aberta?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
