### ISSUE TITLE
[Curitiba - Paraná] Desenvolver(a) Android | Gateware

### ISSUE THREAD

**Issue by FabianoCharan** [androiddevbr/vagas#449]
## Descrição da vaga
Atuação em projetos de grande porte, com time altamente qualificado de profissionais engajados.

## Local
Curitiba - PR

## Benefícios
Todos os benefícios de uma empresa de ponta.

## Requisitos
Inglês e espanhol - intermediário.
3+ years Android development experience
Experience with Android Support Libraries and google Play Services
Experience with the following third party libraries - RxAndroid, Dagger, Gson, SQLite, Okhttp, Picasso.
Experience working in Agile development team and working with Git/GitHub
Experience with consuming external RESTful APIs
Experience with Salesforce MobileSDK in particular SmartStore
Knowledge of OOP and OOAD

## Contratação
CLT

## Nossa empresa
Perfil Corporativo
Somos uma empresa reconhecida pela forte atuação em Gestão de Projetos e PMO, Fábrica de Softwares, Testes e Requisitos.

Visão:
Estar entre os principais players de mercado e ser referência no uso de metodologias competitivas na produção de soluções com tecnologia.

Missão:
Gerar valor para nossos clientes, equipe e sociedade, desenvolvendo soluções com tecnologia.

## Como se candidatar
Envie seu currículo para: bruno.santos@gateware.com.br | whatsapp: 41 987841740

**Comment by jpventura** [comment]
Olá, @FabianoCharan! Essa vaga ainda está aberta?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
