### ISSUE TITLE
Desenvolvedor Mobile na Marmotex

### ISSUE THREAD

**Issue by FernandaAbreu** [androiddevbr/vagas#450]
**Descrição da vaga**
O time de desenvolvimento da Marmotex está procurando por desenvolvedores "gente boa", apaixonados por desafios, comprometidos e proativos.
Que tenha paixão pelos nossos principais objetivos que é alimentar, deixar as marmotinhas felizes e uni-las através do almoço no trabalho. Afinal, a #AComidaNosUne.

**Local**
Vila Olimpia

**Benefícios**
- Ambiente descontraído e informal

- Uma equipe que usa tecnologia de ponta e disruptiva;

- Ambiente de startup;

- Code Review;

- Meetups internos sobre tecnologias usadas na empresa.

**Requisitos**

**Obrigatórios**

- Graduação na área de computação ou experiência equivalente.
- Experiência com desenvolvimento para aplicações móveis (Android Studio).
- Habilidade de trabalhar com dados remotos via REST e JSON.
- Experiência com GIT
- Dominar a construção de queries (SQL).
- Ter utilizado algum ORM Android (GreenDao, OrmLITE, SugarORM).
- Experiência com retrofit e OKHttp.
- Design Patterns.
- Confortável com padrão MVP, MVC, MVVM  e Clean Architecture
-  Experiência com Kotlin ou Java 

**Desejáveis**
Experiência com Espresso e UI Automator
Experiência com RxJava
Android Flavors
Realm

**Como se candidatar**
Por favor envie um email para fernanda@marmotex.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Olá, @FernandaAbreu! Essa vaga ainda está aberta?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
