### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor(a) Android Pleno na Super Revendedores

### ISSUE THREAD

**Issue by felipe-borges93** [androiddevbr/vagas#451]
## Descrição da vaga

Buscamos um(a) Desenvolvedor(a) Android para se unir ao nosso time de desenvolvimento do aplicativo Super Revendedores. Nosso app já ultrapassou a faixa de 100 mil downloads e somos o 4º app mais rentável da categoria de Finanças da Play Store. 
Nosso roadmap desse ano é bastante desafiador e será uma excelente oportunidade para aprendizado e crescimento profissional. Estamos trabalhando em uma integração com a Stone para que os nossos usuários façam cobranças em cartão e boleto pelo app, integradas a uma maquininha da Super Revendedores.

## Local

Praia de Botafogo, 440 - 22º andar - Botafogo - Rio de Janeiro

## Benefícios

- Horário Flexível
- 1 ou 2 dias de home-office
- Possibilidade de participação societária na startup
- VR & VT

## Requisitos

**Obrigatórios**
- 3+ anos de experiência com Android
- Java
- Android Studio
- DbFlow
- Retrofit
- Okhttp
- Dagger2
- ButterKnife

**Desejáveis**
- Picasso
- MPAndroidChart
- RxJava
- RxAndroid

## Contratação

PJ a combinar;
Remuneração: **R$ 6.000,00 a R$ 9.000,00**

## Nossa empresa

Super Revendedores é uma startup focada em revolucionar o mercado de Venda Direta por catálogos no mundo! Esse é um gigantesco mercado, contando com mais de 4,5 milhões de revendedores no Brasil.
Buscamos inovar na Venda Direta através da ampliação da produtividade, vendas e lucratividade dos revendedores e das empresas. Já contamos com mais de 16 mil usuários ativos e mais de R$ 40 milhões em vendas já foram transacionadas no nosso aplicativo.
Somos um time de apaixonados por inovação, buscando gerar um grande impacto na vida de milhões de pessoas.

## Como se candidatar

Por favor envie um email para felipe@superrevendedores.com.br com seu CV anexado - enviar no assunto: Vaga Android, ou acesse a nossa vaga no Trampos: https://trampos.co/oportunidades/138814-desenvolvedor-android

**Comment by rodrigogaraujo** [comment]
Aceita remoto?

**Comment by jpventura** [comment]
Olá, @felipe-borges93! Essa vaga ainda está aberta?

**Comment by felipe-borges93** [comment]
Olá,

a vaga já está fechada! Se abrirmos outras oportunidades postarei aqui!

Abraços
