### ISSUE TITLE
[São Paulo - Alphaville] Ginga.One - Desenvolver(a) Android Pleno/Senior

### ISSUE THREAD

**Issue by otaviommendes** [androiddevbr/vagas#452]
## Local

Escritório São Paulo - Alphaville

## Requisitos

Obrigatórios
- Android Studio
- GIT
- Rest services

Desejáveis
- Testes unitários

## Contratação

CLT ou PJ (a combinar).

## Nossa empresa

NÓS CRIAMOS OPORTUNIDADES E RESOLVEMOS PROBLEMAS ATRAVÉS DA TECNOLOGIA.
NÓS SOMOS A GINGA ONE.

## Como se candidatar

Enviar email para vagas@gingaone.com com o assunto **Desenvolver(a) Android Alphaville**.

**Comment by rodrigogaraujo** [comment]
Aceita remoto?

**Comment by otaviommendes** [comment]
Só presencial

**Comment by jpventura** [comment]
Olá, @otaviommendes! Essa vaga ainda está aberta?

**Comment by otaviomendesginga** [comment]
@jpventura infelizmente não
