### ISSUE TITLE
[São Paulo - Vila Madalena] Ginga.One - Desenvolver(a) Android Pleno/Senior

### ISSUE THREAD

**Issue by otaviommendes** [androiddevbr/vagas#453]
## Descrição da vaga

Temos **DUAS** vagas para desenvolver(a) Android pleno ou senior.

## Local

Escritório São Paulo - Vila Madalena.

## Requisitos

Obrigatórios
- Android Studio
- GIT
- Rest services
- Inglês fluente

Desejáveis
- Testes unitários

## Contratação

CLT ou PJ (a combinar).

## Nossa empresa

NÓS CRIAMOS OPORTUNIDADES E RESOLVEMOS PROBLEMAS ATRAVÉS DA TECNOLOGIA.
NÓS SOMOS A GINGA ONE.

## Como se candidatar

Enviar email para vagas@gingaone.com com o assunto **Desenvolver(a) Android Vila Madalena**.

**Comment by jpventura** [comment]
Olá, @otaviommendes! Essa vaga ainda está aberta?

**Comment by otaviomendesginga** [comment]
@jpventura está sim

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
