### ISSUE TITLE
[São Paulo - Itaim, SP] Android Developer PLENO / SENIOR | XP Investimentos

### ISSUE THREAD

**Issue by thalissondeveloper** [androiddevbr/vagas#454]
## Descrição da vaga

A XP Investimentos está em constante crescimento, portanto surgindo vários projetos e demandas para aplicativos móveis. Hoje temos vários projetos em andamento e estamos a procura de um profissional mobile Android para fazer parte da nossa equipe. Se você é uma pessoa que gosta de inovações e desafios a XP é o lugar certo.

## Local

Escritório São Paulo - Itaim

## Benefícios

- VR
- VA
- PRL
- Plano de saúde

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVVM e derivados
- Ter experiência com Kotlin

Desejáveis
- Experiência com Espresso e UI Automator
- Experiência com Mockito
- Experiência com RxJava
- Experiência com Injeção de Dependência
- Experiência com os conceitos de boas práticas do SOLID.
- Experiência com desenvolvimento modular

## Contratação

CLT Full

## Nossa empresa

Somos uma das maiores instituições financeiras do Brasil e, há mais de 16 anos, estamos transformando o mercado de investimentos no país. Com o propósito de ajudar o brasileiro a investir melhor, nossos mais de 1 mil colaboradores trabalham todos os dias para proporcionar as melhores experiências para cada cliente.

A XP Investimentos é a principal empresa do Grupo XP. Atualmente, o grupo conta com mais de 600 mil clientes ativos e R$ 140 bilhões sob custódia e é referência em soluções financeiras no Brasil. 

## Como se candidatar

Por favor envie um email para thalisson.lopes@xpi.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Olá, @thalissondeveloper! Essa vaga ainda está aberta?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
