### ISSUE TITLE
[Amsterdam, NL] Senior Android Dev. | Speakap

### ISSUE THREAD

**Issue by 3dm1** [androiddevbr/vagas#455]
## Descrição da vaga

We’re looking for people who are passionate about creating great Android applications. Are you as comfortable composing efficient layouts that work well across various screen sizes and densities as you are debugging performance issues in the persistence layer? Then we need you!

https://jobs.speakap.com/senior-android-developer

## Local

Amsterdam, Holanda (presencial) ✈️  🇳🇱 🇳🇱 

## Benefícios

- Reallocation package 🛄 
- Budget for conferences 💲 

## Requisitos

- Bachelor’s degree in Computer Science, Engineering or related field, or equivalent training, fellowship, or work experience
- Extensive understanding of Android framework components and their respective lifecycles
- Strong computer science fundamentals: data structures, algorithms and programming languages
- An excellent understanding of best practices for networking, concurrency and threading
- Current and detailed knowledge of the capabilities of different Android API levels
- Experience developing highly performant Java code and view layouts and the ability to diagnose performance bottlenecks
- A disciplined approach to development, testing, documentation and code structure in a team environment
- Experience working closely with product teams, designers, and other developers to create a truly delightful mobile experience
- A familiarity with the Android tool ecosystem for development, testing, debugging, and
- performance benchmarking
- At least four years of engineering experience, a large portion of which in a team environment
- A constant desire to improve, learn more and take things higher

_Diferenciais_
- A passion for building and maintaining great open source projects or otherwise contributing to the Android community
- Experience with web development, distributed systems and parallel processing

## Contratação

Fulltime

## Nossa empresa

Speakap is a secure and private platform that enables organisations of all sizes to reach and engage with their highly-valued (frontline/customer-facing) employees in order to deliver greater customer experience and business value.

Speakap is currently used by more than 300 companies in 27 countries around the world. Market leaders such as MediaMarkt, Rituals, McDonalds and Hudson's Bay all engage smarter through Speakap.

## Como se candidatar

Fazer inscrição através do link https://speakap1.bamboohr.co.uk/jobs/view.php?id=3

Quaisquer dúvidas, conversar no slack com edson.menegatti

**Comment by jpventura** [comment]
Olá, @3dm1! Essa vaga ainda está aberta?

**Comment by 3dm1** [comment]
@jpventura Está sim 👍

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by saketkumar95** [comment]
@3dm1 Hello , Is there any vacancy for Android Developer with 3 years of experience ?
