### ISSUE TITLE
[São Paulo - Ao Lado da Estação Morumbi] Android Developer PLENO / SENIOR | Everis Brasil

### ISSUE THREAD

**Issue by EverisBrasil** [androiddevbr/vagas#456]
**Descrição da vaga**
Contratação CLT Full - Para trabalhar em projetos de clientes dos setores: bancário, seguros e telecom.

**Local**
São Paulo/SP ao lado da estação Morumbi.

**Benefícios**
Vale transporte/Auxílio fretado ou Auxílio Combustível, Ticket Refeição, Assistência Médica Sulamerica, Convênio Odontológico, Seguro de vida, Previdência Privada e Cartão Good Card.

**Requisitos**
Graduação na área ou experiência equivalente.
Experiência com desenvolvimento em aplicações nativas.
Experiência com GIT.
Design Patterns.
Confortável com padrão MVP, MVC, MVVM e Clean Architecture

Desejáveis
Experiência com Espresso ou Mockito
Experiência com RxJava
Realm

Obrigatórios
- 3+ anos de experiência com Android

**Contratação**
CLT Full

**Nossa empresa**
#VemPraEveris 
“...Trabalhar na everis é fazer parte de uma grande equipe humana, diferenciada por sua cultura, onde cada pessoa é protagonista de sua história. 
Na everis, nós acompanhamos as pessoas na criação de seu próprio caminho, aprendendo a cada dia e promovendo sua própria autonomia ... “

**Como se candidatar**
Por favor envie um email para renata.conti.morais@everis.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Olá, @EverisBrasil! Essa vaga ainda está aberta?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
