### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Android Sênior | Estratégia Concursos

### ISSUE THREAD

**Issue by BrunoYY** [androiddevbr/vagas#457]
## Descrição da vaga

Você terá o seu Macbook Pro, cadeira confortável e poderá trabalhar em horário flexível, basta combinar com o líder de seu time. O que saltará aos olhos no final das contas serão os resultados alcançados, o comprometimento com os objetivos e o bom relacionamento em equipe.

O projeto mobile é uma novidade, construiremos aplicativos Android e IOS para trazer a experiência de estudo no ambiente web para o mobile. Os(as) aprovadxs irão conduzir o projeto do início, sempre em contato com o time de back-end para alimentar os Apps com dados provenientes de APIs e com o time de front-end a fim de mantermos a identidade visual. Além disso, irá auxiliar a estruturação da área junto com o Tech Lead, se responsabilizando por manter a cultura ágil e DevOps na equipe.

## Local

Escritório 
São Paulo - Berrini (Próxima à estação de Trem)

## Benefícios

- Horário flexível
- VR (R$23,00 por dia)
- VT

## Requisitos

Obrigatórios
●      3+ anos de experiência com Android
●	Domínio de Java ou Kotlin
●	Experiência prévia em desenvolvimento de Apps
●	Experiência com consumo de APIs REST

Desejáveis
●	Familiaridade com versionamento de código
●	Familiaridade com testes unitários
●	Familiaridade com cultura DevOps
●	Familiaridade com gestão de pessoas
●	Codar em inglês
●	Publicação de pelo menos uma aplicativo na Play Store
●	Familiaridade com metodologias ágeis

Diferenciais
●	Pós graduação

## Contratação

CLT ou PJ, de acordo com preferência do(a) candidato(a)

## Nossa empresa

A Estratégia Concursos é referência nacional na preparação de candidatos a concursos públicos, por meio do oferecimento de cursos online em pdf e vídeo aulas. 

## Como se candidatar

Por favor envie um email para byoshioka@findhr.com.br com seu CV anexado - enviar no assunto: Vaga Android - Estratégia Concursos

Muito obrigado!

**Comment by jpventura** [comment]
Olá, @BrunoYY! Essa vaga ainda está aberta?

**Comment by BrunoYY** [comment]
@jpventura Tudo bem? Temos outras vagas de Android conosco no mesmo perfil. Me envia um e-mail para batermos um papo:
byoshioka@findhr.com.br

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
