### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Android Sênior | Squad

### ISSUE THREAD

**Issue by BrunoYY** [androiddevbr/vagas#458]
#Descrição da vaga
Será responsável por desenvolver alterações em funcionalidades existentes, novas funcionalidades através de wireframes, critérios de aceite e payloads, levando em consideração limitações técnicas e complexidade para implementação.
Refatorar e aperfeiçoar o código baseando-se em novos e melhores padrões de desenvolvimento.
Utilizar um processo definido de versionamento e revisão de código.
Participar das cerimônias do Scrum.
Publicação do aplicativo na Play Store e acompanhamento das suas métricas em produção, identificando problemas a serem corrigidos.

#Local
Escritório
São Paulo - Vila Lobos (Próxima à estação de Trem)

#Benefícios
Stock Options

#Requisitos

Obrigatórios
●      3+ anos de experiência com Android
●	Conhecimento em modelos arquiteturais (Clean Architecture)
●	Conhecimento em design patterns (Dagger, MVP, Reactive)
●	Experiência com integração de APIs (Retrofit), ORM, serviçoes em background, notificações, banco de dados, Google Maps e Analytics

Desejáveis
●	Experiência com ferramentas de qualidade, publicação e monitoramento (Git Flow, Jenkins, Crashlytics, Firebase)
●	Experiência com metodologias ágeis (Scrum e Kanban)
●	Experiência com definição de novas features, wireframes e endpoints.

Diferenciais
●	Pós graduação

#Contratação
PJ

#Nossa empresa
A Squad é uma Start-up em Early Stage que surgiu como spin off de uma grande empresa de cosméticos Brasileira, possui como propósito desenvolver um aplicativo de comunicação interna com uma plataforma de otimização de tarefas e com features de segmentação de audiência. 
Possui um volume grande de usuários ativos e pretende expandir essa base em Dezembro, quando lançar esse produto para o mercado.

O ambiente da empresa é descontraído e diverso. Ganhará pontos extras no processo seletivo quem curtir video-games e principalmente se for Nintendista :P

#Como se candidatar
Por favor envie um email para byoshioka@findhr.com.br com seu CV anexado - enviar no assunto: Vaga Android - Squad

Muito obrigado!

**Comment by jpventura** [comment]
Olá, @BrunoYY! Essa vaga ainda está aberta?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
