### ISSUE TITLE
Desenvolvedor ANDROID Pleno

### ISSUE THREAD

**Issue by RADARProfissional** [androiddevbr/vagas#459]
## Local

São Paulo - Zona Sul

## Benefícios
VR, Plano de Saúde, Ax.creche, Plano Odontológico, entre outros

## Requisitos

•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Experiência no desenvolvimento de aplicações Android e com Java e Kotlin;
•	Integrações com serviços web (APIs, RESTful e SOAP);
•	Conhecimentos em controle de versão Git e gerenciamento de dependências (Gradle);
•	Vivência com Publicação de versões na Play Store e com adaptações de layouts entre Smartphones e Tablets;
•	Testes automatizados (unitários e de interfaces) e metodologias ágeis (SCRUM e Kanban).

## Contratação

CLT

## Nossa empresa

RADAR Profissional

## Como se candidatar

Por favor envie um email para cristiane@radarprofissional.com.br seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Olá, @RADARProfissional! Essa vaga ainda está aberta?

**Comment by RADARProfissional** [comment]
Olá! 

 

Sim, está aberta! 

 

Obrigada!

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: JP Ventura <notifications@github.com> 
Enviada em: segunda-feira, 16 de julho de 2018 08:35
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] Desenvolvedor ANDROID Pleno (#459)

 

Olá, @RADARProfissional <https://github.com/RADARProfissional> ! Essa vaga ainda está aberta?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
