### ISSUE TITLE
Desenvolvedor Android

### ISSUE THREAD

**Issue by mendesbruna** [androiddevbr/vagas#461]
Descrição da vaga

Startup de mobilidade urbana busca desenvolvedores para garantir lançamentos de software de alta qualidade, usando integração contínua, testes automatizados e revisões de código cuidadosas. Construir plataformas sustentáveis e estáveis para novas ideias de produtos. Orientar arquitetura corporativa e arquitetura de soluções.
Forte conhecimento do Android SDK, diferentes versões do Android e como lidar com diferentes tamanhos de tela. Experiência em princípios, padrões e práticas recomendadas de design da interface do Android. Experiência Git. Capacidade eficiente de priorização de tarefas. Experiência prática com as melhores práticas de engenharia de software (testes, revisão de código, integração contínua). Conhecimento RESTful e prática de fundo. Conhecimento e experiência prática com o processo de distribuição da Play Store. Experiência MVVM e Kotlin. Conhecimentos com mobilidade urbana (passageiros e motoristas) será um diferencial.

## Local

Escritório São Paulo - Zona Oeste - Alto da Lapa
**Não aceitamos remoto

## Benefícios

- curso de idiomas
- bônus de aplicativo
- ambiente descontraído
- sala de jogos
- flexibilidade de horários

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis
- Experiência com Espresso e UI Automator
- Experiência com RxJava

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para vagas.ti@brmendesconsultoria.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by mion23** [comment]
Bom dia, vocês aceitam remoto?

**Comment by mendesbruna** [comment]
Bom dia @mion23, não aceitamos remoto :(

**Comment by jpventura** [comment]
Olá, @mendesbruna! Essa vaga ainda está aberta?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
