### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Android - Pleno e Sênior

### ISSUE THREAD

**Issue by helenmatos** [androiddevbr/vagas#462]
**Empresa**
A 5A Attiva é uma consultoria especialista em identificar profissionais de alta performance em Tecnologia da Informação. Trabalhamos com Terceirização de Profissionais de Desenvolvimento, Gestão de Projetos e Soluções em Sistemas para grandes clientes. 

**Atividades**
Desenvolver uma plataforma que envolve socialização e vouchers para descontos, é uma plataforma "mista".
Essa plataforma envolve desde redes sociais até cuponerias.
Um dos pontos chaves dessa plataforma são as tecnologias avançadas (geolocalização, envio de mensagens socket, inteligência artificial, entre outros).
Escrever código limpo usando padrões de linguagem e design do Objective C.
Entender o design da tela e as metas de negócios para criar um aplicativo para dispositivos móveis eficaz.

**Perfil Técnico**
Experiência em desenvolvimento mobile (Android)
Publicação de pelo menos 1 aplicativo no Google Play(aplicativo próprio ou fazendo parte de uma equipe)
Experiencia com acesso a API Rest
Fabric
Push notifications
Geolocalização
Experiência com Git
Familiaridade com Scrum
Habilidade de comunicação para trabalhar em uma equipe com profissionais de várias tecnologias diferentes
Experiência com alguma ferramente de integração contínua
Conhecimento em testes unitários

**Localidade**
Jardim Paulista

**Contratação**
PJ valor Hora

Interessados, por favor, entrar em contato através do e-mail: Helen.matos@5aattiva.com.br

Indicações são bem vindas.

**Comment by jpventura** [comment]
Olá, @helenmatos! Essa vaga ainda está aberta?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
