### ISSUE TITLE
[Curitiba, Paraná] Desenvolvedor Android  Senior | EBANX

### ISSUE THREAD

**Issue by cocuroci** [androiddevbr/vagas#465]
## Descrição da vaga

Buscamos um Desenvolvedor Android Sênior para nos ajudar no desenvolvimento de produtos para os nossos quase 40 milhões de clientes latino-americanos. Se você é muito bom e quer trabalhar em um ambiente multicultural e inovador com a cara do Vale do Silício, vem conversar com a gente.

- Trabalhar em um ambiente diversificado e dinâmico que utiliza diferentes ferramentas e linguagens de programação;
- Tomar posse de projetos e fazer as coisas acontecerem;
- Escrever códigos reutilizáveis e bem testados, seguindo as boas práticas de programação para desenvolvimento de aplicativos Android;
- Replicar UIs e animações buscando resultado pixel-perfect, visando a melhor UX possível para o usuário final;
- Realizar levantamento de requisitos para novas funcionalidades, bem como debugging e correções para as funcionalidades já existentes.

## Local

Curitiba - Paraná

## Benefícios

- Um ambiente de autonomia para crescimento e realizações;
- Escritório informal e descontraído - frutas e snacks saudáveis, chuveiros no escritório, uma Bulldog Francês que adora correr e morder (entre outros visitantes fofos), patinete, nerf, drones, nespressos e ótimas festas;
- Language Center: Inglês e Espanhol dentro do EBANX;
- WAVES - Programa de Objetivos e Resultados Chave;
- EBANX Education - Até R$300/mês;
- EBANX Play - Bem Estar e Performance (Gympass, e-Sports, SESC);
- Horário Semi-Flexível (8 horas de segunda à sexta);
- Plano de Saúde e Odontológico Bradesco Top Nacional;
- Vale Refeição;
- Vale Transporte.

## Requisitos

Obrigatórios
- Mais de 5 anos de experiência como desenvolvedor de software.
- Pelo menos 3 anos de experiência com desenvolvimento para mobile;
- Integrar com APIs RESTful de olhos fechados;
- Conhecimento em pelo menos 2 linguagens de programação, tais como Java, Kotlin, Swift, Objective-C, Python, Ruby, etc;
- Saber utilizar bem conceitos do GitHub como branching, pull-requests, etc;
- Mindset de Continuous Delivery, focado em entregar valor de negócio para nossos usuários finais;
- Inglês intermediário (lê e escreve bem, fala razoável);
- Precisa ser formado? Sim e não! Se você for formado em Sistemas de Informação, Ciência/Engenharia da Computação, Análise e Desenvolvimento de Sistemas ou cursos similares seria legal, mas se você tem uma puta experiência e sabe muito, se inscreve também!

Desejáveis
- Kotlin;
- RxKotlin;
- Git;
- Google Components Architecture;
- Gradle;
- Testes (Espresso, JUnit);
- Firebase toolkit;
- Kodein;
- DataBinding;
- Retrofit 2;
- Bitrise;
- PhraseApp;
- JIRA / Trello.

## Contratação

CLT

## Nossa empresa

O EBANX é um grupo financeiro global com atitude do Vale do Silício. A gente acredita que todas as pessoas devem ter o poder de escolher e de chegar mais longe. Por isso, colocamos meios de pagamento locais e seguros (boleto bancário, transferências, cartões de crédito nacionais) nos principais sites do mundo. Somos líderes no Brasil e estamos conquistando a América Latina. Tudo para que as pessoas tenham acesso ao que desejam sem burocracia, sem preocupação e sem sair de casa.

Já alcançamos quase 40.000.000 de consumidores finais, temos empresas como AirBnB, Spotify, AliExpress, PlayStation, Wish.com trabalhando com a gente 

Para saber um pouco mais, veja a nossa Career Page e procure as fotos tiradas pelos ebankers no nosso Instagram - #ebanxlife.

## Como se candidatar

No link [https://ebanx.recruiterbox.com/jobs/fk01qz4/](https://ebanx.recruiterbox.com/jobs/fk01qz4/)

**Comment by jpventura** [comment]
Olá, @cocuroci! Essa vaga ainda está aberta?

**Comment by cocuroci** [comment]
Está sim @jpventura

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
