### ISSUE TITLE
[Florianópolis] Android Developer for American IOT / smart home automation company 

### ISSUE THREAD

**Issue by thomasRademaker** [androiddevbr/vagas#466]
## Descrição da vaga

This is an independent contractor (PJ) opportunity in Florianopolis, Brazil, working with a diverse team on a smart home product with several thousand users.

### Responsibilities:

- Maintain current Android codebase
- Design and implement new functionalities 
- Write documentation and tests for all new code
- Assist the rest of the mobile team with design decisions and code reviews

## Local

Office in Florianópolis

## Benefícios

- You will fly to New Jersey once or twice a year to work in our New Jersey office. The office is a 20 minute drive from New York City. When you're here we can all go hang out in the city!  

## Requisitos

- 4+ years experience in professional software development
- Bachelor’s degree in computer science, or equivalent experience
- Professional knowledge of Java and the Android SDK
- Experience with RxJava
- Ability to commit to timelines and deliver on time
- Proficiency in English

Familiarity with any of the following technologies and associated APIs is a plus

- iOS development
- RF / IR signals
- Python
- Lua  

## Nossa empresa

Olibra is an IOT/smart home automation startup and our flagship product is the [BOND](https://bondhome.io). We have an office in the United States, just outside of New York City, and an office in Florianópolis.

## Como se candidatar

please send an email to [Thomas](mailto:thomas@olibra.io) and include your resume

**Comment by jpventura** [comment]
Olá, @thomasRademaker! Essa vaga ainda está aberta?

**Comment by thomasRademaker** [comment]
Olá, @jpventura . Obrigado pelo seu interesse, mas a posição já foi preenchida.

**Comment by thomasRademaker** [comment]
This position has been filled.
