### ISSUE TITLE
São Paulo- SP - Desenvolvedor ANDROID Pleno - RADAR Profissional

### ISSUE THREAD

**Issue by RADARProfissional** [androiddevbr/vagas#467]
## Local

Zona Sul de São Paulo 

## Benefícios

VR, Plano de Saúde, Ax.creche, Plano Odontológico, entre outros.

## Requisitos

•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Experiência no desenvolvimento de aplicações Android e com Java e Kotlin;
•	Integrações com serviços web (APIs, RESTful e SOAP);
•	Conhecimentos em controle de versão Git e gerenciamento de dependências (Gradle);
•	Vivência com Publicação de versões na Play Store e com adaptações de layouts entre Smartphones e Tablets;
•	Testes automatizados (unitários e de interfaces) e metodologias ágeis (SCRUM e Kanban).

## Contratação

CLT

## Nossa empresa

RADAR Profissional, Consultoria de R&S. 

## Como se candidatar

Interessados, por gentileza, envie seu CV para cristiane@radarprofissional.com.br

**Comment by jpventura** [comment]
@RADARProfissional, tudo bem? O emprego é presencial ou remoto?

**Comment by RADARProfissional** [comment]
presencial

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: JP Ventura <notifications@github.com> 
Enviada em: quarta-feira, 30 de maio de 2018 19:08
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] São Paulo- SP - Desenvolvedor ANDROID Pleno - RADAR Profissional (#467)

 

@RADARProfissional <https://github.com/RADARProfissional> , tudo bem? O emprego é presencial ou remoto?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by RADARProfissional** [comment]
Olá! Por gentileza, nos envie seu CV. 

 

Obrigada! 

 

Att, 

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: marciofermino <notifications@github.com> 
Enviada em: sexta-feira, 27 de julho de 2018 13:41
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] São Paulo- SP - Desenvolvedor ANDROID Pleno - RADAR Profissional (#467)

 

Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
