### ISSUE TITLE
[Rio de Janeiro, RJ] Arquiteto de Software/Desenvolvedor Android| Gazeus Games 

### ISSUE THREAD

**Issue by fabicarrilho** [androiddevbr/vagas#468]
## Descrição da vaga

Arquiteto de Software/Desenvolvedor Android

RESPONSABILIDADES: 
- Desenvolvimento e manutenção de aplicativos e bibliotecas para o sistema Android.

REQUISITOS:
- Capacidade e vontade de aprender rapidamente diferentes linguagens e tecnologias
- Conhecimento da língua inglesa 

REQUISITOS TÉCNICOS: 
- Android SDK / API do Android em geral
- Melhores práticas recomendadas pelo Google para o desenvolvimento de Apps
- Gradle
- Sólidos conhecimentos em Orientação a Objetos e Padrões de Projetos
- Experiência com Java
- Experiência com Git

CONHECIMENTOS DESEJÁVEIS:
- In-App Billing, Subscription, Push Notifications, Services, Broadcast Receivers

IRÁ SER CONSIDERADO UM DIFERENCIAL:
- Experiência no desenvolvimento de bibliotecas e frameworks
- Colaboração em projetos OpenSource
- Experiência com desenvolvimento iOS;
- HTML5, Javascript(ES6), CSS e NodeJS

## Local

Barra da Tijuca - Rio de Janeiro

## Benefícios: 
- Plano de Saúde e Odontológico Bradesco
- VR (33,66)
- VT

Outros benefícios:
- Shiatsu 1x por mês
- Snacks oferecidos pela empresa
- Horário flexível
- Day off no dia do aniversário
- Sala de jogos 

## Contratação
CLT

## Nossa empresa
A Gazeus Games é a maior desenvolvedora brasileira de jogos casuais e sociais. Nós fazemos jogos incríveis e, através deles, buscamos criar laços reais entre as pessoas. E nós não faríamos os melhores jogos se não tivéssemos a melhor equipe e anos de história e tradição.
A gente trabalha e a gente se diverte. :)

## Como se candidatar

Por favor, se cadastre no link da vaga e também inclua seu cv.
Link : https://bit.ly/2mvWsHI

**Comment by fabicarrilho** [comment]
Olá, @jpventura Não temos restrição de senioridade por tempo de experiência. 
Iremos avaliar o conhecimento pelo desafio e pela conversa.

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by tiagocasemiro** [comment]
Poderiam disponibilizar um email para envio de currículo?
