### ISSUE TITLE
[Florianópolis, SC] Android Developer - ArcTouch

### ISSUE THREAD

**Issue by arctouch-luizsantana** [androiddevbr/vagas#47]
## Android Developers

ArcTouch is hiring skilled, creative, and adaptable Android Developers/Engineers. This is an opportunity for developers with strong object-oriented programming experience and attention to detail and quality, to contribute to a variety of challenging and cutting edge apps.

Our projects usually range from one to two months. In a year, you could easily work on six different projects. Typically 2-4 people are assigned to each project, each with an opportunity to give input on design and development. We encourage collaboration and creativity. You will interact with our team of product managers and engineers and may architect solutions with our customers and their engineers as well.
## Local

Florianópolis / SC
## Benefícios
- Horário flexível
- Mac retina para trabalhar + iPad (depois de 2 anos de empresa você ganha o iPad)
- Geladeira e dispensa sempre cheias!!!
- Video game / Campeonato de fifa
- Pebolim
- Ótimo escritório
- Excelente work/life balance
- Empresa paga 90% da mensalidade da academia
- Aulas de inglês
- Visto americano pago pela emrpesa
- Sexta-feira trabalha home office
- Quinta-feira happy hour patrocinado pela empresa (Thirsty Thursday)
## Requisitos

Obrigatórios
- 4+ anos de experiência com desenvolvimento OO (1+ em Android)
- Bom conhecimento de Orientação a Objetos e Design patterns
- Motivação
- Inglês **FLUENTE**

Desejáveis
- Formado em um curso de 4+ anos
- Experiência com Agile, TDD, BDD...
## Contratação

CLT
## Nossa empresa

A ArcTouch é uma empresa americana que foca em grandes projetos. Trabalhamos com grandes empresas como cliente (confere no http://arctouch.com)...
Os projetos costumam ser de curta duração, o que permite aplicar novas tecnologias e buscar novos conhecimentos.
Como a matriz da empresa fica em San Francisco, a empresa precisa de pessoas com fluência em inglês para participar das reuniões. E sempre existe a chance de ir passar um tempo na California trabalhando em algum projeto... : )
## Como se candidatar

Por favor envie um email para **luiz.santana@arctouch.com** com seu CV (em inglês) anexado e link para LinkedIn - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@arctouch-luizsantana: Pode ajustar o título pra deixar no padrão do template? Fica mais fácil pesquisar e deixa a lista mais organizada :smile:

**Comment by arctouch-luizsantana** [comment]
@davidtcdeveloper feito... foi mal, me perdi ali hehehe :grin:

**Comment by davidtcdeveloper** [comment]
@arctouch-luizsantana Sem problemas :)

**Comment by walmyrcarvalho** [comment]
@arctouch-luizsantana Essa vaga ainda está aberta? Senão irei fechar essa issue!
