### ISSUE TITLE
[RECIFE - PE] PESSOA DESENVOLVEDORA DE SOFTWARE ANDROID PLENO-SÊNIOR 

### ISSUE THREAD

**Issue by rodrigoperazzo** [androiddevbr/vagas#470]
## Descrição da vaga

Pessoa Desenvolvedora de Software Android Pleno-Sênior

## Local

Recife-PE. Há um pacote de benefícios para realizar a mudança para Recife (Aluguel + Mudança + Passagem Aérea).

## Benefícios
Vem trabalhar num ambiente mara e com projetos desafiadores. Vem liderar a inovação com a gente!

- Plano de Saúde Sulamérica
- Seguro de vida empresarial
- Vale transporte
- Auxílio Alimentação / Refeição
- Auxílio Lentes
- Auxílio Creche

## Requisitos

Obrigatórios
We are looking for people who would like to acquire, share and develop their knowledge in software engineering.

- BS in Computer Science or equivalent degree
- 5+ Years experience with Software Development
- Extensive knowledge of Java Programming language
- Extensive knowledge on Object Oriented Design
- Teamwork and good communication skills across multiple teams
- Be able to work independently and respond to multiple and conflicting requests under tight deadlines and in a dynamic working environment
- Good communication skills in both written and spoken English

Desejáveis
- Knowledge on scripting languages: python, bash, etc.
- Knowledge on Git and Gerrit and Jenkins tools
- Knowledge on Android Software Platform

Principais Responsabilidades
- Design, code and test software for mobile devices
- Review and discuss software architecture solutions for mobile devices based systems
- Review and discuss software requirements with external partners
- Cooperate with team members to review software artifacts, define interfaces and discuss best approach to solve end-user needs
- Coach and technically lead software engineering groups
- Maintain software artifacts overtime

## Contratação

CLT

## Nossa empresa

Somos um centro privado de inovação que cria produtos, serviços e negócios com Tecnologias da Informação e Comunicação (TICs). Desde 1996, desenvolvemos soluções em todo o processo de geração de inovação em e com TICs - desde o desenvolvimento da ideia, passando pela concepção e prototipação, até a execução de projetos para empresas dos mais diversos setores, como telecomunicações, eletroeletrônicos, defesa, automação comercial, financeiro, logística, energia, saúde e agronegócio. Em 2014, o CESAR superou a marca de R$ 90 milhões em vendas de projetos de inovação.

## Como se candidatar

Para mais informações sobre a vaga acesse o nosso Banco de Currículos www.cesar.org.br/trabalhe e coloque o código CSESW1416213 em oportunidades disponíveis.

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
