### ISSUE TITLE
Analista de TI - Android

### ISSUE THREAD

**Issue by WellingtonCosta** [androiddevbr/vagas#472]
## Descrição da vaga

Procuramos pessoas para compor uma nova equipe de desenvolvimento Android onde serão desenvolvidos projetos voltados para mercado financeiro.

## Local

Fortaleza - CE

## Benefícios

- Treinamentos Internos e Externos
- Plano de Saúde
- Plano Odontológico
- Plano de Previdência Privada
- Auxílio Alimentação e Auxílio Cesta Básica
- Auxílio Creche para filhos de até 06 anos
- Seguro de vida

## Requisitos

Obrigatórios
- Maioridade (18 anos completos)
- Formação: Superior Completo em Ciências da Computação, Sistemas de Informação, Análise e  Desenvolvimento de Sistemas e áreas afins
- Conhecimento em Java
- Consumo de Web Services
- Teste com JUnit e Espresso
- SQLite
- MVP
- Dagger 2
- Planejamento e elaboração de projetos de Tecnologia da Informação 

Desejáveis
- Kotlin
- SQL Server

Diferenciais
- Projetos opensource

## Contratação

CLT

## Como se candidatar

Por favor, acesse este [link](http://www.inec.org.br/controle/downloads_8149.pdf) do edital da vaga e siga as instruções para realizar sua candidatura.

**Comment by jpventura** [comment]
OIá, @WellingtonCosta! Qual o nível de senioridade (junior/pleno/sênior) procurado? Trata-se de uma vaga presencial, ou remota?

**Comment by WellingtonCosta** [comment]
Vaga presencial. Aqui não existe níveis de junior, pleno ou senior, mas pode colocar como pleno.
