### ISSUE TITLE
[BH] Avenue Code - Desenvolvedor(a) Android

### ISSUE THREAD

**Issue by TalentAcquisiton** [androiddevbr/vagas#473]
## Descrição da vaga
Desenvolvedor(a) Android para clientes nacionais e internacionais da Avenue Code.

## Local
Belo Horizonte/MG - Presencial

## Benefícios

VR ou VA 
Plano de Saúde (Bradesco)
Plano Odontológico (Odontoprev) 
Aulas de Inglês 2 vezes por semana (no horário de trabalho) 
PLR
Bônus por Performance
Reembolso de Certificações Técnicas (lista pré determinada)
Horário Flexível.

## Requisitos
JAVA 
XML
Android Studio
MVP, MVVM
Teste Unitários para Android
Support Library (Retrofit, Dagger, RXjava, OKhttp, Picasso...)

Desejáveis
Kotlin
Noções de UI

## Contratação
CLT 

## Nossa empresa
A Avenue Code é a principal consultoria de software focada na entrega de soluções de desenvolvimento ponta a ponta para a transformação digital em todas as vertentes. Com sede em São Francisco e três escritórios adicionais (Nova Iorque, Belo Horizonte e São Paulo) a Avenue Code é uma empresa 100% financiada com capital privado, rentável, e apresenta uma sólida trajetória de crescimento desde o primeiro dia. Nós nos preocupamos profundamente com nossos clientes, nossos parceiros e nossos consultores. Preferimos a palavra "parceiro" a "fornecedor" e nossos investimentos nos relacionamentos profissionais são um reflexo dessa filosofia. Temos muito orgulho da nossa perspicácia técnica, da nossa capacidade colaborativa de resolução de problemas e do calor e profissionalismo dos nossos consultores.

## Como se candidatar
Candidate-se através do link: https://www.avenuecode.com/careers/belo-horizonte-mg/desenvolvedor-a-mobile-android/

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by jpventura** [comment]
Olá, @TalentAcquisiton! Essa vaga ainda está aberta?
