### ISSUE TITLE
São Paulo/SP | Desenvolvedor (a) Android | Meta 

### ISSUE THREAD

**Issue by michelicamillo** [androiddevbr/vagas#474]
## Job description

A vaga será para atuar em uma célula de desenvolvimento ágil.
- Estimar o tempo necessário para implementar uma funcionalidade; 
- Indicar as consequências de alternativas técnicas; 
- Negociar com o Cliente a melhor solução para as necessidades de negócio; 
- Aplicar as práticas do processo; 
- Garantir que as ferramentas para testes sejam executadas da forma adequada; e 
- Entender profundamente os requisitos do que vai ser testado

## Local

São Paulo - próximo da Av. Paulista

## Benefícios

- Vale Refeição
- Vale Transporte
- Plano de Saúde
- Plano Odontológico
- Seguro de Vida
- Programa de Incentivo à Certificações

## Requisitos

Essecial: 
- Superior completo em cursos relacionados à TI 
- Experiência como desenvolvedor Android 
- Conhecimento de Fragments, RxJava, BufferKnife, Retrofit e Dagger 2 
- Conhecimento de métodos ágeis 
- Saber trabalhar em um ambiente colaborativo e com times multidisciplinares 
- Perfil argumentador e negociador, usando a comunicação a seu favor 

Desejável: 
- Participação ativa em comunidades, eventos ou cursos na área de métodos ágeis 
- Conhecimento das ferramentas da suite Atlassian ou similiares 

## Contratação

CLT

## Nossa empresa

Somos uma empresa com 27 anos de mercado de TI, seis escritórios no Brasil e com foco em soluções tecnológicas ágeis que simplificam e geram valor real no dia a dia das organizações.

Acreditamos no poder das pessoas para gerar resultados, somos pessoas servindo pessoas, temos gana por performance, crescemos e aprendemos juntos, pensamos e agimos como donos e buscamos a simplicidade.

## Como se candidatar

Candidate-se no link http://bit.ly/desenvolvedorAndroid ou envie seu currículo para recrutamento@meta.com.br ;)

**Comment by jpventura** [comment]
OIá, @michelicamillo ! Qual o nível de senioridade (junior/pleno/sênior) procurado? Trata-se de uma vaga presencial, ou remota?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
