### ISSUE TITLE
[SP - BERRINI] - SKY Brasil - Desenvolvedor Android Pleno/Senior)

### ISSUE THREAD

**Issue by diegoaspereira** [androiddevbr/vagas#475]
**[SP - BERRINI] - SKY Brasil - Desenvolvedor Android Pleno/Senior)**

**Empresa**
A SKY é a maior empresa de TV por Satélite do Brasil, com mais de 5MM de assinantes. 
A área de atuação será no departamento de DIGITAL, com o projeto do Aplicativo Minha SKY, este APP alcançou a marca de 5MM de downloads em 1,4 anos e possui as melhores marcas de usuários mensais, nota de usuários e crescimento do mercado de TV por Assinatura. 
Além de termos sido reconhecidos internacionalmente pelo uso de Inteligencia Artificial, Machine Learning e algumas técnicas de computação em nuvem (Step Functions).

**Descrição da vaga**
O profissional será responsável pelo desenvolvimento do app Android e a expectativa é que o profissional seja capaz de entregar um produto com qualidade e que encante os nossos usuários.

**Posição**
Desenvolvedor Android Pleno/Senior

** Tipo de contratação**
Contratação CLT Cooperado ou PJ

**Requisitos**
Experiência a nível pleno/sênior com desenvolvimento mobile nativo Android .
JAVA
XML
Android Studio
MVP, MVVM
Teste Unitários para Android
Support Library (Retrofit, Dagger, RXjava, OKhttp, Picasso...)
Conhecimentos em consumo de API RESTful

**Desejáveis**
Kotlin
Noções de UI

**Diferenciais**
Experiência com extensions (Android Wear, Android TV, widget).
Conhecimento em testes unitários.
Links com código no github e/ou apps publicadas.
Conhecimento em Integração Contínua.
Conhecimento em Node (JS);

**Como aplicar**
Envie seu CV com Pretensão Salarial para thiago.sano@sky.com.br

**Contato**
Thiago Sano
thiago.sano@sky.com.br

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by jpventura** [comment]
Olá, @diegoaspereira! Essa vaga ainda está aberta?

**Comment by diegoaspereira** [comment]
Olá, bom dia!
Sim, a vaga ainda está aberta.

Por gentileza envie seu CV para thiago.sano@sky.com.br<mailto:thiago.sano@sky.com.br>


Att,

[cid:image001.png@01D282FA.BCFE4120]

Diego Pereira | Digital - LAB’s
(11) 2123-9974 / (11) 98706-2571
Av. das Nações Unidas, 12901, Torre Oeste, 14º andar, CEP 04578-000 – São Paulo, Brasil



De: JP Ventura [mailto:notifications@github.com]
Enviada em: domingo, 29 de julho de 2018 20:45
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: Diego Arruda Soares Pereira <diego.pereira@terceiro-sky.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] [SP - BERRINI] - SKY Brasil - Desenvolvedor Android Pleno/Senior) (#475)


Olá, @diegoaspereira<https://github.com/diegoaspereira>! Essa vaga ainda está aberta?
