### ISSUE TITLE
(São Paulo-SP) Programador (a) Android Pleno ou Sênior- BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [androiddevbr/vagas#478]
## Descrição da vaga
Profissional atuará no desenvolvimento de projeto para grande banco de investimentos.

## Local
Vaga presencial no cliente, Bairro Itaim Bibi- Faria Lima- SP.

## Benefícios
- Vale refeição
-Assistência médica co-participação
-Seguro de Vida
-Vale alimentação
-Previdência Privada
-Plano odontológico

## Requisitos
Obrigatórios
- Experiência com Android e Java

Desejáveis
- Kotlin,  Cloud da Amazon, Jenkins, Git e Docker.

## Contratação
CLT, salário a combinar.

## Nossa empresa
BRQ Digital Solutions, com 25 anos de atuação na área de TI, temos unidades em SP, Rio de Janeiro, Curitiba, Nordeste e Nova York.

## Como se candidatar

Por favor envie um email para ryokota@brq.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
