### ISSUE TITLE
[Jaguariúna, São Paulo] Desenvolvedor Android | Capitani 

### ISSUE THREAD

**Issue by jacquevicari** [androiddevbr/vagas#479]
## Descrição da vaga

Atuará em projetos de transformação digital com aplicativos Android.

## Local

Jaguariúna/SP

## Benefícios

- A combinar.

## Requisitos

Obrigatórios
- Superior Completo em Tecnologia.
- Expertise em desenvolvimento em aplicações Android, atuando com desenvolvimento Ágil.
- Conhecimentos em blibliotecas complementares Android e Google Play Services, RxAndroid, Dagger, SQLite, Gson, Okhttp, Picasso.
- Inglês Intermediário. 

Desejáveis
- Conhecimentos práticos com repositórios Git e integração de RESTful APIs e OOP e OOAD. 

Diferenciais
- Conhecimento em modelagem de Objetos RBDMS.
- Conhecimento em APIs Salesforce (Rest, SOAP e Bulk) e Salesforce MobileSDK (com foco no SmartStore).
- Espanhol.

## Contratação

- CLT

## Nossa empresa

A Capitani é a consolidação de mais de duas décadas de atuação no fornecimento de pessoas para o mercado.

## Como se candidatar

Por favor envie um email para jacqueline.vicari@capitani.com.br seu CV anexado - enviar no assunto: Vaga Android

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
