### ISSUE TITLE
[Porto Alegre/RS] Android Engineer JR/PL | HP

### ISSUE THREAD

**Issue by viniciushisao** [androiddevbr/vagas#480]
## Descrição da vaga

- Designs limited enhancements, updates, and programming changes for portions and subsystems of end-user applications software running on local, networked, and Internet- based platforms.
- Analyzes design and determines coding, programming, and integration activities required based on specific objectives and established project guidelines.
- Executes and writes portions of testing plans, protocols, and documentation for assigned portion of application; identifies and debugs issues with code and suggests changes or improvements.
- Participates as a member of project team of other software applications engineers and internal and outsourced development partners to develop reliable, cost effective and high quality solutions for assigned applications portion or subsystem.
- Collaborates and communicates with internal and outsourced development partners regarding software applications design status, project progress, and issue resolution.

## Local

- Porto Alegre, Rio Grande do Sul, Brazil

## Requisitos

Obrigatórios

- Bachelor's or Master's degree in Computer Science, Information Systems, or equivalent.
- Typically 2-4 years experience.
- Experience on Android development (from designing to publish).
- Experience on design patterns (MVP, MVVM, etc.).
- Experience on software engineering (SOLID and OOP).
- Experience on designing and implementing Restful architecture (RestAPI).
- Experience on Java.
- Experience on Agile and Scrum methodologies.
- Experience on working with distributed and global teams.
- Experience with version control tools, CI/CD tools, unit test and test automation (git, Jenkins, JUnit).
- Excellent written and verbal communication skills in English.

Desejáveis

- Experience on distributed and global teams.
- Experience on RDBMS (MySQL, Oracle or similar).
- Experience in Javascript, HTML, CSS.
- Knowledge on Kotlin (or at least able to learn it).
- Android automation tests (Espresso, JUnit, RoboEletric, etc).

## Contratação

CLT a combinar

## Nossa empresa

"HP innovation springs from a team of individuals, each collaborating and contributing their own perspectives, knowledge, and experience to advance the way the world works and lives. From our earliest days, we’ve recognized that capturing and drawing from diverse points of view improves our products and services — and our company as a whole. 
Go to our [site](http://www.hp.com) to know more!

## Como se candidatar

[Subscribe here](https://h30631.www3.hp.com/job/porto-alegre/software-engineer/3544/7840632)

**Comment by viniciushisao** [comment]
olá @jpventura ! Pode, por favor, remover o label de "PJ" e adicionar também o label de "Pleno". Obrigado

**Comment by guilhermeoa07** [comment]
Os 2 a 4 anos também é uma exigência para Júnior?
