### ISSUE TITLE
[Remoto] desenvolvedor android | enjoei

### ISSUE THREAD

**Issue by Anndressa** [androiddevbr/vagas#481]
## Descrição da vaga

nosso time da engenharia está a procura de um novo membro para a equipe de desenvolvimento Android. 

responsabilidades:
- desenvolver, implementar e manter código bem estruturado, reutilizável e de ótima performance
- interpretar e reproduzir telas a partir de layouts
- analisar, medir esforço e planejar o desenvolvimento de novas funcionalidades
- identificar e corrigir bugs e gargalos de performance
- fazer testes e code reviews
- ter boa comunicação com a equipe, desejo de aprender e aplicar novas tecnologias
- participar de definições estratégicas da evolução do produto
- ser pró-ativo na resolução dos problemas

## Local

remoto 

## Benefícios

- VA ou VR
- plano de saúde e odontológico
- seguro de vida
- ajuda de custo internet

## Requisitos

Obrigatórios
- sólido conhecimento da plataforma Android e no desenvolvimento com diferentes versões do Android SDK (4.1+)
- Android Studio IDE
- gerenciamento de dependências (Gradle)
- controle de versões (GIT)
- conhecimento de padrões de arquiteturas de software
- metodologias ágeis (scrum, kanban, etc)
- conhecimentos de U.X.
- experiência com consumo de apis REST com padrão JSON
- experiência no envio de aplicações para a Play Store
- experiência com Google Play Services (Location, Maps e Places)
- experiência com Firebase (FCM, Analytics, App Indexing)
- conhecimento do ciclo de vida da aplicação e gerenciamento de memória
- conhecimento de gerenciamento de arquivos e banco de dados no Android
- detalhista com a reprodução de layouts na aplicação (saber usar o Sketch é diferencial)  

Desejáveis
- familiaridade com Pull Request e Code Review
- experiência com testes automatizados
- integração contínua
- experiência no desenvolvimento de views customizáveis
- experiência com a configuração de variantes de compilação (build types, flavors) e internacionalização

## Contratação

CLT

## Nossa empresa

[enjoei.com.br](https://www.enjoei.com.br/)

startup brasileira. arroz com feijão. marketplace que vem dobrando de tamanho todo ano. 
 
empresa investida pelos fundos monashees+ e bessemer venture partners.

## Como se candidatar

https://jobs.kenoby.com/enjoei/job/android-developer/5ab558c1985d163e33515c68

**Comment by jpventura** [comment]
Tudo bem, @Anndressa? Está procurando candidatos junior, pleno ou senior?

**Comment by Anndressa** [comment]
pleno/senior

**Comment by RafaCoimbra** [comment]
@Anndressa Acabei de me candidatar para vaga

**Comment by brdevandroid** [comment]
Boa tarde Anndressa, recebi um e-mail de vocês falando que tinha uma anexo, porém não localizei.

**Comment by DaniellSousa** [comment]
Boa tarde @Anndressa . Vocês dão feedback para os concorrentes à vaga? Me candidatei a 14 dias.
