### ISSUE TITLE
[São Paulo] Desenvolvedor Android Sênior - CLT - Sênior - Presencial 

### ISSUE THREAD

**Issue by HeloisaMoraes** [androiddevbr/vagas#482]
## Descrição da vaga
Desenhar sistemas de informação apropriados às necessidades dos usuários e consistentes com a arquitetura de software da organização, realizando muitas das tarefas do nível pleno ou parte do especialista, sendo que o diferencial está relacionado à garantir que os aspectos de análise e desenvolvimento mais complexos

## Local
Paulista - SP 

## Benefícios
Vale Transporte; Vale Alimentação de R$ 900,00/mês; Vale Refeição R$ 31,50/dia;  + Assistência medica
(Sul América ) plano padrão R$ 6.50 por mês + Assistência Odontológica + Seguro de Vida + PLR

## Requisitos

Obrigatórios
Experiência de mais de 5 anos em análise e desenvolvimento de sistemas:
Experiência em desenvolvimento Mobile para IOS
Consumo de serviços rest via aplicação Mobile
Conhecimento no sistema operacional IOS
Linguagem S wift
Plataforma Java ( JSE, JEE, APIS e Bibliotecas ).
Repositório de código (git, svn)
Bibliotecas, frameworks e ferramentas (obrigatórios: Spring, Hibernate)

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para heloisa.moraes@5aattiva.com.br com seu CV anexado - enviar no assunto: Vaga Android
###

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by vitor-ramos** [comment]
A vaga é para Android ou iOS?

**Comment by jpventura** [comment]
Olá, @HeloisaMoraes! Tudo bem? Esse mural é para divulgação de vagas em desenvolvimento Android, infelizmente não divulgamos vagas iOS.
