### ISSUE TITLE
[Campinas, SP] Desenvolvedor Android | Rapiddo

### ISSUE THREAD

**Issue by marcelo-alves-movile** [androiddevbr/vagas#484]
## Descrição da vaga

**O que valorizamos no Grupo Movile?**

- Senso de dono: gostamos de pessoas que se apropriam dos projetos e fazem o melhor;
- Hands-on: porque colocar a mão na massa é essencial;
- Foco em resultado: pois é assim que impactamos verdadeiramente a vida das pessoas;
- Inovação: precisamos mudar o jeito que as coisas acontecem;
- Apaixonadas pelo que fazemos e pelos nossos sonhos.

**Responsabilidades e atribuições:**

- Criação de códigos de boa qualidade a partir de designs/wireframes;
- Criação e manutenção da arquitetura, identificação e manutenção de bugs e gargalos de performance nos apps já existentes;
- Desenvolver novos apps do zero.

## Local

Campinas

## Benefícios

- Plano de Saúde/Odontológico 
- GymPass
- Auxílio Idioma
- VA / VR
- PLR

Além de desfrutar do nosso ambiente, que oferece: Café da manhã , Refri, Energético, Cerveja, Snacks, .... \o/

## Requisitos

Obrigatórios

- Sólida experiência com Android SDK;
- Experiência prática com desenvolvimento em Kotlin;
- Conhecimento de Programação Orientada a Objetos;
- Bom conhecimento de APIs REST;
- Padrões de programação funcional e RxJava;
- MVP (Model View Presenter) e Clean Architecture;
- Experiência na condução de Testes Unitários.

Diferenciais

- Modelos de programação reativas;
- Construção de componentes de UI.

## Contratação

CLT

## Nossa empresa

https://www.rapiddo.com/
Uma empresa do Grupo Movile https://www.movile.com/#/

## Como se candidatar

Por favor envie um email para roberta.schwandt@movile.com + seu CV anexado - enviar no assunto: Vaga Android - Rapiddo

Ou direto pelo site: https://jobs.kenoby.com/Rapiddo

**Comment by jpventura** [comment]
Tudo bem, @marcelo-alves-movile? Procuram desenvolvedores júnior, pleno ou sênior? Presencial ou remoto?

**Comment by marcelo-alves-movile** [comment]
@jpventura nível esta em aberto, depende muito do decorrer da entrevista com candidato ... A vaga é pra Presencial.

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by marcelo-alves-movile** [comment]
@marciofermino poderia me enviar o seu currículo? 
Enviar para: marcelo.alves@movile.com
