### ISSUE TITLE
Desenvolvedor Android - Campinas

### ISSUE THREAD

**Issue by Marianashare** [androiddevbr/vagas#485]
Empresa de tecnologia localizada em Campinas, S.P., com foco em inovação no desenvolvimento de aplicativos nativos e sistemas web.
A empresa possui uma forte cultura e procura profissionais que estejam engajados com ela. É uma companhia que utiliza e aprende sobre tecnologia de ponta, oferece aos funcionários o envolvimento com grandes projetos e ganho rápido de responsabilidades, crescimento contínuo na função e ambiente jovem e descontraído.
Para pessoas formadas em cursos Técnicos em áreas correlatas, cursando nível superior ou  já concluídos.
- Experiências desejáveis da vaga
•	Conhecimentos em Java e Kotlin;
•	Familiaridade com arquitetura e boas práticas para Android;
•	Criação de Layouts em XML;
•	Conhecimento de ferramentas como GIT, Android Studio, Fastlane;
•	Conceito de Programação Reativa;
•	Criação de códigos de boa qualidade a partir de designs de wireframes;
•	Criação e manutenção da arquitetura, identificação e manutenção de bugs e gargalos de performance em alguns dos aplicativos do grupo.

OBS: A vaga é efetiva - Profissional PJ

Local - Campinas,S.P.

## Como se candidatar

Por favor envie um email para ct@sharerh.com com seu CV anexado - enviar no assunto: Vaga Android-Campinas

**Comment by mion23** [comment]
olá Mariana, existe a possibilidade de remoto?

**Comment by Marianashare** [comment]
Olá boa tarde. Tem a possibilidade de ser remoto meio período do dia, ou
metade da semana remoto e metade presencial.
Você tem interesse ou alguém para indicar?
Obrigada



2018-07-03 16:43 GMT-03:00 mion23 <notifications@github.com>:

**Comment by mion23** [comment]
tenho interesse! Vou mandar meu currículo e no e-mail explicarei a situação.

Obrigado!

**Comment by Marianashare** [comment]
Ok combinado. Pode enviar. Você mora em Campinas?



2018-07-03 17:08 GMT-03:00 mion23 <notifications@github.com>:

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by jpventura** [comment]
@Marianashare de acordo com as [regras da comunidade](https://github.com/androiddevbr/vagas/blob/master/README.md), o nome da empresa precisa estar na descrição da vaga.

**Comment by Marianashare** [comment]
Boa tarde.

Qual seu nome?
Eu não anunciei vagas nos últimos dias. Poderia me dizer qual vaga foi
anunciada por favor?

Obrigada.



Em qua, 5 de set de 2018 às 17:46, JP Ventura <notifications@github.com>
escreveu:
