### ISSUE TITLE
[São Paulo, São Paulo] Desenvolvedor(a) Android (Pleno e/ou Senior)

### ISSUE THREAD

**Issue by ademar111190** [androiddevbr/vagas#486]
## Descrição da vaga

Você atuará em projetos de desenvolvimento de aplicativos para Android e contribuir diariamente com nossos projetos.

Estamos crescendo o time, há uma vaga para desenvolvedor(a) Android Nativo, há também uma vaga para desenvolvedor(a) React e duas vagas para desenvolvedor(a) iOS Nativo.

## Local

[Escritório na Maestro Cardim - São Paulo - SP](https://www.google.com.br/maps/place/PorQueN%C3%A3o%3F/@-23.5727607,-46.6425582,16.9z/data=!4m5!3m4!1s0x0:0xce9ffe4627d8e0b0!8m2!3d-23.5723681!4d-46.6416568)
A vaga é aberta à remotos também

## Benefícios

- Férias remuneradas
- Bônus por performance
- Home-office (uma vez por semana)
- Licença maternidade / paternidade
- Trabalhar com pessoas que gostam de ensinar e de aprender
- Ambiente de trabalho descontraído
- Trabalhar com clientes legais e parceiros

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android (Pleno) ou 5+ anos no caso de (Senior)
- GIT
- Restful

Desejáveis
- RxJava
- Clean
- WebSocket
- Kotlin

## Contratação

PJ

## Nossa empresa

Na [PorQueNão?](http://porquenao.mobi/) construímos produtos digitais memoráveis, a partir de motivações reais do dia-a-dia, proporcionando experiências únicas a pessoas. Acreditamos que experiências digitais mudam a vida das pessoas.

## Como se candidatar

Pelo formulário a seguir 😗
[https://form.jotformz.com/81844007712655](https://form.jotformz.com/81844007712655)

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
