### ISSUE TITLE
[Curitiba] Desenvolvedor Mobile [EADBOX]

### ISSUE THREAD

**Issue by RafaeleEADBOX** [androiddevbr/vagas#488]
**Sobre a EADBOX:**

EADBOX é uma startup que cresceu 130% no último ano, e que está revolucionando o mercado da educação e treinamentos corporativos por meio de um software utilizado para criação e distribuição de cursos online.

A empresa cresce rápido, milhares de novos alunos todos os meses, com mais de 800 clientes entre autores e grandes empresas como Ache, Totvs, Renault, WiseUp, Heineken. Num forte processo de crescimento no Brasil, México, Argentina e Colômbia.

Começamos 2018 com 108 pessoas e queremos acabar o ano com mais de 267 pessoas entusiasmadas e comprometidas com um propósito: ser uma grande empresa e transformar a eduacação global.

**Local:**

Curitiba ou remoto

**A vaga:**

Hoje um curso online é basicamente uma sequência de conteúdos digitais enfileirados, o efeito disso é que poucos alunos engajam (ou aprendem) de fato. Entendemos que a educação online tem grande potencial, porém deve ser reinventada e a interface é um dos pilares desta evolução. Com isso, buscamos um desenvolvedor que esteja disposto a inovar e criar com a gente o app mobile, facilitando os estudos dos nossos alunos.

**Buscamos desenvolvedor CLT - Pleno com experiência em:**

Linguagem Swift
Cocoapods
API RESTfull
JSON API
Repositório Git
Linguagem Kotlin

**Benefícios e diferenciais:**

- Vale Transporte
- Vale Refeição
- Plano de Saúde
- Seguro de Vida
- Ambiente dinâmico e inovador
- Equipe comprometida e empolgada

Interessados se candidatar pelo link [https://hipsters.jobs/job/3251/desenvolvedor-mobile-ios-android/] ou dúvidas para o e-mail rafaele.bastian@eadbox.com

**Comment by jpventura** [comment]
Olá @RafaeleEADBOX! A vaga é PJ ou CLT? Qual o nível de senioridade?

**Comment by RafaeleEADBOX** [comment]
Olá @jpventura é para CLT e para Pleno

**Comment by cocuroci** [comment]
@RafaeleEADBOX apesar de estar em Android, é para iOS também?

**Comment by RafaeleEADBOX** [comment]
@cocuroci estamos com as duas posições, tanto para Android quanto para iOS, o candidato pode escolher qual é da sua preferência ;) estamos com vários projetos massas para mobile!
