### ISSUE TITLE
[Porto Alegre, RS] Desenvolvedor(a) Android | Cíngulo

### ISSUE THREAD

**Issue by cnadm** [androiddevbr/vagas#489]
## Descrição da vaga

O Cíngulo, startup de bem-estar emocional acelerada pela WOW Aceleradora, já com quase 1 milhão de downloads e nota 4.9 na Google Play e na App Store, está selecionando um(a) dev Android pleno ou sênior para integrar uma equipe dinâmica, engajada, responsável e crescente.

O(a) dev será responsável pelo desenvolvimento Android, criando a versão nativa do *novo* app. É necessária experiência com Kotlin, Realm e Rx. Nossa API é REST, com documentação, tem mais de 95% de cobertura de testes e o fluxo de design está devidamente organizado.

## Local

Presencial em Porto Alegre, RS
Bairro Moinhos de Ventos

## Benefícios

- ambiente acolhedor e com pessoas legais
- tecnologias atuais
- boa visibilidade do app (quase 1M de users e crescendo)
- o mundo é limite (o Cíngulo vai ser disponibilizado pra outros países provavelmente já no próximo ano)

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados
- Kotlin, Realm e Rx
- Animações
- Apps publicados
- Obs: queremos alguém experiente (Pleno puxando pra Sênior ou já Sênior preferencialmente) e que entre "quente" em programação Android com os itens acima. Não adianta enviar currículo se não se encaixar realmente nisso pois estaremos ambos perdendo tempo nesse momento.

Diferenciais
- Vejam os comentários nas lojas. O Cíngulo é mais do que uma startup "cool" com o discurso padrão de querer mudar a vida das pessoas. O Cíngulo *realmente* muda a vida das pessoas *pra melhor*.

## Contratação

CLT 5 a 8k a depender da experiência.

## Nossa empresa

https://www.cingulo.com já explica suficientemente bem.

## Como se candidatar

Por favor envie um email para contato@cingulo.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by lesimoes** [comment]
Eu uso esse app e é muito bom! Parabéns pelo trabalho!

**Comment by rserro** [comment]
Obrigado @lesimoes ! Ler comentários como esse nos motiva muito a continuar. Teremos novidades super legais até ano que vem :)

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
