### ISSUE TITLE
[Florianopolis/ SC] Android Developer na [AgileProcess]

### ISSUE THREAD

**Issue by amadeu01** [androiddevbr/vagas#491]
Venha colaborar na construção do sistema mais inovador da área de logística!

# Descrição da Vaga:

Atuar em projetos de desenvolvimento de aplicativos para Android (nativo) e contribuir diariamente com nossos projetos.

Participará do desenvolvimento e construção de novos apps. Trabalhará com novas tecnologias e desafios.

## Experiência necessária:

- Ótima lógica de programação;
- Conhecimento em testes (BDD, TDD)
- Principios de programação (SOLID)
- Conhecimento em Java.
- Conhecimento do SKD do Android.
- Inglês (nível suficiente para fazer leitura de textos e documentações técnicas);

## Conhecimentos desejáveis (quanto mais melhor!):

- Kotlin
- Conhecimento em bibliotecas como Retrofit, OKHttp, Glide, RxJava...
- Design Patterns
- Arquiteturas (MCV, MVP, MVVM)

# Horário

Flexível. Dependendo da contratação.

# Tipo de contratação

PJ ou CLT

## Nossa [empresa](http://agileprocess.com.br)

Somos uma startup e buscamos talentos! Queremos pessoas interessadas em aprender! Venha desenvolver para web e android utilizando as mais modernas linguagens e técnicas.

Se você gosta de tecnologia vai adorar fazer parte do nosso time! Nossos projetos mexem com Javascript, Java, C#, Python, Android (Java, Kotlin), AWS e MySQL. Queremos um time full-stack (mobile, front e back-end)!

Buscamos pessoas que tenham a cara da empresa: jovem, automotivado, comprometido, que goste de desafios e seja proativo. Temos um ambiente descontraído com videogame, lanches e cerveja!

## Benefícios

- Almoço
- Lanche
- Vale transporte
- Video Game

# Local

Florianopolis, João Paulo.

# Como se candidatar

Ficou interessado? Quer aprender e fazer parte do nosso time? 
Entre em contato rápido! São poucas vagas. 
Nos mande um e-mail para marcarmos um papo.

Email:  alistamento@agileprocess.com.br

**Comment by jpventura** [comment]
Olá @amadeu01! Qual o nível de senioridade para a vaga?

**Comment by amadeu01** [comment]
@jpventura Desculpa, eu acabei não colocando. Junior ou Pleno

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
