### ISSUE TITLE
Vaga em desenvolvimento Android na Vivakey

### ISSUE THREAD

**Issue by vitordealmeida** [androiddevbr/vagas#493]
## Descrição da vaga

Vaga em desenvolvimento mobile - Android

## Local

Escritório em São Paulo, com possibilidade de remoto

## Benefícios

- Crescimento pessoal e profissional muito acelerado
- Salário acima do mercado
- Possibilidade de remuneração através de participações

## Requisitos

Obrigatórios
- Desenvolvimento mobile na plataformaAndroid
- interfaces, integração com SDK e integração com API

Desejáveis
- Experiência com Espresso e UI Automator
- Experiência com RxJava

Diferenciais
- Desenvolvimento mobile em alguma plataforma híbrida

## Nossa empresa

Participar da equipe de desenvolvimento de um sistema de IoT, com aplicações Web, móveis e embarcadas em um negócio desafiador e de grande potencial.

Este é o desafio, está preparado?

Sobre a Vivakey:

Um hotel autônomo operado por inteligência artificial, dispositivos conectados, e sistemas de identificação digitais. Vivakey é a tecnologia com base na internet das Coisas que realiza distribuição automática de chaves e de acessos, reduzindo erros e permitindo automação de toda operação

Veja o vídeo da Vivakey em https://bit.ly/2IGe1x4

## Como se candidatar

Enviar curriculo para vagas@vivakey.com.br

**Comment by jpventura** [comment]
Tudo bem @vitordealmeida? Qual o nível de senioridade para a vaga?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
