### ISSUE TITLE
[Campinas] Desenvolvedor Android

### ISSUE THREAD

**Issue by talentreplacement** [androiddevbr/vagas#495]
Exigências 
Experiência comprovada de desenvolvimento de software
Experiência comprovada de desenvolvimento de aplicativos Android
Ao menos um aplicativo publicado na Google Play Store
Experiência com Android SDK
Experiência em trabalhos com dado remotos via REST e JSON
Experiência em implementação de bibliotecas de terceiros (Facebook;Twitter;Google)
Sólido conhecimento da arquitetura de aplicações move e seu ciclo de vida

Responsabilidades
Criar e desenvolver aplicativos avançados na plataforma Android
Colaborar com o time multifuncional para definir, desenhar e entregar novas funcionalidades
Trabalhar com APIs e serviços externos de dados
Criar códigos robusto, testável e reutilizável
Trabalhar em correções de bugs e aperfeiçoamento da performance de aplicações
Continuamente descobrir, testar e implementar as novas tecnologias para maximar a eficiência do produto e do desenvolvimento

Enviar cv com pretensao salarial para: recrutamento@talentreplacement.com.br

**Comment by jpventura** [comment]
Olá @talentreplacement! Perguntas a serem respondidas:

  - Vaga é presencial ou remoto?
  - CLT ou PJ?
  - Qual o nível de senioridade?

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
