### ISSUE TITLE
Vaga de Desenvolvedor Android Senior 

### ISSUE THREAD

**Issue by GabrielaNavarr** [androiddevbr/vagas#496]
A procura de desenvolvedores Android senior, com experiência em fintech e que tenha conhecimento em espanhol ou inglês intermediário
Favor enviar CV pelo email gnavarro@optionsgroup.com.

Local

Osasco - São Paulo

Benefícios

- Vale Alimentação
-Refeitorio no local
-Academia
-PLR
- Plano de Saude
- Auxilio Combustivel
...

Requisitos

Obrigatórios
- 3+ anos de experiência com Android Java

Contratação

CLT

Quem somos?

A Options Group é uma consultoria Americana focada em recrutamento para Fintech e Mercado Financeiro. Recruto especialmente para vagas de tecnologia em bancos ou fintech.

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
