### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Android

### ISSUE THREAD

**Issue by silvafabio** [androiddevbr/vagas#497]
## Descrição da vaga

Projeto para desenvolvimento de um App de rede social como o do Facebook, mas beemmm mais simples.

## Local

Zona Sul de São Paulo próximo ao Shopping Interlagos

## Benefícios

- 1 hora de almoço

## Requisitos

Obrigatórios:
- 3+ anos de experiência com Android (Java)
- Confortável com padrão MVP, MVC, MVVM e derivados
- SQL Lite
- Acesso a micro serviços em JSON
- Autenticação JWT
- Domínio sobre o Framework Android
- Experiência com Espresso e UI Automator
- Dominar os requisitos acima e ter experiência comprovada, pois desenvolverá o APP sozinho.

Desejáveis:

- Ter trabalhado em times que utilizem alguma metodologia Ágil.

## Contratação

PJ com duração estimada de 5 meses e início em agosto.

## Nossa empresa

Somos uma Software House a mais de 10 anos no mercado que desenvolve softwares sob encomenda para nosso clientes.

## Como se candidatar

Por favor, encaminhar o CV com pretensão salaria para vagas@vanguardati.com.br. 
CVs sem pretensão salarial serão desconsiderados.

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
