### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) IOS

### ISSUE THREAD

**Issue by silvafabio** [androiddevbr/vagas#498]
## Descrição da vaga

Projeto para desenvolvimento de um App de rede social como o do Facebook, mas beemmm mais simples.

## Local

Zona Sul de São Paulo próximo ao Shopping Interlagos

## Benefícios

- 1 hora de almoço

## Requisitos

Obrigatórios:
- 3+ anos de experiência com desenvolvimento em APPS IOS
- Acesso a micro serviços em JSON
- Autenticação JWT
- Domínio sobre o Framework IOS
- Dominar os requisitos acima e ter experiência comprovada, pois desenvolverá o APP sozinho.

Desejáveis:

- Ter trabalhado em times que utilizem alguma metodologia Ágil.

## Contratação

PJ com duração estimada de 5 meses e início em agosto.

## Nossa empresa

Somos uma Software House a mais de 10 anos no mercado que desenvolve softwares sob encomenda para nosso clientes.

## Como se candidatar

Por favor, encaminhar o CV com pretensão salaria para vagas@vanguardati.com.br. 
CVs sem pretensão salarial serão desconsiderados.

**Comment by davidtcdeveloper** [comment]
@silvafabio estou encerrando mais esta issue por também não se tratar de uma vaga para desenvolvedor Android. Peço que revise as regras deste mural e leia o template com atenção.
