### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Java EE

### ISSUE THREAD

**Issue by silvafabio** [androiddevbr/vagas#499]
## Descrição da vaga

Projeto para desenvolvimento de um App de rede social como o do Facebook, mas beemmm mais simples.

## Local

Zona Sul de São Paulo próximo ao Shopping Interlagos

## Benefícios

- 1 hora de almoço

## Requisitos

Obrigatórios:
- 3+ anos de experiência com Java EE
- Confortável com MVC, Clean Architecture e TDD
- Java EE 8
- Microprofile 1.3
- JSF 2.3, JPA 2.2, JAX-RS 2.1, CDI 2.0, Bean Validation 2.0, Java Mail 1.6, Servlet 4.0
- JUnit 4
- JWT
- Glassfish 5 ou Payara Micro 5
- Dominar os requisitos acima e ter experiência comprovada, pois desenvolverá o APP sozinho.

Desejáveis:

- Ter trabalhado em times que utilizem alguma metodologia Ágil.

## Contratação

PJ com duração estimada de 5 meses e início em agosto.

## Nossa empresa

Somos uma Software House a mais de 10 anos no mercado que desenvolve softwares sob encomenda para nosso clientes.

## Como se candidatar

Por favor, encaminhar o CV com pretensão salaria para vagas@vanguardati.com.br. 
CVs sem pretensão salarial serão desconsiderados.

**Comment by davidtcdeveloper** [comment]
@silvafabio este mural de vagas é destinado somente a vagas  para desenvolvedores Android. Como não encontrei a palavra Android em nenhum momento, estou encerrando a issue.
