### ISSUE TITLE
[Rio de Janeiro, RJ] Desenvolvedor(a) Mobile

### ISSUE THREAD

**Issue by muxidev** [androiddevbr/vagas#500]
## Descrição da vaga

Desenvolvimento de produtos MUXI

- Desenvolvimento de soluções de pagamento nas plataformas Android.

- Desenvolvimento de protótipos em conjunto com a equipe de inovação, colaborando com ideias para novas soluções.
- Nível: Sênior, Pleno ou Júnior. 

## Local

Centro - Rio de Janeiro - RJ

## Benefícios

- +10% do Salário podendo distribuir em algumas opções
- Vale refeição
- Vale transporte
- Plano de saúde
- Plano odontológico
- Horário flexível
- Copa com biscoito e café
- Trabalhe de bermuda
- Evento de TI mensalmente (Com PIZZA!)
- Time super qualificado

## Requisitos

-  Experiência em desenvolvimento para Android ou iOS.

Desejáveis

- Versionamento GIT
- Inglês avançado
- Testes automatizados utilizando os principais frameworks da plataforma Android (Espresso, Mockito e etc)
- Integração contínua (CI – Jenkins)
- Alguns frameworks padrões da plataforma: Dagger, Retrofit e etc
- Conhecimento de metodologias Ágeis e suas ferramentas (JIRA, Scrum)
- Conhecimento com linguagem C/C++
- Conhecimento de padrões de projeto

Diferenciais

- Conhecimento JNI
- Portfólio de aplicativos Android desenvolvidos
- Participação ativa na comunidade Android
    

## Contratação

CLT

## Nossa empresa

Você gosta de inovação, desafios e quer deixar sua marca no que faz?

Então venha ser um Muxer e fazer parte de um time diferenciado.

Buscamos profissionais com bom raciocínio lógico, habilidade para resolução de problemas, que saibam trabalhar de forma colaborativa e que tenham foco em resultado.

http://www.muxi.com.br/

## Como se candidatar

Os interessados em participar deverão enviar um e-mail para mobile@muxi.com.br , com o CV anexado .

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by jpventura** [comment]
Olá, @muxidev! Essa vaga ainda está aberta?
