### ISSUE TITLE
[São Paulo, SP] Android Developer Pleno

### ISSUE THREAD

**Issue by Lilicaan** [androiddevbr/vagas#502]
## Descrição da vaga

Se você é ávido por tecnologias de ponta e gosta de novos desafios...Aqui é o seu lugar!

Na Dextra, os developers são responsáveis pela expertise e conhecimento das tecnologias e propõem as melhores soluções técnicas durante todo o processo de desenvolvimento de software, garantindo o sucesso da entrega para o cliente.

O que você precisa saber para ocupar esta vaga?

Programar.. Mas com paixão! 
Experiência com Kotlin e desenvolvimento de telas para produtos digitais em Android (Componentes Nativos, Views, Criação de componentes customizados) e Integração com API’s REST.

## Local

São Paulo - Vila Olímpia

## Contratação

CLT

## Nossa empresa

A Dextra é um estúdio de inovação digital e de desenvolvimento de software ágil para clientes que buscam criar produtos disruptivos. Combinamos processos de inovação, design de UX, novas tecnologia e visão de negócios para criar software que reposicione os nossos clientes no mundo dos negócios digitais.

## Como se candidatar

Envie  seu cv ou LinkedIn para recrutamento@dextra.com.br - enviar no assunto: VagaAndroidSP

**Comment by 1jGabriel** [comment]
@Lilicaan bom dia, o email está correto?

**Comment by Lilicaan** [comment]
@1jGabriel Infelizmente acabou indo uma letra a mais, já fiz a correção e o e-mail correto é: recrutamento@dextra.com.br
