### ISSUE TITLE
SÃO PAULO - Desenvolvedor Android ( Pleno e Senior) - RESOURCE

### ISSUE THREAD

**Issue by POLLEZI** [androiddevbr/vagas#504]
## Descrição da vaga

Projeto de transformação digital - Ecommerce

## Local

Alphaville - SP

## Benefícios

VR
VT
Convenio Médico
Convenio Odontologico
Auxilio Creche
Convenio Farmácia
Seguro de Vida

## Requisitos

Android Studio
GIT
Firebase
Crashlitycs

## Contratação

CLT

## Nossa empresa
Venha fazer parte do time de Inovação Digital da Resource, uma das maiores integradoras digitais do Brasil e uma as empresas de TI que mais crescem no País. Com 25 anos no mercado, multinacional brasileira com presença global, com 21 escritórios em 5 países. 
Também está presente no Vale do Silício com um avançado Centro de Pesquisa e Inovação, o que possibilita estar cada vez mais próxima do cliente, entender melhor o seu negócio e oferecer a melhor solução.

## Como se candidatar

Por favor envie um cv para adriana.pereira@resourceit.com ou indique um amigo!!!
 - enviar no assunto: Vaga Android

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
