### ISSUE TITLE
Berlin - Germany - Android developer (visa sponsor)

### ISSUE THREAD

**Issue by santanaluiz** [androiddevbr/vagas#505]
## Descrição da vaga

As our new Mobile Engineer you will need to have:

- PASSION for tech; it’s something many companies speak about, but at Affinitas, we put those words into action! We were one of the earliest startups in Berlin from the ‘new wave’ of tech startups. In fact, we’re practically startup royalty - successful (and profitable) with fun plans for expansion.
- Affinitas brands are on the ‘serious dating’ side of the spectrum of dating platforms (an antidote to the casual hookup brands flooding the market). Elite Singles, eDarling, and Attractive World are our main brands aimed at professionals looking for love.
- So; want to make a difference in the lives of millions of singles? Are you interested in joining an ambitious and inclusive workplace? The tech teams are continually striving for the highest quality, quick-release solutions. We work in small, focussed, cross-functional teams using bits of Scrum, Kanban, and a smidge of Extreme Programming.
- Our teams have Product Management, Devs, and UX all working together every day.

## Local

Berlin - Germany

## Benefícios

**What We Offer:**

Super smart, dynamic, international team members. Highly skilled people striving for results; professional but with a fantastic sense of humour.

A competitive salary, great benefits and an excellent working environment.

Berlin startup amenities, such as nice laptops, and great office facilities (fair warning though: don’t be too sad when we beat you at table tennis or kicker in the beginning, as we’ve been training a lot)

An opportunity to build a platform which is used by millions in many, many countries that help people find their soul mate.

## Requisitos

Obrigatórios
- INGLÊS fluente. Não precisa falar alemão.
- Pelo menos 5 anos de desenvolvimento (sendo pelo menos 2 como Android)

## Contratação

Contrato permanente.

## Nossa empresa

Spark Networks é um dos maiores grupos de dating apps no mundo e está presente em tem apps presente em vários países. A empresa tem base em Berlim (Alemanha) e procura desenvolvedores com interesse em se mudar para Alemanha (SOMENTE PRESENCIAL).

## Como se candidatar

Enviar e-mail para:
luiz.santana@affinitas.de

No título do e-mail, POR FAVOR, colocar: **[Android dev br]**

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.
