### ISSUE TITLE
Especialista em Sistemas - Desenvolvimento de SW (Júnior, Pleno e Sênior)

### ISSUE THREAD

**Issue by lucas-inatel** [androiddevbr/vagas#506]
## Descrição da vaga

Especialista em Sistemas - Desenvolvimento de SW (Júnior, Pleno e Sênior)

## Local

Inatel - Santa Rita do Sapucaí - MG

## Benefícios

- Plano de saúde
- Seguro de vida
- Providencia privada
- Áreas de lazer e esporte

## Requisitos

Obrigatórios
 - Formação superior completa em cursos na área de tecnologia;
 - Bons conhecimentos e experiência com: Java Standard, Cassandra, Apache AVRO, Metadata (Javascript), GIT/Gerrit;
  - Inglês avançado.

Desejáveis
- Boa comunicação

## Contratação

CLT

## Nossa empresa

Vou deixar o site para que vocês possam ter a visualização de tudo que temos por aqui: https://inatel.br/home/
Qualquer dúvida estarei a disposição.

## Como se candidatar

[Link para a vaga](https://epartner.vagas.com.br/PagVagaDirSS.asp?v=1687110&pp=https%3A//epartner.vagas.com.br/GoHome.asp%3Fv%3D1687110%26j%3Dt%26sslon%3D1&wiw=1536)

**Comment by jpventura** [comment]
Olá, @lucas-inatel! Tudo bem?

Esse board é para postagens de vagas relacionadas com desenvolvimento Android.
