### ISSUE TITLE
Especialista em Sistemas - Tester (QA)

### ISSUE THREAD

**Issue by lucas-inatel** [androiddevbr/vagas#507]
## Descrição da vaga

Especialista em Sistemas - Tester (QA)

## Local

Inatel - Santa Rita do Sapucaí - MG

## Benefícios

- Plano de saúde
- Seguro de vida
- Providencia privada
- Áreas de lazer e esporte

## Requisitos

Obrigatórios
- Formação superior completa em cursos na área de tecnologia;
- Experiência com automatização de testes;
- Bons conhecimentos e experiência com HTML 5, Selenium Webdriver, Linux, Oracle, SoapUI, Shell Script, Java, JavaScript, Web Services e POstgresSQL/Cassandra;
- Inglês avançado (passará por entrevista técnica).

Desejáveis
- Boa comunicação

## Contratação

CLT

## Nossa empresa

Vou deixar o site para que vocês possam ter a visualização de tudo que temos por aqui: https://inatel.br/home/
Qualquer dúvida estarei a disposição.

## Como se candidatar

[Link para a vaga](https://epartner.vagas.com.br/PagVagaDirSS.asp?v=1686084&pp=https%3A//epartner.vagas.com.br/GoHome.asp%3Fv%3D1686084%26j%3Dt%26sslon%3D1&wiw=1536)

**Comment by jpventura** [comment]
Olá, @lucas-inatel! Tudo bem?

Esse board é para postagens de vagas relacionadas com desenvolvimento Android.

**Comment by lucas-inatel** [comment]
@jpventura desculpa, mas as vagas que eu anunciei o dev também vai trabalhar com Android, por que temos muitos projetos aqui e dependendo do perfil da pessoa ela pode ser remanejada para projetos Android, por isso que anunciei aqui, mas enfim, peço desculpas se cometi um erro. Abraço!
