### ISSUE TITLE
Especialista em Software - Testes e Desenvolvimento (Jr/ Pl)

### ISSUE THREAD

**Issue by lucas-inatel** [androiddevbr/vagas#508]
## Descrição da vaga

Especialista em Software - Testes e Desenvolvimento (Jr/ Pl)

## Local

Inatel - Santa Rita do Sapucaí - MG

## Benefícios

- Plano de saúde
- Seguro de vida
- Providencia privada
- Áreas de lazer e esporte

## Requisitos

Obrigatórios
  - Formação superior completa em cursos na área de tecnologia;
  - Conhecimentos em: Ferramentas de build (Jenkins, Git, RPM), Automação de testes (SOAPUI / PostMan / Groovy / JMeter), Linux (configuração, shell, comandos, scripts shell / AWK /NAWK / SED), REST / SOAP;
  - Experiência em trouble shooting;
  - Inglês avançado.

Desejáveis
- Boa comunicação

## Contratação

CLT

## Nossa empresa

Vou deixar o site para que vocês possam ter a visualização de tudo que temos por aqui: https://inatel.br/home/
Qualquer dúvida estarei a disposição.

## Como se candidatar

[Link para a vaga](https://epartner.vagas.com.br/PagVagaDirSS.asp?v=1723036&pp=https%3A//epartner.vagas.com.br/GoHome.asp%3Fv%3D1723036%26j%3Dt%26sslon%3D1&wiw=1536)

**Comment by jpventura** [comment]
Olá, @lucas-inatel! Tudo bem?

Esse _board_ é para postagens de vagas relacionadas com desenvolvimento Android.
