### ISSUE TITLE
Software Configuration Specialist

### ISSUE THREAD

**Issue by lucas-inatel** [androiddevbr/vagas#509]
## Descrição da vaga

    - Support the local development team with a version control environment customized for their needs;
    - Setup Build, packaging and release routines for the product development;
    - Perform scripting activities to automate the build, packaging and other continuous integration activities;
    - Provide CM training to developers;
    - Tracking build and regression failure issues to closure;
    - Provide support and solution to CM and build related issues for all projects;
    - Manage multiple release streams delivering the proper build to the proper environment in an automated fashion;
    - Implement and maintain automated and self-service build, deploy and code quality tools.

## Local

Inatel - Santa Rita do Sapucaí - MG

## Benefícios

- Plano de saúde
- Seguro de vida
- Providencia privada
- Áreas de lazer e esporte

## Requisitos

Obrigatórios
 - Bachelor's degree in Engineering, Computer Science or a related field;
 - Prior experience in handling SCM activities in a product development environment;
 - In-depth and hands-on knowledge of Configuration Management tools (GIT, SVN);
 - Strong knowledge and experience with of Continuous Integration and Deployment tools (e.g., Jenkins, Bamboo, etc.);
 - Sound scripting skills (Shell, Perl, Python);
 - Exposure to Build tools such as ANT, Maven and Gradle;
 - Experience of working in UNIX environment;
 - Excellent English language skills.

Desejáveis
- Good admin level Unix knowledge;
- Database administration (Oracle, MySQL);
- Basic knowledge of Java, XML and Software Development Life cycle.

Soft skills
 - Ability to troubleshoot failed builds and/or operational failures;
 - Ability to perform in a multi-tasking and team-oriented environment;
 - Ability to pick up new technologies in a rapidly changing environment, meticulous and detail oriented by nature, and keen eye towards identifying and eliminating risk;
 - Initiative to try tools and automation for improvement of productivity and quality.

## Contratação

CLT

## Nossa empresa

Vou deixar o site para que vocês possam ter a visualização de tudo que temos por aqui: https://inatel.br/home/
Qualquer dúvida estarei a disposição.

## Como se candidatar

[Link para a vaga](https://epartner.vagas.com.br/PagVagaDirSS.asp?v=1710378&pp=https%3A//epartner.vagas.com.br/GoHome.asp%3Fv%3D1710378%26j%3Dt%26sslon%3D1&wiw=1536)

**Comment by jpventura** [comment]
Olá, @lucas-inatel! Tudo bem?

Esse _board_ é para postagens de vagas relacionadas com desenvolvimento Android.
