### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor Android Pleno/Sênior - Dr. Cuco

### ISSUE THREAD

**Issue by duvarela** [androiddevbr/vagas#51]
Sendo transparente, queremos mais que um desenvolvedor, queremos alguém alinhado com nossos valores, com pensamento coletivo (saber se relacionar em equipe é fundamental) e que esteja em busca de um desafio maior de carreira. 

O envolvimento com o projeto é fundamental, pois o escolhido terá a possibilidade de tornar-se sócio da empresa através de um contrato de vesting :)  

Requisitos
Sólida experiência no desenvolvimento de Apps Mobile para a plataforma Android (Java); 
Experiência de trabalho com SCRUM e ambientes de desenvolvimento ágeis;
Arquitetura de soluções Mobile;
Familiaridade com Amazon Web Services AWS, Mobile APIs, JSON e Restful APIs.

Benefícios
Estar em uma das cidades com maior qualidade de vida do país (Floripa é demais, sério);
Espaço de trabalho incrível na ACATE;
Possibilidade de tornar-se sócio do CUCO;

[http://www.drcuco.com.br/trabalhe-conosco/]

**Comment by walmyrcarvalho** [comment]
@duvarela Boa tarde duvarela, peço que atualize o template sugerido por esse link: https://github.com/androiddevbr/vagas/issues/new

O título também foi editado pra ficar padronizado com o restante das vagas.
