### ISSUE TITLE
CURITIBA - PR **OPORTUNIDADE PARA DESENVOLVEDOR(A) ANDROID**

### ISSUE THREAD

**Issue by MisaelEugenio** [androiddevbr/vagas#511]
1 - Pleno (PL) e 1 - Junior (JR)
PL
Atividades:
- Atuar no desenvolvimento de smartphones com plataforma Android (implementação de requisitos, correção de bugs e testes unitários);
- Trabalhar em conjunto com parceiros no exterior;
- Desenvolver ferramentas e scripts para automação e melhoria de processos;
- Analisar problemas nas mais diversas áreas relacionadas a software para smartphones.

Necessário:
- Superior completo em Graduação em Ciência da Computação, Engenharia da Computação, Análise de Sistema ou cursos similares;
- Inglês avançado/fluente, principalmente leitura e escrita;
- Comunicação, Foco em Resultados, Flexibilidade e Trabalho em Equipe;
- Experiência com desenvolvimento de aplicativos Android, bons conhecimentos de linguagem Java ou C++, ter atuado com ambientes Linux e ferramentas de versionamento de código, desejável conhecimento em linguagens de script e aplicações back-end. 
*Anexar o link dos projetos pessoais que tenha realizado como aplicativo, site, etc.

- Salário de R$ 3.500,00 a R$ 4.000,00;
- VT, Alimentação no Local, Plano de Saúde, Seguro de Vida;
- CLT.

Empresa contratante alocada na região de Curitiba.

INTERESSADOS ENCAMINHAR CV COM DESCRIÇÃO "VAGA ANDROID PL"  PARA O E-MAIL: tiago@talentosit.com.br
----------------------------------------------------------------------
JR 
Atividades:
 - Atuar na equipe de QA, sendo responsável pela execução de testes funcionais (automatizados e manuais) e analise de defeitos de software em smartphones Android.

Necessário:
- Superior completo nas áreas de exatas/TI;
- Inglês Intermediário;
- Desejável conhecimentos/experiência anterior com plataforma Android e execução de testes funcionais e análise de requisitos, conhecimento em acompanhamento de logs, montagem de cenário de testes e workflow de defeitos (bugs);
- Comunicação, Foco em Resultados, Flexibilidade e Trabalho em Equipe.

- Salário de R$ 2.000,00 a R$ 2.500,00;
- CLT.

Empresa contratante alocada na região de Curitiba.

INTERESSADOS ENCAMINHAR CV COM DESCRIÇÃO "VAGA ANDROID JR"  PARA O E-MAIL: tiago@talentosit.com.br

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência,

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by jpventura** [comment]
@MisaelEugenio de acordo com as [regras da comunidade](https://github.com/androiddevbr/vagas/blob/master/README.md), o nome da empresa precisa estar na descrição da vaga.

**Comment by MisaelEugenio** [comment]
Infelizmente não posso colocar o nome da empresa, cliente solicitou confidencialidade.


________________________________
De: JP Ventura <notifications@github.com>
Enviado: quarta-feira, 5 de setembro de 2018 20:49
Para: androiddevbr/vagas
Cc: MisaelEugenio; Mention
Assunto: Re: [androiddevbr/vagas] CURITIBA - PR **OPORTUNIDADE PARA DESENVOLVEDOR(A) ANDROID** (#511)


@MisaelEugenio<https://github.com/MisaelEugenio> de acordo com as regras da comunidade<https://github.com/androiddevbr/vagas/blob/master/README.md>, o nome da empresa precisa estar na descrição da vaga.
