### ISSUE TITLE
Analista Desenvolvedor (a) Java Pleno - São Paulo

### ISSUE THREAD

**Issue by Daniboto** [androiddevbr/vagas#513]
A FlexVision é uma empresa que desenvolve soluções tecnológicas totalmente customizáveis de 
monitoração inteligente de infraestrutura, aplicações e negócios. 
Presente há mais de 15 anos no mercado, atuando com clientes de alto impacto. 
No momento estamos em busca de profissionais com seguinte perfil:

Ensino Superior em TI (Análise e Desenvolvimento de Sistemas, Engenharia da computação e afins).
Diferencial pós-graduação na área de TI.

Ter conhecimento técnicos relacionados em algumas das seguintes exigências: Java EE, Primefaces, 
Struts, Spring, Hibernate, SQL Server, MySQL, XML, Webservices, Linux, Script SHELL, Jboss, 
Tomcat, Glassfish, PHP, JScript, jQuery, Json, CSS e HTML.

Salário Negociáve l+ Benefícios Compatíveis ao Mercado + Estrutura para carreira
Local de trabalho: Berrini Z/S
E-mail: daniele.boto@flexvision.com.br
Whatsapp: 9 9941-8179

**Comment by marciofermino** [comment]
**Analista de Sistemas com experiência,

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.**

**Comment by davidtcdeveloper** [comment]
@Daniboto este mural é destinado exclusivamente a vagas para desenvolvedores Android. Como não encontrei nenhuma menção, estou encerrando a issue.
