### ISSUE TITLE
[Belo Horizonte, MG] Desenvolvedor Android Sênior | Concrete 

### ISSUE THREAD

**Issue by nascimentodiego** [androiddevbr/vagas#516]
## Descrição da vaga

Somos a Concrete, uma empresa da Accenture especializada em produtos digitais, e estamos em constante movimento. Trabalhamos junto às maiores companhias do Brasil para garantir a transformação digital. Para isso, usamos design, desenvolvimento ágil e nossa cultura de inovação. Trabalhamos com tendências, mas não seguimos passos: criamos os nossos caminhos, que viram referência.

Procuramos desenvolvedores Android para fazerem parte de um time que orquestra os robozinhos verdes para ser um dos canais de maior impacto para nosso clientes. O desenvolvimento Android (que pode ser apps, Android Things, Auto, TV, Chrome OS, etc) é crucial para dar cara a um produto digital. Nosso time vive de discussões sobre essa plataforma desde o design (Material?) até a arquitetura (MVP, MVC, MVVM, MVI, Clean, Architeture Components, etc), testes (locais e instrumentados) e instrumentação (hit analytics, performance, conversão e etc.)

Aqui, você fará parte de um time com mais de 50 devs Android, que possuem sua própria comunidade. Temos vários colegas que são referência, somos o time com maior participação em eventos do Brasil, temos reuniões bi-semanais para discussão e troca de ideias e promovemos treinamentos dos mais diversos temas. Ainda criamos e mantemos projetos Open Source na plataforma e fazemos parte do programa do Google de Agências (GDA, Google Developers Agency).

## Local

Presencial, Belo Horizonte - MG

## Benefícios

- Plano de Participação Resultados
- Previdência Privada
- Plano de Saúde
- Plano odontologico
- Seguro de Vida sem desconto
- VR
- VT
- GymPass

## Requisitos

Buscamos pessoas que:

- Tenham qualquer tempo de experiência, idade, gênero ou qualquer outro ponto que não seja o conhecimento na plataforma e a senioridade de desenvolvimento e de comunicação;
- Entendam sobre a composição de aplicativos Android em estrutura, APIs e performance;
- Entendam o ciclo de vida de aplicações e componentes do Android (Application, Activity, Service, ContentProvider, etc);
- Saibam quais os desafios de desenvolvimento a plataforma nos propõe (manter estado, concorrência, guia de estilos e etc);
- Tenham bom entendimento sobre arquitetura de sistemas (seja GUIs reativas, SOLID, KISS, etc);
- Conheçam formas de instrumentação de aplicativos (Hit Analytics, performance, conversão de uso);
- Entendam formas de ciclo de vida de um aplicativo: como o código evolui da máquina do desenvolvedor até produção;
- Sigam boas práticas de desenvolvimento das linguagens em uso (Java e Kotlin);
- Conheçam sistemas de versionamento de código, preferencialmente GIT;
- Conheçam o build system padrão da plataforma (atualmente o Gradle);
- Entendam sobre práticas de teste: importância, propósito e prática;
- Saibam trabalhar em time;
- Tenham vontade de se envolver com o que faz (tornar-se parte do problema e da solução).

## Contratação

CLT

## Como se candidatar

Por favor envie um email para juliana.freitas@concrete.com.br com seu CV anexado - enviar no assunto: DESENVOLVEDOR ANDROID SÊNIOR BH - FROM AndroidDevBr

**Comment by jpventura** [comment]
Olá, @nascimentodiego! Qual o nível de senioridade da vaga?

**Comment by nascimentodiego** [comment]
Olá @jpventura ... è pra Sênior.
