### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android | Radar Profissional 

### ISSUE THREAD

**Issue by RADARProfissional** [androiddevbr/vagas#519]
VAGAS: ANDROID Pleno e Sênior 

Requisitos:  
•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Experiência com Android, Java, Json/XML, SQLite, Realm, Firebase, Google Analytics, Arquiteturas MVC, MVP e/ou Clean Architecture, SVN e Análise de requisitos;
•	Será considerado como diferencial, profissionais com experiência em Android Annotation, Butter Knife, Jira, Xamarin, React Native, Programação Reativa e Testes unitários e automatizados (TDD).

Contratação: PJ
Local: Alphaville / SP 
Interessados: Enviar CV para vagas@radarprofissional.com.br

**Comment by jpventura** [comment]
@RADARProfissional de acordo com as [regras da comunidade](https://github.com/androiddevbr/vagas/blob/master/README.md), o nome da empresa precisa estar na descrição da vaga.
