### ISSUE TITLE
[Remoto ou São Paulo] Dev Android @ Carreira Beauty

### ISSUE THREAD

**Issue by vixandrade** [androiddevbr/vagas#521]
O Carreira Beauty procura profissional para atuar como **principal dev do nosso aplicativo nativo**! Nós moramos no **CUBO** (hub de startups na **Vila Olímpia em São Paulo**), mas se não quiser vir até aqui, pode preencher essa vaga como dev **remoto(a)** também!

Nós somos os criadores e mantenedores do **Ahazou**, a solução de marketing digital de conteúdo para pequenos negócios no setor de beleza. Já estamos presentes em mais de 1.000 cidades no Brasil inteiro (e algumas fora também), ajudando mais de 16.000 usuários todo mês.

Ahazou na Play Store (temos orgulho desse 4.6, mas a meta é melhorar isso aí!): https://play.google.com/store/apps/details?id=ahzproapp.carreirabeauty.com.ahz_pro

Como residentes do **CUBO**, o **maior centro de empreendedorismo tecnológico da América Latina** e todos na nossa equipe tem a oportunidade de participar da comunidade formada diariamente no espaço e de estar em contato com **pessoas geniais** de todos os setores e que também são residentes.

Nossa cultura como startup é baseada 100% em **oferecer valor ao cliente de maneira ágil e consistente**. Então se você se anima com a ideia de impactar positivamente **todos os dias** a vida de 5 milhões de brasileiros, seu lugar é aqui com a gente.

**Mais informações:**
- Somos um **time enxuto**, pois acreditamos que o valor que cada membro da equipe entrega faz o nosso produto crescer exponencialmente;
- Temos foco forte em **métricas e melhoria contínua**, cada passo que damos tem a intenção de melhorar a vida dos nossos usuários;
- Somos uma equipe com membros **autônomos e responsáveis**. Confiamos que cada um que trabalha conosco está agindo com o **mesmo objetivo em mente**, então não precisamos nos preocupar em supervisionar ou aprovar o que cada um faz.

**Procuramos alguém que:**
- Tenha experiência técnica com desenvolvimento **Android nativo** e com as ferramentas e patterns que compõem a tecnologia. Usamos **Kotlin** e gostamos do modelo MVP, mas como principal dev da empresa você poderá **guiar as decisões** com relação a modelos e ferramentas.
- Goste de **processos de agilidade e qualidade**, mas que saiba conciliar isso com a **rotina de startup** onde fazemos **protótipos e MVPs** com grande frequência.
- Saiba implementar as **melhores práticas** de **desenvolvimento, testes e monitoramento** de aplicações móveis (issues, performance, usabilidade, etc).

**Tipo de contratação**
PJ

**Como se aplicar?**
Mande um email para victor@carreirabeauty.com com o assunto "**Dev Android**" junto com seu perfil do LinkedIn e do GitHub (se usar).

**Comment by vixandrade** [comment]
@jpventura pode marcar como remoto também?

**Comment by jpventura** [comment]
@vixandrade qual o nível de senioridade que estão procurando?

**Comment by vixandrade** [comment]
@jpventura não estamos procurando uma senioridade específica.
