### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Mobile para início imediato  | Pontotel

### ISSUE THREAD

**Issue by defaultbr** [androiddevbr/vagas#528]
# A empresa

A PontoTel é uma empresa de automação de registros trabalhistas para funcionários. Nós somos um SaaS de RH adaptado para as necessidades dos consumidores residenciais.
Você trabalhará diretamente com os sócios e nós vamos fazer o possível para que esse seja o trabalho mais bacana (isso mesmo) que você venha a ter.

# Descrição da vaga

O profissional será responsável por um aplicativo mobile existente e já em produção. Deverá efetuar manutenções caso necessário, acompanhamento de métricas e desenvolvimento de novas features.

# Requisitos
- Kotlin/Java para Android
- Testes unitários
- Git
- REST
- Banco de Dados

# Contratação

Estágio e CLT 

# Benefícios
- Plano de carreira
- VT e VR
- Horário flexível
- Aprender diferentes stacks, tecnologias atuais
- Clima descontraído, democrático e, acima de tudo, divertido
- Café/chá “dos bons”!
- HH na sexta com CS
- Comidas e bebidas no escritório
- Almoço de sexta! Por conta da firma

# Local
Centro de São Paulo (Próximo ao metro Anhangabaú)

# Como se candidatar

envie um e-mail para `work@pontotel.com.br` com o assunto `Vaga desenvolvimento Mobile` com seu CV anexo e links complementares (github, linkedin, etc...)

# Imagem de divulgação:

![image](https://user-images.githubusercontent.com/5432351/44176279-91cb0800-a0bf-11e8-9082-164c853b6444.png)

**Comment by X-X-Xavito** [comment]
A vaga de estágio ainda está em aberto?

Abs
