### ISSUE TITLE
Android Developer

### ISSUE THREAD

**Issue by patyandreolli** [androiddevbr/vagas#530]
Android Developer

Skill Set:
•	Experience with Android development (minimum version 4.1), Reactive Programming (using RX), Unit Test and Dependency Injection (using Dagger);
•	Knowledge of design patterns;
•	Create dynamic layouts.
 
CLT + Attractive salaries ( Bonus Program, Career path Plan
HR Buddy/Mentorship program, International Company, Health and Dental Plan (100% paid by the company), Education Benefits, Sport Benefits, Sponsored English classes, Sponsored Certifications
Location: Vila Olímpia - São Paulo, Brazil
=> recrutamento@infovagas.com

**Comment by jpventura** [comment]
@patyandreolli de acordo com as [regras da comunidade](https://github.com/androiddevbr/vagas/blob/master/README.md), o nome da empresa precisa estar na descrição da vaga.
