### ISSUE TITLE
VAGA DESENVOLVEDOR ANDROID - BERLIM

### ISSUE THREAD

**Issue by RBJUR** [androiddevbr/vagas#532]
## Descrição da vaga
O Core do aplicativo é para Smart Home, estamos desenvolvendo do zero, com muitas features legais.

## Local

Berlim - Alemanha

## Benefícios

- Oportunidade de trazer suas próprias ideias ativamente
- 1 dia da semana de home office 
- Formação adicional individual
- Orientação na recolocação

## Requisitos

Obrigatórios
- 4+ anos de experiência com Android
- Ingles Fluente

Desejáveis
- Kotlin
- RxAndroid
- Dagger 2
- MVP
- MVVM
- MQTT
- Diploma relacionado a TI (Ajuda muito a chance do visto ser aprovado)

## Contratação

- Contrato prazo indeterminado

## Nosa Empresa

Casenio AG

## Como se candidatar

Por favor envie um email para r.buarque@casenio.de com seu CV em inglês anexado - enviar no assunto: Vaga Android

**Comment by henrywm** [comment]
Boa tarde, vi que a vaga é na Alemanha e precisa do Inglês, mas está escrita em Português... então envio meu CV em PT-BR ou EN?

**Comment by jpventura** [comment]
Olá, @RBJUR? Qual o nível de senioridade desejado? Prefere que a vaga seja marcada como presencial ou remoto parcial?

**Comment by jpventura** [comment]
@RBJUR vocês oferecem auxílio para emissão de visto ou o candidato precisa ter cidadania?

**Comment by RBJUR** [comment]
@jpventura  vaga para 4 anos ou mais de experiencia, presencial! Tera um profissional para orientar todo o processo de visto, porém não é Visa sponsorship!
