### ISSUE TITLE
Vaga_Embedded Android Engineer_Manaus-AM

### ISSUE THREAD

**Issue by Sueli321** [androiddevbr/vagas#537]
DESCRIPTION
Embedded Android Engineer have the opportunity to work on low level development such as developing device drivers and native libraries, responsibilites include standard specification analysis, coding, peer review, unit test, integration test and bug fixing.

REQUERIMENTS
•3+ years Embedded Android development experience
•Knowledge in Android AOSP
•Knowledge of C/C++ and JNI development.
•Knowledge in GIT
•Knowledge on camera, audio, Bluetooth technologies/specs is a plus

NICE TO HAVE
•Good written and basic oral English
•Knowledge on multimedia specs

Contratação: CLT efetivo + Benefícios
Jornada: Segunda à Sexta
Local de Atuação: Manaus-AM

Interessados enviar CV com título da vaga para:
sueli.patricio@triadsystems.com.br

**Comment by jpventura** [comment]
@Sueli321 de acordo com as [regras da comunidade](https://github.com/androiddevbr/vagas/blob/master/README.md), o nome da empresa precisa estar na descrição da vaga.
