### ISSUE TITLE
[Manaus / AM] - Vaga Engenheiro de Aplicação Android

### ISSUE THREAD

**Issue by rose12fabi** [androiddevbr/vagas#538]
Engenheiro de Aplicação Android
Oportunidade de trabalhar em melhorias de experiência do usuário, design em novos serviços de internet móvel, responsabilidades incluem análise de requisitos, design, codificação, revisão por pares, teste de unidade, teste de integração e correção de bugs.
3 + anos de experiência em desenvolvimento Android APP 
Conhecimento no framework de aplicativos Android 
Conhecimento em GIT 
Diferencial: Conhecimento do desenvolvimento de C / C ++ e JNI é uma vantagem
Local de Trabalho: Manaus – AM
Contratação CLT Full + Benefícios

Encaminhar currículo atualizado para roseli.reis@triadsystems.com.br com a sigla ANDROID - AM

**Comment by jpventura** [comment]
@rose12fabi de acordo com as [regras da comunidade](https://github.com/androiddevbr/vagas/blob/master/README.md), o nome da empresa precisa estar na descrição da vaga.
