### ISSUE TITLE
[Rio de Janeiro, RJ] Desenvolvedor Android Jr. - Globo Play

### ISSUE THREAD

**Issue by ridjohansen** [androiddevbr/vagas#54]
## Descrição da vaga

Desenvolvedor Android Junior

## Local

Jardim Botânico - Rio de Janeiro/RJ

## Benefícios

- Horário Flexivel
- VR e Plano de Saúde
- entre outros  #beneficios

## Requisitos

Ter experiência no desenvolvimento nativo para Android, de preferência em apps que envolvam uma UX avançada. Já ter desenvolvido games ou apps de vídeos são diferenciais, se já tiver experiência com Android TV melhor ainda.

Diferenciais
- Ser usuário de Android e fanático pelos produtos do Google.

## Contratação

CLT (Salário à combinar)

## Nossa empresa

GloboPlay

## Como se candidatar

Por favor envie um email para richard.johansen@tvglobo.com.br com seu CV anexado - enviar no assunto: Vaga Android Globo Play

**Comment by walmyrcarvalho** [comment]
Título editado pra ficar de acordo com o template sugerido. :)
