### ISSUE TITLE
Desenvolvedor Android (Campinas-sp)

### ISSUE THREAD

**Issue by talentreplacement1** [androiddevbr/vagas#546]
## Descrição da vaga

 Empresa Appito. Projeto de desenvolvimento de um app de futebol

## Local

Campinas-sp

## Benefícios
Vale refeição
vale transporte
plano médico
férias

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Aplicativo publicado na apple store
-Experiência em android SDK

Desejáveis
- 

Diferenciais
- 

## Contratação

cooperado

## Nossa empresa
Um time que joga pra frente, sem sentir o peso da camisa
Nós vamos revolucionar o esporte amador no mundo. Para isso, contamos com um elenco apaixonado por fazer parte dessa revolução e que é movido por cada partida e amizade gerada através do aplicativo.

## Como se candidatar

Por favor envie um email para recrutamento@talentreplacement.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@talentreplacement1 de acordo com as [regras da comunidade](https://github.com/androiddevbr/vagas/blob/master/README.md), o nome da empresa precisa estar na descrição da vaga.
