### ISSUE TITLE
[São Paulo] Desenvolvedor Android Senior - Kiddo Labs

### ISSUE THREAD

**Issue by CavalcanteLeo** [androiddevbr/vagas#55]
## Descrição da vaga

Temos uma vaga aberta para entrar no time de desenvolvimento Android no qual irá contiunuar projetos existentes assim como novos projetos.
## Local

Jardins, São Paulo.
## Requisitos

**Obrigatórios**
- 3+ anos experiencia com java
- 3+ anos experiencia com android
- Conhecimentos em testes (Espresso, Roboletric, JUnit)
- Material Design
- Continuous Integration (diferencial: Jenkins)
- Conhecimentos em algum ORM (DBFlow, Realm, etc)
- Bom raciocínio lógico
- Fortes conhecimentos com Git
- Boa proficiência em inglês

**Desejáveis**
- Continuos Integration
- Apps próprios publicados na Google play
- Kotlin
- Experiência com automatização de testes unidade, integração e funcional
- Experiência com TDD / BDD;

**Diferenciais**
- projetos opensource
## Contratação

A combinar
## Nossa empresa

Somos uma empresa de design de produtos digitais. Atendemos grandes empresas desenvolvendo produtos inovadores que agregam valor real à cadeia de negócio. Precisamos de desenvolvedores iOS senior e pleno para trabalhar em diversos projetos **nacionais** e **internacionais**.

[www.kiddolabs.com](www.kiddolabs.com)
## Como se candidatar

Por favor envie um email para **vagas@kiddolabs.com** com seu linkedin - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@CavalcanteLeo Essa vaga ainda está aberta?

**Comment by walmyrcarvalho** [comment]
@CavalcanteLeo Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!
