### ISSUE TITLE
[Rio de Janeiro - RJ] - Desenvolvedor(a) Android | Webedia

### ISSUE THREAD

**Issue by jonasporto** [androiddevbr/vagas#557]
## Descrição da vaga

Estamos em busca de devs Android, apaixonados em criar apps incriveis que engajam pessoas, para se juntar ao nosso time de tecnologia da Webedia (TudoGostoso).

## Local

Botafogo, RJ

## Benefícios

-  VR de R$ 25/dia
-  Vale Transporte
-  Plano de saúde e odontológico

## Requisitos

Obrigatórios
- Conhecimentos específicos em Android SDK API's, Ciclo de vida de Activities e Fragments;
- Trabalhar com diferentes dimensões de dispositivos (Tablet, celular e afins);
- Conhecimento com bibliotecas e ferramentas comuns ao desenvolvimento Android (Gradle, Android Studio, API Facebook, Material Design, etc);
- Conhecimentos com Google Play Services(Ads, Analytics, GCM, Auth);
- Familiaridade com o processo de distribuição do Google Play;
- Inglês intermediário (leitura e escrita);

Desejáveis
- Experiência com Git;
- Conhecimento de Orientação a Objetos, Design Patterns (MVP, MVVM);

Diferenciais
- Aplicativos já publicados na App Store;
- Conhecimento em outras linguagens de programação (ex: Kotlin, Ruby, Python, Javascript);
- Alguma experiência com desenvolvimento web (Rest API's);

## Contratação

- CLT, Salário de acordo com a pretensão salarial.

## Nossa empresa

A Webedia é um grupo de mídia digital de origem francesa presente em mais de dez países, com verticais que totalizam 177 milhões de usuários únicos por mês, dos quais 47,3 milhões estão no Brasil, a maior audiência do grupo. O sucesso se deve ao controle de sites líderes em segmentos estratégicos: TudoGostoso (comida), AdoroCinema (entretenimento), IGN (jogos), Versus (e-sports), PurePeople e Purebreak (glamour/celebridades), Minha Vida (saúde e bem-estar), Hypeness (inovação e criatividade), entre outros. Por meio da divisão de Brand Publishing, a Webedia oferece ainda expertise em audiência para clientes como Niely, Johnson & Johnson, Oral-B, Gillette, L'Oréal, Maybelline, La Roche Posay, Leroy Merlin, entre outros.

Quer saber um pouco mais da nossa empresa ao redor do Mundo? Se liga nesses vídeos: 
[Webedia no Mundo](https://youtu.be/hsVSaUlVYXU
)
[Webedia Brasil RJ-SP](https://vimeo.com/257192408
)
## Como se candidatar

Topa o desafio? Envie um email para jonas.porto@webedia-group.com com o assunto "Dev Android", com seu curriculo anexo e um breve resumo da sua historia/experiência, sinta-se livre pra mandar algo que você se orgulhe de ter feito, GitHub, LinkedIn, portfólio ou qualquer outra coisa que ache interessante compartilhar com a gente

**Comment by Victorlopesjg** [comment]
Também é remoto?
