### ISSUE TITLE
[São Paulo / SP] Desenvolvedor Android Sr - Truckpad

### ISSUE THREAD

**Issue by ubiratansoares** [androiddevbr/vagas#56]
## Descrição da vaga

Estamos em busca por um Desenvolvedor Android Sênior, para atuar em nosso time.
## Local
- Presencial, em São Paulo (acho que é na região de Pinheiros)
## Benefícios
- Remuneração compatível com o mercado + os seguintes benefícios:
- Assistência médica;
- Assistência odontológica;
- Seguro de Vida em Grupo;
- Vale refeição;
- Vale transporte;
- Curso de inglês In Company ou reembolso no caso de curso em outra escola ou para outras línguas;
- PLR, conforme política da empresa;
- Auxílio creche;
- Futebol, café da manhã e massagem;
- Temos bicicletário e vestiário no prédio para quem vem de bicicleta.
## Requisitos

Obrigatórios
- Profissional com experiência no desenvolvimento de aplicações para dispositivos Android;
- Conhecimentos em análise e desenvolvimento de sistemas para plataforma mobile;
- Definição de arquitetura e análise orientada a objetos;
- Domínio na utilização da linguagem de programação Java, arquitetura MVC e serviços;
- Experiência com desenvolvimento de aplicativos com foco na usabilidade;
- Vivência na otimização de performance de aplicativo;
- Conhecimentos em: Design Patterns, XML, testes unitários e funcionais usando JUnit, SQLite,
- Webservices e, REST, ORMLite, Gradle e SVN / Git.
## Contratação

A combinar (acredito que é CLT)
## Nossa empresa

TruckPad, o maior aplicativo para caminhoneiros do país, premiado no Vale do Silício, conecta de forma simples e rápida caminhoneiros à carga, proporcionando economia de tempo e rentabilidade.

Ao lado das empresas MapLink e Apontador, formam o grupo LBS o qual se uniu à Movile, do grupo Naspers, em 2014.
## Como se candidatar

Acesse o [link](https://grupolbs.recruiterbox.com/jobs/fk06ifi/)

**Comment by MarkyVasconcelos** [comment]
Link para candidatos não funciona.

**Comment by ubiratansoares** [comment]
Acredito que essa vaga já não está mais aberta.
