### ISSUE TITLE
[Porto Alegre, RS] Desenvolvedor Android - Beyond Domotics

### ISSUE THREAD

**Issue by s-venero** [androiddevbr/vagas#57]
Descrição da vaga

Estamos em busca de um profissional para fazer a versão Android de nosso app iOS
## Local

Presencial, em Porto Alegre (TECNOPUC)
## Requisitos

Obrigatórios
- 2+ anos experiencia com java
- 2+ anos experiencia com android
- Bom raciocínio lógico
- Fortes conhecimentos com Git
- Boa proficiência em inglês

Desejáveis
- Apps próprios publicados na Google play
- Ter trabalhado com MQTT
- Saber ler swift, para acessar o fonte do app publicado
## Contratação

A combinar
## Nossa empresa

A [Beyond Domotics](www.beyond.dm) desenvolve produtos para smart homes. O Controle de iluminação e de equipamentos ficou elegante, divertido e fácil de ser instalado em qualquer residência.
## Como se candidatar

Por favor envie um email para sergio.venero@beyond.dm com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@s-venero Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!
