### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor Android [SENIOR] | BJ Hunting Consulting

### ISSUE THREAD

**Issue by sahjarussi** [androiddevbr/vagas#571]
## Descrição da vaga
-Develop Voice apps and  games for Apple TV using the latest frameworks for Siri Remote, Spritekit, AVAudio  
-Develop apps with big audiences in the USA market
-Develop apps using the most recent libraries and frameworks like Realm, Parse, SSO
-Write software that is maintainable, performant and well-designed.

## Local
Presencial - Florianópolis, SC

## Requisitos
Inglês avançado

## Contratação
CLT

## Nossa empresa
BJ Hunting Consulting | From an entry level to C-level, BJ Hunting Consulting can provide a bespoke recruitment service to your business.
Estamos apoiando uma multinacional americana de Tecnologia a expandir o seu time Mobile em Florianópolis.

## Como se candidatar
Interessados deverão enviar o CV para samanta.jarussi@bjhuntingconsulting.com

**Comment by davidtcdeveloper** [comment]
Oi @sahjarussi, nossa comunidade preza pela transparência, por isso as vagas pedem que o nome da empresa seja divulgado.
Peço que edite a issue com o nome da empresa para que ela continue aberta.
