### ISSUE TITLE
[Joinville, SC] Desenvolvedor Android - Meus Pedidos

### ISSUE THREAD

**Issue by ronanrodrigo** [androiddevbr/vagas#58]
## Descrição da vaga

Atuar no desenvolvimento do nosso aplicativo de força de vendas. Como desenvolvedor você será responsável por implementar novas funcionalidades, corrigir bugs, manter o código limpo e testado. Será instigado a propor e realizar melhorias de arquitetura e design dos nossos aplicativos. Além de Android você poderá desenvolver também para iOS, pois nossa plataforma de desenvolvimento mobile é híbrida, utilizamos Xamarin.
## Local

Presencial em nosso escritório em Joinville, Santa Catarina
## Benefícios
- Ambiente descontraído, informal, ágil e focado em aprendizado e resultados;
- Flexibilidade de horário (banco de horas);
- Plano de saúde e odontológico Bradesco.
- Vale transporte ou combustível;
- Vale alimentação ou refeição;
- Frutas e guloseimas liberadas;
- Parcerias e convênios com academias, restaurantes, cursos…
## Requisitos
- Experiência de pelo menos 2 anos com desenvolvimento Android.
- Curiosidade e vontade de aprender novas ferramentas, plataformas e tecnologias.
- Boas habilidades de comunicação, indispensáveis para o trabalho em equipe.
- Residir em Joinville - SC, ou disponibilidade para se mudar para a cidade.
## Diferenciais
- Portfólio de apps publicados no Google Play.
- Experiência prévia com Xamarin.
- Experiência com desenvolvimento iOS.
- Experiência com desenvolvimento de APIs REST.
- Experiência com linguagem C# e frameworks .NET.
- Domínio sobre testes unitários e testes automatizados de UI.
- Conhecimento em design e arquitetura de software.
- Perfil ativo no GitHub e no StackOverflow.
## Contratação

CLT
## Como se candidatar

Através do nosso recruiterbox: https://meuspedidos.recruiterbox.com/jobs/fk06rpu/

**Comment by walmyrcarvalho** [comment]
@ronanrodrigo Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!
