### ISSUE TITLE
[SP - Vila Olímpia] Android Developer - Yellow

### ISSUE THREAD

**Issue by AnaYellow** [androiddevbr/vagas#581]
**Android Developer**

**About your job:**

Our apps are the heart of Yellow. They are responsible for starting a trip, tracking our bicycles, managing the ongoing and finished trips, executing payment transactions, and son on.
You'll be working with a great team, including founders of 99, the first brazilian unicorn, and the former CEO of Caloi.

**Here you are going to be responsible for:**

- Develop and maintain our Android app
- Understand and foresee our requirements
- Work closely with backend developers to design service interfaces and improvements
- Guarantee high performance and high availability of the app

**Double click in your routine:**

- Develop new features and fix bugs in our Android app _(almost 100% Kotlin based)_
- Work side-by-side with product team to design requirements
- Keep our source organized in our git repository
- Collaborate in building and enforcing the roadmap
- Manage and prioritize your tasks efficiently
- Collaborate with architecture and code design decisions

**Our "must haves" for this position includes:**

- +4 years experience in Android development
- Advanced Object Oriented skills
- Dominance of RESTful concepts
- Hands on experience with development best practices (testing, code-review, etc)
- Strong sense of commitment and delivery focus

**Our "nice to have" for this position:**

- Bachelors in Computer Science, Computer Engineering or equivalent in top Universities
- Have already worked in startups
- Have already worked as backend developer
- Deep knowledge in Google Maps integration

**Perks:**

- Competitive Compensation
- Startup environment
- Flexible working hours
- Work in a well funded startup
- Free beers on fridays

São Paulo - Vila Olímpia

 Apply to Position: https://yellow.breezy.hr/p/ae50f03fd800-android-developer

**Comment by AnaYellow** [comment]
@jpventura Hi :) Senior Position!!

**Comment by jpventura** [comment]
@AnaYellow did you really close the issue? is it CLT or PJ?

**Comment by AnaYellow** [comment]
> @AnaYellow did you really close the issue? is it CLT or PJ?

@jpventura CLT!!
