### ISSUE TITLE
[SÃO PAULO-SP] Desenvolvedor JAVA para Android e C | Keycar

### ISSUE THREAD

**Issue by dhaytaboada** [androiddevbr/vagas#585]
## Descrição da vaga

Desenvolvimento de firmware de dispositivo embarcado com interface microcontrolada utilizando linguagens Java para Android e C

## Local

Paulista - São Paulo/SP

## Benefícios

- Horário flexível
- Ambiente descontraído

## Requisitos

- Linguagem Java SE (avançado);
- Particularidades da linguagem Java para Android (intermediário);
- Boas noções de gerenciamento de memória e tráfego de dados.
- Boa noção de lógica binária; 
- Linguagem C para microcontroladores PIC da Microchip (XC8) (básico/intermediário);
- Linguagem C para microcontroladores Atmel/Arduino(desejável);
- Conhecimentos básicos de eletrônica;
- Conhecimento de módulos GSM, GNSS, BLE e WIFI. 

## Contratação

PJ a combinar

## Nossa empresa

Uma Startup antenada as necessidades e tendências do mundo, criando soluções disruptivas focadas principalmente ao mercado automotivo

## Como se candidatar

Por favor envie um email para rh@keycar.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@dhaytaboada o nome da empresa é obrigatório na divulgação da vaga. A empresa é a Keycar, é isso?

**Comment by dhaytaboada** [comment]
Isso mesmo.

**Comment by jpventura** [comment]
@dhaytaboada qual o nível de senioridade desejado? vaga presencial ou remota?

**Comment by dhaytaboada** [comment]
Seria Pleno/Senior. Vaga presencial na Av. Paulista
