### ISSUE TITLE
[SP, Butantã] Coordenador de Desenvolvimento - Games (Android e iOS) [SR] | Tapps Games

### ISSUE THREAD

**Issue by henriqueblacklion** [androiddevbr/vagas#588]
## Recrutador
Intermediado pela Black Lion Consulting

## Descrição da vaga
Estamos buscando um coordenador de desenvolvimento para atuar em uma empresa focada em games para plataformas mobile (Android e iOS). Esse profissional será responsável por liderar devs de alto nível técnico, garantir entregas de qualidade e games com alta disponibilidade no mercado. Definir tecnologias, participar na estratégia e desenvolvimento do produto e se relacionar com a equipe e outras áreas.

## Local
São Paulo - Butantã, local

## Benefícios

- VR
- Plano de saúde, odonto, seguro de vida
- ambiente descontraído e colaborativo
- sala de jogos
- etc...

## Requisitos

Obrigatórios
- Experiência com desenvolvimento de softwares de alta qualidade
- Liderança de equipe
- Domínio de linguagens como C, C++, C# ou Java
- Conhecimento em Python ou Lua
- Design Orientado a Objetos
- Git, SVN
- Inglês Avançado
- Amar jogos

Desejáveis
- Metodologia ágil
- Unity 3D

Diferenciais
- Empresa referência no desenvolvimento de games, equipe de altíssimo nível, ambiente descontraído e colaborativo

## Contratação

CLT (8,8k - 12k)

## Nossa empresa

A Black Lion é uma consultoria de Head Hunting que ajuda empresas a encontrar os melhores talentos na área de Negócios e Tecnologia

## Como se candidatar

Os interessados e que atendam aos requisitos podem enviar um cv com o titulo "PROCESSO GAMES" para henrique.daniel@blacklionconsulting.com.br ou fazer contato pelo Linkedin com @Henrique Daniel (Black Lion Consulting)

**Comment by jpventura** [comment]
@henriqueblacklion, se você é um _head hunter_ trabalhando para [Black Lion Consulting](http://www.blacklionconsulting.com.br/), você deve apresentar o nome da empresa para qual o candidato irá trabalhar (veja os [termos da comunidade](https://github.com/androiddevbr/vagas/blob/master/README.md)).
