### ISSUE TITLE
(BELO HORIZONTE) DESENVOLVEDOR JAVA PARA ANDROID

### ISSUE THREAD

**Issue by MarizaAlves** [androiddevbr/vagas#589]
Pontual Consultores Associados, contrata:

Período de alocação: 06 meses (possibilidades de prorrogação)
Local: Belo Horizonte
Experiência:  Necessário conhecimento em  Java ( Android Studio ou Ionic ), Webservices, WF. 
Desejável conhecimento em ABAP, SAP Web UI5.
Desenvolver soluções mobile, garantindo a entrega do escopo no prazo acordado, com alta qualidade de entrega.
Contratação PJ

Interessados enviar currículo para mariza.alves@pontualca.srv.br
citando pretensão taxa/hora.

**Comment by jpventura** [comment]
@MarizaAlves, qual o nome da empresa?

**Comment by MarizaAlves** [comment]
Bom dia!

 

Pontual Consultores Associados.

 

 



 

De: JP Ventura [mailto:notifications@github.com] 
Enviada em: terça-feira, 16 de outubro de 2018 04:37
Para: androiddevbr/vagas
Cc: MarizaAlves; Mention
Assunto: Re: [androiddevbr/vagas] (BELO HORIZONTE) DESENVOLVEDOR JAVA PARA ANDROID (#589)

 

@MarizaAlves <https://github.com/MarizaAlves> , qual o nome da empresa?
