### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android Pleno | Pixter

### ISSUE THREAD

**Issue by FelipePaiva1992** [androiddevbr/vagas#594]
**Empresa: Pixter (www.pixter.com.br)**

Somo uma empresa de tecnologia, voltada para desenvolvimento de software para clientes de grande relevância no mercado.
Utilizamos alta tecnologia e metodologias ágeis.
Construímos um time de excelência e trabalhamos com projetos selecionados de alto padrão.
Temos uma oportunidade de desenvolvedor, para integrar equipe de desenvolvimento Mobile.

**Requisitos**:
- Interesse em aprender novas tecnologias e compartilhar conhecimento
- Curtir trabalhar em equipe
- Vestir a camisa da empresa
- Adaptável a mudanças no decorrer do projeto
- Experiência com metodologia ágil – SCRUM/Kanban
- Conhecimento da ferramenta JIRA
- Ter trabalhado com metodologias ágeis

**Requisitos técnicos**:
- Confortável com padrão MVP, MVC, MVVM e derivados
- Conhecimento em consumo de APIs Rest e Soap
- Conhecimento com bibliotecas como Retrofit, Firebase, Picasso, Dagger 2
- Conhecimento em versionamento GIT
- Conhecimento em SQL e NOSQL (MongoDB)
- Criar layouts baseados em UI/UX

**Desejáveis**:
- Kotlin
- RxJava, RxAndroid e RxKotlin

**Diferenciais**:
- Conhecimento em Node.js
- Conhecimento em React e React Native
- Conhecimento em IONIC
- Conhecimento em Flutter

## Contratação
- Regime PJ
- Presencial

Interessados, que atendam aos requisitos, devem enviar CV e link do Github para fernanda.monteiro@pixter.com.br - Assunto: Desenvolvedor Android Pleno

**Comment by caiodev** [comment]
Seria sensato fechar esse issue já que o link está expirado e já se passaram 2 anos

**Comment by FelipePaiva1992** [comment]
Na verdade ...."about 2 months ago", só fazem dois meses.

Em qui, 13 de dez de 2018 00:58, Caio Costa <notifications@github.com
escreveu:

**Comment by caiodev** [comment]
Eu estava comentando sobre uma outra issue e acabei comentando nessa, foi mal
