### ISSUE TITLE
[Barra da Tijuca, RJ] Desenvolvedor(a) Mobile Android | Fulllab

### ISSUE THREAD

**Issue by leonardoarnaud** [androiddevbr/vagas#596]
## O que fará?

- Planejar etapas do desenvolvimento junto ao Designer e Líder de Projeto;
- Estimar prazos de entrega;
- Escrever e executar códigos do desenvolvimento;
- Testar os resultados dos códigos desenvolvidos avaliando possíveis erros ou falhas;
- Fazer merge do código; 
- Publicar versões na loja (Deploy);
- Manter comunicação alinhada com o time;
- Garantir a manutenção das funcionalidades desenvolvidas e tratar bugs. 

## É preciso saber:

- Arquitetura de software,
- Versionamento de código utilizando Git,
- Testes unitários,
- Java e Kotlin,
- Requests Restful,
- Arquitetura MVC e MVVM,
- Android Studio,
- Boas práticas de UI.

Forma de contratação e remuneração a combinar (Informar pretensão salarial na candidatura).

## Local
Rio de Janeiro - RJ - Barra da Tijuca

## Nossa empresa

A Fulllab é uma empresa que respira tecnologia e a usa para desenvolver as melhores soluções para o varejo. Combinando dados de consumo, retargetting, apps mobile e social commerce nossa missão é criar ferramentas para aumentar a conversão dos clientes.

## Como se candidatar

Por favor envie um email para leonardo.braga@fulllab.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Olá, @leonardoarnaud! Dúvidas pra melhorar sua experiência de recrutamento:

  - Qual o nível de senioridade procurado?
  - CLT ou PJ?
