### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android [PLENO|SENIOR] | WK Recursos Humanos

### ISSUE THREAD

**Issue by aaamenezes** [androiddevbr/vagas#597]
## Descrição da vaga

Desenvolvimento de bibliotecas Android para projeto fintech

## Local

Escritório São Paulo/SP bairro Santo Amaro

## Requisitos

- Kotlin
- MVVM
- Integração com webservices
- Persistência com banco de dados local

Desejável:
- Experiência em aplicações financeiras

## Contratação

- CLT

## Nossa empresa

Empresa de desenvolvimento mobile

## Como se candidatar

Envie um e-mail para marianna.braga@wkrh.com.br ou faça sua inscrição no link https://www.wkrh.com.br/job/desenvolvedor-android-pleno-senior-a0f1i000004vxwoua4/

**Comment by jpventura** [comment]
Olá, @aaamenezes! Segundo os [termos da comunidade](https://github.com/androiddevbr/vagas), é necessário recrutadores precisam divulgar o nome da empresa onde o desenvolvedor irá atuar. Do contrário, a vaga será removida.

**Comment by aaamenezes** [comment]
Olá @jpventura, somos uma consultoria de recursos humanos, e abrimos diversas vagas todas as semanas. Infelizmente não podemos abrimos o nome da empresa cliente, e por isso colocamos o ramo da empresa, no caso "Empresa de desenvolvimento mobile".

Essa informação podemos passar apenas na entrevista.

Existe outra forma para que eu possa continuar divulgando essa várias vagas?

**Comment by jpventura** [comment]
Nope :disappointed:

**Comment by jpventura** [comment]
@aaamenezes, infelizmente não

**Comment by aaamenezes** [comment]
Tudo bem.
