### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android <-> Junior | Itaú Unibanco

### ISSUE THREAD

**Issue by defaultbr** [androiddevbr/vagas#598]
Eai, está afim de trabalhar no maior banco do Brasil? 

## Sobre a vaga

Atuar no desenvolvimento de novas features, manutenção de aplicativos existentes com Kotlin e Java com aplicação de boas práticas e foco na qualidade, propor melhorias, participar de outros projetos e também terá oportunidade de aprender outras linguagens.

## Local

Itaú Unibanco Centro Empresarial - Parque Jabaquara, São Paulo

## Benefícios

- VA
- VR
- VT
- Plano de saúde
- Plano odontológico
- Seguro de vida
- PLR 
- Plano de carreira
- Café no andar free
- Área de jogos com pebolim e videogame

## Requisitos

- Desenvolvimento Android ou Kotlin
- Saber fazer um teste unitário
- Saber sobre Git (git pull, git push, git commit e outros comandos básicos)
- Trabalhar em equipe
- Noções do que é gradle e suas tasks
- Saber construir teste unitário (Mockito e afins)
- Boas práticas
- Confortável com MVP, MVVM, MVC e outros

Desejáveis
- Conhecimento em Espresso e/ou UI Automator
- Conhecimento em Dagger
- Conhecimento em RxJava ou coroutines

## Contratação

CLT - Junior

## Como se candidatar

Deve se cadidatar por intermédio de um link: http://bit.ly/ItauAndroidJr

conhece mais de Objective-C ou Swift? não tem problema, também temos vaga para você: http://bit.ly/ItauIOSJr

obs: sou funcionário do Itau e não recrutador

**Comment by jpventura** [comment]
@defaultbr, dê uma olhada também no [Cocoa Heads Brasil](https://github.com/CocoaHeadsBrasil/vagas/issues) para postar vagas relativas a iOS.
