### ISSUE TITLE
[Porto Alegre, Rio Grande do Sul] Desenvolvedor Android | TOTVS

### ISSUE THREAD

**Issue by martins-ramon** [androiddevbr/vagas#6]
## Descrição da vaga
Participar do desenvolvimento de aplicativos móveis e compor equipe distribuída globalmente (participantes nos EUA, leste europeu e ásia).

## Principais atividades da vaga
- Desenvolver e customizar sistemas (SW), garantindo que os sistemas desenvolvidos possuam robustez e qualidade.
- Participar do ciclo completo de desenvolvimento de software.
- Conduzir revisões de design e código
- Fornecer suporte ao QA

## Requisitos
- Inglês avançado
- Repositórios GIT, SVN
- Conhecimentos com TDD (Test-Driven Development ou Test-Driven-Design);
- Android Studio, Activities, Intents, Notifications
- Modelos de concorrencia sincronos e assincronos
- Processo de comunicação IPC e HTTP
- Conhecimento em Content Resolvers, Providers, SQLorte e SyncAdapaters
- Android OS 4.3+

## Benefícios
- Vale refeição
- Plano de saúde
- Horário flexível

## Contratação
Preferencialmente CLT. Outros modelos a negociar.

## Como se candidatar
Email para ramon.silva@totvs.com.br com CV, portfólio e pretensão salarial.

**Comment by walmyrcarvalho** [comment]
@martins-ramon Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by martins-ramon** [comment]
Já está fechada. Obrigado!

Date: Thu, 28 Jul 2016 07:46:25 -0700
