### ISSUE TITLE
[RS - Porto Alegre/São Leopoldo] - CWI Software - Desenvolvedor(a) Android

### ISSUE THREAD

**Issue by Lisi-Oliveira** [androiddevbr/vagas#603]
## Descrição da vaga
Dev. Mobile atua no desenvolvimento de aplicativos ou sistemas, programando nativamente ou por meio de outras linguagens para dispositivos móveis. Os principais sistemas operacionais mobile utilizados atualmente são o Android, da Google, e o iOS, da Apple.

Este (a) profissional é responsável por todo o projeto de desenvolvimento, desde a análise das necessidades do cliente, planejamento dos recursos do aplicativo, desenvolvimento, implantação de arquitetura, ferramentas e recursos, até a realização e configuração de testes.

## Local
Sede em São Leopoldo ou Porto Alegre

## Benefícios
Plano de saúde; Seguro de vida; Vale refeição; Vale Transporte; Incentivo a Educação;
Apoio certificação; Benefícios flexíveis; Ambiente Colaborativo;

## Requisitos
Conhecimento em Java, Kotlin, Material Design, Arquitetura MVVM + DataBiding, Injeção de dependências com dagger 2, Retrofit, Testes unitários com Mockito e Roboletric, Testes funcionais automatizados, Integração continua, Clean Code, Git, Publicação na Play Store e Analytics.

## Contratação
CLT 

## Nossa empresa
Desenvolvemos soluções e sistemas de TI com base nas necessidades específicas de empresas de médio a grande porte em âmbito global, desde 1991. O ambiente da CWI é pensado nos mínimos detalhes para que projetos e sonhos de vida sejam colocados em prática, com liberdade criativa e incentivo à inovação. Na CWI, todos têm liberdade para transmitir seus conhecimentos e competências entre todas as áreas, para que juntos sejam construídos projetos de qualidade superior. Os projetos da CWI motivam as equipes a darem o seu melhor, pois o crescimento pessoal e profissional se reflete no resultado final para as marcas que atendemos.

## Como se candidatar
Por favor envie um e-mail para work@cwi.com.br com seu CV anexado - enviar no assunto: Vagas Mobile Android. Você ainda pode cadastrar o currículo através do site https://cwi.com.br/Oportunidades

**Comment by jpventura** [comment]
Olá, @Lisi-Oliveira! Qual o nível de senioridade procurado?

**Comment by Lisi-Oliveira** [comment]
Oi @jpventura tudo bem contigo? Procuramos Pleno e Sênior. Se você tem interesse e disponibilidade em participar da seleção, me envia teu e-mail com teu material e teus contatos ;) Fico à tua disposição. Abraços!
