### ISSUE TITLE
[Santos, SP] Desenvolvedor Android | Cubbo

### ISSUE THREAD

**Issue by diegomalone** [androiddevbr/vagas#61]
## Descrição da vaga

Procuramos um desenvolvedor Android para melhorar nossos aplicativos já existentes e desenvolver novos aplicativos junto com nossa equipe de desenvolvimento.
## Local

Santos, SP.
## Benefícios
- Ambiente descontraído, informal e dinâmico
- Oportunidade de contribuir efetivamente para a evolução de uma startup
- Possibilidade de crescimento na empresa
- Contratação PJ
## Requisitos

Obrigatórios
- Experiência em desenvolvimento de aplicativos Android
- Boas práticas de desenvolvimento
- Experiência em consumo de APIs RESTful
- Conhecimentos em Git
- Facilidade para trabalhar em equipe
- Inglês técnico
- Disponibilidade para trabalho presencial em Santos, SP

Desejáveis
- Conhecimento em UX/UI
- Conhecimento de padrões e guidelines Android
- Conhecimento de programação reativa (RxAndroid)
- Domínio sobre testes unitários, de interface e TDD
- Experiência em desenvolvimento ágil
- Curiosidade e vontade de aprender novas ferramentas e tecnologias
- Capacidade de pensar e resolver problemas de forma criativa
- Experiência em startups

Diferenciais
- Aplicativos publicados
- Conhecimento em outras plataformas mobile, como iOS, Windows Phone, etc
- Projetos Open Source
- Perfil ativo no GitHub e StackOverflow
## Contratação

PJ a combinar.
## Nossa empresa

O Cubbo Design Studio é uma empresa formada por inovação e comprometimento, pioneira na baixada santista em seu segmento. Com o foco em projetos inovadores, desenvolvendo aplicativos e sistemas para facilitar a vida de clientes e empresas.
## Como se candidatar

Por favor envie um email para vagas@cubbo.com.br com o título "Vaga Android".

**Comment by walmyrcarvalho** [comment]
@diegomalone Tags adicionadas! :)

**Comment by diegomalone** [comment]
Essa vaga ainda está aberta.
