### ISSUE TITLE
[Berlin, Germany] Android Developer [SENIOR] | Blinkist

### ISSUE THREAD

**Issue by tfcporciuncula** [androiddevbr/vagas#613]
## Descrição da vaga

This ad goes out to all those who want to find a purpose in what they’re doing and take accountability for their work. At Blinkist, we’ve created a meaningful product that is growing fast. Our blinks – key insights from the world’s best nonfiction – help more than 7 million people around the globe to keep learning new, exciting things each and every day. In 2017, we received the United Nations World Summit Award in the Learning & Education category, a Google Material Design Award for Brand Expressiveness, as well as an Android Excellence Award. **Why do we need you?** Blinkist is growing quickly and we are looking for an Android Developer to help accelerate our ability to deliver a top-notch product to our users. This is where you come in. You will ship features that affect millions of users and revenue while playing with the latest technologies. **As one of our Android developers you will:**

- Take responsibility for driving the Blinkist Android App from day one.
- Implement new features & polish the app by increasing stability, fixing bugs and thinking about the user experience.
- Interact closely with designers & product managers to propose Android-suitable solutions.
- Conduct code reviews and participate in regular standups to ensure quality and alignment

## Local

At Blinkist, we offer a fantastic workplace in the heart of Berlin-Neukölln - but we're a remote friendly company.

## Benefícios

- Free private German & English lessons
- Free lunch
- 30 days paid vacation / year
- Foosball, ping pong, chess, etc.
- Free vouchers for Amazon, IKEA, Netflix, etc.
- 1,500€ yearly personal development budget
- Hairdresser at the office
- Quarterly events & Yearly company retreat
- Flexible working hours & Home office
- Relocation & Bureaucracy assistance

## Requisitos

- Extensive experience in Android Development
- Strong experience with RxJava and testing (Espresso, JUnit)
- Experience with Kotlin
- Familiarity with Dagger and Gradle
- Passion for writing clean architecture and easily-testable code
- Be keen to work with best-practice agile development methods and to increase the team's effectiveness with each release

## Nossa empresa

Where do the world’s smartest people get their ideas? From great books. Blinkist distills the key insights of 2,000+ bestselling nonfiction books into powerful 15-minute reads or listens for your mobile device.

In 2017, our app has been nominated by Apple as one of the best in the App Store. We have received the World Summit Award, granted by the United Nations, in the Learning & Education category, as well as a Google Material Design Award for Brand Expressiveness.

At Blinkist, we got rid of classical management hierarchies and, instead, distributed authority among all colleagues. We foster a unique company culture championing self-empowerment, personal development, direct communication and mutual support.

Our values: Champion Self-Empowerment - Default to Transparency - Communicate Directly - Strive to Learn and Grow - Support Each Other - Leave Egos Behind - Embrace Failure

## Como se candidatar

Stack Overfllow: https://stackoverflow.com/jobs/205426/senior-android-developer-blinkist
LinkedIn: https://www.linkedin.com/jobs/view/959868272/
Google Hire: https://hire.withgoogle.com/public/jobs/blinkistcom/view/P_AAAAAADAAADKVsb1qPddUq

**Comment by jpventura** [comment]
@tfcporciuncula is this position still opened or may we close the issue?

**Comment by tfcporciuncula** [comment]
@jpventura sorry, it's actually still open. I just updated the links, and now we're also looking for non senior candidates. Would it be possible to reopen the issue?
