### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android | BovControl

### ISSUE THREAD

**Issue by FernandaAbreu** [androiddevbr/vagas#62]
## Descrição da vaga

Estamos buscando os melhores brasileiros(as) para integrar a startup de pecuária de maior crescimento no mundo! É apaixonado por desenvolvimento mobile? Você está preparado? Então chegou sua hora!

## Local

Escritório São Paulo - Berrini

## Benefícios
- MAC +Monitor
- Assistência Médica (SulAmérica Saúde)
- Assistência Odontológica (SulAmérica Odonto)
- Ambiente descontraído e informal

## Requisitos

Obrigatórios
- Graduação na área de computação ou experiência equivalente.
- Experiência com desenvolvimento para aplicações móveis (Android Studio).
- Habilidade de trabalhar com dados remotos via REST e JSON.
- Experiência com GIT
- Dominar a construção de queries (SQL).
- Ter utilizado algum ORM Android (GreenDao, OrmLITE, SugarORM,..).
- Experiência com retrofit e OKHttp.
- Design Paterns.
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis
- Experiência com Espresso e UI Automator
- Experiência com RxJava
- Android Flavors
- Realm

## Contratação

CLT

## Nossa empresa

BovControl é uma startup de tecnologia que está revolucionando a forma de empoderar produtores de alimentos em todo o mundo (40% fora do Brasil).
Quer saber mais da empresa? Acesse o nosso [site](http://www.bovcontrol.com)

## Como se candidatar

Por favor envie um email para hello@bovcontrol.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by halysongoncalves** [comment]
Olá, home office?

**Comment by FernandaAbreu** [comment]
@halysongoncalves  Essa vaga em especifico é presencial.

**Comment by FernandaAbreu** [comment]
Inscrições encerradas!
