### ISSUE TITLE
[Franca - SP] Vaga Android LuizaLabs

### ISSUE THREAD

**Issue by rafaeltakiyama-luizalabs** [androiddevbr/vagas#634]
## Descrição da vaga

Atuar no desenvolvimento de aplicativos voltados para digitalização das lojas do Magazine Luiza, desenvolvendo novas features, manutenção preventiva e evolutiva.
O desenvolvedor(a) terá liberdade de trazer novas ideias e ferramentas, com o objetivo de melhorar o 
 processo de desenvolvimento e entrega dos apps.

## Local

LuizaLabs (Franca-SP)

## Benefícios

- Vale alimentação ou Refeição
- Plano de saúde
- PLR
- Apoio para realização de treinamentos e eventos
- Gym Pass
- Sinuca, pebolim, fliperamas e café
- Área de churrasco

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- MVP
- RxJava
- Clean Architecture
- Dagger
- JUnit

Desejáveis
- Ter noções de UX/UI
- Material Design
- Design Patterns
- Firebase
- Espresso
- TDD
- Git
- Código organizado e bem documentado

Diferenciais
- Ter algum tipo de certificação Java ou Android
- Contribuir em projetos opensource

## Contratação

CLT com valor baseado na experiência
Presencial

## Nossa empresa

Utilizar a tecnologia para oferecer uma experiência diferenciada ao cliente. Este é o objetivo do LuizaLabs, o laboratório de Tecnologia e Inovação do Magazine Luiza. 
Aqui, nós somos responsáveis pela digitalização do varejo brasileiro através de autonomia e metodologias ágeis para inovar e encantar o nosso cliente.
Somos ousados e não temos medo de errar. Você tem liberdade para fazer de forma simples e criativa. 
O Magalu faz parte das melhores companhias para se trabalhar do Instituto Great Place to Work, por 19 anos seguidos.
Venha compartilhar conhecimento e impactar a vida de milhares de clientes no Brasil.
https://medium.com/luizalabs

## Como se candidatar

Por favor envie um email para matheus.mendes@luizalabs.com / rafael.akiyama@luizalabs.com com seu CV anexado - enviar no assunto: "Vaga Android LuizaLabs"

**Comment by jpventura** [comment]
Olá, @rafaeltakiyama-luizalabs! Qual o nível de senioridade procurado?

**Comment by rafaeltakiyama-luizalabs** [comment]
Olá @jpventura , tudo bem? Estamos procurando um desenvolvedor(a) senior :)
