### ISSUE TITLE
[São Paulo, SP] Dev Android Sênior | Screencorp

### ISSUE THREAD

**Issue by ab8877** [androiddevbr/vagas#64]
## Descrição da vaga

Buscamos Desenvolvedor Android Sênior para ser o responsável por projetos mobile e Android TV inovadores e desafiadores, em parceria com multinacional de TVs. Temos grandes clientes dos segmentos bancário, cartão de crédito, farmacêutico, hospitalar, contact center, etc. Veja mais em https://screencorp.com.br/ e https://phonecorp.com.br/
## Local

Presencial em São Paulo - Vila Madalena, perto do metrô
## Benefícios
- Café expresso infinito
- Benefícios pagos em dinheiro
- Ambiente informal e super descontraído
- Flexibilidade de horário
- Apoio às suas intenções de carreira
- Muito teamwork
- Acesso direto aos founders (CEO, COO, CTO). Sua opinião é relevante
## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Criação de apps Android: do começo ao fim (inclusive publicação na Play Store)
- Experiência em otimização de memória e recursos de hardware
- Experiência em gestão (download, cache, buffering e reprodução) de mídias (vídeos e imagens)
- Experiência no envio de alertas / pushes
- Bons conhecimentos de UX
- Experiência com versionamento utilizando Git
- Experiência com controle de bugs e crashes

Desejáveis
- Experiência com integração contínua
- Experiência em aplicativos kiosk (rodando 24/7)
- Experiência com Android TV
- Experiência com Crashlytics
- Experiência com Firebase Cloud Messaging (FCM)

Diferenciais
- Conhecimento de Android NDK (e, claro, C/C++)
## Contratação
- CLT
- Salário compatível com o perfil. Envie sua pretensão e vamos analisar com atenção
## Nossa empresa

Somos uma startup B2B com produto validado, time world class e crescendo rápido com recursos próprios. Você responderá direto para o CTO, podendo propor ideias e melhorias para o produto.
## Como se candidatar

Por favor envie um email para rh@screencorp.com.br com seu CV anexado, mencionando apps publicados desenvolvidos por você. Enviar no assunto: Vaga Dev Android Sênior

**Comment by walmyrcarvalho** [comment]
@ab8877 Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by ab8877** [comment]
Olá... A vaga já foi fechada. Obrigado



-- André Barbosa
Skype: ab.8877 On Sat, Apr 08, 2017 at 9:47pm, Walmyr Carvalho < notifications@github.com [notifications@github.com] > wrote:
@ab8877 [https://github.com/ab8877] Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!
