### ISSUE TITLE
Desenvolvedor(a) Android Multinacional 

### ISSUE THREAD

**Issue by brunagsn** [androiddevbr/vagas#643]
Desenvolvedor(a) Android 

Projeto desenvolvimento de App reconhecimento facial 

Full Vila Olímpia 

Escritório com home Office um dia da semana São Paulo - Vila Olímpia

## Benefícios

- 1 horas de almoço
VT 
VR 30,00 
Ass.Medica 
Horário Flexível 

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android (Java ) Native

## Contratação

PJ a combinar 

## Nossa empresa

Aqui GSN somos líderes em Recrutamento e Seleção de TI 

## Como se candidatar

Por favor envie um email para claudio.santos@gsn.com.br com seu CV anexado - enviar no assunto: Vaga Android Full  com pretensão salarial 
Ou chamar no WhatsApp +5511946351802 Claudio

**Comment by jpventura** [comment]
Olá, @brunagsn!

De acordo com os termos da comunidade, é necessário divulgar o nome da empresa contratante. Caso contrário, a vaga será encerrada.

**Comment by davidtcdeveloper** [comment]
Issue encerrada por não seguir os termos do mural de vagas.
