### ISSUE TITLE
[Rio de Janeiro, RJ] Dev Android | Stone 

### ISSUE THREAD

**Issue by lalbuquerque** [androiddevbr/vagas#648]
## Descrição da vaga
O time com vaga disponível é:

{SDK Mobile} Uma biblioteca que permite realizar pagamentos direto em sua plataforma através de transações realizadas com cartão de crédito/débito/voucher que movimenta milhões por mês. Disponível para Android e iOS

Desenvolver bibliotecas de integração para parceiros grandes chave da empresa (Sum Up, Bematech) tudo sempre bem testado, redondo, um fluxo maduro antes de divulgar para um cliente, o maior desafio é desenvolver com estabilidade, confiança do produto sem nenhum erro em produção (o que afeta diretamente o cliente final) e desenvolvimento em cima de produtos novos do mercado; Manter o produto estável, subir atualizações sem que haja nenhum problema, qualquer erro pode custar caro; sdk transacional, um dos meios onde entra o dinheiro da companhia.

## Local
Nosso escritório fica no Centro do Rio de Janeiro/RJ

## Benefícios
- Vale Alimentação/Refeição
- Vale transporte
- Plano de Saúde e Odontológico
- Gym Pass
- Auxilio Creche
- Entre outros...

## Requisitos

Obrigatórios
- Sangue nos olhos
- Conhecimento de SDK Android
- Domínio da linguagem Kotlin
- Conhecimento de REST
- Conhecimento de algum modelo de arquitetura no meio Mobile (DDD, Clean Architecture, MVP, MVVM)
- Saber como criar uma biblioteca Android
- Git
- Testes unitários

Desejáveis
- Conhecimento com otimização e desempenho
- Conhecimento/experiência com Agilidade 
- Experiência com Pro-Guard
- Conhecimento de Programação Funcional
- Conhecimento de Design Patterns 
- Flavors e Tasks do Gradle
- Conhecimento de Programação Reativa (RxJava)

Diferenciais
- Experiência com C++
- Conhecimento de JNI/NDK
- Experiência com Espresso e UI Automator
- Familiaridade com “meio de pagamento”
- Conhecimento de iOS

## Contratação
CLT

## Nossa empresa
A Stone é uma empresa de tecnologia que desenvolve produtos para que lojistas recebam o valor das vendas feitas por meio de pagamento eletrônico, seja no mundo físico ou no digital.

Nascemos em 2012. Já fomos uma startup. Hoje, somos uma companhia de mais de 3000 pessoas, unidas por um único sonho: mudar este mercado, trazendo melhores tecnologias, produtos inovadores e um serviço de qualidade para nossos clientes. Nosso propósito é ajudar o empreendedor a empreender no Brasil.

Nosso dia a dia? Ultrapassar limites, aprender muito e transformar potencial em potência. O seu, o da Stone e o dos nossos Clientes.

## Como se candidatar
Por favor envie um email para maib.oliveira@stone.com.br com seu CV anexado ou LinkedIn (caso esteja bem preenchido 😄). 
Enviar no assunto: Vaga SDK Android (Android Dev BR)

**Comment by jpventura** [comment]
Olá, @lalbuquerque! Qual o nível de senioridade?

**Comment by lalbuquerque** [comment]
@jpventura pleno/senior
