### ISSUE TITLE
[São Paulo, SP] Android Software Engineer | MeSeems

### ISSUE THREAD

**Issue by nmizoguchi** [androiddevbr/vagas#65]
## Job Description

**What should I expect to do?**
A software engineer is a professional responsible for planning the software architecture and development. A good software engineer cares deeply about how to design, develop, maintain, and test a system. Doing this in mobile is just as important as in any other platform. An outstanding mobile software engineer understands the importance of a good architecture, building modular features, and coordinating different parts of the software, such as persistence, networking, business logic, and UI. Besides all responsibility, you will improve yourself and learn a lot in this position!

**Why engineer, and not developer?**
MeSeems is a technology company, and therefore, we need an outstanding tech team. We believe that mobile development is more than just hacking, and making it work, but building a system that is maintainable and extensible. At MeSeems, we treat a mobile app as a complete software, with well-defined layers, striving to build a Clean Architecture.

**What about user experience?**
At MeSeems, we care deeply about our Android users. We thrive to deliver the best UX to users, following the UI guidelines of each platform, and we give the same importance to UI and UX as we give to our architecture.
## Location

São Paulo - Jardim América, SP, Brasil
## Benefits
- Competitive salary package
- Health and dental insurance
- Meal allowance (“Vale refeição”)
- Fun and fast-paced work environment
## Requirements
- Computer Science, Computer Engineering or equivalent degree
- Deep understanding of Android SDK
- Strong analytical skills (we take this seriously!)
- Want to learn more about Reactive Programming
- Excited to always deliver the best UX to users

**Relevant Experiences**
- Passion for mobile technology and high quality engineering
- Have developed and submitted an app on the App Store or Play Store
- Experience with specific frameworks (Custom UI, Animation, etc.)
- Pixel perfect eye
## About Us
- [business.meseems.com.br/jobs](http://business.meseems.com.br/jobs)
- [business.meseems.com.br](http://business.meseems.com.br)
- [www.meseems.com.br](http://www.meseems.com.br)
## How to Apply

Please send resume to oportunidades@meseems.com.br with subject: _MeSeems | Recruitment_.

**Comment by rsicarelli** [comment]
Oi @nmizoguchi. Obrigado por cadastrar a vaga. Os hiperlinks estão errados na parte do `About Us`. Seria interessante corrigir para não haver necessidade de copiar e colar

**Comment by nmizoguchi** [comment]
Olá @rsicarelli obrigado pelos toques! Corrigido.
