### ISSUE TITLE
[São Paulo - SP] Radar Profissional - Desenvolvedor Mobile Android Pleno/Sênior

### ISSUE THREAD

**Issue by RADARProfissional** [androiddevbr/vagas#656]
Essa vaga foi removida por não atender as [especificações do grupo de Android Dev BR](https://github.com/androiddevbr/vagas/blob/master/README.md).

Se ela for reeditada atendendo as regras descritas no [README](https://github.com/androiddevbr/vagas/blob/master/README.md), teremos prazer em aprová-la :smile:

**Comment by douglasdrumz** [comment]
Qual o nome da empresa? De acordo com os requisitos de publicação, vagas sem nome da empresa serão removidas

**Comment by RADARProfissional** [comment]
RADAR PROFISSIONAL.

**Comment by douglasdrumz** [comment]
Para trabalhar na Radar Profissional mesmo ou é recrutamento para outra empresa?

**Comment by jpventura** [comment]
@RADARProfissional Os [novos termos de uso](https://github.com/androiddevbr/vagas/blob/master/README.md) são claros com relação a postagem de vagas por partes de recrutadores e agências de empregos: *é necessário divulgar o nome da empresa onde o candiato irá atuar*.

Percemos que você repostou a vaga sem respeitar os termos. Caso essa regra não seja respeitada, a vaga será removida.
