### ISSUE TITLE
[São José dos Campos, SP] Desenvolvedor Android Sênior - Guichê Virtual

### ISSUE THREAD

**Issue by brsanthiago** [androiddevbr/vagas#66]
#### O que a gente procura:

Sólida experiência em desenvolvimento de apps para Android, tendo já desenvolvido/publicado apps. Conhecimentos avançados em estrutura de dados, algoritmos, arquitetura de software, design patterns e TDD.
#### O que a gente espera:
- Proativo em puxar problemas para si e buscar soluções.
- Comprometido com o time.
- Compromisso com qualidade.
- Autodidata.
#### O que a você fará:
- Desenvolvimento de apps para Android, direcionando a arquitetura, manutenção e evolução do app.
- Levantamento de requisitos e necessidades, através de prototipação e testes de usabilidade.
- Planejamento, priorização e estimativa das atividades a serem realizadas para atingimento dos objetivos e entregas do app.
- Atuação como referência para outros desenvolvedores, incluindo disseminação de conhecimento.
## Local

São José dos Campos - São Paulo
## Requisitos

Obrigatórios
- Design Patterns
- Estrutura de dados
- Arquitetura de software (Mobile)
- TDD

Desejáveis
- Experiência com desenvolvimento Agile/Scrum
- Conhecimento em design: UI/UX/HCL especialmente mobile.

Diferenciais
- Ter desenvolvido algum app.
## Como se candidatar

Por favor envie um email para recrutamento@guichevirtual.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Android Sênior

**Comment by walmyrcarvalho** [comment]
@brsanthiago Boa tarde Bruno, tudo bem? Cara, você sabe qual é o formato de contratação da vaga? Só pra gente completar o repo. :)

**Comment by lucasgcampos** [comment]
@walmyrcarvalho aqui no Guichê estamos buscando um clt presencial

**Comment by walmyrcarvalho** [comment]
@lucasgcampos Show, vou adicionar a label! :)

**Comment by walmyrcarvalho** [comment]
@brsanthiago Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by brsanthiago** [comment]
@walmyrcarvalho Pode encerrar.
