### ISSUE TITLE
[Rio de Janeiro/RJ] Desenvolvedores (as) Android [Junior/Pleno/Sênior] BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [androiddevbr/vagas#662]
Descrição da vaga
Estamos montando um time de profissionais com experiência em Android para cliente de grande porte.
Serão muito bem vindos profissionais de todos os níveis (Júnior, Pleno e Sênior). 

Local
Escritório BRQ no Rio de Janeiro- região Central da capital.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-previdência privada
-assistência médica
-assistência odontológica
-ambiente descontraído
-chances de crescimento e aprendizado

Requisitos

Obrigatórios
- Android (Java e Kotlin)

Desejáveis
-REST 
-Butterknife 
-Retrofit 
-RX Java 
-FCM 
-RecyclerView 
-Constraint Layout e Fragments. 
-Desejável conhecimento em Event bus, CardView.

Contratação

CLT full, salário a combinar + atrativo pacote de benefícios.

Nossa empresa
Fundada em 1993, a BRQ é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife e Nova Iorque. 

Como se candidatar

Por favor envie um email para ryokota@brq.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by lfgtavora** [comment]
Olá existiria a possibilidade de uma vaga em nivel estágiario? Gostei MUITO da empresa e possuo certa "experiencia" com Retrofit, RecyclerViews, Constraint Layout, mas gostaria muito de evoluir minha programação através de desafios reais. Possuo no meu repositorio um desafio da CONCRETE feito no padrao MVP... Caso interesse segue meu curriculo completo:

[Curriculo_2019.pdf](https://github.com/androiddevbr/vagas/files/2784374/Curriculo_2019.pdf)

**Comment by jpventura** [comment]
@ReAnne123 Se essa oportunidade ainda estiver disponível, por favor reabra o _issue_
