### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android PLENO | MIRA EDUCAÇÃO

### ISSUE THREAD

**Issue by MiraEduc** [androiddevbr/vagas#664]
## Descrição da vaga

O time de engenharia Mira é responsável, dentre outras coisas, pelo desenvolvimento do app Mira Aula que promove a interação entre professores, gestores, responsáveis e alunos. A qualidade é um dos nossos valores bases, manter o Mira Aula estável, íntegro e rápido são preocupações fundamentais em nosso time. Para isso contamos com um time de engenheiros de software genuinamente preocupados em utilizar as melhores tecnologias e metodologias de desenvolvimento.

Estamos crescendo, e para isso precisamos aumentar o nosso time. Procuramos engenheiros de software apaixonados por tecnologia, que se comprometam com a missão da nossa empresa e que tomem o Mira Aula como sendo seu. Que não se limitem apenas em resolver o problema, mas também em encontrar a melhor solução possível dentre as demais.

Como Software Engineer Android os seus maiores desafios serão:

Desenvolver features, melhorias e correções no app Mira Aula na linguagem Kotlin, seguindo os fluxos e UI estabelecidos por Design;
Implementar testes minuciosos para as entregas, garantindo o crescimento sustentável do app;
Se posicionar proativamente perante os problemas enfrentados no dia a dia;
Auxiliar tecnicamente o time com o conhecimento e experiência;
Se manter atualizado sobre as novidades tecnológicas do Android;
Não se limitar a uma única linguagem e/ou plataforma. Somos todos engenheiros;

## Local

Escritório - Paulista/SP.

## Benefícios

- Assistência Médica e Odontológica - 100% custeada pela empresa;
- Vale Refeição;
- Vale Alimentação ou Combustível;
- Vale Cultura;
- Gympass;
- Auxílio Creche;
- PLR – Atrelado a metas;
- Desconto com escola de idiomas;
- Quick Massage;
- Flexíveis: Happy Hour toda sexta, Snacks à vontade, Sala de descanso, Vídeo game, Dresscode e ambiente informal;
- Ótima localização, ao lado do metrô Consolação/Paulista.

## Requisitos

- Bagagem com desenvolvimento android, preferencialmente que já tenha experiência em Kotlin;
- Preocupação constante com arquitetura, documentação e testes;
- Familiaridade com arquitetura reativa;
- Experiência com offline first e CI são muito bem-vindas;
- Pensar como time: compartilhar conhecimentos, discutir soluções, trabalhar em equipe;
- Sempre ter um olhar crítico e propor melhorias na organização do código, estrutura e arquitetura quando achar necessário;
- Expor sua opinião, independente da opinião dos demais;

## Contratação

CLT a combinar

## Nossa empresa

A Mira é uma Startup que busca solucionar uma questão básica em todo o mundo: educação. Desenvolvemos ferramentas com o objetivo de facilitar a vida de professores e gestores, envolvendo os responsáveis e garantindo uma melhora no processo educativo dos alunos de modo escalável e com baixo custo.

Somos uma empresa engajada por um propósito maior, fazer a diferença na educação pública do Brasil. Somos inconformados com o presente e queremos construir um futuro diferente.

Se você quer que seu trabalho cause impacto na sociedade e você sinta orgulho disso, seu lugar é aqui.
Queremos inspirar outras pessoas, contribuir positivamente para o futuro de nosso país. Para isso contamos com colaboradores engajados, apaixonados pela nossa causa e motivados pelo impacto social.

Um pouco sobre a nossa Cultura:
- Somos orientados pela experiência de nosso usuário. O problema do nosso usuário é o nosso problema;
- Nosso foco é resultado, contamos com uma equipe altamente capaz e disposta para atingi-lo;
- Estamos sempre em busca de melhorias;
- Estimulamos o “pensar fora da caixa” e valorizamos as boas ideias;
- Nossa equipe é colaborativa e prestativa;
- Valorizamos as singularidades e respeitamos as diferenças;
- Damos a todos autonomia e liberdade para colocar suas ideias em prática;
- Nossos Miranautas se sentem donos do projeto e realizados a cada entrega;
- Reconhecemos nossos erros, e mais do que isso, estamos sempre abertos a mudança.
- Aqui tudo é compartilhado, nossos resultados, ideias, dúvidas, gostamos de ouvir a opinião de nosso time, independentemente da posição que ocupe.

## Como se candidatar

Por favor, envie um email para rh@miraeducacao.com.br com seu CV anexado - enviar no assunto: Vaga Android.

**Comment by jpventura** [comment]
@MiraEduc Se essa oportunidade ainda estiver disponível, por favor reabra o _issue_
