### ISSUE TITLE
[São Paulo,SP] Desenvolvedor Mobile [Pleno] SETIS

### ISSUE THREAD

**Issue by lurodrigues77** [androiddevbr/vagas#666]
## Pré-requisitos

Graduação Completa em Análise de Sistemas, Ciência da Computação, Engenharia da Computação, Sistemas de Informação ou cursos afins;
2 a 3 anos de experiência em Android e desenvolvimento para aplicações corporativas utilizando Java;
Conhecimentos em linguagem C e C++
Conhecimentos em testes de sistema e integração contínua;
Experiência com desenvolvimento de Testes Unitários;
Experiência com sistemas de controle de versão (preferencialmente GIT).
Bom nível em inglês

## Local
Vila Mariana - perto do metrô Ana Rosa

## Benefícios
Vaga CLT, Vale Transporte/Estacionamento, Vale refeição (28,60/dia), Assistência Médica SulAmérica para você e dependentes sem coparticipação, Programa de Qualidade de Vida.

## Requisitos

Obrigatórios:
- 2+ anos de experiência com Android

Diferenciais:
-Experiência com Kotlin;
Conhecimento da plataforma iOS;
Conhecimentos em desenvolvimento Cross-Plataform para mobile (React Native, Xamarin, dentre outros);
Experiência com metodologias de desenvolvimento ágil;
Experiência com desenvolvimento utilizando Spring, JPA, Serviços REST;
Projetos opensource

## Contratação

CLT

## Nossa empresa

A SETIS especifica, desenvolve e integra a maioria dos componentes de software envolvidos em sistemas de pagamento eletrônico, de drivers específicos a sistemas completos, de plataformas proprietárias a sistemas em PC, de ferramentas de certificação a sistemas de autorização.

A SETIS é pioneira no Brasil no desenvolvimento de soluções de cartões com chip, assim como de aplicações para terminais POS.

## Como se candidatar

Por favor envie um email para luciana.domingues@setis.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Mobile

**Comment by mr-villalobo** [comment]
Venham trabalhar com a gente!

**Comment by jpventura** [comment]
@lurodrigues77 Se essa oportunidade ainda estiver disponível, por favor reabra o _issue_
