### ISSUE TITLE
[Rio de Janeiro, RJ] Storm Group - Desenvolvedor Android Sênior

### ISSUE THREAD

**Issue by luanstorm** [androiddevbr/vagas#667]
### **Descrição da vaga:**
Procuramos desenvolvedores com sólida experiência em desenvolvimento na plataforma Android para ingressar na equipe de desenvolvimento dos aplicativos Globoplay para Android (mobile e tablet) e Android TV. 

Buscamos profissionais apaixonados por tecnologia, que valorizam trabalhar em ambiente colaborativo; que tenha participação ativamente na concepção e desenvolvimento, desde o design até a entrega da experiência aos nossos usuários; E que tenha propriedade sobre o produto e lute pelo sucesso e melhoria, com senso de "dono" do projeto. 

### **Procuramos quem tenha:**
- Amplos conhecimentos em Java e Kotlin (3+ anos de experiência);
- Ter boa experiência com controle de versão com Git;
- Experiência com Gradle para gerenciamento de dependências do projeto;
- Experiência com integração com APIs RESTful;
- Domínio em desenvolvimento front-end (criação de views e telas) e adaptação de layout entre diferentes tamanhos de tela,
- Conhecimento das guidelines de design e de desenvolvimento do Google (Material Design)
- Prática de testes automatizados;
- Ter familiaridade com frameworks Android nativos (Design Support Library, Google Play Services, etc).
- Conhecer o processo de publicação e distribuição de Apps pela Google Play;
- Experiência com integração contínua;
- Vivência profissional de Metodologias Ágeis (Scrum / Kanban / Lean)

### **Diferencial será:**
- Experiência com desenvolvimento para AndroidTV;
- Experiência com universal links e In-App billing;
- Experiência com GraphQL no ambiente Android;
- Experiência com ferramentas como Firebase, Google Analytics, Crashlytics e Fastlane;

### **Nossa empresa**
A Storm Group é uma prestadora de serviços e integradora de soluções completas em tecnologia, desde o desenvolvimento e manutenção de sistemas de alta performance até a criação de aplicativos web e mobile.

### **Como se candidatar**

Por favor envie um email para rh@stormsec.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Mobile Android

**Comment by jpventura** [comment]
@santanaluiz qual o nível de senioridade? clt ou pj? remoto ou presencial?

**Comment by santanaluiz** [comment]
@jpventura tag errado 😂

**Comment by jpventura** [comment]
@luanstorm Se essa oportunidade ainda estiver disponível, por favor reabra o _issue_
