### ISSUE TITLE
[Alemanha - (Berlin e Hamburgo)] Android Developer Senior

### ISSUE THREAD

**Issue by santanaluiz** [androiddevbr/vagas#668]
## Descrição da vaga

You love coding, we get it. We love coding too!
But most important, we love good code. And what does this mean?
It means...
that we write clean code
that we use the latest technologies (Kotlin, RxJava, MVP)
that our developers and our QAs are part of the same team
that we learn from our colleagues (even if they own an iPhone)
that we work on an agile environment
that we enjoy the product we build
Good code means a lot to us.

So…
Do you have a degree in informatics or similar?
Do you have several years of experience in Android development?
Do you have very good knowledge of Kotlin and Java?
Jump in to mytaxi and show us what you can do!

## Local

Alemanha - Berlim ou Hamburgo

## Benefícios

- The chance to bring in your own ideas
- A strong team spirit
- Excellent monetary benefits (a pension plan, a monthly mobility allowance for free taxi rides, - subsidised public transport ticket)
- Have your birthday off!
- ...and all the usual start-up goodies like unlimited soft drinks, after-work beers and many more

Oh, and the opportunity to work with the best team in the world (we know, everybody says so, but at mytaxi it’s true)!

## Requisitos

**POR FAVOR, SE NÃO TIVER OS REQUISÍTOS OBRIGATÓRIOS, NÃO APLICAR/ENVIAR E-MAIL!!!!**

Obrigatórios
- Formado em Ciencias da Computação ou Similar
- Mínimo 4 anos de experiência
- Experiência com testes
- RxJava/RxKotlin
- Kotlin
- **FALAR INGLÊS**

## Contratação

Contrato permanente e sponsor de visto

## Nossa empresa

Design the future of mobility with us!

mytaxi was founded in June 2009 and was the world’s first taxi app that established a direct connection between a passenger and a taxi driver. With more than 10 million passengers and 100,000 drivers, mytaxi is the leading taxi e-hailing app in Europe.

Since September 2014, mytaxi has been part of Daimler Mobility Services GmbH (part of the Daimler Group). In July 2016, mytaxi announced a merger with Hailo, the leading taxi app in the UK and Ireland, an important step in becoming the leading taxi e-hailing app in Europe. Mytaxi works with more than 500 employees in 26 European offices and is available in more than 100 European cities. Eckart Diepenhorst is CEO of mytaxi.

Join a fun, global team of top engineers and seasoned entrepreneurs for the challenge of a lifetime. We strive to be passionate yet practical, driven but focused and visionary but humble. Our employees are routinely challenged to solve large-scale, highly complex technical problems. As a new "family member" you will be stretched, but will learn best practice at scale in our creative and fun environment!

## Como se candidatar

https://mytaxi.com/career/jobs/

**POR FAVOR, SE NÃO TIVER OS REQUISÍTOS OBRIGATÓRIOS, NÃO APLICAR/ENVIAR E-MAIL!!!!**

*** Ao aplicar mencionar: "Brazilian Android dev Slack comunity"

**Comment by jpventura** [comment]
@santanaluiz qual o nível de senioridade? cobrem os custos do visto e mudança? 🤔

**Comment by santanaluiz** [comment]
@jpventura Senior. Ajudam com custos sim. Mas não sei dizer valores

**Comment by jpventura** [comment]
@santanaluiz Se essa oportunidade ainda estiver disponível, por favor reabra o _issue_
