### ISSUE TITLE
[São Paulo, SP] Android Software Engineer [Senior] | DogHero

### ISSUE THREAD

**Issue by guimellon** [androiddevbr/vagas#669]
## DogHero

DogHero is a peer-to-peer pet boarding marketplace that connects pet owners with trusted hosts. Using technology and design we are redesigning how pet owners think about boarding their pets while they are away, an experience that before was very painful and troublesome. We want to revolutionize the pet services industry in Brazil, Latin America and the world.

## Technology Team at DogHero

The tech team is a core part of DogHero. It’s our responsibility not only to develop systems and products that our customers want but also to help other internal stakeholders to make the right decisions. The tech team participates in all aspects of the product development: idea, market, UX, UI, architecture, code development, and QA. We know that it's about delivering the right solutions no matter what technologies we need to use. We encourage learning and self development - we stay away from people that are living in the past. Our goals are to build great products, be a cohesive high performing team, and be excellent in all aspects.

We are looking for top notch developers to scale our tech team.

## Location

Our office is in Vila Mariana, São Paulo

## Responsibilites

- Develop and maintain our native Android app
- Consume RESTful APIs to implement new functionalities that enhance the quality of our product
- Bring pixel perfect UI/UX into life
- Work in a an informal fast paced environment.
- Learn and be constantly challenged
- Have autonomy to define the best courses of action
- Work and learn the newest technologies
- Create quality products that has a very high approval from both our customers and hosts
- Live by the concepts of agile development and lean startup

## Requirements

- 3+ years of relevant coding experience
- Knowledge in software architecture
- Strong problem solving skills
- Excellent TDD and test automation skills (Espresso, Mockito, JUnit)
- Advanced knowledge of Android Java (Kotlin is a plus)
- Has an entrepreneurial spirit. Thinks and acts as an owner - preferably you have already started your own venture, or worked at a technology startup
- Willingness and motivation to do the heavy lifting
- Comfortable with uncertainty and able to navigate without a clear direction
- Values environments where data and facts speak louder than HiPPO (Highest Paid Person’s Opinion)
- Is a great communicator - able to convey and argument in a clear and concise way to other team members
- Has deep point of views about emerging technologies, and that helps create a clear and productive workflow for the tech team.

## Hiring & Benefits

- Competitive salary (CLT)
- Opportunity to earn stock options
- Health plan
- Bonus for upgrading your computer set up
- Private cook at the office
- Fun, collaborative, and fast-paced work environment
- Dog-friendly office... wof wof

## Apply

Please apply at https://doghero.workable.com/j/7BDE7D938F

We are a Portuguese speaking company. This is written in English because 1) we value diversity and would welcome foreign candidates, and 2) if you are Brazilian you need to be advanced reading in English in order to learn the most from the whole world.

**Comment by jpventura** [comment]
@guimellon Se essa oportunidade ainda estiver disponível, por favor reabra o _issue_
