### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android Pleno - ZAP Imóveis

### ISSUE THREAD

**Issue by ladoleste** [androiddevbr/vagas#67]
## Descrição da vaga

O ZAP está contratando profissionais para Android. Venha fazer parte do nosso time!
## Local

Escritório São Paulo – Vila Olímpia
## Benefícios
- Assistência Médica (Bradesco Saúde)
- Assistência Odontológica (Bradesco Odonto)
- VR
- VT
- Seguro de Vida
- PPR conforme resultados da Empresa
- Happy Day – folga no dia do aniversário
- Convênios Diversos
- Ambiente descontraído
## Requisitos

**Ferramentas**
- IDE: Android Studio
- Build: Gradle
- Controle de versão: Git

**Metodologia**
- Scrum

**Competências técnicas**
- Domínio dos conceitos do Material Design
- Fragments
- Support Library
- Services
- Broadcast Receivers
- SQL Lite
- Notifications
- Themes, styles e animações
- Consumo de REST API's com Volley e/ou Retrofit

**Teste automatizado**
- Unitário: JUnit
- Interface: Espresso

**Desejamos**
- Ter preocupação com as boas práticas de programação (SOLID)
- Bons conhecimentos de UX
- Inglês técnico
- Injeção de dependência
- Domínio das API’s do Google Play Services
- Publicação de aplicativos na loja e acompanhamento de bugs
- Ter um aplicativo próprio preferencialmente já publicado
- Experiência com Google Analytics e/ou Tag Manager

**Diferenciais**
- Pleno conhecimento de padrões de projetos (Design Patterns)
- Bons conhecimentos em Kotlin
- RxJava
- Domínio de conceitos de programação funcional e reativa
- ORM’s (Realm)
- Contribuições Open Source
## Contratação

CLT
## Nossa empresa

O ZAP, uma empresa do Grupo Globo, é o mais moderno e eficiente portal de classificados de imóveis da internet brasileira, onde mantém liderança absoluta. Saiba mais: https://www.youtube.com/watch?v=BTKLdxbkGdA
## Como se candidatar

Por favor envie um email para selecao2@zapcorp.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@ladoleste Ia editar agora, valeu!
