### ISSUE TITLE
[Palo Alto / Los Angeles, California] Senior Android Engineer | Tinder

### ISSUE THREAD

**Issue by tinder-marcosdamasceno** [androiddevbr/vagas#670]
**Candidatos(as) que precise de H1B sponsoring deverão aplicar até o dia 20 de Janeiro 2019.**

**Folks que façam parte de um grupo de tecnologia que tenha um processo seletivo ou de prestígio, como Google Developer Expert, Microsoft MVP, Oracle Champion e etc. Podem aplicar a qualquer momento pois existe uma boa chance que você qualifique para o visto O-1**

**Inglês fluente necessário**

As a Senior Android Developer at Tinder you have the unique opportunity of joining a company with hundreds of millions of downloads, but a small enough team where your impact is felt. From your first day on the job you will be contributing to core features of Tinder. You've already built multiple Android apps and are ready to meet the unique challenges of supporting a huge user base while continuing to add new features and products as Tinder keeps skyrocketing. The Tinder design team is first class and you will no longer be working on lifeless apps with lists of data and boring screens.

We're a diverse team that encourages personal success and is always looking on different ways to make the team excited and happy.

This position is for either our Tinder LA HQ or our new Tinder Palo Alto office! Unfortunately no remotes for now.

**In this Senior Android Engineer role, you will:**

- Develop new features and fix bugs for the Tinder Android app 
- Work closely with Backend Engineers to deploy exciting new Tinder features 
- Work with graphics team to design and wireframe modern interfaces 

**We're looking for:**

- Loves Kotlin, we're 85% plus in Kotlin and every new feature is expected to be written in Kotlin
- Someone who obsesses over Activity transitions and animations (eg. you know your way around a Canvas and can do property animations in your sleep.  You could implement the Tinder Card Stack yourself and have ideas on how to optimize it.)
- A strong software architect and well versed in design patterns.  (eg. you've worked with MVP, Clean or MVVM and know the benefits of each. You've written your own Respositories and Factories.)
- Understanding the value of Dependency Injection and have implemented Dagger
- Someone who loves test coverage.  (eg. you're well versed with Mockito and JUnit.  You can write Espresso tests when needed.)
- Someone on the RxJava train.  (eg. you know when to map or flatMap, but when something shouldn't be Observable, also when coroutines would be a better candidate than RxJava.)
- Consuming RESTful service is old hat for you, you use RetroFit and move on to the more important pieces of your app
- Understanding Material design guidelines, but are not a slave to it.  (eg. you know how to be a good Android citizen while maintaining a strong unique brand identity.)
- Someone interested in Kotlin, who's using Retrolambda and know what's new in Java 8
- Able to mentor junior developers, impart your knowledge so they can become an engineer of the same quality as your self
- Comfortable working with legacy code and improving it

## Como se candidatar

Por favor envie um email para marcos.damasceno@gotinder.com com seu CV anexado - enviar no assunto: Senior Android Position. No email por favor também compartilhe se você precisa de um H1B ou se você acredita que se qualifica para o O-1.

**Comment by jpventura** [comment]
@tinder-marcosdamasceno Se essa oportunidade ainda estiver disponível, por favor reabra o _issue_
