### ISSUE TITLE
[Rio de Janeiro, RJ] Globo.com - Desenvolvedor(a) Android Globoesporte [Pleno, Senior] [CLT]

### ISSUE THREAD

**Issue by vivientavares** [androiddevbr/vagas#673]
Você quer trabalhar com produtos que são a paixão de mais de 30 milhões de fãs de esporte? Venha criar com a gente o Cartola FC e o Globoesporte. 

Você fará parte de um time multidisciplinar, formado por software engineers, designers, arquiteta(o)s de informação e devops.

## Descrição da vaga

Projeto de desenvolvimento  da APP globoesporte.com

## Requisitos

Suas responsabilidades:

Ser apaixonada(o) por desenvolvimento de software e tecnologia;
Ter facilidade para trabalhar dentro de times multi-disciplinares;
Escrever código limpo, de fácil manutenção, utilizando as melhores práticas de desenvolvimento de software;
Procurar sempre criar a melhor experiência de uso para o usuário final, trabalhando de perto com os especialistas em UX;
Colaborar com idéias e sugestões para soluções eficazes e criativas;
Ajudar o crescimento do seu time, ensinando, capacitando e dando feedbacks;
Colaborar com o time, a área e a empresa para criar um clima positivo e motivador;
Estar sempre crescendo e se desenvolvendo profissionalmente.

Para aplicar para essa vaga é **fundamental**:

Ter sólidos conhecimentos e habilidades em algoritmos e estruturas de dados;
Ter domínio de engenharia de software, princípios, boas praticas e padrões de arquitetura;
Pelo menos 2 anos de experiência com Java e/ou Kotlin;
Ter conhecimento de práticas de XP (TDD, pair programming, refactoring, continuous integration, etc).

São diferenciais:

Conhecimentos de automação de publicação de aplicações (fabric, etc);
Ter experiência com métodos ágeis e práticas de engenharia ágil;
Conhecer e ter experiência com testes unitários, de aceitação, mocks, etc;
Ser poliglota em linguagens de programação e plataformas;
Saber trabalhar com ferramentas de controle de versão.
 
## Local

Esta vaga é para o nosso escritório no Rio de Janeiro/RJ. Pessoas de qualquer parte do Brasil são muito bem-vindas - a globo.com tem uma grande quantidade de profissionais de diversos estados. Temos um pacote especial de benefícios para a mudança de pessoas de fora da cidade.

## Contratação

CLT

## Nossa empresa

A globo.com

A globo.com é o braço de Internet do Grupo Globo, o maior grupo de mídia da América Latina. A globo.com agrega os maiores portais do Brasil, e é líder de audiência de Notícias com o portal G1, Esportes com o GloboEsporte.com, Entretenimento com o portal GShow, e Vídeos com o Globo Play.

A globo.com possui uma das maiores infra-estruturas de distribuição de conteúdo da América Latina, e é detentora do recorde de maior audiência em vídeo streaming do Brasil.

Somos uma empresa que reconhece a importância da igualdade de oportunidades. O respeito ao outro, a valorização da diversidade e a convicção de que todos dependem de todos são componentes essenciais da nossa identidade.

## Como se candidatar

Por favor, se inscreva em https://talentos.globo.com/#/oportunidades/desenvolvedor-a-android-esportes/mp0jooq

BOA SORTE!

**Comment by jpventura** [comment]
@vivientavares Se essa oportunidade ainda estiver disponível, por favor reabra o _issue_
