### ISSUE TITLE
[Curitiba, PR] Desenvolvedor Android [JUNIOR][PLENO] | Wolk

### ISSUE THREAD

**Issue by gustavosantosneto** [androiddevbr/vagas#675]
## Descrição da vaga

Vaga para empresa http://www.wolk.com.br/

Para mais detalhes entrar em contato com HeadHunter:
(11) 961942551
gustavosantosneto@gmail.com

## Local

Curitiba, PR 

## Requisitos

Obrigatórios
- Pelo menos 1 ano de experiência com desenvolvimento Android nativo JAVA

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para gustavosantosneto@gmail.com com seu CV anexado.
Enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@gustavosantosneto Se essa oportunidade ainda estiver disponível, por favor reabra o _issue_
