### ISSUE TITLE
[Belo Horizonte, MG] Desenvolvedor Android Junior/Pleno | Escola em Movimento S/A

### ISSUE THREAD

**Issue by eem-dev** [androiddevbr/vagas#678]
## Descrição da vaga

Integrar ao time de desenvolvimento focando nas evoluções dos nossos aplicativos Android desenvolvidos em Java e Kotlin. 

## Local

Escritório em Belo Horizonte - Savassi

## Requisitos

- 3 anos de experiência em desenvolvimento de software
- 2 anos de experiência com desenvolvimento Android
- Experiência em desenvolvimento de aplicativos nativos Android (Java e/ou Kotlin)
- Experiência com ferramentas de versionamento de código e desenvolvimento colaborativo (ex.: GitHub, Bitbucket etc);
- Experiência com apis REST/JSON, apis de persistência de dados.
- Experiência arquiteturas MVC e MVP.
- Bom conhecimento teórico e em lógica de programação.
- Curso superior concluído ou nos últimos períodos em Ciências da Computação, Engenharias, Sistemas de informação ou áreas afins.

## Contratação

CLT Full
Vale Refeição - R$ 21,00/dia
Vale Transporte ou Vale Combustível
Plano de saúde Alianz 

## Nossa empresa

A Escola em Movimento é uma empresa de tecnologia focada em melhorar a comunicação de escolas com pais e alunos por meio de aplicativos. Atuamos em todo o Brasil e também no exterior, e somos os líderes do setor. É apaixonado por tecnologia e inovação? Venha fazer parte do nosso time.

## Como se candidatar

Por favor envie um email para vagas@escolaemmovimento.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@eem-dev Se essa oportunidade ainda estiver disponível, por favor reabra o _issue_
