### ISSUE TITLE
[Düsseldorf, Germany] Software Engineer - Android | Trivago

### ISSUE THREAD

**Issue by zhenleiji** [androiddevbr/vagas#679]
## Descrição da vaga

Do you have proven Android app development credentials to match your passion for creating world-class products? trivago is determined to ensure their global hotel search platform gives users a mobile experience that is unrivaled. We believe in achieving innovation through constant experimentation and are seeking an experienced software engineer with the passion and expertise to help push us to greater heights. If you think you can drive trivago's Android app to the next level, apply today!

## Local

Düsseldorf, Germany

## Benefícios

- The opportunity for self-driven individuals to have a direct impact on the business.
- The freedom to embrace small-scale failures as a path to large-scale success.
- The belief that factual proof is the word of truth and determines the way forward.
- The chance to develop personally and professionally due to a strong feedback culture and access to training and workshops.
- A unique culture with a strong sense of community and an agile, international work environment.
- The chance to develop personally and professionally due to a strong feedback culture and access to training and workshops.
- Flexibility for all talents to contribute value and maintain a healthy work-life balance.
- A state-of-the-art campus with world-class ergonomics that supports your health and happiness, 30+ sports and a multi-cuisine cafeteria to satisfy your inner foodie.
- To find out more about life at trivago, follow us on social media @lifeattrivago.
- To learn more about tech at trivago, check out our blog: https://tech.trivago.com

### What you'll do:

- Develop trivago's Android app by working cross-functionally and using the latest technologies
- Use your expert knowledge to bring fresh new ideas to the table
- Analyse feature requests and then plan & implement them test-driven
- Working effectively with a mature code base you will debug and break down big architectural problems
- Exchange ideas, share your knowledge with the rest of the team and participate in pair programming

### What you'll definitely need:

- Burning love for the Android and Google ecosystems. You enjoy fancy apps and can't wait to install every new developer preview
- 2-3 years' experience in native Android app development
- A bachelor's degree in Computer Science, Software Engineering, IT or a similar field
- Experience in dealing with the Android SDK, design patterns and software architecture
- A genuine interest in agile development processes
- To be an excellent team player who believes great teamwork is at the heart of all great products
- To speak English (our company language) fluently

### What we'd love you to have:

- Code references that you can share with us
- Familiarity with Kotlin, TDD, Dependency Injection, Reactive Programming and Continuous Integration
- Challenging attitude to always find beautiful solutions for requirements specific to the Android platform

## Como se candidatar

https://stackoverflow.com/jobs/232940/software-engineer-android-trivago-nv

**Comment by jpventura** [comment]
Hi, @zhenleiji! How are you? Do you also offer visa sponsorship and cover the relocation costs?

**Comment by zhenleiji** [comment]
Olá @jpventura, eles oferecem visa sponsorship e relocation costs. Quanto ao nível eles querem mais pleno ou sênior.

**Comment by jpventura** [comment]
@zhenleiji Se essa oportunidade ainda estiver disponível, por favor reabra o _issue_
