### ISSUE TITLE
[Osasco, SP] - Desenvolvedor Android Sênior - Foursys

### ISSUE THREAD

**Issue by marceloreis13** [androiddevbr/vagas#68]
[SP - Osasco] Foursys - Desenvolvedor Android Sênior
## Empresa

Somos uma empresa de serviços de TI com 15 anos de atuação no mercado, focada no desenvolvimento de soluções customizadas, consultoria de TI, Outsourcing, Body Shop e treinamento, para atender as demandas de seus clientes.

Provedora de soluções, consolida sua marca entregando projetos com qualidade e respeitando os prazos acordados com seus clientes.

Utilizamos as melhores práticas de mercado para desenvolvimento de software, atuando em todo ciclo de vida do projeto com profissionais capacitados, que utilizam seus processos baseados na metodologiaRUP (Rational Unified Process) e a gestão dos projetos baseados no PMI (Project Management Institute), o que garante alto grau de satisfação de seus clientes.
## Descrição da vaga

Atualmente a **Foursys** tem uma oportunidade para Desenvolvedor Android, para trabalhar alocado dentro do Bradesco em Osasco (Cidade de Deus).

Você será responsável por desenvolver e dar manutenção em versões Android de aplicativos novos e legados.
## Posição

Sênior.
## Tipo de contratação

Presencial, alocado no Bradesco (Cidade de Deus/Osasco)
CLT-Flex
###### Obrigatórios
- Experiência em desenvolvimento (+5 anos)
- APIs RESTful e/ou Webservices
- Familiaridade com Fragments
- Familiaridade com Runtime permissions
- Conhecimento de Material Designer
- Customizações de Layouts
###### Desejáveis
- Conhecimento de metodologias ágeis
- Experiência com Retrofit, Picasso, ORMLite, ButterKnife
- Conhecimentos em BDD e TDD
- Ter participado de comunidades, grupos de discussões, eventos e afins (online ou não) relacionadas ao desenvolvimento de software
## Como aplicar

Por favor envie um email para jonny.bergara@foursys.com.br com seu CV anexado - enviar no assunto: Vaga Dev Android Sênior

**Comment by walmyrcarvalho** [comment]
@marceloreis13 Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!
