### ISSUE TITLE
[Rio de Janeiro, RJ] Homer Parcerias Imobiliárias - Desenvolvedor(a) Android Pleno/Sênior

### ISSUE THREAD

**Issue by Mutaquiha** [androiddevbr/vagas#680]
## Informações importantes:
O Homer é a maior e mais segura rede de parcerias para corretores de imóveis. Milhares de corretores em todo o Brasil já estão melhorando
a sua forma de trabalhar com o Homer. Startup de 2 anos e meio com uma equipe robusta e unida que busca transformar o mercado imobiliário.
Quer entrar pra esse time?

Estamos buscando uma pessoa incrível para fazer parte do nosso time Android e melhorar ainda mais nosso produto.

## O que estamos buscando:
- Disciplina
- Foco em Resultado
- Senso de Dono

## Atividades:

• Implementação de features usando SDK Android
• Identificação de problemas, riscos e fazer a gestão dos mesmos quando apropriado
• Promover e defender as melhores práticas de código dentro da equipe

## Experiência:
• 4 anos de experiencia desenvolvendo aplicativos android.
• Conhecimento profundo do SDK Android.
• Proficiência em Java.
• Experiência com Git.
• Conhecimento de bibliotecas  Android como Retrofit.
• Experiencia com RESTful API.

## Diferenciais:
• Ter algum aplicativo publicado na play store
• Conhecimento de testes unitários e testes instrumentados
• Experiencia com ferramentas de integração contínua.

## Local:
- Escritório na Barra da Tijuca, RJ, Avenida das Américas.

## Benefícios:
- Possilidade de receber Stock Options, de acordo com desempenho.
- Regime PJ.
- Horários Flexíveis

 Entrar em contato pelo email: vagas@homer.com.br
 Assunto: *Vaga Android*

**Comment by jpventura** [comment]
@Mutaquiha Se essa oportunidade ainda estiver disponível, por favor reabra o _issue_
