### ISSUE TITLE
[Barra Funda, SP] Desenvolvedor Android (SR) | Tocalivros

### ISSUE THREAD

**Issue by marcelocamps** [androiddevbr/vagas#686]
## Descrição da vaga
Desenvolvedor que ira cuidar de todo o desenvolvimento mobile da Tocalivros. (Foco em Android)
Buscamos uma pessoa pró-atividade, hands-on, com alta capacidade de trabalho em equipe, 
engajamento e focado em metas, para trabalhar full-time na equipe.

## Local

Av. Ordem e Progresso 115, na Barra Funda São Paulo

## Benefícios

- Almoço em loco pago
- 1 horas de almoço
- Estacionamento incluso
- Horario flexivel

## Requisitos
- Kotlin
- Google Cloud
- Clean archtecture
- Mvp
- Rxjava
- Sqlite
- Firebase 
- 3+ anos de experiência com Android

Desejáveis
- Ioc (injeção de dependência)
- Materal design
- Push notification
- Notification manager

## Contratação

PJ a combinar

## Nossa empresa

A Tocalivros é a maior produtora e distribuidora de audiolivros do Brasil. Trazemos livros em formato Audio para qualquer um ouvir como um podcast ;)

## Como se candidatar

Por favor envie um email para marcelo@tocalivros.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@marcelocamps Se essa oportunidade ainda estiver disponível, por favor reabra a _issue_ 😉
