### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android [PLENO] | SYSMAP SOLUTIONS

### ISSUE THREAD

**Issue by Molladri1** [androiddevbr/vagas#687]
Venha fazer parte do tome vencedor da Sysmap! Envie seu currículo com pretensão salarial e disponibilidade para adriana.moll@sysmap.com.br. Compartilhem!

Vaga de DESENVOLVEDOR ANDROID para SP (Urgente!!!)
#vemprasysmap

## Local

Escritório São Paulo - Av. Paulista

## Requisitos

Competências Técnicas:	
Experiência em orientação a objetos, padrões de projeto (design patterns) e arquitetura de software;
Expertise em desenvolvimento em aplicações Android;
Liguagem de programação Kotlin;
Desenvolvimento utilizando APIs e Mock;	
OWASP Mobile Project;
12 Factor App;
GitFlow;
TDD;
Conhecimentos em bibliotecas complementares Android e Google Play Services, RxAndroid, Dagger, Gson, SQLite, Okhttp, Picasso;
Conhecimentos práticos com repositórios Git e integração de RESTful APIs e OOP e OOAD;
Atuando com desenvolvimento Ágil.

## Contratação

A combinar

## Como se candidatar

Por favor envie um email para adriana.moll@sysmap.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@Molladri1 Se a oportunidade ainda estiver disponível, por favor reabra o _issue_ 😉
