### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android [PLENO, SENIOR] | Looke

### ISSUE THREAD

**Issue by thaishbrasil** [androiddevbr/vagas#688]
# Sobre o Looke
Somos a mais completa  plataforma de Streaming do mercado Brasileiro 
Trabalhamos com opções de assinatura, locação e compra de conteúdos em Vídeo.
Oferecendo mais de 14.000 vídeos, incluindo filmes recém-saídos dos cinemas, clássicos, shows, documentários, séries exclusivas e os mais queridos conteúdos infantis,  levando diversão para todos os targets.
O Looke tem parcerias com grandes empresas  de diversos segmentos, levando sempre as melhores experiências para seus usuários

## Descrição da vaga
Com o que você vai trabalhar: 
Desenvolver aplicativos para Streaming de Videos em dispositivos com sistema operacional Android. 

**Atividades**: 
Construir aplicações para Android utilizando Java / Kotlin
Implementar mockups do time de design, com atenção aos detalhes visuais e compatibilidade entre devices;
Priorizar e tratar bugs e exceções reportados em produção;
Contribuir em decisões de arquitetura sobre novas partes do projeto
Integração com banco de dados, integrações com APIs RESTful

## Local
Alameda dos Maracatins - Moema - Zona Sul - São Paulo - SP

## Benefícios
Nós oferecemos uma estrutura competitiva de salários e benefícios alinhada com os mercados locais:
Seguro Saúde, Odontológico e de Vida de Primeira linha
VT/VR 
Bônus Salarial por Performance pago 1x no ano
Escola de Inglês na empresa
no dress code
Frutas, Snacks, Ginástica Laboral e programas de incentivo e suporte de Qualidade de vida
Gostamos de comemorar com festas 1x ao mês no nosso Ambiente de trabalho

## Requisitos Obrigatórios
Ter pelo menos 3 anos de experiência com desenvolvimento de softwares 
Ter pelo menos 1 ano de experiência com desenvolvimento Android.
Ter experiência com desenvolvimento de apps nativo  
Sólidos conhecimentos em Java e ter conhecimentos em Kotlin
Dominar o Git Flow 
Dominar o processo de deploy (Google Play Store)
Dominar a especificação do Material Design 

## Diferenciais Desejáveis (não obrigatório)
Conhecimentos em desenvolvimento iOS com o objetivo de potencializar a curva de aprendizado dentro do nosso ambiente de desenvolvimento

Dominar técnicas de testes automatizados com Espresso e JUnit 
Experiência com ferramentas de integração continua 
Gradle
Familiaridade com processo de desenvolvimento de software ágil (como XP, Scrum e Kanban)
Experiência com desenvolvimento multiplataforma (Flutter, Xamarim, Cordova, Phonegap)

## Contratação

CLT à  combinar

## Nossa empresa
Nossa Cultura: 
Somos uma empresa jovem inspirada em tecnologias disruptivas.  Oferecemos um ambiente de trabalho que Incentiva a inovação e a produtividade, garantido liberdade com responsabilidade.

O Looke é uma Plataforma brasileira. Multiplataforma.
Temos aplicativos de iOS, Android, TV conectada, Playstation, PC, Safari, Apple TV, Android TV. 
Tudo isso a gente faz aqui. A gente faz a plataforma inteira.
Fazemos toda a parte de Encriptação, Decriptação, Encoding de vídeo.
100% dessa tecnologia, é nacional, proprietária da empresa e, é feita toda aqui com a gente. 
Você, se vir a ser contratado, virá para trabalhar numa área específica de Android para atender essa plataforma. 
O Streaming de Vídeo é o futuro da distribuição de Vídeo pela internet. O que a gente conhece hoje de distribuição linear de TV, aqueles canais que a gente contrata, isso vai acabar. 100% está se tornando internet. Está se tornando no mundo inteiro. Como a Netflix fez isso, a Amazon Prime, o próprio Itunes, o Google Play...
É com isso que a gente quer que você venha trabalhar. 
Distribuição de Vídeo por internet. 

## Como se candidatar
Envia CV para : vagas@looke.com.br

**Comment by jpventura** [comment]
@thaishbrasil Se a oportunidade ainda estiver disponível, por favor reabra o _issue_ 😉
