### ISSUE TITLE
[Stockholm, Sweden] Senior Android Developer - Truecaller

### ISSUE THREAD

**Issue by careerslab** [androiddevbr/vagas#69]
## Descrição da vaga

Being one of the key roles in our Mobile Engineering team, you are deeply involved in the whole cycle of product development on Android. Your challenge will be to apply software craftsmanship as well as to identify and lead larger refactoring and improvement initiatives. Everything you release will reach 70+ millions of Android users, which require a strong focus on usability. You will be developing for several devices together with your team, and also drive cross-team technical initiatives. Implementation of complex features and design work are also things that you will be highly involved in.
## Local

Stockholm, Sweden
## Benefícios
- full relocation support (finding a flat, visa, plane tickets, language courses etc.)
- friendly, lean, international working environment 
- lab / creativity days
- working on a truly global app with over 200mln users
- beautiful, spacious office right in the heart of Stockholm
- lots of benefits (daily breakfasts in the office, exclusive gym package, language courses, extra private healthcare insurance)
- great compensation package 
- private pensions package 
## Requisitos
- 5+ years extensive experience with Android SDK, development tools, application lifecycle, asynchronous server communication, and UI components
- Ability to play the role of tech lead on complex projects as well as consult on architecture
- Experience from UI testing frameworks such as Espresso
- Experience of agile development, TDD and Continuous Improvement
- Fluent English skills, oral and written (required)
## Nice to have:
- Knowledge of other languages like C++, C#, Objective-C
## Contratação

Full time employment. 
## Nossa empresa

Truecaller is changing the way hundreds of millions of people interact with each other every day. It is a unique, multi-platform app, that is transforming your phone to make it more intelligent and useful. With over 200 mln active users, 140 million identified phone calls per day (or 1500 identified phone calls per second) and a database of 2.2 billion phone numbers they are handling big data, solving big challenges and having big fun. The team's focus is always on the user (+4.5 stars in both Google Play and in the App Store). Today, Truecaller is around 80 diverse employees in an agile organization with more focus on the product and our users than on processes and policies. They're backed by some of the most prominent investors in the world such as Sequoia Capital, Atomico, and Kleiner Perkins Caufield & Byers.  
## Como se candidatar

Por favor envie um email para agata@careerslab.co com seu CV/LinkedIn anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@careerslab Is this position still open? If not, I'll close it just for organization purposes. :)
