### ISSUE TITLE
[SÃO PAULO] Desenvolvedor(a) Moblie Android / IOS [AUTOPASS]

### ISSUE THREAD

**Issue by aline-navarro** [androiddevbr/vagas#690]
## Descrição da vaga

Programa, codifica e testa nas plataformas Android e/ou iOS. Executa a manutenção dos sistemas, fazendo eventuais correções necessárias, visando atender às necessidades dos usuários. Desenvolve trabalhos de montagem, depuração e testes de programas, executando serviços de manutenção nos programas já desenvolvidos.

## Local

São Paulo - Vila Olímpia (local)

## Requisitos

* Desenvolvedor Mobile ANDROID e IOS
* GIT;
* Conversão de design;
* Testes;
* Conhecimento em Metodologias ágeis;
* React Native (Imprescindível)

Diferenciais
* Desenvolvimento NATIVO iOs ou Android com swift.

## Contratação

PJ 

## Nossa empresa

A Autopass é uma empresa de tecnologia, soluções e serviços associados à mobilidade urbana.

## Como se candidatar

Envie um email para aline.navarro@keepsimple.com.br com seu CV - enviar no assunto: Vaga Moblie Android / IOS AUTOPASS

**Comment by jpventura** [comment]
@aline-navarro Se a oportunidade ainda estiver disponível, por favor reabra o _issue_ 😉
