### ISSUE TITLE
[Vila Olímpia, SP] Desenvolvedor Android - Gold 360

### ISSUE THREAD

**Issue by JulianaGold360** [androiddevbr/vagas#691]
## Descrição da vaga

- Criar e manter aplicações nativas Android (Java)
- Converter aplicações para Kotlin
- Corrigir crash's reportados no Firebase

## Local

Vila Olímpia

## Benefícios

VR de 770/mês, VT, assistência médica e odontológica, descontos em instituições de ensino, PLR de até 1 salário e seguro de vida. 
Frutas todos os dias, geladeira com refrigerantes e sucos, e bolo dos aniversariantes do mês.

## Requisitos

- Consumo de API's RESTful
- Ferramentas de versionamento de código e desenvolvimento colaborativo (ex.: GitHub, Bitbucket etc)
- Principais funcionalidades do Android SDK
- Bibliotecas complementares, Gson, SQLite, Okhttp, Picasso
- Inglês intermediário

Desejáveis

- Firebase (Crashlytics/Notifications)
- In-App Purchases
- Node.js
- Kotlin

Diferenciais

- Conhecimento em testes
- Atualizar-se constantemente das tecnologias e padrões de mercado
- Ter participado do desenvolvimento de aplicativos de grande relevância
- Conhecimento do mercado de Telecom e SVAs
- Conhecimento do universo de publicações digitais

## Contratação

CLT

## Como se candidatar

Quer participar da seleção? Mande seu currículo atualizado e pretensão salarial para juliana.castro@gold360.com.br, com assunto Android.

**Comment by jpventura** [comment]
Olá, @JulianaGold360! A vaga é pra Gold 360 ou vocês uma empresa de recrutamento?

**Comment by JulianaGold360** [comment]
@jpventura Olá! Oportunidade para atuar na Gold360.

**Comment by jpventura** [comment]
@JulianaGold360 junior, pleno ou senior?

**Comment by jpventura** [comment]
@JulianaGold360 Se essa oportunidade ainda estiver disponível, por favor reabra a _issue_ 😉
