### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android [PL|SR] | CloudWalk

### ISSUE THREAD

**Issue by lupape** [androiddevbr/vagas#693]
## Descrição da vaga

A CloudWalk é uma rede de pagamentos inteligente que processa crédito, débito e oferece dezenas de outros produtos para a indústria de pagamentos. Provemos insights aos nossos clientes usando Deep-Learning e liquidamos transações em tempo real com Blockchain. Procuramos alguém focado em resultados para fazer parte do nosso time atuando como Desenvolvedor Android. Uma pessoa que anseie por participar da construção de um grande sonho. Valorizamos habilidades colaborativas e vontade de aprender.

## Principais atividades

- Programação do aplicativo nativo Android usado pelos usuários da Cloudwalk
- Elaborar soluções para problemas diversos junto com a equipe de produto e as demais áreas da empresa
- Elaborar documentação técnica das funcionalidades desenvolvidas;
- Programação de testes unitários e automatizados
- Automatizar tarefas repetitivas e sujeitas a erros
- Contribuir para a melhoria contínua da arquitetura de aplicação e dos processos de desenvolvimento

## Requisitos

- Contribuição open source no github em Kotlin e/ou Java;
- Pelo menos 2 anos de experiência em programação Android;
- Experiência em Android Support Library e Material Design;
- Sólidos conhecimentos em programação orientada a objetos, padrões de projeto e engenharia de software;
- Experiência com GIT;
- Conhecimentos de AWS;
- Inglês Fluente;

## Diferencial

- Experiência com device tracking, geofencing, GCM, Firebase, Okhttp, Retrofit, Butterknife, Dagger, RxJava e Reactive ;
- Conhecimento em Bluetooth
- Ter trabalhado com ferramentas de build e automação, como o gradle, Jenkins;
- Familiaridade com o processo de distribuição do Google Play,
- Conhecimento para desenvolver em IOS

## Local

Escritório São Paulo - Vila Olímpia

## Benefícios

- Vale alimentação
- Vale transporte
- Seguro Saúde para você e mais um dependente 

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para carrers@cloudwalk.io com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@lupape Por favor, reabra o _issue_ se a vaga ainda estiver disponível.
