### ISSUE TITLE
[Consolação, SP] Desenvolvedor Android | Grupo ZAP

### ISSUE THREAD

**Issue by alexnavarro** [androiddevbr/vagas#694]
### No Grupo ZAP você vai:
- Trabalhar com uma equipe de alto nível que busca sempre se desenvolver utilizando as melhores práticas e ferramentas
- Realizar Pair Programming com membros da equipe
- Projetar e desenvolver aplicativos/features sempre atento à qualidade, aprimorando assim a experiência dos nossos usuários
- Estar envolvido diretamente com métricas e testes A/B para proporciar sempre o melhor resultado
- Participar de guildas, tech talks e outros, com foco em evoluir as práticas de engenharia do seu time, distribuindo conhecimento entre toda organização, aumentando o nível das práticas de todos.
- Trabalhar próximo às áreas de Produto/UX, criando soluções para melhorar a experiência e atender as necessidades dos nossos usuários
- Gerenciar as lojas dos aplicativos (App Store / Play Store)

## Local

Rua Bela Cintra (região da Paulista)

## Benefícios

- Salário compatível com o mercado
- Academia (Gympass)
- Vale Refeição
- Plano de Saúde, Odontológico e Seguro de Vida
- Incentivo à Educação
- Home office (até 2 vezes por semana)
- Bônus anual
- Frutas no escritório
- Acompanhamento de carreira (com 1:1's e PDI - plano de desenvolvimento inividual)

## Requisitos

- Desejável experiência com mobile development e de preferência ter trabalhado em projetos relevantes usando linguagens modernas
- Conhecimento em arquitetura de software e boas práticas de desenvolvimento
- Desejável competente conhecimento em Kotlin ou Swift 
- Atenção aos detalhes de UI
- Atenção com a qualidade e padronização do código, garantindo legibilidade, escalablidade e performance
- Capacidade de elaborar testes unitários e de integração
- Desejável conhecimento em CI/CD
- Conhecimento em ferramentas de debugging e profiling, assim como comportamentos e bugs específicos de certas versões e devices.

## Contratação

CLT

## Nossa empresa

No Grupo ZAP temos o objetivo de auxiliar os consumidores na busca pelo imóvel ideal. Com a maior base de dados do mercado imobiliário, desenvolvemos produtos, inteligência, serviços e informações que geram ganhos e decisões assertivas para todos agentes envolvidos.

Estamos presentes em todo o brasil, com 26 escritórios espalhados pelo país. Mensalmente, geramos 4 milhões de contatos de interessados para 7 milhões de anúncios de imóveis e recebemos por volta de 40 milhões de visitas - a maior audiência qualificada do mercado.

Para nos ajudar a transformar o mercado imobiliário estamos procurando para nosso escritório de São Paulo desenvolvedores Mobile iOS e Android que estejam dispostos a viver essa mudança com a gente.

## Como se candidatar

Abra neste [link](https://jobs.kenoby.com/engenhariaeproduto/job/engenheir-mobile-android/5bf6ac81eb90c707b04398bf) e siga as intruções para se aplicar

**Comment by jpventura** [comment]
@alexnavarro junior, pleno ou senior?

**Comment by alexnavarro** [comment]
@jpventura não foi especificado pois estamos contratando de todos os níveis.

**Comment by caiodev** [comment]
O link para aplicação está quebrado

**Comment by lucasbrandaodossantos** [comment]
O link para candidatura está quebrado, teria algum e-mail direto para enviar o currículo?

**Comment by jpventura** [comment]
@alexnavarro Por favor, reabra o _issue_ se a vaga ainda estiver disponível.
