### ISSUE TITLE
[RJ / Remoto] Stone - Android Engineer (Pleno/Senior)

### ISSUE THREAD

**Issue by ubiratansoares** [androiddevbr/vagas#695]
## Sobre a Stone

Somos uma empresa de tecnologia que atua no mercado de pagamentos, lutando para servir o nosso cliente e provar que há uma maneira mais justa, pessoal e inteligente de fazer negócio.

Estamos crescendo em um ritmo forte e assumindo desafios cada vez maiores e mais difíceis. Queremos nos tornar os melhores em serviços aos clientes e construir um negócio grande: em receita, colaboradores e pessoas impactadas.

## Sobre a área de Banking

Somos uma _Business Unit_ da Stone voltada para o desenvolvimento de novos produtos financeiros focados em melhorar ainda mais a vida do **verdadeiro** empreendedor brasileiro. Queremos - e iremos! - construir um banco sem banqueiros.

Nosso foco é em PJ. Queremos mudar a forma como lojistas gerenciam as finanças dos seus negócios e realizam suas operações bancárias. Para isso, contamos com um time fora da curva e distribuído por diversas cidades do Brasil (sim, somos um time remote-first!). Além disso, não temos medo de inovar na tecnologia para entregar os melhores produtos!

Nossa stack é baseada principalmente em Elixir no back-end (gostamos de python também), React e Elm no front-end, serviços na AWS e GCP e apps nativos com Kotlin (Android) e Swift (iOS) .

## Sobre a vaga

Estamos em busca de Android Developers (Pleno e Sênior) para se juntar ao nosso time de mobile e nos ajudar a construir apps incríveis!

## Sobre a contratação

A contração será em regime CLT full, com possibilidade de trabalho 100% remoto, ou presencial no Rio de Janeiro (centro).

## O que não pode faltar?

- Experiência com Kotlin;
- Capacidade de produzir código limpo e de fácil manutenção;
- Curiosidade para aprender, ler e estudar;
- Motivação por aprendizado contínuo;
- Capacidade de se comunicar de forma concisa, franca e clara (também por escrito);
- Facilidade de trabalhar com equipes remotas;
- Capacidade de motivação em ambientes dinâmicos.

## O que aumentam suas chances?

- Experiência com publicação de aplicações na Play Store;
- Experiência com testes automatizados (unidade, integração, funcionais de aceitação, E2E);
- Experiência com produtos digitais financeiros ou apps de larga escala;
- Ter/contribuir com projetos open-source no Github;
- Experiência com Continuous Integration e Continuous Delivery para Android;
- Vivência e opinião crítica sobre mais de um padrão de arquitetura para composição das responsabilidades da aplicação no contexto de Android (MVP, MVVM, MVI, etc);
- Noções sólidas de programação reativa funcional (usamos RxJava);
- Domínio de alguns dos principais frameworks open-source amplamente adotados pela comunidade Android em aplicações modernas;
- Noções de engenharia de segurança aplicada a Android;
- Experiência com ferramentas de métricas e de marketing aplicadas a Mobile (GA, Mixpanel, Localytics, Firebase, etc)

## Como se candidatar

Se candidate no [Kenobi](https://jobs.kenoby.com/stone/job/android-developer-banking/5ace5cc786b5e113c5a9ec1e)

Maiores dúvidas comentar aqui na issue, ou me pingue em private no Slack 🚀

**Comment by lucas-inatel** [comment]
Olá @ubiratansoares essa vaga ainda está disponível ou já foi preenchida?

**Comment by ubiratansoares** [comment]
@lucas-inatel Ainda está disponível
