### ISSUE TITLE
VAGAS DEV ANDROID (SR) | K2 PARTNERING

### ISSUE THREAD

**Issue by natashacosta** [androiddevbr/vagas#698]
Essa vaga foi removida por não atender as [especificações do grupo de Android Dev BR](https://github.com/androiddevbr/vagas/blob/master/README.md).

Se ela for reeditada atendendo as regras descritas no [README](https://github.com/androiddevbr/vagas/blob/master/README.md), teremos prazer em aprová-la :smile:

**Comment by jpventura** [comment]
@natashacosta  Os [termos de uso](https://github.com/androiddevbr/vagas/blob/master/README.md) são claros com relação a postagem de vagas por partes de recrutadores e agências de empregos: *é necessário divulgar o nome da empresa onde o candiato irá atuar*.
