### ISSUE TITLE
[Helsinki/Tampere, Finland] Senior Mobile Developer | Futurice (Apply until April)

### ISSUE THREAD

**Issue by pedpess** [androiddevbr/vagas#699]
## Descrição da vaga

We at Futurice are looking for a darn cool person to join us in the journey of becoming a leader in a world beyond digital. We are a family of companies working together to shape the future. We also look forward to defining the ways human and machines co-operate. The journey is about to start for you when you come to work with us, so who do you wanna become? Let us know!

If you're looking for a new challenge. If you have a desire to work and collaborate with the best developers and designers out there and want to have colleagues with whom you can have meaningful conversations about technology and the world around them. All team members need to be ambitious self-starters and have a desire to be part of a workplace with a lean, flat structure. Individuals are constantly given the opportunity to learn and grow in collaboration with wonderfully nice and extremely talented people.

## Local

Helsinki and Tampere, Finland

## Benefícios

 - Flex hours, 
 - Up to 30 hours per month payment of your free time if you contribute to [Open Source and Social Impact](https://spiceprogram.org/) activities
 - Darn cool offices in the heart of Helsinki and Tampere 
 - A part of your lunch is paid by us!
 - Recreational bonus per year
 - Social clubs (Runners, gamers, beer/wine/whisky tasters et al)
 - EBIT (Participação de Lucros e Resultados)
 - Home care (aka nanny) for your sick child if you still insist you want to come to work instead. The nanny is paid by us!
 - Futuhike is the chance you can get to work (paid by us - flights/accomodations) for 1 week per year in one of our other offices (Oslo, Berlin, Munich, London, Stockholm, Helsinki, Tampere) and get to know your colleagues that you usually see just via video.
 - Much more...

## Requisitos

Our primary goal is to find a person with strong iOS and/or Android skills and a passion for mobile development and creative problem-solving. We don't want a very narrow-focused person who only wants to work on one platform, but rather a developer with an interest in beautifully written code and great quality apps. In fact, having some experience from other mobile platforms (iOS/Android), modern cross-platform frameworks (e.g. React Native, Flutter, Xamarin) or modern web development would be a nice plus, since the situations and needs change quickly in today’s business environment.

We expect you to have the skills to deliver commercial grade applications for mobile devices. One of the best ways to demonstrate this is to show us the App Store and Google Play references together with a description of your own role in creating those published apps.

As a senior person in general, we also have the intention that you will be willing to challenge teammates and clients to be the best version of themselves in a positive way. Even if you don't know how, we are here to help you my friend! ;)

## Contratação

 - Full-time employment 

## Nossa empresa

[Futurice](https://www.futurice.com/about)

### We do:

 - We assume good intentions. if we disagree, we also try to understand why.
 - We respect other and opposing opinions in our speech and actions.
 - We always attempt collaboration before a conflict.
 - We focus on our actions instead of (non-)actions of others.
 - We are mindful of our fellow people by supporting inclusion in choosing the language we use.

### We don't do:

 - We don’t accept violence, threats of violence, or violent language directed against another person.
 - We don’t tolerate unwelcome comments regarding a person’s personal life choices or practices.
 - We will not tolerate discriminatory actions, language or jokes – particularly those related to gender, sexual orientation, race, religion or disability.
 - We will not tolerate unwelcome sexual attention including sexualized comments or jokes.

## Como se candidatar

 - [Senior Mobile Developer - Helsinki Office](https://www.futurice.com/open-positions/senior-mobile-developer-helsinki)
 - [Android Developer - Tampere Office](https://www.futurice.com/open-positions/ios-or-android-developer-tampere/)
 - [React Native Developer - Tampere Office](https://www.futurice.com/open-positions/react-native-developer-tampere/)

Any doubts, please hit me an email (pedro.pessoa@futurice.com). Also, hit me a message on AndroidDevBr Slack for further quick/informal doubts.

**Comment by jpventura** [comment]
@pedpess This issue has being inactive for over 3 months. If the job opportunity is still available, please comment **Opportunity still available**.
