### ISSUE TITLE
[Botafogo, Rio de Janeiro] Desenvolvedor Android / Mobicare

### ISSUE THREAD

**Issue by MobiSelecao** [androiddevbr/vagas#702]
## Descrição da vaga

Participar de todo o ciclo de desenvolvimento de aplicativos, desde a fase de análise da solução até a entrega e manutenção do projeto;
Trabalhar com outros desenvolvedores de alto desempenho em um ambiente colaborativo.

## Local

Botafogo - Rio de Janeiro

## Benefícios

Horário flexível
Plano de saúde- Bradesco
Plano Odontológico – Bradesco 
Vale-Transporte 
Vale-Refeição e / ou Alimentação (flex) 
Curso de inglês e /ou espanhol (Dentro do nosso programa de curso de idiomas ministrado internamente)
Bônus
Política de trabalho remoto (Home Office).
Cursos e palestras para o desenvolvimento de carreira

## Requisitos
Estudante ou formado em Ciências da Computação, Análise e Desenvolvimento de sistemas, Sistema de Informação e ou áreas correlatas;

Conhecimentos em:
•	Forte conhecimento do Android SDK e das diferentes versões do Android;
•	Padrões de UI do Android, princípios de design, padrões e melhores práticas;
•	Libs open-source mais utilizadas para Android;
•	Android Studio / Gradle;
•	Familiaridade com ferramentas de versionamento (Git/SVN);
•	Familiaridade com RESTful webservices;
•	Testes automatizados;
•	Testes de UI;
•	API’s do Google Services (maps, analytics, GTM, GCM etc);
•	Metodologias ágeis;
•	Inglês técnico;

Vivência com:
•	Armazenamento off-line, threading e melhora de performance;
•	Push notifications / FCM;
•	Material Design;
•	Contribuição em projetos open source;
•	Ter ao menos um aplicativo desenvolvido (não necessariamente publicado no Google Play);
•	Saber lidar com diferentes tamanhos de tela;

## Contratação

CLT

## Como se candidatar

Entre na nossa página de carreira e faça a sua inscrição na vaga de interesse: https://jobs.kenoby.com/mobicare

**Comment by jpventura** [comment]
@MobiSelecao @pess0a Por favor, reabra a _issue_ se a vaga ainda estiver disponível.
