### ISSUE TITLE
[Rio de Janeiro, RJ] Desenvolvedor Android (Pleno/Sênior) - Ubook

### ISSUE THREAD

**Issue by rafsouzap** [androiddevbr/vagas#704]
### Sobre a Ubook
Somos uma empresa brasileira de streaming de audiobooks, ebooks, podcasts, jornais e revistas. Com uma base de 6 milhões de usuários registrados e mais de 15 mil títulos no catálogo, estamos crescendo em um ritmo forte e acelerado, assumindo desafios cada vez maiores, expandindo nossos serviços para mais países da América Latina e Europa.

### Sobre a vaga
Estamos em busca de desenvolvedor Android (Pleno e Sênior) para se juntar ao nosso time de mobile e nos ajudar a construir apps incríveis, que tenha vontade de fazer parte de uma empresa que está mudando o mundo com suas novas tecnologias. 

### O que esperamos
* Experiência com a plataforma Android e suas APIs
* Experiência com a linguagem Java
* Conhecimento sobre SQLite, Json e Git
* Elaborar código limpo e com estrutura legível e de fácil manutenção (clean code)
* Curiosidade para aprender, ler e estudar
* Motivação por aprendizado contínuo
* Capacidade de motivação em ambientes dinâmicos

**Será um diferencial quem também tiver estes conhecimentos:**
* Otimização de recursos em ambientes embarcados
* Estar atualizado com as tendências e novidades da plataforma para sugestão de melhorias
* Conhecer a linguagem PHP (para depurar problemas na integração, se necessário)
* Conhecer testes unitários
* Conhecer o banco MySQL para validar registros enviados do aplicativo para o backend

**Local:** Barra da Tijuca - Rio de Janeiro/RJ

### Como se candidatar
Para se candidatar, envie seu currículo para o e-mail [vagas.ti@ubook.com](mailto:vagas.ti@ubook.com), mencionando no assunto o nome da vaga: Vaga - Dev Android.

**Labels**
CLT
Presencial
Pleno
Sênior

**Comment by jpventura** [comment]
@rafsouzap @pess0a Por favor, reabra a _issue_ se a vaga ainda estiver disponível.
