### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Flutter | Renda Fixa

### ISSUE THREAD

**Issue by franciswagner** [androiddevbr/vagas#705]
## Descrição da vaga

Estamos recrutando um desenvolvedor Flutter para atuar em nosso aplicativo de investimentos.

## Local

Presencial, São Paulo - Campos Elíseos

## Benefícios

- Plano de saúde
- Gympass

#### Diferenciais

- Horário Flexível
- Snacks à vontade
- Frigobar com cervejas, refrigerantes, sucos e energéticos
- Xbox One para descontração e tirar um contra no PES 2019 :P
- Dress code despojado
- Cafés Nespresso e Dolce Gusto
- Acesso a quase 2000 cursos online pela Udemy, Datacamp
- Acesso a cursos online sobre finanças e investimentos

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento de aplicativos com Flutter/Dart
- Experiência em consumo de APIs
- Conhecimento em animações

**Desejáveis:**
- Conhecimentos de Git
- Conhecimentos de Material Design

**Diferenciais:**
- Conhecimentos de matemática financeira

## Contratação

PJ a combinar

## Nossa empresa

O App Renda Fixa é uma startup da área financeira (Fintech) e nosso propósito é revolucionar o mercado de investimentos no Brasil.

## Como se candidatar

Por favor envie um email para francis@rendafixa.rocks com seu CV anexado - enviar no assunto: Vaga Dev Flutter

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

## Labels

- PJ

**Comment by douglasdrumz** [comment]
Qual o nível de senioridade?

**Comment by franciswagner** [comment]
> Qual o nível de senioridade?

Oi Douglas, precisamos de algum dev que já tenha feito algumas coisas em flutter. Veja que é uma tecnologia bem recente e os devs daqui acabaram aprendendo com a conversão do app em si, mas o principal é que o dev consiga tocar o desenvolvimento de novas funcionalidades e manutenção de nosso app. Atualmente estamos convertendo nosso aplicativo que foi feito em Ionic 1 para o Flutter. Acredito que 80% já esteja convertido, mas o dev precisa ser capaz de dar continuidade nas novas funcionalidades quando substituirmos o app Ionic pelo Flutter.

**Comment by mion23** [comment]
Boa tarde, a vaga é apenas para presencial?

**Comment by franciswagner** [comment]
> Boa tarde, a vaga é apenas para presencial?

Boa tarde, sim, somente presencial.

**Comment by jpventura** [comment]
@franciswagner Por favor, reabra a _issue_ se a vaga ainda estiver disponível.
