### ISSUE TITLE
Desenvolvedor Android e IOS

### ISSUE THREAD

**Issue by acnslak** [androiddevbr/vagas#706]
**Contratação para atuação em desenvolvimento de app Android/IOS**

## Local

Rua: Butantã, 518 - Pinheiro - São Paulo/SP

## Requisitos

Experiência em projetos com as tecnologias:

- Kotlin
- Firebase(Crashlytics)
- GSON
- Banco de dados : Realm
- Requisições : Retrofit
- Arquitetura : MVP
- API : 17
- Layout para diferentes tamanhos de tela
- Versionamento : GitLab

## Contratação

PJ a combinar

## Nossa empresa

A Single Point é uma empresa com mais de 15 anos de mercado. Somos desenvolvedores e comercializamos nosso produto de CRM - Customer Relationship Management em modelo SaaS.

www.singlepoint.com.br

## Como se candidatar

Por favor envie um email para alex.navarro@singlepoint.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@acnslak Por favor, reabra a _issue_ se a vaga ainda estiver disponível.
