### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android (PL|SR) - Serasa Consumidor

### ISSUE THREAD

**Issue by mafabeni** [androiddevbr/vagas#708]
Startup Serasa Consumidor - 02 vagas para Dev Android

Somos uma startup com foco no cliente e temos a missão de ajudar os brasileiros a melhorarem de vida através de nossos serviços digitais. 

## Descrição da vaga
O profissional irá atuar em um time que tem foco no Aplicativo que será lançado agora no final de fevereiro. O time é multidisciplinar, com muita autonomia mas com muita responsabildiade.

## Local

São Paulo - Planalto Paulista - Alameda dos Quinimuras

## Benefícios

- Vale Refeição
- Plano de Saúde
- Previdência Privada
- Gympass
- Bônus e muito mais

## Requisitos

Obrigatórios
- experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados

## Contratação

CLT

## Nossa empresa

Somos uma empresa voltada para o consumidor e queremos revolucionar a saúde financeira dos brasileiros. 

Queremos ser a maior empresa digital do Brasil. Para isso, precisamos de pessoas que pensem tão grande quanto a nós, que não tenham medo de desafios e, principalmente, que joguem junto sempre que necessário. Um ambiente dinâmico, formado por um time que quer transformar a realidade financeira de um país inteiro. Achou desafiador? Isto é o Serasa Consumidor.

Se você se gosta de desafios e tem vontade de trabalhar em um time com um propósito claro e ambicioso, seu lugar é com a gente!

## Como se candidatar

Por favor envie um email para marcelo.fabeni@br.experian.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@mafabeni Serasa Experian ou outra unidade do Serasa?

**Comment by jpventura** [comment]
@mafabeni Por favor, reabra a _issue_ se a vaga ainda estiver disponível.
