### ISSUE TITLE
[Campinas - SP] Desenvolvedor(a) Android (JR|PL|SR) - Venturus

### ISSUE THREAD

**Issue by davirss** [androiddevbr/vagas#709]
## Descrição da vaga

Projeto de desenvolvimento de um app no contexto de meios de pagamentos.

## Local

Global Tech, Campinas - São Paulo (Presencial)

## Benefícios

- Previdência Privada
- Cooperativa de Crédito
- Vale Refeição/Alimentação
- Home Office uma vez por semana
- Planos de Saúde e Odontológico

## Requisitos

Obrigatórios
- Superior completo em Ciências da Computação, Engenharia da Computação e áreas afins.
- Experiência em desenvolvimento de aplicativos mobile.
- Experiência em programação e depuração de código (domínio de orientação a objetos).
- Excelentes conhecimentos em Android
- Inglês intermediário

Diferenciais
- Experiência com Git e Jira. 
- Experiência com aplicações para Meios de Pagamento

## Contratação
CLT ou PJ

## Nossa empresa
Com mais de 20 anos de história, o Venturus conta com uma estrutura apta a encarar qualquer desafio com um mindset inovador

Mais detalhes em: http://www.venturus.org.br/sobre

## Como se candidatar
Aplique para a vaga em: https://jobs.kenoby.com/venturus/job/desenvolvedor-android-jrplsr/5c6db098109508354facea8e

**Comment by jpventura** [comment]
@davirss Por favor, reabra a _issue_ se a vaga ainda estiver disponível.
