### ISSUE TITLE
Analista de Sistemas Pleno (Java)

### ISSUE THREAD

**Issue by srolemberg** [androiddevbr/vagas#71]
## Descrição da vaga

Analista de Sistemas Pleno (Java)

## Local

Local da vaga: (Centro) Rio de Janeiro/RJ/BR

## Requisitos

- Ensino Superior Completo em Informática ou áreas afins;
- Experiência com Spring MVC, JPA, Hibernate, Servlet; 
- Experiência em Java (diferencial Nodejs);
- Experiência com IDE Eclipse, IntelliJ;
- Experiência em Controle de versão (TFS, Git);
- Experiência em integração em soluções SOAP, REST;
- Disponibilidade para viagens.

## Nossa empresa

A Bematech, provedora de soluções completas de tecnologia para o mercado de varejo, food service e hospitality é uma multinacional brasileira líder no mercado de automação comercial no Brasil.
Na Bematech você encontra o cenário perfeito para colocar seu conhecimento em prática e adquirir ainda mais, trabalhando com uma equipe profissional, talentosa, que busca o melhor em tudo o que faz.
Se você também é assim e quer trabalhar em uma empresa que valoriza seus profissionais e oferece todos os recursos para desenvolver o seu plano de carreira, atenção para esta oportunidade.

## Como se candidatar

Faça a candidatura através do link: http://bit.ly/2cwMmS6

**Comment by davidtcdeveloper** [comment]
@srolemberg, este mural é dedicado a vagas para desenvolvedores Android. Agradecemos o interesse, mas fecharemos a issue, uma vez que se trata de uma vaga para Java e não Android.
