### ISSUE TITLE
[São Paulo- SP] Desenvolvedor (a) Android JR / PL / SR | RESOURCEIT

### ISSUE THREAD

**Issue by POLLEZI** [androiddevbr/vagas#711]
## Empresa
Venha fazer parte do time de Inovação Digital da Resource, uma das maiores integradoras digitais do Brasil e uma as empresas de TI que mais crescem no País. Com 25 anos no mercado, multinacional brasileira com presença global, com 21 escritórios em 5 países.
Também está presente no Vale do Silício com um avançado Centro de Pesquisa e Inovação, o que possibilita estar cada vez mais próxima do cliente, entender melhor o seu negócio e oferecer a melhor solução.

## Descrição da vaga
Desenvolvimento de novos aplicativos e melhorias e novas funcionalidades utilizando IOS ou Android Nativo.

## Posição
Desenvolvedor Android

## Tipo de contratação
CLT

## Requisitos
DESENVOLVEDOR ANDROID
ANDROID STUDIO GIT
FIREBASE
CRASHLITYCS

## Benefícios
VR
VT
Convenio Médico
Convenio Odontologico
Auxilio Creche
Convenio Farmácia
Seguro de Vida

## Local
Interlagos – SP - 10 POSIÇÕES
Berrini - SP - 1 POSIÇÃO

## Como aplicar
Por favor envie um cv para natalia.oliveira@resourceit.com ou adriana.pereira@resourceit.com indique um amigo!!!

* enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Olá, @POLLEZI! É a própria Resource IT que contratará o candidato CLT?

**Comment by POLLEZI** [comment]
sim, a própria Resource

> Olá, @POLLEZI! É a própria Resource IT que contratará o candidato CLT?
