### ISSUE TITLE
[São Paulo, Vila Olímpia] Desenvolvedor(a) Android JUNIOR na VEE DIGITAL TECNOLOGIA S.A.

### ISSUE THREAD

**Issue by sergiobr** [androiddevbr/vagas#714]
## Descrição da vaga

**Vaga: Desenvolvedor(a) Junior (Android/iOS)
Tipo: CLT ou a combinar
Experiência: não obrigatória
Formação(Diploma): não obrigatório**

☛ Responsabilidades
⟹ Estar atento(a) à novas tecnologias que podem ser usadas no desenvolvimento dos produtos VEE para aplicá-las em diferentes projetos e situações.
⟹ Participar durante as fases concepção de novos produtos e funcionalidades mobile. Entendimento das regras de negócio e análise de requisitos.
⟹ Colocar em prática as tecnologias e frameworks utilizados através da implementação das funcionalidades.

## Local
Escritório São Paulo - Vila Olímpia

## Benefícios
⟹ Remuneração compatível com o mercado
⟹ Horário flexível;
⟹ Sem dresscode;
⟹ Ambiente descontraído;

## Requisitos
☛ Obrigatórios
⟹ Gostar muito de programar
⟹ Conhecimentos básico de algoritmos e estrutura de dados; ótimo raciocínio lógico e pró-atividade. 
⟹ Inglês intermediário para leitura 

☛ Desejáveis
⟹ Experiência com a linguagem Java
⟹ Experiência com programação Android e/ou iOS
⟹ Experiência com aplicações Web
⟹ Familiaridade com ambiente Linux

☛ Diferenciais
⟹ Ter cursado Técnico em Informática ou correlatos
⟹ Noções de Kotlin, ObjC e Swift
⟹ Experiência com tecnologias cross-platform (Flutter, React Native, Ionic, Phonegap)

☛ Soft skill
⟹ Excelente trabalho em equipe 
⟹ Desapego por tecnologias (“explain to me like I’m five years old”: procuramos uma pessoa que não seja apegada a qualquer linguagem de programação ou tecnologia, que esteja aberto a desenvolver conforme nossas necessidades). 
⟹ Comunicação tranquila e pacífica (todos aqui temos ótimas ideias e é necessário ouvir e respeitar cada uma delas).

## Contratação
CLT ou a combinar

## Nossa empresa
A Vee surgiu com o objetivo de romper o oligopólio do mercado de benefícios do Brasil: um sistema antiquado, burocrático, acomodado e amarrado aos grandes bancos, a configuração atual impede a criação de um produto flexível, ágil e menos custoso para empresas, colaboradores e estabelecimentos.
Em breve resumo, criamos uma plataforma de baixo custo, com transações p2p, extinguindo intermediários do processo de pagamento. Conseguimos assim resolver os principais downsides do sistema atual para todos os stakeholders (empresas, colaboradores e dos estabelecimentos), oferecendo baixíssimos custos, além de excelente user experience aliado a um produto altamente customizável, características notoriamente inexistentes no atual panorama desse segmento.
Em números, o mercado PAT movimenta cerca de R$85 bilhões por ano. Já o mercado de benefícios como um todo movimenta R$150 bilhões por ano. Com a reforma trabalhista, existem previsões que colocam esse mercado no patamar de R$450 bilhões dentro dos próximos 5 anos.

Que tal fazer parte dessa revolução?!  

☛ Cultura da empresa:
⟹ Você terá muita liberdade para propor novas ideias, novas soluções;
⟹ Não temos apegos a hierarquias, a melhor ideia sempre vence;
⟹ Queremos desenvolvedores(as) que prezam pela qualidade do código.

☛ Onde ficamos
Vila Olímpia
Rua Funchal, 538 - 4º andar – sala 42/44
São Paulo

☛ Políticas de inclusão
Somos uma empresa jovem favorável a diversidade, queremos uma empresa diversa, pois somente, assim, criaremos uma experiência de pagamento que envolvam todas a perspectivas.

☛ Políticas de não discriminação
Qualquer intolerância por motivos raciais, religiosos ou preferência sexual não serão toleradas na Vee.

Oferecemos uma grande oportunidade de aprendizagem e crescimento profissional, em conjunto com a expansão da empresa e de fazer parte de um time inovador e eclético de desenvolvedores(as), ajudando a criar uma nova forma para realizar transações financeiras.

## Como se candidatar
Por favor preencha o formulário em [https://docs.google.com/forms/d/e/1FAIpQLSdrNew4KluM_wzXyeeL3o5tzuFEOdUrKNvcXheoKhR7hcbJYQ/viewform](https://docs.google.com/forms/d/e/1FAIpQLSdrNew4KluM_wzXyeeL3o5tzuFEOdUrKNvcXheoKhR7hcbJYQ/viewform)

**Comment by jpventura** [comment]
@sergiobr Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar **Vaga ainda está aberta**.
