### ISSUE TITLE
[Barcelona, Spain] mytaxi | Android Developer

### ISSUE THREAD

**Issue by taxidriverbcn** [androiddevbr/vagas#715]
## Descrição da vaga

You love coding, we get it. We love coding too!
But most important, we love good code. And what does this mean?

It means...

that we write clean code
that we use the latest technologies (Kotlin, RxJava, MVP)
that our developers and our QAs are part of the same team
that we learn from our colleagues (even if they own an iPhone)
that we work on an agile environment
that we enjoy the product we build

Good code means a lot to us.

## Local

Barcelona, Spain

## Benefícios

Short working Fridays
Gym membership
Tteam-building activities (karting, bowling, laser tag, escape rooms, barbecues/calçotades…)
Hacking weeks
Health insurance with basic dental coverage
25 days annual leave plus your birthday off
The opportunity to use the latest technologies and implement your own ideas
Free language lessons
Relocation package

## Requisitos

Obrigatórios

4+ years of experience in Android development
Very good knowledge of Kotlin and Java

Desejáveis
Degree in informatics or similar
- Good knowledge of RxJava

## Contratação

Full-time permanent (40h/week)

## Nossa empresa

mytaxi was founded in June 2009 and was the world’s first taxi app that established a direct connection between a passenger and a taxi driver. With more than 10 million passengers and 100,000 drivers, mytaxi is the leading taxi e-hailing app in Europe.

Since February 2019, mytaxi is part of the FREE NOW group, the ride-hailing joint venture of BMW and Daimler. Within 2019, mytaxi will rebrand to FREE NOW.

mytaxi today works with 600 employees in 26 offices and is available in around 100 European cities. 

## Como se candidatar

Apply here: https://boards.greenhouse.io/mytaxigroup/jobs/666798#app
Email: m.saborit@mytaxi.com

**Comment by lucas-inatel** [comment]
Hi @taxidriverbcn, please set the tags that correspond to this job

**Comment by jpventura** [comment]
Thank you @taxidriverbcn! We added all the tags related to the job description.

Let us know if any related tag is missing.

**Comment by jpventura** [comment]
@taxidriverbcn This issue has being inactive for over 3 months. If the job opportunity is still available, please comment **Opportunity still available**.
