### ISSUE TITLE
[São Paulo - Paraíso] Netshoes - Desenvolvedor Android Pleno

### ISSUE THREAD

**Issue by rafaelsm** [androiddevbr/vagas#716]
## Empresa
 Somos responsáveis pelas lojas virtuais Netshoes, o maior e-commerce de artigos esportivos do mundo e Zattini, nossa loja fashion que já é o um sucesso do e-commerce brasileiro. Operamos também mais de 25 lojas oficiais de clubes de futebol, marcas esportivas, além de parceiros como NBA, NFL, Puma, Olympikus e Asics, além das lojas virtual e física da nossa mais recente marca: a Shoestock.

## Descrição da vaga
 - Desenvolvimento de Soluções para plataforma Android

## Posição
 Desenvolvedor Pleno

## Tipo de contratação
CLT

###### Obrigatórios
Superior completo
Conhecimento em consumo de APIs JSON/REST
Conhecimento em Gradle(Build Variant, Tasks, etc)
Conhecimento sólido em Java/Kotlin
Conhecimento do processo de distribuição da Play Store
Conhecimento em algumas arquiteturas mobile (ex: MVP, MVVM, VIPER)
Conhecimento em armazenamento local (offline)
Conhecimento em Proguard
Conhecimento em metodologia ágil
Conhecimento em Git – GitFlow
Testes unitários
Inglês leitura técnica

###### Desejáveis
Conhecimento em ferramentas de automação
Conhecimento em Integração Contínua / Entrega Contínua
Conhecimento de testes de interface – instrumentados
Experiência em aplicativos Whitelabel
Portfólio de aplicativos na Play Store
Conhecimento em monitoração e métricas (crash report, analytics, performance)
Conhecimento em e-commerce

###### Diferenciais
Experiência em desenvolvimento backend;
Conhecimento em Otimização de Performance e Segurança;

## Benefícios
Vale Refeição, pois temos foodtruck e gostamos muito de comer! :-)
Vale Alimentação, para complementar as compras no mercado!!
Assistência Médica: Bradesco.
Assistência Odontológica: BBDental.
Day Off, descanso merecido no dia do seu aniversário \o/
Participação nos lucros e resultados.
Horário Flexivel
Desconto em produtos
Previdência Privada
Parceria com Academias, mexa-se !
Parceria com Faculdades, você sendo protagonista do seu conhecimento!

## Como aplicar
Através do link: https://jobs.kenoby.com/gruponetshoes/job/desenvolvedor-android-pl/5c70380ade7ae0076e5c4a0f

**Comment by jpventura** [comment]
@rafaelsm Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar *Vaga ainda está aberta*.
