### ISSUE TITLE
[São Paulo] Desenvolvedor IOS Talent Four 

### ISSUE THREAD

**Issue by 160303** [androiddevbr/vagas#717]
Descrição da vaga

Desenvolvimento e correções de bugs . 

Berrini 

## Benefícios

sala de descompressão com sinuca, video game, bicicletas , energéticos frutas , massagem , 

Obrigatórios
- 3+ anos de experiência com IOS 
- Objective C - Swift 

Conhecimentos nas arquiteturas MVC, MVVM; Conhecimento de design patterns | 

PJ a combinar

Talent Four , somos uma empresa há mais de 25 anos no mercado com expertise em profissionais de T.I . atendendo as melhores empresas . 

Interessados enviar curriculo para suelen.matta@talentfour.com.br

**Comment by douglasdrumz** [comment]
Vaga não é relacionada a Android
