### ISSUE TITLE
[São Paulo] Desenvolvedor Android -TALENT FOUR -INICIO IMEDIATO 

### ISSUE THREAD

**Issue by 160303** [androiddevbr/vagas#718]
## Descrição da vaga

Desenvolvimento Android e correção de bugs . 

## Local

Berrini - São Paulo 

## Benefícios

Sala de descompressão com mesa de sinuca , bilhar, video game, energéticos , bebidas e frutas. Disponibilizamos bicicletas , 

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados
Inglês intermediário , avançado , fluente 

## Contratação

PJ por tempo indeterminado . 

## Nossa empresa

Somos uma empresa especializada em profissionais de T.I , há mais de 25 anos no mercado. Atuando em âmbito nacional. 

## Como se candidatar

Por favor envie um e-mail para suelen.matta@talentfour.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by mion23** [comment]
Olá Suelen, vocês aceitam candidatos remotos?

**Comment by jpventura** [comment]
@160303 Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar *Vaga ainda está aberta*.
