### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android Pleno ou Sênior | NESS

### ISSUE THREAD

**Issue by SergioSCF** [androiddevbr/vagas#72]
![vaga android](https://cloud.githubusercontent.com/assets/2027565/18711263/79060ce6-7fdf-11e6-9ed5-6090e15fee1d.jpg)
## Descrição da vaga

Estou contratando um Dev Android Pleno e/ou Senior pra integrar no nosso time de desenvolvimento aqui na NESS (São Paulo / Itaim). 

Inicialmente este Dev será responsável pela criação do zero do App de um cliente da NESS o qual já tem um App iOS com as funcionalidades prontas como referência. 

Peço que enviem os CVs para desenvolvimento@ness.com.br com o título "Vaga Android Pleno" ou "Vaga Android Senior" caso seja o seu perfil. 

Os pré requisitos são:
- Desenvolver em Android há pelo menos 2 anos
- Ser auto gerenciável
- Gostar de aprender coisas novas 

Desejável
- Trabalhar ou ter trabalhado com qualquer outra linguagem há pelo menos 3 anos (ASP.NET, Java, Ruby, etc)
- Inglês
- Curso superior
## Local

Escritório em São Paulo - Itaim
## Contratação

A combinar

**Comment by walmyrcarvalho** [comment]
@SergioSCF Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by SergioSCF** [comment]
Fechou. Mega obrigado Walmyr !

Atenciosamente,




*Sergio Costa Faria*( +55 11 98634-7527

* sergio.gri@gmail.com

: http://www.linkedin.com/in/sergiocostafaria



2017-04-08 21:48 GMT-03:00 Walmyr Carvalho <notifications@github.com>:
