### ISSUE TITLE
[Barcelona, Spain] mytaxi | Android Lead

### ISSUE THREAD

**Issue by taxidriverbcn** [androiddevbr/vagas#720]
## Job description

So, coding is your passion, right? And now it just happens that you lead a team of developers too.
However, you didn’t let your programming skills go rusty and are still great at writing code. Why? Because you love coding.
We know that finding a role that balances between coding and leading your own team can be challenging.

Well, at mytaxi we have it. 

As the **Android Chapter Lead**, you will act as a coach for your team in order to help them with their weaknesses and foster their strengths. You will also set their goals and motivate them to achieve these.
Being part of an agile interdisciplinary team, you will also work closely with our Product Department in Hamburg to lead the development of your chapter.
You will be responsible for the development of a high-quality product capable to stand our fast growth and evolution.

And all this, while you code!

Is it challenging? Of course.

Is it fun? Absolutely!

## Location

Barcelona, Spain [we will sponsor your visa & relocation]

## Benefits

- **Relocation package** (visa sponsorship, flights & temporary accommodation)
- Health insurance with basic dental coverage  
- Short working Fridays
- Gym membership
- Team-building activities (karting, bowling, laser tag, escape rooms, barbecues/calçotades…)
- Hacking weeks
- 25 days annual leave plus your birthday off
- The opportunity to use the latest technologies and implement your own ideas
- Free language lessons

## Requirements
- If you are experienced in team leadership and Android development 
- If you dream in **Kotlin** rather than in your mother tongue
- If you have a deep knowledge of Java
- If you know how to work with microservices
- If you have kowledge of Kotlin, RxJava, MVP, Dagger/Dagger2, Retrofit2, gradle, mqtt
- If you are a **software craftsperson**

Jump in to mytaxi and show us what you can do!

## Contract

Full-time permanent (40h/week)

## About mytaxi

mytaxi was founded in June 2009 and was the world’s first taxi app that established a direct connection between a passenger and a taxi driver. With more than 10 million passengers and 100,000 drivers, mytaxi is the leading taxi e-hailing app in Europe.

Since February 2019, mytaxi is part of the FREE NOW group, the ride-hailing joint venture of BMW and Daimler. Within 2019, mytaxi will rebrand to FREE NOW.

mytaxi today works with 600 employees in 26 offices and is available in around 100 European cities.

## How to apply

Apply here: https://boards.greenhouse.io/mytaxigroup/jobs/934258#app
Email: m.saborit@mytaxi.com

**Comment by jpventura** [comment]
Hi, @taxidriverbcn! Will you sponsor the working permit as well or European citizenship is required?

**Comment by taxidriverbcn** [comment]
Hi @jpventura! Yes, we sponsor the work permit and also offer to pay for flights and temporary accommodation for your first few weeks :)

**Comment by jpventura** [comment]
Thank you @taxidriverbcn! We added all the tags related to the job description.

Let us know if any related tag is missing.

**Comment by jpventura** [comment]
@taxidriverbcn This issue has being inactive for over 3 months. If the job opportunity is still available, please comment **Opportunity still available**.
