### ISSUE TITLE
[São Paulo, SP] Lead Android Developer

### ISSUE THREAD

**Issue by carlosdejavite** [androiddevbr/vagas#722]
## KEYWORDS
2+ anos de experiência com Android desenvolvendo em arquiteturas modernas ("Clean Architecture", MVP, MVVM e afins) em paradigmas assíncrono (Reactive Programming, ...). Preferência por experiências em empresas de tecnologia no serviços financeiros (fintechs).

## COMPANY DESCRIPTION
SmartMEi is inspired by a dream: give all the infrastructure the entrepreneur needs to take care of his business in an easy, intuitive and cheap way, using his smartphone.

We provide a large range of financial services and accounting solutions for those completely ignored by traditional financial institutions and by the Government.

Taking bureaucracy out of the way, entrepreneurs can finally focus on their business and have a better chance of improving their lives and of those around them.

Excited about building a cutting edge fintech to empower millions of Brazilian microentrepreneurs? Join the team! The company is now hiring for the Android Mobile Developer position!

You'll reshape the core experience of thousands entrepreneurs who are using our solution on a daily basis.

## JOB DESCRIPTION
Refactor and later maintenance of the company app using a Java / Kotlin language.

## PLACE
Metrô Faria Lima, São Paulo - BR

## BENEFITS
Work remotely or at the office
Near subway station
Bike parking place
Relaxed place with snacks
Happy-hour with board games
Periodic tech presentations
Opportunity to hands-on backend, frontend, chatbot as well

## REQUIREMENTS

4+ years of Android experience
Standard MVP, MVVM, Clean Architecture and derivatives
RxJava and RxAndroid
RESTful APIs integrations with Volley or Retrofit
Git code versioning
Desirable knowledge
Firebase Realtime Database, Firebase Remote Config, and Firebase Analytics
Espresso, Mockito and UI Automator
Off-line data persistence with SQLite, Content Providers, Realm, or Room

Por favor envie um email para dejavite@smartmei.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by douglasdrumz** [comment]
Closed after 3 months. If it's still open, reopen the issue
