### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor Nativo ou Multiplataforma - ArcTouch

### ISSUE THREAD

**Issue by arctouch-danilofavoratti** [androiddevbr/vagas#724]
## Descrição da vaga

Quer trabalhar para clientes exclusivamente internacionais como Walmart, 3M, HP, Disney, entre outras, fazendo apps sob medida, do **conforto de sua casa** ou morando em uma das capitais mais belas do Brasil?

A ArcTouch é uma empresa fundada em São Francisco, Califórnia, que conta com um lindo escritório na ilha mais tecnológica do Brasil: Florianópolis, Santa Catarina (também conhecida como Ilha do Silício).

Não importa de onde você é (o processo seletivo é 100% remoto e você pode trabalhar via home office se desejar) e nem quem você é (diversidade é um fator chave em nossa cultura).

Procuramos Devs Mobile (nativo ou não) que já tenha experiência na área, com um bom nível de inglês (ao menos no entendimento), para transformar os nossos clientes em heróis!

## Local

Remoto ou Florianópolis/SC, próximo ao centro.

## Benefícios

CLT (Férias, décimo terceiro, etc...)
Plano de Saúde (e Odontológico)
Vale Alimentação
Vale Transporte e/ou Estacionamento
Aulas de inglês
Gympass
Home Office às sextas-feiras (ou todo dia)
... e muito, mas MUITO, mais (detalhes: https://arctouch.com/careers/brazil/)

## Requisitos

Obrigatórios
- 2+ anos de experiência com Android
- Inglês intermediário+ (precisa ao menos se comunicar verbalmente)

Desejáveis
- Experiência com metodologia ágil.

Diferenciais
- Possibilidade de trabalhar no exterior.

## Contratação
- CLT com todos os direitos previstos em lei e muitos outros adicionais

## Como se candidatar

Mande um e-mail com suas dúvidas diretamente pra mim (de dev pra dev) junto ao seu CV em PDF e/ou LinkedIn que vou te indicar internamente se identificarmos que a oportunidade é válida para você: danilo.favoratti@arctouch.com

**Comment by arctouch-danilofavoratti** [comment]
Não estou conseguindo adicionar as tags, mas seriam: Sênior, Pleno, Remoto, Presencial e CLT

**Comment by lucas-marciano** [comment]
Olá @arctouch-danilofavoratti , tudo bom? Amigo, tu poderia me tirar uma dúvida? Essa vaga é para contratação imediata? Obrigado

**Comment by arctouch-danilofavoratti** [comment]
@lucas-marciano É sim! :)

**Comment by DaniloFurtado** [comment]
@arctouch-danilofavoratti  mandei meu currículo no email, valeu por compartilhar.

**Comment by rodrigoAOliveira** [comment]
Ainda está aberta a vaga?

**Comment by arctouch-danilofavoratti** [comment]
@rodrigoAOliveira Está sim! Especialmente para sêniors.

**Comment by rodrigoAOliveira** [comment]
Obrigado pelo retorno, encaminhei meu curriculo.

**Comment by jpventura** [comment]
@arctouch-danilofavoratti Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar *Vaga ainda está aberta*.
