### ISSUE TITLE
[Goiânia, Goias] Desenvolvedor Android/ IOS - Tilix Digital 

### ISSUE THREAD

**Issue by IsabelaCampos** [androiddevbr/vagas#725]
# Sobre a vaga

O profissional será responsável pelo desenvolvimento e manutenção do app iOS, a expectativa é que o profissional seja capaz de entregar um produto com qualidade e requintes avançados de UX.

# Tipo de contratação

CLT – Presencial – Goiânia – Goiás

# Requisitos

– Analisar, projetar, programar, depurar e modificar software.

– Escrever códigos realizar testes e depurar aplicações.

– Interagir com o time de experiência do usuário para definir os requisitos de sistema e/ou modificações necessárias, bem como interagir com os interessados para entender os requisitos para o desenvolvimento de aplicações.

# Obrigatórios

– Experiência com desenvolvimento mobile nativo iOS ou Android. 

– Experiência no uso de Web Services.

– Autolayout.

– Conhecimentos de UX e guidelines da Apple.

– Design Patterns.

– Noções de arquitetura MVC e MVVM.

– Conhecimento em arquitetura de Micro-Serviços.

# Diferencial

– Inglês

– Conhecimento em Testes Unitários.

– Conhecimento em programação funcional.

– Conhecimento em programação reativa.

– Experiência com outras plataformas como Android e NodeJS.

– Links com código no github e/ou apps publicadas.

– Conhecimento em Integração Contínua.

# Benefícios

VR ou VA + Plano de Saúde + Horário Flexível.

# Salário 

 A Combinar

Para se inscrever acesse: tilix.com.br/worker

**Comment by jpventura** [comment]
@IsabelaCampos Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar *Vaga ainda está aberta*.
