### ISSUE TITLE
[SÃO PAULO] Desenvolvedor Android Kotlin [Pleno] | Formalizar e-Signature

### ISSUE THREAD

**Issue by penelopevitoria** [androiddevbr/vagas#726]
**Esta é uma vaga de um cliente da GeekHunter, candidate-se para ter acesso as informações completas sobre a empresa.**

Buscamos talentos para se juntar ao nosso time ágil, que some forças para crescer no impacto da transformação digital em empresas de todos os tamanhos e segmentos.

### **Procuramos novo integrante que:** 

- Seja apaixonado pelo que faz, com hábito e histórico de busca por aperfeiçoamento contínuo;
- Tenha foco na experiência do usuário e usabilidade;
- Saiba trabalhar em equipe;
- Tenha mindset de auto responsabilidade.

### **Salário:** 
R$ 8 000,00 (PJ)

### **Responsabilidades:**

**1.** Atue diretamente com os aplicativos utilizados por nossos usuários finais para gerenciar e realizar a o formalização digital de documentos (ou onboarding);

**2.** Desenvolver novas funcionalidades e otimizar funcionalidades existentes;

**3.** Auxiliar no levantamento de requisitos, impactos e otimização dos processos de 
desenvolvimento;

 **4.** Refatorar e aperfeiçoar o código baseando-se em novos e melhores padrões de 
desenvolvimento;

**5.** Utilizar um processo definido de versionamento e revisão de código;

**6.** Acompanhar métricas em produção e identificar problemas a serem corrigidos.

### **As tecnologias:**

- Em nosso App utilizamos SDK, Nativo Android, SQLite, Anko, com Linguagens 
Kotlin, Java e C++ e Arquitetura 
Client- API Gateway.

### **## Local**

São Paulo - SP

### **## Requisitos Obrigatórios**

- Kotlin, Programação Orientada a Objeto

### **### Requisitos Desejáveis**

Git, TDD, RESTful, SOAP, Clean Architecture

### **## Contratação**

PJ a combinar // R$ 8 000

### ## Como se candidatar

Cadastre na GeekHunter e tenha acesso às demais informações: http://bit.ly/2Ya54W2

**Comment by jpventura** [comment]
@penelopevitoria Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar *Vaga ainda está aberta*.
