### ISSUE TITLE
[Florianópolis - SC] Arquiteto de Soluções na Portobello

### ISSUE THREAD

**Issue by penelopevitoria** [androiddevbr/vagas#727]
**Esta é uma vaga de um cliente da GeekHunter, candidate-se para ter acesso as informações completas sobre a empresa.**

Oportunidade para Arquiteto de Soluções Sênior para atuação no time de Inovação Digital em Florianópolis.

Será ponto focal na definição de novas estruturas, participação ativa na avaliação do AS-IS junto às áreas internas (principalmente TI), avaliação de fornecedores, homologação de plataformas em projetos na área de Inovação Digital.

Atuará principalmente em estruturação de soluções integradas para sites web, aplicativos mobile Android e IOS, CRM Salesforce e ERPs.

### **## Local**

Florianópolis - SC

### **Benefícios**

- Vale refeição
- Vale transporte
- Vale estacionamento
- Plano de saúde
- Plano odontológico
- Entre outros

### **Requisitos Obrigatórios**

- Arquitetura SOA
- Arquitetura de software

### **Requisitos Desejáveis**

- Experiência em Python, Node.js, RESTful

### **## Contratação**

CLT // Salário R$ 8 000,00

## Como se candidatar

Cadastre-se na GeekHunter e concorra à vaga: http://bit.ly/2Y787Ox

**Comment by davidtcdeveloper** [comment]
@ penelopevitoria Nosso mural de vagas é voltado para oportunidades para desenvolvedores Android. Como não ficou claro quais as responsabilidades relacionadas a Android, estou encerrando esta vaga. Peço que, caso a vaga seja realmente para desenvolvimento Android, a vaga seja reaberta com uma descrição mais detalhada.
