### ISSUE TITLE
[São Caetano do Sul, SP] Desenvolvedor Android (PL|SR) | Via Varejo

### ISSUE THREAD

**Issue by recruitermaaaa** [androiddevbr/vagas#728]
A Taking Consultoria está contratando profissionais para atuar em nosso cliente Via Varejo.

Descrição da vaga:
Desenvolvimento para Android.

Posição
Desenvolvedor Pleno e Sr

Tipo de contratação
PJ por tempo indeterminado

Local
São Caetano do Sul - SP

Requisitos
Experiência em Kotlin, Java, Gradle, RetroFit, REST, Push Notification (Firebase, GCM). Constraint Layout.

Desejáveis: 
APPs Publicados na Loja, SOLID, DDD, Cultura DevOps.

Como aplicar:

Enviar cv atualizado para cida.araujo@taking.com.br

**Comment by jpventura** [comment]
Olá, @recruitermaaaa! Qual o nome da empresa? Segundo o código de conduta da comunidade, é preciso informar o nome da empresa.

**Comment by recruitermaaaa** [comment]
@jpventura alterado! Coloquei o cliente.

**Comment by jpventura** [comment]
@recruitermaaaa presencial ou remoto?

**Comment by recruitermaaaa** [comment]
@jpventura presencial...primeira vez publicando aqui....sorry

**Comment by jpventura** [comment]
@recruitermaaaa Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar *Vaga ainda está aberta*.
