### ISSUE TITLE
[CE - Fortaleza] Resource IT Solutions - Desenvolvedor(a) ANDROID

### ISSUE THREAD

**Issue by matheusaguiardev** [androiddevbr/vagas#729]
# Empresa
Venha fazer parte do time de Inovação Digital da Resource, uma das maiores integradoras digitais do Brasil e uma as empresas de TI que mais crescem no País. Com 25 anos no mercado, multinacional brasileira com presença global, com 21 escritórios em 5 países.
Também está presente no Vale do Silício com um avançado Centro de Pesquisa e Inovação, o que possibilita estar cada vez mais próxima do cliente, entender melhor o seu negócio e oferecer a melhor solução.

## Descrição da vaga

Procuramos por desenvolvedor Android.

## Tipo de contratação

Presencial CLT.

## Posição

Desenvolvedor Android Pleno ou Sênior

## Benefícios

- Vale refeição.
- Plano de saúde.
- Plano odontológico.
- Seguro de vida.
- Convênio farmácia.

## Requisitos

Obrigatórios
- Nível superior completo.
- Experiência com aplicativos em Android nativo.
- Ter experiência em Google Material Design.
- Trabalhar com Constraint Layout e diferentes resoluções de tela.
- Experiência com versionamento.
- Experiência com Kotlin.
- Abordagem voltada a testes.
- Ser proativo.
- Ter o Clean Code na veia.

Desejáveis
- Automação de teste unitários.
- Experiência em Scrum / Kanban.
- Conhecimento da arquitetura MVVM ou VIPER.
- Conhecimento em Koin.
- Conhecimento em Retrofit.
- Conhecimento em armazenamento local.
- Conhecimento em Coroutines.

Diferenciais

- Conhecimento em desenvolvimento de serviços .NET.
- Conhecimento em desenvolvimento iOS/Swift.
- Conhecimento em Otimização de Performance e Segurança

## Como se candidatar

- Enviar um e-mail para joao.aguiar@resourceit.com com título [Desenvolvedor ANDROID PLENO ou SÊNIOR] e currículo em anexo.
- Pretensão salarial

**Comment by lucas-inatel** [comment]
@matheusaguiardev vcs aceitam home office?

**Comment by WellingtonCosta** [comment]
@lucas-inatel infelizmente não.
