### ISSUE TITLE
[Indaiatuba, São Paulo] Desenvolvedor Mobile Pleno ou Sênior | GAS Tecnologia

### ISSUE THREAD

**Issue by gbazilio** [androiddevbr/vagas#73]
## Descrição da vaga

Análise e desenvolvimento de bibliotecas e aplicativos na área Mobile e segurança da informação.
## Local

Indaiatuba / SP
## Benefícios
- Assistência médica
- Assistência odontológica 
- VR e VT
- Seguro de vida
- 2 horas de almoço
  - Ambiente informal
  - Café da manhã mensal
  - Sala de jogos com sinuca, totó, ping pong, videogame
  - Parabéns com bolo todo mês 
- Festas e eventos ao longo do ano
  - Troca de conhecimento através de palestras e workshops internos
  - Parcerias com academias e escolas de idiomas
## Requisitos

Conhecimento em análise de requisitos;
Desenvolver e manter soluções tecnológicas conforme especificações (aplicativos e bibliotecas);
Criar e manter builds automatizados;
Criar e manter métricas intermediárias de qualidade de software.
Desenvolvimento de scripts de automatização de processos;
Conhecimento em lógica de programação;
Conhecimento em orientação a objetos;
Conhecimento dos ambientes de desenvolvimento Mobile: Android ou iOS;
Conhecimento em linguagens como: Python, C++, C#, Java, Objective-C e/ou Swift.
Conhecimento de sistemas de versionamento como GIT ou SVN;
Conhecimento de utilização de ferramentas de build como Quickbuild, Jenkins
## Contratação

Modelo de contratação CLT
## Nossa empresa

Somos líderes em soluções de combate à fraude e responsáveis pela segurança digital de milhões de dispositivos no Brasil e no mundo.

Temos um grande desafio e estamos comprometidos com ele: proteger a integridade, a informação e as finanças dos nossos clientes e de seus usuários. 

Transformamos nosso conhecimento e muita pesquisa nas melhores práticas para coibir ações maliciosas e impedir que a tranquilidade de pessoas e instituições seja abalada. 
Somos pessoas engajadas, comprometidas, com fôlego e vontade para a transformação, pensamos à frente e estimulamos sempre o trabalho em equipe.
## Como se candidatar

Por favor envie um email para guilherme.bazilio@diebold.com com seu CV anexado - enviar no assunto: Vaga Dev Mobile - Github

**Comment by WCLima** [comment]
Vaga já foi preenchida?

**Comment by gbazilio** [comment]
Ainda não.

Em 23 de nov de 2016 1:55 PM, "WCLima" <notifications@github.com> escreveu:

**Comment by walmyrcarvalho** [comment]
@gbazilio Essa vaga ainda está aberta? Senão, irei fechá-la pra fins de organização!

**Comment by gbazilio** [comment]
@walmyrcarvalho Não mais. Já devia ter fechado.
