### ISSUE TITLE
[RJ - Barra da Tijuca - Downtown] Desenvolvedor Android Pleno (Ubook)

### ISSUE THREAD

**Issue by prsolucoes** [androiddevbr/vagas#730]
## Descrição da vaga

O Ubook está a procura de um desenvolvedor Android que tenha vontade de fazer parte de uma empresa que está mudando o mundo com suas novas tecnologias. Esta oportunidade é para aqueles que possuem experiência no desenvolvimentos de aplicativos mobile para Android.

Site:
https://www.ubook.com

## Local

Local - Shopping Downtown - Barra

## Requisitos

- Conhecimento pleno da plataforma Android e suas APIs
- Conhecimento pleno da linguagem Java 
- Conhecimento pleno da IDE AndroidStudio
- Conhecimento sobre SQLite e JSON 
- Conhecimento sobre Git 
- Elaborar código limpo e com estrutura legível (clean code) 

Será um diferencial quem também tiver estes conhecimentos: 

- Otimização de recursos em ambientes embarcados 
- Estar atualizado com as tendências e novidades da plataforma para sugestão de melhorias 
- Conhecer a linguagem PHP (para depurar problemas na integração caso necessário) 
- Conhecer testes unitários 
- Conhecer o banco MySQL para validar registros enviados do aplicativo para o backend

Diferenciais
- Projetos opensource

## Contratação

CLT

## Nossa empresa

Ubook

Imprensa:
http://try.ubook.com/ubooknews/

## Como se candidatar

Por favor envie um email para vagas.ti@ubook.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@prsolucoes Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar *Vaga ainda está aberta*.
