### ISSUE TITLE
[Jaguariuna] Desenvolvedor Android l Mazzatech

### ISSUE THREAD

**Issue by taianeuchoa** [androiddevbr/vagas#731]
## Descrição da vaga

Oportunidade para atuar no time de desenvolvimento Mobile de uma grande multinacional brasileira do ramo de bebidas.

## Local

Atuação no escritório da empresa em Jaguariuna.

## Benefícios

- Refeitório no local
- gestão horizontal
- ambiente startup
- contato com equipes multiculturais

## Requisitos

Obrigatórios
- Experiência minima de 3 anos atuando com Android ou/e IOS;
- Inglês avançado para conversação.

## Contratação

PJ ou CLT a combinar (estamos trabalhando com pretensão salarial do candidato)

## Nossa empresa

A Mazzatech é uma consultoria de TI que atua há 10 anos no mercado, auxiliando diversos tipos de empresa na busca pelos melhores profissionais.

## Como se candidatar

Por favor envie um email para taiane@mazza.tech com seu CV anexado - enviar no assunto: Vaga Android (Jaguariuna). Enviar no email também sua pretensão salarial.

**Comment by davidtcdeveloper** [comment]
@taianeuchoa a vaga é para ser contratado(a) pela Mazzatech mesmo? Ou é para ser contratado por outra empresa? Caso seja a segunda opção, nossas regras obrigam a divulgação do nome da empresa.

**Comment by taianeuchoa** [comment]
Oi David! A contratação eh pela Mazzatech, mas atuará, ficará alocado em um cliente.

Obrigada!!

Enviado do meu iPhone

Em 4 de abr de 2019, à(s) 16:41, David Tiago Conceição <notifications@github.com<mailto:notifications@github.com>> escreveu:


@taianeuchoa<https://github.com/taianeuchoa> a vaga é para ser contratado(a) pela Mazzatech mesmo? Ou é para ser contratado por outra empresa? Caso seja a segunda opção, nossas regras obrigam a divulgação do nome da empresa.

**Comment by jpventura** [comment]
@taianeuchoa Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar *Vaga ainda está aberta*.
