### ISSUE TITLE
[Rio de Janeiro, RJ] Desenvolvedor Android [Pleno, Senior] [CLT] | iMusica

### ISSUE THREAD

**Issue by gbrandao01** [androiddevbr/vagas#732]
## Descrição da vaga

Estamos à procura de um desenvolvedor Android para desenvolvimento e manutenção de aplicativos voltados para um grande número de dispositivos. Seu foco principal será o desenvolvimento de aplicativos Android e sua integração com serviços de back-end. Você trabalhará ao lado de outros desenvolvedores em diferentes camadas da infraestrutura. Portanto, o compromisso com a solução colaborativa de problemas, o design sofisticado e a criação de produtos de qualidade é essencial.

## Local

Rio de Janeiro - Botafogo

## Benefícios

- Plano de saúde (Bradesco) extensível aos dependentes
- Vale Refeição
- Vale Transporte

## Requisitos

- Forte conhecimento do Android SDK, diferentes versões do Android e como lidar com diferentes tamanhos de tela
- Familiaridade com APIs RESTful para conectar aplicativos Android a serviços de back-end
- Conhecimentos sólidos dos princípios, padrões e práticas recomendadas do design da IU do Android
- Experiência com armazenamento offline, segmentação e ajuste de desempenho
- Familiaridade com APIs de mensagem na nuvem e notificações push
- Entendimento dos princípios de design e diretrizes de interface do Google para Android
- Compreensão proficiente de ferramentas de controle de versão de código, como o Git
- Familiaridade com integração contínua

Desejáveis
- Idioma inglês e/o espanhol

## Contratação

CLT

## Nossa empresa

A iMusica é uma empresa do grupo Claro. Criamos aplicativos de música e entretenimento para a Claro Brasil e para todas as operações da Claro Latin America.

## Como se candidatar

Por favor envie um email para glauco.brandao@imusica.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@gbrandao01 Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar *Vaga ainda está aberta*.

**Comment by gbrandao01** [comment]
Vaga ainda está aberta
