### ISSUE TITLE
[SP / Santo Amaro] Desenvolvedor(a) Android (Kotlin)

### ISSUE THREAD

**Issue by aaamenezes** [androiddevbr/vagas#734]
Essa vaga foi removida por não atender as [especificações do grupo de Android Dev BR](https://github.com/androiddevbr/vagas/blob/master/README.md).

Se ela for reeditada atendendo as regras descritas no [README](https://github.com/androiddevbr/vagas/blob/master/README.md), teremos prazer em aprová-la :smile:

**Comment by jpventura** [comment]
Olá, @aaamenezes! Qual o nome da empresa referente a vaga?

**Comment by aaamenezes** [comment]
Desculpa esqueci dessa informação.

WK Recursos Humanos

**Comment by jpventura** [comment]
@aaamenezes não, qual o nome da empresa onde o candidato irá atuar, não da empresa de recrutamento. De acordo com o Código de Conduta da comunidade, você precisa postar o nome da empresa.

**Comment by jpventura** [comment]
@aaamenezes não, qual o nome da empresa onde o candidato irá atuar, não da empresa de recrutamento. De acordo com o Código de Conduta da comunidade, você precisa postar o nome da empresa.
