### ISSUE TITLE
[Campinas/SP] Android Developer | MasterMundi/ProCar

### ISSUE THREAD

**Issue by josejlpp** [androiddevbr/vagas#738]
## Descrição da vaga

Seu trabalho será aprimorar, dar manutenção e evoluir a nossa aplicação junto a nossa equipe

## Local

- Presencial
- Alphaville Empresarial Campinas - SP

## Requisitos

**Obrigatórios:**
- Android
- Java
- Kotlin
- API Google Maps

**Desejáveis:**
- Padrões de desenvolvimento
- Metodologias Ágeis
- Bitbucket

**Diferenciais:**
- Escrever testes automatizados (unidade, aceitação, etc).
- Integração Contínua 

## Contratação

- CLT
- VR/VT
- Enviar pretensão salarial
- Horário: De segunda a sexta, Flexível dentro de 44 horas semanais
Salário
Entre 5.000,00 e 10.000,00

## Nossa empresa

Trabalhamos em diversos ramos entre eles o da mobilidade urbana e procuramos pessoas que busquem crescer junto da empresa nesse novo projeto. Se você procura desafio e quer crescer com a empresa, isto é para você.

## Como se candidatar

Por favor envie um email para curriculo@mastermundi.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Desenvolvedor Android

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Pleno
- Especialista
- Sênior

**Comment by jpventura** [comment]
@josejlpp Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar *Vaga ainda está aberta*.
