### ISSUE TITLE
Desenvolvedor (a) Android Embarcado 

### ISSUE THREAD

**Issue by CynthiaAlvarenga** [androiddevbr/vagas#739]
Oportunidade para atuação em projeto em parceria com empresa multinacional, referência no desenvolvimento de soluções móveis, com as seguintes atividades:

- Desenvolvimento de módulos de software embarcado para novos dispositivos móveis Android, tal como atualizações de versão do SO para os módulos de câmera.

- Analisar e corrigir falhas no código Android relacionado à câmera, incluindo adaptação de código para novas plataformas de hardware e novas versões do Android.
 
- Dar suporte no desenvolvimento do Kernel Android/drivers.

**Requisitos:**

Formação superior em Engenharia/Ciência da Computação, Sistemas de Informação ou cursos similares;
Experiência com desenvolvimento de software embarcado em C/C++;
Experiência com desenvolvimento em Linux e/ou Android embarcado;
Habilidade de debugar código, solucionar erros de software e atuar na melhoria de estabilidade da plataforma.
Inglês avançado para contato frequente com times no exterior.

Local

Campinas/SP

Contratação

CLT

## Nossa empresa

O Eldorado é referência no Brasil em pesquisa, desenvolvimento e inovação nas áreas de software, hardware, ensaios e testes de produtos eletrônicos, com diversos prêmios como uma das Melhores Empresas para se trabalhar e começar a carreira! Venha fazer parte desta história que já tem 20 anos!

Como se candidatar

Basta acessar nosso site :)

https://www.eldorado.org.br/project/DesenvolvedorAndroidEmbarcado_219/

**Comment by jpventura** [comment]
@CynthiaAlvarenga Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar *Vaga ainda está aberta*.
