### ISSUE TITLE
[Rio de Janeiro, RJ] Android Developer - Órama

### ISSUE THREAD

**Issue by ianromano** [androiddevbr/vagas#74]
## Descrição da vaga

Estamos procurando um desenvolvedor mobile para o desenvolvimento dos nossos aplicativos!

Você terá a oportunidade de participar de projetos desafiadores em um ambiente legal e cooperativo, com uma equipe multidisciplinar.

Você participará de um movimento das chamadas Fintechs, empresas inovadoras no mercado financeiro que estão substituindo os bancos, com bastante inovação, serviços e tecnologia!
## Local

Praça Santos Dumont, 70, Rio de Janeiro, RJ
## Benefícios
- Plano de Assistência Médica
- Vale Refeição
- Vale Transporte
## Requisitos

Obrigatórios
- Java
- Desenvolvimento Android
- Usabilidade
- Guidelines

Diferenciais
- Python/Django
- Angular
- Javascript

Esperamos ainda
- Que você ame desenvolver;
- Que você seja perfeccionista com seu código e não se furte de melhora-lo sempre que possível;
- Que seja comprometido com os prazos acordados;
- Que goste de entender profundamente como as coisas funcionam;
- Que estude sempre;
- Não se furte de dar idéias;
## Contratação

a combinar
## Nossa empresa

**Sobre a Órama**

Desde 2011 a Órama está no mercado suportada por 5 pilares que descrevem o seu papel como instituição e a sua missão com seus clientes.

● Seleção criteriosa de Investimentos
● Tecnologia
● Educação Financeira
● Inovação
● Segurança

Estamos presentes em todo o Brasil com uma estrutura 100% online e comprometidos com a entrega do melhor serviço para que o brasileiro possa investir de forma consciente e transparente.

Primeira plataforma digital de investimentos no Brasil, premiada pela Amazon Web Services como uma das empresas mais inovadoras em Serviços Financeiros.

Os fundadores da Órama são os mesmos fundadores da Ágora Corretora, instituição reconhecida como uma das maiores corretoras do Brasil e uma das cinco maiores corretoras online do mundo, vendida para o Bradesco em 2008. Dando continuidade ao histórico de inovações, eles se uniram para criar a Órama.
## Como se candidatar

Basta aplicar pela 3days [nesse link](http://3days.com.br/talents/vaga/Orama/Android-Developer/H19cboeq?utm_source=github_vagasandroid&utm_content=vaga_oramaandroid)! ;)

**Comment by walmyrcarvalho** [comment]
@ianromano Essa vaga ainda está aberta? Senão, irei fechá-la pra fins de organização!

**Comment by paulo101977** [comment]
@walmyrcarvalho Impossível acessar o link informado :(

**Comment by ianromano** [comment]
@walmyrcarvalho pode fechar essa também por favor!
