### ISSUE TITLE
[Jaguariúna, SP] Desenvolvedor(a) Android | AB-InBev

### ISSUE THREAD

**Issue by rssm** [androiddevbr/vagas#741]
## Empresa
   A AB-Inbev, com operações em todos os continentes do mundo e com um portfólio de "estrelas" como Budweiser, Stella Artois, Skol, Brahma, Corona, entre outras e reconhecida como uma das melhores empresas para se trabalhar por vários anos consecutivos, procura desenvolvedor(a) Android Pleno(a) e Sênior, com perfil dinâmico, que seja apaixonado(a) por tecnologia e que queira novos desafios.

   O Centro de Desenvolvimento fica em Jaguariúna/SP e o desenvolvedor(a) integrará a célula do OneApp que hoje desenvolve projetos globais.

## Descrição da vaga

   Atuar junto ao time de desenvolvimento nos produtos globais da companhia.

## Local

Escritório em Jaguariúna - SP

## Benefícios

14º Salário, bônus anual variável, plano médico e odontológico, fretado para região metropolitana de Campinas, Gympass, desconto em cerveja!!!

## Requisitos

Obrigatórios
- Superior Completo / Tecnólogo
- Inglês Intermediário / Avançado
- Conhecimento em desenvolvimento Android

Desejáveis
- Desenvolvimento em Kotlin
- Experiência de trabalho em metodologias ágeis
- Confortável com padrão MVP, MVC, MVVM e derivados

Diferenciais
- Conhecimento em testes unitários
- Conhecimento em desenvolvimento iOS

## Contratação

Presencial - CLT

## Como se candidatar

Envie seu currículo e/ou LinkedIn para rafael.sol@ab-inbev.com
assunto: Vaga Android Developer

**Comment by jpventura** [comment]
@rssm Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar *Vaga ainda está aberta*.
