### ISSUE TITLE
[Campinas, SP] Analista de Software Java/Android | Instituto Eldorado

### ISSUE THREAD

**Issue by CynthiaAlvarenga** [androiddevbr/vagas#742]
Oportunidade para atuação em projeto em parceria com empresa multinacional, referência no desenvolvimento de soluções móveis, com as seguintes atividades:

- Desenvolvimento   (aperfeiçoamento e incorporação de novas funcionalidades) em aplicações para   Android;
 
- Desenvolvimento   e validação de novas funcionalidades em aplicações para Web, com base em   Javascript e Java EE (JQuery, REST APIs, Hibernate, Spring, GAE, AWS).

Requisitos:

- Formação superior em Engenharia/Ciência da Computação, Sistemas de Informação ou cursos similares;
- Experiência com desenvolvimento de aplicações para Android;
- Conhecimento de arquitetura do sistema Android;
- Inglês avançado para contato frequente com times no exterior.

Local

Campinas/SP

Contratação

CLT

Nossa empresa
O Eldorado é referência no Brasil em pesquisa, desenvolvimento e inovação nas áreas de software, hardware, ensaios e testes de produtos eletrônicos, com diversos prêmios como uma das Melhores Empresas para se trabalhar e começar a carreira! Venha fazer parte desta história que já tem 20 anos!

Como se candidatar

Basta acessar nosso site :)

https://www.eldorado.org.br/project/AnalistadeSoftwareJavaAndroid_220/

**Comment by jpventura** [comment]
@CynthiaAlvarenga Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar *Vaga ainda está aberta*.
