### ISSUE TITLE
[Campinas, SP] Desenvolvedor(a) de Aplicações Android | Instituto Eldorado

### ISSUE THREAD

**Issue by CynthiaAlvarenga** [androiddevbr/vagas#743]
Oportunidade para atuação em projeto junto à empresa multinacional da área de telefonia móvel, em contato frequente com times no exterior para execução das seguintes atividades:

- Desenvolvimento de novas funcionalidades para um aplicativo Android relacionado à área de Marketing e Vendas e aplicação envolvendo utilização dos sensores do smartphone para identificação de gestos;
- Prototipação e validação de funcionalidades.
- Revisão de código.
- Correção de bugs e adaptação de funcionalidades as novas versões de Android.  

**Requisitos:**

- Formação superior em Engenharia/Ciência da Computação, Sistemas de Informação, ou cursos similares;
- Experiência com desenvolvimento de aplicações Android;
- Experiência em ferramentas de controle de versão
- Inglês avançado para conversação, escrita e leitura.             

 **Local**

Campinas/SP

**Contratação**

CLT

**Nossa empresa**

O Eldorado é referência no Brasil em pesquisa, desenvolvimento e inovação nas áreas de software, hardware, ensaios e testes de produtos eletrônicos, com diversos prêmios como uma das Melhores Empresas para se trabalhar e começar a carreira! Venha fazer parte desta história que já tem 20 anos!

**Como se candidatar**

Basta acessar nosso site :)

https://www.eldorado.org.br/project/DesenvolvedorAndroid_87/

**Comment by jpventura** [comment]
@CynthiaAlvarenga Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar Vaga ainda está aberta.
