### ISSUE TITLE
[São Paulo - Distrito de Santo Amaro] Desenvolvedor(a) Android Kotlin - Vortigo

### ISSUE THREAD

**Issue by aaamenezes** [androiddevbr/vagas#744]
## Descrição da vaga

Empresa de desenvolvimento mobile contrata Desenvolvedor Android Sênior (nativo) para o distrito de Santo Amaro/SP.

## Local

São Paulo - Distrito de Santo Amaro
Presencial apenas

## Benefícios

- VT
- VR
- Plano de saúde

## Requisitos

Obrigatórios
- Experiência em desenvolvimento para Android (kotlin)
- Desenvolvimento de app's com conexão de serviços
- API's de terceiros 

Diferenciais
- Experiência em App's nativos para o segmento financeiro

## Contratação

CLT ou PJ

## Nossa empresa

Aqui na Vortigo, desenhamos e criamos apps iOS, Android, Cloud e Web.

## Como se candidatar

Gostou? Envie envie seu currículo para vaga-31836-10803@compleo.com.br

**Comment by lucas-inatel** [comment]
@aaamenezes a vaga é presencial, apenas?

**Comment by aaamenezes** [comment]
> @aaamenezes a vaga é presencial, apenas?

Sim :) Acabei de atualizar o texto

**Comment by jpventura** [comment]
@aaamenezes Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar Vaga ainda está aberta.
