### ISSUE TITLE
[Amsterdã - Holanda] Android Developer na Booking.com

### ISSUE THREAD

**Issue by henriquehsv** [androiddevbr/vagas#745]
## Descrição da vaga
We are looking for talented Android Developers to join our mobile team in our Amsterdam headquarters and help us to make the best travel app in the world! Our Android developers are given the freedom to make meaningful and measurable improvements to our top rated mobile app and impact more than 10 million users worldwide.

Our guiding principle is that by helping our users we help our business, so we listen to our customers and give them features they want to use.  As a developer in our mobile team you'll be a key part of the idea generation process, working in a small start up-like group which takes full ownership of its part of our platform. You'll be working on the iterative improvements we make as part of our high-speed release cycles, as well as looking ahead and implementing broader changes to our mobile app.

## Local
Amsterdã, Holanda - vaga presencial.

## Benefícios
We are a performance-based company that offers career advancement and lucrative compensation, including bonuses and stock potential.  We also offer what we call the “Booking Deal” with other competitive perks and benefits.  The Technology department offers training and attends/speaks at global conferences.

This position is open to worldwide candidates and in the case of relocation, we will assist you with a generous relocation package, ensuring a smooth transition to working and living in Amsterdam.  We have successfully relocated 300+ Technology professionals to Amsterdam in the last year!

## Requisitos
We expect our developers to know the ins and outs of the Android framework and to deliver polished products customers want to use. We need self-starters who are great at solving problems, initiate solutions and discussions and are not afraid of solving challenges due to our huge scale.

We have found that people who match the following requirements are the ones who fit us best:

- 5+ years of experience as a developer using Java and other languages
- At least 2-3 years of this experience must be from working with Android SDK
- Strong interaction and design sense, excellent attention to detail
- Self-motivated to explore new technologies, applications and environments
- Self-starter, highly motivated, team-player

### Diferenciais
- Experience with Android Market place & Distribution Process
- An approved Play store app
- SQL knowledge and/or willingness to learn
- Experience working with A/B testing
- You are passionate about open source and contribute
- You’re not afraid to solve deep technical challenges of a whole new level at a huge scale
- You have an intrinsic curiosity in technological innovations and you are always on top of the latest trends

## Nossa empresa
https://careers.booking.com/about-booking

At Booking.com we combine the best traits of a start-up with the resources of planet Earth’s #1 accommodation website. We are working towards building the ultimate travel experience, building and improving great products for both travelers and the accommodation partners.

## Como se candidatar
Enviar o currículo direto no site: https://grnh.se/5381f98f1

Estou a disposição pra tirar qualquer dúvida quanto a empresa por email ou hangouts henriquehsv@gmail.com - boa sorte aos candidatos

**Comment by henriquehsv** [comment]
@davidtcdeveloper oi David, pode adicionar `Visa Sponsorship`?

**Comment by jpventura** [comment]
@henriquehsv This issue has being inactive for over 3 months. If the job opportunity is still available, please comment **Opportunity still available**.

**Comment by henriquehsv** [comment]
Opportunity still available

**Comment by henriquehsv** [comment]
@jpventura, ainda estamos com vaga por aqui :)

**Comment by matheusbrandao** [comment]
Bom dia. É imprescindível ser fluente em inglês?

**Comment by henriquehsv** [comment]
@matheusbrandao Vc precisa ter proficiência pra se comunicar em inglês no ambiente de trabalho. Aqui na Booking tem gente de todo o mundo trabalhando, então vc vai precisar se comunicar com eles em inglês. Não precisa ser o inglês mais bonito do mundo, mas vc precisa compreender e ser compreendido.
