### ISSUE TITLE
[Ribeirão Preto, SP] Desenvolvedor(a) Android/iOS Ionic | Dart Digital

### ISSUE THREAD

**Issue by victoroliveira1605** [androiddevbr/vagas#746]
## Descrição da vaga

- Construir aplicativos com qualidade
- Analisar, sugerir e participar de discussões para entendimento da demanda
- Integrar equipe multidisciplinar para a concepção e evolução do produto

## Local

- Escritório Ribeirão Preto - SP

## Benefícios

- PPR semestral
- Vale refeição
- Auxílio convênio médico UNIMED
- Ambiente descontraído
- Estrutura ampla e moderna

## Requisitos

Obrigatórios

- Ter experiência com desenvolvimento de aplicativos móveis
- Ter experiência com Ionic
- Ter experiência com JavaScript
- Ter experiência com Angular

Diferenciais

- Ter conhecimento em Git e versionamento de código
- Ter experiência em UI e UX (Guidelines do Androide iOS)
- Ter um ou mais aplicativos publicados na Google Play ou Apple Store
- Ter conhecimento em Banco de Dados para aplicativos(SQLite)

É importante

- Ter vontade de crescer (ser inquieto)
- Gostar de desafios (trabalhar com diferentes perfis de projetos e clientes)
- Saber e gostar de trabalhar com autonomia

## Contratação

- CLT 

## Remuneração

- A definir após entrevista e avaliação técnica

## Como se candidatar

Por favor envie um email para  rh@dartdigital.com.br com seu CV anexado - 
enviar no assunto: Vaga Desenvolvedor Mobile - Ionic

**Comment by davidtcdeveloper** [comment]
A empresa contratando é a dartdigital, certo?

**Comment by victoroliveira1605** [comment]
É sim

**Comment by jpventura** [comment]
@victoroliveira1605 qual o nível de senioridade pedido?

**Comment by victoroliveira1605** [comment]
@jpventura, Estamos procurando Pleno ou Sênior.

**Comment by jpventura** [comment]
@victoroliveira1605 Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar **Vaga ainda está aberta**.
