### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android [PLENO] | VISÃO GRUPO

### ISSUE THREAD

**Issue by Brunobcoutinho** [androiddevbr/vagas#748]
## Descrição da vaga

Atuar com manutenção e desenvolvimento de aplicativos para Android, em ambiente nativo (Android Studio) com arquitetura MVC, publicação e controle de versionamentos na playstore.

## Local

Escritório - Av.Paulista

## Benefícios

- Horário de 40hs semanais, iniciando as 09h30;
- Vale Refeição;
- PLR;

## Requisitos

Obrigatórios
- Experiência anterior com publicação e versionamento de APPs
- Conhecimento em Java e Json

Desejáveis
- Conhecimento em arquitetura MVC

## Contratação

CLT - A partir de R$ 5.000,00

## Nossa empresa

Empresa de serviços, consultoria e soluções em tecnologia focada em resultados. Possuímos como core business o desenvolvimento de sistemas de ponta para a indústria farmacêutica, sendo uma empresa INOVADORA que oferece inteligência de mercado para negócios inteligentes no segmento farmacêutico. Nos posicionamos no mercado como um estúdio de tecnologia, em oposto à uma empresa de outsourcing de T.I. 

Atualmente, somos fornecedores de ferramentas de vendas, visitação, captação de pedidos e geração de demanda para alguns dos maiores laboratórios, nacionais e multinacionais. Presentes nos mais diversos setores do mercado, operamos tanto com a integração via ERP com laboratórios que realizam a venda direta, quanto com a integração direta via webservice com distribuidoras parceiras, nacionais e regionais, para laboratórios que trabalham com operação logística.

Hoje, transacionamos bilhões de dólares por ano em pedidos, além de milhares de pedidos diários, trabalhando de perto com as grandes distribuidoras e indústrias farmacêuticas presentes no território nacional.

## Como se candidatar

Por favor envie um email para atendimento@visaogrupo.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by lucas-inatel** [comment]
A vaga é somente presencial?

**Comment by lucas-inatel** [comment]
Olá @Brunobcoutinho, tudo bom? Amigo, a vaga é somente presencial?

**Comment by Brunobcoutinho** [comment]
Ola Lucas, seria presencial sim, você tem disponibilidade na cidade de São Paulo?

 


 <http://www.visaogrupo.com.br/> 



Bruno Bernardi Coutinho


Gerência de Projetos


 <mailto:bruno.coutinho@visaogrupo.com.br> bruno.coutinho@visaogrupo.com.br


Websolutions & Softwares - Av. Paulista, 1765 cj. 32 - São Paulo - SP - CEP. 01311-200 - Tel / Fax: (11) 3263-0044


Esta mensagem (incluindo quaisquer anexos) é endereçada somente para o(s) destinatário(s) acima identificado e talvez possa conter informação privilegiada ou confidencial protegida por lei. Favor estar ciente que a leitura não autorizada, divulgação, cópia ou distribuição deste e-mail ou o uso das informações aqui contidas estão proibidas e podem violar os direitos do proprietário. Caso você não seja o destinatário, favor retornar a mensagem para o remetente e removê-la imediatamente. Obrigado.


This e-mail (including any attachments) is intended for the addressee(s) stated above only and may contain confidential information protected by law. You are hereby notified that any unauthorized reading, disclosure, copying or distribution of this e-mail or use of information contained herein is strictly prohibited and may violate rights to proprietary information. If you are not an intended recipient, please return this e-mail to the sender and delete it immediately hereafter. Thank you.

**Comment by lucas-inatel** [comment]
Nossa @Brunobcoutinho infelizmente não tenho, mas vou passar adiante para alguns colegas. Muito obrigado.

**Comment by jpventura** [comment]
@Brunobcoutinho Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar **Vaga ainda está aberta**.
