### ISSUE TITLE
[Stockholm, Sweden] Senior Android Developer - Instabridge

### ISSUE THREAD

**Issue by thiagokimo** [androiddevbr/vagas#75]
## Descrição da vaga

Instabridge is building the world's best wifi client and the world's largest virtual wifi network. We're funded by some of Europe's leading investors and are now looking for a highly skilled Android developer to join our small but ambitious team.

At Instabridge the Android app is not an afterthought and not a clone of an iOS app. It's the main focus of the company. Your work will be absolutely central to what we do.

We are based in Stockholm, Sweden, but we want to hire the best developers out there, and that means not limiting our search to a single, small Scandinavian capital. If you want to move here to work with us, that’s great. If you want to stay where you are, that’s also fine. As long as you ship code, you can work from wherever you like.
## Local

Stockholm - Sweden
## Benefícios
- An opportunity to get in on the ground floor on one of Europe’s hottest startups (we didn’t say it, blame Wired!)
- Work on stuff that your friends, family and colleagues will use
- Competitive pay and generous stock options program
- Flexible work hours
- A small but very diverse team
- Fun!
### Technical Skills
- 2+ years Experience in Android development
- Full understanding of Android Apis and SDK
- Firm grounding in algorithms and data structures
- Understanding of computer security principles
- Pride in writing beautiful and maintainable code
- Git
- RxJava
- Automation
#### Driven

Your friends ask you how you manage to do all the things that you do, and you believe that magic happens outside your comfort zone. You work hard, especially when nobody is watching.
#### Goal oriented

Winning drives you. And you love a challenge. When you fail you see how you can learn and improve, and then you get back up on the horse.
#### Entrepreneurial

You thrive when you have big responsibilities and much freedom to put your ideas into practise.
#### Well organized

You are always on time, and you consider your calendar your best buddy on your way forward.
#### Positive

You see solutions where others see hinders, you energy is contagious, and you start every day with a smile ;) You believe that the future is bright, and that it's up to each and every one of us, to make it as good as it can be.
## Contratação

Full time employment
### Internet for Everyone

Our vision is to bring internet to everyone. Internet should be a basic human right - it removes barriers, gives people better health and removes inequality. Together with our community we are crowdsourcing the world's largest wifi network. Join us!
## Como se candidatar

Follow the instructions at http://jobs.instabridge.com/jobs/4111-senior-android-developer

**Comment by walmyrcarvalho** [comment]
@thiagokimo Essa vaga ainda está aberta? Senão, irei fechá-la pra fins de organização!

**Comment by thiagokimo** [comment]
Puts, só agora vi a mensagem @walmyrcarvalho. 
A vaga ainda está aberta :)

**Comment by jpventura** [comment]
@thiagokimo se quer otimizar as contratações, eu diria pra criar outro _issue_ com a mesma descrição.

Como você abriu em 2016, ele está na última página. Vou deixar aberto, mas se preferir pode repostar e fechar esse.

**Comment by marciofermino** [comment]
Analista de Sistemas com experiência Pleno / Sênior

Procuro oportunidade.

Android
iOS
Java

Obrigado.

Telefone / whatsapp 43999014416.

**Comment by caiodev** [comment]
Acho que seria sensato fechar esse issue já que o link está expirado e já se passaram 2 anos

**Comment by thiagokimo** [comment]
Puts! Esqueci completamente dessa issue. 

Nós contratamos um dev pra essa vaga recentemente. Ela pode ser fechada :)

**Comment by jpventura** [comment]
@thiagokimo @caiodev a vaga tinha sido reaberta
