### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Android Sênior - Ciclic 

### ISSUE THREAD

**Issue by striker2x2** [androiddevbr/vagas#753]
## Descrição da vaga

Trabalhar no desenvolvimento de APP's nativo.

## Local

São Paulo - Vila Olímpia

## Benefícios

- Horário flexível
- Home Office 1 dia por semana
- BÔNUS ANUAL  (proporcional aos meses trabalhados e ao atingimento de metas)
- vale refeição
- vale alimentação
- Seguro de vida
- Seguro odontológico (opcional)
- Vale Transporte (opcional)
- Plano de previdência privada (opcional)
- Day Off (dia de aniversário)
- Gympass
- Auxílio creche/babá

## Requisitos

Obrigatórios
- Padrão MVP(Clean Architecture)
- Experiência com Kotlin
- Injeção de dependência (Dagger 2)
- Git Flow
- Integração contínua (Circle-ci)
- Componentização de views
- Uso de Apis Restful (Retrofit 2)
- Testes Unitários (Mockito)

Desejáveis
- Experiência com Espresso e UI Automator
- Experiência com RxJava
- Conhecimentos em MVC, MVVM e derivados

Diferenciais
- Conhecimentos em Swift 

ESCOPO DE TRABALHO
- Suporte ao desenvolvimento de todo ciclo de vida das apps (concepção,
design, codificação, teste, release e manutenção).
- Desenvolver apps com as melhores práticas do mercado (Andorid e/ou iOS).
- Escrever testes automatizados
- Estar sempre atualizado e antenado com as novas tecnologias de mercado.

## Contratação

(Nível Sênior) - CLT a combinar

## Nossa empresa

A Ciclic nasceu com o propósito de revolucionar o mercado ao conseguir traduzir e materializar os sonhos de todos os nossos clientes dando a eles uma experiência única e inovadora  por meio do nosso primeiro produto de Previdência Privada. 

Nossos acionistas são o Banco do Brasil e a PFG (Principal Financial Group), que se destacam no mercado financeiro, garantindo a solidez e toda estrutura necessária para o nosso crescimento.

## Como se candidatar

Por favor envie um email para felipeavila@ciclic.com.br com seu CV anexado - enviar no assunto: Vaga Android SR

**Comment by jpventura** [comment]
@striker2x2 Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar Vaga ainda está aberta.

**Comment by striker2x2** [comment]
Vaga ainda está aberta
