### ISSUE TITLE
[Curitiba, Paraná] Desenvolvedor Android - TCS Tata

### ISSUE THREAD

**Issue by rsalomao2** [androiddevbr/vagas#758]
## Descrição da vaga

Projeto de desenvolvimento e manutenção do setor financeiro com mais de 1 milhão de usuários e crescimento maior que 5 mil novos por dia.
Será responsável por realizar manutenção de código e criação de novas funcionalidade, de acordo com a demanda.

## Local

Curitiba - PR

## Benefícios

- Horário semi-flexível
- VR/VT/VA
- Plano de saúde Sulamérica
- Plano dentário Sulamérica
- Auxílio a creche
- Lanche manha/tarde
- Plataforma de treinamento

## Requisitos

Obrigatórios
- 2+ anos de experiência com Android
- Java
- Orientação a Objeto
- Realm
- Retrofit
- Git
- Clean Code

Desejáveis
- Experiência com padrão MVP, MVC, MVVM e derivados

Diferenciais
- Aplicativo para mostrar

## Contratação

CLT

## Nossa empresa

Multinacional do setor de outsourcing em TI. Para trabalhar com cliente local do ramo financeiro. Projeto grande com mais de 20 desenvolvedores e mais de 1 milhão de usuário.

## Como se candidatar

Por favor envie um email para rsalomao2@gmail.com com seu CV anexado - enviar no assunto: Vaga Android - Nome Completo

**Comment by jpventura** [comment]
@rsalomao2 Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar **Vaga ainda está aberta**.
