### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android [PLENO| SENIOR] | BRQ

### ISSUE THREAD

**Issue by Noemivandalete** [androiddevbr/vagas#759]
Desenvolvedor Android (PL e SR)

Região da Faria Lima - SP

Benefícios: R$ 2.095,00 a ser distribuído de acordo com a necessidade e realidade do candidato.

Requisitos

Obrigatórios
Desenvolvedor(a) capaz de elaborar soluções de arquitetura MVC ou MVP para Android; 
•  Experiência com processo de publicação da aplicação para Google Play (Beta Test e Produção);  
• Desejável experiência com bibliotecas para interação com câmera, localização, gráficos e http client. 
  • Conhecimentos de Programação Orientação Objetos e Design Patterns 
• Conhecimentos da linguagem de programação Kotlin

Contratação

CLT (de 5k a 9k)

Nossa empresa

Aqui na BRQ prezamos pelo bem estar dos nossos alocados. 
Benefícios de acordo com a necessidade do profissionais
26 anos de mercado
E muita paixão por tecnologia

## Como se candidatar

Por favor envie um e-mail para noemivm@brq.com com seu CV anexado - enviar no assunto: Vaga Android
ou me chame via Whatsapp: 11 5278-8877

**Comment by jpventura** [comment]
@Noemivandalete Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar **Vaga ainda está aberta**.
