### ISSUE TITLE
[São Paulo] - Vagas para Desenvolvedor Android 

### ISSUE THREAD

**Issue by giseledosanjosrh** [androiddevbr/vagas#76]
## Descrição da vaga

Cliente de grande porte contrata desenvolvedor mobile para a região da Zona Sul de São Paulo.
## Local

Próximo da estação Vila Olímpia 
## Requisitos

Obrigatórios
- Experiência  com desenvolvimento de app's utilizando Java,  Android SDK, POO e Design Patterns; 
- Consumo de APIs Restful;
- Testes (Espresso, Roboletric, JUnit).

Desejáveis
- Refactoring e TDD
- Automatização de testes unidade, integração e funcional.
## Contratação

PJ 
## Como se candidatar

Por favor envie um e-mail para gisele.anjos@5a.com.br  com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@giseledosanjosrh Temos o template das vagas para facilitar a classificação das mesmas e a pesquisa pelos interessados. Sugiro detalhar melhor as vagas com os campos do template. 
Se preferir, pode criar uma issue para cada vaga, como forma de deixar mais detalhado.
Pedimos também que foque nas vagas de Android ;)

**Comment by giseledosanjosrh** [comment]
@davidtcdeveloper obrigada :-D

**Comment by walmyrcarvalho** [comment]
@giseledosanjosrh Essa vaga ainda está aberta? Senão, irei fechá-la pra fins de organização!
