### ISSUE TITLE
[SÃO PAULO] Desenvolvedor(a) Moblie Android Pleno/Senior [Entelgy] 

### ISSUE THREAD

**Issue by pess0a** [androiddevbr/vagas#761]
## Descrição da vaga

- Será um dos responsáveis pelo desenvolvimento e aperfeiçoamento de aplicativos em
Android em Java/Kotlin
- Executar a manutenção fazendo eventuais correções necessárias, visando atender às
necessidades dos usuários
- Desenvolver trabalhos de montagem, depuração e testes em programas a serem desenvolvidos;

## Local

Av. Angélica próximo da Avenida Paulista

## Benefícios
- Vale-refeição
- Vale-transporte
- Assistência médica
- Assistência odontológica

## Requisitos

- Experiência no desenvolvimento de aplicações para dispositivos Android
- Sólidos conhecimentos em Java
- Confortável com padrão MVP e derivados
- Experiência com testes unitários e testes automatizados

## Desejáveis
- Conhecimentos em Kotlin
- Experiência com a cultura DevOps, Entrega e Integração Contínua. 
- Experiência com liderança de times de desenvolvimento. ( caso senior )

## Contratação

CLT

## Nossa empresa

Entelgy é um grupo inovador de Consultoria, Outsourcing e Tecnologia de âmbito internacional, tendo como missão aportar a maior satisfação aos seus Clientes e Profissionais.

Com matriz na Espanha, a Entelgy continuou sua expansão no mercado latino-americano constituindo Entelgy Brasil, Entelgy Chile, Entelgy Colômbia,  Entelgy Peru e Entelgy México.

## Como se candidatar

Por favor envie um email para felipe.pessoa@entelgy.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@pess0a Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar **Vaga ainda está aberta**.
