### ISSUE TITLE
[Interlagos, SP] Desenvolvedores Android - Santander Digital

### ISSUE THREAD

**Issue by douglasbento** [androiddevbr/vagas#762]
## Descrição da vaga

A Resource IT está com oportunidades para Desenvolvedores Android para atuação em projeto de longa duração no Santander (Espaço Geração Digital Santander).

## Local

Santander - Av. Interlagos, 3501 - Bloco 10 – Térreo – Bairro Roxo

## Benefícios

•	Vale Refeição: R$ 440,00 / Mês (sem desconto)
•	Vale Transporte
•	Assistência médica: Sul America Exato plano apartamento (sem desconto) com coparticipação. 
•	Assistência Odontológica: Porto Seguro (sem desconto). 
•	Seguro de vida em Grupo: Porto Seguro

## Requisitos
ANDROID STUDIO GIT
FIREBASE 
CRASHLITYCS

## Contratação

CLT Full

## Nossa empresa

Venha fazer parte do time de Inovação Digital da Resource, uma das maiores integradoras digitais do Brasil e uma as empresas de TI que mais crescem no País. Com 25 anos no mercado, multinacional brasileira com presença global, com 21 escritórios em 5 países. Também está presente no Vale do Silício com um avançado Centro de Pesquisa e Inovação, o que possibilita estar cada vez mais próxima do cliente, entender melhor o seu negócio e oferecer a melhor solução.

## Como se candidatar

Enviar o CV atualizado com pretensão salarial CLT Full para douglas.bento@resourceit.com

**Comment by jpventura** [comment]
@douglasbento Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar **Vaga ainda está aberta**.
