### ISSUE TITLE
[Maringá, PR] Desenvolvedor(a) Android [JR, PL, SR] | UDS Tecnologia

### ISSUE THREAD

**Issue by denisgasparoto** [androiddevbr/vagas#763]
## Descrição da vaga

Buscamos profissionais com perfil crítico, com forte orientação a qualidade e padrões de projeto. Desejável interessado em plano de carreira rumo a lideranças técnicas.

## Local

Remoto [PL, SR] ou Alocado em Maringá, Paraná [JR, PL, SR]

## Requisitos

- Experiência e bons conhecimentos em orientação a objetos, padrões de projeto (design patterns) e arquitetura de software (MVP, MVVM...);
- Experiência em Java Android e Android Studio;
- Bons conhecimentos em Android API; 
- Conhecimento em Kotlin;
- Conhecimentos em Retrofit, RxJava, Dagger, Realm, Espresso, Mockito; 
- Conhecimentos em componentes UI (Material design, Estilização de componentes nativos); 
- Conhecimentos em construção de componentes visuais customizados; 
- Experiência em construção de telas dinamicamente (via código); 
- Conhecimento das melhores práticas recomendadas pelo Google para tela, navegação, acesso a dados e desempenho; 
- Consumo de API REST;
- Domínio do SQLite e banco de dados SQL; 
- Persistência local de dados (Realm, DBFlow;.
- Conhecimentos em estrutura de dados e algoritmos de ordenação; 
- Conhecimentos em ferramentas de controle de versão Git; 
- Experiência de trabalho em projetos com metodologia Ágil.

Diferenciais
- Ionic, React Native

## Contratação

- CLT ou PJ

## Nossa empresa

Somos uma empresa brasileira de tecnologia, com quase 20 anos de experiência, especializada no desenvolvimento de softwares e aplicativos mobile personalizados. Somos uma das pioneiras no mercado de TI e desde o início mantemos nosso comprometimento com a inovação.

## Como se candidatar

Currículos com assunto Android e pretensão salarial para vagas@uds.com.br

**Comment by jpventura** [comment]
@denisgasparoto Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar **Vaga ainda está aberta**.
