### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android [PLENO, SÊNIOR] RADAR PROFISSIONAL

### ISSUE THREAD

**Issue by RADARProfissional** [androiddevbr/vagas#764]
Descrição da vaga
Buscamos profissionais com forte orientação a qualidade e padrões de projeto. Desejável interessado em plano de carreira rumo a lideranças técnicas.

Local
Vila Olímpia 

Requisitos

•	Superior completo em Administração, Análise de Sistemas, TI ou áreas afins;
•	Experiência com desenvolvimento Android, JAVA e Kotlin, integrações de APIs, RESTful e SOAP, controle de versão no Git e gerenciamento de dependências (Gradle); 
•	Vivência com adaptações de layouts entre Smartphones e Tablets e testes automatizados (unitários e de interfaces);
•	Experiência em metodologias ágeis (SCRUM e Kanban) e que tenha publicações de versões na Play Store;

•	Será considerado como diferencial, 

o profissional com conhecimento em arquitetura MVP e Android Architecture Components.

Contratação
CLT 

Como se candidatar
Currículos com assunto Android e pretensão salarial para vagas@radarprofissional.com.br

**Comment by davidtcdeveloper** [comment]
@RADARProfissional as regras da nossa comunidade exigem a divulgação do nome da empresa contratante, pedimos que a descrição seja editada para constar o nome da empresa.

**Comment by davidtcdeveloper** [comment]
Vaga encerrada devido a informações incompletas.
