### ISSUE TITLE
[Águas Claras, DF] Desenvolvedor Android (JR) | Advances Solutions

### ISSUE THREAD

**Issue by Cabulozo** [androiddevbr/vagas#765]
## Descrição da vaga

Projeto de desenvolvimento de APP de reconhecimento de Imagem e Audio

## Local

Brasília - Águas Claras

## Benefícios

- 2 horas de almoço
- monte a sua máquina como desejar
- sala de jogos
- ambiente descontraido

## Requisitos

Obrigatórios
- Rest API
- Firebase
- Analytics
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis
- Experiência com React Native e Flutter
- Experiência com Ruby

Diferenciais
- Projetos opensource

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para vagas@advances.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@Cabulozo De acordo com as regras da nossa comunidade, é obrigatório divulgar o nome da empresa contratante. Pedimos que edite a descrição para que conste o nome da empresa.

**Comment by Cabulozo** [comment]
> @Cabulozo De acordo com as regras da nossa comunidade, é obrigatório divulgar o nome da empresa contratante. Pedimos que edite a descrição para que conste o nome da empresa.

@davidtcdeveloper o nome da empresa está no e-mail. Vou detalhar melhor.

**Comment by jpventura** [comment]
@Cabulozo Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar **Vaga ainda está aberta**.
