### ISSUE TITLE
[Metrô Brigadeiro, SP] Desenvolvedor Android | MC1

### ISSUE THREAD

**Issue by vitortane** [androiddevbr/vagas#766]
DESENVOLVEDOR ANDROID - SP PAULISTA - CLT

MC1 - A MC1 é especializada em automação de processos comerciais e inteligência de vendas com foco no aumento de produtividade nas operações em campo.

**REQUISITOS E QUALIFICAÇÕES**

•	Superior completo com no mínimo 2 anos de formado;
•	Razoável experiência e **grande conhecimento em orientação a objetos**, padrões de projeto (design patterns) e arquitetura de software;
•	Razoável experiência em Java Android;
•	Experiência tanto em IDE Eclipse quanto Android Studio;
•	Bons conhecimentos em Android API;
•	Conhecimentos em componentes UI Layout/List/Fragment/Provider;
•	Conhecimentos em construção de componentes visuais customizados;
•	Experiência em construção de telas dinamicamente (via código);
•	Conhecimento das melhores práticas recomendadas pelo Google para tela, navegação, acesso a dados e desempenho;
•	Domínio do SQLite e banco de dados em geral (SQL);
•	Fortes conhecimentos em estrutura de dados e algoritmos de ordenação;
•	Conhecimentos em ferramentas de configuração de software (SVN, Git);
•	Conhecimentos em ferramentas de gestão de bugs (Bugzilla, Jira);
•	Conhecimentos em automatização de testes TDD;
•	Facilidade para trabalho em equipe;
•	Forte senso de organização;
•	Experiência de trabalho em projetos com metodologia Ágil

**BENEFÍCIOS**
VR ou VA. Convenio. Odontológico. Seguro de Vida. Refeitório para Marmita. 

**PROCESSO**
Currículo > Entrevista telefone > Entrevista Pessoal > Contratação

**CONTATO**
Enviar CV para vitor.tane@gsn.com.br com assunto "Desenvolvedor Android SP"

**Comment by davidtcdeveloper** [comment]
@vitortane De acordo com as regras da nossa comunidade, é obrigatório divulgar o nome da empresa contratante. Pedimos que edite a descrição para que conste o nome da empresa.

**Comment by vitortane** [comment]
Obrigado! Alterado.

**Comment by jpventura** [comment]
@vitortane qual o nível de senioridade procurado?

**Comment by jpventura** [comment]
@vitortane Essa vaga está inativa por 3 meses. Caso a vaga ainda não tenha sido preenchida, basta comentar **Vaga ainda está aberta**.
