### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android Pleno/Sênior e Líder - Studo +

### ISSUE THREAD

**Issue by mayksalles** [androiddevbr/vagas#78]
## Descrição da vaga

Desenvolvimento de aplicativo para a área educacional 
## Local

Escritório São Paulo - Próximo ao metro Santa Cruz
## Requisitos

Obrigatórios
Experiência em desenvolvimento de apps mobile nativos Android.
Conhecimento prático sobre design patterns, refactoring e TDD.
Experiência pratica em consumo de APIS restfull.
Experiência com metodologias ágeis de desenvolvimento
*\*  Para o perfil de líder é necessário ter experiência com liderança de equipe  **
## Contratação

CLT 
## Como se candidatar

Por favor envie um email para maycon.salles@5a.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@mayksalles Boa tarde, a vaga seria pra qual empresa, pode informar? :)

**Comment by mayksalles** [comment]
Boa tarde!
Seria para a empresa Studo +
Você tem interesse em vagas em SP? Vi que você é do RIO.

2016-09-22 12:23 GMT-03:00 Walmyr Carvalho <notifications@github.com>:

**Comment by walmyrcarvalho** [comment]
@mayksalles Na verdade eu organizo esse repositório, só queria saber pra adicionar no título da vaga. Mas obrigado de qualquer forma! :)

**Comment by walmyrcarvalho** [comment]
@mayksalles Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by mayksalles** [comment]
Boa tarde!
Pode cancelar.
Obrigado.

Att

2017-04-08 21:52 GMT-03:00 Walmyr Carvalho <notifications@github.com>:
