### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android Pleno/Sênior 

### ISSUE THREAD

**Issue by mayksalles** [androiddevbr/vagas#79]
## Local

 Escritório São Paulo - Vila Olímpia
## Requisitos

Obrigatórios
Experiência com Android SDK
Conhecimentos sólidos em POO e Design Patterns
Consumo de APIs RESTful
Conhecimentos em testes (Espresso, Roboletric, JUnit)
Material Design
Bom raciocínio lógico
Git
TDD / BDD;

Desejáveis
APP publicado
## Contratação

PJ a combinar
## Como se candidatar

Por favor envie um email para maycon.salles@5a.com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@mayksalles Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!
