### ISSUE TITLE
Vaga de instrutor - HackaTruck MakerSpace (Instituto de Pesquisas Eldorado)

### ISSUE THREAD

**Issue by RafaelSermenho** [androiddevbr/vagas#793]
## Descrição da vaga
Atividades:
Fazer parte de uma equipe de projeto de capacitação profissional para estudantes de Instituições de Ensino Superior de Tecnologia da Informação, em desenvolvimento iOS (Swift) para aplicativos móveis, aplicações JavaScript, serviços cognitivos e Watson através da plataforma IBM Cloud, com aplicação em Internet das Coisas (IoT) em um espaço maker. O profissional deverá atuar ministrando a capacitação para o público citado e realizar atividades atreladas, possuir disponibilidade para viagens para diversas regiões do Brasil.

Oportunidade:
Se desenvolver em serviços cognitivos, IBM Cloud e IoT junto a equipe.

## Local
Campinas

## Requisitos
·        Formação superior concluída em Engenharia/Ciência da Computação, Sistemas de Informação ou similar;
·        Conhecimentos em desenvolvimento de soluções iOS utilizando Swift;
·        Inglês intermediário;
·        Disponibilidade para viagens.

## Contratação
CLT

## Como se candidatar
Enviar seu currículo para lucimara.almeida@eldorado.org.br com o título “Vaga HackaTruck”.

**Comment by davidtcdeveloper** [comment]
Este mural de vagas é focado em vagas para desenvolvedores Android. Como o texto não cita Android, estou encerrando a vaga.
