### ISSUE TITLE
[São Bernardo do Campo, SP] Desenvolvedor Android Sênior

### ISSUE THREAD

**Issue by jokapoa** [androiddevbr/vagas#795]
##  Responsabilidades:

Desenvolver aplicativos para Android , usando android nativo.
Criar testes unitários e instrumentados.
Identifique problemas, riscos e gerencie-os quando apropriado.
Promover e defender as melhores práticas dentro da equipe e em todo o negócio.
Esteja ciente de novas técnicas, algoritmos, tecnologias, ferramentas e bibliotecas, para melhorar sempre o código.
Local:  São Bernardo do Campo

## Requisitos 
• Android Studio.
• Bom conhecimento de Kotlin.
• Boa experiência com o Git.
• Conhecimento de bibliotecas do Android como Retrofit, RxJava.
• Conhecimento de padrões de arquitetura como MVP e MVVM.
• Conhecimento de Testes Unitários e Testes Instrumentados.
• Experiência com a API RESTful.

Desejáveis

Conhecimento do Android JetPack (Componentes de Arquitetura é importante).
• Experiência com metodologias ágeis, como Kanban e Scrum.
• Capacidade de continuar aprendendo novas tecnologias.

A empresa é uma Multinacional da área de tecnologia, com projetos diferenciados voltados para iOT, inovação e indústria 4.0

## Contratação:

CLT + pacote completo de benefícios

## Como se candidatar

Por favor envie um email para mobile@holdenrh.com.br com seu CV anexado 
ou mais informações  com  Jonas ou Romario, no fone ( 11)-994017411 ou 5102-2229

**Comment by davidtcdeveloper** [comment]
@jokapoa As regras deste mural de vagas exigem que o nome da empresa contratante seja divulgado. Peço que a vaga seja editada com o nome da empresa para que a mesma seja reaberta.
