### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Android [SENIOR] | XDS

### ISSUE THREAD

**Issue by limarachel** [androiddevbr/vagas#796]
## Descrição da vaga

Projeto de desenvolvimento para empresa voltada para o setor de tecnologia.

## Local

Alocado em São Paulo, próximo ao metrô Conceição - Zona Sul 

## Requisitos

- Desenvolver Android nativo em linguagem Kotlin;
- Experiência com base de dados;
- Senoridade pleno/senior;
- Experiência retrofit, dagger, event bus, fragments, layout constraints;
- Experiência com arquitetura MVP;
- Testes com MockK e espresso;
- Experiência em projetos com metodologia ágil (SCRUM).

## Contratação

Contratação PJ ou CLT;
Projeto inicial 6 meses;

## Como se candidatar

Por favor envie um email para welcome@joinus.com.br com seu CV anexado - enviar no assunto: Vaga Android Senior

**Comment by davidtcdeveloper** [comment]
@limarachel As regras do nosso mural de vagas exigem a divulgação do nome da empresa. Não ficou claro qual é a empresa contratante, por isso peço que adicione a descrição da mesma para que a vaga seja reaberta.
