### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Android Sênior | GAZEUS

### ISSUE THREAD

**Issue by AlineFerrer** [androiddevbr/vagas#8]
Descrição da vaga
**
RESPONSABILIDADES: **
- Desenvolvimento e manutenção de aplicativos para o sistema Android.

*_REQUISITOS:  *_
- Conhecimentos sólidos de estruturas de dados, algoritmos e arquitetura de sistemas;  
- Capacidade de aprender rapidamente diferentes linguagens e tecnologias; 
- Conhecimento da língua inglesa.  

*_CONHECIMENTOS ESPECÍFICOS: *_
-  Android SDK / API do Android em geral
- Ciclo de vida de activities e fragments
- Adaptação de layout entre diferentes tamanhos de tela
- Android Studio e Gradle
- Sólidos conhecimentos de Orientação a Objetos
- Conhecimentos das melhores práticas recomendadas pelo Google para o desenvolvimento de Apps
- Java 6
- Experiência de uso de sistemas de versionamento 

**CONHECIMENTOS DESEJÁVEIS:**
- Experiência com Git
- Material Design
- in-App Billing, Push Notifications, Services, Broadcast Receivers
- Java 7 e 8

**IRÁ SER CONSIDERADO UM DIFERENCIAL:**
- Experiência com desenvolvimento iOS;
- Saber se comunicar com eficiência entre diferentes áreas da empresa;
- Trabalhar de forma independente e pró-ativa como também em equipe;
- Se manter atualizado com as novidades da área de mobile.
## Local

Barra da Tijuca - Rio de Janeiro
## Benefícios
- Horário Flexivel
- sala de jogos
- Shiatsu 1x por semana
- frutas, guloseimas e sucos à disposição do time
- VR + VT + plano de saúde e odontológico
## Contratação

CLT
## Nossa empresa

Somos a maior empresa brasileira desenvolvedora de jogos casuais e sociais. Iniciamos as operações em 2006 na web com o site Jogatina.com. Em 2012, iniciamos o desenvolvimento de games para celulares e tablets com enorme resultado, expandindo nosso mercado para vários países.

Confira nossos jogos nas principais lojas:
https://play.google.com/store/apps/developer?id=Jogatina.com
https://itunes.apple.com/br/artist/gazzag-servicos-internet-ltda/id562305388

Além dos aplicativos, também somos responsáveis por dois sites de jogos:
www.jogatina.com
www.thesocialpoker.com
## Como se candidatar

Por favor envie um email para aline.ferrer@mosaicointernet.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@AlineFerrer Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by walmyrcarvalho** [comment]
@AlineFerrer Estou fechando essa vaga por falta de resposta, caso ainda esteja aberta me avise! :)
