### ISSUE TITLE
[São Paulo - SP] Programador Android Sênior 

### ISSUE THREAD

**Issue by Andrecouto2** [androiddevbr/vagas#80]
## Descrição da vaga

Desenvolvimento do novo aplicativo do BTG Pactual em plataforma nativa (Android), em modelo de célula ágil com profissionais de UX e Teste que também integraram a equipe. Através do aplicativo os clientes poderão realizar todas as transações disponíveis no banco assim como o não cliente realizar uma abertura de conta.
## Local

Escritório São Paulo - Faria Lima
## Benefícios
- 1 hora de almoço
- jornada de 40 horas semanais segunda-sexta feira
- plano de saúde \odontológico 
- vale alimentação
- vale refeição
- transporte
- seguro de vida 
- PLR
- previdência privada
## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis
-Refactoring e TDD
-Automatização de testes unidade, integração e funcional.

Diferenciais
- Projetos opensource
## Contratação

CLT FULL a combinar
## Nossa empresa

Terceira maior empresa de consultoria TI do Brasil.
## Como se candidatar

Por favor envie um email para andrecouto@brq.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@Andrecouto2 Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by Andrecouto2** [comment]
Pode fechar.Obrigado.

2017-04-08 21:51 GMT-03:00 Walmyr Carvalho <notifications@github.com>:
