### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Android

### ISSUE THREAD

**Issue by aline-navarro** [androiddevbr/vagas#811]
## Local

Escritório São Paulo - Paulista

## Requisitos

Obrigatórios
-Profissionais com domínio técnico de linguagens para o sistema KOTLIN;
- Necessário ter conhecimentos em Push Notifications;
- Autentificação (login e logout);
- Integração de APIs e publicação de aplicativos (Google Play);

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para aline.navarro@keepsimple.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@aline-navarro

- A empresa contratante é a Keep Simple?
- Qual o nível de senioridade buscado
- Qual a estação de metrô mais próxima?
