### ISSUE TITLE
[Porto Alegre, RS] Android Developer | Superplayer

### ISSUE THREAD

**Issue by Juliahickmann** [androiddevbr/vagas#819]
**Android Developer** na [Superplayer](http://www.superplayer.co)

No Superplayer nós temos a oportunidade de trabalhar com duas coisas fascinantes: Música (Arte) e Tecnologia (Ciência). 
A música nos prende pelo coração. Apesar de ser algo tão etéreo, ela tem o poder de mover multidões e dar cor a nossa vida. Já a tecnologia e a inovação são aquilo que impulsiona a humanidade, melhorando e simplificando a vida de todos nós. 

Buscamos um **Android Developer** capaz de arquitetar e construir interfaces que proporcionem a melhor experiência em aplicativos de música da plataforma Android, que seja apaixonado por aprender e codificar (em Java e Kotlin) e que goste de pensar no produto além das linhas de código.

Ela/ele será responsável por pensar, contribuir no planejamento e desenvolver novas funcionalidades no Superplayer para Android, trabalhar junto com nosso time de engenheiros na arquitetura e definição de soluções de alta escala e alta disponibilidade e utilizar as melhores práticas e tecnologias para escrever código que se orgulhará de ler amanhã. :)

Responsabilidades:
- Pensar, contribuir no planejamento e desenvolver novas funcionalidades no Superplayer para Android.
- Garantir, junto com nosso time de designers, a melhor experiência em aplicativos de música da plataforma.
- Utilizar as melhores práticas e tecnologias para escrever código que você se orgulhará de ler amanhã.
- Trabalhar junto com nosso time de engenheiros na arquitetura e definição de soluções de alta escala e alta disponibilidade.
- Resolver problemas e defeitos no Superplayer para Android e cuidar para que eles nunca cheguem em ambiente de produção.
- Ajudar seus colegas nerds a resolver problemas complexos.
- Definir, junto com todo o time do Superplayer, os caminhos de nossos produtos e nosso processo de desenvolvimento.

Requisitos:
- Paixão em escrever código e pela plataforma Android.
- Graduado(a) ou graduando(a) em alguma faculdade de informática: engenharia de software, ciências da computação, sistemas de informação, processamento de dados, análise de sistemas ou qualquer outra que ensine que 1 + 1 não é 2.
- Vivência com desenvolvimento de aplicativos para plataforma Android.
- Domínio de conceitos de OOP e conhecimento em conceitos de Functional Programming.
- Conhecimento sobre os guidelines de desenvolvimento e usabilidade da plataforma Android.
- ♡ Git.
- Habilidade de desenvolver aplicativos do seu início ao fim (desde New Project até APK > Upload new APK).
- Capacidade de planejar e desenvolver seu trabalho focando os objetivos estabelecidos em conjunto.
- Se sentir confortável com arquiteturas de desenvolvimento, tais como, MVP, MVC, MVVM, MVQC (MV Qualquer Coisa).
- Vivência com desenvolvimento em ambientes e times ágeis.
- Disponibilidade para trabalho em tempo integral.

Nossa cultura  :) 
A melhor forma de descrever o Superplayer é pelos seus valores: RISE (Resultados, Inovação, Simplicidade e Empreendedorismo). Somos empreendedores e não temos problemas em meter a mão na massa. Temos garra e determinação para fazer as coisas acontecerem. Somos orientados por fatos e dados, sem esquecer da importância do bom senso e da intuição. Sabemos que as pessoas trabalham melhor de maneiras diferentes, por isso respeitamos a individualidade de cada um e damos flexibilidade para as pessoas trabalharem da forma como produzem melhor. Para que isto funcione, entendemos que é necessário confiança nas pessoas, porém exigimos responsabilidade de todos. Acreditamos que a inovação e a criatividade florescem com a diversidade de estilos, conhecimentos e pensamentos. Incentivamos o trabalho em equipe, a cooperação e a participação de todos. Acreditamos em ter uma empresa enxuta, com alta produtividade individual. Por isso, tentamos prover o ambiente e recursos que estimulem cada um a atingir o seu melhor. Hoje, somos 16 Superplayers, apaixonados por música e tecnologia, baseadas em nossos escritórios em Porto Alegre e São Paulo ou remotamente no Rio de Janeiro, Goiânia e Londres.

Local: Porto Alegre, RS ou REMOTO
Contratação: CLT
Benefícios: VR/VA R$ 22,00/dia, VT, Plano de saúde

Como se candidatar: Se você se interessou, manda seu currículo, LinkedIn e/ou GitHub para julia@hickmannrh.com.br com o assunto Android Developer.

**Comment by davidmagalhaes** [comment]
Oii @Juliahickmann tudo bem?
Essa vaga ainda está disponível? enviei o CV para o email indicado.

**Comment by tiagobpompeo** [comment]
Essw preço deve ser de meia hora de trabalho por dia?

**Comment by tiagobpompeo** [comment]
Um salario de um dev android não baixa de 10.000 por mês, quem em sã consciência trabalharia por 20/dia, que loucura é essa? Estou errado

**Comment by tiagobpompeo** [comment]
Se for esse valor acima estão de sacanagem

**Comment by DaniloFurtado** [comment]
Esse valor de 22 dia acho que é o vale refeição.

**Comment by tiagobpompeo** [comment]
Ah ok, sorry

**Comment by Juliahickmann** [comment]
> Oii @Juliahickmann tudo bem?
> Essa vaga ainda está disponível? enviei o CV para o email indicado.

Oi David! Desculpe a demora aqui, mas já conversamos! A vaga segue aberta, te mantenho informado do andamento dela!

**Comment by davidmagalhaes** [comment]
Oi @Juliahickmann vi agora sua mensagem! Tá certo, no aguardo.
