### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android Sênior | TRADE FORCE SA

### ISSUE THREAD

**Issue by RodrigoSampaio** [androiddevbr/vagas#83]
## Descrição da vaga

Manutenção e desenvolvimento de novas features de um app de pesquisas em pontos de vendas. Liderança técnica para sugerir melhorias e refatorações.
## Local

Escritório São Paulo - Paraíso
## Benefícios
- Vale refeição
- Vale transporte\combustível
- Seguro saúde
- Seguro odontológico
- Seguro de vida
- Todos os benefícios sem desconto em folha
## Requisitos

Obrigatórios
- Profundo conhecimento em Java;
- 4+ anos de experiência com Android;
- Testes unitários com JUnit, Mockito, etc;
- Testes instrumentais Roboletric, Espresso, etc; 
- Git e Github;
- Confortável com padrão MVP, MVC, MVVM e derivados;

Desejáveis
- DI/IoC (Dagger 2)
- RxJava

Diferenciais
- Experiência com desenvolvimento de API REST(Node.js, ASP.Net Web API)
## Contratação

CLT FULL
## Nossa empresa

HISTÓRIA

A Trade Force é uma empresa jovem, que identificou no mercado uma necessidade de transformar a gestão de equipes de Trade Marketing. Seu know-how de mercado, aliado ao conhecimento técnico de desenvolvimento de sistemas, e sua incansável sede por inovação possibilitou a criação de uma ferramenta extremamente aderente aos negócios dos seus clientes, agregando valor à operação e extraindo todo o potencial estratégico dos PDVs.

O QUE FAZEMOS

Transformamos a maneira como as empresas fazem gestão de Trade Marketing, tornando os PDVs uma fonte estratégica de recursos para a tomada de decisão.

NO QUE ACREDITAMOS

Somos movidos pela inovação constante, tanto no sentido tecnológico como na forma de fazer negócios. Criamos parcerias que estimulam o crescimento mútuo, através de resultados mensuráveis, soluções descomplicadas e agilidade no atendimento.
## Como se candidatar

Por favor envie um email para rodrigo.sampaio@tradeforce.com com seu CV anexado - enviar no assunto: Vaga Android Sênior

**Comment by elisonj** [comment]
Poxa, se fosse remoto eu tava dentro.
