### ISSUE TITLE
[Moema, SP] Desenvolvedor(a) Android Pleno| Looke

### ISSUE THREAD

**Issue by thaishbrasil** [androiddevbr/vagas#848]
## [Moema - São Paulo -SP](https://goo.gl/maps/s3SZTWvyN6pASvQA6)

www.looke.com.br

## Requisitos
•	Ter pelo menos 3 anos de experiência com desenvolvimento de softwares 
•	Ter pelo menos 1 ano de experiência com desenvolvimento Android.
•	Ter experiência com desenvolvimento de apps nativo  
•	Sólidos conhecimentos em Java e ter conhecimentos em Kotlin

Com o que você vai trabalhar: 
Desenvolver aplicativos para Streaming de Videos em dispositivos com sistema operacional Android. 

Atividades: 
	Construir aplicações para Android utilizando Java / Kotlin
	Dominar a especificação do Material Design 
	Dominar o git flow 
	Implementar mockups do time de design, com atenção aos detalhes visuais e compatibilidade entre devices;
	Dominar o processo de deploy (Google Play Store).
	Priorizar e tratar bugs e exceções reportados em produção;
	Contribuir em decisões de arquitetura sobre novas partes do projeto.
	Experiência em integração com banco de dados, integrações com APIs RESTful.

##Desejáveis
Conhecimentos em desenvolvimento iOS com o objetivo de potencializar a curva de aprendizado dentro do nosso ambiente de desenvolvimento

•	Dominar técnicas de testes automatizados com Espresso e JUnit 
•	Experiência com ferramentas de integração continua 
•	Gradle
•	Familiaridade com processo de desenvolvimento de software ágil (como XP, Scrum e Kanban)
•	Experiência com desenvolvimento multiplataforma (Flutter, Xamarim, Cordova, Phonegap)

## Contratação
Indiferente 
CLT ou PJ

## Nossa empresa
Nossa Cultura:
Somos uma empresa jovem inspirada em tecnologias disruptivas. Oferecemos um ambiente de trabalho que Incentiva a inovação e a produtividade, garantido liberdade com responsabilidade.
O Looke é uma Plataforma brasileira. Multiplataforma.
Temos aplicativos de iOS, Android, TV conectada, Playstation, PC, Safari, Apple TV, Android TV.
Tudo isso a gente faz aqui. A gente faz a plataforma inteira.
Fazemos toda a parte de Encriptação, Decriptação, Encoding de vídeo.
100% dessa tecnologia, é nacional, proprietária da empresa e, é feita toda aqui com a gente.
Você, se vir a ser contratado, virá para trabalhar numa área específica de Android para atender essa plataforma.
O Streaming de Vídeo é o futuro da distribuição de Vídeo pela internet. O que a gente conhece hoje de distribuição linear de TV, aqueles canais que a gente contrata, isso vai acabar. 100% está se tornando internet. Está se tornando no mundo inteiro. Como a Netflix fez isso, a Amazon Prime, o próprio Itunes, o Google Play...
É com isso que a gente quer que você venha trabalhar.
Distribuição de Vídeo por internet.

## Como se candidatar

Por favor envie um email para thais.fernandes@looke.com.br  com seu CV anexado - enviar no assunto: Vaga Android

![android_2](https://user-images.githubusercontent.com/47364879/61823576-6eadea00-ae32-11e9-83ab-3fe70ea87c8c.png)

**Comment by davidtcdeveloper** [comment]
@thaisbrasil recomendamos adicionar sempre o estado e cidade no título da issue, para facilitar a pesquisa dos interessados.

**Comment by thaishbrasil** [comment]
> @thaishbrasil recomendamos adicionar sempre o estado e cidade no título da issue, para facilitar a pesquisa dos interessados.

Feito!! :))

**Comment by jpventura** [comment]
@thaishbrasil Qual o nível de senioridade buscado?

**Comment by thaishbrasil** [comment]
> @thaishbrasil Qual o nível de senioridade buscado?

Pleno para Senior!!
