### ISSUE TITLE
[Rio de Janeiro - RJ] Mobile Developer - Globo.com

### ISSUE THREAD

**Issue by ianromano** [androiddevbr/vagas#85]
## Descrição da vaga

A globo.com tem mais de 300 milhões de vídeos assistidos todos os meses, abrangendo desde o Globo Play e o Globosat Play até os portais G1, GE e GShow. Nossa área é Webmedia, e somos os responsáveis por realizar essa mágica, entregando para o nosso usuário vídeos de alta qualidade através de uma estrutura que agrega diversos componentes e serviços para aquisição, processamento e distribuição. Na ponta dessa estrutura está o Player, responsável direto pelo consumo de vídeos do usuário.

O Player é um componente complexo e altamente estratégico. Ele precisa funcionar em múltiplos browsers e devices mobile e TV, com suporte a múltiplos formatos de vídeos. Ele concentra e garante as regras de negócio de vídeo e deve funcionar em todas as aplicações web e nativas do Grupo Globo. Também é responsável, além de tocar o vídeo, pela segurança, criptografia, métricas e publicidade. Para quem gosta de desafios, é um prato cheio: existem desafios em todos os níveis!

Temos desafios de negócio: é preciso entender como funcionam os produtos, quais são os seus casos de uso e como os vídeos são consumidos pelo usuário final, e projetar uma interface com uma grande experiência de uso junto com nossos especialistas em UX.

Temos desafios técnicos em todas as camadas: a renderização visual, o projeto de arquitetura baseado em componentes e plugins, a necessidade de trabalhar com restrições no uso de recursos, como o baixo uso de memoria, tamanho mínimo do componente e baixo uso de bateria, pois é usado por apps nativas e web em aparelhos high-end e low-end, e a integração com toda a plataforma de vídeos de baixo nível, além de criar APIs e serviços que forem necessários.

O Player tem versões diferentes para as diferentes plataformas. Existe o Player web, escrito em Javascript, o Player iOS, escrito em Swift e o Player Android, escrito em Kotlin. Alguns serviços de backend são escritos em Scala. Para essa oportunidade, estamos procurando alguém para o Player Android.

Procuramos alguém que goste de pensar no usuário final, que se preocupe com a sua experiência de uso e, ao mesmo tempo, seja apaixonado pela engenharia de software.

Esta vaga é para o nosso escritório no Rio de Janeiro, Barra da Tijuca. Pessoas de qualquer parte do Brasil são muito bem-vindas - a globo.com tem uma grande quantidade de profissionais de diversos estados. Temos um pacote especial de benefícos para a mudança de pessoas de fora da cidade.
## Local

Barra, Rio de Janeiro - RJ
## Benefícios
- Plano de Assistência Odontológica
- Plano de Assistência Médica
- Vale Refeição
- Vale Transporte
- Vale Alimentação
- Previdência Privada
- Áreas de descompressão na empresa para que as pessoas se sintam mais a vontade, com sofás, poltronas, almofadas, um lugar bem descontraído com televisão, video game, totó
## Requisitos
- Escrever código limpo, de fácil manutenção, utilizando as melhores práticas de desenvolvimento de software.
- Procurar sempre criar para o Player a melhor experiência de uso para o usuário final, trabalhando de perto com os especialistas em UX.
- Atuar como um team-player, comprometendo-se com os objetivos do time e trabalhando em harmonia com todos.
- Colaborar com idéias e sugestões para soluções eficazes e criativas.
- Ajudar o crescimento do seu time, ensinando, capacitando e dando feedbacks.
- Colaborar com o time, a área e a empresa para criar um clima positivo e motivador.
- Compreender o funcionamento e as necessidades dos produtos que usam o Player.
- Compreender o funcionamento da plataforma de vídeo (serviços de backend e infraestrutura) e colaborar com a sua evolução.
- Estar sempre crescendo e se desenvolvendo tecnicamente e profissionalmente.

MUST HAVE:
- Ter sólidos conhecimentos e habilidades em algoritmos e estruturas de dados.
- Ter domínio de engenharia de software, princípios, boas praticas e padrões de arquitetura.
- Ter excelente conhecimento de redes, principalmente HTTP.
- Gostar de programar em todos os níveis do stack tecnológico.
- Ter pelo menos 4 anos de experiência com alguma linguagem de programação (Java, Objective-C, C/C++, C#, Kotlin, Scala, Groovy, Clojure, etc.)
- Pelo menos 2 anos de experiência com programação em um desses ambientes: Android, iOS, desktop nativo ou sistemas embarcados..
- Ter experiência com métodos ágeis e práticas de engenharia ágil.
## Contratação

CLT a combinar
## Nossa empresa

A Globo.com é o braço de internet das Organizações Globo, o maior conglomerado de mídia da América Latina. Baseada no Rio de Janeiro, a Globo.com desenha, desenvolve e mantém os maiores portais verticais da internet Brasileira, todos líderes em suas categorias - O portal G1, líder em notícias, Globoesporte.com, em esportes, GSHOW em vídeos, e Ego em notícias de celebridades. A empresa fornece ainda consultoria estratégica e suporte tecnológico a todas as demais empresas das Organizações Globo. É reconhecida por lidar com volumes altíssimos de tráfego, transmissões de vídeo ao vivo de larga escala, e é responsável pela maior audiência de vídeos online do país. - 45 milhões de acessos por dia; - 1.8 milhões de acessos por hora; - 32 mil acessos por minuto;

É uma empresa que visa o bem estar dos seus funcionários, nós temos áreas de descompressão para que as pessoas se sintam mais a vontade, com sofás, poltronas, almofadas, um lugar bem descontraído com televisão, video game, totó.

Toda quinta temos um campo reservado para após o expediente para que os praticantes de futebol possam usufruir.
## Como se candidatar

Basta aplicar pela 3days :)
é só clicar nesse [link](http://3days.com.br/talents/vaga/Globocom/Mobile-Developer/Sy-sj-ryx?utm_source=github_androiddevbr&utm_medium=email&utm_content=vaga_globocom&utm_campaign=oportunidade)

**Comment by walmyrcarvalho** [comment]
@ianromano Muito obrigado pela submissão de vaga. :) Coloquei algumas labels pra ajudar o pessoal a entender melhor a vaga, caso precise de algum ajuste é só falar! 👍

**Comment by walmyrcarvalho** [comment]
@ianromano Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by paulo101977** [comment]
@walmyrcarvalho O link da 3days está inacessível :(

**Comment by ianromano** [comment]
Olá @walmyrcarvalho pode fechar essa vaga por favor :) obrigado!
