### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Android | Bloov

### ISSUE THREAD

**Issue by glaucobloov** [androiddevbr/vagas#851]
## Empresa
Olá, nós somos a Bloov, nascemos porque ouvimos!
Uma startup com o propósito de expandir a maneira com que nos relacionamos com a música, unindo pessoas, tecnologia, dados e inteligência. 
Buscamos gente, que como nós, sejam apaixonados por música e tecnologia. 
Vem com a gente fazer parte dessa banda, desafiar as métricas, ritmos e revolucionar a forma com que experienciamos nossos shows.
#VivaMúsica
## Localização
Vila Olímpia
## Posição
Desenvolvedor Android Sênior
## Tipo de contratação
Presencial, CLT
###### Obrigatórios

- Kotlin;
- Gradle;
- RetroFit;
- Git / Gitflow;
- Consumir webservices REST;
- Dagger 2;
- Constraint Layout.

###### Desejáveis

- Unit Tests;
- UI Tests;
- Continuous Delivery;
- Continuous Deployment.

###### Diferenciais

- Conhecimento dos princípios SOLID;
- Experiência trabalhando com múltiplos targets e frameworks;
- Conhecimento de outros patterns arquiteturais;
- Ser músico ou apaixonado por música;

## Benefícios

- Assistência Médica;
- Assistência Odontológica;
- Seguro de Vida;
- Vale Refeição/Alimentação;
- Vale Transporte;
- GymPass.

## Como aplicar
Envie o seu currículo para: casting@bloov.com 

## Contato
Maiores informações ou dúvidas, entra em contato com a gente:
Glauco Moraes: glaucomoraes@bloov.com
Anna Fernandes: annafernandes@bloov.com

**Comment by vitordealmeida** [comment]
Oi @glaucobloov! Pode adicionar a região que o escritório fica em São Paulo?

**Comment by glaucobloov** [comment]
Já atualizei @vitordealmeida. Muito obrigado.
