### ISSUE TITLE
[Rio de Janeiro - RJ] Android Developer - Sua Música

### ISSUE THREAD

**Issue by rodrigohenriques** [androiddevbr/vagas#86]
## Descrição da vaga

Buscamos um profissional super motivado que tenha como objetivo construir o melhor produto do mundo.
## Local

Rio de Janeiro - Copacabana
## Benefícios
- Horário flexível
- Possibilidade de trabalho remoto
- Pizza toda terça-feira
###### Obrigatórios
- 1 ano ou mais de experiência com Android
- Ao menos 1 aplicativo publicado na play store
- Git & Git Flow
- POO
###### Desejáveis
- Reactive Extensions
###### Diferenciais
- Kotlin
## Contratação

CLT
## Nossa empresa

O Sua Música é um espaço para artistas divulgarem seus trabalhos. Nossa plataforma conta hoje com mais de 7 milhões de usuários ativos. 
## Como se candidatar

Por favor envie um email para rodrigohenriques@suamusica.com.br com seu CV anexado. 
Enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@rodrigohenriques Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by rodrigohenriques** [comment]
Pode fechar!

Em 08/04/2017 21:51, "Walmyr Carvalho" <notifications@github.com> escreveu:
