### ISSUE TITLE
[Florianópolis - SC] Pessoa Desenvolvedora Android [Júnior, Pleno e Sênior]

### ISSUE THREAD

**Issue by davidtcdeveloper** [androiddevbr/vagas#861]
## Descrição da vaga
Você busca entregar valor e superar os desafios?
Estamos em busca de pessoas com um mínimo de experiência profissional com a plataforma Android, interessadas em crescimento individual e coletivo da equipe.
Nosso time de desenvolvimento pode ser um lugar para você! 
As tecnologias que utilizamos são: 
- Android SDK "nativo"
- Kotlin++(Java--)
- RxJava
- OkHttp
- MVVM
- Data Binding
- git
- Mockito
- Mockk
- Sqlite
- WebSocket
- Google Play Services
- Jenkins
- muitas outras.

## Local
Florianópolis, SC com home office (semi-presencial). 
Remoto para o perfil adequado.

## O que oferecemos

Aqui na Involves oferecemos um ambiente com autonomia, onde a gestão confia na capacidade técnica de nossos Involvidos e atua de forma compartilhada, trazendo o time para as decisões. Esta autonomia nasceu dentro dos times, que têm liberdade tanto para escolher os processos quanto as tecnologias a serem utilizadas. Além disso, você poderá fazer home-office sempre que precisar.

Trabalhamos em times multidisciplinares e valorizamos a troca de conhecimento entre nossos Involvidos. Acreditamos que essa é a trilha que facilita o desenvolvimento tanto profissional quanto pessoal. Contamos com um ambiente seguro para compartilhar nossas lições aprendidas, onde os erros são vistos como oportunidades de melhorias e aumento de conhecimento.

### E claro, sendo um Involvido, quais benefícios você terá aqui dentro?

- Frutas fresquinhas todos os dias para o seu café da tarde e bolo às sextas-feiras
- Faz parte da nossa cultura o home-office; horário flexível; no dress code
- Apoio no seu desenvolvimento pessoal e profissional
- Cultura que valoriza o 1:1; feedback; diversidade; inclusão; causas sociais e valores humanos
- Área de lazer com video-game; mesa de sinuca; instrumentos musicais; piscina de bolinha; churrasqueira; cervejeira
- Benefícios flexíveis para massagem; pilates; yoga; ingresso de cinema; academia; terapia holística; jogos de tabuleiro; acupuntura
- Programa de participação nos resultados (PPR) duas vezes ao ano
- Vale transporte (sem desconto); Vale refeição e alimentação (sem desconto)
- Licença maternidade e paternidade estendidas; folga de aniversário
- Verba para capacitação, treinamento e participação em eventos
- Plano de saúde subsidiado pela empresa.

## Requisitos

Obrigatórios
- Conhecimento básico do Android SDK.
- Experiência (profissional ou não) com a plataforma Android.
- Conhecimentos sobre testes automatizados.

Desejáveis
- Experiência em uma ou mais tecnologias que usamos.

Diferenciais
- Conhecimentos avançados de arquitetura.

## Contratação

CLT a combinar

## Nossa empresa

A Involves foi a vencedora do prêmio Melhores Empresas para Trabalhar 2016, 2017 e 2018 da GPTW:
- Oitava Melhor empresa de T.I do Brasil na categoria médias
- Melhor empresa de SC de todos os ramos de atuação na categoria médias

INVOLVIDO: Ser INTELIGENTE com a MENTE ABERTA pensamento POSITIVO e FORA DO QUADRADO mangas da camisa levantadas PUNHOS CERRADOS com gana de VENCER olhar fixo no RESULTADO habitante do mundo Involves Tecnologia. Somos Involvidos de CORAÇÃO. Se você se sente assim, queremos você no time.

## Como se candidatar

Aplicar através do sistema https://jobs.kenoby.com/involves/job/desenvolvedor-android/5ad88fc84d9afb6e2bbbe14e

**Comment by rodrigo364** [comment]
Encerrou a vaga?

**Comment by rodrigo364** [comment]
No site não exibiu a vaga para desenvolvedor Android somente IOS

**Comment by davidtcdeveloper** [comment]
A vaga ainda está aberta, estou conferindo o que houve.

**Comment by rodrigo364** [comment]
Ta bem David, obrigado.

________________________________
De: David Tiago Conceição <notifications@github.com>
Enviado: sexta-feira, 2 de agosto de 2019 18:49
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: Rodrigo <digaorfl@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] [Florianópolis - SC] Pessoa Desenvolvedora Android [Júnior, Pleno e Sênior] (#861)


A vaga ainda está aberta, estou conferindo o que houve.

**Comment by davidtcdeveloper** [comment]
A vaga já voltou para o site, pequena falha de configuração :)

**Comment by rodrigo364** [comment]
Ok David, irei me inscrever agora.

________________________________
De: David Tiago Conceição <notifications@github.com>
Enviado: sexta-feira, 2 de agosto de 2019 19:04
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: Rodrigo <digaorfl@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] [Florianópolis - SC] Pessoa Desenvolvedora Android [Júnior, Pleno e Sênior] (#861)


A vaga já voltou para o site, pequena falha de configuração :)

**Comment by davidmagalhaes** [comment]
Oi! A vaga já foi preenchida?

**Comment by rodrigo364** [comment]
Quis dizer que a vaga já foi preenchida? entrei lá e não estava disponível.

________________________________
De: David Magalhães <notifications@github.com>
Enviado: sábado, 3 de agosto de 2019 20:22
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: Rodrigo <digaorfl@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] [Florianópolis - SC] Pessoa Desenvolvedora Android [Júnior, Pleno e Sênior] (#861)


Oi! A vaga já foi preenchida?

**Comment by davidtcdeveloper** [comment]
A vaga ainda está aberta, estamos com alguns problemas na configuração da mesma no site. Assim que estiver disponível novamente eu aviso aqui ;)

**Comment by davidtcdeveloper** [comment]
Pessoal, a vaga voltou para o site, resolvemos a configuração aqui.

**Comment by rodrigo364** [comment]
Ok, obrigado David.

________________________________
De: David Tiago Conceição <notifications@github.com>
Enviado: segunda-feira, 5 de agosto de 2019 10:37
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: Rodrigo <digaorfl@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] [Florianópolis - SC] Pessoa Desenvolvedora Android [Júnior, Pleno e Sênior] (#861)


Pessoal, a vaga voltou para o site, resolvemos a configuração aqui.
