### ISSUE TITLE
[São Paulo/SP - Zona Sul] Desenvolvedor Android Senior

### ISSUE THREAD

**Issue by gabimollo** [androiddevbr/vagas#87]
Senior Developer - Mobile (Android):

**Responsibilities**
Develop and maintain our native mobile apps (Android)
Consume RESTful APIs to implement new functionalities that enhance the quality of our product
Bring pixel perfect UI/UX into life

**Requirements**
5+ years of experience coding in relevant startups and/or personal projects
Relevant Startup experience
Advanced knowledge of Android Java

**Local de trabalho:** 
Vila Mariana

**Contratação:**
CLT Full 

**Benefícios:**
Salário competitivo
Oportunidade de ganhar Stock Options
Assistência médica
Gym Pass
Bonus para upgrade deconfiguração de notebook
Cozinha com chefe de cozinha
Ambiente fun

Interessados enviar cv para `gaby_mollo@hotmail.com`

**Comment by walmyrcarvalho** [comment]
@gabimollo Gabi, o email está correto? Parece que ele tá meio duplicado, imaginei que estivesse errado!

**Comment by gabimollo** [comment]
@walmyrcarvalho :  nao está certo, mas estou editando e nao está indo =(
O correto é gaby_mollo@hotmail.com

**Comment by gabimollo** [comment]
Obrigada por avisar @walmyrcarvalho . Agora deu certo. Tks =)

**Comment by walmyrcarvalho** [comment]
Vaga preenchida, issue fechada a pedido da @gabimollo. :)
