### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android - Work & Co

### ISSUE THREAD

**Issue by marceloatwork** [androiddevbr/vagas#88]
## Descrição da vaga

Buscamos desenvolvedores Android ( E iOS, caso queira indicar conhecidos ) de todos os níveis de experiência para projeto de larga escala com a Vivo no Brasil. 

Junior, Pleno, Senior, Lead / Principal 

## Local

Presencial em Escritório São Paulo - Vila Cordeiro / Brooklyn

## Benefícios

Plano de Saúde e Dental
VR
Acesso a vasto material de treinamento

## Requisitos

- Não ligamos para anos de experiência, ligamos para tipos de problemas que você já resolveu. Com ou sem ajuda, no prazo ou fora dele pois você buscava a melhor solução  possível. 

- Excelente conhecimento da plataforma e seus fundamentos. Ter utilizado ou experimentado seus principais Frameworks e APIs. Realmente buscamos aqueles que foram além dos tutoriais online e realmente se aprofundaram na plataforma. Entendem as nuances da plataforma, e já encaram aqueles problemas chatos que só conhecemos e resolvemos quando estamos com a mão na massa de verdade.

- Como temos um foco em experiência do usuário, conhecimentos que são relevantes para a interface de usuário e apreço por criar interfaces novas com o time de design  são cruciais.

- Git 

- Conhecimentos de Design Patterns e arquiteturas proporcionais ao seu nível

Desejáveis
- Experiência com frameworks de terceiros ( Analytics / Reports / etc )
- Inglês Técnico ( leitura ) 
- Experiência com otimização ( performance ) 

Diferenciais
- Experiência / Conhecimento em RxJava
- Projetos pessoais em Android que mostrem sua paixão por experimentar e aprender

## Contratação

CLT full 

## Nossa empresa

[Work & Co](http://work.co) : Empresa dos Estados Unidos começando sua presença em São Paulo. Estamos no nosso terceiro ano de vida e já contamos com 176 pessoas em 3 países. 
Nossa cultura é pautada na meritocracia, respeito e principalmente na mão na massa. 

Nosso foco é a criação  e o  desenvolvemos produtos digitais para as maiores empresas do mundo. Não trabalhamos como produto de Agências. Somos independentes. Não somos uma Agência, não fazemos nenhum tipo de Marketing ou Social Media, apenas produtos.

Estamos organizados em somente 3 áreas: Estratégia, Design e Tecnologia, com pesos iguais.

Clientes Globais: Virgin America, Google, Facebook, Apple, Epic Games, Nike, Youtube...
Clientes no Brasil: Vivo, Santander, Descomplica, Oi

Case da Virgin America: [VA Case](https://work.co/virgin-america/)
Nossa perspective em desenvolvimento de apps: [The Next Web: the app that makes flying fun again/](http://thenextweb.com/insider/2016/09/29/the-app-that-makes-flying-fun-again/)

## Como se candidatar

Mande email com CV básico + Código ( Github ou similar  ) para:
eduardo@work.co 

Process (rápido!)

1. avaliação do código submetido
2. Entrevistas com Desenvolvedores da Work & Co
3. Opcional (caso material não seja suficiente) : Teste simplificado ( code review )
4. Entrevistas com Sócios
5. Proposta
6. Boom!

**Comment by zontag** [comment]
@marceloatwork possibilidade de trabalho remoto?

**Comment by walmyrcarvalho** [comment]
@marceloatwork Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!
