### ISSUE TITLE
[São Paulo]- Desenvolvedor(a) iOS Pleno- GFT

### ISSUE THREAD

**Issue by Befresche** [androiddevbr/vagas#887]
Descrição da vaga

Projeto de desenvolvimento de um app .

## Local

Jabaquara- SP

Benefícios
- VR ou VA;
- Convênio Médico Bradesco;
- Convênio Odontológico;
- Auxílio Creche;
- Plano de Previdência Privada;
- Seguro de vida em Grupo;
- Estacionamento;
- Cartão Multibenefícios ;
- Gympass de 50%
- Bolsa de estudos (seguindo a regra de avaliação); e curso de idiomas
- Reembolso de certificações

## Requisitos

Obrigatórios
- Strengths: 
- Objective-C 
-  Swift 3+ 
- Git 
- SCRUM 
- Testes unitários 
                                                
- Desejável alguma experiência em projetos que envolveram 
- APIs 
- Node.JS 
- Segurança
 - Devops 
  
Diferenciais: 
- Alguma experiência em Android e/ou Apps Híbridos 
- Experiência em Configuração/Acesso à Backend (REST e/ou SOAP) 

## Contratação

CLT

## Nossa empresa

GFT é uma Consultoria Multinacional Alemã, especialista em soluções de TI com foco no mercado financeiro.

## Como se candidatar

Por favor envie um email para Beatriz.Souza@gft.com com seu CV anexado.

**Comment by davidtcdeveloper** [comment]
@Befresche Este mural de vagas é dedicado exclusivamente a oportunidades para profissionais android, conforme citado nas regras do mesmo.
Por este motivo, estamos removendo esta issue.
