### ISSUE TITLE
[São Paulo - SP] Desenvolvedor Android Pleno/Senior - Projeto muito bacana!

### ISSUE THREAD

**Issue by mangar** [androiddevbr/vagas#89]
## Descrição da vaga

Olá!

​Estamos desenvolvendo um app para uma grande empresa e neste momento estamos precisando de bons programadores para trabalhar conosco.

Somos uma agencia de propaganda, mas não somos (tão) desorganizados. Temos uma cultura de portas abertas onde suas opiniões serão ouvidas de verdade e na medida do possível implementadas.

Nada por aqui está escrito em pedra, ou seja, muitas coisas podem ser revistas.

Procuramos devs com conhecimento em Java, o aplicativo está sendo desenvolvido nativo.

Se você entende o que estou dizendo, ou se tem uma idéia e está muito afim de ajudar a fazer acontecer, mande uma mensagem.

## Local

Escritório em São Paulo - Jardins
Trabalho presencial. Remoto não é uma opção para este projeto.

## Benefícios

- Sua máquina pode ser um Dell com Windows OOOOUUU se vc quiser pode ser um Mac, fica a seu critério ;-).
- Horário flexível
- Projeto bastante inovador

## Requisitos

Obrigatórios
- Experiencia em Android Nativo (Java!)
- Confortável com padrão MVVM
- RxAndroid

Diferenciais
- Possuir projetos bacanas desenvolvidos (publicados ou não na PlayStore)
- Desenvolvimento de animações com Android

## Contratação

Inicialmente é como PJ. A partir do momento (3-6 meses mais ou menos) que nos entendemos podemos rever a forma de contratação, valores, mecanica, etc....
Tudo depende do "fit" de lado-a-lado.

## Nossa empresa

Somos uma agencia de propaganda, mas não somos (tão) desorganizados. Temos uma cultura de portas abertas onde suas opiniões serão ouvidas de verdade e na medida do possível implementadas.

## Como se candidatar

Por favor envie um email para rgasp.tech+vagasandroid@gmail.com com seu CV (Linkedin, Github, tudo que vc achar que vale a pena) - enviar no assunto: Vaga: Android

**Comment by walmyrcarvalho** [comment]
@mangar Labels adicionadas. :)

**Comment by walmyrcarvalho** [comment]
@mangar Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!
