### ISSUE TITLE
iOS Developer (Remote)

### ISSUE THREAD

**Issue by aalvarezbluecoding** [androiddevbr/vagas#896]
## Descrição da vaga

We are looking for an experienced iOS developer with experience with Objective-C to work with one of our clients.

About the role:
Someone responsible for maintaining an Objective-C and Swift iOS application, updating CocoaPods and hardware integration SDKs as necessary and fixing bugs and memory leaks.

## Local

Remoto 

## Benefícios

Remote

40 hrs/a week

USD $25 - 30 per hour
- ...

## Requisitos

Obrigatórios
100 % English Fluent.
    Strong experience with iOS.
    Experience with Objective C (Swift is a plus).
    Experience using XCode Instruments to profile memory/CPU usage.
    Experience with crash analytic tools like BugSnag/Crashlytics.
    Programmatic and storyboard driven Auto Layout.

## Nossa empresa

At Blue Coding we specialize in hiring amazing developers. Through our work, we help companies, both large and small, build great development teams and develop great products. Our team of over 30, is distributed in more than 10 countries across the Americas. Our clients include online retailers, digital agencies, SaaS companies, and software consultancies.

## Como se candidatar

Por favor envie um email para hr@bluecoding.com com seu CV anexado - enviar no assunto: Vaga iOS
https://hire.withgoogle.com/public/jobs/bluecodingcom/view/P_AAAAAAGAAGIOKc7eF1XADR?trackingTag=TEMP-008

**Comment by davidtcdeveloper** [comment]
@aalvarezbluecoding This is a job board for Android development opportunities only. Because of that, I will have to remove this issue.
