### ISSUE TITLE
[Indaiatuba, São Paulo] Desenvolvedor Android [PLENO] | Indústria confidencial

### ISSUE THREAD

**Issue by analuhcosta** [androiddevbr/vagas#899]
## Descrição da vaga

Buscamos um profissional que será responsável pelo desenvolvimento android e web (backend) em uma indústria de grande porte nacional

## Local

Presencial em Indaiatuba-SP

## Benefícios

-Plano médico e odontológico
-Refeição no local
-Cesta básica
-PLR

## Requisitos

Obrigatórios
- Buscamos candidatos de nivel jr/pleno, com experiência em desenvolvimento Java e Android

## Contratação

CLT de R$4.5k a R$6k, dependendo da senioridade do profissional

## Como se candidatar

Por favor envie um email para juliapedroso@michaelpage.com.br com seu material

**Comment by davidtcdeveloper** [comment]
@analuhcosta As regras deste mural de vagas exigem que o nome da empresa contratante seja divulgado. Estou encerrando esta issue, peço que a mesma seja recriada descrevendo o nome da contratante.
