### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Android | Mobicare

### ISSUE THREAD

**Issue by marcellogalhardo** [androiddevbr/vagas#9]
## Descrição da vaga

Participar de todo o ciclo de desenvolvimento de aplicativos, desde a fase de análise da solução até a entrega e manutenção do projeto.

## Local

Praia de Botafogo / Rio de Janeiro.
Horário semi-flexível de 40h semanais.

## Benefícios

- Vale-Refeição/Alimentação;
- Vale-Transporte;
- Plano de Saúde Bradesco;
- Plano Odontológico Bradesco;
- Crédito Consignado;
- Participação nos Resultados da Empresa;
- Convênios com academias, cursos e outros.

### Obrigatórios
- Estrutura de um aplicativo Android (Smartphones e Tablets);
- API do Android em geral;
- Ciclo de vida de Activities e Fragments;
- Entendimento de versionamento de código;
- Integração com serviços utilizando XML e/ou JSON;
- Conceito de orientação a objetos.

### Desejáveis
- AsyncTasks
- Adaptação de layouts para diferentes tamanhos de telas
- SQLite
- Conhecimento em SQL
- Experiência com plataformas Mobile
- Android Studio / Gradle
- Utilização do GitHub
- Inglês técnico

### Diferenciais
- Testes automatizados
- Contribuição em algum projeto open source
- Ter ao menos um aplicativo desenvolvido (não necessariamente publicado no Google Play)
- API’s do Google Services (maps, analytics, GTM, GCM etc)
- Experiência com Material Design
- Metodologia Scrum

## Contratação

Regime CLT;

## Nossa empresa

A plataforma Mobicare aprimora a experiência do usuário ao permitir acesso aos serviços de autoatendimento de sua empresa em qualquer aparelho celular. Totalmente customizável para qualquer mercado ou indústria a solução usa apps multi-plataforma e portais móveis de última geração compatíveis com todos os aparelhos, sejam eles smartphones, webphones ou feature-phones básicos.

## Como se candidatar

Por favor envie um email para **vagas@mobicare.com.br** com seu CV anexado - enviar no assunto: **Vaga - Desenvolvedor Android [AndroidDevBr]**

**Comment by walmyrcarvalho** [comment]
@marcellogalhardo Essa vaga ainda está aberta? Só tô checando mesmo, pra fins de organização. :)

**Comment by marcellogalhardo** [comment]
@walmyrcarvalho não foi preenchida, mas até onde eu sei não estão buscando mais devs Android no momento. Por conta disso, vou encerrar ela. :+1:

**Comment by marcellogalhardo** [comment]
Estou reabrindo a issue a pedido do RH da Mobicare. @walmyrcarvalho se puder mudar a label da vaga, agora é apenas para Junior.

**Comment by marcellogalhardo** [comment]
Desculpem, me equivoquei. A vaga na verdade é para uma empresa parceira. Encerrando esta issue.
