### ISSUE TITLE
[SP - Vila Olímpia - Presencial] Webmotors - Desenvolvedor Android PJ nível da vaga em aberto

### ISSUE THREAD

**Issue by AkiraSp** [androiddevbr/vagas#90]
[SP - Vila Olímpia] Webmotors - Desenvolvedor Android )
Se você manda bem como desenvolvedor Android e tem habilidades para  trabalhar em times integrados, ágeis e multidisciplinares, vem trabalhar com a gente e fazer a diferença na vida de milhões de compradores, vendedores e amantes de veículos.
A Webmotors é a marca automotiva nº1 do Brasil, Clean, Web, Pessoal.

Pra trabalhar aqui tem que ter atitude, pró atividade e curtir desafios. Tem que botar a mão na massa. A Web (apelido carinhoso) parece uma start-up, mesmo com seus 200 funcionários, quase todo mundo se conhece.

Nada aqui é problema de outra pessoa. O limite do seu escopo de trabalho depende, quase sempre, de você e da sua vontade de puxar os jobs. Tem muita oportunidade.
Se você procura um lugar informal, jovem e desafiador, você vai ter espaço.

Job description:

• Atuar no desenvolvimento de novas features e manutenção de aplicativos Android;

• Participar de plannings, retro e outras reuniões com o time;

• Acompanhar a performance do aplicativo nas lojas, no dia-a-dia e nos chamados dos clientes ao nosso suporte;

• Antenado em novas tecnologia

• Manter o motor ligado

Conhecimentos

• Trabalhar com desenvolvimento em Fragments

• Material Design

• Metodologias ágeis (Kanban / Scrum)

• Ferramentas de Gestão (JIRA ou Similares)

• Bibliotecas de gestão e renderização de imagens (picasso e etc)

• Ferramentas de Analytics (Fabric, Adobe, Google...)

Características desejadas

• Facilidade em integrar o time com outras áreas de negócio da empresa

Diferencial

• Ter atuado com aplicativos em Material Design

• Ter atuado em empresar com cultura ágil

Contato: tsugiura@webmotors.com.br enviar currículo para este email

**Comment by hpedrorodrigues** [comment]
@AkiraSp possibilidade de trabalho remoto?

**Comment by AkiraSp** [comment]
Somente presencial, acabei de alterar no título.

**Comment by AkiraSp** [comment]
#PJ #Presencial

**Comment by marcusberger** [comment]
Tem estágio?
