### ISSUE TITLE
[Metrô Butantã, SP] Desenvolvedor(a) Mobile | Stoodi

### ISSUE THREAD

**Issue by reinaldomoreira** [androiddevbr/vagas#906]
# Vaga para Desenvolvedor Mobile

---

## Sobre o Stoodi

O Stoodi transforma o futuro dos brasileiros por meio da educação. Somos uma empresa jovem com uma grande ambição de democratizar o acesso ao ensino superior para milhões de brasileiros.

Fazemos parte do maior grupo de educação do mundo (sim, do mundo)! Combinando a agilidade, autonomia e alto crescimento de uma startup com a força e estabilidade de um gigante.

A nossa plataforma online de estudos serve mais de 100 mil exercícios e 50 mil vídeos por dia a alunos de todo Brasil!

Além disso temos diversas outras soluções como simulados, planos de estudos personalizados, o app mais bem rankeado de orientação vocacional, gabarito Enem, entre tantos outros.

Mas não são apenas os números que nos movem. Mudamos diariamente a vida de milhares de pessoas e acreditamos que ter um propósito de impacto é o que nos diferencia.

Sabemos que com pessoas comprometidas, transparentes e que valorizem o aprendizado vamos construir o futuro da educação.

---

## Nosso time de Engenharia

Somos um grupo de desenvolvedores apaixonados por tecnologia e dedicados a entregar as melhores soluções para nossos alunos.
Nós prezamos muito por código de qualidade, compartilhamento de conhecimento e um ambiente incrível para se trabalhar.

---

## Nós acreditamos que:

- Nada motiva mais um desenvolvedor do que um desafio legal.
- Criar um ambiente bacana é responsabilidade de todos.
- O motivo final de tudo o que fazemos é a evolução dos nossos alunos.
- Compartilhar conhecimento faz com que todos cresçam juntos.
- É muito importante ter um equilíbrio entre a vida profissional e pessoal.
- Pessoas e informações devem ser acessíveis. Quer bater um papo com o CEO? Só marcar na agenda.

---

## O que você irá encontrar aqui:

- Squads com autonomia para entregar os melhores produtos usando o que melhor lhes convêm (Kanban, Scrum, XP...)
- Uma tech stack massa! Estamos usando as tecnologias mais atuais, como: Kotlin/Swift, Flutter, RxSwift/RxKotlin/RxDart, Clean Architecture, Retrofit/RxAlamofire, ConstraintLayout/Autolayout, e muitas outras...
- Não temos medo de crescer nossa stack, desde que essa mudança traga benefícios para o Stoodi ou para nossos alunos.
- Toddynho, frutas e happy hour todos os meses na nossa laje gourmet (rooftop).

---

## O que esperamos de você:

* Aprendizado contínuo e curiosidade para manter a inovação viva.
* Multidisciplinaridade - adquirir novas habilidades em outras áreas e ajudar seu squad com o que for preciso.
* Colaboração - apoiar ativamente as pessoas, se posicionando para cumprir nossos objetivos coletivos e individuais.

---

## Local

Próximo ao metrô Butantã em São Paulo

## O que precisamos:

Na nossa stack mobile temos apps nativos em **Kotlin** e **Swift**, e também estamos criando em multiplataforma com o **Flutter**.

Se você se encaixa em **qualquer uma dessas** categorias, não deixe de aplicar:
- Tem uma vasta experiência em desenvolvimento mobile.
- Adora metodologias ágeis.
- É fluente em Kotlin, Swift e/ou Dart.
- Manja de Clean Architecture.
- Tem conhecimento de git flow.
- Sabe Gradle/CocoaPods como ninguém.
- Curte armazenar dados offline. 
- Não tem medo de injeção (de dependência, claro).
- Sabe programação reativa na alma.
- Conhece bastante design patterns, inclusive os de apresentação (MVVM, MVP, ...).
- Constrói layouts like a boss.
- Viciado em consumir APIs.
- Adora testes!
- Sabe razoavelmente SQL/NoSQL e sabe usar algum ORM.
- Já trabalhou com players de vídeo mobile.
- Não tem medo de meter a mão no código alheio.
- Já mexeu com Bitrise ou ferramentas de entrega contínua.

## Como se candidatar
Envie seu currículo em https://jobs.kenoby.com/stoodi

**Comment by jpventura** [comment]
@ViperAlpha junior/pleno/senior? CLT/PJ? presencial/remoto?

**Comment by ViperAlpha** [comment]
Pleno e/ou Senior. CLT. Presencial. 
Obrigado @jpventura
