### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Android | BovControl

### ISSUE THREAD

**Issue by FernandaAbreu** [androiddevbr/vagas#925]
## Descrição da vaga

Olá, nós somos a Bovcontrol.

E nós estamos revolucionando o agribusiness no mundo!!!

Somos a 3 startup mais inovadora, segundo a Startse. 

O time de desenvolvimento da BovControl está procurando desenvolvedor(a) android  apaixonados por desafios exponenciais.

## Local

Escritório  de São Paulo - Berrini

## Benefícios

-Vale refeição
-Vale transporte
-Plano de saúde
-Ambiente descontraído e informal

## Requisitos

Obrigatórios
- Graduação na área de computação ou experiência equivalente.
- Experiência com desenvolvimento para aplicações móveis (Android Studio) com Java e Kotlin
- Habilidade de trabalhar com dados remotos via REST e JSON.
- Experiência com GIT
- Dominar a construção de queries (SQL).
- Ter utilizado algum ORM Android (GreenDao, OrmLITE, SugarORM,..).
- Experiência com retrofit e OKHttp.
- Design Patterns.
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis
- Experiência com Espresso e UI Automator
- Experiência com RxJava
- Android Flavors
- Realm

## Contratação
 a combinar

## Nossa empresa

Somos uma startup global que vem conectando todas as vacas e fazendas do planeta numa 'nuvem diferente' (antes do modismo do blockchain) - com o objetivo de erradicar a fome no mundo, empoderando produtores rurais com tecnologia para serem mais eficientes e sustentáveis.
Nossas soluções combinam coleta e a análise de dados, para toda a cadeia produtiva.

Os dados são coletados no campo por aplicativos móveis e podem ser analisados por vários meios, por diferentes elos da cadeia (varejo, bancos, processadores de leite, etc).

Alimentar 1 bilhão de pessoas por dia, em 10 anos de existência da empresa, é a nossa meta.

## Como se candidatar

Por favor envie um email para vagas@bovcontrol.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@FernandaAbreu CLT, PJ ou ambos?
