### ISSUE TITLE
JOB REMOVED

### ISSUE THREAD

**Issue by Mahajankunal0** [androiddevbr/vagas#928]
# Important information
For jobs submitted on this wall to be categorized with labels, they must follow the following rules:

1. All positions submitted on this board must comply with our community Code of Conduct: https://github.com/androiddevbr/codigo-de-conduta/blob/master/README-en.md. Positions that violate this Code of Conduct will be automatically edited and terminated by the moderation team.
2. Try to use terms and descriptions that make the least of gender distinction. For example, use "Developer," "Engineer," or "Person."
3. Add links or describe the inclusion, non-discrimination and related policies adopted by the company.
4. Jobs posted on this wall will be automatically posted to our community's #job-alerts Slack channel.
5. Remove this starting block before posting the vacancy.

## Job Description

Project development of a racing app, etc.

## Location

Office or Remote Office Vancouver, CA

## Benefits

- Assemble your workstation as you wish
- playroom
- Games
- ...

## Requirements

Required
- 3+ years of Android experience
- Comfortable with MVP, MVC, MVVM and derivatives standard

Desirable
- Experience with Espresso and UI Automator
- Experience with RxJava

Differentials
- opensource projects

## Hiring

Contractor or full-time

## Our company

Here at ACME Corporation we are leaders in ...

## How to apply

Please email us at email@email.com.br with your CV attached - send in subject: Vacancy Android

**Comment by jpventura** [comment]
@Mahajankunal0 please, follow the job guidelines before posting at this board
