### ISSUE TITLE
[Belo Horizonte, MG] Estágio em Desenvolvimento Android | eMotion Digital

### ISSUE THREAD

**Issue by bernardoassis** [androiddevbr/vagas#93]
## Descrição da vaga

Estamos buscando por estagiários na área de desenvolvimento Android!

## Local

Escritório em Belo Horizonte - Santa Lúcia

## Benefícios

- Flexibilidade de horário;
- Possibilidade de home office;
- Lanche oferecido no final da tarde;
- Vale Transporte.

## Requisitos

Obrigatórios
- Conhecimento em programação orientada a objetos;
- Conhecimento de padrões de projeto de software;
- Estar cursando alguma faculdade na área de ciências exatas (de preferência em TI).

Desejáveis
- Experiência com programação em Java;
- Experiência com programação para Android;
- Algum aplicativo publicado na Play Store;

Diferenciais
- Conhecimento de controle de versão de código-fonte Git;
- Experiência de trabalho em equipes de desenvolvimento ágil;
- Habilidade de trabalho com independência e supervisão mínima;
- Disposição em compartilhar o seu conhecimento com as pessoas da área de tecnologia da empresa;
- Boa habilidade de comunicação escrita e verbal;
- Disposição para aprender novas tecnologias e aplicá-las em um curto espaço de tempo;
- Espírito de equipe em um time multi-disciplinar;
- Capacidade de analisar situações e informações, realizando avaliação crítica e conclusiva, apontando direcionamentos para subsidiar as tomadas de decisões.

## Contratação

Estágio 

## Nossa empresa

A eMotion Digital é uma empresa de tecnologia focada em produção, distribuição de conteúdo e desenvolvimento de projetos incríveis (apps iOS/Android/HTML5) para o mercado de SVA (Serviços de Valor Agregado) para operadoras no mundo inteiro!

## Como se candidatar

Por favor envie um email para bernardo@emotiondigital.com.br com seu CV anexado - com o assunto: Vaga Estágio Android

**Comment by walmyrcarvalho** [comment]
@bernardoassis Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!
