### ISSUE TITLE
[Porto Alegre, RS] Desenvolvedor (a) Android Sênior | 4all Tecnologia

### ISSUE THREAD

**Issue by micheliane** [androiddevbr/vagas#933]
**DESCRIÇÃO DA VAGA**
Essa oportunidade é para Fintech do Hub. São os meios de pagamento do hub. Fintech as a service, ou seja, criamos fintechs, pois os meios de pagamento estão mudando. Saiba mais acessando: http://somosphi.com
Aproveite para conhecer um pouquinho mais sobre como é a vibe da 4all clicando aqui 👉 www.instagram.com/pordentroda4all 😉

**RESPONSABILIDADES E ATRIBUIÇÕES**
Sólidos conhecimentos em Kotlin e Java;
Experiência com: Git; integrações a web service; orientação a objetos e design patterns;
Conhecimento do padrão MVVM e dos guidelines de design do Google (Material Design);
Também é necessário conhecimento em: Analytics; Gradle (flavors, build type); testes e frameworks de teste (JUnit, Mockito Kotlin, Espresso) e componentes do Android Jetpack (Data Binding, Room, Animações e Transições).

**Consideramos diferenciais:**
Criação de componentes customizados;
Experiência com padrão MVVM utilizando Architecture Components;
Conhecimento em: CI; Coroutines e em programação funcional;
Experiência em testes unitários.

**REQUISITOS E QUALIFICAÇÕES**
Superior completo ou em andamento em Ciência da Computação, Sistemas de Informação, TI e áreas afins.

**INFORMAÇÕES ADICIONAIS**
O que oferecemos:
Explore todo o potencial de oportunidades de desenvolvimento e práticas do hub 4all aqui pelo nosso bot: http://bit.ly/BillBot 🤖
Liberdade com responsabilidade
Um ambiente de trabalho descontraído com colegas dispostos a te ajudar e a compartilhar conhecimento
Possibilidade de crescimento e desenvolvimento
Happy mensal
Home Office
Acessos rotativos ao Alura
Parcerias que te dão desconto: Sucesu e Target Trust
Gympass
Plano de saúde e odontológico da Unimed
VR ou VA
VT
Carga horária de 40h semanais
Confira 10 motivos para amar trabalhar aqui 💚 👉 http://bit.ly/10motivosparaamartrabalharaqui

**MANIFESTO 🤗**
A 4all é feita por pessoas que fazem a diferença.
E proporciona crescimento profissional e pessoal para todos que estão aqui.
Um lugar com um entrosamento cada vez maior.
De experiências únicas em um ambiente enriquecedor e gratificante.
Espaço para muito aprendizado e valorização do coletivo.
Uma galera incrível e uma equipe unida.
Onde a energia positiva encontra o clima perfeito.
Com oportunidades de aprendizado todos os dias.
Temos a motivação para o novo.
Somos engajados com o futuro.
Nossos dias são uma constante evolução.
Estamos sempre em busca do melhor.
Com criatividade para mudar, pensar grande e inovar.

Onde se candidatar?  https://4all.gupy.io/jobs/96732
Dúvidas: Entre em contato com rh@4all.com

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
