### ISSUE TITLE
Android Developer for successful e-commerce app

### ISSUE THREAD

**Issue by renatoarg** [androiddevbr/vagas#934]
**Android Developer** 

**HANZO** offers a white label Software as a Service (SaaS) mobile customer engagement platform that enables Companies to interact with the target audience through their smartphones, with products such as loyalty, coupon wallets, m-commerce, instant payments, CRM, etc.;
  
As an addition to our Android Development team, you will design, write, and maintain efficient, reusable, and reliable native Android code. 

Flexible hours, cool culture, lots of remote working, good salary and negotiable conditions.

**Your Key Responsibilities**
- Develop of new functionalities and and improve already existing ones;
- Participate in daily status update and planning meetings;
- Find and correct bugs;
- Debug;
 
 **Desired Qualifications: [Essential]**
- At least 3 years of professional native Android experience;
- Good knowledge of Fragments lifecycle, communication between Activity and Fragment, and use of SupportFragmentManager for browsing;
- Experience with lysts in RecyclerViews, PagerViews, Adapter and communication between these components and Activity/Fragment;
- Working knowledge of GIT
 
**A plus if you also have: [Desirable]**
- Retrofit2;
- MVP and/or MVVM;
- Android Jetpack (LiveData/MutableLiveData);
- Dagger2;
- Animations;
- Camera;
- Firebase;
- Junit, Espresso, Mockito;
- Experience with Google Play (tests, alpha, beta and production);
 
**Differentials**
- Experience with Kotlin and Jira;
- Knowledge of HTTP Protocol;
- Published APPs on Google Play, and code to show.

**Apply on Linkedin:**  https://www.linkedin.com/jobs/view/1547135546/

**Comment by jpventura** [comment]
@renatoarg presencial ou remoto? Júnior, pleno ou sênior?

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
