### ISSUE TITLE
[Remoto] Android Developer | Impulso Network

### ISSUE THREAD

**Issue by ThaysdaCosta** [androiddevbr/vagas#935]
Buscamos **Devs que curtam trabalhar com a plataforma Android** e tenham **bons conhecimentos de Kotlin ou Java** para atuarem num projeto muito TOP🔝!
 
Saber **analisar logs de ferramentas e reconhecer possíveis bugs** são habilidades que farão muita diferença!

Ter **experiência com suporte/atendimento** e ter **trabalhado com Zendesk** também contarão pontos.

Nível: **Pleno ou Sênior**
Modelo: **Remoto**
Linguagem: **Java** ou  **Kotlin**
Carga horária: **Full Time**, em horário comercial
Data de início: **imediato**
Remuneração: **até R$95/h (~R$15.200/mês)**. 💰A própria pessoa define quanto julga ser adequado receber.

😃 **Sobre nós:** Somos uma comunidade com milhares de profissionais de TI que integra diversas iniciativas, produtos e serviços para a colaboração mútua e desenvolvimento pessoal e profissional de seus integrantes. **Já somos mais de 15 mil pessoas!** 😍

E aí? **Tem interesse em participar desse processo?** Então, **acesse** 👉https://impulser.me/thays-impulso , **registre-se** e me **chame lá pelo chat da Impulso Network** (logo após seu registro, vc receberá por email as credenciais para acessar o nosso chat. Pode me chamar por lá, **sou `@thays`**).
 
**Essa e todas as outras oportunidades estão divulgadas lá na comunidade, no canal #oportunidades.**

Aguardo vocês! 🚀

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
