### ISSUE TITLE
[Bairro da Moóca, SP] Desenvolvedor(a) Android | EasyTech

### ISSUE THREAD

**Issue by etnishiyama** [androiddevbr/vagas#936]
## Nossa empresa

Somos uma empresa nacional, atuando há vinte anos no mercado, oferecendo souções complexas de hardware software.

Localizados no Bairro da Mooca, dispomos de uma excelente estrutura e buscamos identificar um(a) Desenvolvedor(a) Android Sênior, que atuará em nossa unidade em São Paulo, no Bairro da Mooca, de segunda a sexta-feira em horário comercial.

## Local

Alto da Mooca (Zona Leste), São Paulo - SP

## Descrição da vaga

·       Desenvolver e manter aplicativos Android em Kotlin.
·       Definir boas práticas e arquitetura do sistema.
·       Integração com APIs RESTful.
·       Integração com Sistemas Embarcados utilizando tecnologia Bluetooth.
·       Publicação e gerenciamento do aplicativo na loja.
·       Desenvolver novas soluções de comunicação, escrever protocolos (visando segurança).

## Benefícios

·       Ambiente inclusivo e desafiador, com ferramentas e tecnologias de ponta.
·       Desenvolvimento contínuo (on the job e treinamentos).
·       Assistência Médica e Odontológica, Vale-Transporte, Vale-Refeição e Café da Manhã.
·       Remuneração condizente com a posição e flexibilidade de vínculo empregatício.

## Requisitos

Obrigatórios:
·       Formação: Cientista/Engenheiro(a) da Computação, Matemática, Física, Análise de Sistemas e afins.
·       Raciocínio lógico, que saiba resolver problemas sozinho.
·       Experiência e sólidos conhecimentos em projetos Android/Kotlin.
·       Experiência em integração com banco de dados, integrações com APIs RESTful e/ou Webservices.
·       Familiaridade com componentes de User Interface do Android e adaptação de layouts para diferentes tamanhos de telas e dispositivos.
·       Experiência com Banco de Dados SQLite.

Diferenciais:
·       Conhecimento em processos de segurança (criptografia, desenvolvimento de processos seguro de comunicação, etc.).
·       Experiência com configurações de build e CI/CD.
·       Noções de IPC, JNI e NDK
·       Conhecimento em arquiteturas MVVM e VIPER.
·       Conhecimentos de testes de unidade e git.
·       Conhecimentos de Linux, servidores e IOS.
·       Inglês avançado.

## Contratação

CLT ou PJ

## Como se candidatar

Por favor, envie um email para everton.nishiyama@easytech.com.br com seu CV anexado e/ou LinkedIn - enviar no assunto: [Vaga Android] ...

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
