### ISSUE TITLE
[Belo Horizonte, BH] Desenvolvedor(a) Mobile | GO FREE

### ISSUE THREAD

**Issue by megandavulpi** [androiddevbr/vagas#937]
### Sobre a empresa: GoFree

Uma plataforma pensada para te dar as melhores soluções, seja a Venda de Ingressos, o Cashless, Mapas Inteligentes ou Perfomance em Dados. A Gofree pode ser a integração de tudo isso ou a entrega de uma única solução que atenda sua necessidade. Somos A plataforma Gofree. O aplicativo Gofree. A solução Gofree. A ferramenta Gofree. O time Gofree. Somos sem gênero, sendo tudo e para todos. Fluímos, evoluímos e construímos com você o melhor da tecnologia para eventos.

### Descrição: Ocupações do cargo

Este profissional será responsavel por certificar que a alta qualidade dos aplicativos da GoFree seja mantida.
Implementar aplicações mobile nativas em Android ou Kotlin.
Desenvolver a compreensão do contexto dos clientes e do uso dos nossos produtos.
Ser capaz de desenvolver habilidades em novas tecnologias para cumprir os objetivos do produto.

### Benefícios

Temos um time bem diferenciado, buscamos sempre promover a troca de conhecimento, a interação entre as pessoas e a diversidade.

### Fazendo parte do nosso time você terá:

Vale Refeição: R$ 24,20 ao dia;
Plano de saúde para você e dependentes,onde a coparticipação somente é descontada se o valor for acima de R$ 100,00;
Plano Odontológico Sulamérica;
PPLR; ( de 1 a 2 salarios )
Convênio SESC , e várias parcerias incriveis.
No Dress Code;

### Aptidões e qualidades

Precisamos de gente fera, com muita disposição para aprender, com muito engajamento , e tenha muita sede por desafios!

### Para fazer parte do nosso time é necessário que você:

Tenha um otimo conhecimento em Android ou Kotlin, e assim seja capaz de entender a composição de aplicativos
Android em estrutura, APIs e performance;
Conheça o ciclo de vida de aplicações e componentes do Android
Conheça sistemas de versionamento de código, preferencialmente GIT;

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/mobile_gofree

**Comment by jpventura** [comment]
@megandavulpi junior, pleno ou senior? remoto ou presencial?

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
