### ISSUE TITLE
[Curitiba, PR] Desenvolvedor(a) Android | Juno

### ISSUE THREAD

**Issue by diefferson** [androiddevbr/vagas#939]
## Descrição da vaga

A Juno está crescendo e o céu é o nosso limite! Somos uma empresa de Tecnologia, inserida no mercado financeiro e o nosso time de TI tem um papel fundamental e estratégico para o nosso crescimento, qualidade e fortalecimento como empresa. É por meio dessa união, que conseguimos lançar novos produtos e sonhar cada vez mais alto!

**Essa oportunidade é para você que:**

- Sonha Grande, tem senso de dono e é mão na massa!
- É proativo e coopera de forma genuína;
- Ama tecnologia e está sempre por dentro das novidades!
- Adora solucionar problemas e está sempre em busca do porquê das coisas;

## Responsabilidades e atribuições

- Implementação de telas e animações;
- Desenvolvimento de código limpo;
- Definições arquiteturais;
- Colaboração nas decisões negociais;
- Melhorias contínuas em projetos relacionados ao app da Juno;
- Oportunidade de participar de um Squad multidisciplinar para atuar em projetos inovadores e de grande potencial para a Juno, sendo um dos responsáveis pelas criações de novos produtos;
- Gostar e estar sempre se atualizando em novas tecnologias;
- Ter perfil autogerenciável;
- Vestir a camisa e topar crescer e viver esse Sonho Grande com a gente!

## Local

Curitiba - PR

## Benefícios

 - Horário flexível;
 - Vale transporte;
 - Vale refeição de R$ 23;
 - Gympass;
 - Clube de benefícios Gazeta do Povo;
 - Plano Odontológico;
 - Plano de Saúde;
 - Desconto em instituições de ensino;
 - Frutas para consumo diário na empresa;
 - Happy hour mensal;
 - Escritório pet friendly.

## Requisitos

- Kotlin
- Android Architecture Components
- Android Jetpack
- Coroutines
- Integração com API REST (Retrofit) 
- Moshi
- Injeção de Dependências *de preferência Koin
- Padrões de projeto, arquiteturas MVVM e Clean Architecture 
- Testes unitários - Mockito, Expresso, JUnit
- Git

## Contratação

CLT

## SEJA UM JUNO!
Sonhamos em deixar finanças fáceis, justas e acessíveis para todos. Sem burocracias e dificuldades, assim todos crescemos juntos. Você é bem vindo para fazer esse sonho acontecer com a gente. Vamos fazer isso juntos?

## Como se candidatar

Aplicar pelo [link](https://juno.gupy.io/jobs/98288): [https://juno.gupy.io/jobs/98288](`https://juno.gupy.io/jobs/98288`)

**Comment by lucas-marciano** [comment]
A vaga é somente presencial?

**Comment by diefferson** [comment]
@lucas-marciano Sim, somente presencial.

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
