### ISSUE TITLE
[Belo Horizonte, MG] Desenvolvedor(a) Android | Ci&T

### ISSUE THREAD

**Issue by jessicafsciandt** [androiddevbr/vagas#942]
## Descrição da vaga

Uma das líderes mundiais no segmento de sistemas de monitoramento de glicose no sangue para uso doméstico e hospitalar. A empresa desenvolve produtos inovadores, que permitem aos pacientes um controle mais prático e eficaz do diabetes, contribuindo para uma melhor qualidade de vida. 

## Local

Base de Belo Horizonte - MG

## Benefícios

-Regime CLT, 40 horas semanais de segunda a sexta com horário flexível;
-Remuneração a combinar;
-Participação nos lucros e resultados;
-Vale alimentação e refeição;
-Assistência médica e odontológica (plano padrão custeado pela empresa);
-Seguro de vida;
-Licenças maternidade e paternidade estendidas;
-Auxílio creche;
-Ônibus fretado, estacionamento ou transporte intermunicipal de acordo com a base de atuação;
-Descontos em estabelecimentos e parceria com o SESC;
-Gympass.
-Sem dress code: quem gosta de roupa social são nossos clientes. Aqui na base da CI&T você pode trabalhar do jeito que se sentir mais confortável!
-Ambiente descontraído e acolhedor (adoramos cores, quadros e post-its);
-Opções de lazer e relaxamento (videogame, sinuca, cadeira de massagem, etc);
-Plano de carreira estruturado e acompanhamento individual;
-CI&T University com cursos online disponíveis em diversos temas!

## Requisitos

Obrigatórios

-Language: Kotlin;

-Android: Constraint Layout, Lifecycle, Bluetooth, Screen sizes, RecyclewView, Notification;

-Architecture: MVVM, DDD, Clean Code, Multi-module architecture, Offline first development;

-Libraries: Android Architecture Components(Room, Lifecycle, Databinding, WorkManager), Koin;

-CI/Environment: Git, Jenkins, Sonarqube;

-Testing: Espresso, MockK, JUnit (edited);

- Inglês intermediário para leitura escrita e conversação.

Desejáveis
- Inglês avançado.

Diferenciais
- Kotlin

## Contratação

CLT.

## Nossa empresa

A CI&T é uma multinacional brasileira de TI, especializada em desenvolvimento e manutenção de sistemas, que promove inovações capazes de transformar o negócio dos seus clientes.

## Como se candidatar

Por favor se inscreva na nossa oportunidade pelo nosso site de carreiras:
https://carreiras.ciandt.com/registration/3362?language=pt

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
