### ISSUE TITLE
[REMOTO] Desenvolvedor Mobile na UNITY

### ISSUE THREAD

**Issue by megandavulpi** [androiddevbr/vagas#943]
### Sobre a empresa: Unity

Desenvolvemos softwares para o mercado americano e europeu.

### Descrição: Qual será o seu papel?

Desenvolver aplicações mobile com as mais modernas tecnologias.

### Esperamos que você tenha conhecimento em:

Flutter;
Laravel ou Nodejs.

### Vamos ficar muito felizes se você também tiver conhecimento em:

Socket.io;
Mongodb ou MySQL.

### Você vai amar trabalhar aqui se:

Estiver em busca de crescimento e evolução;
Gostar de trabalhar remotamente tendo liberdade de horários e localização;
O trabalho remoto não te impedir de se comprometer com a empresa e o produto (queremos que você se sinta parte da nossa empresa!).

### Informações Complementares:

Contratação tipo PJ;
Pleno.

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/unity_remoto1

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
