### ISSUE TITLE
[Campinas, SP] Desenvolvedores Android | MB Labs

### ISSUE THREAD

**Issue by Kelvao** [androiddevbr/vagas#944]
## Descrição da vaga

Estamos em busca de Desenvolvedores Android para compor nossa equipe, atuamos com projetos de alta performance, essa vaga será para atuar em diversos projetos em um curto intervalo de tempo, com muita oportunidade para se tornar líder técnico em um determinado projeto.

## Local

Escritório em Campinas/SP

## Benefícios

- Horário flexível;
- Atividades recreativas para unir a equipe;
- Eventos de tecnologia sediados na empresa para os devs aprenderem ainda mais.

## Requisitos

Obrigatórios:
- Bons conhecimentos de padrões de projetos;
- Habilidade de resolução de desafios técnicos;
- Implementação de requisições HTTP/RESTFULL;
- Metodologia de desenvolvimento Scrum/Kanban;
- Bons conhecimentos do SDK Android;
- Bons conhecimentos Java ou Kotlin;
- Controle de versão GIT;

Diferenciais:
- Integração Contínua;
- Architecture Components;
- Testes unitário e end to end;
- Injeção de dependências;

## Contratação

PJ com salário a combinar.

## Nossa empresa

Empresa fundada em 2013 com o objetivo de alcançar e atender a região metropolitana de Campinas-SP no que se diz a respeito de tecnologia, inicialmente composta por dois sócios formados em Engenharia da Computação vem crescendo exponencialmente nos ultimos meses, criando raízes com grandes empresas no mercado e sempre que possível realizando novas parcerias duradouras.

Atualmente trabalhamos utilizando metodologias ágeis focado em resultado e inovação. Este processo acrescenta sinergia evolutiva entre o cliente e fornecedor, pois com a entrega rápida em prazo reduzido.

## Como se candidatar

Envie o seu cv para: rh@mblabs.com.br
Ou cadastre: https://lnkd.in/d6TZx8R

**Comment by jpventura** [comment]
@Kelvao junior, pleno ou senior?

**Comment by Kelvao** [comment]
Estamos avaliando todos os níveis.

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
