### ISSUE TITLE
VAGA REMOVIDA

### ISSUE THREAD

**Issue by renatoarg** [androiddevbr/vagas#945]
As regras deste mural de vagas exigem que o nome da empresa contratante seja divulgado. Estou encerrando esta issue, peço que a mesma seja recriada descrevendo o nome da contratante.

**Comment by oivlisnet** [comment]
Olá! Qual o nome da empresa e o link/e-mail para envio de currículo?

**Comment by renatoarg** [comment]
Oi Silvio,

Não posso falar a empresa cliente por enquanto, mas eh uma rede varejista
que está no Brasil inteiro.

Por favor, mande o CV para renatoarg@gmail.com

Obrigado!

Em qui, 17 de out de 2019 13:23, Silvio Guedes <notifications@github.com>
escreveu:

**Comment by graffiti75** [comment]
É vaga remota mesmo? Pois moro em Curitiba.
