### ISSUE TITLE
[Metrô Faria Lima, SP] Desenvolvedor(a) Android | Guia Bolso

### ISSUE THREAD

**Issue by fcjonas** [androiddevbr/vagas#947]
## Descrição da vaga

Devs mobile dos nossos squads estão imersos em cultura ágil, se responsabilizam de ponta a ponta pela engenharia de software e tem a missão de desenvolver o aplicativo Android usado pelos usuários Guiabolso, propondo soluções para problemas diversos junto com a equipe de produto. 
Como Dev Android você atuará na melhoria do nosso app, seja na etapa de onboarding de crédito ou experiência em todo o app.

## Local

Local de trabalho: Rua Butanta, 194, Pinheiros – São Paulo, SP

## Benefícios

Remuneração a Combinar
Vale Alimentação
Vale Refeição
Vale Transporte
Assistência Médica
Assistência Odontológica
Bônus semestral de até um salário 1 e meio (de acordo com o atingimento de metas)
Seguro de vida
Dog Friendly
Gympass
Stock Options
Frutas no escritório
Wework
Metrô Faria Lima - 400 metros

## Requisitos

Obrigatórios
A nossa tecnologia está sendo construída utilizando Kotlin e utiliza programação orientada a objetos, padrões de projeto e engenharia de software. Você sabe usar ferramentas de build e automação, como o gradle, Jenkins? Sim? Então pode chegar. Somos heavy users de AWS e é fundamental ter alguma familiaridade com ferramentas de CI/CD!

## Contratação

CLT

## Nossa empresa

O Guiabolso nasceu em 2012 pra ajudar os brasileiros a fazerem escolhas “dinheirísticas” mais espertas e, aos poucos, fortalecer uma comunidade que, unida, consegue jogar melhor esse jogo, forçando o sistema financeiro a melhorar suas práticas.

Acreditamos que as melhores ideias surgem quando as pessoas estão trabalhando por um propósito maior. Aqui você pode aprender, ter grandes desafios e transformar a vida de milhões pessoas todos os dias enquanto se diverte.

## Como se candidatar

https://www.linkedin.com/in/jonas-cornelio-6b32a4194/
https://intera.talent-hacking.com/guiabolso/dev-android/

**Comment by jpventura** [comment]
@fcjonas junior, pleno ou senior?

**Comment by fcjonas** [comment]
Principalmente pleno, mas aceita as faixas de Pleno e Sênior!

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
