### ISSUE TITLE
[Aeroporto de Congonhas, SP] React Native Developer | Voe Gol (via Mazzatech)

### ISSUE THREAD

**Issue by taianeuchoac** [androiddevbr/vagas#949]
## Descrição da vaga
Atuará em uma squad responsavel por desenvolver aplicações para a área financeira da empresa.

## Local
Atuação no escritório da empresa, ao lado do aeroporto de Congonhas.

## Benefícios
Contratação PJ.

## Requisitos
Experiência com desenvolvimento em:
React Native, Redux, Redux Saga, Duck patterns, JavaScript ES6+, Git, App Store Connect, Play Console.

Desejáveis
- Experiência na área financeira.

## Contratação

PJ a combinar

## Nossa empresa
Profissional será contratado pela Mazzatech, uma consultoria de TI que esta no mercado há mais de 10 anos. Atuará alocado na GOL Linhas Aéreas, uma grande empresa aérea brasileira.

## Como se candidatar

Por favor envie um email para taiane@mazza.tech com seu CV anexado - enviar no assunto: Vaga React Native.

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
