### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Android - Banco Neon

### ISSUE THREAD

**Issue by CamilaNeon** [androiddevbr/vagas#95]
## Descrição da vaga

O profissional será responsável pelo desenvolvimento e manutenção do app Android, consumindo e alimentando dados a partir de uma api remota. A expectativa é que o profissional seja capaz de entregar um produto com requintes avançados de UX utilizando animações e navegação fluída.

## Local

Escritório São Paulo - Rua Oscar Freire, 1431

## Benefícios

- Horário Flexível
- No dress code
- happy hour semanal por conta da empresa
- sala de descanso/ videogame
- Subsidio para academia (Gym Pass)
- Subsidio Plano de Saúde
- Estacionamento ou Vale Transporte (sem desconto)
- Vale Cultura 

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android/ aplicativos nativos
- Conhecimentos avançados em Java.
- Conhecimentos avançados em animações.
- Experiência no uso de Web Services(REST, JSON/XML).
- Ter preocupação com a parte visual dos aplicativos.
- Adaptação de layouts para diferentes tamanhos de telas.
- Testes integrados.
- Elaborar modelagem de dados.
- Design Patterns.

Diferenciais
- Experiência com desenvolvimento para smartwatch
- Links com código no github e ou apps publicadas
- Ter trabalhado com jogos.

## Contratação

CLT a combinar

## Nossa empresa

O Neon é um banco novo e totalmente diferente. 
Ele nasceu do desejo de transformar, de revolucionar uma área que quase não se reinventa. E também nasce por cansaço. Estamos cansados de pagar uma fortuna em taxas e não receber um atendimento de qualidade, de ter que apelar pra uma lupa pra saber de verdade com que tipo de instituição estamos lidando. Inovar é ter coragem para mudar. 
Nosso aplicativo foi construído para facilitar a vida financeira e valorizar a experiência dos clientes. Tudo sem enrolação, sem blá blá blá. Somos transparentes e queremos continuar assim. 
Um banco acessível e aberto a conversas, opiniões e novas ideias.

## Como se candidatar

Por favor envie um email para seja@banconeon.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
@CamilaNeon Atualizei o título da vaga e as labels! :)

**Comment by CamilaNeon** [comment]
Obrigada Walmyr!
