### ISSUE TITLE
[Recife, PE] Android Mobile Developer | Bleu Empreendimentos

### ISSUE THREAD

**Issue by luizpaulogodoy** [androiddevbr/vagas#950]
## Descrição da vaga:

É desenvolvedor Android e está procurando um job?

Estamos buscando um desenvolvedor(a) Android, de todos os níveis, para somar à nossa equipe e que goste de trabalhar em um ambiente dinâmico, aprendendo novas tecnologias.

Se você gosta de trabalhar com inovação, é antenado, auto-didata, pro-ativo, possui um bom relacionamento interpessoal e gosta ou tem interesse de trabalhar em uma empresa com foco em Blockchain entre em contato conosco.

## Local:

Presencial, Recife - Pina(Rio Mar Trade Center)

## Benefícios:

Vale Refeição
Plano de Saúde
Estacionamento
Vale Transporte
Auxílio Combustível
Custeio de curso/workshop/palestras de aperfeiçoamento

## Diferenciais:

Geladeira aberta
Café à vontade
Chocolate e lanches livres

## Requisitos:

3 anos de experiência.
Conhecimento em Kotlin;
Adepto de boas práticas: Git-flow, Code Review, Refactoring, Debugging, Integração Contínua e Gerenciamento de Releases;
Especificar funcionalidades com o time e com clientes;
Capaz de auto-gerenciamento;
Inglês técnico (leitura e escrita).

## Desejável:

Aplicativos publicados;
Contribuições em projetos Open Source.

## Nossa empresa:

A Bleu Empreendimentos é uma empresa voltada para criação e desenvolvimento de tecnologia em Blockchain. Combinamos a inovação e descontração para o desenvolvimento de projetos.

## Como se candidatar:

Por favor envie um email para rh@bleu.com.br - enviar no assunto: [Android]

**Comment by jpventura** [comment]
@luizpaulogodoy júnior, pleno ou sênior?

**Comment by luizpaulogodoy** [comment]
> @luizpaulogodoy júnior, pleno ou sênior?

Pleno

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
