### ISSUE TITLE
[Remoto | Florianópolis, SC] Desenvolvedor(a) Android | ArcTouch

### ISSUE THREAD

**Issue by lucvaladao** [androiddevbr/vagas#952]
## Descrição da vaga

This is an opportunity for Android Developers with strong object-oriented programming experience and attention to detail and quality, to contribute to a variety of challenging and cutting edge apps.

Our projects usually range from three to six months. In a year, you could easily work on four different projects. We encourage collaboration and creativity. You will interact with our team of product managers, designers and engineers and may architect solutions with our customers and their engineers as well.

## Local

Florianópolis - SC

## Benefícios

- Health insurance
- Dental insurance
- Life insurance
- Flexible hours
- Work from home Fridays
- English school tuition assistance
- Snacks, beverages, and team meals
- Gaming, movie and karaoke nights
- Gympass membership
- Tech talks and meetups
- Diversity program
- Career planning and development

## Requisitos

- Java and/or Kotlin's knowledge
- Solid understanding of Android SDK
- Advanced object-oriented programming and knowledge of design patterns
- Experience with Agile and Test Driven or Behavior Driven Development
- Strong code refactoring skills
- Understanding of Material design principles and interface guidelines
- Familiarity integrating apps to RESTful APIs
- Advanced English

## Contratação

CLT

## Nossa empresa

ArcTouch has been developing award-winning mobile apps for phones and tablets since the original iPhone was introduced. We’ve completed hundreds of handcrafted custom apps for some of today’s most important brands including NBC, salesforce.com, Audi, CBS, Razorfish, Google, and Yahoo! [More info](https://arctouch.com/portfolio/).

## Como se candidatar

Cadastre-se pelo [link](https://grnh.se/cc0cae571). Sinta-se à vontade para mandar mensagem pra mim no Slack do AndroidDevBr (Lucas Valadão)!

**Comment by jpventura** [comment]
@lucvaladao junior, pleno ou senior?

**Comment by lucvaladao** [comment]
@jpventura Pleno e Sênior
