### ISSUE TITLE
[Remoto] Mobile Developer | Abacomm

### ISSUE THREAD

**Issue by DougFischer** [androiddevbr/vagas#954]
**About**

A Abacomm é um estúdio de design e transformação digital com base no Rio de Janeiro, conhecido por trabalhar com equipes locais e remotas. Trabalhamos tanto com projetos para dispositivos móveis (iOS e Android) quanto aplicações web (Vue.js, Node, etc). Nós valorizamos o conhecimento e a vontade de aprender mais do que formação superior e diplomas. Gostamos de trabalhar com profissionais apaixonados e envolvidos em comunidades, que interajam com outros profissionais e ajudem àqueles que estão começando.

**Job description**

Na posição de desenvolvedor(a) Mobile na Abacomm você irá trabalhar em conjunto com o gerente de produto e com os profissionais de UI/UX com o objetivo de reproduzir experiências visuais encantadoras para nossos projetos. Sua posição será levemente mais direcionada ao Android.

O candidato que buscamos precisa ser alguém experiente e apaixonado, que busca entregar um trabalho com qualidade acima do padrão de mercado e está sempre estudando e se atualizando em relação ao que há de mais novo em termos de ferramentas e processos.

Nessa posição você será responsável por toda a arquitetura, desenvolvimento, manutenção e planejamento da vida útil dos projetos iOS e Android da Abacomm. Poderá definir metodologias e tecnologias que desejar, entretanto deve garantir a operação e evolução constante dos projetos desenvolvidos.

Buscamos profissionais que tenham curiosidade em toda relação de frameworks (APIs) das plataformas buscando as melhores abordagens para cada aspecto de negócio ou de UX que precise ser resolvido.

**Key responsibilities**

- Propor sempre a melhor solução técnica para os projetos, com critérios racionais e não por mera opinião ou hype de mercado;
- Construir interfaces e protótipos funcionais para diversos tamanhos de tela;
- Traduzir layouts estáticos em interfaces bem construídas, agradáveis e intuitivas;
- Garantir que o layout está implementado de acordo com os specs que foram fornecidos pela equipe de criação (pixel perfect);
- Garantir que as aplicações sigam as melhores práticas de mercado, especialmente em relação a segurança;
- Saber discutir problemas do cliente/usuário com a equipe de criação e propor soluções de forma colaborativa;
- Acompanhar mudanças em regras e práticas das lojas de aplicativos para garantir que os apps atendam todas as exigências e recomendações das fabricantes;
- Ser auto-gerenciável e proativo;

**Requirements**

- Objective-C e Java;
- Android Studio e Xcode;
- Experiência trabalhando na construção de interfaces (de alta fidelidade);
- Experiência consumindo serviços REST;
- Experiência com Banco de Dados (tais como Realm, SQLite, etc);
- Experiência com CodeSign, Deploy e publicação de apps nas lojas;
- Gostar de implementar animações e layouts interativos/vivos;
- Ser organizado e responsável o suficiente para trabalho remoto;
- Algum conhecimento (mesmo que básico) com CocoaPods;
- GIT (branches, tags, boas práticas de commit, etc);
- Conhecer guidelines do Google Material Design e do Apple HIG;

**Desirable**

- Evitar o uso descontrolado de libs de terceiros quando não for realmente necessário;
- Experiência configurando ambientes de CI/CD como Bitrise, Travis, etc;
- Ter conhecimento básico de boas práticas de design;
- Ter inglês suficientemente avançado para leitura de posts, documentações e entendimento de vídeos, cursos online e etc;
- Gostar de apps e smartphones.
- Noções gerais de práticas ágeis (Lean, Scrum, Kanban, etc);
- Multitask: Eventualmente (tentamos evitar!) você será requisitado para trabalhar em mais de um projeto por vez.

**What will set you apart (not a requirement)**

- Ser ativo na comunidade (compartilhar ideias, se engajar em discussões, participar de eventos, etc);
- Experiência configurando ambientes para testes automatizados;
- Experiência prévia em apps com forte uso de APIs de localização;
- Testes automatizados de UI;
- Custom Animations;
- Swift e/ou Kotlin;

**What we offer**
 
- Contratação CLT com remuneração compatível com mercado/experiência;
- Trabalho home-office;
- Plano de saúde (cobertura nacional);
- Vale alimentação/refeição (Alelo);
- Day-off no dia do aniversário.

**How apply?**

- Para se candidatar, por favor preencha o formulário disponível nesse link: http://bit.ly/vagas-abacomm

**Comment by jpventura** [comment]
@DougFischer não está claro se é:
  - junior, pleno ou senior
  - dev android ou ios

**Comment by DougFischer** [comment]
@jpventura Obrigado pela dica! É Pleno ou Senior. A vaga é para Dev Mobile (generalista), porém com foco em Android.

**Comment by jpventura** [comment]
@DougFischer fazer uma postagem separada então aqui e no [CocoaHeadsBrasil](https://github.com/CocoaHeadsBrasil/vagas/issues) separando os requisitos das vagas

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
