### ISSUE TITLE
[Alphaville, SP | Berrine, SP] Android Developer | Dextra

### ISSUE THREAD

**Issue by Julianapessoto88** [androiddevbr/vagas#956]
## Descrição da vaga
Se você curte tecnologias de ponta e gosta de novos desafios...Aqui é o seu lugar!
Na Dextra, nossos developers são responsáveis pela expertise e conhecimento das tecnologias e propõem as melhores soluções técnicas durante todo o processo de desenvolvimento de software, garantindo o sucesso da entrega para o cliente.

## Local
Dextra  - Oportunidades para Berrine ou Barueri (Alphaville)

## Benefícios
- Cesta de benefícios personalizada + Plano de Saúde + GymPass
- Horário flexível;

## Requisitos
O que você precisa saber para ocupar esta vaga?
Programar.. Mas com paixão! 
Saber de Java e Kotlin e sobre desenvolvimento de telas para produtos digitais em Android (Componentes Nativos, Views, Criação de componentes customizados) 
Integração com API’s REST;

## Contratação
CLT Full

## Nossa empresa
Somos a Melhor Empresa de TI para se trabalhar segundo pesquisa do GPTW. Estamos localizados em Campinas e crescendo em SP e Floripa.
Saiba mais em: https://jobs.kenoby.com/dextra

## Como se candidatar
Favor enviar um e-mail para juliana.pessoto@dextra.com.br  com seu CV anexado ou link do Linkedin  - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
