### ISSUE TITLE
[Porto Alegre, RS] Android Developer

### ISSUE THREAD

**Issue by felipeespitalher** [androiddevbr/vagas#96]
## Description
Android Mobile Developers must be skilled enough to build custom Android applications for some of the world’s leading companies. Candidates must:
* Be able to develop an Android application from initial conception through submittal to the Android marketplace.
* Be proficient with Java and object-oriented programming, including software design and design patterns, as well as standard Java development tools such as IntelliJ, Android Studio, Eclipse or ADT.
* Be able to work with open source frameworks and third-party libraries specific to Android applications.

## Local
Porto Alegre, Rio Grande do Sul, Brazil 

## Benefits
* General benefits ( VR, VT, Heath Plan )
* Fun place with video game, 3d printer, HTC VR =]
* Possibility to travel to Chicago and New York

## Requirements 
* Fluency in English
* 1+ years of experience in application development on Android and 3+ years in Java/C++
* Most recent projects or job must be Android-based development
* Bachelor’s degree in Computer Science/Information Technology or related field (or equivalent education/experience)
* Strong OO design and development experience
* Experience with Android SDK
* Ability to work with data from outside APIs
* Ability to understand and parse XML, JSON and serialized data
* Experience with embedded relational databases (SQLite)
* Understanding of multi-threaded interface design
* Experience with Fragment-based Android application architectures
* Have at least one or two functioning apps in the Android market place
* Should be self-driven and operate independently with little guidance

## Spotlight
* Experience with multiple mobile platforms
* Experience with profiling, tuning, and optimizing Java applications
* Experience with third-party libraries and frameworks, such as those by SquareUp
* Experience rooting devices or building the platform from source
* Thorough knowledge of IntelliJ or Android Studio
* Experience building library projects for Android
* Experience dealing with streaming media on Android
* Familiar with JNI
* Experience with emerging Android devices such as smart watches

## Contratação
CLT a combinar

## Know us

www.isobar.com/br/en/about-us
www.facebook.com/iwsbrazilpoa

## How aplly?

https://iwsbrazil.workable.com/jobs/351571

**Comment by walmyrcarvalho** [comment]
@felipeespitalher Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by felipeespitalher** [comment]
Essa vaga já foi preenchida. Estou fechando o PR
