### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor(a) android

### ISSUE THREAD

**Issue by MauricioFalbo** [androiddevbr/vagas#960]
## Local

Escritório Rio de Janeiro - Cidade Nova

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Kotlin;
- Integração com API;
- Retrofit;
- Programação funcional e reativa;
- Injeção de dependências (Dagger);
- Utilização de Socket ;
- Configuração / Utilização de API de maps;
- Configuração / Envio de push notification;
- Flavors;
- Firebase;
- Realm;

Desejáveis
- Conhecimento em Android Architecture Components (Room, LivaData,ViewModel, Lifecycle Owner)
- Experiência em Desenvolvimento “full stack”

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para curriculosdeinformatica2019@gmail.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@MauricioFalbo segundo [o código de conduta](https://github.com/androiddevbr/vagas/blob/master/README.md) do mural de vagas, é necessário postar o nome da empresa 😉
