### ISSUE TITLE
[Campinas, SP] Desenvolvedor(a) Android | Venturus

### ISSUE THREAD

**Issue by AlineFrediani** [androiddevbr/vagas#961]
Estamos com duas oportunidades 1 Pleno e 1 Sênior
## Descrição da vaga

**Quem estamos buscando?**

Desenvolvedores Android que desejam construir aplicativos que impactem a vida de usuários. Que adorem desenvolvimento Mobile e aprender tecnologias para resolver problemas.

**Como será o seu dia a dia?**

Suas responsabilidades serão voltadas para o desenvolvimento de aplicativos participando desde a arquitetura até a publicação na Google Play. Projeto com Design Thinking e metodologia de desenvolvimento ágil.

## Local

Campinas-SP

## Requisitos

**Competências e experiência necessárias:**

Formação: Ensino Superior Completo na área de TI ou correlacionadas;

Experiência em desenvolvimento Android Java, arquitetura MVVM;

Inglês: leitura/escrita avançado e conversação nível intermediário;

**Competências e experiência desejável:**

Conhecimento da ferramenta Jira, GitLab e DevOps com Jenkins.
## Contratação

CLT 

## Nossa empresa

Descubra sobre o Venturus em http://www.venturus.org.br/

## Como se candidatar: clique no link abaixo:

https://jobs.kenoby.com/venturus/job/desenvolvedor-mobile-android/5db7046628e57c7567903cc6

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
