### ISSUE TITLE
App Meio de pagamento - Zona Leste - Itaquera

### ISSUE THREAD

**Issue by owdeveloper** [androiddevbr/vagas#963]
## Descrição da vaga

Aplicativo meio de pagamento.

## Local

Escritório em São Paulo - Itaquera

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados

Desejáveis
- Experiência com Espresso e UI Automator
- Experiência com RxJava

Diferenciais
- Projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Consultoria e desenvolvimento especializada em mobile nativo

## Como se candidatar

Por favor envie um email para fernando@owldeveloper.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@owdeveloper segundo [o código de conduta](https://github.com/androiddevbr/vagas/blob/master/README.md) do mural de vagas, é necessário postar o nome da empresa.
