### ISSUE TITLE
[Metrô Consolação, SP] Android Developer | AMARO

### ISSUE THREAD

**Issue by vithoriaamaro** [androiddevbr/vagas#964]
##  Descrição da vaga

Projeto de desenvolvimento de um app de corrida, etc.

## Local

Av. Paulista / São Paulo

## Benefícios

- Plano de saúde
- VR/ VA
- Gympass
- Desconto em produtos
- Convênio Farmácia

Diferenciais

- frutas no escritório 2x por semana
- happy hour

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Conhecimento em metodologias ágeis
- Experiência com desenvolvimento de APIs
- Desenvolvimento de testes unitários (TDD)

Desejáveis
- Experiência desenvolvimento em Kotlin
- Inglês avançado

## Contratação

CLT 

## Nossa empresa

A AMARO é uma empresa de tecnologia que veio para (r)evolucionar o mundo da moda 
https://amaro.com/sobre-nos

## Como se candidatar

Por favor envie um email para vithoria.duarte@amaro.com com seu CV anexado - enviar no assunto: Front End Developer

**Comment by jpventura** [comment]
@vithoriaamaro júnior, pleno ou sênior?

**Comment by vithoriaamaro** [comment]
Oi @jpventura pleno/sênior. Próximo ao metrô Consolação

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
