### ISSUE TITLE
[Curitiba, SP] Desenvolvedor(a) Android | Mercafacil 

### ISSUE THREAD

**Issue by manoelaalmeida** [androiddevbr/vagas#965]
Desenvolvedor Android - Curitiba 

Se você está em busca de um desafio que proporcione muito aprendizado e desenvolvimento essa é a sua chance!
Aqui na Mercafacil, estamos buscando um fera que responsável por desenvolver aplicativos móveis, com foco na plataforma Android.
Deverá também dar manutenção, corrigir bugs e desenvolver novas funcionalidades nos aplicativos da Mercafácil.
Tudo isso em um ambiente com bastante troca de conhecimento, onde você será peça chave para o desenvolvimento do nosso Produto!﻿

Curitiba - PR

Escritório em Curitiba - PR

## Benefícios

- Benefícios Flex (Vale Refeição, Vale Alimentação e Vale Combustível, Uber e estacionamento);
- Horário Flexível;
- Seguro de Vida;
- No Dress Code (apoiamos a diversidade e acreditamos na integração de diferentes perfis para a construção uma empresa ainda mais incrível);
-DayOff de Aniversário;
- Benefícios nas Férias;
- Convênio com Universidades e cursos incríveis;
- MercaClub (sempre novas parcerias para você aproveitar);
- Programa de Indicações Internas;
- Metodologia OKR Trimestral;

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados
- Experiência anterior em desenvolvimento nativo: Kotlin;
- Vivência com Metologia Scrum.

Desejáveis
- Integração com APIs REST (manutenção nas definições OpenApi/Swagger);
- Integração com APIs GraphQL;
- Experiência com Espresso e UI Automator
- Experiência com RxJava

## Contratação

CLT a combinar

## Nossa empresa

Somos uma startup curitibana que tem como missão potencializar a conversão de vendas no varejo a partir da melhor experiência de consumo. Ajudamos varejistas a expandir o negócio de forma segura, entendendo o comportamento de consumo com inteligência e, principalmente, aumentando o lucro. Isso é possível pela criação e gerenciamento de uma base de dados acionável capaz de mapear as vendas e possibilitar conexões significativas com cada consumidor. Utilizamos tecnologias de Big Data, Data Mining e Geolocalização para fornecer informações estratégicas e aproximar a comunicação com os consumidores mostrando o que eles querem na hora que precisam.

## Como se candidatar

Direto pelo link https://mercafacil.gupy.io/jobs/95670?jobBoardSource=gupy_public_page
ou email para manoela.almeida@mercafacil.me  com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@manoelaalmeida júnior, pleno ou sênior?

**Comment by manoelaalmeida** [comment]
Olá,

Busco alguém mais pra Pleno/Sênior

Em qua, 30 de out de 2019 08:40, JP Ventura <notifications@github.com>
escreveu:

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
