### ISSUE TITLE
[Rio de Janeiro, RJ] Desenvolvedor(a) Android | Hotel Urbano

### ISSUE THREAD

**Issue by thiagocortat** [androiddevbr/vagas#97]
## Descrição da vaga

Faça parte do time HU. 
Uma das maiores agências de turismo online do mundo precisa do seu talento. Estamos procurando um desenvolvedor Android para nosso aplicativo!
Procuramos pessoas inteligentes e ágeis como você para nos ajudar a resolver os nossos desafios.
Você vai trabalhar, no seu dia-a-dia, buscando a alta disponibilidade e qualidade, atuando dentro de um time multidisciplinar.

## Local

Alocado, Rio de Janeiro - Barra da Tijuca

## Benefícios
- Assistência Médica,
- Assistência Odontológica,
- Tíquete-refeição
- Horário Flexível
- Seguro de vida
- Auxílio Creche

## Requisitos

Obrigatórios
- 3+ anos de experiência com Android
- Confortável com padrão MVP, MVC, MVVM e derivados
- Ter facilidade para trabalhar dentro de times multi-disciplinares;
- Saber escrever código limpo e legível;
- Possuir conhecimentos de integração utilizando API RESTful;
- Ter conhecimento de práticas de XP (TDD, pair programming, refactoring, continuous integration, etc);
- Conhecer e ter experiência com testes unitários, de aceitação, mocks, etc;
- Saber trabalhar com ferramentas de controle de versão;
- Experiência com RxJava

Diferenciais:
- Experiência com Espresso e UI Automator
- Ter experiência com Kotlin;
- Conhecimentos de desenvolvimento WEB (HTML, CSS, Javascript, jQuery, etc);
- Ter experiência com React Native;
- Ter experiência com Objective C e/ou Swift;
- Conhecimentos de automação de publicação de aplicações (fabric, etc);

## Contratação

CLT - Pleno, Sênior ou PJ a combinar

## Nossa empresa
 
A visão do Hotel Urbano é realizar o match dos nossos usuários com a viagem dos sonhos.

Números do HU:
mais de 180.000 hotéis ao redor do mundo;
18 milhões de viajantes cadastrados;
1 diária vendida a cada 8 segundos;
20 milhões de pessoas buscando viagens todo mês;
12 milhões de fans no facebook;

## Como se candidatar

Por favor envie um email para mobile@hotelurbano.com.br com seu CV anexado, mencionando apps publicados desenvolvidos por você. Enviar no assunto: Vaga Dev Android.

**Comment by walmyrcarvalho** [comment]
@thiagocortat Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!
