### ISSUE TITLE
[Bairro Berrini, SP] Desenvolvedor(a) Android | SENNIT 

### ISSUE THREAD

**Issue by Silvana-alcides** [androiddevbr/vagas#970]
## Descrição da vaga

 Estamos buscando Desenvolvedores Mobile Android para fazer parte da nossa equipe.

## Local

Local: Região Berrini Zona Sul – São Paulo

## Requisitos
 Experiência com análise e desenvolvimento de aplicativos Mobile. 
Experiência consumo de APIs REST.
Experiência em integrações XML. 
Experiência com a linguagens Java, (Android Studio), Kotlin.
Conhecimento com a metodologia SCRUM.

## Contratação

PJ 

## Nossa empresa

SENNIT

## Como se candidatar
Favor enviar o currículo com a pretensão salarial no e-mail oportunidades@sennit.com.br
Whatssapp (11)97658-8399

**Comment by jpventura** [comment]
@orafaaraujo dúvidas:

  - Contrato será feito diretamente com a SENNIT?
  - Júnior, pleno ou sênior?
  - Presencial ou remoto?
  - Alocado em cliente ou presencial na SENNIT?

**Comment by Silvana-alcides** [comment]
Boa tarde,

Segue os dados:

  *   Contrato será feito diretamente com a SENNIT? Sim
  *   Júnior, pleno ou sênior? Sênior
  *   Presencial ou remoto? Presencial
  *   Alocado em cliente ou presencial na SENNIT? Ficar alocado na consultoria Sennit.



Qualquer dúvida estou à disposição.

Att,
[cid:image001.jpg@01D54C74.927D9A40]
Silvana Ferreira
Diretoria de Recursos Humanos/Comercial

[call, phone icon]
(11) 3213-3496
[mobile, phone icon]
(11) 9.7658- 8399
[email, mail icon]
silvana.ferreira@sennit.com.br<mailto:silvana.ferreira@sennit.com.br>
[browser, internet explorer icon]
www.sennit.com.br<http://www.sennit.com.br/>


De: JP Ventura <notifications@github.com>
Enviada em: segunda-feira, 4 de novembro de 2019 14:51
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: Oportunidades <oportunidades@sennit.com.br>; Author <author@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] [Bairro Berrini, SP] Desenvolvedor(a) Android | SENNIT (#970)


@orafaaraujo<https://github.com/orafaaraujo> dúvidas:

  *   Contrato será feito diretamente com a SENNIT?
  *   Júnior, pleno ou sênior?
  *   Presencial ou remoto?
  *   Alocado em cliente ou presencial na SENNIT?

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
