### ISSUE TITLE
[Remoto | Florianópolis, SC] Desenvolvedor(a) Android | PEIXE URBANO

### ISSUE THREAD

**Issue by lelecoral** [androiddevbr/vagas#971]
## Descrição da vaga

No seu dia a dia aqui no PU você vai: 

- Participar do desenvolvimento de apps relacionados ao negócio do Peixe Urbano & Groupon Latam na plataforma Android;
- Identificar, diagnosticar e corrigir de bugs;
- Contribuir no desenvolvimento e adoção de melhores práticas no time

## Local

Remoto ou Escritório de Florianópolis, SC.

## Requisitos

- Ensino superior completo em Ciência da computação, Engenharia da computação, Analise e Desenvolvimento de Sistemas ou áreas correlatas;
- Mais de 3 anos de experiência criando apps para Android (Kotlin e Java);
- Experiência ou conhecimento de metodologias ágeis (Scrum e Kanban);
- Experiência com consumo de dados via REST e padrão JSON;
- Conhecimentos gerais do ambiente mobile, como: arquiteturas, padrões, tendências e tecnologias emergentes;
- Conceitos sólidos em orientação a objetos;
- Desejável experiência e cultura de testes (unitários e instrumentais);
- Preocupação em detalhes de tela: olhos clínicos para as definições de design

Diferenciais

- Arquitetura MVVM com Architecture Components
- Conhecimento em Clean Architecture

## Contratação

PJ a combinar

## Nossa empresa

O Peixe Urbano é a maior plataforma de ofertas locais do Brasil. Com mais de 30 milhões de usuários cadastrados e milhares de ofertas de gastronomia, entretenimento, estética, turismo e produtos, sua missão é conectar pessoas a serviços com o melhor custo-benefício.

## Como se candidatar

Por favor envie um email para leticia.coral@peixeurbano.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by walmyrcarvalho** [comment]
Fechado a pedido da pessoa que abriu a issue.
