### ISSUE TITLE
[Curitiba, PR] Desenvolvedor(a) Android | James Delivery

### ISSUE THREAD

**Issue by repeixoto** [androiddevbr/vagas#972]
OI! EU SOU O JAMES!
Sou o primeiro delivery de tudo do Brasil. Pela minha plataforma, conecto entregadores, consumidores e estabelecimentos, entregando qualquer produto da cidade em um tempo médio de 30 minutos. Eu quero ser mais do que um delivery particular. Quero ser seu melhor amigo! :D

Acredito na tecnologia como uma ferramenta que trabalha em favor da sociedade, tornando a vida das pessoas mais fácil e descomplicada. Acima de tudo, valorizo a humanização e as conexões interpessoais, por isso busco construir um ambiente saudável e estimulante em todos os níveis.
Somos mais de 300 Jamers!
Atuação em 10 cidades... e vem muito mais por aí!

Por meio do nosso app levamos praticidade e conforto à vida das pessoas! Com apenas alguns cliques, oferecemos a maneira mais prática de receber seu delivery, que vai muito além de comida. É do produto que você quiser e de qualquer lugar da cidade! E, para que isso tudo funcione da melhor forma, estamos em busca de um profissional para fazer parte do nosso time de Android! Confira abaixo e vem pro seu melhor job! 👍 

Desenvolvedor Android 

Especificações da vaga: 
É interessante e necessário possuir conhecimento e participado de projetos de desenvolvimento de aplicativo Android nativo publicado na Google Play;
Linguagem Kotlin;
Arquitetura MVVM;
Linguagem Java e Orientação a objetos;
Arquitetura MVP;
Notificações push com FCM;
Consumo de APIs Rest utilizando Retrofit;
Android Architecture Components (LiveData, ViewModel, Room);
Injeção de dependências utilizando Dagger ou Koin.

Seria muito bacana você também conhecer: 
Integração e Delivery contínuo (GitLab, Bitrise);
Testes automatizados com Espresso, Mockito e Junit;
Listas complexas utilizando RecyclerView e DiffUtil;
Kotlin Couroutines;
Lambdas, Extensions e DSLs Kotlin;
Animações e transições nativas;
Android App Bundle e Instant Apps;
Gradle Build Flavors;
Firebase Realtime Database, Cloud Messaging;
Conhecimento em recursos de localização do dispositivo (GPS, Network);
Experiência no desenvolvimento de soluções utilizando câmera e bluetooth;
Android Paging e WorkManager Components;
Android Navigation Component;
GitFlow;
RxJava;
Banco de dados utilizando Realm;

Atuação em nosso escritório em Curitiba/PR

Contratação CLT.

Benefícios? Temos! :)
• Bônus por metas globais;
• Plano de saúde subsidiado pela empresa (com coparticipação);
• Plano Odontológico;
• Seguro de vida;
• Vale refeição (ou alimentação) para o almoço com a galera; 
• Vale transporte;
• Gympass;
• Promo code para pedidos no app do James;
• Estacionamento para bikes;
• Horário flexível;
• No dress code;
• Espaço com conveniências;
• Copa com geladeira, microondas e cafeteiras para aquela disposição no dia a dia :)
• Além de um ambiente colaborativo, com oportunidade de desenvolvimento e crescimento profissional!

Ficou interessado(a)? Se candidate pelo nosso site! https://james.gupy.io/

Acompanhe minhas redes sociais:
Site: www.jamesdelivery.com.br/
LinkedIn: www.linkedin.com/company/james-delivery/
Instagram: www.instagram.com/jamesdelivery
Facebook: www.facebook.com/JamesDeliveryBR/

**Comment by jpventura** [comment]
@repeixoto júnior, pleno ou sênior?

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
