### ISSUE TITLE
[Taboão da Serra, SP] Desenvolvedor(a) Android | G&P

### ISSUE THREAD

**Issue by julianafoguel** [androiddevbr/vagas#973]
## Descrição da vaga

DESENVOLVEDOR ANDROID
Profissional com experiência em Android: Java, Kotlin, Lifecycle, Services, Broadcast Services, Firebase Cloud Messaging, Material Design, FCM Notifications, Google Maps, Bluetooth, Voice Recorder, SQLite, MVP, MVVM, processo de publicação na Play Store e integrações com Redes Sociais (Twitter e Facebook); Web Services: REST e SOAP; GIT.

## Local

Escritório: Taboão da Serra – SP (Estacionamento Gratuito ... Tem fretado que pega os funcionários na estação Morumbi e leva até o cliente)

## Benefícios

- VT (6%)
- VR 20,00 (pode ser trocado pelo VA)
- Seguro de Vida 
- AM Intermédica (Co-participação)
- AO MetLife (planos a partir de 13,20)
- Auxilio Creche – 0 a 24 meses 482,00 – 24 a 60 meses 421,75
- Parcerias com Instituições de Ensino (faculdades, cursos técnicos e escolas de idioma), 
- Desconto com Parceiros Vida Link (lazer, academia e farmácia),
- Reembolso de Certificação
- Carteirinha do SESC.

## Contratação

CLT Full a combinar

## Nossa empresa

Fundada em 1989, a G&P caracteriza-se por uma trajetória de sólido crescimento, permanentes investimentos em qualificação profissional e uma reconhecida excelência operacional.

Com base nas melhores práticas de governança de TI, a empresa tem uma marca de longevidade e qualidade nas atuações técnicas operacionais, e principalmente, serviços na modalidade projeto fechado e outsourcing total.

A empresa conta com uma equipe especializada em Gestão de Pessoas capacitada para o recrutamento, seleção, treinamento e acompanhamento de carreira dos seus mais de 1.500 colaboradores distribuídos no território nacional.

## Como se candidatar

Por favor envie um e-mail para juliana.foguel@gpnet.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
@julianafoguel júnior, pleno ou sênior?

**Comment by julianafoguel** [comment]
Tenho vagas de Pleno e Sênior



Enviado do meu smartphone Samsung Galaxy.


-------- Mensagem original --------
De : JP Ventura <notifications@github.com>
Data: 04/11/2019 15:43 (GMT-03:00)
Para: androiddevbr/vagas <vagas@noreply.github.com>
Cc: julianafoguel <julianabeatrizandrade@hotmail.com>, Mention <mention@noreply.github.com>
Assunto: Re: [androiddevbr/vagas] DESENVOLVEDOR ANDROID (#973)


@julianafoguel<https://github.com/julianafoguel> júnior, pleno ou sênior?

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
