### ISSUE TITLE
[Bairro Brooklin Paulista, SP] Android Developer | Petlove

### ISSUE THREAD

**Issue by DayaneVeronez** [androiddevbr/vagas#974]
## Descrição da vaga

Aqui na Petlove, nós desenvolvemos e continuamos expandindo uma plataforma tecnológica própria. A stack é baseada em aplicações e micro serviços que utilizam tecnologias como Ruby on Rails, NodeJS e Elixir, Bancos de Dados MySql, Postgres e Elastic Search. Somos 100% Cloud e nossa infra é baseada em containers Docker e Kubernetes.

O time de tecnologia, que atualmente está em fase de crescimento acelerado, é formado por mais de 30 profissionais entre desenvolvedores Frontend, Backend, Mobile, Fullstack, Devops e de Infraestrutura. Os petlovers do time de tecnologia estão alocados em squads diversos, o que permite maior foco e qualidade nas entregas, além da autonomia e liberdade de trabalho presentes em todas as áreas da empresa.

Curiosidades sobre o time: os desenvolvedores da Petlove são amantes de café e ping pong assumidos!

Se você é uma pessoa analítica, com um forte background em Java , Arquitetura MVC / MVP e Web Services / REST temos uma ótima oportunidade para você:
Procuramos um profissional experiente para contribuir no desenvolvimento da nossa plataforma de produtos.

## Local

Escritório São Paulo - Berrini.

## Benefícios

- Assistência médica e odontológica 100% custeada pela empresa; 
- Vale Refeição (podendo dividir com Vale Alimentação; 
- Crédito para Snacks; - Bicicletário no prédio; 
- Sala de descompressão com vídeo-game, mesa de ping-pong e pebolim; 
- Day-off de aniversário; 
- Ambiente descontraído e dinâmico; 
- Parcerias com descontos; 
- Desconto em produtos no site; 
- PLR - Atrelado a metas; 
- Gympass;
- E claro, Pet Friendly, pets são muito bem vindos no escritório!!

## Requisitos

**O que esperamos de você:**

- Experiência com desenvolvimento Android;
- Excelente conhecimento na linguagem Java;
- Conhecimentos nas arquiteturas MVP, MVVM;
- Conhecimento de Design Patterns;
- Experiência em testes automatizados;
- Experiência com Git;
- Experiência com REST APIs;
- Experiência em gerenciamento de dependências.

**Diferenciais**

- Conhecimento em Dagger;
- Conhecimento em RxJava;
- Conhecimento em Kotlin;
- Conhecimento / interesse em aprender iOS;
- Familiaridade com a cultura ágil;
- Conhecimento em NodeJS;

## Contratação

CLT

## Nossa empresa

A Petlove é o maior petshop online e clube de assinaturas para pets do Brasil. Nascemos em 1999 a partir do sonho visionário de um médico veterinário que foi pioneiro em apostar na venda online de produtos pets em uma época em que a internet no país ainda era uma incerteza. Somos investidos pelos melhores fundos de venture capital do Brasil e estamos em ritmo de crescimento acelerado para continuarmos cumprindo nossa principal missão: ajudar pais e mães de pets a fazerem seus filhos peludos mais felizes e saudáveis. 

## Como se candidatar

Por favor envie um email para vagasti@petlove.com.br com seu CV anexado - enviar no assunto: Vaga Android ou se cadastrar no link: https://petlove.gupy.io/jobs/111770

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
