### ISSUE TITLE
[São Paulo, SP] Desenvolvedor(a) Android | PSM Company

### ISSUE THREAD

**Issue by Anapribeiro** [androiddevbr/vagas#979]
**Descrição da vaga**
DESENVOLVEDOR ANDROID
Profissional com experiência em Android: Java, Kotlin, e, MVP, MVVM, Web Services: REST e SOAP; e GIT.

**Local**
Escritório: Zona Sul de São Paulo

**Benefícios**
VT (6%)
VR 
Seguro de Vida
AM 
AO 
Auxilio Creche – 0 a 24 meses 482,00 – 24 a 60 meses
Parcerias com Instituições de Ensino (faculdades, cursos técnicos e escolas de idioma),
Contratação
CLT Full a combinar

**Nossa empresa**

Em seu 11º ano de atuação, a PSM Company é referência de mercado, Somos especializados na identificação de Talentos para as áreas de TI / Telecom como também para as áreas operacionais e administrativas.
venha fazer parte da nossa equipe, vem pra PSM.

**Como se candidatar**
Por favor envie um e-mail para ana.silva@psmcompany.com.br com seu CV anexado - enviar no assunto: Vaga Android

**Comment by davidtcdeveloper** [comment]
@Anapribeiro A vaga é para uma pessoa ser contratada pela PSM ou será contratada por outra empresa. As regras do nosso mural exigem a divulgação do nome da empresa, por isso precisamos desta informação bem clara.

**Comment by Anapribeiro** [comment]
@davidtcdeveloper para fazer parte da PSM.

**Comment by davidtcdeveloper** [comment]
> @davidtcdeveloper para fazer parte da PSM.

Show

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
