### ISSUE TITLE
[São Paulo/SP - Zona Sul]  - Android Engineer

### ISSUE THREAD

**Issue by gabimollo** [androiddevbr/vagas#98]
**_Recruto para Startup com produto fantástico e extremamente inovador: acabaram de ser selecionados pelo Google para programa global de aceleração._**

**Responsibilities**
Develop and maintain our native mobile apps (Android)
Consume RESTful APIs to implement new functionalities that enhance the quality of our product
Bring pixel perfect UI/UX into life

**Requirements**
Senior experience coding in relevant startups and/or personal projects
Relevant Startup experience
Advanced knowledge of Android Java

**Local de trabalho:**
Vila Mariana

**Contratação:**
CLT Full

**Benefícios:**
Salário competitivo
Oportunidade de ganhar Stock Options
Assistência médica
Gym Pass
Bonus para upgrade deconfiguração de notebook
Cozinha com chefe de cozinha
Ambiente fun

Interessados enviar cv para gaby_mollo@hotmail.com

**Comment by zontag** [comment]
Cidade? Faltou conformizar o título..

**Comment by gabimollo** [comment]
Tks @zontag 
Feita alteração!

**Comment by walmyrcarvalho** [comment]
@gabimollo Essa vaga ainda está aberta? Senão irei fechar, pra fins de organização!

**Comment by walmyrcarvalho** [comment]
Fechada a pedido da dona da issue.
