### ISSUE TITLE
Desenvolvedor Mobile Android - Lapa - SP

### ISSUE THREAD

**Issue by owdeveloper** [androiddevbr/vagas#981]
## Descrição da vaga
Estamos buscando Desenvolvedores Mobile Android para fazer parte da nossa equipe.

## Local
Local: Lapa Zona Oeste, Próximo faculdade Flamingo – São Paulo

## Requisitos
Experiência consumo de APIs REST.
Experiência com a linguagens Java, Kotlin (Android Studio).

## Contratação
PJ

## Nossa empresa
OWL Developer

## Como se candidatar
Favor enviar o currículo com a pretensão salarial no e-mail fernando@owldeveloper.com.br
Whatssapp (11)97522-5700

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
