### ISSUE TITLE
[RS - Porto Alegre] - Phi [Hub 4all Tecnologia] - Desenvolvedor (a) Android 

### ISSUE THREAD

**Issue by micheliane** [androiddevbr/vagas#984]
Essa oportunidade é para Fintech do Hub. São os meios de pagamento do hub. Fintech as a service, ou seja, criamos fintechs, pois os meios de pagamento estão mudando. Saiba mais acessando: http://somosphi.com
Aproveite para conhecer um pouquinho mais sobre como é a vibe da 4all clicando aqui 👉 www.instagram.com/pordentroda4all 😉

**Habilidades e experiências necessárias:**
Conhecimentos em Kotlin e Java;
Experiência com: Git; integrações a web service; orientação a objetos e design patterns;
Conhecimento do padrão MVVM e dos guidelines de design do Google (Material Design);
Também é necessário conhecimento em: Analytics; Gradle (flavors, build type); testes e frameworks de teste (JUnit, Mockito Kotlin, Espresso) e componentes do Android Jetpack (Data Binding, Room, Animações e Transições).

**Consideramos diferenciais:**
Criação de componentes customizados;
Experiência com padrão MVVM utilizando Architecture Components;
Conhecimento em: CI; Coroutines e em programação funcional;
Experiência em testes unitários.

Tecnopuc - Porto Alegre/RS

Pleno e Sênior

Presencial- CLT

Inscrições: https://4all.gupy.io/jobs/96732

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
