### ISSUE TITLE
[SP, Pinheiros] Desenvolvedor Android

### ISSUE THREAD

**Issue by gabrielylopes** [androiddevbr/vagas#986]
## Descrição da vaga
A Foco em Você está buscando por Desenvolvedor Android.
Profissional com experiência em Android: Java, Kotlin, e, MVP, MVVM, Web Services: REST e SOAP; e GIT

## Local
Escritório São Paulo - Pinheiros

## Contratação
PJ 

## Como se candidatar
Por favor envie um email para gabriely@focoemvoce.com.br com seu CV atualizado anexado - enviar no assunto: Desenvolvedor Android - GitHub

## Labels
- Pleno
- Sênior
- PJ
- Alocado

**Comment by davidtcdeveloper** [comment]
@gabrielylopes A empresa contratante é a Foco em você? Pelas regras do nosso mural de vagas, o nome da empresa contratante deve ser divulgado.

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
