### ISSUE TITLE
[Vila Olimpia, SP] Desenvolvedor(a) Android na ClickBus

### ISSUE THREAD

**Issue by vgchabelman** [androiddevbr/vagas#987]
## Descrição da vaga

Venha ser um (a) ClickBuser! 🚌🚌🚌

A ClickBus é a maior plataforma online de vendas de passagens rodoviárias no Brasil, temos como um de nossos valores o foco no cliente e por isso somos incansáveis na busca por inovação do setor.

Agilidade e ousadia está em nosso sangue, aqui levamos muito em conta a colaboração inclusive nosso processo seletivo é feito por todos os ClickBusers, somos todos responsáveis pela busca por novos integrantes para embarcar nesse busão acelerado!

E a viagem, como vai ser? 

Nosso time de tecnologia está dobrando de tamanho e precisamos de Desenvolvedores Android para nos ajudar nesse crescimento! Está a fim de encarar esse mega desafio? 

## Local

Escritório São Paulo - Vila Olímpia

## Benefícios

- Ambiente de trabalho descontraído, com espírito de equipe e pessoas talentosas;
- Incentivo e autonomia para trabalhar, desenvolver e implementar ideias;
- Empresa que valoriza a melhor versão de você mesmo;
- Frutas todos os dias;
- Café para quem é de café;
- Chá para quem é de chá;
- Horário flexível;
- Espaço para soneca (aquela recarga) e vídeo game;
- Vale refeição/alimentação de R$31,00/dia;
- Vale transporte;
- Gympass;
- Auxílio Creche;
- Plano de saúde sem co-participação;
- Plano odontológico;
- Seguro de vida;
- Local de trabalho: Vila Olímpia próximo da estação

## Requisitos

Obrigatórios
- Experiência com Kotlin/Java para android;
- Conhecimento em Android Studio, Git, Google e Firebase Analytics;
- Conhecimento nos frameworks: Retrofit, Dagger 2, Realm;
- Conhecimento em Custom Views (desejável);
- Conhecimentos nas arquiteturas MVP e Repositories;

Desejáveis
- Conhecimento em ferramentas como Appium, Invision, PlayStore (assinatura e envio de apks), Fabric;	
- Inglês intermediário.

## Contratação

CLT a combinar

## Como se candidatar

Acesse https://jobs.kenoby.com/clickbus/job/desenvolvedora-android/5d0a664e83a60141be9a237d e envie seu CV

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
