### ISSUE TITLE
[Vila Olimpia, São Paulo] Desenvolvedor Android

### ISSUE THREAD

**Issue by gabrielylopes** [androiddevbr/vagas#988]
## Descrição da vaga
A Approvata está em busca de Desenvolvedores Android, para atuar em um banco de investimentos.

## Local
Escritório São Paulo - Vila Olímpia

## Requisitos
Experiencia com:
• Kotlin;
• Retrofit, Android Annotations, Material Designer, Push Notification, LiveData
• Criação de componentes personalizados Android nativo;
• Conceito de código limpo e melhores práticas;
• Utilização arquitetura MVP, MVC, MVVM;
• JSON, REST, SOAP;
• Conhecimento em Design Patterns;
• Metodologia SCRUM;
• Análise de Requisitos;
• Git;

## Contratação
PJ 

## Como se candidatar

Por favor envie um email para gabriely@focoemvoce.com.br com seu CV anexado - enviar no assunto: Vaga Android - GitHub

## Labels
- PJ
- Sênior
- Pleno
- Alocado

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
