### ISSUE TITLE
[Remoto] Android Hero | InEvent

### ISSUE THREAD

**Issue by arturgaleno** [androiddevbr/vagas#99]
**ANDROID HERO DA INEVENT**

A InEvent está a procura de um(a) profissional com abições de crescer junto com uma equipe de jovens empreendedores em uma startup no mercado de eventos. Se você acha que é capaz de inovar na forma como desenvolvemos e criamos nossas plataformas, introduzir novos conceitos e formas de nossos sistemas mais robustos e poderosos, você está no lugar certo. Venha conosco fazer parte da construção desta empresa consciente que vai mudar o mercado de eventos no Brasil e mundo à fora!

**SOBRE A INEVENT**

A InEvent é uma startup B2B que desenvolve um aplicativo inteligente para organizadores de eventos possibilitarem interação, negócios e networking dentro deles, facilitando toda a troca de informações entre os principais stakeholders. Nós ajudamos a construir grandes histórias dentro dos eventos através de um SaaS web e mobile.

**SOBRE A VAGA**

Buscamos profissionais com vontade de aprender, que gostam de acompanhar inovações e novas formas de resolver problemas. Dentro da InEvent, você poderá:

Aprender modelos de desenvolvimento usados nas nossas plataformas;

Inovar e reestruturar parte dos nossos sistemas (estrutura + design);

Aprender sobre automatização de processos para a produção e entrega de aplicativos em larga escala.

Trabalhar com uma equipe capacitada e pronta para aprender e ensinar todo tipo de experiência e conhecimento;

Otimizar a performance do aplicativo mobile para diferentes versões e modelos de dispositivos Android, incluindo adaptações para tablets.

Implementar as funcionalidades das novas APIs da Google, com suporte mínimo API 14. Atualizar funcionalidades para adequar ao visual indicado pelo Material Design.

Ter flexibilidade de horário e de local de trabalho!

Participar de eventos de empreendedorismo e tecnologia.

**PERFIL IDEAL**

Capacidade de aprendizado rápido e percepção na resolução de problemas;

Conhecimento e experiência em desenvolvimento com Java/XML e Gradle (Groovy).

Ter desenvolvido algum projeto utilizando alguma IDE baseada no Intellij IDEA. Prática com Android Studio é um diferencial.

Ter prática utilizando ferramentas como repositórios opensorces mantidos pela InEvent (https://github.com/ineventapp) e JIRA.

Estar preparado para trabalhar em um ambiente remoto e confortável com um ambiente UNIX e plataformas de versionamento de código (GIT).

Criatividade e curiosidade para aprender e aplicar novos conceitos em nossas plataformas;

Gostar de hackathons, ter o espírito de um hacker - quando requisitado, resolver o problema com paixão e vontade;

Colaborar ativamente com a geração de valor da InEvent, tendo coragem para ser desafiado e disposição para propor melhorias necessárias.

**INFORMAÇÕES SOBRE A VAGA**

Local: Vaga não presencial. Qualquer lugar do Brasil ou do mundo.

Carga horária: Full Time ou Part Time. Horários flexíveis (o que importa são os resultados).

Modalidade: PJ

Resultados esperados: tornar o produto da InEvent mais consistente ao longo do tempo, de forma a ser flexível para diferentes segmentos de eventos e mantendo leve (build atual tem apenas 7.4mb).

Benefícios: Salário (a partir de R$ 1.500,00) + bônus por metas. As metas são calculadas como uma % da receita total da empresa e divididas com o time a partir de 6 meses de trabalho, variando entre 5 a 10 salários.

Início: Fevereiro 2017.

**COMO SE CANDIDATAR**

Basta enviar seus dados usando o formulário abaixo. Este é um processo seletivo contínuo, com data de término indeterminada.

**LINK:** https://ineventapp.recruiterbox.com/jobs/fk0hn7p

**Comment by arturgaleno** [comment]
@davidtcdeveloper Não precisa ser sênior não :smile:, na verdade estamos aceitando qualquer nível que não seja extremamente iniciante. Buscamos pessoas que querem aprender e se desenvolver, e que buscam criar e crescer junto a empresa.

**Comment by davidtcdeveloper** [comment]
Legal @arturgaleno Como a vaga fugiu do template padrão, eu adicionei a label baseada no _Hero_ do título.
Adicionei agora a label _pleno_ também.
