### ISSUE TITLE
[São Paulo-SP] Desenvolvedor Android Sênior | REDE 

### ISSUE THREAD

**Issue by nathaliaambrosio** [androiddevbr/vagas#991]
## Descrição da vaga

- Irá desenvolver sistemas Mobile utilizando a linguagem de programação Kotlin;
- Levantamento de requisitos com os usuários;
- Fazer especificação técnica.

## Local

Escritório São Paulo - Pinheiros

## Benefícios

- O de praxe de contratação CLT + PLR

## Requisitos

Obrigatórios:
- Kotlin;
- JAVA;

Diferenciais:
- ISO 8583 (Diferencial);
- Conhecimento em meios de pagamento (Diferencial).

## Contratação

CLT

## Nossa empresa

Há 20 anos pensamos e agimos em rede. Esta é a melhor maneira de transformar o comércio, movimentar o consumo e inovar.  

Hoje somos mais do que uma empresa de tecnologia. Somos uma rede de pessoas e soluções a favor dos negócios de milhões de brasileiros, sejam grandes empresas ou pequenos empreendedores que surgem todos os dias. 

Compartilhando ideias e oportunidades, inventando e nos reinventando, crescemos junto e multiplicamos nossa capacidade de transformar negócios em todo o país. 

Essa é a nossa Rede.

www.userede.com.br

## Como se candidatar

Por favor envie um email para nathalia.ambrosio@beit.work com seu CV anexado - enviar no assunto: Vaga Android

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
