### ISSUE TITLE
[São Paulo-SP] Desenvolvedor Mobile Sênior

### ISSUE THREAD

**Issue by dimiantoni** [androiddevbr/vagas#992]
## Descrição da vaga

Procuramos desenvolvedores ou desenvolvedoras com amplos conhecimentos Mobile capazes de mover-se livremente entre desenvolvimento Android e iOS que estejam estudando ou utilizando Flutter e React Native em projetos, e dispostos a encararem uma variedade de desafios, Buscamos devs experientes em Mobile, porém estamos trabalhando com Flutter e React Native, portanto é requisito estar estudando as respectivas tecnologias já a algum tempo. Então se você interessa profundamente pelas tecnologias emergentes em mobile e já trabalhou em times realmente ágeis. Entende de Kanban, Scrum, XP e métricas de produtividade. Trabalhou próximo a designers para desenvolver experiências de usuário incríveis queremos conhecer você.

Atividades e Responsabilidades:

- Projetar e implementar aplicativos móveis no Flutter E/OU React Native para Android e IOS;
- Elaborar soluções de arquitetura;
- Manter uma arquitetura coesa em projetos com uma rápida evolução;
- Implementar estratégias de integração simples, extensíveis com tecnologias e serviços de terceiros;
- Construir soluções incrementais que são compatíveis com versões anteriores;
- Produzir código limpo e com boas práticas;
- Colaborar com Product Managers, Designers e Desenvolvedores, tornando-se um integrante importante de um time cross-funcional de desenvolvimento de produto;
- Será um dos responsáveis pela qualidade do código e do produto;
- Desenvolverá novas features e realizará resolução de bugs para os aplicativos de responsabilidade do seu time;
- Trabalhará com as stacks de desenvolvimento mobile, React-Native e Flutter, e tudo o que envolve o ecossistema Android e iOS;

## Local

Escritório São Paulo - Chácara Santo Antônio (Permitido Home Office pelo menos um dia na semana)

## Requisitos

- Sólido background em desenvolvimento de aplicações Mobile;
- Ter tido experiências com Java/Android e/ou Kotlin, Objective C e/ou Swift, Dart e/ou Javascript anteriormente;
- Experiência com apps em produção, monitorar evoluir e atualizar aplicativos nas plataformas Android / iOS;
- Experiência prévia nas linguagens informadas;
- Compreensão do processo completo de criação de aplicações mobile (desde o design, desenvolvimento até a entrega);
- Ter senso de organização, atenção a detalhes e foco;
- Excelente conhecimento em tecnologias de desenvolvimento mobile, em geral (Ferramentas, libs e serviços);
- Seguir às tendências do mercado e que seja capaz de se adaptar rapidamente a novas tecnologias;
- Ter facilidade de trabalhar em times multidisciplinares;

Você trabalhará alocado na sede da startup cliente em SP, em um ambiente de inovação, integrando um time incrível que se orgulha por trabalhar sob uma cultura realmente ágil.

## Contratação

Regime de contratação PJ 
Salário: Até R$18.000

## Nossa empresa

A EZDEVS é uma empresa de Outsourcing e consultoria de software, ajudamos outras empresas a construirem seus produtos digitais. Aqui nós acreditamos em três pilares, liberdade, responsabilidade e busca por conhecimento.

## Como se candidatar

Se aplicar no link da vaga pela plataforma [Programathor](https://programathor.com.br/jobs/8689-desenvolvedor-a-mobile-flutter-react-native)

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
