### ISSUE TITLE
[São Paulo-SP] Android Developer at Fintech GuiaBolso

### ISSUE THREAD

**Issue by iagobyintera** [androiddevbr/vagas#996]
**É tudo do início!** Estamos desenvolvendo um novo produto e para isso buscamos a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Estamos **reduzindo aproximadamente R$250 milhões** em gastos dos usuários por ano.

Atualmente nós trabalhamos principalmente com **Kotlin**, além disso estamos utilizando AWS e ferramentas de CI/CD, com **espaço para aprender muito** também. Essas tecnologias com pessoas de propósito, dispostas e autonomia de ponta a ponta é o que nos faz crescer exponencialmente. A contratação é **regime CLT** com horário flexível e presencial.

**Página da vaga para inscrição:** http://byintera.in/vemserguiabolso (preencher formulário na página)

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
