### ISSUE TITLE
[Porto Alegre-RS ou Remoto] Desenvolvedor Android | Aegro

### ISSUE THREAD

**Issue by pvsilvestrin** [androiddevbr/vagas#997]
## Nosso time de Engenharia de Software

Os engenheiros de mobile da AEGRO estão construindo a próxima geração de apps de gestão agrícola que estão revolucionando a forma que produtores rurais, agrônomos e engenheiros agrícolas conectam, exploram e interagem com as informações do maior setor econômico do Brasil: a agricultura.
Nossos produtos precisam atender um dos cenários mais heterogêneos de clientes de maneira fácil em locais onde a infraestrutura de telecomunicação é precária e as condições de trabalho normalmente são duras.
Estamos buscando engenheiros mobile que queriam criar e manter aplicativos para um  ambiente desafiador, que ajude a construir e pensar um aplicativo que atenda premissas como offline-first, que ajude o produtor a processar e entender milhares de informações, que tenha interesses  em criar aplicativos resilientes e responsivos, que queira trabalhar com recursos como mapas e gráficos, que sabe que o mundo mobile vai muito além de cruds.
Nosso engenheiro mobile também deve estar preparado para ajudar a elaborar soluções 360, que possa ir  desde discutir a arquitetura mobile, a comunicação com o server-side, a pensar na melhor forma de arquitetar os dados, mas que também possa pensar nas melhores soluções para smartphones e smartwatches. O aplicativo da Aegro, diferente da grande maioria dos aplicativos que estão nas app stores, é grande, complexo, com vários recursos, mas com o desafio de transparecer simples e fluido para o usuário.
Como engenheiro de mobile, você irá trabalhar num time ágil com tarefas de múltiplas áreas do produto, desde construir interfaces inovadoras a otimizar a  utilização dos  recursos. Precisamos que nossos engenheiros sejam versáteis, empreendedores e saibam navegar no caos de demandas geradas pelos times de vendas, de suporte e dos próprios clientes: característica inata de uma empresa que cresce na velocidade em que a AEGRO vem crescendo. Como um engenheiro chave dentro de um time pequeno e versátil, você irá projetar, desenvolver, testar, publicar e manter nossos produtos.
Na AEGRO, os engenheiros de software não estão apenas criando o melhor sistema de gestão agrícola possível, eles estão transformando pequenas fazendas em grandes negócios agrícolas, e grandes negócios agrícolas em negócios ágeis e sem burocracia. Se você enxerga o agronegócio brasileiro não como ele é, mas no que um dia ele pode se tornar, você tem um espaço na AEGRO.

## Habilidades e experiências importantes:

Forte conhecimento em linguagem e lógica de programação
Capacidade de pensar de maneira simples para resolver problemas complexos
Desenvolvimento Android em Kotlin ou Java
Ter algum app na AppStore ou Google Play em que teve uma participação significativa no desenvolvimento
Conhecimento de alguma MVVM
Boas práticas de desenvolvimento
Ter experiência com testes unitários
Ter alguma experiência ou vontade de trabalhar com outras tecnologias como iOS ou Flutter

## O que estamos procurando?

Pessoas que gostam de trabalhar em times multidisciplinares e orientados a resultados;
Pessoas com empatia, dispostas a construir uma solução que vai impactar produtores e fazendeiros em seus negócios;
Pessoas com brilho no olho, curiosas e sedentas por novos aprendizados e altamente colaborativas; 

## Será um diferencial se …

Tiver espírito empreendedor
 
## Sobre nós

A AEGRO foi fundada por quatro cientistas da computação e um agrônomo e é uma empresa apaixonada por evoluir o estado-da-arte da tecnologia para a agricultura. Nós contratamos pessoas com um conjunto de habilidades amplo que estão prontas para enfrentar desafios que impactam a vida de mais de cinco milhões de produtores rurais de todo Brasil.
 
## Benefícios

Oportunidade de aprendizados e aprimoramento na área de atendimento ao cliente no modelos SaaS
Plano de Saúde
VR ou VA
VT
Ambiente descontraído e sem “dress code”
Flexibilidade de horário
Home Office uma vez na semana, se quiser
Acesso a plataforma da Alura para cursos de atualização
Oportunidade de realizar 8 horas de treinamento/cursos/capacitações no horário de trabalho por mês
Frutas no escritório diariamente
Massoterapeuta para dar aquela relaxada
Localização privilegiada, estamos em frente ao Parque da Redenção

## Como se candidatar

http://bit.ly/36vqTSZ

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
