### ISSUE TITLE
[Rio de Janeiro] Android Develop | Globo.com

### ISSUE THREAD

**Issue by carloshpdoc** [androiddevbr/vagas#998]
## Descrição da vaga

Venha trabalhar com a plataforma de apps dos produtos da Globo.com.

Os nossos desafios vão do negócio ao técnico, em um time multi-disciplinar. Projetos componentizados, processos de automatização, desafios de escalabilidade! E sempre buscando melhorar a qualidade de vida dos nossos projetos e tornar fácil o uso da nossa plataforma!

E, no fim das contas, o mais importante: sempre pensar no nosso usuário final! Usuário com aparelhos high-end e low-end, pensando em como podemos entregar pequenas funcionalidades com a melhor experiência possível para todos.

## Local

Esta vaga é para o nosso escritório no Rio de Janeiro, Barra da Tijuca, porém submissões de todo o Brasil são aceitas. A globo.com entende as dificuldades de mudança de cidade, e oferecemos um pacote de benefícios especial para pessoas de fora do estado. 

## Oferecemos

 - Salário e benefícios compatíveis com o mercado.
 - Possibilidade de afetar positivamente a vida de milhares de usuários.
 - Espaço e autonomia pra você deixar a sua marca.
 - Ambiente descontraído e um time incrível formado por pessoas apaixonadas pelo que fazem e referências em suas áreas de atuação.

## Requisitos

Obrigatórios
- Ter sólidos conhecimentos e habilidades em algoritmos e estruturas de dados;
- Ter domínio de engenharia de software, princípios, boas práticas e padrões de arquitetura;
- Ter experiência com Desenvolvimento de Apps;
- Ter pelo menos 2 anos de experiência com Kotlin ou Swift;
- Ter conhecimento de práticas de XP (TDD, pair programming, refactoring, continuous integration, etc);

Desejáveis
- Conhecimento da linguagem Java/Objective-C;
- Ter experiência com métodos ágeis e práticas de engenharia ágil;
- Conhecer e ter experiência com testes unitários, de aceitação, mocks, etc;
- Saber trabalhar com ferramentas de controle de versão.

## Contratação

CLT 

## Nossa empresa

A Globo.com é uma empresa de soluções digitais para o Grupo Globo, maior grupo de mídia da América Latina. Nossas marcas digitais estão entre as maiores do Brasil, reconhecidas pela qualidade e liderança de audiência em seus segmentos. G1, Globoesporte.com, Gshow, Cartola, Globoplay, Globosatplay, são exemplos de um portfólio diverso presente na vida de milhões de pessoas que buscam informação, diversão e cultura.

Com foco no desenvolvimento de produtos, visando a melhor experiência de consumo, interação e relacionamento com os nossos usuários, contamos com um time de referência no mercado de Tecnologia.

Possuímos uma das mais modernas infraestruturas de distribuição de conteúdo do Brasil. Todas as nossas opiniões, decisões e ações se sustentam em nossos valores. Nossa Essência é composta por: Paixão por Comunicação | Brasilidade | Atitude Otimista | Talento e Liderança | Respeito à Diversidade | Qualidade e Inovação | Estética | Crescer Juntos.

Temos escritórios no Rio de Janeiro, Porto Alegre e um núcleo de Tecnologia em São Paulo. Aqui ideias, competência e inovação fazem toda a diferença. Valorizamos a diversidade e o desenvolvimento pessoal e profissional. Junte-se a nós e traga o seu talento!

## Como se candidatar

Pode ser pelo nosso canal de vagas [talentos.globo.com](https://talentos.globo.com/#/oportunidades/desenvolvedor-a-android-ou-i-os-plataforma-de-apps/mp0qdej). Também pode me enviar uma mensagem pelo slack da comunidade Android dev br, meu user é: @carloshpc

**Comment by jpventura** [comment]
Essa vaga foi fechada devido inatividade.

Caso a vaga ainda não tenha sido preenchida, basta comentar _**Vaga ainda está aberta**_.
